import test from 'node:test';import assert from 'node:assert/strict';
import {StateStore} from '../src/state.ts';import {PilotKnowledge} from '../src/pilot/knowledge.ts';import {ConnectionService,ConnectionRegistry,maintainedReadAdapters,OfflineTransport} from '../src/pilot/connections/index.ts';import {createConnectionTransport} from '../src/pilot/connections/live-transport.ts';
const setup=()=>{const store=new StateStore(':memory:'),knowledge=new PilotKnowledge(store),company=knowledge.createCompany({name:'Test connection owner',goal:'Read a consented document'}),service=new ConnectionService(store,knowledge,new ConnectionRegistry(maintainedReadAdapters())),c=service.beginConfiguration({businessId:company.id,provider:'google_workspace',credentialReference:{kind:'owner_vault',id:'fixture-reference'},capabilityIds:['drive_documents_read'],configuration:{maxFiles:1,maxPages:1}});return {store,knowledge,company,service,c};};
const consent={grantedAt:new Date().toISOString(),grantedBy:'explicit-test-owner',purpose:'Read test document',scopes:['https://www.googleapis.com/auth/drive.readonly']};
test('a live transport cannot relabel fixture provenance or import one account into a different business',async()=>{
 const x=setup(),other=x.knowledge.createCompany({name:'Different owner',goal:'Read only my own records'}),b=x.service.beginConfiguration({businessId:other.id,provider:'google_workspace',credentialReference:{kind:'owner_vault',id:'different-account'},capabilityIds:['drive_documents_read']});
 x.service.grantConsent(x.c.id,consent);x.service.grantConsent(b.id,consent);let reads=0;
 const port=createConnectionTransport(x.service,x.c.id,{resolveAccessToken:async()=>{reads++;throw Error('must not read a credential');},fetch:async()=>{reads++;throw Error('must not fetch');}});
 await assert.rejects(x.service.sync(b.id,port),/LIVE_TRANSPORT_BINDING/);await assert.rejects(x.service.sync(b.id,{kind:'live',request:async()=>{reads++;return {status:200,body:{files:[]}};}}),/LIVE_TRANSPORT_BINDING/);assert.equal(reads,0);assert.equal(x.service.get(b.id).readiness,'configured');x.store.close();
});
test('interrupted source linking never exposes uncommitted connection evidence and retry reuses exact retained bytes',async()=>{
 const x=setup();x.service.grantConsent(x.c.id,consent);
 const port=new OfflineTransport([{matches:r=>r.path==='/drive/v3/files',response:{status:200,body:{files:[{id:'doc2',name:'Interrupted policy',mimeType:'application/vnd.google-apps.document'}]}}},{matches:r=>r.path.includes('/documents/'),response:{status:200,body:{body:{content:[{textRun:{content:'Retained policy awaiting its connection binding.'}}]}}}}]);
 const put=x.store.put.bind(x.store);let crash=true;x.store.put=((kind:string,...args:any[])=>{if(kind==='pilot-connection-source'&&crash){crash=false;throw Error('test crash before connection source link');}return (put as any)(kind,...args);}) as any;
 await assert.rejects(x.service.sync(x.c.id,port),/test crash/);
 const original=x.knowledge.sources(x.company.id).find(s=>s.title==='Interrupted policy')!;assert.equal(original.permission,'excluded');assert.equal(original.origin?.kind,'connection-read');
 x.store.put=put;await x.service.sync(x.c.id,port);const restored=x.knowledge.sources(x.company.id).filter(s=>s.title==='Interrupted policy');assert.equal(restored.length,1);assert.equal(restored[0].id,original.id);assert.equal(restored[0].permission,'worker');
 x.service.grantConsent(x.c.id,{...consent,expiresAt:'2000-01-01T00:00:00Z'});assert.equal(x.knowledge.sources(x.company.id).find(s=>s.id===original.id)?.permission,'excluded');x.store.close();
});
test('trusted host maps exact official endpoint, bounds requests and never persists a token or auth header',async()=>{const x=setup();let resolves=0,calls=0;const fakeSecret='explicit-test-token-never-a-real-credential';const port=createConnectionTransport(x.service,x.c.id,{maxRequests:1,resolveAccessToken:async()=>{resolves++;return fakeSecret;},fetch:async(url,init)=>{calls++;assert.equal(String(url),'https://www.googleapis.com/drive/v3/files');assert.equal((init!.headers as any).Authorization,'Bearer '+fakeSecret);assert.equal(init!.redirect,'error');return new Response(JSON.stringify({files:[]}),{status:200,headers:{'content-type':'application/json','x-request-id':'fixture-read-id'}});}});const req={provider:'google_workspace' as const,method:'GET' as const,path:'/drive/v3/files',capabilityIds:['drive_documents_read']};await assert.rejects(port.request(req),/AUTHORITY/);assert.equal(resolves,0);x.service.grantConsent(x.c.id,consent);await port.request(req);await assert.rejects(port.request(req),/REQUEST_CAP/);assert.equal(calls,1);const persisted=JSON.stringify(x.store.db.prepare('SELECT body FROM entities').all());assert.ok(!persisted.includes(fakeSecret));assert.ok(!persisted.includes('Authorization'));assert.ok(persisted.includes('fixture-read-id'));x.store.close();});
test('central knowledge projection blocks every retired revision, pending cached job context and expired consent',async()=>{const x=setup();x.service.grantConsent(x.c.id,consent);const sync=async(text:string)=>x.service.sync(x.c.id,new OfflineTransport([{matches:r=>r.path==='/drive/v3/files',response:{status:200,body:{files:[{id:'doc1',name:'Rules',mimeType:'application/vnd.google-apps.document'}]}}},{matches:r=>r.path.includes('/documents/'),response:{status:200,body:{body:{content:[{textRun:{content:text}}]}}}}]));await sync('First supported policy');const first=x.service.sources(x.c.id)[0].knowledgeSourceId;await sync('Second supported policy');const second=x.service.sources(x.c.id).find(s=>!s.supersededAt)!.knowledgeSourceId;assert.equal(x.knowledge.selectedSources(x.company.id).some(s=>s.id===first),false);assert.ok(x.knowledge.selectedSources(x.company.id).some(s=>s.id===second));x.service.revoke(x.c.id,'Owner withdrew access');assert.ok(!x.knowledge.selectedSources(x.company.id).some(s=>[first,second].includes(s.id)));assert.equal(x.knowledge.sources(x.company.id).filter(s=>[first,second].includes(s.id)).length,2);x.store.close();});
