import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { PilotService } from '../src/pilot/service.ts';
import { servePilot } from '../src/pilot/server.ts';
import { launchCheckBrowser } from '../src/portfolio/preview.ts';

test('real-shaped outcome graph and source-bound development controls preserve current artifacts, correction binding, and authority boundaries', async () => {
  const root=mkdtempSync(join(tmpdir(),'pilot-connected-ui-')),service=new PilotService(root),server=servePilot({service,port:0}),origin=await server.ready,browser=await launchCheckBrowser(),context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),page=await context.newPage(),company=service.createBusiness({name:'Connected UI business',website:'',goal:'Use one corrected local artifact to prepare a grounded procedure candidate.',notes:'Browser fixture only.'}),base=service.view(company.id);
  const source={id:'source-current',title:'Current operating procedure',text:'The current procedure requires owner review before a local offer is used. The correction revealed that this checkpoint needs an explicit checklist.',permission:'worker',validUntil:null,observedAt:'2026-09-14T12:00:00.000Z',rights:'Fixture evidence',kind:'text'};
  const correctedTask={id:'task-corrected',title:'Offer clarification packet',status:'completed',correctionHistory:[{id:'correction-1',taskId:'task-corrected',artifactHash:'artifact-current',instruction:'Add the owner-review checklist before the final local offer.',assisted:false,at:'2026-09-14T12:01:00.000Z'}]};
  const outcome={id:'outcome-current',objective:'Prepare an owner-reviewed offer clarification.',autonomy:'prepare_supported_work',state:'ready',nextAction:'Review the current artifact before any external use.',plan:{decision:'prepare',evidenceRefs:[{sourceId:source.id,quote:'owner review'}],tasks:[]},graph:[{id:'current-node',title:'Current offer packet',status:'completed',current:true,assignment:{worker:'Offer worker'}},{id:'stale-node',title:'Earlier offer packet',status:'stale',current:false,assignment:{worker:'Offer worker'}}],artifacts:[{nodeId:'current-node',artifactId:'artifact-current',hash:'artifact-current',title:'Current offer packet',current:true},{nodeId:'stale-node',artifactId:'artifact-stale',hash:'artifact-stale',title:'Earlier offer packet',current:false}],calls:{admitted:4,remaining:8,repairAllocated:0},corrections:[]};
  const developmentWorker={jobId:'functional-project-current',responsibilities:['A bounded local application prepared from the retained company evidence.'],procedureScope:{capability:'software.build',population:'company-only'},evidenceAccess:{evidenceHash:'a8cc253e4c81b4d99b7aa098cd3f6fe9a6f43398839559f91a4b8aa23a20bb1e'}};
  let candidate:any=null,prepareBody:any=null,fixtureBody:any=null,operatingDemoBody:any=null,displayedMode:'owner'|'fixture'='owner';
  const view=(mode:'owner'|'fixture'='owner')=>({...base,business:{...company,mode},sources:[source],tasks:[correctedTask],corrections:[...correctedTask.correctionHistory],operatingOutcomes:[outcome],learning:[{id:'historical-learning',status:'archived',title:'Earlier procedure comparison',summary:'Preserved historical record.'}],development:{report:{definitions:[developmentWorker],observations:[],candidates:candidate?[candidate]:[],comparisons:[],runtime:{status:'unavailable_pending_trusted_signed_factory',reason:'No signed comparison route is available.'}}}});
  const external:string[]=[],errors:string[]=[];page.on('pageerror',(error:Error)=>errors.push(error.message));await context.route('**/*',(route:any)=>new URL(route.request().url()).origin===origin?route.continue():(external.push(route.request().url()),route.abort()));
  try {
    await page.route(origin+'/api/**',async(route:any)=>{const request=route.request(),url=new URL(request.url());if(url.pathname==='/api/session')return route.fulfill({json:{csrf:'connected-ui-csrf'}});if(url.pathname==='/api/state')return route.fulfill({json:view(displayedMode)});if(url.pathname==='/api/operating-demo'){operatingDemoBody=request.postDataJSON();return route.fulfill({json:{view:view('fixture'),result:{id:company.id}}});}if(url.pathname==='/api/development/prepare'){prepareBody=request.postDataJSON();candidate={id:'candidate-current',status:'candidate_prepared',qualification:'experimental_unqualified',diagnosis:{rationale:prepareBody.rationale},procedureAddition:prepareBody.procedureAddition};return route.fulfill({json:{view:view(displayedMode),result:{candidateId:candidate.id}}});}if(url.pathname==='/api/development/fixture'){fixtureBody=request.postDataJSON();return route.fulfill({json:{view:view('fixture'),result:{candidateId:candidate.id,status:'fixture_comparison_prepared'}}});}return route.fulfill({status:404,json:{error:'UNEXPECTED_ROUTE'}});});
    await page.goto(origin+'/#outcomes');await page.evaluate(id=>localStorage.setItem('midas-pilot-business',id),company.id);await page.reload();await page.getByText('Current offer packet',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Request correction'}).count(),1,'only the current artifact can be corrected');assert.equal(await page.getByText(/Earlier: Earlier offer packet/).count(),1);assert.equal(await page.getByText('4 admitted · 8 remaining · 0 repair allocated',{exact:true}).count(),1);
    await page.goto(origin+'/#learning');await page.getByRole('button',{name:'Prepare development candidate'}).first().click();await page.getByLabel('What consequence did the correction reveal?').fill('The owner could not consistently verify the review checkpoint before using the local offer.');await page.getByLabel('Why might that be the cause?').fill('The corrected artifact and current procedure show that the checklist was absent from the prior workflow.');await page.getByLabel('Alternative explanation one').fill('The owner may need a clearer source selection, not a new procedure.');await page.getByLabel('Alternative explanation two').fill('The correction may be specific to this one offer packet.');await page.getByLabel('Reusable material title').fill('Owner review checklist');await page.getByLabel('Reusable material content').fill('Before use, confirm the offer references the current source and owner review checkpoint.');await page.getByLabel('Material provenance').fill('Prepared from the retained current operating procedure for this local fixture.');await page.getByLabel('I have permission to reuse this learning material').check();await page.getByLabel('Proposed procedure addition').fill('Require a visible owner-review checklist before presenting any local offer for inspection.');await page.getByLabel('Assistance informed this candidate').check();await page.getByRole('button',{name:'Prepare development candidate'}).last().click();await page.getByText('Comparison pending authority',{exact:true}).waitFor();
    assert.deepEqual(prepareBody,{businessId:company.id,taskId:'task-corrected',sourceId:source.id,quote:source.text,consequence:'The owner could not consistently verify the review checkpoint before using the local offer.',cause:'missing_knowledge',rationale:'The corrected artifact and current procedure show that the checklist was absent from the prior workflow.',alternatives:['The owner may need a clearer source selection, not a new procedure.','The correction may be specific to this one offer packet.'],material:{title:'Owner review checklist',content:'Before use, confirm the offer references the current source and owner review checkpoint.',provenance:'Prepared from the retained current operating procedure for this local fixture.',rights:'reusable'},procedureAddition:'Require a visible owner-review checklist before presenting any local offer for inspection.',assisted:true});assert.equal(await page.getByText(/software build/).count(),1);assert.equal(await page.getByText('[object Object]',{exact:true}).count(),0);assert.equal(await page.locator('.learning-entry .small-copy').filter({hasText:'experimental_unqualified'}).count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    displayedMode='fixture';await page.reload();await page.getByRole('button',{name:'Run labeled fixture comparison'}).click();await page.waitForFunction(()=>document.querySelector('#toast')?.textContent?.includes('Labeled fixture comparison requested'));assert.deepEqual(fixtureBody,{businessId:company.id,candidateId:'candidate-current'});await page.goto(origin+'/#archive');await page.getByRole('button',{name:'Explore connected service journey'}).click();await page.waitForFunction(()=>document.querySelector('#toast')?.textContent?.includes('labeled offline connected journey'));assert.deepEqual(operatingDemoBody,{fixture:'service'});assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  } finally { await browser.close();await server.close();service.store.close(); }
});
