import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {PilotService} from '../src/pilot/service.ts';
import {servePilot} from '../src/pilot/server.ts';
import {keypair} from '../src/experiment/config.ts';
import {prepareOutcomeJourneyAuthorization,signOutcomeJourneyProposal,loadAuthorizedOutcomeJourney} from '../src/pilot/outcome-journey-authorized.ts';
import {commercialCases,fixtureCommercialOutput} from '../src/pilot/intelligence-fixtures.ts';
import {fixturePilotWorker} from '../src/pilot/fixtures-execution.ts';

const owner=async(origin:string)=>{const r=await fetch(origin+'/api/session'),body=await r.json() as any,cookie=r.headers.get('set-cookie')!.split(';')[0];return {post:async(path:string,payload:any)=>{const x=await fetch(origin+path,{method:'POST',headers:{cookie,origin,'content-type':'application/json','x-csrf-token':body.csrf},body:JSON.stringify(payload)});return {status:x.status,body:await x.json() as any};}};};
const plan=(source:any)=>({decision:'prepare',rationale:'Prepare one bounded owner packet.',strongestAlternative:'Ask the owner for more current evidence.',blockingConditions:[],evidenceRefs:[{sourceId:source.id,quote:source.text}],tasks:[{id:'packet',family:'response-packet',title:'Owner packet',outcome:'Prepare a reviewable local packet',details:'Keep commercial outcomes unknown.',dependsOn:[],sourceIds:[source.id],competencies:['evidence-synthesis'],reasonForWorker:'A bounded worker can prepare it.',calls:3}],successEvidence:['Authenticated local readback.'],limitsOfInference:'Offline signed transport verifies mechanics only.'});

test('owner HTTP approved journey runs once through its injected signed mock runner',async()=>{
const root=mkdtempSync(join(tmpdir(),'journey-service-')),service=new PilotService(root,{publicReader:{kind:'public'}}),sample=commercialCases.service,company=service.knowledge.createCompany({name:sample.name,website:sample.website,goal:sample.goal,notes:sample.notes,mode:'fixture'}),sources=sample.pages.map(page=>service.knowledge.addSource(company.id,{title:page.title,text:page.text,kind:'website',rights:'Synthetic fixture',observedAt:new Date().toISOString()})),source=sources[0];service.discovery.start(company.id,{website:sample.website,limits:{maxDecisions:6}});const mandate=service.operatingOutcomes.create(company.id,{objective:'Prepare a source-grounded owner packet',autonomy:'prepare_supported_work',allowedFamilies:['response-packet'],maxCalls:18,repairReserve:7}),services={outcomes:service.operatingOutcomes,intelligence:service.intelligence,discovery:service.discovery},prepared=prepareOutcomeJourneyAuthorization(services,{root,id:'journey-034-http',outcomeId:mandate.id,projectId:'proj_JOURNEY_HTTP',credentialFile:null,expiresAt:new Date(Date.now()+60000).toISOString(),countUncertaintyMinor:271,mode:'mock'}),keys=keypair(),signed=signOutcomeJourneyProposal(services,root,{proposal:prepared.proposal,expectedHash:prepared.proposalHash,principal:'ephemeral-http-owner',approvalReference:'Explicit mock journey HTTP acceptance.',...keys});
 let counts=0,creates=0;const terminal=new Map<string,any>();const transport=(async(url:any,init:any)=>{if(String(url).endsWith('/input_tokens')){counts++;return Response.json({object:'response.input_tokens',input_tokens:100});}if(init.method==='POST'){creates++;const input=JSON.parse(JSON.parse(init.body).input),value=creates===1?{action:'finish',url:null,sourceId:null,reason:'Synthetic discovery finishes.',unresolved:[]}:creates===2?fixtureCommercialOutput('service',input.context.sources):creates===3?plan(input.context.sources[0]):(await fixturePilotWorker().run({request:{context:input.context}} as any)).output,id='resp_http_'+creates;terminal.set(id,{id,model:'gpt-6-astra',status:'completed',service_tier:'default',background:true,store:true,usage:{input_tokens:100,output_tokens:100},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(value)}]}]});return Response.json({id,model:'gpt-6-astra',status:'queued',service_tier:'default',background:true,store:true,usage:null,output:[]});}assert.equal(init.method,'GET');return Response.json(terminal.get(String(url).split('/').at(-1)!));}) as typeof fetch;
 const runner=loadAuthorizedOutcomeJourney(services,root,{testing:{envelope:signed.envelope,trustedPublicKey:keys.publicKey,transport}});(service as any).authorizedJourney=runner;
 const app=servePilot({service,port:0}),origin=await app.ready;try{const c=await owner(origin),denied=await c.post('/api/outcome/run-approved',{businessId:'wrong-business',outcomeId:mandate.id});assert.equal(denied.status,400);assert.equal(creates,0);const unsigned=service.operatingOutcomes.create(company.id,{objective:'Unsigned separate outcome',autonomy:'prepare_supported_work',allowedFamilies:['response-packet'],maxCalls:8,repairReserve:3}),unsignedDenied=await c.post('/api/outcome/run-approved',{businessId:company.id,outcomeId:unsigned.id});assert.equal(unsignedDenied.status,403);assert.equal(creates,0);
 const started=await c.post('/api/outcome/run-approved',{businessId:company.id,outcomeId:mandate.id});assert.equal(started.status,202);await service.settle();const view=service.view(company.id),outcome=view.operatingOutcomes.find((x:any)=>x.id===mandate.id);assert.equal(outcome.state,'completed');assert(view.tasks.some((x:any)=>x.artifact?.current));assert.equal(view.accounting.providerCalls,0);assert.equal(counts,5);assert.equal(creates,5);const again=await c.post('/api/outcome/run-approved',{businessId:company.id,outcomeId:mandate.id});assert.equal(again.status,202);await service.settle();assert.equal(creates,5);assert.equal(counts,5);
 }finally{await app.close();service.store.close();rmSync(root,{recursive:true,force:true});}
});
