import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,realpathSync,rmSync} from 'node:fs';
import {dirname,isAbsolute,join,relative,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {StateStore} from '../src/state.ts';
import {hash} from '../src/contracts.ts';
import {keypair,signed,verified} from '../src/experiment/config.ts';
import {PilotKnowledge} from '../src/pilot/knowledge.ts';
import {PilotExecution} from '../src/pilot/execution.ts';
import {PilotOutcomes} from '../src/pilot/outcomes.ts';
import {fixturePilotWorker} from '../src/pilot/fixtures-execution.ts';
import {prepareOutcomeAuthorization,signOutcomeProposal,loadAuthorizedOutcome} from '../src/pilot/outcome-authorized.ts';

const packageRoot=resolve(dirname(fileURLToPath(import.meta.url)),'..');
function plan(source:any,dependent=false){
 const tasks:any[]=[{id:'foundation',family:'response-packet',title:'Owner response foundation',outcome:'Give the owner a sourced recommendation and review step',details:'Preserve pricing uncertainty and owner approval.',dependsOn:[],sourceIds:[source.id],competencies:['evidence-synthesis'],reasonForWorker:'One bounded generalist can prepare and check this local packet.',calls:4}];
 if(dependent)tasks.push({id:'dependent',family:'response-packet',title:'Dependent operating packet',outcome:'Turn the checked foundation into a second locally reviewable packet',details:'Carry the source and review obligation through the dependency.',dependsOn:['foundation'],sourceIds:[source.id],competencies:['evidence-synthesis'],reasonForWorker:'The same bounded profile can consume the checked upstream artifact.',calls:4});
 return {decision:'prepare',rationale:'Prepare the smallest source-grounded local graph; no commercial effect is claimed.',strongestAlternative:'Reject and ask the owner for current private economics.',blockingConditions:[],evidenceRefs:[{sourceId:source.id,quote:source.text}],tasks,successEvidence:['Current deterministic checks and authenticated local readback.'],limitsOfInference:'Offline signed transport fixture tests mechanics only; usefulness and economic impact remain unmeasured.'};
}
async function setup(options:{dependent?:boolean;terminal?:'failed'|'incomplete';queued?:boolean;commercial?:boolean}={}){
 const root=mkdtempSync(join(tmpdir(),'midas-outcome-034-')),store=new StateStore(join(root,'state.sqlite')),knowledge=new PilotKnowledge(store),company=knowledge.createCompany({name:'Signed outcome fixture',website:'',goal:'Prepare a useful source-grounded owner response',notes:'Synthetic test business; prices and customer results are unknown.',mode:'fixture'}),source=knowledge.addSource(company.id,{title:'Owner policy',text:'The example service requires owner review before pricing. No verified customer result is available.',kind:'notes',rights:'Synthetic development fixture',observedAt:new Date().toISOString()}),execution=new PilotExecution(store,{root}),outcomes=new PilotOutcomes(store,execution);if(options.commercial)store.transaction(()=>store.put('pilot-intelligence',company.id,{businessId:company.id,contextHash:outcomes.intelligence.contextHash(company.id),status:'proposal_ready',executiveSummary:'Synthetic commercial proposal retained only as an unverified suggestion.',opportunities:[],provenance:'fixture'},null));const mandate=outcomes.create(company.id,{objective:'Prepare a useful source-grounded owner response',autonomy:'prepare_supported_work',allowedFamilies:['response-packet'],maxCalls:18,repairReserve:7}),prepared=prepareOutcomeAuthorization({outcomes},{root,directory:join(root,'proposal'),implementationRoot:packageRoot,id:'outcome-034-test',outcomeId:mandate.id,projectId:'proj_OUTCOME_OFFLINE_TEST',credentialFile:null,expiresAt:new Date(Date.now()+3600000).toISOString(),countUncertaintyMinor:301,mode:'mock'}),keys=keypair(),approved={...prepared.proposal,approvedBy:'ephemeral-outcome-test-owner',approvalReference:'Explicit ephemeral mock-only acceptance; no provider authority or expenditure.'},envelope=signed(approved,keys.privateKey);
 let counts=0,creates=0,reads=0,loseReads=false,sequence=0;const terminals=new Map<string,any>();
 const transport=(async(url:any,init:any)=>{const target=String(url);if(target.endsWith('/input_tokens')){counts++;return Response.json({object:'response.input_tokens',input_tokens:100});}if(init.method==='POST'){creates++;assert.equal(target,'https://api.openai.com/v1/responses');const body=JSON.parse(init.body);assert.equal(body.model,'gpt-6-astra');assert.equal(body.reasoning.effort,'max');assert.equal(body.background,true);assert.equal(body.store,true);const input=JSON.parse(body.input),output=input.context.mandate?plan(source,options.dependent):(await fixturePilotWorker().run({request:{context:input.context}} as any)).output,id='resp_outcome_mock_'+(++sequence),base={id,model:'gpt-6-astra',status:options.terminal??'completed',service_tier:'default',background:true,store:true,usage:{input_tokens:100,output_tokens:100},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(output)}]}]};
  const terminal=options.terminal?{...base,usage:null,output:[],error:{code:'mock_terminal',message:'Explicit offline terminal fixture.'}}:base;terminals.set(id,terminal);return options.queued||loseReads?Response.json({id,model:'gpt-6-astra',status:'queued',service_tier:'default',background:true,store:true,usage:null,output:[]}):Response.json(terminal);}
  if(init.method==='GET'){reads++;if(loseReads)throw Error('Explicit lost same-ID mock retrieval');const id=target.split('/').at(-1)!;assert(terminals.has(id));return Response.json(terminals.get(id));}assert.fail('Mock transport has no fallthrough: '+init.method+' '+target);}) as typeof fetch;
 const load=()=>loadAuthorizedOutcome({outcomes},root,{testing:{envelope,trustedPublicKey:keys.publicKey,transport}});
 return {root,store,knowledge,company,source,execution,outcomes,mandate,prepared,keys,envelope,transport,load,stats:()=>({counts,creates,reads}),loseReads:(value:boolean)=>{loseReads=value;},close(){store.close();const exact=realpathSync(root),rel=relative(realpathSync(tmpdir()),exact);assert(rel&&!rel.startsWith('..')&&!isAbsolute(rel));rmSync(exact,{recursive:true,force:true});}};
}

test('unsigned factory creates reviewable exact authority and an ephemeral signed mock runs only its admitted graph',async()=>{const f=await setup();try{
 assert.equal(f.prepared.summary.approved,false);assert.equal(f.prepared.summary.providerRequests,0);assert.equal(f.prepared.summary.credentialRead,false);assert.equal(f.prepared.proposal.outcome.plannerCalls,1);assert.equal(f.prepared.proposal.outcome.profiles.length,1);assert.equal(f.prepared.proposal.limits.allocations.find((a:any)=>a.value==='outcome-repair').attempts,7);assert.equal(f.stats().creates,0);
 assert.throws(()=>loadAuthorizedOutcome({outcomes:f.outcomes},f.root,{testing:{envelope:{payload:'arbitrary grant string',signature:'bad'},trustedPublicKey:f.keys.publicKey,transport:f.transport}}),/SIGNATURE_INVALID/);assert.deepEqual(f.stats(),{counts:0,creates:0,reads:0});
 const runner=f.load();await runner.plan();const done=await runner.run();assert.equal(done.state,'completed',JSON.stringify(done));assert.equal(done.graph.length,1);assert(done.artifacts[0].current);assert.equal(runner.totals().stageUsage['outcome-planner'].used,1);assert.equal(runner.totals().stageUsage['outcome-primary'].used,2);assert.equal(runner.totals().providerRequests,0);assert.deepEqual(f.stats(),{counts:3,creates:3,reads:0});
 const bindings=f.store.db.prepare("SELECT body FROM entities WHERE kind='pilot-authorized-outcome-task'").all().map((r:any)=>JSON.parse(String(r.body)));assert.equal(bindings.length,1);assert.match(bindings[0].definitionHash,/^[a-f0-9]{64}$/);await f.load().run();assert.deepEqual(f.stats(),{counts:3,creates:3,reads:0});
 }finally{f.close();}});

test('correction and every regenerated dependent remain linked to the finite repair reserve',async()=>{const f=await setup({dependent:true});try{const runner=f.load();await runner.plan();let result=await runner.run();assert.equal(result.state,'completed');const originalIds=result.graph.map((n:any)=>n.taskId),artifact=f.execution.artifact(f.company.id,originalIds[0]);runner.correct({nodeId:'foundation',artifactHash:artifact.hash,instruction:'Make owner review explicit before any price or customer-facing use.',repairCalls:3,assisted:true});assert.equal(f.outcomes.get(f.mandate.id).repairAllocated,7);result=await runner.run();assert.equal(result.state,'completed',JSON.stringify(result));assert.equal(f.outcomes.get(f.mandate.id).taskIds.length,4);assert(originalIds.every(id=>f.outcomes.get(f.mandate.id).taskIds.includes(id)));assert.equal(result.graph[0].generation,1);assert.equal(result.graph[1].generation,1);assert.equal(runner.totals().stageUsage['outcome-repair'].used,4);assert(runner.totals().callsUsed<=runner.totals().callLimit);assert.throws(()=>runner.correct({nodeId:'foundation',artifactHash:f.execution.artifact(f.company.id,result.graph[0].taskId).hash,instruction:'A second correction cannot refill the exhausted reserve.',repairCalls:3,assisted:true}),/REPAIR_RESERVE_INSUFFICIENT/);
 }finally{f.close();}});

test('expired signed authority refuses before count or response creation',async()=>{const f=await setup();try{
 const expired=signed({...f.prepared.proposal,expiresAt:new Date(Date.now()-1000).toISOString(),approvedBy:'ephemeral-outcome-test-owner',approvalReference:'Expired mock grant for refusal coverage only.'},f.keys.privateKey);
 const runner=loadAuthorizedOutcome({outcomes:f.outcomes},f.root,{testing:{envelope:expired,trustedPublicKey:f.keys.publicKey,transport:f.transport}});
 await assert.rejects(()=>runner.plan(),/OUTCOME_GRANT_EXPIRED/);assert.deepEqual(f.stats(),{counts:0,creates:0,reads:0});
 }finally{f.close();}});

test('explicit fixture signing writes one pinned envelope without reading credentials or granting plaintext access',async()=>{const f=await setup();try{
 const installed=signOutcomeProposal({outcomes:f.outcomes},f.root,{proposal:f.prepared.proposal,expectedHash:f.prepared.proposalHash,principal:'ephemeral-outcome-test-owner',approvalReference:'Explicit fixture-only signature installation.',...f.keys});
 assert.equal(installed.credentialRead,false);assert.equal(installed.providerRequests,0);assert.equal(verified(JSON.parse(readFileSync(join(f.root,'pilot.outcome.authorization.json'),'utf8')),f.keys.publicKey).approvedBy,'ephemeral-outcome-test-owner');assert.deepEqual(f.stats(),{counts:0,creates:0,reads:0});
 assert.throws(()=>signOutcomeProposal({outcomes:f.outcomes},f.root,{proposal:f.prepared.proposal,expectedHash:f.prepared.proposalHash,principal:'ephemeral-outcome-test-owner',approvalReference:'A repeated envelope must not overwrite the pinned authority.',...f.keys}),/OUTCOME_EXACT_APPROVAL_HASH/);
 }finally{f.close();}});

test('a signed stale source-code binding is refused before a count or response call',async()=>{const f=await setup();try{
 const proposal=structuredClone(f.prepared.proposal);proposal.outcome.implementationFiles[0].sha256=hash('different-loaded-source');const envelope=signed({...proposal,approvedBy:'ephemeral-outcome-test-owner',approvalReference:'Fixture stale-code refusal.'},f.keys.privateKey);
 assert.throws(()=>loadAuthorizedOutcome({outcomes:f.outcomes},f.root,{testing:{envelope,trustedPublicKey:f.keys.publicKey,transport:f.transport}}),/OUTCOME_AUTHORIZED_CODE_CHANGED/);assert.deepEqual(f.stats(),{counts:0,creates:0,reads:0});
 }finally{f.close();}});

test('same response ID is retrieved after interruption, then stale owner input prevents its use without another admission',async()=>{const f=await setup({queued:true});try{f.loseReads(true);await assert.rejects(()=>f.load().plan(),/MODEL|BACKGROUND|RESULT/);assert.deepEqual(f.stats(),{counts:1,creates:1,reads:3});f.knowledge.addSource(f.company.id,{title:'Later owner constraint',text:'A new owner constraint requires a fresh plan.',kind:'notes',rights:'Synthetic fixture',observedAt:new Date().toISOString()});f.loseReads(false);await assert.rejects(()=>f.load().plan(),/OUTCOME_CONTEXT_CHANGED/);assert.deepEqual(f.stats(),{counts:1,creates:1,reads:4});assert.equal(f.store.get('pilot-outcome-plan-attempt',f.mandate.id).state,'stale_input');assert.equal(f.outcomes.get(f.mandate.id).plan,null);await assert.rejects(()=>f.load().plan(),/OUTCOME_CONTEXT_CHANGED/);assert.deepEqual(f.stats(),{counts:1,creates:1,reads:4});
 }finally{f.close();}});

test('terminal provider failure remains distinct from unknown and cannot fall through or be inferred again',async()=>{const f=await setup({terminal:'failed'});try{await assert.rejects(()=>f.load().plan(),/MODEL_RESPONSE_FAILED/);assert.deepEqual(f.stats(),{counts:1,creates:1,reads:0});assert.equal(f.store.get('pilot-outcome-plan-attempt',f.mandate.id).state,'terminal_failed');await assert.rejects(()=>f.load().plan(),/MODEL_RESPONSE_FAILED/);assert.deepEqual(f.stats(),{counts:1,creates:1,reads:0});assert.equal(f.load().totals().stageUsage['outcome-planner'].used,1);
 }finally{f.close();}});

test('fresh generated task definition and local profile are checked before any worker admission',async()=>{const f=await setup();try{const runner=f.load();await runner.plan();f.outcomes.materialize(f.mandate.id);const taskId=f.outcomes.get(f.mandate.id).graph[0].taskId,task=f.execution.portfolio.getTask(taskId);f.store.transaction(()=>f.store.put('portfolio-task',taskId,{...task,allowedTools:[...task.allowedTools,'research.fetch']},task._version));await assert.rejects(()=>runner.runTask(taskId),/OUTCOME_TASK_PROFILE_DENIED/);assert.deepEqual(f.stats(),{counts:1,creates:1,reads:0});assert.equal(f.store.db.prepare("SELECT count(*) n FROM entities WHERE kind='pilot-authorized-outcome-task'").get().n,0);
 }finally{f.close();}});

test('a declared correction may finish against stale commercial interpretation without widening the pinned owner source scope',async()=>{const f=await setup({commercial:true});try{
 const runner=f.load();await runner.plan();let result=await runner.run();const taskId=result.graph[0].taskId,artifact=f.execution.artifact(f.company.id,taskId);assert(f.outcomes.prepare(f.mandate.id).context.commercialUnderstanding);
 runner.correct({nodeId:'foundation',artifactHash:artifact.hash,instruction:'Make the owner review requirement explicit in the corrected local packet.',repairCalls:3,assisted:true});assert.equal(f.outcomes.prepare(f.mandate.id).context.commercialUnderstanding,null);result=await runner.run();assert.equal(result.state,'completed',JSON.stringify(result));
 }finally{f.close();}});
