import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,realpathSync} from 'node:fs';
import {join,relative,isAbsolute} from 'node:path';
import {tmpdir} from 'node:os';
import {spawnSync} from 'node:child_process';
import {StateStore} from '../src/state.ts';
import {rawHash,hash} from '../src/contracts.ts';
import type {ModelPort} from '../src/contracts.ts';
import {PilotKnowledge} from '../src/pilot/knowledge.ts';
import {PilotDiscovery,canonicalDiscoveryUrl,robotsDecision,discoveryProcedure} from '../src/pilot/discovery.ts';
import {createPinnedLookup,createBoundedResearchAdapter} from '../src/operations/research.ts';
import {intelligenceRequest} from '../src/pilot/intelligence-contract.ts';
const page=(body:string,status=200,type='text/html')=>({status,headers:{get:(n:string)=>n==='content-type'?type:null},arrayBuffer:async()=>new TextEncoder().encode(body).buffer});
const fixture=(output:any,counter?:()=>void):ModelPort=>({kind:'fixture',run(r){counter?.();return {output,route:{kind:'fixture',model:r.role.model,provider:'offline-test'},usage:{inputTokens:null,outputTokens:null,cost:{status:'known',money:{currency:'USD',minorUnits:0},basis:'Explicit fixture; no provider calls'}}};}});
function setup(options:{robots?:string;pages?:Map<string,any>;limits?:any;dns?:any;disabled?:boolean}={}){
 const root=mkdtempSync(join(tmpdir(),'midas-discovery-'));let store=new StateStore(join(root,'pilot.sqlite')),knowledge=new PilotKnowledge(store);const company=knowledge.createCompany({name:'Explicit test company',goal:'Investigate the actual buyer journey without invented economics',mode:'fixture'});
 const html='<html><title>Test company</title><style>body{color:#123456}</style><main><h1>Repair service</h1><p>Inspection is needed before a price. €🙂</p><a href="/policy?utm_source=test#fragment">Policy</a><a href="/policy">Same policy</a><a href="https://alternative.test/offer">Compare an alternative</a><a href="http://127.0.0.1/private">Forbidden link</a></main></html>';
 const pages=options.pages??new Map([['https://example.test/',page(html)],['https://example.test/policy',page('<main>Actual current policy.</main>')],['https://alternative.test/offer',page('<h1>Alternative offer</h1><p>Published alternative claim.</p>')]]);
 let fetches:string[]=[];const reader:any={kind:'mock',ports:{dnsLookup:options.dns??(async()=>[{address:'93.184.216.34'}]),fetch:async(url:string,init:any,address:string)=>{assert.equal(address,'93.184.216.34');assert.deepEqual(Object.keys(init.headers).sort(),['accept','user-agent']);fetches.push(url);return url.endsWith('/robots.txt')?page(options.robots??'User-agent: *\nAllow: /',200,'text/plain'):pages.get(url)??page('Missing',404);}}};
 let discovery=new PilotDiscovery(store,{root,knowledge,publicReader:options.disabled?undefined:reader});discovery.start(company.id,{website:'https://example.test/',limits:options.limits});
 return {root,company,html,pages,get store(){return store;},get knowledge(){return knowledge;},get discovery(){return discovery;},fetches:()=>fetches,reader,restart(){store.close();store=new StateStore(join(root,'pilot.sqlite'));knowledge=new PilotKnowledge(store);discovery=new PilotDiscovery(store,{root,knowledge,publicReader:reader});},close(){store.close();const p=realpathSync(root),r=relative(realpathSync(tmpdir()),p);assert(r&&!r.startsWith('..')&&!isAbsolute(r));rmSync(p,{recursive:true,force:true});}};
}
test('public seed retains exact bytes/provenance, deduplicates links and leaves alternative retrieval to a model choice',async()=>{
 const f=setup();try{await f.discovery.seed(f.company.id);assert.deepEqual(f.fetches(),['https://example.test/robots.txt','https://example.test/']);const v=f.discovery.view(f.company.id),source=f.discovery.sources(f.company.id)[0];assert.equal(v.frontier.filter(x=>x.url==='https://example.test/policy').length,1);assert(v.frontier.some(x=>x.url==='https://alternative.test/offer'));assert.equal(source.result.source.contentHash,rawHash(f.html));assert.equal(Buffer.from(source.result.source.retainedBody.base64,'base64').toString(),f.html);assert.equal(f.knowledge.sources(f.company.id).find(x=>x.origin)?.origin?.url,'https://example.test/');
 let calls=0;await f.discovery.next(f.company.id,{attemptId:'decision-follow',port:fixture({action:'follow',url:'https://alternative.test/offer',sourceId:null,reason:'Compare the claimed alternative offer before recommending a change.',unresolved:['Private costs remain unknown.']},()=>calls++)});assert.equal(calls,1);assert(f.fetches().includes('https://alternative.test/robots.txt'));const before=f.fetches().length;f.restart();await f.discovery.next(f.company.id,{attemptId:'decision-follow',port:fixture({},()=>calls++)});assert.equal(f.fetches().length,before);assert.equal(calls,1);
 const packet=f.discovery.request(f.company.id);assert.equal(packet.request.role.model,'gpt-6-astra');assert.equal((packet.request as any).images,undefined);assert(!JSON.stringify(packet).includes('FitKitty'));assert.equal(f.discovery.view(f.company.id).used.decisions,1);
 }finally{f.close();}
});
test('robots rules, private DNS, unsupported content and login walls preserve exact access blockers without bypass',async()=>{
 assert.equal(robotsDecision('User-agent: *\nDisallow: /private\nAllow: /private/open','https://example.test/private/open').allowed,true);
 assert.equal(robotsDecision('User-agent: *\nDisallow: /\nUser-agent: MIDAS\nAllow: /','https://example.test/').allowed,true);
 for(const o of [{robots:'User-agent: *\nDisallow: /'},{dns:async()=>[{address:'127.0.0.1'}]},{pages:new Map([['https://example.test/',page('<p>Log in to continue</p><input type="password">')]])},{pages:new Map([['https://example.test/',page('%PDF',200,'application/pdf')]])}]){const f=setup(o);try{await f.discovery.seed(f.company.id);assert.notEqual(f.discovery.sources(f.company.id)[0].status,'retrieved');assert.equal(f.knowledge.sources(f.company.id).filter(x=>x.origin).length,0);const n=f.fetches().length;await f.discovery.seed(f.company.id);assert.equal(f.fetches().length,n);}finally{f.close();}}
 const disabled=setup({disabled:true});try{await assert.rejects(()=>disabled.discovery.seed(disabled.company.id),/DISCOVERY_PUBLIC_READER_NOT_ENABLED/);assert.equal(disabled.fetches().length,0);}finally{disabled.close();}
 assert.throws(()=>canonicalDiscoveryUrl('https://user:password@example.test/'));assert.throws(()=>canonicalDiscoveryUrl('https://example.test/?access_token=secret'));
});
test('failed decisions consume capacity, retain their output, and unknown decisions cannot become replacement inference',async()=>{
 const f=setup({limits:{maxDecisions:2}});try{await f.discovery.seed(f.company.id);let calls=0;await assert.rejects(()=>f.discovery.next(f.company.id,{attemptId:'bad-schema',port:fixture({action:'finish',url:'https://unobserved.test/',sourceId:null,reason:'Invalid finish cross-fields',unresolved:[]},()=>calls++)}));assert.equal(f.discovery.view(f.company.id).decisions[0].status,'invalid_or_action_blocked');
 const unknown:ModelPort={kind:'fixture',run(){calls++;throw Error('Simulated connection loss');}};await assert.rejects(()=>f.discovery.next(f.company.id,{attemptId:'unknown-decision',port:unknown}));f.restart();await assert.rejects(()=>f.discovery.next(f.company.id,{attemptId:'unknown-decision',port:unknown}),/DISCOVERY_UNKNOWN_DECISION_NO_RESUBMIT/);await assert.rejects(()=>f.discovery.next(f.company.id,{attemptId:'replacement-denied',port:unknown}));assert.equal(calls,2);assert.equal(f.discovery.view(f.company.id).used.decisions,2);
 }finally{f.close();}
});
test('saved decision survives interrupted application and reuses the completed read without another model call',async()=>{
 const f=setup();try{await f.discovery.seed(f.company.id);let calls=0;const port=fixture({action:'read',url:'https://example.test/policy',sourceId:null,reason:'Current policy can contradict the initial offer.',unresolved:[]},()=>calls++);
 f.discovery.afterCheckpoint=phase=>{if(phase==='decision-response-persisted')throw Object.assign(Error('Injected crash'),{simulatedCrash:true});};await assert.rejects(()=>f.discovery.next(f.company.id,{attemptId:'saved-read',port}));await f.discovery.read(f.company.id,'https://example.test/policy');const n=f.fetches().length;f.restart();await f.discovery.next(f.company.id,{attemptId:'saved-read',port});assert.equal(calls,1);assert.equal(f.fetches().length,n);assert.equal(f.discovery.view(f.company.id).decisions[0].status,'applied');
 f.discovery.pause(f.company.id);await f.discovery.seed(f.company.id);assert.equal(f.fetches().length,n);f.discovery.resume(f.company.id);await f.discovery.next(f.company.id,{attemptId:'done',port:fixture({action:'finish',url:null,sourceId:null,reason:'Enough public evidence for commercial analysis; private metrics remain unknown.',unresolved:['Private conversion and margin metrics.']})});assert.equal(f.discovery.view(f.company.id).state,'ready_for_analysis');
 }finally{f.close();}
});
test('selected evidence and company scope govern contexts; explicit restart archives previous observations',async()=>{
 const f=setup();try{await f.discovery.seed(f.company.id);const source=f.discovery.sources(f.company.id)[0],other=f.knowledge.createCompany({name:'Other fixture',goal:'Separate business',mode:'fixture'});assert.throws(()=>f.discovery.source(other.id,source.id));const owner=f.knowledge.sources(f.company.id).filter(s=>!s.origin).map(s=>s.id);f.knowledge.selectEvidence(f.company.id,owner);assert.equal(f.discovery.context(f.company.id).sources.length,0);assert(!f.discovery.context(f.company.id).frontier.some(x=>x.discoveredFrom));const prior=f.discovery.view(f.company.id).id;f.discovery.restart(f.company.id,{website:'https://alternative.test/offer'});assert.notEqual(f.discovery.view(f.company.id).id,prior);assert.equal(f.discovery.sources(f.company.id).length,0);assert(f.knowledge.sources(f.company.id).some(s=>s.origin?.recordId===source.id));assert(f.knowledge.snapshot(f.company.id).history.some(r=>r.kind==='PilotDiscoveryArchivedSession'));
 }finally{f.close();}
});
test('actual isolated browser produces retained screenshot and bounded pixels only after explicit selection and image opt-in',async()=>{
 const f=setup();try{await f.discovery.seed(f.company.id);const source=f.discovery.sources(f.company.id)[0],rendered=await f.discovery.render(f.company.id,source.id);assert.equal(rendered.render.kind,'sanitized-retained-render');assert(rendered.render.modelImage.bytes<=65000);assert.match(rendered.render.text,/Inspection is needed/);assert(rendered.render.screenshot.bytes>0);
 await f.discovery.next(f.company.id,{attemptId:'focus-render',port:fixture({action:'read-source',url:null,sourceId:rendered.id,reason:'Inspect the bounded visual hierarchy of retained evidence.',unresolved:['Interactive and external assets are unavailable.']})});assert.equal((f.discovery.request(f.company.id).request as any).images,undefined);const req=f.discovery.request(f.company.id,'image-decision',{includeImages:true}).request as any;assert.equal(req.images.length,1);assert.equal(req.images[0].sha256,rendered.render.modelImage.sha256);assert.match((req.context as any).modelVisibility,/attached/);assert.equal(req.context.sources.find((s:any)=>s.id===rendered.id).imageSentToModel,true);
 const img=f.discovery.attachImage(f.company.id,{title:'Owner-supplied screenshot fixture',base64:rendered.render.screenshot.base64,mimeType:'image/png',sourceUrl:'https://example.test/',observedAt:new Date().toISOString(),caption:'This is an owner caption, not extracted publisher wording.',rights:'Explicit synthetic test screenshot'});assert.equal(img.kind,'image');assert.equal(f.knowledge.sources(f.company.id).find(s=>s.origin?.recordId===img.id)?.origin?.kind,'owner-image');assert.throws(()=>f.discovery.attachImage(f.company.id,{title:'Too large',base64:Buffer.alloc(2000001).toString('base64'),mimeType:'image/png',observedAt:new Date().toISOString(),caption:'',rights:'test'}));
 }finally{f.close();}
});
test('real process exit preserves fetch/decision intent and recovery never dispatches a duplicate',async()=>{
 for(const operation of ['fetch','decision']){
 const f=setup();try{
 const code='import {StateStore} from '+JSON.stringify(new URL('../src/state.ts',import.meta.url).href)+';import {PilotDiscovery} from '+JSON.stringify(new URL('../src/pilot/discovery.ts',import.meta.url).href)+';const store=new StateStore('+JSON.stringify(join(f.root,'pilot.sqlite'))+');const d=new PilotDiscovery(store,{root:'+JSON.stringify(f.root)+',publicReader:{kind:"mock",ports:{dnsLookup:async()=>{throw Error("DNS must not run")},fetch:async()=>{throw Error("HTTP must not run")}}}});d.afterCheckpoint=()=>process.exit(42);'+(operation==='fetch'?'await d.seed('+JSON.stringify(f.company.id)+');':'await d.next('+JSON.stringify(f.company.id)+',{attemptId:"process-interrupted",port:{kind:"fixture",run(){throw Error("model must not run")}}});');
 const result=spawnSync(process.execPath,['--input-type=module','-e',code],{encoding:'utf8',timeout:10000});assert.equal(result.status,42,result.stderr);
 const pending=f.discovery.view(f.company.id).pending;assert(pending);f.restart();assert.equal(f.discovery.recover(f.company.id).state,'interrupted');assert.equal(f.store.get('pilot-discovery-record',pending!.id).status,'unknown');
 if(operation==='fetch'){await f.discovery.seed(f.company.id);assert.equal(f.fetches().length,0);assert.equal(f.discovery.view(f.company.id).used.requests,2);}
 else{let duplicate=0;const port=fixture({},()=>duplicate++);await assert.rejects(()=>f.discovery.next(f.company.id,{attemptId:'process-interrupted',port}),/DISCOVERY_UNKNOWN_DECISION_NO_RESUBMIT/);await assert.rejects(()=>f.discovery.next(f.company.id,{attemptId:'new-identity-denied',port}),/DISCOVERY_UNKNOWN_DECISION_REQUIRES_RECOVERY/);assert.equal(duplicate,0);
 await f.discovery.next(f.company.id,{attemptId:'process-interrupted',port,recoverSameResponse:async r=>fixture({action:'finish',url:null,sourceId:null,reason:'Recovered fixture response; ready for separate analysis.',unresolved:[]}).run(r)});assert.equal(f.discovery.view(f.company.id).state,'ready_for_analysis');assert.equal(f.discovery.view(f.company.id).used.decisions,1);assert.equal(duplicate,0);}
 }finally{f.close();}
 }
});
test('Node lookup all:true keeps the single vetted address; native failures and expanded private IPv6 stay observable',async()=>{
 let args:any[]=[];createPinnedLookup('93.184.216.34')('example.test',{all:true},(...v)=>args=v);assert.deepEqual(args,[null,[{address:'93.184.216.34',family:4}]]);createPinnedLookup('93.184.216.34')('example.test',{},(...v)=>args=v);assert.deepEqual(args,[null,'93.184.216.34',4]);
 for(const address of ['0:0:0:0:0:0:0:1','0:0:0:0:0:ffff:7f00:1','fe90::1']){let fetched=0;const adapter=createBoundedResearchAdapter({seedUrls:['https://example.test/']},{dnsLookup:async()=>[{address}],fetch:async()=>{fetched++;return page('never');}});assert.equal((await adapter.retrieve('https://example.test/')).code,'PRIVATE_ADDRESS_RESOLUTION_FORBIDDEN');assert.equal(fetched,0);}
 const adapter=createBoundedResearchAdapter({seedUrls:['https://example.test/']},{dnsLookup:async()=>[{address:'93.184.216.34'}],fetch:async()=>{throw Object.assign(Error('uncontrolled message must not persist'),{code:'EACCES'});}});const failed=await adapter.retrieve('https://example.test/');assert.equal(failed.code,'EACCES');assert(!JSON.stringify(failed).includes('uncontrolled'));
});
test('redirect destination cannot skip its own robots policy or host limit',async()=>{
 const redirect={status:302,headers:{get:(name:string)=>name==='location'?'https://destination.test/private':null}};
 const f=setup({pages:new Map<string,any>([['https://example.test/',redirect],['https://destination.test/private',page('hidden')]])});try{await f.discovery.seed(f.company.id);assert.equal(f.discovery.sources(f.company.id)[0].result.code,'ROBOTS_REDIRECT_RECHECK_REQUIRED');assert(!f.fetches().includes('https://destination.test/private'));assert(f.discovery.view(f.company.id).frontier.some(x=>x.url==='https://destination.test/private'));}finally{f.close();}
 const capped=setup({limits:{maxHosts:1},pages:new Map([['https://example.test/',redirect]])});try{await capped.discovery.seed(capped.company.id);assert(!capped.discovery.view(capped.company.id).frontier.some(x=>x.url==='https://destination.test/private'));}finally{capped.close();}
});
test('trusted admission observations distinguish terminal failure, incomplete and no admission without replacing inference',async()=>{
 for(const status of ['terminal_failed','terminal_incomplete','not_admitted'] as const){const f=setup();try{await f.discovery.seed(f.company.id);let calls=0;const port:ModelPort={kind:'fixture',run(){calls++;throw Object.assign(Error('private provider detail never copied'),{code:status==='terminal_incomplete'?'MODEL_RESPONSE_INCOMPLETE':'MODEL_RESPONSE_FAILED'});}};
 const trustedFailureObservation=()=>({status,observationId:'ledger-attempt-1',code:status==='not_admitted'?'ADMISSION_DENIED':'MODEL_RESPONSE_FAILED'});
 await assert.rejects(f.discovery.next(f.company.id,{port,attemptId:'observed-1',trustedFailureObservation}));const first=f.store.get('pilot-discovery-record','observed-1');assert.equal(first.status,status);assert.equal(first.failureObservation.observationId,'ledger-attempt-1');assert.equal(first.result,undefined);assert(!JSON.stringify(first).includes('private provider detail'));
 await assert.rejects(f.discovery.next(f.company.id,{port,attemptId:'observed-1',recoverSameResponse:async()=>{calls++;throw Error('must not run');},trustedFailureObservation}),{code:'DISCOVERY_UNKNOWN_DECISION_NO_RESUBMIT'});assert.equal(calls,1);assert.equal(f.store.get('pilot-discovery-record','observed-1').status,status);assert.equal(f.store.get('pilot-discovery-record','observed-1').error,first.error);
 }finally{f.close();}}
});
test('durable page response reapplies links and source import after interrupted application without another public read',async()=>{
 const f=setup();try{f.discovery.afterCheckpoint=p=>{if(p==='page-response-persisted')throw Object.assign(Error('test process interruption'),{simulatedCrash:true});};await assert.rejects(f.discovery.seed(f.company.id));const attempts=f.fetches().length;assert.equal(f.discovery.view(f.company.id).frontier.length,1);assert.equal(f.knowledge.sources(f.company.id).filter(s=>s.origin).length,0);f.restart();await f.discovery.read(f.company.id,'https://example.test/');assert.equal(f.fetches().length,attempts);assert(f.discovery.view(f.company.id).frontier.some(x=>x.url==='https://alternative.test/offer'));assert.equal(f.knowledge.sources(f.company.id).filter(s=>s.origin).length,1);await f.discovery.read(f.company.id,'https://example.test/');assert.equal(f.knowledge.sources(f.company.id).filter(s=>s.origin).length,1);assert.equal(f.fetches().length,attempts);}finally{f.close();}
});
test('analysis inherits bounded attributed decision observations with exact supplied image references and respects withdrawn evidence',async()=>{
 const f=setup();try{await f.discovery.seed(f.company.id);const base64='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aW6kAAAAASUVORK5CYII=',image=f.discovery.attachImage(f.company.id,{title:'Explicit image fixture',base64,mimeType:'image/png',observedAt:new Date().toISOString(),caption:'Owner supplied visual evidence; fixture provenance.',rights:'Synthetic fixture only'});
 await f.discovery.next(f.company.id,{attemptId:'focus-image',port:fixture({action:'read-source',sourceId:image.id,url:null,reason:'Select pixels before proposing a visual interpretation.',unresolved:['Capture completeness is unknown.']})});
 await f.discovery.next(f.company.id,{attemptId:'observed-image',includeImages:true,port:fixture({action:'read-source',sourceId:image.id,url:null,reason:'Mock visual interpretation retained for the next analysis, not established fact.',unresolved:['The live interactive flow remains unobserved.']})});
 const context=f.discovery.context(f.company.id),observation=context.decisionObservations.find(x=>x.attemptId==='observed-image')!;assert.equal(context.decisionObservations[0].imagesSupplied.length,0);assert.equal(observation.imagesSupplied[0].sourceId,image.id);assert.equal(observation.imagesSupplied[0].sha256,rawHash(Buffer.from(base64,'base64')));assert.match(observation.provenance,/offline_mock/);assert.match(observation.visualBasis,/does not independently verify/);assert.equal(observation.reason,'Mock visual interpretation retained for the next analysis, not established fact.');assert(!JSON.stringify(context).includes(base64));const analysis=intelligenceRequest(f.knowledge.company(f.company.id),f.knowledge.selectedSources(f.company.id),'analysis-fixture',context);assert.equal((analysis.context as any).discovery.decisionObservations[1].imagesSupplied[0].sha256,observation.imagesSupplied[0].sha256);
 for(let i=0;i<6;i++)await f.discovery.next(f.company.id,{attemptId:'bounded-'+i,port:fixture({action:'read-source',sourceId:image.id,url:null,reason:'Bounded context fixture '+i,unresolved:[]})});assert.equal(f.discovery.context(f.company.id).decisionObservations.length,6);assert(!f.discovery.context(f.company.id).decisionObservations.some(x=>x.attemptId==='observed-image'));f.knowledge.selectEvidence(f.company.id,f.knowledge.sources(f.company.id).filter(s=>!s.origin).map(s=>s.id));assert.equal(f.discovery.context(f.company.id).decisionObservations.length,0);
 }finally{f.close();}
});
test('oversized discovery HTML retains an exact bounded prefix, aborts the body and never claims complete coverage',async()=>{
 const html='<html><title>Large fixture</title><main>Visible policy: inspection first. €🙂</main><a href="/policy">Read policy</a><script>'+('untrusted internal code '.repeat(40))+'</script><main>UNREAD_PRIVATE_ASSUMPTION</main><a href="/unread">Unseen link</a>',bytes=Buffer.from(html);let reads=0,aborted=false;const response={status:200,headers:{get:(name:string)=>name==='content-type'?'text/html':name==='content-length'?String(bytes.length):null},body:{getReader:()=>({async read(){reads++;return reads===1?{done:false,value:bytes.subarray(0,400)}:{done:false,value:bytes.subarray(400)};}})}};
 const f=setup({limits:{maxBytes:300},pages:new Map([['https://example.test/',response]])});try{const original=f.reader.ports.fetch;f.reader.ports.fetch=async(url:string,init:any,address:string)=>{if(url==='https://example.test/')init.signal.addEventListener('abort',()=>aborted=true);return original(url,init,address);};await f.discovery.seed(f.company.id);const r=f.discovery.sources(f.company.id)[0],s=r.result.source;assert.equal(reads,1);assert.equal(aborted,true);assert.equal(r.status,'retrieved');assert.equal(r.result.code,'PARTIAL_BODY_RETAINED');assert.equal(s.retainedBody.byteLength,300);assert.equal(s.retainedBody.bodyComplete,false);assert.equal(s.retainedBody.hashScope,'retained-prefix');assert.equal(s.retainedBody.declaredByteLength,bytes.length);assert.equal(s.retainedBody.receivedBytesAtLeast,400);assert.equal(s.contentHash,rawHash(bytes.subarray(0,300)));assert.deepEqual(Buffer.from(s.retainedBody.base64,'base64'),bytes.subarray(0,300));assert.match(s.text,/Visible policy/);assert(!s.text.includes('untrusted'));assert(!s.text.includes('UNREAD'));assert(f.discovery.view(f.company.id).frontier.some(x=>x.url==='https://example.test/policy'));assert(!f.discovery.view(f.company.id).frontier.some(x=>x.url==='https://example.test/unread'));assert.match(f.knowledge.sources(f.company.id).find(x=>x.origin?.recordId===r.id)!.origin!.extraction,/partial byte prefix/);assert.equal(f.discovery.context(f.company.id).sources[0].bodyComplete,false);assert.match(f.discovery.context(f.company.id).sources[0].coverageNote!,/remaining body was aborted/);
 const strict=createBoundedResearchAdapter({seedUrls:['https://example.test/'],retainBody:true,maxBytes:300},{dnsLookup:async()=>[{address:'93.184.216.34'}],fetch:async()=>page(html)});assert.equal((await strict.retrieve('https://example.test/')).code,'BYTE_LIMIT_EXCEEDED');assert.match(discoveryProcedure,/allowance includes the finish decision/);assert.match(discoveryProcedure,/Reserve the final available decision/);
 }finally{f.close();}
});
