import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,relative,isAbsolute} from 'node:path';
import {StateStore} from '../src/state.ts';
import {PilotExecution} from '../src/pilot/execution.ts';
import {validatePreviewRequest} from '../src/portfolio/preview.ts';
import {emptyBusinessSiteState} from '../src/portfolio/business-site-state.ts';
import {hash} from '../src/contracts.ts';
const sources=[{id:'policy',title:'Owner policy',text:'Harbor Workshop is a test furniture-restoration company. Obtain item type, damage, dimensions and preferred contact. Owner inspection is required before feasibility, price or booking. No messages are sent by this local application.',rights:'Developer-authored fixture',observedAt:new Date().toISOString()}];
const company={id:'pilot-test',name:'Harbor Workshop — test company',goal:'Prepare complete inquiries for owner inspection',mode:'fixture'};
function setup(){const root=mkdtempSync(join(tmpdir(),'midas-pilot-execution-'));let store=new StateStore(join(root,'state.sqlite')),execution=new PilotExecution(store,{root});return {root,get store(){return store;},get x(){return execution;},reopen(){store.close();store=new StateStore(join(root,'state.sqlite'));execution=new PilotExecution(store,{root});},close(){store.close();const resolved=realpathSync(root),r=relative(realpathSync(tmpdir()),resolved);assert(r&&!r.startsWith('..')&&!isAbsolute(r));rmSync(resolved,{recursive:true,force:true});}};}
test('shared controller produces sourced deliverable, targeted correction, authenticated new version and restart evidence',async()=>{const f=setup();try{
 const t=f.x.plan({business:company,sources,workflow:'response-packet'});await f.x.run(company.id,t.id);assert.equal(f.x.portfolio.getTask(t.id).status,'completed');const first=f.x.artifact(company.id,t.id),prior=f.x.tools.load(company.id,t.id);assert(first.checks.every((c:any)=>c.passed));assert.match(first.sourceAuthorship,/test double/);const oldContent=prior.files[0].content,oldHash=first.hash;
 const revised=f.x.correct({businessId:company.id,taskId:t.id,artifactHash:oldHash,instruction:'Ask for dimensions and a preferred contact method before owner inspection.'});await f.x.run(company.id,revised.id);assert.equal(f.x.portfolio.getTask(revised.id).status,'completed');const current=f.x.artifact(company.id,revised.id);assert.notEqual(current.hash,oldHash);assert.equal(current.version,2);assert.equal(f.x.tools.load(company.id,t.id).files[0].content,oldContent);assert.equal(f.x.portfolio.getTask(t.id).outputCurrent,false);assert.match(f.x.preview(company.id,revised.id).html!,/Ask for dimensions/);assert.throws(()=>f.x.correct({businessId:company.id,taskId:t.id,artifactHash:oldHash,instruction:'Another change please'}),/PILOT_CORRECTION_ARTIFACT_STALE/);
 const steps=f.x.engine.rows('portfolio-tool-intent');assert(steps.some(s=>s.call.name==='workspace.patch'));const calls=f.x.engine.rows('portfolio-model-request').length;f.reopen();assert.equal(f.x.artifact(company.id,revised.id).hash,current.hash);await f.x.run(company.id,revised.id);assert.equal(f.x.engine.rows('portfolio-model-request').length,calls);assert.equal(JSON.parse(f.x.download(company.id,revised.id).content).manifest.sha256,current.manifestHash);
 }finally{f.close();}});
test('real company may prepare exact requests but fixture adapter cannot dispatch them; scope, stale sources and pause are enforced',async()=>{const f=setup();try{
 const real={...company,id:'real-company',mode:'owner'},t=f.x.plan({business:real,sources,workflow:'response-packet'});const preview=await f.x.engine.previewRequest(t.id);assert.equal((preview.request.context as any).task.inputs.requiresGrant,true);assert.throws(()=>f.x.run(real.id,t.id),/PILOT_LIVE_GRANT_REQUIRED/);assert.equal(f.x.engine.rows('portfolio-model-request').length,0);assert.throws(()=>f.x.artifact(company.id,t.id),/PILOT_TASK_SCOPE_DENIED/);assert.throws(()=>f.x.plan({business:company,sources:[{...sources[0],validUntil:'2020-01-01T00:00:00Z'}],workflow:'business-site'}),/PILOT_STALE_EVIDENCE/);
 const offline=f.x.plan({business:company,sources,workflow:'response-packet'});f.x.pause(company.id,offline.id);assert.equal(f.x.portfolio.getTask(offline.id).status,'paused');assert.throws(()=>f.x.run(company.id,offline.id),/TASK_NOT_READY/);await f.x.resume(company.id,offline.id);assert.equal(f.x.portfolio.getTask(offline.id).status,'completed');
 }finally{f.close();}});
test('business-site profile executes real browser journey and owner state survives restart; stale/cross-profile writes denied',async()=>{const f=setup();try{
 const t=f.x.plan({business:company,sources,workflow:'business-site'});await f.x.run(company.id,t.id);assert.equal(f.x.portfolio.getTask(t.id).status,'completed',f.x.portfolio.getTask(t.id).reason);const artifact=f.x.artifact(company.id,t.id);assert(artifact.checks.every((c:any)=>c.passed));assert(artifact.checks.some((c:any)=>c.id==='site.save-edit'));assert(artifact.checks.some((c:any)=>c.id==='software.browser-observation'&&c.evidence.views.length>=2));assert.equal(f.x.engine.rows('portfolio-model-request').length,3);
 const w=f.x.tools.load(company.id,t.id),binding={ventureId:company.id,taskId:t.id,manifestHash:w.manifest.sha256},state={schemaVersion:1,inquiries:[{id:'owner-test',name:'Explicit owner test',need:'A retained inspection request',details:['work','scope','condition','contact'].map(fieldId=>({fieldId,value:'Supplied '+fieldId})),status:'draft'}]};const write={...binding,operation:'write',state,expectedVersion:0};f.x.previewState(company.id,t.id,write);assert.throws(()=>f.x.previewState(company.id,t.id,{...write,expectedVersion:1,state:{schemaVersion:1,inquiries:[{...state.inquiries[0],details:state.inquiries[0].details.slice(1)}]}}),/PREVIEW_REQUIRED_INFORMATION_MISSING/);assert.throws(()=>f.x.previewState(company.id,t.id,write),/PREVIEW_STATE_STALE/);assert.throws(()=>validatePreviewRequest(write,binding),/PREVIEW_STATE_INVALID/);assert.throws(()=>f.x.previewState(company.id,t.id,{...binding,operation:'write',expectedVersion:1,state:{schemaVersion:1,inquiries:[{...state.inquiries[0],status:'sent'}]}}),/PREVIEW_INQUIRY_INVALID/);f.reopen();assert.deepEqual(f.x.previewState(company.id,t.id,{...binding,operation:'read'}).state,state);assert.notEqual(hash(state),hash(emptyBusinessSiteState()));
 const correction=f.x.correct({businessId:company.id,taskId:t.id,artifactHash:artifact.hash,instruction:'Bring photographs and dimensions for owner review.'});await f.x.run(company.id,correction.id);assert.equal(f.x.portfolio.getTask(correction.id).status,'completed',f.x.portfolio.getTask(correction.id).reason);assert.throws(()=>f.x.previewState(company.id,t.id,{...binding,operation:'read'}),/PILOT_PREVIEW_ARTIFACT_STALE/);const revised=f.x.preview(company.id,correction.id);assert.match(revised.files[0].content,/Bring photographs/);assert.deepEqual(f.x.previewState(company.id,correction.id,{...revised.binding,operation:'read'}).state,state);assert.equal(f.x.tools.load(company.id,t.id).manifest.sha256,w.manifest.sha256);
 }finally{f.close();}});
test('interruption after persisted model response resumes without duplicate fixture admission',async()=>{const f=setup();try{
 const t=f.x.plan({business:company,sources,workflow:'response-packet'});f.x.engine.afterPersist=phase=>{if(phase==='model')throw Object.assign(new Error('test interruption'),{simulatedCrash:true});};await assert.rejects(f.x.run(company.id,t.id),/test interruption/);assert.equal(f.x.engine.rows('portfolio-model-request').length,1);f.x.portfolio.recover({ownerAlive:()=>false});f.reopen();await f.x.recover();await f.x.run(company.id,t.id);assert.equal(f.x.portfolio.getTask(t.id).status,'completed');assert.equal(f.x.engine.rows('portfolio-model-request').length,2);assert.equal(f.x.engine.rows('local-tool-call').filter(t=>t.tool==='artifact.publish_local').length,1);
 }finally{f.close();}});
test('unavailable browser preserves failed checks and blocks the fixture without publication or fallback',async()=>{const f=setup();try{
 const x=new PilotExecution(f.store,{root:f.root,browserLauncher:async()=>{throw Error('TEST_BROWSER_UNAVAILABLE');}}),t=x.plan({business:company,sources,workflow:'business-site'});await x.run(company.id,t.id);assert.equal(x.portfolio.getTask(t.id).status,'blocked');assert.equal(x.artifact(company.id,t.id),null);assert.equal(x.tools.load(company.id,t.id).published,null);assert(x.tools.load(company.id,t.id).checks.some(c=>c.id==='site.journey'&&!c.passed));assert.equal(x.engine.rows('portfolio-model-request').length,3);assert(x.engine.rows('portfolio-model-result').every(r=>r.provenance==='offline_mock'));assert.throws(()=>x.plan({business:company,sources:[{...sources[0],text:'x'.repeat(8001)}],workflow:'response-packet'}),/PILOT_EXECUTION_EVIDENCE_SCOPE_REQUIRED/);
 }finally{f.close();}});
