import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {StateStore} from '../src/state.ts';
import {PilotKnowledge} from '../src/pilot/knowledge.ts';
import {PilotExecution} from '../src/pilot/execution.ts';
import {PilotOutcomes} from '../src/pilot/outcomes.ts';
import {mockResult} from '../src/portfolio/worker.ts';
import {validateOutcomePlan} from '../src/pilot/outcome-contract.ts';
function setup(){const root=mkdtempSync(join(tmpdir(),'midas-outcome-')),store=new StateStore(join(root,'state.sqlite')),k=new PilotKnowledge(store),c=k.createCompany({name:'Test service',website:'',notes:'Explicit synthetic fixture',goal:'Prepare a useful response with current evidence',mode:'fixture'});const s=k.addSource(c.id,{title:'Service rules',text:'The example service requires owner review before pricing. There are no verified prices.',kind:'text',rights:'Synthetic development material',observedAt:new Date().toISOString()});const e=new PilotExecution(store,{root}),o=new PilotOutcomes(store,e);return {root,store,k,c,s,e,o};}
function plan(s:any,decision='prepare'){return {decision,rationale:'Prepare a bounded sourced response; no measured customer benefit.',strongestAlternative:'Ask the owner for private evidence before changing public operations.',blockingConditions:decision==='blocked'?['Current private evidence unavailable']:[],evidenceRefs:[{sourceId:s.id,quote:s.text}],tasks:decision==='prepare'?[{id:'prepare-response',family:'response-packet',title:'Useful response packet',outcome:'Provide the owner a sourced response and next step',details:'Preserve price uncertainty and owner authority.',dependsOn:[],sourceIds:[s.id],competencies:['evidence-grounded-work'],reasonForWorker:'One generalist has the writing and source tools; quality is unmeasured.',calls:5}]:[],successEvidence:['Current checks and local readback; owner usefulness remains unknown.'],limitsOfInference:'Scripted integration fixture, not AI competence.'};}
test('one owner mandate creates persisted real work and completes without a ceremonial planning task',async()=>{const x=setup(),o=x.o.create(x.c.id,{objective:x.c.goal,autonomy:'prepare_supported_work',maxCalls:14,repairReserve:8});const r=await x.o.propose(o.id,{kind:'fixture',run:()=>mockResult(plan(x.s))});assert.equal(r.state,'ready');const done=await x.o.runOffline(o.id);assert.equal(done.state,'completed',JSON.stringify(done));assert.equal(done.graph.length,1);assert.ok(done.artifacts[0].current);assert.ok(x.e.download(x.c.id,done.graph[0].taskId,'report.html').content.includes('Service rules'));assert.ok(done.calls.admitted>1);const before=done.calls.admitted;await x.o.runOffline(o.id);assert.equal(x.o.view(o.id).calls.admitted,before);x.store.close();const restored=new StateStore(join(x.root,'state.sqlite'));assert.equal(new PilotOutcomes(restored,new PilotExecution(restored,{root:x.root})).view(o.id).state,'completed');restored.close();});
test('rejection preserves evidence and creates no dependent work',async()=>{const x=setup(),o=x.o.create(x.c.id,{objective:x.c.goal,autonomy:'prepare_supported_work',maxCalls:8,repairReserve:2});await x.o.propose(o.id,{kind:'fixture',run:()=>mockResult(plan(x.s,'reject'))});assert.equal(x.o.view(o.id).state,'rejected');assert.deepEqual(x.o.get(o.id).taskIds,[]);assert.equal(x.o.view(o.id).calls.admitted,1);assert.throws(()=>x.o.materialize(o.id),/OUTCOME_NOT_EXECUTABLE/);x.store.close();});
test('unknown planner attempt cannot be silently resubmitted and bad reference/capacity is rejected',async()=>{const x=setup(),o=x.o.create(x.c.id,{objective:x.c.goal,autonomy:'prepare_supported_work',maxCalls:8,repairReserve:2});let calls=0;const port={kind:'fixture' as const,run(){calls++;throw Error('deliberate connection loss');}};await assert.rejects(x.o.propose(o.id,port),/deliberate/);await assert.rejects(x.o.propose(o.id,port),/NO_RESUBMIT/);assert.equal(calls,1);const p=plan(x.s);p.tasks[0].calls=7;assert.throws(()=>validateOutcomePlan(p,x.o.prepare(o.id).context),/CAPACITY/);p.tasks[0].calls=4;p.evidenceRefs[0].quote='invented';assert.throws(()=>validateOutcomePlan(p,x.o.prepare(o.id).context),/REFERENCE/);x.store.close();});
test('no outcome grant is inferred from live ModelPort and source changes block execution',async()=>{const x=setup(),o=x.o.create(x.c.id,{objective:x.c.goal,autonomy:'prepare_supported_work',maxCalls:8,repairReserve:2});await assert.rejects(x.o.propose(o.id,{kind:'live',run(){throw Error('must never run');}}),/SIGNED_RUNNER/);await x.o.propose(o.id,{kind:'fixture',run:()=>mockResult(plan(x.s))});x.k.addSource(x.c.id,{title:'New policy',text:'Private evidence is now unavailable.',kind:'text',rights:'synthetic',observedAt:new Date().toISOString()});assert.throws(()=>x.o.materialize(o.id),/CONTEXT_CHANGED/);assert.equal(x.o.view(o.id).contextCurrent,false);x.store.close();});

 test('correction preserves original, invalidates dependents and regenerates a fresh linked task without borrowing limits',async()=>{const x=setup(),o=x.o.create(x.c.id,{objective:x.c.goal,autonomy:'prepare_supported_work',maxCalls:30,repairReserve:19});const p=plan(x.s);p.tasks.push({...p.tasks[0],id:'review-summary',title:'Downstream summary',dependsOn:['prepare-response']});await x.o.propose(o.id,{kind:'fixture',run:()=>mockResult(p)});const before=await x.o.runOffline(o.id),oldParent=before.graph[0].taskId,oldChild=before.graph[1].taskId,artifact=before.artifacts[0];assert.equal(before.state,'completed');const request={nodeId:'prepare-response',artifactHash:artifact.hash,instruction:'Request owner confirmation of service scope before proposing a next step.',repairCalls:4,assisted:true};const revised=x.o.correct(o.id,request);assert.equal(revised.repairAllocated,9);assert.equal(x.o.correct(o.id,request).repairAllocated,9);assert.equal(x.e.portfolio.getTask(oldChild).outputCurrent,false);assert.equal(x.k.corrections(x.c.id).length,1);const done=await x.o.runOffline(o.id);assert.equal(done.state,'completed',JSON.stringify(done));assert.notEqual(done.graph[0].taskId,oldParent);assert.notEqual(done.graph[1].taskId,oldChild);assert.ok(done.taskIds.includes(oldParent)&&done.taskIds.includes(oldChild));assert.ok(x.e.download(x.c.id,done.graph[0].taskId,'report.html').content.includes('Request owner confirmation'));assert.ok(x.e.portfolio.getTask(done.graph[1].taskId).inputArtifacts.some(a=>a.sha256===done.artifacts[0].hash));assert.ok(done.calls.admitted<=o.maxCalls);x.store.close();});
