import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,relative,isAbsolute} from 'node:path';
import {StateStore} from '../src/state.ts';
import {PilotExecution} from '../src/pilot/execution.ts';
import {PilotKnowledge} from '../src/pilot/knowledge.ts';
import {PilotLearning} from '../src/pilot/learning.ts';
import {checkCampaign,campaignText} from '../src/portfolio/campaign-profile.ts';
import {hash,rawHash} from '../src/contracts.ts';
function setup(){const root=mkdtempSync(join(tmpdir(),'midas-commercial-')),store=new StateStore(join(root,'pilot.sqlite')),knowledge=new PilotKnowledge(store),x=new PilotExecution(store,{root}),learning=new PilotLearning(store);return {root,store,knowledge,x,learning,close(){store.close();const p=realpathSync(root),r=relative(realpathSync(tmpdir()),p);assert(r&&!r.startsWith('..')&&!isAbsolute(r));rmSync(p,{recursive:true,force:true});}};}
function company(f:ReturnType<typeof setup>,name:string){return f.knowledge.createCompany({name,goal:'Develop a source-grounded, bounded commercial proposal for owner review.',notes:'This is synthetic development material. Prices, demand and economic outcomes are unknown. Owner review is required; no sending, sales or booking is authorized.',mode:'fixture'});}
const job={title:'A coordinated offer and commercial test packet',outcome:'Prepare an inspectable proposal and practical next-step assets',details:'Use company evidence to contrast a bounded proposed offer with the existing alternative. No commercial claim is established.',audience:'Independent operators evaluating their next seasonal promotion',offer:'A bounded owner-reviewed campaign planning session'};
test('two business configurations produce authored coordinated content and a usable responsive page through the same controller',async()=>{for(const name of ['Juniper Studio — synthetic design business','Copper Field — synthetic specialty retailer']){const f=setup();try{
 const c=company(f,name),sources=f.knowledge.sources(c.id),campaign=f.x.plan({business:c,sources,workflow:'campaign-packet',job,procedureBinding:f.learning.assignment(c.id,'campaign-packet')});
 const preview=await f.x.engine.previewRequest(campaign.id);assert.equal((preview.request.context as any).workspace.currentSource[0].content,'{}');assert.equal((preview.request.context as any).workspace.fileContract.extension.id,'commercial-campaign-v1');await f.x.run(c.id,campaign.id);assert.equal(f.x.portfolio.getTask(campaign.id).status,'completed',f.x.portfolio.getTask(campaign.id).reason);
 const current=f.x.artifact(c.id,campaign.id),body=JSON.parse(f.x.download(c.id,campaign.id,'brief.json').content);assert.equal(body.campaign.assets.length,7);assert(current.checks.every((x:any)=>x.passed));assert.match(f.x.download(c.id,campaign.id,'initial-offer.md').content,/bounded owner-reviewed campaign/);assert.match(f.x.preview(c.id,campaign.id).html!,/Coordinated commercial assets/);
 const page=f.x.plan({business:c,sources,workflow:'marketing-page',job:{...job,title:'A local product and offer page'},campaignTaskId:campaign.id,procedureBinding:f.learning.assignment(c.id,'marketing-page')});const pagePreview=await f.x.engine.previewRequest(page.id);assert.match((pagePreview.request.context as any).workspace.currentSource[0].content,/Implementation pending/);assert.equal((pagePreview.request.context as any).dependencies[0].artifacts[0].campaignLocation,'workspace.inputs.campaign');assert.equal((pagePreview.request.context as any).workspace.inputs.campaign.foundation.offer.value,body.campaign.foundation.offer.value);
 await f.x.run(c.id,page.id);const complete=f.x.portfolio.getTask(page.id);assert.equal(complete.status,'completed',complete.reason+' '+JSON.stringify(f.x.tools.load(c.id,page.id).checks.filter(x=>!x.passed)));const artifact=f.x.artifact(c.id,page.id);assert(artifact.checks.every((x:any)=>x.passed));assert(artifact.checks.some((x:any)=>x.id==='marketing.campaign-binding'));assert(artifact.checks.some((x:any)=>x.id==='site.responsive'));assert.match(f.x.download(c.id,page.id,'app.html').content,/id="faq"/);assert.equal(f.x.engine.rows('portfolio-model-request').length,5);assert(f.x.engine.rows('portfolio-model-result').every(r=>r.provenance==='offline_mock'));
 }finally{f.close();}}});
test('canonical campaign correction revises exported assets, invalidates the dependent page, and prepares a fresh linked page without resetting allowance',async()=>{const f=setup();try{
 const c=company(f,'Harbor Brand — synthetic'),sources=f.knowledge.sources(c.id),campaign=f.x.plan({business:c,sources,workflow:'campaign-packet',job});await f.x.run(c.id,campaign.id);const original=f.x.artifact(c.id,campaign.id),originalBytes=f.x.download(c.id,campaign.id,'brief.json').content;
 const page=f.x.plan({business:c,sources,workflow:'marketing-page',job,campaignTaskId:campaign.id});await f.x.run(c.id,page.id);assert(f.x.artifact(c.id,page.id).current);
 const corrected=f.x.correct({businessId:c.id,taskId:campaign.id,artifactHash:original.hash,instruction:'A focused owner-reviewed positioning workshop with a practical action sheet'});await f.x.run(c.id,corrected.id);assert.equal(f.x.portfolio.getTask(corrected.id).status,'completed',f.x.portfolio.getTask(corrected.id).reason);assert.equal(f.x.download(c.id,campaign.id,'brief.json').content===originalBytes,false);assert.equal(f.x.tools.load(c.id,campaign.id).files[0].content,originalBytes);assert.match(f.x.download(c.id,corrected.id,'first-conversation.md').content,/positioning workshop/);assert.equal(f.x.artifact(c.id,page.id).current,false);assert(f.x.portfolio.getTask(page.id).invalidatedAt);
 const replacement=f.x.replanDependent({businessId:c.id,taskId:page.id,campaignTaskId:corrected.id});assert.notEqual(replacement.id,page.id);assert.equal(replacement.attempts,0);assert.equal((replacement.inputs as any).replannedFrom,page.id);assert.equal(f.x.portfolio.getTask(page.id).attempts,1);await f.x.run(c.id,replacement.id);assert.equal(f.x.portfolio.getTask(replacement.id).status,'completed',f.x.portfolio.getTask(replacement.id).reason);assert.match(f.x.download(c.id,replacement.id,'app.html').content,/positioning workshop/);
 }finally{f.close();}});
test('shared-value, money, source and execution-state defects fail independent campaign checks without publication',async()=>{const f=setup();try{const c=company(f,'Consistency test — synthetic'),task=f.x.plan({business:c,sources:f.knowledge.sources(c.id),workflow:'campaign-packet',job});await f.x.run(c.id,task.id);const w=f.x.tools.load(c.id,task.id),report=JSON.parse(w.files[0].content);for(const mutate of [(r:any)=>r.campaign.assets[0].body+=' Now only $10.',(r:any)=>r.campaign.foundation.price={currency:'USD',minorUnits:1.5,status:'hypothesis',references:[]},(r:any)=>r.campaign.foundation.offer={value:'Approved by everyone',status:'source',references:[{sourceId:'absent',quote:'approved'}]},(r:any)=>r.campaign.assets[0].status='sent']){const bad=structuredClone(report);mutate(bad);assert(checkCampaign(bad,w.inputs).some(c=>c.required&&!c.passed));}
 const bad=structuredClone(report);bad.campaign.assets[0].body+=' Final price $9.';await f.x.tools.execute({ventureId:c.id,taskId:task.id,tool:'workspace.replace',args:{path:'brief.json',content:JSON.stringify(bad),expectedHash:rawHash(w.files[0].content)}});const check=await f.x.tools.execute({ventureId:c.id,taskId:task.id,tool:'check.run',args:{}});assert.equal(check.ok,false);const publish=await f.x.tools.execute({ventureId:c.id,taskId:task.id,tool:'artifact.publish_local',args:{}});assert.equal(publish.ok,false);assert.equal(f.x.tools.load(c.id,task.id).published,null);
 }finally{f.close();}});
test('commercial source selection retains large permitted material and sends bounded previews with explicit read paths',async()=>{const f=setup();try{const c=company(f,'Evidence test — synthetic');f.knowledge.addSource(c.id,{title:'Retained public workflow excerpt',kind:'website',text:'Public source material. '.repeat(1000),rights:'Public read-only test content',observedAt:new Date().toISOString()});const latest=f.knowledge.company(c.id),sources=f.knowledge.sources(c.id),task=f.x.plan({business:latest,sources,workflow:'campaign-packet',job,requiredSourceIds:[sources[0].id]});const preview=await f.x.engine.previewRequest(task.id),context=preview.request.context as any;assert(context.sources.some((s:any)=>s.truncated&&s.readMore.tool==='research.read'));assert.equal(f.x.evidence.forTask(task).length,2);assert(context.workspace.inputs.requiredSourceIds.length===1);assert(Buffer.byteLength(JSON.stringify(context))<40000);assert.throws(()=>f.x.plan({business:latest,sources,workflow:'response-packet'}),/PILOT_WORKER_BUNDLE_TOO_LARGE|PILOT_EXECUTION_EVIDENCE_SCOPE_REQUIRED/);
 }finally{f.close();}});
