import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {PilotService} from '../src/pilot/service.ts';
import {servePilot} from '../src/pilot/server.ts';
import {launchCheckBrowser} from '../src/portfolio/preview.ts';

test('adaptive owner preparation persists exact public acquisition policy and denies private evidence or invalid scope',async()=>{
 const root=mkdtempSync(join(tmpdir(),'pilot-acquisition-http-')),service=new PilotService(root),app=servePilot({service,port:0}),origin=await app.ready;let calls=0;service.execution.engine.model.run=async()=>{calls++;throw Error('Preparation must not dispatch');};
 try{const fixture=service.knowledge.createCompany({name:'Explicit synthetic acquisition task',goal:'Inspect a public sample',mode:'fixture'}),owner=service.knowledge.createCompany({name:'Private owner task',goal:'Prepare an operating packet'});
  for(const business of [fixture,owner])service.knowledge.addSource(business.id,{title:'Permitted context',kind:'text',text:'This owner-entered context contains the acceptance criteria for local review.',rights:'Permitted local preparation',observedAt:'2026-09-14T12:00:00Z'});
  const response=await fetch(origin+'/api/session'),cookie=response.headers.get('set-cookie')!.split(';')[0],session=await response.json() as any;
  const post=async(body:any)=>{const response=await fetch(origin+'/api/adaptive/plan',{method:'POST',headers:{cookie,origin,'content-type':'application/json','x-csrf-token':session.csrf},body:JSON.stringify(body)});return {status:response.status,body:await response.json() as any};};
  const acquisition={dataScope:'public-or-synthetic',allowedHosts:['docs.example.com','registry.example.com'],maxRequests:7,maxBytes:3*1024*1024,deadlineMs:14000},request={businessId:fixture.id,workflow:'response-packet',job:{title:'Inspect permitted public material',outcome:'Prepare a source-backed local operating packet',details:'Record unknowns before choosing an action.'},adaptive:{prompt:'baseline',allowCommands:true,allowServices:true,modelCalls:24,localToolRuns:64,acquisition}};
  for(const invalid of [{...acquisition,allowedHosts:['https://docs.example.com']},{...acquisition,maxRequests:101},{...acquisition,maxBytes:16777217},{...acquisition,deadlineMs:30001},{...acquisition,dataScope:'private'}]){const rejected=await post({...request,adaptive:{...request.adaptive,acquisition:invalid}});assert([400,403].includes(rejected.status),JSON.stringify(rejected));assert.match(JSON.stringify(rejected.body),/ACQUISITION_SCOPE_REQUIRED|ACQUISITION_LIMIT_INVALID/);}
  const denied=await post({...request,businessId:owner.id});assert([400,403].includes(denied.status),JSON.stringify(denied));assert.match(JSON.stringify(denied.body),/ACQUISITION_PRIVATE_CONTEXT_DENIED/);
  assert.equal(service.execution.tasks(fixture.id).length,0);assert.equal(service.execution.tasks(owner.id).length,0);
  const prepared=await post(request);assert.equal(prepared.status,200,JSON.stringify(prepared.body));const task=service.execution.portfolio.getTask(prepared.body.result.id);assert.deepEqual((task.inputs as any).adaptiveExecution.acquisition,acquisition);assert.equal((task.inputs as any).adaptiveExecution.allowServices,true);assert.equal(calls,0);assert.equal(service.authority().liveEnabled,false);
  const ordinary=await post({...request,businessId:owner.id,adaptive:{prompt:'baseline',allowCommands:true,modelCalls:24,localToolRuns:64}});assert.equal(ordinary.status,200);assert.equal(ordinary.body.result.inputs.adaptiveExecution.acquisition,undefined);assert.notEqual(ordinary.body.result.inputs.adaptiveExecution.allowServices,true);
 }finally{await app.close();service.store.close();rmSync(root,{recursive:true,force:true});}
});

test('actual owner browser submits every public acquisition limit only after explicit selection',async()=>{
 const root=mkdtempSync(join(tmpdir(),'pilot-acquisition-browser-')),service=new PilotService(root),business=service.knowledge.createCompany({name:'Acquisition browser fixture',goal:'Inspect a public sample',mode:'fixture'});service.knowledge.addSource(business.id,{title:'Synthetic source',kind:'text',text:'A synthetic task needs a local review packet.',rights:'Synthetic development evidence',observedAt:'2026-09-14T12:00:00Z'});const app=servePilot({service,port:0}),origin=await app.ready,browser=await launchCheckBrowser();
 try{const context=await browser.newContext({viewport:{width:1280,height:960}});await context.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());await context.addInitScript(id=>localStorage.setItem('midas-pilot-business',id),business.id);const page=await context.newPage();const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(origin+'/#adaptive');await page.getByRole('button',{name:'Prepare adaptive assignment'}).click();
  assert.equal(await page.getByRole('checkbox',{name:'Request public document or package access'}).isChecked(),false);assert.equal(await page.getByLabel('Maximum requests',{exact:true}).isDisabled(),true);assert.equal(await page.getByRole('checkbox',{name:'Request temporary local services'}).isChecked(),false);
  await page.getByLabel('Assignment title',{exact:true}).fill('Inspect public specification');await page.getByLabel('What result should be completed?',{exact:true}).fill('Prepare a readable local operating packet with source references');await page.getByLabel('Evidence, constraints and acceptance details',{exact:true}).fill('Retain the permitted source references and unknowns.');await page.getByRole('checkbox',{name:'Request public document or package access'}).check();await page.getByRole('checkbox',{name:'Request temporary local services'}).check();await page.getByLabel('Exact allowed hosts, separated by commas',{exact:true}).fill('docs.example.com, registry.example.com');await page.getByLabel('Maximum requests',{exact:true}).fill('6');await page.getByLabel('Maximum bytes per download',{exact:true}).fill('2097152');await page.getByLabel('Download deadline in milliseconds',{exact:true}).fill('12000');
  const responsePromise=page.waitForResponse(response=>response.url().endsWith('/api/adaptive/plan'));await page.getByRole('button',{name:'Prepare assignment',exact:true}).click();const response=await responsePromise;const result=await response.json();assert.equal(response.status(),200,JSON.stringify(result));assert.deepEqual(result.result.inputs.adaptiveExecution.acquisition,{dataScope:'public-or-synthetic',allowedHosts:['docs.example.com','registry.example.com'],maxRequests:6,maxBytes:2097152,deadlineMs:12000});assert.equal(result.result.inputs.adaptiveExecution.allowServices,true);assert.equal(result.view.accounting.providerCalls,0);await page.reload();assert.equal(service.execution.portfolio.getTask(result.result.id).status,'queued');
  await page.goto(origin+'/#outcomes');await page.getByRole('button',{name:'Create outcome mandate',exact:true}).first().click();assert.equal(await page.getByRole('checkbox',{name:'Allow task-scoped capability development'}).isChecked(),false);const objective=page.getByLabel('What outcome do you need?',{exact:true});await objective.fill('Prepare a current review packet without additional capabilities');const ordinaryResponse=page.waitForResponse(response=>response.url().endsWith('/api/outcome/create'));await page.getByRole('dialog').getByRole('button',{name:'Create outcome mandate',exact:true}).click();const ordinary=await (await ordinaryResponse).json();assert.equal(ordinary.result.adaptive,undefined);
  await page.getByRole('button',{name:'Create outcome mandate',exact:true}).first().click();await page.getByLabel('What outcome do you need?',{exact:true}).fill('Prepare a permitted public specification review with scoped capability development');await page.getByRole('checkbox',{name:'Allow task-scoped capability development'}).check();await page.getByRole('checkbox',{name:'Request isolated project commands'}).check();await page.getByRole('checkbox',{name:'Request temporary local services'}).check();await page.getByRole('checkbox',{name:'Request public document or package access'}).check();await page.getByLabel('Exact allowed hosts, separated by commas',{exact:true}).fill('docs.example.com');await page.getByLabel('Maximum requests',{exact:true}).fill('4');await page.getByLabel('Maximum bytes per download',{exact:true}).fill('1048576');await page.getByLabel('Download deadline in milliseconds',{exact:true}).fill('11000');
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const mandateResponse=page.waitForResponse(response=>response.url().endsWith('/api/outcome/create'));await page.getByRole('dialog').getByRole('button',{name:'Create outcome mandate',exact:true}).click();const createdResponse=await mandateResponse,created=await createdResponse.json();assert.equal(createdResponse.status(),200,JSON.stringify(created));const expected={prompt:'baseline',allowCommands:true,allowServices:true,acquisition:{dataScope:'public-or-synthetic',allowedHosts:['docs.example.com'],maxRequests:4,maxBytes:1048576,deadlineMs:11000}};assert.deepEqual(service.operatingOutcomes.get(created.result.id).adaptive,expected);assert.deepEqual(service.operatingOutcomes.prepare(created.result.id).context.mandate.adaptive,expected);assert.equal(service.authority().liveEnabled,false);assert.deepEqual(errors,[]);
 }finally{await browser.close();await app.close();service.store.close();rmSync(root,{recursive:true,force:true});}
});

test('owner pause latches execution before service cleanup and retains unconfirmed shutdown',async()=>{
 const root=mkdtempSync(join(tmpdir(),'pilot-service-control-')),service=new PilotService(root),business=service.knowledge.createCompany({name:'Service cleanup fixture',goal:'Prepare local review',mode:'fixture'});service.knowledge.addSource(business.id,{title:'Synthetic source',kind:'text',text:'Local review is required before any use.',rights:'Synthetic development evidence',observedAt:'2026-09-14T12:00:00Z'});const task=service.execution.plan({business,sources:service.knowledge.sources(business.id),workflow:'response-packet',job:{title:'Local review task',outcome:'Prepare local reviewed work',details:'Keep the local service bounded.'},adaptive:{prompt:'baseline',allowCommands:true,allowServices:true,modelCalls:24,localToolRuns:64}}),app=servePilot({service,port:0}),origin=await app.ready;
 try{const response=await fetch(origin+'/api/session'),cookie=response.headers.get('set-cookie')!.split(';')[0],session=await response.json() as any;let calls=0;
  (service.execution as any).stopAdaptiveServices=async(businessId:string,taskId:string)=>{assert.equal(businessId,business.id);assert.equal(taskId,task.id);assert.equal(service.execution.portfolio.getTask(taskId).status,'paused');calls++;throw Error('SERVICE_STOP_UNCONFIRMED_FIXTURE');};
  const post=()=>fetch(origin+'/api/pause',{method:'POST',headers:{cookie,origin,'content-type':'application/json','x-csrf-token':session.csrf},body:JSON.stringify({businessId:business.id,taskId:task.id})});const stopped=await post(),body=await stopped.json() as any;assert.equal(stopped.status,200);assert.equal(body.result.status,'paused');assert.equal(body.result.serviceCleanup.status,'unconfirmed');assert.equal(body.view.tasks[0].serviceCleanup.status,'unconfirmed');assert.equal(service.execution.portfolio.getTask(task.id).status,'paused');assert.equal(calls,1);
  (service.execution as any).stopAdaptiveServices=async()=>({stopped:true,fixture:true});const retried=await(await post()).json() as any;assert.equal(retried.result.serviceCleanup.status,'confirmed');assert.equal(retried.view.tasks[0].serviceCleanup.status,'confirmed');
 }finally{await app.close();service.store.close();rmSync(root,{recursive:true,force:true});}
});


test('inspection preserves configured worker version and classic stop creates no adaptive namespace',async()=>{
 const root=mkdtempSync(join(tmpdir(),'pilot-inspection-preserves-'));let service=new PilotService(root);
 try{
  service.execution.portfolio.registerWorker({id:'pilot-generalist',name:'Frozen direct baseline',competencies:['evidence-grounded-work'],capabilities:['service.brief'],procedureId:'frozen-master-v1',maxConcurrency:2,available:false});
  const before=service.store.get('portfolio-worker','pilot-generalist');service.store.close();service=new PilotService(root);assert.deepEqual(service.store.get('portfolio-worker','pilot-generalist'),before);
  const business=service.knowledge.createCompany({name:'Inspection fixture',goal:'Prepare a local response packet',mode:'fixture'});service.knowledge.addSource(business.id,{title:'Synthetic evidence',kind:'text',text:'Prepare a scoped response for review only.',rights:'Synthetic',observedAt:'2026-09-14T12:00:00Z'});
  const task=service.execution.plan({business,sources:service.knowledge.sources(business.id),workflow:'response-packet'});assert.deepEqual(await service.execution.stopAdaptiveServices(business.id,task.id),[]);assert.equal(existsSync(join(root,'adaptive')),false);assert.deepEqual(service.store.get('portfolio-worker','pilot-generalist'),before);
 }finally{service.store.close();rmSync(root,{recursive:true,force:true});}
});
