import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {PilotService} from '../src/pilot/service.ts';
import {servePilot} from '../src/pilot/server.ts';
import {launchCheckBrowser} from '../src/portfolio/preview.ts';

async function client(origin:string){const res=await fetch(origin+'/api/session'),session:any=await res.json(),cookie=res.headers.get('set-cookie')!.split(';')[0];return async(path:string,body:any,csrf=session.csrf)=>{const response=await fetch(origin+path,{method:'POST',headers:{cookie,origin,'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify(body)});return {status:response.status,body:await response.json() as any};};}
test('HTTP observation ingress persists typed evidence, guards scope and exposes runnable authority state',async()=>{
 const root=mkdtempSync(join(tmpdir(),'midas-observation-http-')),service=new PilotService(root),app=servePilot({service,port:0}),origin=await app.ready;
 try{const post=await client(origin),created=await post('/api/business',{name:'New venture without a website',goal:'Investigate whether a permitted operational pilot is useful.',operatingMode:'found',mode:'fixture'}),businessId=created.body.view.business.id;
 assert.equal(created.status,200);assert.equal(created.body.view.business.mode,'owner');assert.equal(created.body.view.business.operatingMode,'found');
 const body={businessId,idempotencyKey:'http-observation',taskId:null,artifactHash:null,sourceIds:[],kind:'hypothesis',result:'inconclusive',notes:'Prospective operators might value a small workflow audit; willingness to pay is untested.',observedAt:'2026-09-01T12:00:00Z',measurement:null,assisted:true};
 assert.equal((await post('/api/observation',body,'invalid')).status,403);const result=await post('/api/observation',body);assert.equal(result.status,200,JSON.stringify(result.body));assert.equal(result.body.view.observationLoop.decisions[0].state,'needs_authority');assert.equal(result.body.view.operatingOutcomes.length,1);assert.equal(service.operatingOutcomes.prepare(result.body.result.decision.outcomeId).context.businessMode,'found');
 assert.equal((await post('/api/observation',body)).body.result.id,result.body.result.id);assert.equal(service.observationLoop.view(businessId).observations.length,1);assert.equal((await post('/api/outcome/run-approved',{businessId,outcomeId:result.body.result.decision.outcomeId})).status,403);
 const other=await post('/api/business',{name:'Separate operator',goal:'Keep this context separated.'});assert.equal((await post('/api/observation/withdraw',{businessId:other.body.view.business.id,observationId:result.body.result.id,reason:'Cannot withdraw another business observation.'})).status,403);
 const withdrawn=await post('/api/observation/withdraw',{businessId,observationId:result.body.result.id,reason:'This is not a permitted input for future work.'});assert.equal(withdrawn.status,200);assert.equal(withdrawn.body.view.observationLoop.decisions[0].state,'withdrawn');assert.equal(withdrawn.body.view.accounting.providerCalls,0);
 }finally{await app.close();service.store.close();}
});

test('desktop and phone owner controls persist pending feedback, measured evidence and follow-up decisions in a real browser',async()=>{
 const root=mkdtempSync(join(tmpdir(),'midas-observation-browser-')),service=new PilotService(root),app=servePilot({service,port:0}),origin=await app.ready;let browser:any;
 try{browser=await launchCheckBrowser();const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',(e:Error)=>errors.push(e.message));await context.route('**/*',(route:any)=>new URL(route.request().url()).origin===origin?route.continue():route.abort());page.setDefaultTimeout(10000);
 await page.goto(origin);await page.getByLabel('Operating mode',{exact:true}).selectOption('found');await page.getByText('Add a name or helpful context',{exact:false}).click();await page.getByLabel('Business name',{exact:true}).fill('Browser new venture fixture input');await page.getByLabel('What would make this useful?').fill('Investigate an operating pilot using evidence and reversible work.');await page.getByRole('button',{name:'Start business investigation'}).click();await page.getByRole('heading',{name:'Your business, moving forward.'}).waitFor();
 await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Results',exact:true}).click();await page.getByRole('button',{name:'Record result or feedback'}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Evidence type',{exact:true}).selectOption('pending_feedback');await dialog.getByLabel('What did you observe or expect to learn?').fill('Awaiting a consenting operator to inspect the prepared workflow.');await dialog.getByRole('button',{name:'Save evidence and next decision'}).click();await dialog.waitFor({state:'hidden'});await page.getByText('awaiting feedback',{exact:true}).waitFor();
 const businessId=await page.evaluate(()=>localStorage.getItem('midas-pilot-business'));assert.equal(service.operatingOutcomes.list(businessId).length,0);await page.screenshot({path:join(root,'pending-desktop.png'),fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'Record the feedback'}).click();await dialog.getByLabel('Evidence type',{exact:true}).selectOption('measurement');await dialog.getByLabel('Observed result',{exact:true}).selectOption('improved');await dialog.getByLabel('What did you observe or expect to learn?').fill('Development browser verification: inquiry completeness counts were recorded in a controlled local fixture.');await dialog.getByLabel('Metric',{exact:true}).fill('Complete inquiries');await dialog.getByLabel('Unit',{exact:true}).fill('inquiries');await dialog.getByLabel('Observed value',{exact:true}).fill('7');await dialog.getByLabel('Baseline value',{exact:false}).fill('5');await dialog.getByLabel('Observation count',{exact:true}).fill('12');await dialog.getByLabel('Window starts',{exact:true}).fill('2026-08-01');await dialog.getByLabel('Window ends',{exact:true}).fill('2026-09-01');await dialog.getByLabel('I checked that the instrument',{exact:false}).check();await dialog.getByRole('button',{name:'Save evidence and next decision'}).click();await dialog.waitFor({state:'hidden'});await page.getByText('needs authority',{exact:true}).waitFor();assert.equal(service.observationLoop.view(businessId).observations.length,2);assert.equal(service.operatingOutcomes.list(businessId).length,1);
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:join(root,'observation-phone.png'),fullPage:true,animations:'disabled'});await page.reload();await page.getByText('needs authority',{exact:true}).waitFor();await page.getByRole('button',{name:'Reject follow-up',exact:true}).click();await dialog.getByLabel('Reason',{exact:true}).fill('The owner declines this review until a real pilot is available.');await dialog.getByRole('button',{name:'Reject follow-up',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.equal(service.observationLoop.view(businessId).decisions[1].state,'rejected');assert.deepEqual(errors,[]);assert.equal(service.view(businessId).accounting.providerCalls,0);console.log(JSON.stringify({browserEvidence:root,desktop:'1440x1000',phone:'390x844',providerCalls:0}));
 }finally{if(browser)await browser.close();await app.close();service.store.close();}
});
