import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,realpathSync} from 'node:fs';
import {join,relative,isAbsolute} from 'node:path';
import {tmpdir} from 'node:os';
import {StateStore} from '../src/state.ts';
import {hash} from '../src/contracts.ts';
import {keypair} from '../src/experiment/config.ts';
import {PilotKnowledge} from '../src/pilot/knowledge.ts';
import {PilotExecution} from '../src/pilot/execution.ts';
import {PilotIntelligence} from '../src/pilot/intelligence.ts';
import {PilotDiscovery,discoverySchema} from '../src/pilot/discovery.ts';
import {commercialCases,fixtureCommercialOutput} from '../src/pilot/intelligence-fixtures.ts';
import {fixturePilotWorker} from '../src/pilot/fixtures-execution.ts';
import {prepareIntelligenceAuthorization,signIntelligenceProposal,loadAuthorizedIntelligence,readIntelligenceAccounting,readIntelligenceAuthority} from '../src/pilot/intelligence-authorized.ts';
async function setup(){
 const root=mkdtempSync(join(tmpdir(),'midas-outcome-authorized-')),store=new StateStore(join(root,'pilot.sqlite')),knowledge=new PilotKnowledge(store),sample=commercialCases.service,c=knowledge.createCompany({name:sample.name,website:sample.website,goal:sample.goal,notes:sample.notes,mode:'fixture'});
 for(const p of sample.pages)knowledge.addSource(c.id,{title:p.title,text:p.text,kind:'website',rights:'Developer-authored synthetic material',observedAt:new Date().toISOString()});
 const x=new PilotExecution(store,{root}),intelligence=new PilotIntelligence(store,x),discovery=new PilotDiscovery(store,{root,knowledge}),services={intelligence,discovery};discovery.start(c.id,{website:c.website,limits:{maxDecisions:6}});
 const prepared=prepareIntelligenceAuthorization(services,{root,directory:join(root,'proposal'),id:'intelligence-033-test',businessId:c.id,projectId:'proj_OFFLINE_TEST',credentialFile:null,expiresAt:new Date(Date.now()+3600000).toISOString(),countUncertaintyMinor:275,includeCorrection:true,includeImages:true,mode:'mock'}),keys=keypair();
 const signed=signIntelligenceProposal(services,root,{proposal:prepared.proposal,expectedHash:prepared.proposalHash,principal:'ephemeral-test-owner',approvalReference:'Mock only, no actual provider authority',...keys});
 const terminal=new Map<string,any>();let counts=0,creates=0,reads=0,loseCreate=false,loseGet=false,failedTerminal=false;
 const transport=(async(url:any,init:any)=>{const u=String(url);if(u.endsWith('/input_tokens')){counts++;return Response.json({object:'response.input_tokens',input_tokens:100});}if(init.method==='POST'){creates++;assert.equal(u,'https://api.openai.com/v1/responses');const body=JSON.parse(init.body);assert.equal(body.reasoning.effort,'max');assert.equal(body.max_output_tokens,32768);assert.equal(body.model,'gpt-6-astra');if(loseCreate)throw Error('Lost create: explicit offline fixture');const payload=JSON.parse(body.input);let output:any;
  if(payload.context.version==='business-public-discovery-033-v1')output={action:'finish',reason:'The selected synthetic public corpus is sufficient for a bounded initial analysis; customer economics remain unknown.',sourceId:null,url:null,unresolved:['No real customer behavior or economics has been observed.']};
  else if(payload.context.executableJobs)output=fixtureCommercialOutput('service',payload.context.sources);
  else output=(await fixturePilotWorker().run({request:{context:payload.context}} as any)).output;
  const id='resp_intelligence_test_'+creates;terminal.set(id,{id,model:'gpt-6-astra',status:'completed',service_tier:'default',background:true,store:true,usage:{input_tokens:100,output_tokens:100},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(output)}]}]});return Response.json({id,model:'gpt-6-astra',status:'queued',background:true,store:true,usage:null,output:[]});}
  assert.equal(init.method,'GET');if(loseGet)throw Error('Lost retrieval: explicit offline fixture');const id=u.split('/').at(-1)!;assert(terminal.has(id));reads++;return Response.json(failedTerminal?{...terminal.get(id),status:'failed',usage:null,output:[],error:{code:'insufficient_quota',message:'Explicit failed-provider mock; no API activity.'}}:terminal.get(id));}) as typeof fetch;
 return {root,store,knowledge,c,x,intelligence,discovery,services,prepared,keys,signed,transport,load:()=>loadAuthorizedIntelligence(services,root,{execution:{kind:'mock',transport}}),stats:()=>({counts,creates,reads}),failTerminal:()=>{failedTerminal=true;},loseCreate:()=>{loseCreate=true;},loseGet:(value:boolean)=>{loseGet=value;},close(){store.close();const p=realpathSync(root),r=relative(realpathSync(tmpdir()),p);assert(r&&!r.startsWith('..')&&!isAbsolute(r));rmSync(p,{recursive:true,force:true});}};
}
test('signed dynamic outcome executes discovery, analysis, owner-selected campaign and actual checked page without fixture-to-provider fallback',async()=>{const f=await setup();try{
 assert.equal(f.prepared.proposal.limits.totalMinor,5400);assert.equal(f.prepared.summary.approved,false);const runner=f.load();await runner.runInvestigation();await runner.runAnalysis();assert.equal(f.intelligence.view(f.c.id).status,'proposal_ready');assert.equal(f.x.tasks(f.c.id).length,0);
 const selected=f.intelligence.select(f.c.id,'clarify-first-step');assert.equal(selected.task.resource.modelCalls,6);await runner.runTask(selected.task.id);assert.equal(f.x.portfolio.getTask(selected.task.id).status,'completed',f.x.portfolio.getTask(selected.task.id).reason);
 const page=f.intelligence.materialize(f.c.id)[0];assert.equal(page.resource.modelCalls,8);await runner.runTask(page.id);assert.equal(f.x.portfolio.getTask(page.id).status,'completed',f.x.portfolio.getTask(page.id).reason);assert(f.x.artifact(f.c.id,page.id).checks.every((r:any)=>r.passed));assert.match(f.x.download(f.c.id,page.id,'app.html').content,/data-campaign-offer/);
 assert.deepEqual(f.stats(),{counts:7,creates:7,reads:7});assert.equal(runner.totals().providerRequests,0);assert.equal(runner.totals().retainedMinor,1710);assert.equal(runner.totals().stageUsage.page.used,3);await f.load().runTask(page.id);assert.deepEqual(f.stats(),{counts:7,creates:7,reads:7});
 const corrected=f.x.correct({businessId:f.c.id,taskId:page.id,artifactHash:f.x.artifact(f.c.id,page.id).hash,instruction:'Prepare an owner-reviewed reporting readiness discussion before requesting any system access.'});assert.equal(corrected.resource.modelCalls,4);await runner.runTask(corrected.id);assert.equal(f.x.portfolio.getTask(corrected.id).status,'completed',f.x.portfolio.getTask(corrected.id).reason);assert.equal(runner.totals().stageUsage.correction.used,3);
 }finally{f.close();}});
test('new admissions require exact bound owner sources, procedure and owner-selected task',async()=>{for(const mutation of ['context','source','task'] as const){const f=await setup();try{const runner=f.load();if(mutation==='context')f.knowledge.updateCompany(f.c.id,{goal:'A changed owner outcome'});if(mutation==='source')f.knowledge.addSource(f.c.id,{title:'Unrelated later upload',text:'This source was not selected in the approved initial bundle or discovered by its permitted session.',kind:'notes',rights:'Synthetic fixture',observedAt:new Date().toISOString()});if(mutation==='task'){const task=f.x.plan({business:f.knowledge.company(f.c.id),sources:f.knowledge.sources(f.c.id),workflow:'campaign-packet'});await assert.rejects(()=>runner.runTask(task.id),/OWNER_SELECTED_WORK/);}else await assert.rejects(()=>runner.runInvestigation(),/OWNER_CONTEXT_CHANGED|UNGRANTED_SOURCE/);assert.deepEqual(f.stats(),{counts:0,creates:0,reads:0});}finally{f.close();}}});
test('unknown creation retains the admitted exposure and cannot be resent with a fresh or repeated identity',async()=>{const f=await setup();try{f.loseCreate();const r=f.load();await assert.rejects(()=>r.runInvestigation(),/Lost create|NETWORK|BACKGROUND|FETCH|TRANSPORT/);assert.deepEqual(f.stats(),{counts:1,creates:1,reads:0});assert.equal(r.totals().retainedMinor,480);await assert.rejects(()=>f.load().runInvestigation(),/UNKNOWN_NO_RESUBMIT/);assert.deepEqual(f.stats(),{counts:1,creates:1,reads:0});}finally{f.close();}});
test('same-ID retrieval survives restart and changed owner context without admitting another inference',async()=>{const f=await setup();try{f.loseGet(true);await assert.rejects(()=>f.load().runInvestigation());assert.deepEqual(f.stats(),{counts:1,creates:1,reads:0});f.knowledge.updateCompany(f.c.id,{goal:'Changed after the preserved response identity'});f.loseGet(false);await f.load().runInvestigation();assert.deepEqual(f.stats(),{counts:1,creates:1,reads:1});await assert.rejects(()=>f.load().runAnalysis(),/OWNER_CONTEXT_CHANGED/);assert.deepEqual(f.stats(),{counts:1,creates:1,reads:1});}finally{f.close();}});
test('stable task intents prevent duplicate plans and preserve publisher attribution',async()=>{const f=await setup();try{const origin={kind:'public-retrieval' as const,url:'https://publisher.example/scope',recordId:'retained-public-1',contentHash:hash('publisher text'),extraction:'Exact retained text excerpt',provenance:'runtime_public_retrieval'};const source=f.knowledge.addSource(f.c.id,{title:'Publisher policy',text:'A publisher says its service needs owner scoping before delivery.',kind:'website',rights:'Public read-only',observedAt:new Date().toISOString()},origin),input={taskId:'stable-campaign-work',business:f.knowledge.company(f.c.id),sources:[source],workflow:'campaign-packet' as const};const a=f.x.plan(input),b=f.x.plan(input);assert.equal(a.id,b.id);assert.equal(f.x.tasks(f.c.id).length,1);assert.throws(()=>f.x.plan({...input,job:{title:'Changed task',outcome:'Changed requested outcome',details:'Changed details'}}),/STABLE_TASK_BINDING_CHANGED/);const imported=f.x.evidence.forTask(a)[0];assert.equal(imported.url,origin.url);assert.equal(imported.textKind,'exact_excerpt');assert.equal(imported.rights,'public_readonly');assert.equal(JSON.parse(imported.interpretation!).origin.recordId,origin.recordId);}finally{f.close();}});
test('existing shared ledger applies stage caps without borrowing unused downstream admissions',async()=>{const f=await setup();try{const r=f.load(),request=f.prepared.proposal.intelligence.initialRequest.request,principal={id:'ephemeral-test-owner',tenantId:'mason',businessId:f.c.id,permissions:['operate']};const invoke=(i:number)=>r.models.invoke(principal,{businessId:f.c.id,goalHash:hash(f.c.goal),sourceHosts:[],attemptId:'stage-cap-'+i,stage:'investigation',request:{...request,requestId:'stage-cap-'+i},schema:discoverySchema,validate:()=>{}});for(let i=0;i<6;i++)await invoke(i);await assert.rejects(()=>invoke(6),/CAP|ALLOCATION|BUDGET|LIMIT/);assert.deepEqual(f.stats(),{counts:6,creates:6,reads:6});assert.equal(r.totals().stageUsage.investigation.used,6);assert.equal(r.totals().stageUsage.campaign.used,0);assert.equal(r.totals().callsUsed,6);}finally{f.close();}});
test('historical accounting remains visible after source changes with unknown usage distinguished from billing',async()=>{const f=await setup();try{f.loseCreate();await assert.rejects(()=>f.load().runInvestigation());f.knowledge.updateCompany(f.c.id,{goal:'Changed scope after unresolved creation'});const a=readIntelligenceAccounting(f.store,f.root);assert.equal(a.status,'signed_ledger');assert.equal(a.callsUsed,1);assert.equal(a.retainedMinor,480);assert.equal(a.provisionalMinor,null);assert.equal(a.settledMinor,null);assert.equal(a.unknownCostAttempts,1);assert.equal(a.providerRequests,0);assert.equal(a.inferenceDispatches,1);assert.equal(a.remainingMinor,4920);assert(a.accountIdentity);}finally{f.close();}});

test('known terminal failure remains terminal without usage and is not retrieved or inferred again',async()=>{const f=await setup();try{f.failTerminal();await assert.rejects(()=>f.load().runInvestigation(),/MODEL_RESPONSE_FAILED/);const view=f.discovery.view(f.c.id);assert.equal(view.decisions[0].status,'terminal_failed');assert.deepEqual(f.stats(),{counts:1,creates:1,reads:1});await f.load().runInvestigation();assert.deepEqual(f.stats(),{counts:1,creates:1,reads:1});const account=readIntelligenceAccounting(f.store,f.root);assert.equal(account.retainedMinor,480);assert.equal(account.provisionalMinor,null);assert.equal(account.unknownCostAttempts,1);}finally{f.close();}});
test('authority status is a read-only view and never enables a mock grant as live execution',async()=>{const f=await setup();try{const snapshot=()=>hash(JSON.stringify(f.store.db.prepare('SELECT kind,key,body,version FROM entities ORDER BY kind,key').all())),before=snapshot(),status=readIntelligenceAuthority(f.services,f.root);assert.equal(status.approved,true);assert.equal(status.current,true);assert.equal(status.liveEnabled,false);assert.equal(status.mode,'mock');assert.equal(status.credentialRead,false);assert.equal(snapshot(),before);assert.deepEqual(f.stats(),{counts:0,creates:0,reads:0});}finally{f.close();}});
