import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync,mkdtempSync,rmSync,realpathSync}from'node:fs';import{tmpdir}from'node:os';import{join,resolve,relative,isAbsolute}from'node:path';
import{prepareCreditContinuation}from'../tools/prepare-credit-continuation-r5.mjs';import{inspectCreditParent,validateCreditContinuation,R5_TASKS}from'../src/portfolio/continuation-r5.ts';import{StateStore}from'../src/state.ts';import{ModelLedger}from'../src/experiment/ledger.ts';import{hash,rawHash,canonical}from'../src/contracts.ts';import{Portfolio}from'../src/portfolio/core.ts';import{PortfolioEngine}from'../src/portfolio/engine.ts';import{LocalWorkTools}from'../src/portfolio/tools.ts';import{EvidenceLibrary}from'../src/portfolio/evidence.ts';import{portfolioScope}from'../src/portfolio/contracts.ts';import{stageContractForTask,stageContractSet,CREDIT_CONTINUATION_KIND,validateStageOutput}from'../src/portfolio/stage-contracts.ts';import{buildResponsesBody}from'../src/model-port.ts';import{portfolioTaskRoute}from'../src/portfolio/live.ts';
const parent=resolve('../foundry-worktree-031-contracts-r4/var/portfolio-031-continuation-r4'),backup=parent+'-stop-backup',key=readFileSync(join(parent,'auth/portfolio-owner.pub'),'utf8');
test('exact R5 preparation preserves credit failure, raw research, scopes tasks and enforces 2665-cent capacity',async()=>{
 const temp=mkdtempSync(join(tmpdir(),'midas-credit-r5-')),root=join(temp,'run');try{
 const before=inspectCreditParent(parent,key);const prepared=await prepareCreditContinuation({root,parentRoot:parent,backupRoot:backup,manifestHash:'a19d45f11bb9a0ba6d31b4b7fb27c93cf32aa8d84b68c00d850412272c31e3b3'});const p=JSON.parse(readFileSync(join(prepared.output,'portfolio.authorization.request.json'),'utf8'));
 assert.equal(p.incrementalExposureMinor,2665);assert.equal(p.historicalRetainedMinor,1917);assert.equal(p.maximumExposureMinor,4582);assert.equal(p.inferenceAdmissions,14);assert.equal(p.countAdmissions,14);assert.equal(p.portfolio.recovery.maxAdmissions,0);
 assert.deepEqual(p.portfolio.tasks.map((t:any)=>t.workCalls),[1,5,4,3,1]);assert.deepEqual(p.portfolio.stageContracts.map((t:any)=>t.maxOutputTokens),[24576,32768,32768,24576,24576]);assert.equal(p.portfolio.route.reasoningEffort,'max');assert.equal(rawHash(readFileSync(join(prepared.output,'accepted-r1-brief.json'))),'fae4225c8d37b82b2ad8fc10a622988081538da7a794338e6bfac09bd583d34e');validateCreditContinuation(p.portfolio,key,false);
 for(const mutate of [(g:any)=>g.continuation.historical.reservedMinor=0,(g:any)=>g.tasks[3].workCalls=4,(g:any)=>g.continuation.diagnosticHash='0'.repeat(64),(g:any)=>g.route.reasoningEffort='high',(g:any)=>g.continuation.maxNewRetrievals=3600]){const g=structuredClone(p.portfolio);mutate(g);assert.throws(()=>validateCreditContinuation(g,key,false));}
 const store=new StateStore(join(root,'portfolio.sqlite'));try{
 const portfolio=new Portfolio(store),tools=new LocalWorkTools({root,store,scopeFor:portfolioScope}),engine=new PortfolioEngine({portfolio,tools,evidence:new EvidenceLibrary(store),accounting:()=>({taskAllocations:p.portfolio.tasks})});const preview=await engine.previewRequest(R5_TASKS[0].id),c=stageContractForTask(portfolio.getTask(R5_TASKS[0].id))!;
 assert.equal(canonical(buildResponsesBody(portfolioTaskRoute(p.portfolio.route,c),preview.request,preview.schema)),readFileSync(join(prepared.output,'initial-responses-bytes.json'),'utf8'));const text=canonical(preview.request);assert(!text.includes('existingUnstartedTaskIds'));assert(!text.includes('quote-desk/build-v4-r4'));assert(!text.includes('quote-desk/operate-v4-r3'));assert.equal(stageContractForTask(portfolio.getTask(R5_TASKS[3].id))?.ordinaryAdmissions,3);
 const context=preview.request.context as any,decision={decision:'stop',rationale:'Explicit offline contract fixture',strongestAlternative:{name:'Retain existing process',rationale:'No new engineering value in this fixture'},sourceRefs:[context.allowedReferenceIds[0]],blockingConditions:[]};assert.doesNotThrow(()=>validateStageOutput(portfolio.getTask(R5_TASKS[0].id),decision,context));assert.throws(()=>validateStageOutput(portfolio.getTask(R5_TASKS[0].id),{...decision,decision:'build',blockingConditions:['Unresolved required condition']},context));for(const t of p.portfolio.tasks)assert.equal(portfolio.getTask(t.id).attempts,0);
 }finally{store.close();}
 const bs=new StateStore(join(temp,'budget.sqlite'));try{const l=new ModelLedger(bs,p.operating.accountScope,hash(p.operating),p.operating.limits);let n=0;const admit=async(contract:string,cost:number)=>{const id='offline-'+(++n),bytes=JSON.stringify({id});await l.port('development',{businessId:'quote-desk',stage:'portfolio-work',stageContract:contract}).prepare!({scope:p.operating.accountScope,requestId:id,task:'operate',role:{},context:{},limits:{},tools:[]} as any,{currency:'USD',minorUnits:cost},rawHash(bytes),bytes);l.finish(id,null,'OFFLINE_FIXTURE');};for(let i=0;i<3;i++)await admit('operating-delivery-v1',164);await assert.rejects(admit('operating-delivery-v1',164),/ALLOCATION_ATTEMPT_CAP/);for(const c of stageContractSet(CREDIT_CONTINUATION_KIND).filter(c=>c.id!=='operating-delivery-v1'))for(let i=0;i<c.ordinaryAdmissions;i++)await admit(c.id,c.maxCallCost.minorUnits);assert.equal(l.totals().reserved+1917,4582);assert.equal(l.totals().attempts,14);}finally{bs.close();}
 assert.equal(inspectCreditParent(parent,key).snapshotHash,before.snapshotHash);assert.equal(inspectCreditParent(parent,key).diagnosticHash,before.diagnosticHash);
 }finally{const path=realpathSync(temp),part=relative(realpathSync(tmpdir()),path);assert(part&&!part.startsWith('..')&&!isAbsolute(part));rmSync(path,{recursive:true,force:true});}
});

