import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { spawn } from 'node:child_process';
import { StateStore } from '../src/state.ts';
import { hash } from '../src/contracts.ts';
import { Portfolio } from '../src/portfolio/core.ts';
import type { TaskSpec } from '../src/portfolio/contracts.ts';
function setup() { const root = mkdtempSync(join(tmpdir(), 'portfolio-')); const file = join(root, 'state.sqlite'); let now = Date.now(); const store = new StateStore(file); const p = new Portfolio(store, { now: () => now, leaseMs: 100 }); p.createVenture({ id: 'a', name: 'Software', goal: 'Perform a useful job' }); p.createVenture({ id: 'b', name: 'Service', goal: 'Deliver useful work' }); p.registerWorker({ id: 'worker', name: 'Worker', competencies: ['build'], capabilities: ['build', 'portfolio.reassess'], maxConcurrency: 4 }); return { root, file, store, p, advance: () => now += 200, close: () => { store.close(); rmSync(root, { recursive: true, force: true }); } }; }
const task = (id: string, dependsOn: string[] = []): TaskSpec => ({ id, title: id, lane: 'build', capability: 'build', dependsOn, acceptance: ['Working result'], requiredChecks: ['working'], resource: { modelCalls: 2, localToolRuns: 2 } });
test('dependency graph, atomic claims across independent database connections, and finite step admission', () => { const s = setup(); const other = new StateStore(s.file); try { s.p.configure({ maxConcurrency: 2, resources: { workerSlots: 2, modelCalls: 1, localToolRuns: 2 } }); s.p.addPlan('a', { rationale: 'Build then verify', tasks: [task('one'), task('two', ['one'])] }); s.p.addPlan('b', { rationale: 'Independent service', tasks: [task('one')] }); const peer = new Portfolio(other); const lease = s.p.claimTask('a/one', 'worker')!; assert(lease); assert.equal(peer.claimTask('a/one', 'worker'), null); assert.equal(s.p.claimTask('a/two', 'worker'), null); const b = peer.claimTask('b/one', 'worker')!; assert(b); s.p.reserveStep(lease.task.id, lease.token, 'model', 'one'); assert.throws(() => peer.reserveStep(b.task.id, b.token, 'model', 'two'), /PORTFOLIO_RESOURCE_CAP/); s.p.finishStep(lease.task.id, lease.token, 'one'); assert.throws(() => s.p.complete(lease.task.id, lease.token, { checks: [{ id: 'irrelevant', passed: true, required: true }] }), /TASK_ACCEPTANCE_CHECK_FAILED/); s.p.complete(lease.task.id, lease.token, { checks: [{ id: 'working', passed: true }] }); assert(s.p.claimTask('a/two', 'worker')); const snapshot = s.p.snapshot(); assert.equal(snapshot.resources.used.modelCalls, 1); assert.equal(snapshot.resources.byVenture.a.used.modelCalls, 1); assert.equal(snapshot.resources.activeWorkerSlots, 2); assert.equal(snapshot.resources.monetaryCost, null); } finally { other.close(); s.close(); } });
test('restart reclaims undispatched work, fencing rejects old owner, and uncertain steps never automatically retry', () => { const s = setup(); try { s.p.addPlan('a', { rationale: 'Recovery', tasks: [task('safe'), task('unknown')] }); const old = s.p.claimTask('a/safe', 'worker')!; s.advance(); s.p.recover(); const fresh = s.p.claimTask('a/safe', 'worker')!; assert.notEqual(fresh.token, old.token); assert.throws(() => s.p.heartbeat('a/safe', old.token), /TASK_LEASE_MISMATCH/); const unknown = s.p.claimTask('a/unknown', 'worker')!; s.p.reserveStep('a/unknown', unknown.token, 'tool', 'effect'); s.advance(); const recovered = s.p.recover(); assert.equal(recovered.find(t => t.id === 'a/unknown').status, 'needs_reconciliation'); assert.equal(s.p.claimTask('a/unknown', 'worker'), null); assert.equal(s.p.snapshot().resources.reserved.localToolRuns, 1); assert.equal(s.p.snapshot().resources.activeWorkerSlots, 0); } finally { s.close(); } });
test('changed authoritative artifact invalidates dependent work and rejects output from stale inputs', () => { const s = setup(); try { const a = s.p.publishArtifact('a', { id: 'source', title: 'Input', kind: 'document', content: 'v1', provenance: 'owner input' }); s.p.addPlan('a', { rationale: 'Use current input', tasks: [{ ...task('one'), inputArtifacts: [{ artifactId: a.id, version: a.version, sha256: a.sha256 }] }, task('two', ['one'])] }); const lease = s.p.claimTask('a/one', 'worker')!; s.p.publishArtifact('a', { id: 'source', title: 'Input', kind: 'document', content: 'v2', provenance: 'owner input' }); const result = s.p.complete('a/one', lease.token, { checks: [{ id: 'working', passed: true }], artifacts: [{ id: 'output', title: 'Old output', kind: 'document', content: 'old', provenance: 'runtime' }] }); assert.equal(result.status, 'stale'); assert.equal(s.p.getTask('a/two').status, 'stale'); assert.equal(s.p.snapshot().artifacts.length, 1); } finally { s.close(); } });
test('observations deduplicate reassessment and change persisted work, while pause isolates ventures', () => { const s = setup(); try { s.p.addPlan('a', { rationale: 'Original', tasks: [task('old')] }); s.p.addPlan('b', { rationale: 'Independent', tasks: [task('independent')] }); const input = { kind: 'defect', summary: 'Customer job fails', source: 'trusted check', provenance: 'observed local check' }; const first = s.p.recordObservation('a', input), second = s.p.recordObservation('a', input); assert.equal(second.duplicate, true); assert.equal(first.reassessmentTaskId, second.reassessmentTaskId); const lease = s.p.claimTask(first.reassessmentTaskId!, 'worker')!; const decision = s.p.applyReassessment(lease.task.id, lease.token, { rationale: 'Repair observed defect', cancelTaskIds: ['a/old'], priority: 80, tasks: [task('repair')] }); assert.equal(decision.observationIds[0], first.observation.id); assert.equal(s.p.getTask('a/old').status, 'cancelled'); assert.equal(s.p.getVenture('a').priority, 80); s.p.controlVenture('a', 'pause'); assert.equal(s.p.claimTask('a/repair', 'worker'), null); assert(s.p.claimTask('b/independent', 'worker')); s.p.controlVenture('a', 'resume'); assert(s.p.claimTask('a/repair', 'worker')); } finally { s.close(); } });
test('cycles and stale owner revisions do not partially persist a plan', () => { const s = setup(); try { assert.throws(() => s.p.addPlan('a', { rationale: 'Cycle', tasks: [task('one', ['two']), task('two', ['one'])] }), /TASK_DEPENDENCY_CYCLE/); assert.equal(s.p.snapshot().tasks.length, 0); assert.throws(() => s.p.addPlan('a', { rationale: 'Stale', tasks: [task('one')] }, 999), /VENTURE_REVISION_CHANGED/); assert.equal(s.p.snapshot().tasks.length, 0); } finally { s.close(); } });
test('two real worker processes contend for one persisted assignment', async () => { const s = setup(); try { s.p.addPlan('a', { rationale: 'Single owner', tasks: [task('contended')] }); const stateUrl = pathToFileURL(resolve('packages/foundry/src/state.ts')).href, coreUrl = pathToFileURL(resolve('packages/foundry/src/portfolio/core.ts')).href; const script = `import {StateStore} from ${JSON.stringify(stateUrl)}; import {Portfolio} from ${JSON.stringify(coreUrl)}; const store=new StateStore(process.argv[1]);const p=new Portfolio(store);const lease=p.claimTask('a/contended','worker',{leaseMs:60000});console.log(JSON.stringify({claimed:Boolean(lease),token:lease?.token??null}));store.close();`; const run = () => new Promise<any>((yes, no) => { const child = spawn(process.execPath, ['--input-type=module', '-e', script, s.file], { windowsHide: true }); let out = '', err = ''; child.stdout.on('data', d => out += d); child.stderr.on('data', d => err += d); child.on('error', no); child.on('exit', code => code === 0 ? yes(JSON.parse(out)) : no(Error(err))); }); const results = await Promise.all([run(), run()]); assert.equal(results.filter(r => r.claimed).length, 1); assert.equal(s.p.getTask('a/contended').attempts, 1); } finally { s.close(); } });
test('only a scoped durable response reconciles uncertainty; cancellation preserves retained exposure', () => { const s = setup(); try { s.p.addPlan('a', { rationale: 'Reconcile', tasks: [task('work')] }); const lease = s.p.claimTask('a/work', 'worker')!; s.p.reserveStep('a/work', lease.token, 'model', 'call'); s.advance(); s.p.recover(); s.p.controlTask('a/work', 'cancel'); assert.equal(s.p.getTask('a/work').status, 'needs_reconciliation'); const output = { answer: 'preserved' }, key = 'a/work/call', proof = { recordKind: 'portfolio-model-result' as const, recordKey: key, requestHash: hash('request'), outputHash: hash(output) }; assert.throws(() => s.p.reconcileStep('a/work', 'call', proof), /RECONCILIATION_DURABLE_RESPONSE_REQUIRED/); s.store.transaction(() => s.store.put('portfolio-model-result', key, { taskId: 'a/work', stepId: 'call', requestHash: proof.requestHash, outputHash: proof.outputHash, output }, null)); s.p.reconcileStep('a/work', 'call', proof); assert.equal(s.p.getTask('a/work').status, 'cancelled'); assert.equal(s.p.snapshot().resources.reserved.modelCalls, 0); assert.equal(s.p.snapshot().resources.used.modelCalls, 1); assert.equal(s.p.claimTask('a/work', 'worker'), null); } finally { s.close(); } });
test('pause during admitted work preserves output without publishing or allowing a new step', () => { const s = setup(); try { s.p.addPlan('a', { rationale: 'Pause boundary', tasks: [task('work')] }); const lease = s.p.claimTask('a/work', 'worker')!; s.p.reserveStep('a/work', lease.token, 'tool', 'read'); s.p.controlTask('a/work', 'pause'); assert.throws(() => s.p.reserveStep('a/work', lease.token, 'tool', 'next'), /TASK_NOT_RUNNING/); s.p.finishStep('a/work', lease.token, 'read'); const stopped = s.p.complete('a/work', lease.token, { checks: [{ id: 'working', passed: true }], artifacts: [{ id: 'held', title: 'Held', kind: 'report', provenance: 'runtime', content: 'retained' }] }); assert.equal(stopped.status, 'paused'); assert.equal(s.p.snapshot().artifacts.length, 0); assert.equal(stopped.result.artifacts.length, 0); s.p.controlTask('a/work', 'resume'); assert(s.p.claimTask('a/work', 'worker')); } finally { s.close(); } });
test('owner changes to completed outputs stale downstream work while a correction can publish its next input version', () => { const s = setup(); try { const input = { id: 'source', title: 'Source', kind: 'document', provenance: 'runtime', content: 'first' }; const source = s.p.publishArtifact('a', input); s.p.addPlan('a', { rationale: 'Correct and consume', tasks: [{ ...task('correct'), inputArtifacts: [{ artifactId: source.id, version: source.version, sha256: source.sha256 }] }, task('consume', ['correct'])] }); const lease = s.p.claimTask('a/correct', 'worker')!; s.p.complete('a/correct', lease.token, { checks: [{ id: 'working', passed: true }], artifacts: [{ ...input, content: 'corrected' }] }); assert.equal(s.p.getTask('a/correct').outputCurrent, true); assert.equal(s.p.getTask('a/correct').invalidatedAt, null); assert.equal(s.p.snapshot().tasks.find(t => t.id === 'a/consume')?.runnable, true); s.p.publishArtifact('a', { ...input, content: 'owner correction' }); assert.equal(s.p.getTask('a/correct').status, 'completed'); assert.equal(s.p.getTask('a/correct').outputCurrent, false); assert.equal(s.p.getTask('a/consume').status, 'stale'); assert.equal(s.p.claimTask('a/consume', 'worker'), null); } finally { s.close(); } });

test('ordinary planning applies decisions atomically and derived work retains the planner input lineage',()=>{
 const s=setup(),peer=new StateStore(s.file);try{
  s.p.registerWorker({id:'worker',name:'Worker',competencies:['build'],capabilities:['build','portfolio.plan'],maxConcurrency:4});
  const source=s.p.publishArtifact('a',{id:'reviewed-source',title:'Reviewed source',kind:'document',provenance:'owner input',content:'version one'});
  s.p.addPlan('a',{rationale:'Choose next useful work',tasks:[task('obsolete'),{...task('planner'),capability:'portfolio.plan',inputArtifacts:[{artifactId:source.id,version:source.version,sha256:source.sha256}]}]});
  const lease=s.p.claimTask('a/planner','worker')!,input={rationale:'Replace the unstarted work with a better evidence-backed task',summary:'Bounded next action',tasks:[task('child')],cancelTaskIds:['a/obsolete'],priority:80,evidenceIds:['recorded-source'],checks:[{id:'working',passed:true}],artifacts:[{id:'proposal',title:'Next work proposal',kind:'business_proposal',content:'Observed source supports this next action',provenance:'test runtime'}]};
  const original=s.store.record.bind(s.store),beforeRecords=s.store.db.prepare('SELECT count(*) AS n FROM records').get()!.n;
  s.store.record=(scope,id,kind,value,parents)=>{if(kind==='PortfolioTaskResult'){assert.equal(peer.get('portfolio-task','a/child'),null,'another scheduler cannot see or claim a partially applied child');assert.equal(peer.get('portfolio-task','a/obsolete').status,'queued');assert.equal(peer.get('portfolio-venture','a').priority,50);throw Error('simulated failure before checked completion');}return original(scope,id,kind,value,parents);};
  assert.throws(()=>s.p.applyPlanning(lease.task.id,lease.token,input),/simulated failure/);s.store.record=original;
  assert.equal(s.store.get('portfolio-task','a/child'),null);assert.equal(s.p.getTask('a/obsolete').status,'queued');assert.equal(s.p.getTask('a/planner').status,'running');assert.equal(s.p.getVenture('a').priority,50);assert.equal(s.p.snapshot().decisions.length,0);assert.equal(s.store.db.prepare('SELECT count(*) AS n FROM records').get()!.n,beforeRecords);
  const completed=s.p.applyPlanning(lease.task.id,lease.token,input);assert.equal(completed.status,'completed');assert.equal(s.p.getTask('a/obsolete').status,'cancelled');assert.equal(s.p.getVenture('a').priority,80);assert.equal(completed.result.output.priorPriority,50);assert.equal(completed.result.output.priority,80);assert.deepEqual(s.p.getTask('a/child').dependsOn,['a/planner']);assert.equal(s.p.snapshot().tasks.find(t=>t.id==='a/child')!.runnable,true);assert.equal(peer.get('portfolio-task','a/planner').status,'completed');assert.equal(peer.get('portfolio-task','a/child').status,'queued');
  s.p.publishArtifact('a',{id:'reviewed-source',title:'Reviewed source',kind:'document',provenance:'owner correction',content:'version two contradicts the prior basis'});assert.equal(s.p.getTask('a/planner').status,'completed');assert.equal(s.p.getTask('a/planner').outputCurrent,false);assert.equal(s.p.getTask('a/child').status,'stale');assert.equal(s.p.claimTask('a/child','worker'),null);
 }finally{peer.close();s.close();}
});

test('planning cannot cancel started, terminal, paused or other-venture work and invalid completion changes nothing',()=>{
 const s=setup();try{
  s.p.registerWorker({id:'worker',name:'Worker',competencies:['build'],capabilities:['build','portfolio.plan'],maxConcurrency:4});
  s.p.addPlan('a',{rationale:'Preserve work while planning',tasks:[task('queued'),task('running'),task('done'),task('cancelled'),task('paused'),{...task('planner'),capability:'portfolio.plan'}]});s.p.addPlan('b',{rationale:'Other venture owns its work',tasks:[task('other')]});
  s.p.claimTask('a/running','worker');const done=s.p.claimTask('a/done','worker')!;s.p.complete(done.task.id,done.token,{checks:[{id:'working',passed:true}]});s.p.controlTask('a/cancelled','cancel');s.p.controlTask('a/paused','pause');const lease=s.p.claimTask('a/planner','worker')!;
  for(const id of ['a/running','a/done','a/cancelled','a/paused','b/other','a/planner']){assert.throws(()=>s.p.applyPlanning(lease.task.id,lease.token,{rationale:'Unsupported cancellation',cancelTaskIds:['a/queued',id],priority:99,checks:[{id:'working',passed:true}]}),/PLANNING_CANNOT_CANCEL_STARTED_TASK|PLANNING_TASK_SCOPE/);assert.equal(s.p.getTask('a/queued').status,'queued');assert.equal(s.p.getVenture('a').priority,50);}
  assert.throws(()=>s.p.applyPlanning(lease.task.id,lease.token,{rationale:'Missing independent check',tasks:[task('child')],cancelTaskIds:['a/queued'],priority:99,checks:[]}),/TASK_ACCEPTANCE_CHECK_FAILED/);assert.equal(s.store.get('portfolio-task','a/child'),null);assert.equal(s.p.getTask('a/queued').status,'queued');assert.equal(s.p.getVenture('a').priority,50);assert.equal(s.p.snapshot().decisions.length,0);
 }finally{s.close();}
});
