import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { StateStore } from '../src/state.ts';
import { hash } from '../src/contracts.ts';
import { Portfolio } from '../src/portfolio/core.ts';
import { portfolioScope } from '../src/portfolio/contracts.ts';
import { PortfolioEngine } from '../src/portfolio/engine.ts';
import { EvidenceLibrary } from '../src/portfolio/evidence.ts';
import { LocalWorkTools } from '../src/portfolio/tools.ts';
import { preparePortfolio, offlinePortfolioModel } from '../src/portfolio/prepare.ts';
import { mockResult } from '../src/portfolio/worker.ts';
import type { WorkerModel } from '../src/portfolio/worker.ts';
import { ProcedureRegistry } from '../src/portfolio/learning.ts';
import { WORKER_PROCEDURE } from '../src/portfolio/worker.ts';

function setup() {
 const root=mkdtempSync(join(tmpdir(),'portfolio-engine-')),file=join(root,'state.sqlite'),store=new StateStore(file),portfolio=new Portfolio(store),tools=new LocalWorkTools({root,store,scopeFor:portfolioScope}),evidence=new EvidenceLibrary(store);
 preparePortfolio(portfolio,tools,evidence);let calls=0;const mock=offlinePortfolioModel(tools),model:WorkerModel={kind:'offline_mock',async run(call){calls++;return mock.run(call);}};
 const engine=new PortfolioEngine({portfolio,tools,evidence,model});return {root,file,store,portfolio,tools,evidence,engine,model,calls:()=>calls,close:()=>{store.close();rmSync(root,{recursive:true,force:true});}};
}
const crash=()=>Object.assign(Error('simulated crash after durable persistence'),{simulatedCrash:true});

test('common runtime fulfills three jobs, corrects observed defects, verifies delivery and changes allocation',{timeout:90000},async()=>{
 const f=setup();try{
  await f.engine.drain();const snapshot=f.portfolio.snapshot(),work=snapshot.tasks.filter(t=>t.localId==='fulfill');
  assert.equal(work.length,3);assert(work.every(t=>t.status==='completed'),JSON.stringify(work.map(t=>({id:t.id,status:t.status,reason:t.reason}))));
  for(const task of work){const w=f.tools.load(task.ventureId,task.id);assert.equal(w.manifest.revision,2);assert(w.published);assert(task.result.checks.some((c:any)=>c.id==='delivery.current'&&c.passed));assert.equal(task.result.artifacts.length,1);const observations=f.store.get('portfolio-execution',task.id).observations;assert(observations.some((o:any)=>o.tool==='check.run'&&!o.result.ok));assert.equal(observations.filter((o:any)=>o.tool==='workspace.replace').length,1);const bundle=JSON.parse(f.tools.download(task.ventureId,task.id).content);assert.equal(bundle.manifest.sha256,w.manifest.sha256);assert.equal(bundle.delivery.customerAcknowledged,false);}
  assert.equal(snapshot.decisions.length,3);assert(snapshot.ventures.every(v=>v.priority===45));assert(snapshot.tasks.filter(t=>t.capability==='portfolio.reassess').every(t=>t.status==='completed'));assert.equal(snapshot.resources.used.modelCalls,f.calls());assert.equal(snapshot.resources.reserved.modelCalls,0);assert.equal(snapshot.resources.activeWorkerSlots,0);assert.equal(snapshot.resources.monetaryCost,null);assert(snapshot.ventures.every(v=>v.economics.revenue===null));
  const callCount=f.calls();await f.engine.drain();assert.equal(f.calls(),callCount,'completed work and retained grant gates do not repeat');
 }finally{f.close();}
});

for(const phase of ['model','tool'] as const)test('restart after durable '+phase+' output reuses the same result and edit identity',{timeout:30000},async()=>{
 const f=setup();try{
  const id='release-readiness/fulfill';let hit=false;
  f.engine.afterPersist=(kind,taskId)=>{if(!hit&&kind===phase&&taskId===id){hit=true;throw crash();}};
  await assert.rejects(()=>f.engine.runTask(id),/simulated crash/);assert(hit);const count=f.calls();
  // Emulate process death using the deterministic owner liveness boundary. A new
  // engine and SQLite connection then read the existing checkpoint.
  f.portfolio.recover({ownerAlive:()=>false});const reopened=new StateStore(f.file);
  try{const p=new Portfolio(reopened),tools=new LocalWorkTools({root:f.root,store:reopened,scopeFor:portfolioScope}),evidence=new EvidenceLibrary(reopened),engine=new PortfolioEngine({portfolio:p,tools,evidence,model:f.model});const recovered=await engine.recover();assert.equal(recovered.pending.length,0);assert.equal(f.calls(),count);await engine.runTask(id);assert.equal(p.getTask(id).status,'completed',p.getTask(id).reason);assert.equal(f.calls(),6,'same six model decisions; no duplicate inference');assert.equal(tools.load('release-readiness',id).manifest.revision,2);assert.equal(engine.rows('portfolio-tool-intent').filter(r=>r.call.name==='workspace.replace').length,1);assert.equal(p.snapshot().resources.reserved.modelCalls,0);assert.equal(p.snapshot().resources.reserved.localToolRuns,0);}finally{reopened.close();}
 }finally{f.close();}
});

test('crash after a local edit but before engine output persistence recovers the durable operation',{timeout:30000},async()=>{
 const f=setup();try{const id='release-readiness/fulfill',original=f.tools.execute.bind(f.tools);let hit=false;f.tools.execute=async call=>{const result=await original(call);if(!hit&&call.tool==='workspace.replace'){hit=true;throw crash();}return result;};await assert.rejects(()=>f.engine.runTask(id),/simulated crash/);assert.equal(f.tools.load('release-readiness',id).manifest.revision,2);f.portfolio.recover({ownerAlive:()=>false});f.tools.execute=original;const engine=new PortfolioEngine({portfolio:f.portfolio,tools:f.tools,evidence:f.evidence,model:f.model});const recovered=await engine.recover();assert.equal(recovered.pending.length,0);await engine.runTask(id);assert.equal(f.portfolio.getTask(id).status,'completed');assert.equal(f.tools.load('release-readiness',id).manifest.revision,2);assert.equal(f.calls(),6);}finally{f.close();}
});

test('received invalid model output is retained as a known failure; absent output remains uncertain',{timeout:30000},async()=>{
 for(const uncertain of [false,true]){const f=setup();try{let calls=0;const model:WorkerModel={kind:'offline_mock',async run(){calls++;if(uncertain)throw Error('transport interrupted without response');return mockResult({action:'complete',reason:'I claim success',toolCall:{name:'shell.exec'}});}},engine=new PortfolioEngine({portfolio:f.portfolio,tools:f.tools,evidence:f.evidence,model});await engine.runTask('release-readiness/fulfill');const task=f.portfolio.getTask('release-readiness/fulfill');assert.equal(task.status,uncertain?'needs_reconciliation':'blocked');assert.equal(engine.rows('portfolio-model-result').length,uncertain?0:1);assert.equal(f.portfolio.snapshot().resources.reserved.modelCalls,uncertain?1:0);assert.equal(f.portfolio.snapshot().artifacts.length,0);await engine.recover();await engine.drain();assert.equal(calls,uncertain?3:3,'other two independent ventures may attempt once; failed assignment is not redispatched');assert.equal(f.portfolio.getTask('release-readiness/fulfill').attempts,1);}finally{f.close();}}
});

test('model completion cannot bypass required tool checks and local delivery readback',async()=>{const f=setup();try{let calls=0;const engine=new PortfolioEngine({portfolio:f.portfolio,tools:f.tools,evidence:f.evidence,model:{kind:'offline_mock',async run(){calls++;return mockResult({action:'complete',reason:'Trust me, everything works',toolCall:null});}}});await engine.runTask('release-readiness/fulfill');assert.equal(calls,1);assert.equal(f.portfolio.getTask('release-readiness/fulfill').status,'blocked');assert.match(f.portfolio.getTask('release-readiness/fulfill').reason,/CURRENT_DELIVERY_REQUIRED/);assert.equal(f.portfolio.snapshot().artifacts.length,0);}finally{f.close();}});

test('dynamic planning persists source-checked tasks and visibly blocks missing executable capability',async()=>{const f=setup();try{f.portfolio.addPlan('release-readiness',{id:'dynamic',rationale:'Plan from supplied sources',tasks:[{id:'plan-now',title:'Plan next work',lane:'research',capability:'portfolio.plan',dependsOn:[],acceptance:['A checked plan'],requiredChecks:['proposal.reference_checks'],allowedTools:[],resource:{modelCalls:1}}]});const proposal={summary:'A new capability is needed',claims:[],contradictions:[],unknowns:['Buyer acceptance is unknown'],alternatives:[],priority:50,rationale:'Build a bounded new product with a real acceptance contract',cancelTaskIds:[],tasks:[{id:'new-software',title:'Build another product',objective:'Perform its customer job',lane:'build',capability:'software.build',dependsOn:[],acceptance:['Correct core job and persistence'],requiredCompetencies:[],allowedTools:['workspace.read','workspace.replace','check.run','artifact.publish_local'],priority:50}]};let calls=0;const engine=new PortfolioEngine({portfolio:f.portfolio,tools:f.tools,evidence:f.evidence,model:{kind:'offline_mock',async run(){calls++;return mockResult(proposal);}}});await engine.runTask('release-readiness/plan-now');assert.equal(f.portfolio.getTask('release-readiness/plan-now').status,'completed');const created=f.portfolio.snapshot().tasks.find(t=>t.localId.startsWith('new-software-'))!;await engine.runTask(created.id);assert.equal(f.portfolio.getTask(created.id).status,'blocked');assert.match(f.portfolio.getTask(created.id).reason,/executable workspace/);assert.equal(calls,1,'missing capability does not buy a useless model call');}finally{f.close();}});

test('the exact job baseline is pinned in execution and every model request',{timeout:30000},async()=>{const f=setup();try{const registry=new ProcedureRegistry(f.store),scope={capability:'service.brief',population:'source-bound decision packets'},procedure=WORKER_PROCEDURE+' Review the exact source map for this scoped packet.';registry.baseline({id:'brief-baseline',scope,procedure,strongBaselineReference:'Excellent common operating instructions and source review checklist'});const original=f.portfolio.getTask('release-readiness/fulfill');f.store.transaction(()=>f.store.put('portfolio-task',original.id,{...original,inputs:{...original.inputs as object,procedureScope:scope,baselineProcedureId:'brief-baseline'}},original._version));const used:string[]=[];const mock=offlinePortfolioModel(f.tools),engine=new PortfolioEngine({portfolio:f.portfolio,tools:f.tools,evidence:f.evidence,model:{kind:'offline_mock',async run(call){used.push(call.request.role.procedure);return mock.run(call);}}});await engine.runTask(original.id);assert.equal(f.portfolio.getTask(original.id).status,'completed');assert(used.length>1&&used.every(p=>p===procedure));const state=f.store.get('portfolio-execution',original.id);assert.equal(state.procedureHash,hash(procedure));assert.equal(state.procedureSelection.procedureId,'brief-baseline');assert.equal(state.procedureSelection.adoption,null);assert.equal(f.portfolio.getTask(original.id).result.artifacts[0].metadata.procedureHash,hash(procedure));}finally{f.close();}});

test('a runtime correction updates the authoritative artifact and invalidates stale consumers',{timeout:30000},async()=>{const f=setup();try{const artifact=f.portfolio.publishArtifact('release-readiness',{id:'client-packet',title:'Initial client packet',kind:'service',content:'Requires correction',provenance:'owner input'}),original=f.portfolio.getTask('release-readiness/fulfill');f.store.transaction(()=>f.store.put('portfolio-task',original.id,{...original,inputs:{...original.inputs as object,authoritativeArtifactId:artifact.id},inputArtifacts:[{artifactId:artifact.id,version:artifact.version,sha256:artifact.sha256}]},original._version));f.portfolio.addPlan('release-readiness',{rationale:'Consume exactly the approved packet',tasks:[{id:'downstream',title:'Downstream review',lane:'build',capability:'service.brief',dependsOn:[],acceptance:['Current packet'],inputArtifacts:[{artifactId:artifact.id,version:artifact.version,sha256:artifact.sha256}]}]});await f.engine.runTask(original.id);const final=f.portfolio.getTask(original.id);assert.equal(final.status,'completed',final.reason);assert.equal(final.result.artifacts[0].id,artifact.id);assert.equal(final.result.artifacts[0].version,2);assert.equal(f.portfolio.snapshot().artifacts.filter(a=>a.ventureId==='release-readiness').length,1);assert.equal(f.portfolio.getTask('release-readiness/downstream').status,'stale');assert.equal(final.outputCurrent,true);}finally{f.close();}});

test('source change during model work preserves response but stales work before tool dispatch',async()=>{const f=setup();try{const mock=offlinePortfolioModel(f.tools);let calls=0;const engine=new PortfolioEngine({portfolio:f.portfolio,tools:f.tools,evidence:f.evidence,model:{kind:'offline_mock',async run(call){calls++;const source=f.evidence.list(call.ventureId)[0],{id,ventureId,revision,sha256,supersedes,...input}=source;f.evidence.add(call.ventureId,{...input,text:input.text+' New contradictory owner evidence.'});return mock.run(call);}}});await engine.runTask('release-readiness/fulfill');const task=f.portfolio.getTask('release-readiness/fulfill');assert.equal(task.status,'stale');assert.equal(calls,1);assert.equal(engine.rows('portfolio-model-result').length,1);assert.equal(engine.rows('portfolio-tool-intent').length,0);assert.equal(f.portfolio.snapshot().resources.used.modelCalls,1);assert.equal(f.portfolio.getTask('release-readiness/live-investigation').status,'stale');}finally{f.close();}});

for(const capability of ['service.brief','research.investigate'])test('dynamic '+capability+' planning creates and fills a blank source-bound workspace',{timeout:30000},async()=>{const f=setup();try{
 const ventureId=capability==='service.brief'?'release-readiness':'midas-intelligence',planId=ventureId+'/plan-dynamic';
 f.portfolio.addPlan(ventureId,{rationale:'Derive substantive work from the present evidence',tasks:[{id:'plan-dynamic',title:'Plan a sourced next deliverable',lane:'research',capability:'portfolio.plan',dependsOn:[],acceptance:['Useful source-linked work'],requiredChecks:['proposal.reference_checks'],allowedTools:[],inputs:{dynamicCapability:capability}}]});
 const mock=offlinePortfolioModel(f.tools);let preparations=0,modelCalls=0;
 const engine=new PortfolioEngine({portfolio:f.portfolio,tools:f.tools,evidence:f.evidence,prepareTask:task=>{preparations++;const sources=f.evidence.list(task.ventureId),venture=f.portfolio.getVenture(task.ventureId);f.tools.seed(task.ventureId,task.id,{kind:'service',files:[{path:'brief.json',content:'{}'}],inputs:{title:task.title,client:venture.name,asOf:'2026-09-12',sources:sources.map(s=>({id:s.id,title:s.title,text:s.text,rights:s.rights})),requiredSourceIds:sources.map(s=>s.id)},provenance:'Controller-created blank workspace; fixture runtime authors output from the supplied evidence'});},model:{kind:'offline_mock',async run(call){modelCalls++;const context=call.request.context as any;if(context.task.inputs?.dynamicCapability){assert(context.capabilityProfiles[capability].requiredTools.includes('check.run'));const source=context.sources[0];return mockResult({summary:'Produce a complete brief from the permitted source context',claims:[{kind:'source_assertion',text:'The supplied source states the operating context',sourceId:source.id,quote:source.text.slice(0,100)}],contradictions:[],unknowns:['Whether an owner accepts this output as useful remains unobserved'],alternatives:[],priority:50,rationale:'The next reversible step is an inspectable sourced packet',cancelTaskIds:[],tasks:[{id:'new-packet',title:capability==='service.brief'?'Scoped service validation packet':'Operating evidence investigation',objective:'Create a useful complete source-grounded deliverable from the current permitted evidence',lane:'build',capability,dependsOn:[],acceptance:['Current source coverage and grounded claims','Accountable actions and honest unknowns'],requiredCompetencies:['source-review'],allowedTools:['workspace.read','workspace.replace','check.run','artifact.publish_local'],priority:50}]});}return mock.run(call);}}});
 await engine.runTask(planId);const child=f.portfolio.snapshot(ventureId).tasks.find(t=>t.localId.startsWith('new-packet-'))!;assert(child);assert.throws(()=>f.tools.load(ventureId,child.id),/WORKSPACE_NOT_FOUND/);await engine.runTask(child.id);const completed=f.portfolio.getTask(child.id);assert.equal(completed.status,'completed',completed.reason);assert.equal(preparations,1);assert.equal(modelCalls,7);const workspace=f.tools.load(ventureId,child.id),report=JSON.parse(workspace.files.find(x=>x.path==='brief.json')!.content);assert.equal(workspace.manifest.revision,2);assert.equal(report.title,child.title);assert.equal(report.client,f.portfolio.getVenture(ventureId).name);assert(report.observations.every((o:any)=>workspace.inputs.sources.find((s:any)=>s.id===o.sourceId)?.text.includes(o.quote)));assert.equal(JSON.parse(f.tools.download(ventureId,child.id).content).delivery.customerAcknowledged,false);assert.equal(completed.result.artifacts.length,1);
 }finally{f.close();}});
