import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { StateStore } from '../src/state.ts';
import { LocalWorkTools } from '../src/portfolio/tools.ts';
import { quoteTrackerFiles, serviceBriefFiles, defaultServiceInputs, developerProvenance, checkServiceBrief } from '../src/portfolio/products.ts';
import { InteractivePreviewSessions, validateQuoteState, renderRemotePreview } from '../src/portfolio/preview.ts';

function fixture(){const root=mkdtempSync(join(tmpdir(),'midas-local-tools-')),store=new StateStore(join(root,'state.sqlite'));const tools=new LocalWorkTools({root,store,scopeFor:businessId=>({tenantId:'test',businessId,runId:'portfolio',dataPolicyVersion:'v1',mode:'fixture'})});return {root,store,tools,close:()=>{store.close();rmSync(root,{recursive:true,force:true});}};}
const call=(tools:LocalWorkTools,taskId:string,tool:string,args:any={},operationId?:string)=>tools.execute({ventureId:'venture',taskId,tool,args,operationId});

test('shared revision tools repair a source-supported service and publish authenticated local readback',async()=>{
 const f=fixture();try{f.tools.seed('venture','brief',{kind:'service',files:serviceBriefFiles(defaultServiceInputs,{defect:true}),inputs:defaultServiceInputs,provenance:developerProvenance});
  const failed=await call(f.tools,'brief','check.run');assert.equal(failed.ok,false);assert.equal(failed.checks.find(c=>c.id==='service.sources')?.passed,false);assert.equal((await call(f.tools,'brief','artifact.publish_local')).ok,false);
  const old=(await call(f.tools,'brief','workspace.read',{path:'brief.json'})).output;const replacement=serviceBriefFiles()[0];const args={...replacement,expectedHash:old.sha256};const corrected=await call(f.tools,'brief','workspace.replace',args,'repair-service');assert.equal(corrected.ok,true);assert.equal(corrected.manifest?.revision,2);
  assert.deepEqual(await call(f.tools,'brief','workspace.replace',args,'repair-service'),corrected);assert.equal(f.tools.load('venture','brief').manifest.revision,2);assert.deepEqual(f.tools.recoverOperation('repair-service','venture','brief'),corrected);
  assert.equal((await call(f.tools,'brief','check.run')).ok,true);const published=await call(f.tools,'brief','artifact.publish_local',{},'publish-service');assert.equal(published.ok,true);assert.equal(published.output.customerAcknowledged,false);assert.equal(published.output.obligations.length,2);assert.deepEqual(await call(f.tools,'brief','artifact.publish_local',{},'publish-service'),published);
  const bundle=JSON.parse(f.tools.download('venture','brief').content);assert.equal(bundle.manifest.sha256,published.manifest?.sha256);assert.match(f.tools.download('venture','brief','report.html').content,/confirmed-access/);assert.equal(bundle.delivery.customerAcknowledged,false);
  const current=f.tools.load('venture','brief');assert.equal((await call(f.tools,'brief','workspace.replace',{path:'README.md',content:'Revision note',expectedHash:null})).ok,true);assert.equal(f.tools.load('venture','brief').published,null);assert.equal(f.tools.load('venture','brief').checkedManifest,null);assert.throws(()=>f.tools.download('venture','brief'),/PUBLICATION/);assert.notEqual(current.manifest.sha256,f.tools.load('venture','brief').manifest.sha256);
 }finally{f.close();}
});

test('trusted source contract is parameterized and cannot be changed through workspace paths',async()=>{const f=fixture();try{const inputs={title:'Custom customer assessment',client:'Another business',asOf:'2026-10-02',sources:[{id:'custom-log',title:'Custom log',text:'Two scheduled visits await access confirmation.',rights:'Explicit local test input'}],requiredSourceIds:['custom-log']};const files=serviceBriefFiles(inputs);assert.equal(checkServiceBrief(files,inputs).checks.every(c=>c.passed),true);f.tools.seed('venture','custom',{kind:'service',files,inputs,provenance:developerProvenance});for(const path of ['../checks.ts','/absolute','C:/secret','.git/config','safe/../../checks'])assert.equal((await call(f.tools,'custom','workspace.replace',{path,content:'overwrite',expectedHash:null})).ok,false);assert.equal((await call(f.tools,'custom','shell.exec',{cmd:'anything'})).ok,false);assert.equal((await call(f.tools,'custom','workspace.replace',{path:'brief.json',content:'{}',expectedHash:'wrong'})).error,'WORKSPACE_STALE_FILE');assert.throws(()=>f.tools.load('other-venture','custom'),/NOT_FOUND/);}finally{f.close();}});

test('source mutation rolls back when durable operation evidence cannot be committed',async()=>{const f=fixture();try{const original=f.tools.seed('venture','atomic',{kind:'software',files:quoteTrackerFiles(),provenance:developerProvenance});const record=f.store.record.bind(f.store);let injected=false;f.store.record=((...args:any[])=>{if(args[2]==='LocalToolObservation'&&!injected){injected=true;throw Error('INJECTED_DURABILITY_FAILURE');}return (record as any)(...args);}) as any;const result=await call(f.tools,'atomic','workspace.replace',{path:'README.md',content:'This must roll back',expectedHash:original.files.find(x=>x.path==='README.md')!.sha256},'atomic-write');assert.equal(result.ok,false);assert.equal(result.error,'INJECTED_DURABILITY_FAILURE');assert.deepEqual(f.tools.load('venture','atomic').manifest,original);assert.deepEqual(f.tools.recoverOperation('atomic-write','venture','atomic'),result);}finally{f.close();}});

test('actual browser checks expose a code defect, then verify corrected totals, persistence, job states and export', {timeout:60000},async()=>{
 const f=fixture();try{f.tools.seed('venture','software',{kind:'software',files:quoteTrackerFiles({defect:true}),provenance:developerProvenance});const failure=await call(f.tools,'software','check.run');assert.equal(failure.ok,false,JSON.stringify(failure));assert.equal(failure.checks.find(c=>c.id==='software.line-totals')?.passed,false,JSON.stringify(failure));assert.equal(failure.checks.find(c=>c.id==='software.line-totals')?.evidence?.actual,'$15.50');
  const read=(await call(f.tools,'software','workspace.read',{path:'app.html'})).output;assert.equal((await call(f.tools,'software','workspace.replace',{path:'app.html',content:quoteTrackerFiles()[0].content,expectedHash:read.sha256},'software-repair')).ok,true);
  const pass=await call(f.tools,'software','check.run');assert.equal(pass.ok,true,JSON.stringify(pass));assert.equal(pass.checks.filter(c=>c.required).length,7);assert.equal((await call(f.tools,'software','artifact.publish_local')).ok,true);
  const w=f.tools.load('venture','software');const saved=f.tools.previewState('venture','software',{ventureId:'venture',taskId:'software',manifestHash:w.manifest.sha256,operation:'read'});assert.equal(saved.state.quotes.length,0,'Acceptance data must not pollute owner state');
 }finally{f.close();}
});

test('preview persistence rejects stale bindings, forged state and unexpected authority fields',()=>{const f=fixture();try{const manifest=f.tools.seed('venture','app',{kind:'software',files:quoteTrackerFiles(),provenance:developerProvenance});const binding={ventureId:'venture',taskId:'app',manifestHash:manifest.sha256};const state={schemaVersion:1,quotes:[{id:'q',customer:'Customer',lines:[{description:'Work',quantity:2,unitMinor:100}],status:'quoted'}]};assert.equal(f.tools.previewState('venture','app',{...binding,operation:'write',expectedVersion:0,state}).version,1);assert.throws(()=>f.tools.previewState('venture','app',{...binding,operation:'write',expectedVersion:0,state}),/STALE/);assert.throws(()=>f.tools.previewState('venture','app',{...binding,manifestHash:'stale',operation:'read'}),/BINDING/);assert.throws(()=>f.tools.previewState('venture','app',{...binding,operation:'read',filePath:'secret'}),/REQUEST_INVALID/);assert.throws(()=>validateQuoteState({...state,authority:'spend'}),/INVALID/);assert.throws(()=>validateQuoteState({...state,quotes:[{...state.quotes[0],lines:[{description:'x',quantity:1.5,unitMinor:10}]}]}),/INVALID/);}finally{f.close();}});

test('owner preview contains only trusted image controls and managed browser blocks external navigation', {timeout:30000},async()=>{
 const sessions=new InteractivePreviewSessions();try{const source='<h1>Network boundary</h1><script>setTimeout(()=>{location.href="https://example.com/forbidden"},300)</script>';let stateCalls=0;const preview=await sessions.open({ventureId:'venture',taskId:'network',manifestHash:'abc',files:[{path:'app.html',content:source}],stateHandler:()=>{stateCalls++;return {version:0,state:{schemaVersion:1,quotes:[]}};}});assert.equal(preview.image.mimeType,'image/png');assert.ok(preview.image.data.length>100);await new Promise(resolve=>setTimeout(resolve,500));const next=await sessions.screenshot(preview.sessionId);assert.ok(next.blockedRequests>=1);assert.equal(stateCalls,0);assert.deepEqual(sessions.binding(preview.sessionId),{ventureId:'venture',taskId:'network',manifestHash:'abc'});await assert.rejects(()=>sessions.act(preview.sessionId,{kind:'key',key:'Control+L'}),/DENIED/);
  const html=renderRemotePreview({ventureId:'venture',taskId:'network',manifestHash:'abc',openEndpoint:'/api/preview/open',actionEndpoint:'/api/preview/action'});assert.equal(html.includes(source),false);assert.equal(html.includes('srcdoc'),false);assert.match(html,/Live product browser/);
 }finally{await sessions.closeAll();}
});
