import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync,rmSync,appendFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { StateStore } from '../src/state.ts';
import { Portfolio } from '../src/portfolio/core.ts';
import { portfolioScope } from '../src/portfolio/contracts.ts';
import { ModelLedger } from '../src/experiment/ledger.ts';
import { makeWorkerRequest } from '../src/portfolio/worker.ts';
import { backupPortfolio,restorePortfolio,verifyPortfolioBackup } from '../src/portfolio/continuity.ts';
import { canonical,hash,rawHash } from '../src/contracts.ts';
import { keypair } from '../src/experiment/config.ts';

const task=(id:string,dependsOn:string[]=[])=>({id,title:'Complete '+id,lane:'build' as const,capability:'software',dependsOn,acceptance:['Executable behavior observed'],requiredChecks:['working'],resource:{modelCalls:3,localToolRuns:3,workerSlots:1}});
test('consistent backup and fresh restart preserve waiting work, actor grants, immutable evidence and uncertain reservations',async()=>{
 const parent=mkdtempSync(join(tmpdir(),'portfolio-continuity-')),sourceRoot=join(parent,'source');mkdirSync(sourceRoot);const store=new StateStore(join(sourceRoot,'portfolio.sqlite'));let restored:StateStore|undefined;
 try{const p=new Portfolio(store);p.createVenture({id:'venture',name:'Venture',goal:'Deliver useful work'});p.registerWorker({id:'worker',name:'Worker',competencies:[],capabilities:['software']});p.addPlan('venture',{rationale:'Check continuity',tasks:[task('pending'),task('waiting',['pending']),task('paused')]});p.controlTask('venture/paused','pause');const lease=p.claimTask('venture/pending','worker',{ownerId:'old-supervisor'})!;p.reserveStep(lease.task.id,lease.token,'model','pending-model');
  const scope=portfolioScope('account'),ledger=new ModelLedger(store,scope,hash('test-only-account'),{totalMinor:200,concurrency:1,stages:{smoke:{minor:0,attempts:0},development:{minor:200,attempts:2},validation:{minor:0,attempts:0},evaluation:{minor:0,attempts:0}}});const request={...makeWorkerRequest({ventureId:'venture',taskId:'venture/pending',attemptId:'uncertain-model',context:{test:true},tools:[]}),scope};const bytes=canonical(request),budget=ledger.port('development',{businessId:'venture',stage:'portfolio-work'});await budget.prepare!(request,{currency:'USD',minorUnits:123},rawHash(bytes),bytes);await budget.reserve(request,{currency:'USD',minorUnits:123},rawHash(bytes));await budget.uncertain(request,'TEST_TIMEOUT');ledger.finish('uncertain-model',null,'TEST_TIMEOUT');
  store.transaction(()=>{store.put('principal','actor',{id:'actor',permissions:['read','approve'],tokenHash:hash('test-token-not-copied-in-plaintext')},null);store.put('grant','historical-action',{id:'historical-action',scope:portfolioScope('venture'),payloadHash:hash('artifact'),revoked:false},null);store.record(portfolioScope('venture'),'evidence','PermittedEvidence',{text:'Observed local fixture result'});});
  mkdirSync(join(sourceRoot,'auth'));writeFileSync(join(sourceRoot,'auth','portfolio-owner.pub'),keypair().publicKey);writeFileSync(join(sourceRoot,'portfolio.authorization.json'),JSON.stringify({payload:{kind:'historical-test-grant',credentialFile:'C:/outside/provider.key'},signature:'test-evidence-only'}));writeFileSync(join(sourceRoot,'auth','provider.key'),'TEST-CREDENTIAL-MUST-NOT-BE-COPIED');
  const saved=backupPortfolio(store,{sourceRoot,backupRoot:join(parent,'backup')});assert.equal(saved.manifest.credentialsCopied,false);assert.equal(saved.manifest.authority.length,2);assert.equal(existsSync(join(saved.backupRoot,'auth','provider.key')),false);store.transaction(()=>store.put('after-snapshot','later',{notInBackup:true},null));
  const targetRoot=join(parent,'restored'),receipt=restorePortfolio({backupRoot:saved.backupRoot,targetRoot,expectedManifestHash:saved.manifestHash});assert.equal(receipt.activeAuthorizationInstalled,false);assert.equal(existsSync(join(targetRoot,'portfolio.authorization.json')),false);assert.equal(existsSync(join(targetRoot,'historical-authority','portfolio.authorization.json')),true);restored=new StateStore(receipt.database);const restarted=new Portfolio(restored);assert.equal(restarted.getTask('venture/waiting').status,'queued');assert.equal(restarted.getTask('venture/paused').status,'paused');assert.equal(restored.get('after-snapshot','later'),null);assert.equal(restored.get('principal','actor').tokenHash,hash('test-token-not-copied-in-plaintext'));assert.equal(restored.get('grant','historical-action').revoked,false);assert.equal(restored.records({id:'reader',tenantId:'mason',businessId:'venture',permissions:['read']},portfolioScope('venture')).some(r=>r.id==='evidence'),true);
  const restoredLedger=new ModelLedger(restored,scope,hash('test-only-account'),ledger.limits);assert.equal(restoredLedger.totals().reserved,123);restarted.recover({ownerAlive:()=>false});assert.equal(restarted.getTask('venture/pending').status,'needs_reconciliation');assert.equal(restarted.claimTask('venture/pending','worker'),null);assert.equal(restoredLedger.totals().reserved,123);assert.equal(restarted.snapshot().resources.reserved.modelCalls,1);
 }finally{restored?.close();store.close();rmSync(parent,{recursive:true,force:true});}
});
test('hash failure and occupied restore targets cannot overwrite existing state',()=>{const parent=mkdtempSync(join(tmpdir(),'portfolio-restore-reject-')),sourceRoot=join(parent,'source');mkdirSync(sourceRoot);const store=new StateStore(join(sourceRoot,'portfolio.sqlite'));try{const backup=backupPortfolio(store,{sourceRoot,backupRoot:join(parent,'backup')});const occupied=join(parent,'occupied');mkdirSync(occupied);writeFileSync(join(occupied,'keep.txt'),'Keep original');assert.throws(()=>restorePortfolio({backupRoot:backup.backupRoot,targetRoot:occupied,expectedManifestHash:backup.manifestHash}),/TARGET_EXISTS/);assert.equal(readFileSync(join(occupied,'keep.txt'),'utf8'),'Keep original');const fresh=join(parent,'fresh');assert.throws(()=>restorePortfolio({backupRoot:backup.backupRoot,targetRoot:fresh,expectedManifestHash:'0'.repeat(64)}),/HASH_MISMATCH/);assert.equal(existsSync(fresh),false);appendFileSync(join(backup.backupRoot,'portfolio.sqlite'),'corruption');assert.throws(()=>verifyPortfolioBackup({backupRoot:backup.backupRoot,expectedManifestHash:backup.manifestHash}),/DATABASE_HASH_MISMATCH/);assert.throws(()=>restorePortfolio({backupRoot:backup.backupRoot,targetRoot:fresh,expectedManifestHash:backup.manifestHash}),/HASH_MISMATCH/);assert.equal(existsSync(fresh),false);assert.throws(()=>backupPortfolio(store,{sourceRoot,backupRoot:'relative-backup'}),/ABSOLUTE/);}finally{store.close();rmSync(parent,{recursive:true,force:true});}});
test('credential material in a whitelisted authority file is rejected before creating backup output',()=>{const parent=mkdtempSync(join(tmpdir(),'portfolio-backup-secret-')),sourceRoot=join(parent,'source');mkdirSync(sourceRoot);const store=new StateStore(join(sourceRoot,'portfolio.sqlite'));try{writeFileSync(join(sourceRoot,'portfolio.authorization.json'),JSON.stringify({payload:{apiKey:'TEST-SECRET'}}));assert.throws(()=>backupPortfolio(store,{sourceRoot,backupRoot:join(parent,'backup')}),/INLINE_CREDENTIAL/);assert.equal(existsSync(join(parent,'backup')),false);}finally{store.close();rmSync(parent,{recursive:true,force:true});}});
