import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { StateStore } from '../src/state.ts';
import { hash,scopeKey } from '../src/contracts.ts';
import { keypair,signed } from '../src/experiment/config.ts';
import { createPortfolioProposal,loadLivePortfolio,portfolioRecoveryInstruction,taskDefinitionHash } from '../src/portfolio/live.ts';
import type { WorkerCall } from '../src/portfolio/worker.ts';
import { makeWorkerRequest,workerSchema,validateWorker } from '../src/portfolio/worker.ts';
import { searchBody,searchCountBody,searchPolicy } from '../src/portfolio/search.ts';
import { countPayload } from '../src/experiment/token-count.ts';

const decision={action:'complete',reason:'Explicit offline transport output; no actual-model capability claim.',toolCall:null};
const searchResponse=()=>({id:'resp_search_test',model:'gpt-6-astra',service_tier:'default',status:'completed',usage:{input_tokens:1000,output_tokens:30},output:[{type:'web_search_call',id:'ws_test',status:'completed',action:{type:'search',sources:[{url:'https://example.com/evidence',title:'Public evidence'}]}},{type:'message',content:[{type:'output_text',text:'Public source describes a possible operational problem; demand remains unknown.',annotations:[{type:'url_citation',url:'https://example.com/evidence',title:'Public evidence'}]}]}]});
function fixture(options:{workCalls?:number;searchCalls?:number;recoveryAdmissions?:0|2;billingAuthority?:boolean;response?:(body:any)=>any;transport?:(url:string,init:any)=>Promise<Response>}={}){
 const root=mkdtempSync(join(tmpdir(),'portfolio-provider-')),store=new StateStore(join(root,'model.sqlite')),keys=keypair(),requests:any[]=[];
 const goal='Build and test a useful local quote tracker';const tools=['workspace.read','workspace.replace','check.run','artifact.publish_local','research.search'];
 store.transaction(()=>{store.put('portfolio-venture','venture',{id:'venture',goal,status:'active'},null);store.put('portfolio-task','venture/build',{id:'venture/build',ventureId:'venture',capability:'software.quote',allowedTools:tools},null);});
 const proposal=createPortfolioProposal({root,id:'portfolio-031-test',projectId:'proj_test',credentialFile:null,billingPublicKey:options.billingAuthority?keys.publicKey:null,expiresAt:new Date(Date.now()+3600000).toISOString(),mode:'mock',countUncertaintyMinor:25,recoveryAdmissions:options.recoveryAdmissions??0,ventures:[{id:'venture',goal,capabilities:['software.quote'],tools,workCalls:options.workCalls??2,searchCalls:options.searchCalls??1}]});
 const sign=()=>{proposal.operating.approvedBy='ephemeral-test-owner';proposal.operating.approvalReference='test-only signature; no real authorization';proposal.portfolio.approved=true;proposal.portfolio.approvedBy=proposal.operating.approvedBy;proposal.portfolio.approvalReference=proposal.operating.approvalReference;proposal.portfolio.operatingGrantHash=hash(proposal.operating);return {...signed(proposal.portfolio,keys.privateKey),operatingEnvelope:signed(proposal.operating,keys.privateKey)};};
 const transport=(async(input:any,init:any)=>{const url=String(input),body=JSON.parse(init.body);requests.push({url,body,headers:init.headers,redirect:init.redirect,signal:init.signal});if(options.transport)return options.transport(url,init);if(url.endsWith('/input_tokens'))return Response.json({object:'response.input_tokens',input_tokens:100});const result=options.response?.(body)??(body.tools?searchResponse():{id:'resp_worker_test',model:'gpt-6-astra',service_tier:'default',status:'completed',usage:{input_tokens:100,output_tokens:100},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(decision)}]}]});return Response.json(result);}) as typeof fetch;
 const load=()=>loadLivePortfolio(root,store,{envelope:sign(),trustedPublicKey:keys.publicKey,execution:{kind:'mock',transport}});
 const call=(attemptId='work-1'):WorkerCall=>({ventureId:'venture',goal,sourceHosts:[],attemptId,request:makeWorkerRequest({ventureId:'venture',taskId:'venture/build',attemptId,tools,context:{goal}}),schema:workerSchema,validate:validateWorker});
 return {root,store,proposal,requests,load,call,sign,keys,transport,close:()=>{store.close();rmSync(root,{recursive:true,force:true});}};
}

test('separately signed portfolio binding transports max worker and native search through one account',async()=>{const f=fixture();try{const ports=f.load();assert.equal(ports.worker.kind,'offline_mock');const worker=await ports.worker.run(f.call());assert.equal(worker.route.kind,'fixture');const result=await ports.search.search('venture','venture/build','quote tracking substitutes','search-1');assert.equal(result.provenance,'offline_mock');assert.equal(result.links.length,1);assert.equal(ports.totals().callsUsed,2);assert.equal(ports.totals().retainedMinor,448);assert.equal(ports.totals().providerRequests,0);assert.equal(f.requests.length,4);assert.deepEqual(f.requests[1].body.reasoning,{effort:'max'});assert.equal(f.requests[1].body.max_output_tokens,16384);assert.equal(f.requests[1].headers['OpenAI-Project'],'proj_test');assert.equal(f.requests[3].body.max_tool_calls,1);assert.equal(f.requests[3].body.tools[0].type,'web_search');assert.equal(f.requests[3].body.tools[0].external_web_access,true);assert.deepEqual(f.requests[2].body,countPayload(searchCountBody(f.requests[3].body)));assert.equal(f.requests.every(r=>r.redirect==='error'&&r.signal instanceof AbortSignal),true);const before=f.requests.length;assert.deepEqual(await ports.worker.recover!(f.call()),worker);assert.deepEqual(await ports.search.search('venture','venture/build','quote tracking substitutes','search-1'),result);assert.equal(f.requests.length,before);assert.equal(ports.totals().countBufferMinor,25);}finally{f.close();}});

test('unsigned, stale code, mismatched project, expired and historical grants reject before transport',()=>{for(const change of ['unsigned','code','project','expired','historical','inner-signature']){const f=fixture();try{const env=f.sign();if(change==='unsigned')env.payload.approved=false;if(change==='code')env.payload.implementationHash='0'.repeat(64);if(change==='project')env.payload.projectId='proj_other';if(change==='expired'){env.payload.expiresAt='2020-01-01T00:00:00Z';env.operatingEnvelope.payload.expiresAt=env.payload.expiresAt;env.payload.operatingGrantHash=hash(env.operatingEnvelope.payload);env.operatingEnvelope=signed(env.operatingEnvelope.payload,f.keys.privateKey);}if(change==='historical')env.payload.historicalAuthorizationTransfer=true;env.signature=signed(env.payload,f.keys.privateKey).signature;if(change==='inner-signature')env.operatingEnvelope.signature='invalid';assert.throws(()=>loadLivePortfolio(f.root,f.store,{envelope:env,trustedPublicKey:f.keys.publicKey,execution:{kind:'mock',transport:f.transport}}));assert.equal(f.requests.length,0);}finally{f.close();}}});

test('task goal, capability, tool and per-venture stage envelopes gate new admissions',async()=>{const f=fixture({workCalls:1,searchCalls:1});try{const ports=f.load();const changed=f.call();changed.goal='Different goal';await assert.rejects(()=>ports.worker.run(changed),/SCOPE/);const changedTools=f.call();changedTools.request.role.tools=[...changedTools.request.role.tools,'shell.exec'];await assert.rejects(()=>ports.worker.run(changedTools),/TOOLS/);assert.equal(f.requests.length,0);await ports.worker.run(f.call());await assert.rejects(()=>ports.worker.run(f.call('work-2')),/WORK_CAP/);await ports.search.search('venture','venture/build','alternatives','search-1');await assert.rejects(()=>ports.search.search('venture','venture/build','more alternatives','search-2'),/SEARCH_CAP/);assert.equal(ports.totals().callsUsed,2);assert.equal(f.requests.length,4);}finally{f.close();}});

test('transport uncertainty retains worker and search exposure without automatic retry or fallback',async()=>{for(const search of [false,true]){const f=fixture({transport:async(url)=>{if(url.endsWith('/input_tokens'))return Response.json({object:'response.input_tokens',input_tokens:100});throw Error('mock transport uncertain');}});try{const ports=f.load(),run=()=>search?ports.search.search('venture','venture/build','alternatives','uncertain'):ports.worker.run(f.call('uncertain'));await assert.rejects(run);const before=f.requests.length;await assert.rejects(run,/NO_RETRY/);await assert.rejects(()=>ports.worker.run(f.call('fresh-after-uncertain')),/PROVIDER_UNCERTAIN/);await assert.rejects(()=>ports.search.search('venture','venture/build','new attempt','fresh-search'),/PROVIDER_UNCERTAIN/);assert.equal(f.requests.length,before);assert.equal(ports.totals().retainedMinor,(search?300:123)+25);assert.equal(ports.totals().callsUsed,1);}finally{f.close();}}});

test('all input-bearing hosted search fields remain in token admission and conservative bounds fit',()=>{const body=searchBody('test question','test goal'),count=countPayload(searchCountBody(body));for(const field of ['input','instructions','model','reasoning','tools','tool_choice'])assert.deepEqual(count[field],(body as any)[field]);assert.equal('include' in count,false);assert.equal('max_tool_calls' in count,false);assert.equal(Math.ceil(((32768+131072)*1250+16384*5000)/1000000)+1,288);assert.ok(searchPolicy.reservationMinor>=288);});

test('shared provider concurrency denies simultaneous search while worker count is in flight',async()=>{let release!:()=>void;const wait=new Promise<void>(r=>release=r);let entered!:()=>void;const enteredPromise=new Promise<void>(r=>entered=r);const f=fixture({transport:async(url,init)=>{if(url.endsWith('/input_tokens')){entered();await wait;return Response.json({object:'response.input_tokens',input_tokens:100});}return Response.json({id:'resp_work',model:'gpt-6-astra',service_tier:'default',status:'completed',usage:{input_tokens:100,output_tokens:100},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(decision)}]}]});}});try{const ports=f.load(),worker=ports.worker.run(f.call());await enteredPromise;await assert.rejects(()=>ports.search.search('venture','venture/build','parallel query','search-concurrent'),/CONCURRENCY/);assert.equal(f.requests.length,1);release();await worker;assert.equal(f.requests.length,2);assert.equal(ports.totals().callsUsed,1);}finally{release();f.close();}});

test('out-of-envelope search usage halts the account; rejected output still retains recorded costs',async()=>{const f=fixture({response:()=>({...searchResponse(),usage:{input_tokens:500000,output_tokens:30}})});try{const ports=f.load();await assert.rejects(()=>ports.search.search('venture','venture/build','too much usage','excess'),/EXPOSURE/);assert.equal(ports.totals().retainedMinor,325);assert.ok(ports.totals().provisionalMinor>300);await assert.rejects(()=>ports.worker.run(f.call()),/ACCOUNT_HALTED|No automatic retry/);assert.equal(f.requests.length,2);}finally{f.close();}});

const completed=()=>({id:'resp_recovery_test',model:'gpt-6-astra',service_tier:'default',status:'completed',usage:{input_tokens:100,output_tokens:100},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(decision)}]}]});
const incompleteResponse=()=>({...completed(),status:'incomplete',output:[]});
function recoveryCall(f:ReturnType<typeof fixture>,ports:ReturnType<typeof loadLivePortfolio>,parent:WorkerCall,id:string){const proof=ports.recoveryEvidence(parent.attemptId),call={...parent,attemptId:id,recoveryOf:parent.attemptId,request:{...parent.request,requestId:id,context:{...(parent.request.context as any),recoveryInstruction:portfolioRecoveryInstruction}}};f.store.transaction(()=>f.store.put('portfolio-recovery-intent',id,{id,parentAttemptId:parent.attemptId,ventureId:parent.ventureId,taskId:'venture/build',reason:'known-incomplete-v1',parentRequestHash:proof.parentRequestHash,createdAt:new Date().toISOString()},null));return call;}

test('known incomplete requires pinned intent, identical task request and one linked fresh admission inside the work pool',async()=>{
 const f=fixture({workCalls:5,recoveryAdmissions:2,response:body=>JSON.parse(body.input).context.recoveryInstruction?completed():incompleteResponse()});
 try{const ports=f.load(),parent=f.call('parent');await assert.rejects(()=>ports.worker.run(parent),/MODEL_RESPONSE_INCOMPLETE/);const proof=ports.recoveryEvidence('parent');assert.equal(proof.eligible,true);assert.equal(proof.status,'incomplete');assert.equal(proof.providerId,'resp_recovery_test');assert.equal(proof.cost.status,'provisional');assert.match(proof.parentRequestHash!,/^[a-f0-9]{64}$/);
  const unprepared={...parent,attemptId:'missing-intent',recoveryOf:'parent',request:{...parent.request,requestId:'missing-intent'}};await assert.rejects(()=>ports.worker.run(unprepared),/INTENT_REQUIRED/);
  const recovery=recoveryCall(f,ports,parent,'recovery-1'),before=f.requests.length;await assert.rejects(()=>ports.worker.run(f.call('unlinked-bypass')),/RECOVERY_PENDING/);const noLink={...recovery};delete noLink.recoveryOf;await assert.rejects(()=>ports.worker.run(noLink),/LINK_REQUIRED/);
  const changed={...recovery,request:{...recovery.request,context:{recoveryInstruction:portfolioRecoveryInstruction,replacedEvidence:'not approved'}}};await assert.rejects(()=>ports.worker.run(changed),/REQUEST_CHANGED/);assert.equal(f.requests.length,before);
  const result=await ports.worker.run(recovery);assert.equal(result.output.action,'complete');assert.equal(ports.totals().callsUsed,2);assert.equal(ports.totals().recoveryAdmissions,1);assert.equal(ports.totals().ordinaryWorkLimit,3);assert.equal(ports.totals().retainedMinor,271);assert.equal(ports.recoveryEvidence('parent').eligible,false);
  const after=f.requests.length;assert.deepEqual(await ports.worker.recover!(recovery),result);assert.equal(f.requests.length,after);const second=recoveryCall(f,ports,parent,'duplicate-parent-recovery');await assert.rejects(()=>ports.worker.run(second),/ALREADY_CLAIMED/);assert.equal(f.requests.length,after);
  assert.equal(f.store.db.prepare("SELECT count(*) AS n FROM records WHERE body LIKE '%PortfolioRecoveryLink%'").get()!.n,1);
 }finally{f.close();}
});

test('ordinary work cannot consume two held recovery admissions; recovery cap never grows the total or venture budget',async()=>{
 const f=fixture({workCalls:5,searchCalls:1,recoveryAdmissions:2,response:body=>body.tools?searchResponse():JSON.parse(body.input).context.recoveryInstruction?completed():incompleteResponse()});
 try{const ports=f.load(),parents=[f.call('parent-1'),f.call('parent-2'),f.call('parent-3')];for(const p of parents)await assert.rejects(()=>ports.worker.run(p),/INCOMPLETE/);const before=f.requests.length;await assert.rejects(()=>ports.worker.run(f.call('ordinary-overflow')),/ORDINARY_WORK_CAP/);assert.equal(f.requests.length,before);
  for(let i=0;i<2;i++)await ports.worker.run(recoveryCall(f,ports,parents[i],'recovery-'+i));assert.equal(ports.totals().callsUsed,5);assert.equal(ports.totals().recoveryAdmissions,2);assert.equal(ports.recoveryEvidence('parent-3').eligible,false);
  await assert.rejects(()=>ports.worker.run(recoveryCall(f,ports,parents[2],'recovery-3')),/WORK_CAP|RECOVERY_CAP/);await ports.search.search('venture','venture/build','public substitutes','search-after-recovery');assert.equal(ports.totals().callsUsed,6);assert.equal(ports.totals().retainedMinor,940);assert.equal(f.requests.length,12);
 }finally{f.close();}
});

test('recovery of a recovery, uncertain responses and an unapproved recovery reserve cannot create calls',async()=>{
 for(const mode of ['second-incomplete','unknown','missing-usage','disabled'] as const){const f=fixture({workCalls:4,recoveryAdmissions:mode==='disabled'?0:2,transport:async(url)=>url.endsWith('/input_tokens')?Response.json({object:'response.input_tokens',input_tokens:100}):mode==='unknown'?Promise.reject(Error('response unknown')):Response.json(mode==='missing-usage'?{...incompleteResponse(),usage:undefined}:incompleteResponse())});
  try{const ports=f.load(),parent=f.call('initial');await assert.rejects(()=>ports.worker.run(parent));if(mode==='second-incomplete'){const child=recoveryCall(f,ports,parent,'child');await assert.rejects(()=>ports.worker.run(child),/INCOMPLETE/);assert.equal(ports.recoveryEvidence('child').eligible,false);const next=recoveryCall(f,ports,child,'grandchild'),before=f.requests.length;await assert.rejects(()=>ports.worker.run(next),/INELIGIBLE/);assert.equal(f.requests.length,before);}else{assert.equal(ports.recoveryEvidence('initial').eligible,false);const next=recoveryCall(f,ports,parent,'cannot-recover'),before=f.requests.length;await assert.rejects(()=>ports.worker.run(next),/INELIGIBLE|UNCERTAIN/);assert.equal(f.requests.length,before);}}
  finally{f.close();}
 }
});

test('known count or route access failure stops new work and search admissions without probing again',async()=>{
 for(const failure of ['count-access','count-invalid','inference-access'] as const){const f=fixture({transport:async(url)=>{if(url.endsWith('/input_tokens'))return failure==='count-access'?Response.json({error:{type:'authentication_error',code:'invalid_api_key'}},{status:401}):failure==='count-invalid'?Response.json({object:'unexpected',input_tokens:100}):Response.json({object:'response.input_tokens',input_tokens:100});return Response.json({error:{type:'invalid_request_error',code:'model_not_found'}},{status:404});}});
  try{const ports=f.load();await assert.rejects(()=>ports.worker.run(f.call('failed-access')));const before=f.requests.length;await assert.rejects(()=>ports.worker.run(f.call('new-after-access-failure')),/PROVIDER_UNAVAILABLE/);await assert.rejects(()=>ports.search.search('venture','venture/build','different task cannot reprobe','search-after-access-failure'),/PROVIDER_UNAVAILABLE/);assert.equal(f.requests.length,before);assert.equal(ports.totals().callsUsed,1);assert.equal(ports.totals().retainedMinor,148);assert.equal(ports.recoveryEvidence('failed-access').eligible,false);}finally{f.close();}
 }
});

test('billing requires separately bound authority and exact signed ledger evidence; count uncertainty remains reserved',async()=>{
 const denied=fixture();try{const ports=denied.load();assert.throws(()=>ports.reconcileBilling({}),/BILLING_AUTHORITY_REQUIRED/);assert.equal(denied.requests.length,0);}finally{denied.close();}
 const f=fixture({billingAuthority:true});try{const ports=f.load();await ports.worker.run(f.call('billed'));const row=f.store.get('model-attempt',scopeKey(f.proposal.operating.accountScope)+'/billed');const statement={kind:'closed_attempt_invoice',projectId:'proj_test',authorizationHash:hash(f.proposal.operating),scope:scopeKey(f.proposal.operating.accountScope),attemptId:'billed',requestHash:row.requestHash,providerRequestId:row.providerRequestId,actual:{currency:'USD',minorUnits:2},evidenceSha256:hash('Explicit offline fixture accounting record; not a provider invoice'),issuer:'ephemeral-test-billing-authority',closedAt:new Date().toISOString()},envelope=(s:any)=>({statement:s,signature:signed(s,f.keys.privateKey).signature});
  for(const change of [{projectId:'proj_other'},{scope:'different-account'},{authorizationHash:'0'.repeat(64)},{requestHash:'0'.repeat(64)},{providerRequestId:'resp_other'},{evidenceSha256:'not-a-hash'}])assert.throws(()=>ports.reconcileBilling(envelope({...statement,...change})),/BILLING_/);
  assert.throws(()=>ports.reconcileBilling({statement,signature:'invalid'}),/BILLING_SIGNATURE/);assert.equal(ports.totals().retainedMinor,148);const before=f.requests.length,result=ports.reconcileBilling(envelope(statement));assert.equal(result.accounting.retainedMinor,25);assert.equal(result.accounting.settledMinor,2);assert.equal(result.countUncertaintyReleasedMinor,0);assert.equal(result.accounting.countBufferMinor,25);assert.deepEqual(ports.reconcileBilling(envelope(statement)),result);assert.throws(()=>ports.reconcileBilling(envelope({...statement,actual:{currency:'USD',minorUnits:1}})),/RECONCILIATION_CONFLICT/);assert.equal(f.requests.length,before);
 }finally{f.close();}
});

test('billing-only loading works after execution expiry and cannot issue work or search',async t=>{
 const f=fixture({billingAuthority:true});try{const ports=f.load();await ports.worker.run(f.call('closed-after-expiry'));const row=f.store.get('model-attempt',scopeKey(f.proposal.operating.accountScope)+'/closed-after-expiry'),env=f.sign();t.mock.method(Date,'now',()=>Date.parse(f.proposal.portfolio.expiresAt)+1000);assert.throws(()=>loadLivePortfolio(f.root,f.store,{envelope:env,trustedPublicKey:f.keys.publicKey,execution:{kind:'mock',transport:f.transport}}),/EXPIRED/);
  const billing=loadLivePortfolio(f.root,f.store,{envelope:env,trustedPublicKey:f.keys.publicKey,purpose:'billing',execution:{kind:'mock',transport:f.transport}}),before=f.requests.length;await assert.rejects(()=>billing.worker.run(f.call('not-executable')),/BILLING_ONLY/);await assert.rejects(()=>billing.search.search('venture','venture/build','not executable','blocked-search'),/BILLING_ONLY/);
  const statement={kind:'closed_attempt_invoice',projectId:'proj_test',authorizationHash:hash(f.proposal.operating),scope:scopeKey(f.proposal.operating.accountScope),attemptId:'closed-after-expiry',requestHash:row.requestHash,providerRequestId:row.providerRequestId,actual:{currency:'USD',minorUnits:124},evidenceSha256:hash('Explicit offline overage fixture'),issuer:'ephemeral-test-billing-authority',closedAt:new Date(Date.now()).toISOString()};const result=billing.reconcileBilling({statement,signature:signed(statement,f.keys.privateKey).signature});assert.equal(result.accounting.settledMinor,124);assert.equal(result.accounting.retainedMinor,25);assert.equal(f.store.get('experiment-account',scopeKey(f.proposal.operating.accountScope)).halted,true);assert.equal(f.requests.length,before);
 }finally{t.mock.restoreAll();f.close();}
});


test('frozen integrated task caps forbid counter transfer, changed definitions and unlisted generated work before transport',async()=>{
 const f=fixture({workCalls:4,recoveryAdmissions:2,searchCalls:0});try{
  const original=f.store.get('portfolio-task','venture/build'),first={...original,title:'Build',objective:'Bounded build',dependsOn:[],acceptance:['Check'],requiredChecks:['delivery.current'],requiredCompetencies:[],resource:{modelCalls:3,localToolRuns:4},inputs:{}};f.store.transaction(()=>{f.store.put('portfolio-task','venture/build',first,original._version);f.store.put('portfolio-task','venture/review',{...first,id:'venture/review'},null);});
  f.proposal.portfolio.tasks=[{id:'venture/build',definitionHash:taskDefinitionHash(first),workCalls:1},{id:'venture/review',definitionHash:taskDefinitionHash(f.store.get('portfolio-task','venture/review')),workCalls:1}];
  const ports=f.load();await ports.worker.run(f.call());const before=f.requests.length;
  await assert.rejects(()=>ports.worker.run(f.call('extra-build')),/FROZEN_TASK_CAP/);assert.equal(f.requests.length,before);
  f.store.transaction(()=>{const t=f.store.get('portfolio-task','venture/build');f.store.put('portfolio-task',t.id,{...t,objective:'Alter the approved job'},t._version);});
  await assert.rejects(()=>ports.worker.run(f.call('changed')),/FROZEN_TASK_SCOPE/);assert.equal(f.requests.length,before);
  f.store.transaction(()=>f.store.put('portfolio-task','venture/generated',{...first,id:'venture/generated'},null));
  const call={...f.call('generated'),request:makeWorkerRequest({ventureId:'venture',taskId:'venture/generated',attemptId:'generated',tools:first.allowedTools,context:{goal:'bounded'}})};
  await assert.rejects(()=>ports.worker.run(call),/FROZEN_TASK_SCOPE/);assert.equal(f.requests.length,before);
 }finally{f.close();}
});
