import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,relative,isAbsolute} from 'node:path';
import {StateStore} from '../src/state.ts';
import {Portfolio} from '../src/portfolio/core.ts';
import {portfolioScope} from '../src/portfolio/contracts.ts';
import {EvidenceLibrary} from '../src/portfolio/evidence.ts';
import {LocalWorkTools} from '../src/portfolio/tools.ts';
import {PortfolioEngine} from '../src/portfolio/engine.ts';
import {preparePortfolio} from '../src/portfolio/prepare.ts';
import {createTaskPreparer} from '../src/portfolio/task-preparation.ts';
import {prepareValueReleaseV4,valueReleaseV4Allocation,valueReleaseV4TaskAllowances} from '../src/portfolio/value-release-v4.ts';
import {quoteProductV2Example} from '../src/portfolio/quote-product-v2-example.ts';
import {serviceBriefFiles} from '../src/portfolio/products.ts';
import {mockResult} from '../src/portfolio/worker.ts';
import {buildResponsesBody} from '../src/model-port.ts';
import {countPayload} from '../src/experiment/token-count.ts';
import {createPortfolioProposal} from '../src/portfolio/live.ts';
import {canonical} from '../src/contracts.ts';

const referenceFiles=()=>{const files=quoteProductV2Example();const target=23900;files[0].content+='\n<!-- '+ 'x'.repeat(target-Buffer.byteLength(JSON.stringify(files))-10)+' -->';return files;};
const action=(name:string,args:any={})=>mockResult({action:'tool',reason:'Scripted offline infrastructure verification, not model reasoning.',toolCall:{name,arguments:{path:null,content:null,expectedHash:null,query:null,url:null,...args}}});
function proposal(decision='prototype'){return {summary:'Explicit offline fixture decision; no market conclusion.',claims:[],contradictions:[],unknowns:['Demand and labor unmeasured'],alternatives:[{name:'quote-to-job',caseFor:'Test a bounded model-to-product execution path.',caseAgainst:'Established substitutes and no buyer evidence.',evidenceIds:[],decision}],priority:31,rationale:'This fixture exercises controller behavior, not commercial judgment.',cancelTaskIds:[],tasks:[]};}
function operating(report:any,artifactHash:string){return {version:'operating-deliverable-v1',reviewedProduct:{artifactHash},recommendation:{decision:'revise',rationale:'Offline example only; actual user observation is still needed.'},trySteps:[{action:'Open the exact local reviewed product and save a two-line example quote.',expected:'Reopen the same record with identical work and totals.'}],advantage:{statement:'A small local work ledger is a hypothesis, not demonstrated switching value.',substitutes:['Spreadsheet and calendar','Existing field-service software']},contraryEvidence:['Existing alternatives already provide quote-to-job workflows.'],unresolvedAssumptions:['No willingness to pay or founder acquisition cost measured.'],demo:{summary:'Synthetic example, not customer activity.',steps:['Save a quote','Reopen and edit it','Convert to job and export']},nextObservation:{route:'Owner-arranged consenting observation; no outreach sent.',record:'Current workflow, missing fields, errors and actual correction effort.',decisionRule:'Retain only if the observation identifies consequential value beyond substitutes.'},interviewQuestions:['Show the last quote you turned into a job. Where was information re-entered?'],acquisitionDraft:{status:'unsent',subject:'A question about your quote-to-job workflow',body:'Would you be willing to show how a recent quote became scheduled work? This is research, not a sales claim.'},economics:Object.fromEntries(['acquisition','delivery','correction','founderEffort'].map(k=>[k,{status:'unknown',detail:'Not measured; record actual effort before qualification.'}])),nextTasks:[{id:'observe',title:'Record a consenting operator walkthrough',dependsOn:[],acceptance:['One source-linked observation preserves contrary evidence and workload.']}],evidence:{findingIds:[report.observations[0].id],sourceIds:[report.observations[0].sourceId],verification:'review_required'}};}

test('v4 exact scoped requests drive blank-source build, unchanged substantive review, real browser checks, operating deliverable and reassessment', {timeout:90000},async()=>{
 const root=mkdtempSync(join(tmpdir(),'midas-v4-e2e-')),store=new StateStore(join(root,'portfolio.sqlite')),portfolio=new Portfolio(store),tools=new LocalWorkTools({root,store,scopeFor:portfolioScope}),evidence=new EvidenceLibrary(store);
 try{preparePortfolio(portfolio,tools,evidence);prepareValueReleaseV4(portfolio,evidence);for(const[id]of valueReleaseV4Allocation){const t=portfolio.getTask('quote-desk/'+id);store.transaction(()=>store.put('portfolio-task',t.id,{...t,inputs:{...t.inputs as any,requiresGrant:false}},t._version));}
 const counts:Record<string,number>={},sizes:any[]=[];let sawBlank=false,sawActualReview=false,sawOperating=false;
 const route=createPortfolioProposal({root,id:'portfolio-031-offline-v4-contract',mode:'mock',projectId:'proj_mock',credentialFile:null,expiresAt:new Date(Date.now()+60000).toISOString(),countUncertaintyMinor:400,recoveryAdmissions:2,ventures:[{id:'quote-desk',goal:portfolio.getVenture('quote-desk').goal,capabilities:['research.investigate','portfolio.plan','software.build','quality.review','service.brief','portfolio.reassess'],tools:[],workCalls:34,searchCalls:2}]}).operating.route;
 const engine=new PortfolioEngine({portfolio,tools,evidence,accounting:()=>({taskAllocations:valueReleaseV4TaskAllowances(portfolio)}),prepareTask:createTaskPreparer(portfolio,tools,evidence),model:{kind:'offline_mock',async run(call){const c=call.request.context as any,t=portfolio.snapshot().tasks.find(t=>t.lease)!,n=counts[t.id]=(counts[t.id]??0)+1;const body=buildResponsesBody(route,call.request,call.schema);assert.deepEqual(countPayload(body).text,body.text);assert.equal(body.reasoning.effort,'max');assert.equal(body.service_tier,'default');sizes.push({task:t.id,n,contextBytes:Buffer.byteLength(canonical(c)),payloadBytes:Buffer.byteLength(canonical(body))});
 assert.equal(c.remaining.modelCalls,valueReleaseV4Allocation.find(a=>t.id.endsWith(a[0]))![1]-n+1);assert(c.sources.every((s:any)=>s.textKind));assert(!JSON.stringify(c.sources).includes('Checkly'));
 if(t.capability.startsWith('portfolio.'))return mockResult(proposal(t.id.endsWith('/adapt-v4')?'retain':'prototype'));
 const w=tools.load('quote-desk',t.id);assert.equal(c.workspace.currentSource[0].content,w.files[0].content);
 if(t.id.endsWith('/review-product-v4')){sawActualReview=true;assert(c.dependencies[0].artifacts[0].software.latestBrowserObservation||c.observations.some((o:any)=>o.tool==='check.run'));assert(c.workspace.currentSource[0].content===referenceFiles()[0].content);if(n===1)return action('check.run');if(n===2)return action('artifact.publish_local');}
 else {if(n===1){if(w.kind==='software'){sawBlank=true;assert(w.files[0].content.includes('Product implementation pending'));return action('workspace.replace',{path:'app.html',content:referenceFiles()[0].content,expectedHash:w.manifest.files[0].sha256});}const report=JSON.parse(serviceBriefFiles(w.inputs)[0].content);if(w.inputs.operatingProfile){sawOperating=true;assert(c.dependencies[0].artifacts[0].software.files[0].content===referenceFiles()[0].content);report.operating=operating(report,w.inputs.reviewedArtifactHash);}return action('workspace.replace',{path:'brief.json',content:w.inputs.operatingProfile?JSON.stringify(report)+' '.repeat(Math.max(0,8999-Buffer.byteLength(JSON.stringify(report)))):JSON.stringify(report),expectedHash:w.manifest.files[0].sha256});}if(n===2)return action('check.run');if(n===3)return action('artifact.publish_local');}
 return mockResult({action:'complete',reason:'This offline fixture delivered the actual checked artifact; customer and model competence remain unobserved.',toolCall:null});}}});
 for(const[id]of valueReleaseV4Allocation){await engine.runTask('quote-desk/'+id);const t=portfolio.getTask('quote-desk/'+id);assert.equal(t.status,'completed',t.id+' '+t.reason+' '+JSON.stringify(engine.rows('portfolio-context-diagnostic'))+' '+JSON.stringify(sizes));}
 assert(sawBlank&&sawActualReview&&sawOperating);assert.equal(Object.values(counts).reduce((a,b)=>a+b,0),17);const delivered=tools.download('quote-desk','quote-desk/operate-v4','report.html').content;assert.match(delivered,/interview/i);assert.match(delivered,/unsent/i);assert.match(delivered,/founder/i);assert(sizes.every(s=>s.contextBytes<=72000));const used=Object.values(counts).reduce((a,b)=>a+b,0);await engine.recover();assert.equal(Object.values(counts).reduce((a,b)=>a+b,0),used);console.log(JSON.stringify({v4ContextSizes:sizes}));
 }finally{store.close();const cleanupPath=realpathSync(root),cleanupRelative=relative(realpathSync(tmpdir()),cleanupPath);assert(cleanupRelative&&!cleanupRelative.startsWith('..')&&!isAbsolute(cleanupRelative));rmSync(cleanupPath,{recursive:true,force:true});}
});
