import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';
import { ProjectWorkspace } from '../src/portfolio/project-workspace.ts';
import { TrustedProjectServer } from '../src/portfolio/project-server.ts';
import { declaredProjectCommands, runProjectCommand } from '../src/portfolio/project-check.ts';
import { launchCheckBrowser } from '../src/portfolio/preview.ts';
import { StateStore } from '../src/state.ts';
import { LocalWorkTools } from '../src/portfolio/tools.ts';
import { blankProjectFiles } from '../src/portfolio/project-contracts.ts';
import { ManagedProjectPreviewSessions } from '../src/portfolio/project-preview.ts';

const source = (options: { invalid?: boolean; external?: boolean } = {}) => [
  { path: 'project.json', content: JSON.stringify(options.invalid ? { version: 1, title: 'Broken', description: 'Missing entities', entities: [] } : { version: 1, title: 'Request desk', description: 'A configurable local request tracker.', entities: [{ id: 'request', title: 'Request', fields: { title: { type: 'string', required: true, maxLength: 120 }, status: { type: 'string', required: true, values: ['draft', 'ready'] }, priority: { type: 'integer', min: 0, max: 10 } } }], actions: [{ id: 'ready', entity: 'request', from: ['draft'], set: { status: 'ready' } }] }, null, 2) },
  { path: 'public/index.html', content: '<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Request desk</title><main><h1>Request desk</h1><p id="status">Use the local request workspace.</p><form data-project-form><label>Title<input data-project-field="title"></label><label>Status<select data-project-field="status"><option value="draft">Draft</option><option value="ready">Ready</option></select></label><label>Priority<input data-project-field="priority" type="number"></label><button data-project-save>Save</button><p data-project-error role="alert"></p></form><div id="records"></div><script src="/app.js"></script></main>' },
  { path: 'public/app.js', content: "(()=>{const entity='request',$=s=>document.querySelector(s),f=['title','status','priority'];let version=0,editing=null;const err=$('[data-project-error]'),records=$('#records'),v=id=>$('[data-project-field=\"'+id+'\"]').value,call=async(p,o={})=>{const r=await fetch(p,o),b=await r.json();if(!r.ok)throw Error(b.error);return b},key=()=>crypto.randomUUID();function draw(rows){records.innerHTML=rows.map(x=>'<article data-project-record><b>'+x.title+'</b><button data-project-open=\"'+x.id+'\">Open</button><button data-project-action=\"ready\" data-id=\"'+x.id+'\">Ready</button></article>').join('');document.querySelectorAll('[data-project-open]').forEach(b=>b.onclick=()=>{editing=rows.find(x=>x.id===b.dataset.projectOpen);f.forEach(id=>$('[data-project-field=\"'+id+'\"]').value=editing[id]??'')});document.querySelectorAll('[data-project-action]').forEach(b=>b.onclick=async()=>{await call('/api/entities/'+entity+'/'+b.dataset.id+'/actions/ready',{method:'POST',headers:{'idempotency-key':key()}});load()})}async function load(){const b=await call('/api/entities/'+entity);version=b.version;draw(b.records)}$('[data-project-form]').onsubmit=async e=>{e.preventDefault();err.textContent='';const record={title:v('title'),status:v('status'),priority:Number(v('priority'))};try{const b=editing?await call('/api/entities/'+entity+'/'+editing.id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({expectedVersion:version,record})}):await call('/api/entities/'+entity,{method:'POST',headers:{'content-type':'application/json','idempotency-key':key()},body:JSON.stringify({record})});version=b.version;editing=null;await load()}catch(e){err.textContent=e.message}};load();" + (options.external ? "fetch('https://example.com/blocked')" : '') + '})()' },
  { path: 'public/style.css', content: 'body{font-family:system-ui;max-width:48rem;margin:3rem auto}' }
];
function fixture(id = 'request-desk') { const root = mkdtempSync(join(tmpdir(), 'midas-project-workspace-')); const workspace = new ProjectWorkspace(root, id); return { root, workspace, close: () => rmSync(root, { recursive: true, force: true }) }; }
async function json(url: string, init?: RequestInit) { const result = await fetch(url, init); return { status: result.status, body: await result.json(), headers: result.headers }; }
async function nodeResult(args: string[]) { return await new Promise<{ code: number | null; stdout: string; stderr: string }>((resolve, reject) => { const child = spawn(process.execPath, args, { stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true }); let stdout = '', stderr = ''; child.stdout.setEncoding('utf8'); child.stderr.setEncoding('utf8'); child.stdout.on('data', chunk => stdout += chunk); child.stderr.on('data', chunk => stderr += chunk); child.once('error', reject); child.once('exit', code => resolve({ code, stdout, stderr })); }); }

test('project workspace allows bounded multi-file read, add, literal patch, and source-bound invalidation', () => {
  const f = fixture(); try { const initial = f.workspace.seed(source()); assert.equal(f.workspace.list().length, 4); const html = f.workspace.read('public/index.html'); assert.match(html.content, /Request desk/);
    const added = f.workspace.replace({ path: 'public/help.html', content: '<h1>Help</h1>', expectedHash: null }); assert.notEqual(added.revision.manifestHash, initial.manifestHash); assert.equal(f.workspace.read('public/help.html').content, '<h1>Help</h1>');
    const css = f.workspace.read('public/style.css'); const patched = f.workspace.patch({ path: 'public/style.css', expectedHash: css.sha256, edits: [{ find: 'max-width:48rem', replace: 'max-width:52rem' }] }); assert.notEqual(patched.revision.manifestHash, added.revision.manifestHash); assert.throws(() => f.workspace.replace({ path: '../host-secret.txt', content: 'no', expectedHash: null }), /PROJECT_PATH_DENIED/); assert.throws(() => f.workspace.replace({ path: 'server.mjs', content: 'process.exit()', expectedHash: null }), /PROJECT_SERVER_SOURCE_DENIED/); const manifest=f.workspace.read('project.json');assert.throws(()=>f.workspace.replace({path:'project.json',expectedHash:manifest.sha256,content:JSON.stringify({version:1,title:'Bad',description:'',entities:[{id:'thing',title:'Thing',fields:{id:{type:'string'}}}]})}),/PROJECT_FIELD_RESERVED/);
  } finally { f.close(); }
});

test('trusted backend validates configured records, makes actions durable, deduplicates idempotent effects, exports, and restarts', async () => {
  const f = fixture(); let first: TrustedProjectServer | null = null; let second: TrustedProjectServer | null = null; try { f.workspace.seed(source()); first = new TrustedProjectServer(f.workspace); const preview = await first.start(); const home = await fetch(preview.url + '/'); assert.equal(home.status, 200); assert.match(home.headers.get('content-security-policy') ?? '', /connect-src 'self'/); assert.equal((await json(preview.url + '/api/health')).body.manifestHash, f.workspace.revision().manifestHash);
    const create = await json(preview.url + '/api/entities/request', { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'request-effect-0001' }, body: JSON.stringify({ record: { title: 'Confirm access', status: 'draft', priority: 3 } }) }); assert.equal(create.status, 201); const duplicate = await json(preview.url + '/api/entities/request', { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'request-effect-0001' }, body: JSON.stringify({ record: { title: 'Confirm access', status: 'draft', priority: 3 } }) }); assert.equal(duplicate.status, 201);
    const conflictingRetry=await json(preview.url+'/api/entities/request',{method:'POST',headers:{'content-type':'application/json','idempotency-key':'request-effect-0001'},body:JSON.stringify({record:{title:'Changed payload',status:'draft',priority:3}})});assert.equal(conflictingRetry.status,400);assert.equal(conflictingRetry.body.error,'PROJECT_IDEMPOTENCY_CONFLICT');const optional=await json(preview.url+'/api/entities/request',{method:'POST',headers:{'content-type':'application/json','idempotency-key':'optional-effect-0001'},body:JSON.stringify({record:{title:'No optional priority',status:'draft'}})});assert.equal(optional.status,201); const recordId = create.body.record.id; const action = await json(preview.url + '/api/entities/request/' + recordId + '/actions/ready', { method: 'POST', headers: { 'idempotency-key': 'transition-effect-0001' } }); assert.equal(action.status, 200); assert.equal(action.body.record.status, 'ready'); const actionRepeat = await json(preview.url + '/api/entities/request/' + recordId + '/actions/ready', { method: 'POST', headers: { 'idempotency-key': 'transition-effect-0001' } }); assert.equal(actionRepeat.status, 200); assert.equal(actionRepeat.body.version, action.body.version);const actionCollision=await json(preview.url+'/api/entities/request/'+recordId+'/actions/ready',{method:'POST',headers:{'idempotency-key':'optional-effect-0001'}});assert.equal(actionCollision.status,400); const invalid = await json(preview.url + '/api/entities/request', { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'request-effect-0002' }, body: JSON.stringify({ record: { title: '', status: 'draft', priority: 99 } }) }); assert.equal(invalid.status, 400); const concurrent = await Promise.all(Array.from({ length: 8 }, (_, index) => json(preview.url + '/api/entities/request', { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'parallel-effect-' + index }, body: JSON.stringify({ record: { title: 'Parallel ' + index, status: 'draft', priority: index } }) }))); assert(concurrent.every(result => result.status === 201)); const exported = await json(preview.url + '/api/export'); assert.equal(exported.body.state.entities.request.length, 10); assert.equal(exported.body.state.entities.request[0].status, 'ready');
    await first.close(); first = null; second = new TrustedProjectServer(f.workspace); await second.start(); const after = await json(second.url() + '/api/entities/request'); assert.equal(after.body.records.length, 10); assert.equal(after.body.records[0].status, 'ready');
  } finally { await first?.close(); await second?.close(); f.close(); }
});

test('source change invalidates checks and rejects an already-open preview identity', async () => {
  const f = fixture(); let server: TrustedProjectServer | null = null; try { f.workspace.seed(source()); const check = await runProjectCommand(f.workspace, 'project.http'); assert.equal(check.passed, true, JSON.stringify(check)); assert.equal(f.workspace.revision().checkedManifest, f.workspace.revision().manifestHash); server = new TrustedProjectServer(f.workspace); await server.start(); const css = f.workspace.read('public/style.css'); f.workspace.replace({ path: 'public/style.css', content: css.content + '\nmain{padding:1rem}', expectedHash: css.sha256 }); assert.equal(f.workspace.revision().checkedManifest, null); const stale = await json(server.url() + '/api/health'); assert.equal(stale.status, 409); assert.equal(stale.body.error, 'PROJECT_PREVIEW_STALE');
  } finally { await server?.close(); f.close(); }
});

test('fixed check command uses a disposable server and cleanup leaves no fixture records; malformed and external-source attempts remain contained', async () => {
  const f = fixture(); try { f.workspace.seed(source({ external: true })); assert.deepEqual(declaredProjectCommands, ['project.schema', 'project.http']); const before = f.workspace.state(); const result = await runProjectCommand(f.workspace, 'project.http'); assert.equal(result.passed, true, JSON.stringify(result)); assert.deepEqual(f.workspace.state(), before, 'check server must not mutate owner data'); const server = new TrustedProjectServer(f.workspace); await server.start(); const home = await fetch(server.url() + '/'); assert.match(home.headers.get('content-security-policy') ?? '', /default-src 'self'/); await server.close(); assert.throws(() => f.workspace.replace({ path: 'project.json', content: source({ invalid: true })[0].content, expectedHash: f.workspace.read('project.json').sha256 }), /PROJECT_ENTITIES_REQUIRED/); assert.throws(() => f.workspace.patch({ path: 'public/app.js', expectedHash: f.workspace.read('public/app.js').sha256, edits: [{ find: 'missing', replace: 'x' }] }), /PROJECT_PATCH_NOT_UNIQUE/);
  } finally { f.close(); }
});

test('the supported surface blocks server modules and path reads; the browser CSP prevents worker frontend network requests', { timeout: 30000 }, async () => {
  const f = fixture(); let server: TrustedProjectServer | null = null; let browser: any = null; try { f.workspace.seed(source({ external: true })); const hostSecret = join(f.root, 'host-secret.txt'); writeFileSync(hostSecret, 'not-for-project'); const permission = await nodeResult(['--permission', '--allow-fs-read=' + f.workspace.sourceDirectory, '-e', "try{require('node:fs').readFileSync(process.argv[1]);console.log('READ')}catch(error){console.log(error.code)}", hostSecret]); assert.equal(permission.stdout.trim(), 'ERR_ACCESS_DENIED'); assert.notEqual(permission.stdout.trim(), 'READ'); assert.throws(() => f.workspace.replace({ path: 'worker-server.mjs', content: "require('node:net').connect(443)", expectedHash: null }), /PROJECT_SERVER_SOURCE_DENIED/);
    server = new TrustedProjectServer(f.workspace); await server.start(); browser = await launchCheckBrowser(); const context = await browser.newContext(); let external = 0; await context.route('**/*', async (route: any) => { if (new URL(route.request().url()).origin !== server!.url()) { external++; await route.abort('blockedbyclient'); } else await route.continue(); }); const page = await context.newPage(); await page.goto(server.url() + '/'); await page.waitForTimeout(200); assert.equal(external, 0, 'CSP must stop source-authored fetch before a network request exists'); await context.close();
  } finally { await browser?.close(); await server?.close(); f.close(); }
});

test('LocalWorkTools runs a functional-project through the normal immutable source, trusted check, publication and persistent owner-preview paths', { timeout: 30000 }, async () => {
  const root = mkdtempSync(join(tmpdir(), 'midas-functional-project-tools-')); const store = new StateStore(join(root, 'state.sqlite')); const tools = new LocalWorkTools({ root, store, scopeFor: businessId => ({ tenantId: 'test', businessId, runId: 'project', dataPolicyVersion: 'v1', mode: 'fixture' }) }); let preview: any = null;
  try { tools.seed('venture', 'functional', { kind: 'software', files: blankProjectFiles(), inputs: { profile: 'functional-project-v1' }, provenance: 'Controller-created blank project; no expected business result.' }); const checked = await tools.execute({ ventureId: 'venture', taskId: 'functional', tool: 'check.run', args: {} }); assert.equal(checked.ok, true, JSON.stringify(checked)); assert.deepEqual(checked.checks.filter(check => check.required).map(check => check.id).sort(), ['project.browser', 'project.persistence', 'project.preview', 'project.restart', 'project.schema']); assert.equal(tools.projectRuntime('venture', 'functional').state().version, 0, 'disposable check state must not become owner state'); const publication = await tools.execute({ ventureId: 'venture', taskId: 'functional', tool: 'artifact.publish_local', args: {} }); assert.equal(publication.ok, true, JSON.stringify(publication)); assert.equal(tools.download('venture', 'functional', 'public/app.js').mimeType, 'text/javascript; charset=utf-8');
    preview = await tools.openProjectPreview('venture', 'functional'); assert.equal((await json(preview.url + '/api/health')).body.manifestHash, preview.workspace.revision().manifestHash); const css = tools.load('venture', 'functional').files.find(file => file.path === 'public/style.css')!; const revised = await tools.execute({ ventureId: 'venture', taskId: 'functional', tool: 'workspace.replace', args: { path: css.path, content: css.content + '\n#app{min-height:1px}', expectedHash: (await tools.execute({ ventureId: 'venture', taskId: 'functional', tool: 'workspace.read', args: { path: css.path } })).output.sha256 } }); assert.equal(revised.ok, true, JSON.stringify(revised)); const stale = await json(preview.url + '/api/health'); assert.equal(stale.status, 409, 'accepted source edit must invalidate the active owner preview identity');
  } finally { await preview?.server.close(); store.close(); rmSync(root, { recursive: true, force: true }); }
});

test('managed project preview blocks worker navigation, images, fetches, forms, popups and websockets outside its exact local server origin', { timeout: 30000 }, async () => {
  const f = fixture(); const sessions = new ManagedProjectPreviewSessions(); let server: TrustedProjectServer | null = null; try { const files = source(); const app = files.find(file => file.path === 'public/app.js')!; app.content = "const x='https://example.com/blocked';fetch(x);new WebSocket('wss://example.com/blocked');const image=new Image();image.src=x;document.body.append(image);window.open(x);document.body.insertAdjacentHTML('beforeend','<form action=\"https://example.com/blocked\"></form>');document.forms[0].submit();location.href=x;"; f.workspace.seed(files); server = new TrustedProjectServer(f.workspace); await server.start(); const active = server; const preview = await sessions.open(async () => ({ url: active.url(), server: active, workspace: f.workspace, localManifestHash: f.workspace.revision().manifestHash })); assert.ok(preview.image.data.length > 100); assert.ok(preview.blockedRequests >= 3, JSON.stringify(preview));const css=f.workspace.read('public/style.css');f.workspace.replace({path:css.path,content:css.content+'\nbody{outline:0}',expectedHash:css.sha256});await assert.rejects(()=>sessions.act(preview.sessionId,{kind:'refresh'}),/PROJECT_PREVIEW_STALE/); await sessions.close(preview.sessionId); server = null;
  } finally { await sessions.closeAll(); await server?.close(); f.close(); }
});
