import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {StateStore} from '../src/state.ts';
import {VentureWorkspace} from '../src/venture/workspace.ts';
const prepared={selectedId:'candidate-a',founder:{},candidates:[{id:'candidate-a',name:'Prepared offer',problem:'Unverified buyer problem',offer:'A',sourceIds:['s']},{id:'candidate-b',name:'Alternative',problem:'Other uncertainty',offer:'B',sourceIds:['s']}],offer:{scope:'Draft package'},sample:{title:'Illustrative sample'},interview:['What happens today?'],outreach:{body:'Draft only'},economics:{priceAssumption:100},sources:[{id:'s',url:'https://example.org',claim:'Public signal'}]};
function open(path:string){const store=new StateStore(path);return {store,app:new VentureWorkspace(store,prepared)};}
test('founder edits, exact local package review and real observations survive restart without claiming demand',()=>{
 const path=join(mkdtempSync(join(tmpdir(),'venture-owner-')),'state.sqlite');let {store,app}=open(path);let v=app.view();assert.equal(v.state.results.length,0);assert.equal(v.state.weeklyHours,null);assert.equal(v.assignment.workers.length,1);assert.equal(v.understanding.assessment.selected,null);
 v=app.act('approve',{expected:v.state._version,packageHash:v.state.packageHash});const oldHash=v.state.packageHash;assert.ok(v.state.approval);assert.match(v.state.approval.scope,/no outreach/);
 v=app.act('revise',{expected:v.state._version,selectedId:'candidate-a',offer:'Revised scope and recommendation',reason:'Owner corrected delivery scope'});assert.equal(v.state.packet.offer,'Revised scope and recommendation');assert.equal(v.state.approval,null);assert.notEqual(v.state.packageHash,oldHash);assert.throws(()=>app.act('approve',{expected:v.state._version,packageHash:oldHash}),/STALE_PACKAGE/);
 v=app.act('record-result',{expected:v.state._version,kind:'interview',summary:'Buyer did not report urgency',source:'Owner notes from a test observation',observedAt:new Date().toISOString(),humanMinutes:null});assert.equal(v.state.results[0].humanMinutes,null);assert.match(v.understanding.current.brief.claims.at(-1).statement,/Owner reported/);assert.match(v.state.status,/need_decision/);assert.equal(v.understanding.feedback,null);store.close();({store,app}=open(path));assert.equal(app.view().state.results.length,1);assert.match(app.view().state.results[0].provenance,/not independently verified/);store.close();
});
test('unknown alternative package, stale revisions, invalid results and external actions fail closed',()=>{
 const {store,app}=open(join(mkdtempSync(join(tmpdir(),'venture-boundary-')),'state.sqlite'));try{let v=app.view();assert.throws(()=>app.act('send-outreach',{expected:v.state._version}),/UNSUPPORTED/);assert.throws(()=>app.act('save-founder',{expected:999}),/STALE/);assert.throws(()=>app.act('record-result',{expected:v.state._version,kind:'sale',summary:'Invented sale'}),/RESULT_KIND/);v=app.act('revise',{expected:v.state._version,selectedId:'candidate-b',offer:'Alternative draft',reason:'Compare another option'});assert.equal(v.state.packet.sample,null);assert.throws(()=>app.act('approve',{expected:v.state._version,packageHash:v.state.packageHash}),/NOT_PREPARED/);}finally{store.close();}
});
test('trusted runtime review remains a proposal until owner adoption and invalidates dependent assets',()=>{
 const {store,app}=open(join(mkdtempSync(join(tmpdir(),'venture-runtime-adopt-')),'state.sqlite'));try{let v=app.view();const output={kind:'validation-package-review',recommendation:{candidateId:'candidate-a',reason:'Revised after supplied evidence',sourceIds:['s']},offer:{segment:'Small service owner',promise:'Reproducible source-backed findings',scope:['One contact route'],exclusions:['No changes']},validation:{riskiestAssumption:'Buyer need',method:'Interview',successCriterion:'Explicit pilot request',revisionCriterion:'Needs implementation instead',stopCriterion:'No actionable need'},tasks:[{id:'owner-review',description:'Owner decides whether the offer fits',competencies:['commercial_judgment'],dependsOn:[],humanRequired:true}],changes:['Narrowed scope'],limitations:['No demand evidence']};
 const proposal={attemptId:'test-only-review',provenance:'actual-model',status:'proposed',result:{output}};v=app.stageRuntimeProposal(proposal,v.state.packageHash);assert.equal(v.state.reviewedOffer,null);assert.equal(v.state.runtimeOverride,undefined);v=app.act('adopt-runtime-review',{expected:v.state._version});assert.deepEqual(v.state.packet.offer,output.offer);assert.equal(v.state.packet.sample,null);assert.equal(v.state.packet.outreach,null);assert.equal(v.assignment.status,'blocked');assert.equal(v.state.approval,null);assert.throws(()=>app.act('approve',{expected:v.state._version,packageHash:v.state.packageHash}),/NOT_PREPARED/);}finally{store.close();}
});
