import test from 'node:test';
import assert from 'node:assert/strict';
import {hash} from '../src/contracts.ts';
import {requireThat} from '../src/contracts.ts';
import {keypair,verified} from '../src/experiment/config.ts';
import {prepareWorkerDevelopmentComparisonGrant,prepareWorkerDevelopmentOperatingPacket,signWorkerDevelopmentComparisonGrant,loadAuthorizedWorkerDevelopmentComparison,assertAuthorizedComparisonExecutor} from '../src/pilot/worker-development-authorized.ts';
import {StateStore} from '../src/state.ts';
import {PilotKnowledge} from '../src/pilot/knowledge.ts';
import {WorkerDevelopment} from '../src/pilot/worker-development.ts';
import {createPortfolioProposal} from '../src/portfolio/live.ts';
import {OperatingModels} from '../src/operations/model.ts';

function unsignedOperatingGrant(){return {kind:'operations-model-grant-v1',approvedBy:'',approvalReference:'',route:{model:'gpt-6-astra'},businesses:[{id:'worker-business'}]};}
function input(){return {authorizationId:'worker-comparison-034',businessId:'worker-business',jobId:'commercial-review',candidateId:'candidate-034',baselineProcedureHash:hash('excellent-generalist'),candidateProcedureHash:hash('candidate-procedure'),model:'gpt-6-astra',toolHash:hash(['workspace.read']),evidenceHash:hash('permitted-source'),resourcesHash:hash({maxCalls:4,maxAttempts:1}),evaluationCaseIds:['evaluation-a','evaluation-b'],profileHash:hash('worker-profile')};}

test('one exact unsigned worker comparison becomes a separately signed replacement packet',()=>{
 const prepared=prepareWorkerDevelopmentComparisonGrant(input());
 assert.equal(prepared.providerRequests,0);assert.equal(prepared.status,'prepared_unsigned');
 const packet=prepareWorkerDevelopmentOperatingPacket({operatingGrant:unsignedOperatingGrant(),prepared});
 assert.equal(packet.proposal.workerDevelopmentComparisons.length,1);assert.equal(packet.proposal.workerDevelopmentComparisons[0].comparisonHash,prepared.comparisonHash);
 const keys=keypair(),signed=signWorkerDevelopmentComparisonGrant({proposal:packet.proposal,prepared,expectedHash:packet.proposalHash,principal:'ephemeral-worker-owner',approvalReference:'Explicit offline-only worker comparison acceptance.',...keys});
 assert.equal(verified(signed.envelope,keys.publicKey).approvedBy,'ephemeral-worker-owner');assert.equal(signed.providerRequests,0);
 const changed=structuredClone(packet.proposal);changed.workerDevelopmentComparisons[0].resourcesHash=hash('changed');
 assert.throws(()=>signWorkerDevelopmentComparisonGrant({proposal:changed,prepared,expectedHash:packet.proposalHash,principal:'ephemeral-worker-owner',approvalReference:'Must reject changed packet.',...keys}),/WORKER_DEVELOPMENT_EXACT_APPROVAL_HASH/);
 assert.throws(()=>prepareWorkerDevelopmentOperatingPacket({operatingGrant:{...unsignedOperatingGrant(),workerDevelopmentComparisons:[]},prepared}),/WORKER_DEVELOPMENT_NEW_PACKET_REQUIRED/);
});

test('an ephemeral signed OperatingModels mock admits the exact comparison requests and rejects a cross-store executor',async()=>{
 const store=new StateStore(':memory:'),knowledge=new PilotKnowledge(store),company=knowledge.createDemo(),development=new WorkerDevelopment(store),source=knowledge.selectedSources(company.id)[0];
 const worker=development.definition(company.id,'signed-review',{responsibilities:['Check permitted evidence'],model:'gpt-6-astra',tools:['workspace.read'],sourceIds:[source.id],outputContract:{id:'signed-review',version:'v1',description:'An opaque source-grounded review.'}});
 const observation=development.observe(company.id,'signed-review',{kind:'commercial_omission',sourceId:source.id,quote:source.text.slice(0,40),summary:'A source-backed omission needs a bounded comparison.',consequence:'The owner could miss a material uncertainty.',assisted:true}),content='Reusable comparison material.';
 development.material(company.id,{id:'signed-material',kind:'public_source',title:'Signed material',provenance:'Synthetic fixture material.',rights:'reusable',content,contentHash:hash(content)});
 const candidate=development.candidate(company.id,'signed-review',{observationId:observation.id,diagnosis:{cause:'missing_procedure',rationale:'A comparative procedure can make the source coverage check explicit.',alternativeExplanations:['The source wording may be ambiguous.','The owner may prefer a different check.']},materialIds:['signed-material'],procedureAddition:'Run a bounded source coverage check before finalizing.',practiceCases:[{id:'practice',partition:'practice',prompt:'Practice.',evidenceIds:[source.id],regression:false},{id:'evaluation-a',partition:'evaluation',prompt:'Evaluate A.',evidenceIds:[source.id],regression:false},{id:'evaluation-b',partition:'evaluation',prompt:'Evaluate B.',evidenceIds:[source.id],regression:true}]});
 const resources={maxCostMinor:205,maxCalls:4,maxAttempts:1,maxHumanMinutes:0},prepared=prepareWorkerDevelopmentComparisonGrant({authorizationId:'signed-worker-034',businessId:company.id,jobId:candidate.jobId,candidateId:candidate.id,baselineProcedureHash:hash(store.get('portfolio-procedure',candidate.baselineProcedureId).procedure),candidateProcedureHash:hash(store.get('portfolio-procedure',candidate.procedureId).procedure),model:'gpt-6-astra',toolHash:hash(worker.tools),evidenceHash:hash({sources:[{id:source.id,sha256:source.sha256}],materials:[{id:'signed-material',contentHash:hash(content)}]}),resourcesHash:hash(resources),evaluationCaseIds:['evaluation-a','evaluation-b'],profileHash:hash({responsibilities:worker.responsibilities,tools:worker.tools,outputContract:worker.outputContract})});
 const base=createPortfolioProposal({root:process.cwd(),id:'portfolio-031-worker-034',projectId:'proj_WORKER034',credentialFile:null,expiresAt:new Date(Date.now()+60000).toISOString(),countUncertaintyMinor:1,mode:'mock',background:true,ventures:[{id:company.id,goal:knowledge.company(company.id).goal,capabilities:['evidence-synthesis'],tools:['workspace.read'],workCalls:4,searchCalls:0}]}).operating;base.limits.allocations!.find((x:any)=>x.metadataKey==='stage')!.value='worker-comparison';
 const packet=prepareWorkerDevelopmentOperatingPacket({operatingGrant:base,prepared}),keys=keypair(),signed=signWorkerDevelopmentComparisonGrant({proposal:packet.proposal,prepared,expectedHash:packet.proposalHash,principal:'ephemeral-worker-owner',approvalReference:'Explicit mock worker comparison.',...keys});let counts=0,creates=0,readFailures=0,recover=false;
 const terminal=(id:string)=>({id,model:'gpt-6-astra',status:'completed',service_tier:'default',background:true,store:true,usage:{input_tokens:12,output_tokens:12},output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({output:{id}})}]}]});
 const transport=(async(url:any,init:any)=>{if(String(url).endsWith('/input_tokens')){counts++;return Response.json({object:'response.input_tokens',input_tokens:12});}if(init.method==='POST'){creates++;const id='resp_worker_'+creates;return creates===1?Response.json({id,model:'gpt-6-astra',status:'queued',service_tier:'default',background:true,store:true,usage:null,output:[]}):Response.json(terminal(id));}if(init.method==='GET'){if(!recover&&++readFailures<=3)throw Error('mock lost retrieval after persisted identity');return Response.json(terminal(String(url).split('/').at(-1)!));}throw Error('unexpected transport');}) as typeof fetch;
 const operating=new OperatingModels({store,root:process.cwd(),envelope:signed.envelope,trustedPublicKey:keys.publicKey,execution:{kind:'mock',transport}}),principal={id:'ephemeral-worker-owner',tenantId:'mason',businessId:company.id,permissions:['read','operate'] as any};
 const invocationFor=(request:any)=>({businessId:company.id,goalHash:base.businesses[0].goalHash,sourceHosts:[],attemptId:request.requestId,stage:'worker-comparison',request,schema:{type:'object',additionalProperties:false,properties:{output:{type:'object'}},required:['output']},validate:(out:any)=>requireThat(out&&typeof out.output==='object','WORKER_OUTPUT_INVALID')});
 const loaded=loadAuthorizedWorkerDevelopmentComparison({operating,principal,invocationFor});
 assert.throws(()=>assertAuthorizedComparisonExecutor(loaded.runtime,prepared.spec,new StateStore(':memory:')),/WORKER_DEVELOPMENT_GRANT_BINDING/);assert.equal(creates,0);
 const runInput=(loaded:any)=>({mode:'ledger_backed_runtime' as const,modelPort:{kind:'live' as const,run(){throw Error('unused');}},runtime:loaded.runtime,authorization:loaded.authorization,resources,custody:{claimedProtected:false,custody:'not_claimed' as const,manifestHash:null,custodianId:null}});
 await assert.rejects(()=>development.runComparison(candidate.id,runInput(loaded)),/BACKGROUND_READ_ERRORS/);assert.equal(creates,1);assert.equal(counts,1);const first=store.db.prepare("SELECT body FROM entities WHERE kind='pilot-worker-development-comparison'").get() as any,interrupted=JSON.parse(String(first.body));assert.equal(interrupted.slots[0].status,'admitted');assert.equal(interrupted.grantHash,signed.grantHash);
 recover=true;const restarted=new OperatingModels({store,root:process.cwd(),envelope:signed.envelope,trustedPublicKey:keys.publicKey,execution:{kind:'mock',transport}}),resumed=loadAuthorizedWorkerDevelopmentComparison({operating:restarted,principal,invocationFor}),run=await development.runComparison(candidate.id,runInput(resumed));assert.equal(run.status,'awaiting_external_grade');assert.equal(creates,4);assert.equal(counts,4);
 assert.equal(run.executionProvenance,'fixture','A signed mock factory must not become actual runtime evidence');
 const grades=['evaluation-a','evaluation-b'].map(caseId=>({caseId,baselineAccepted:false,candidateAccepted:true,criticalCommercialOmission:false,baselineCorrectionSeconds:null,candidateCorrectionSeconds:null,assessor:'Mock external grade input; no independent assessment',independent:true,opaqueGradeHash:hash(caseId)}));
 const graded=development.gradeComparison(run.id,grades);assert.equal(graded.provenance,'operating_models_authorized','Historical authorization route label remains intact');assert.equal(graded.evaluationProvenance,'fixture');assert.equal(graded.decision,'retain_baseline');assert.equal(graded.verifiedAssessor,null);assert.deepEqual(development.gradeComparison(run.id,grades).grades,grades);assert.equal(creates,4);assert.equal(counts,4);
 store.close();
});
