import test from 'node:test';
import assert from 'node:assert/strict';
import { StateStore } from '../src/state.ts';
import { hash } from '../src/contracts.ts';
import { PilotKnowledge } from '../src/pilot/knowledge.ts';
import { WorkerDevelopmentService, workerDevelopmentDiagnosisSchema } from '../src/pilot/worker-development-service.ts';

test('service facade exposes defined worker, prepared model-assisted diagnosis contract, and a future PilotLearning-compatible assignment', () => {
 const store = new StateStore(':memory:'); try { const knowledge = new PilotKnowledge(store), business = knowledge.createDemo(), source = knowledge.selectedSources(business.id)[0], service = new WorkerDevelopmentService(store);
  const worker = service.define(business.id, 'commercial-review', { responsibilities: ['Identify source-backed commercial omissions'], model: 'strict-mock-model-v1', tools: ['workspace.read'], sourceIds: [source.id], outputContract: { id: 'commercial-review', version: 'v1', description: 'A source-grounded review.' } });
  const observed = service.observe(business.id, 'commercial-review', { kind: 'commercial_omission', sourceId: source.id, quote: source.text.slice(0, 80), summary: 'A consequential commercial obstacle was omitted.', consequence: 'The owner could choose the wrong priority.', assisted: true });
  const content = 'Reusable public source coverage method.', material = service.intake(business.id, { id: 'coverage-method-service-v1', kind: 'public_source', title: 'Coverage method', provenance: 'Public reusable method retained locally.', rights: 'reusable', content, contentHash: hash(content) });
  const prepared = service.prepareDiagnosis(business.id, 'commercial-review', { observationId: observed.id, materialIds: [material.id] }); assert.equal(prepared.status, 'prepared_requires_trusted_signed_factory'); assert.equal(prepared.request.outputSchema, workerDevelopmentDiagnosisSchema); assert.equal(prepared.dispatch.available, false); assert.match(prepared.dispatch.required, /OperatingModels/);
  const assignment = service.assignment(business.id, 'commercial-review', 'response-packet'); assert.equal(assignment.status, 'ready_for_future_assignment'); assert.equal(assignment.procedureVersion, worker.baselineProcedureId); assert.equal(assignment.outputContract.id, 'commercial-review');
 } finally { store.close(); }
});

test('service proposal is input-driven and source selection revocation blocks future assignment and fresh evaluation', async () => {
 const store = new StateStore(':memory:'); try { const knowledge = new PilotKnowledge(store), business = knowledge.createDemo(), source = knowledge.selectedSources(business.id)[0], service = new WorkerDevelopmentService(store);
  service.define(business.id, 'commercial-review', { responsibilities: ['Identify source-backed commercial omissions'], model: 'strict-mock-model-v1', tools: ['workspace.read'], sourceIds: [source.id], outputContract: { id: 'commercial-review', version: 'v1', description: 'A source-grounded review.' } });
  const observed = service.observe(business.id, 'commercial-review', { kind: 'commercial_omission', sourceId: source.id, quote: source.text.slice(0, 80), summary: 'A consequential commercial obstacle was omitted.', consequence: 'The owner could choose the wrong priority.', assisted: true }); const content = 'Reusable public source coverage method.'; service.intake(business.id, { id: 'coverage-method-service-v2', kind: 'public_source', title: 'Coverage method', provenance: 'Public reusable method retained locally.', rights: 'reusable', content, contentHash: hash(content) });
  const proposed = service.propose(business.id, 'commercial-review', { observationId: observed.id, diagnosis: { cause: 'missing_procedure', rationale: 'The observed omission warrants a focused coverage step.', alternativeExplanations: ['The source wording is ambiguous.', 'The owner may use another priority.'] }, materialIds: ['coverage-method-service-v2'], candidateMechanism: 'Trace consequential source observations to findings, alternatives, or an evidence request.', diagnosisProvenance: 'owner_or_assisted', cases: [{ id: 'practice', partition: 'practice', prompt: 'Practice', evidenceIds: [source.id], regression: false }, { id: 'evaluation', partition: 'evaluation', prompt: 'Evaluation', evidenceIds: [source.id], regression: false }, { id: 'regression', partition: 'evaluation', prompt: 'Regression', evidenceIds: [source.id], regression: true }] });
  assert.equal(service.practice(proposed.candidate.id).evaluation.length, 2); await assert.rejects(() => service.evaluate(proposed.candidate.id, { mode: 'ledger_backed_runtime', modelPort: { kind: 'live', run: () => { throw Error('must not be called'); } }, resources: { maxCostMinor: 0, maxCalls: 4, maxAttempts: 1, maxHumanMinutes: 0 }, custody: { claimedProtected: false, custody: 'not_claimed', manifestHash: null, custodianId: null }, authorization: { signed: 'caller-supplied text is insufficient' } }), /WORKER_DEVELOPMENT_LEDGER_FACTORY_REQUIRED/); knowledge.selectEvidence(business.id, []); assert.equal(service.assignment(business.id, 'commercial-review', 'response-packet').status, 'blocked_source_revoked'); await assert.rejects(() => service.evaluate(proposed.candidate.id, { mode: 'offline_fixture', modelPort: { kind: 'fixture', run: () => { throw Error('must not be called'); } }, resources: { maxCostMinor: 0, maxCalls: 4, maxAttempts: 1, maxHumanMinutes: 0 }, custody: { claimedProtected: false, custody: 'not_claimed', manifestHash: null, custodianId: null } }), /WORKER_DEVELOPMENT_SOURCE_UNAVAILABLE/); assert.match(service.report(business.id).runtime.reason, /plain signature/);
 } finally { store.close(); }
});
