import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {prepare,open,workflowScope} from '../src/workflow/runner.ts';
import {scopeKey} from '../src/contracts.ts';
import {environmentFor,mockOutput} from '../src/workflow/task.ts';
import {startReview,beginCorrection,completeReview,reviewInteractive} from '../src/workflow/review.ts';
function setup(){const root=mkdtempSync(join(tmpdir(),'workflow-review-'));prepare(root);const {store}=open(root),env=environmentFor('W-001'),snapshot=env.snapshot(),q=mockOutput({task:'investigate',context:{snapshot}}),evidence=env.evidenceRequests!(q).map(x=>env.getEvidence(x)),decision=mockOutput({task:'decide',context:{snapshot,evidence}});store.transaction(()=>store.put('run',scopeKey(workflowScope('W-001-single')),{snapshot,evidence,decision,phase:'completed',outcome:{operationalResult:'pass',economicResult:'unmeasured',failures:[]}},null));store.close();return root;}
const answers={source:'human' as const,timingReliable:true,dimensions:{decision:true,artifactUsefulness:true,authority:true,statusAccuracy:true},critical:false,correctionText:'NONE; no unsupported statement identified.',notes:'Explicit exploratory test input, not a founder review.'};
test('review cannot score a waiting approval as completed delivery',()=>{const root=setup();try{const {store}=open(root),key=scopeKey(workflowScope('W-001-single'));store.transaction(()=>{const run=store.get('run',key);store.put('run',key,{...run,phase:'waiting_approval'},run._version);});store.close();assert.throws(()=>startReview(root,'W-001-single'),/REVIEW_TERMINAL_OBSERVATION_REQUIRED/);}finally{rmSync(root,{recursive:true,force:true});}});
test('explicit review binds observation, records original immutably and excludes assisted timing',()=>{const root=setup();try{const start=startReview(root,'W-001-single');assert.equal(JSON.stringify(start.packet).includes('W-001-single'),false);beginCorrection(root,'W-001-single');const record=completeReview(root,'W-001-single',{...answers,source:'ai-assisted'});assert.equal(record.accepted,true);assert.equal(record.reviewSeconds,null);assert.equal(record.correctionSeconds,null);assert.equal(record.independentHumanReview,false);assert.equal(readdirSync(join(root,'reviews')).length,1);assert.throws(()=>completeReview(root,'W-001-single',answers),/REVIEW_ALREADY_COMPLETED/);const {store}=open(root);assert.throws(()=>store.db.prepare("DELETE FROM records WHERE id='semantic-review'").run(),/immutable record/);store.close();}finally{rmSync(root,{recursive:true,force:true});}});
test('unassisted declared reliable timing records separate review and correction clocks, never identity proof',()=>{const root=setup();try{startReview(root,'W-001-single');beginCorrection(root,'W-001-single');const result=completeReview(root,'W-001-single',answers);assert.equal(typeof result.reviewSeconds,'number');assert.equal(typeof result.correctionSeconds,'number');assert.match(result.provenance,/not independently authenticated/);}finally{rmSync(root,{recursive:true,force:true});}});
test('absent review remains absent and invalid input or changed observation cannot silently complete',()=>{const root=setup();try{assert.throws(()=>completeReview(root,'W-001-single',answers),/REVIEW_START_REQUIRED/);startReview(root,'W-001-single');assert.throws(()=>completeReview(root,'W-001-single',{...answers,notes:''}),/REVIEW_ANSWERS_INVALID/);const {store}=open(root);store.transaction(()=>{const run=store.get('run',scopeKey(workflowScope('W-001-single')));store.put('run',scopeKey(workflowScope('W-001-single')),{...run,decision:{...run.decision,rationale:'Changed after review start'}},run._version);});store.close();assert.throws(()=>completeReview(root,'W-001-single',answers),/REVIEW_OBSERVATION_CHANGED/);}finally{rmSync(root,{recursive:true,force:true});}});
test('interactive review requires deliberate answers and rejects unreliable timings',async()=>{const root=setup();try{const input=['NO','NO','YES','YES','YES','YES','NO','NONE; correct supplied decision.','Synthetic test review only.'],display:string[]=[];const result=await reviewInteractive(root,'W-001-single',{question:async()=>input.shift()!,write:t=>display.push(t)});assert.equal(result.reviewSeconds,null);assert.equal(result.correctionSeconds,null);assert.match(display.join('\n'),/configuration labels omitted/i);assert.equal(display.join('\n').includes('W-001-single'),false);}finally{rmSync(root,{recursive:true,force:true});}});
test('review packet includes actual persisted readback, obligations, prepublication review and inspection',()=>{const root=setup();try{const {store}=open(root),key=scopeKey(workflowScope('W-001-single'));store.transaction(()=>{const run=store.get('run',key),artifact={...run.decision.draft.artifact,title:'Actually delivered artifact'};store.put('run',key,{...run,proposal:{id:'publish',payload:{artifact:run.decision.draft.artifact}}},run._version);store.put('action',key+'/publish',{status:'confirmed',externalReceiptId:'FX-observed',observation:{status:'confirmed',artifact,effectCount:1,payloadHash:'observed-hash',ledger:{obligations:{minorUnits:17,currency:'USD'}}}},null);store.put('model',key+'/operate',{result:{output:{review:{issues:['Seeded defect'],changes:['Removed promise'],verdict:'ready'}}}},null);store.put('model',key+'/verify',{result:{output:{kind:'inspection',status:'fail',findings:['Obligation remains'],evidenceIds:['FX-observed']}}},null);});store.close();const start=startReview(root,'W-001-single');assert.equal(start.packet.artifact.title,'Actually delivered artifact');assert.equal(start.packet.receipt.externalReceiptId,'FX-observed');assert.equal(start.packet.obligations.minorUnits,17);assert.deepEqual(start.packet.prepublicationReview.issues,['Seeded defect']);assert.equal(start.packet.inspection.status,'fail');assert.equal(JSON.stringify(start.packet).includes('W-001-single'),false);}finally{rmSync(root,{recursive:true,force:true});}});
