import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {prepare,runWorkflow,status,approvalView,approve,open,workflowScope,mockTransport} from '../src/workflow/runner.ts';
import {report} from '../src/workflow/report.ts';
import {read,write,configFor,authorize,accountScope} from '../src/workflow/config.ts';
import {hash,scopeKey,canonical,rawHash} from '../src/contracts.ts';
import {ModelLedger} from '../src/experiment/ledger.ts';
import {StateStore} from '../src/state.ts';
import {Authority} from '../src/authority.ts';
const fresh=(mode:'mock'|'live'='mock')=>{const root=mkdtempSync(join(tmpdir(),'workflow-029-'));prepare(root,mode);return root;};
async function finish(root:string,id:string){let s=await runWorkflow(root,id);if(s.checkpoint==='waiting_approval'){const v=approvalView(root,id);approve(root,id,v.proposalHash,'fixture-demo');s=await runWorkflow(root,id);}if(s.checkpoint==='reconciling')s=await runWorkflow(root,id);return s;}
test('six episodes both configurations: real fixture effects, scoped inputs, correction, no-action and repeat-safe report',async()=>{const root=fresh();const oldFetch=globalThis.fetch;globalThis.fetch=()=>{throw Error('NETWORK_MUST_NOT_BE_CALLED');};try{for(const item of read(root,'config.json').schedule)await finish(root,item.runId);const r=report(root);assert.equal(r.status,'offline_mechanics_complete');assert.equal(r.observations.length,12);assert.equal(r.accounting.actualProviderCalls,0);assert.equal(r.accounting.mockAttempts,42);assert.equal(r.observations.reduce((n:number,o:any)=>n+o.effectCount,0),6);assert.equal(r.observations.reduce((n:number,o:any)=>n+o.simulatedBusinessSpentMinor,0),150);for(const x of r.allAttempts){const text=canonical(x.request.context);assert.doesNotMatch(text,/"expected"|"seeding"|authorization|OFFLINE-MOCK-NOT-A-CREDENTIAL/i);assert.equal(x.result.route.kind,'fixture');assert.equal(x.metadata.provenance,'mock');}for(const x of r.observations.filter((o:any)=>o.episode==='W-006')){assert.ok(x.prepublicationReview.issues.length);assert.ok(x.failures.some((f:any)=>f.category==='uncertain_external_effect'));assert.equal(x.effectCount,1);}for(const o of r.observations)assert.equal(o.independentHumanCorrectionSeconds,null);await finish(root,'W-001-single');assert.equal(report(root).allAttempts.length,42);}finally{globalThis.fetch=oldFetch;}});
test('live root refuses before credential/transport, mock mode cannot be substituted and manifest drift fails',async()=>{const root=fresh('live');await assert.rejects(runWorkflow(root,'W-001-single'),/LIVE_EXECUTION_NOT_AUTHORIZED/);assert.equal(status(root,'W-001-single').state,'not_started');const c=read(root,'config.json');c.mode='mock';write(root,'config.json',c); // Tampering root changes grant but no credentials are reachable in mock; explicit mock execution is harmless.
 const episodes=read(root,'episodes.json');episodes[0].costs[0]=1;write(root,'episodes.json',episodes);assert.throws(()=>configFor(root),/CASE_MANIFEST_CHANGED/);});
test('invalid/unsupported output and incomplete transport retain exposure without retry',async()=>{for(const fault of ['malformed','wrong_model','transport_timeout']){const root=fresh();await assert.rejects(runWorkflow(root,'W-001-single',{fault}));const s=status(root,'W-001-single');assert.equal(s.state,'blocked');assert.equal(s.callsUsed,1);assert.equal(s.retainedMinor,52);await assert.rejects(runWorkflow(root,'W-001-single'));assert.equal(status(root,'W-001-single').callsUsed,1);}});
test('lost actual handoff draft is a meaningful failure, not manufactured empty-evidence penalty',async()=>{const root=fresh();await assert.rejects(runWorkflow(root,'W-001-team',{fault:'handoff_loss'}),/WORKFLOW_REVIEW_INPUT_MISSING|MODEL_RESULT_UNCERTAIN/);const r=report(root);assert.equal(r.observations.find((x:any)=>x.runId==='W-001-team').effectCount,0);assert.equal(status(root,'W-001-team').callsUsed,3);});
test('exact approval refuses a stale screen and revoked grant prevents fixture effect',async()=>{const root=fresh();await runWorkflow(root,'W-001-single');const view=approvalView(root,'W-001-single');assert.throws(()=>approve(root,'W-001-single','0'.repeat(64),'fixture-demo'),/STALE_APPROVAL/);approve(root,'W-001-single',view.proposalHash,'fixture-demo');const {store}=open(root);const s=workflowScope('W-001-single');const auth=new Authority(store);const g=store.get('grant',scopeKey(s)+'/publish');store.transaction(()=>store.put('grant',scopeKey(s)+'/publish',{...g,revoked:true},g._version));store.close();await assert.rejects(runWorkflow(root,'W-001-single'),/APPROVAL_REVOKED/);const db=new DatabaseSync(join(root,'services/W-001-single.sqlite'));assert.equal(db.prepare('SELECT COUNT(*) n FROM effects').get()!.n,0);db.close();});
test('missing artifact/receipt mismatch cannot become successful completion on resume',async()=>{for(const defect of ['artifact','receipt']){const root=fresh();await runWorkflow(root,'W-001-single');approve(root,'W-001-single',approvalView(root,'W-001-single').proposalHash,'fixture-demo');await runWorkflow(root,'W-001-single',{checkpoint:'verify'});const db=new DatabaseSync(join(root,'services/W-001-single.sqlite'));const row=db.prepare('SELECT key,result FROM effects').get()!;const body=JSON.parse(String(row.result));if(defect==='artifact')body.artifact=null;else body.externalReceiptId='forged-receipt';db.prepare('UPDATE effects SET result=? WHERE key=?').run(JSON.stringify(body),row.key);db.close();if(defect==='receipt')await assert.rejects(runWorkflow(root,'W-001-single'),/VERIFICATION_RECEIPT_REQUIRED/);else{await runWorkflow(root,'W-001-single');assert.equal(status(root,'W-001-single').checkpoint,'failed');}}});
test('atomic model allocations cap workflow and arm independently of aggregate',async()=>{const root=fresh();const store=new StateStore(join(root,'allocation.sqlite'));const limits={totalMinor:1000,stages:{smoke:{minor:1000,attempts:20},development:{minor:0,attempts:0},validation:{minor:0,attempts:0},evaluation:{minor:0,attempts:0}},allocations:[{metadataKey:'workflow',value:'W',attempts:1,minor:52}]};const ledger=new ModelLedger(store,accountScope,'test',limits);const request:any={scope:accountScope,requestId:'one',context:{},role:{},task:'investigate'};const b=ledger.port('smoke',{workflow:'W'});await b.prepare!(request,{minorUnits:52,currency:'USD'},rawHash('{}'),'{}');const b2=ledger.port('smoke',{workflow:'W'});await assert.rejects(b2.prepare!({...request,requestId:'two'},{minorUnits:52,currency:'USD'},rawHash('{}'),'{}'),/ALLOCATION_ATTEMPT_CAP/);assert.equal(ledger.rows().length,1);assert.equal(ledger.totals().reserved,52);store.close();});
test('postinspection invented receipt reference cannot pass independent acceptance',async()=>{const root=fresh();await runWorkflow(root,'W-001-single');approve(root,'W-001-single',approvalView(root,'W-001-single').proposalHash,'fixture-demo');await assert.rejects(runWorkflow(root,'W-001-single',{fault:'false_inspection'}),/WORKFLOW_OUTPUT_INVALID|WORKFLOW_EVIDENCE_REFS_INVALID/);const r=report(root);const o=r.observations.find((x:any)=>x.runId==='W-001-single');assert.equal(o.checks.execution,true);assert.equal(o.checks.modelInspection,false);assert.equal(o.deterministicAccepted,false);});
