'use strict';

const api = '/api/operations';
const views = {
  business: ['Business', 'Set a clear commercial goal and inspect the evidence MIDAS is allowed to use.'],
  work: ['Work', 'Run the next bounded piece of work. Every task remains visible and persisted.'],
  team: ['Team', 'See the team MIDAS assembled, the procedure each worker follows, and its evidence.'],
  pipeline: ['Pipeline', 'Review, improve, and authorize the business materials that move through the operating pipeline.'],
  results: ['Results', 'Read observed economics and learn from source-backed outcomes.'],
  approvals: ['Approvals', 'Review an exact outbound batch. Approval does not dispatch it.']
};
let state = { data: null, view: 'business', busy: false, pollTimer: null };

const escape = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[character]);
const list = value => Array.isArray(value) ? value : [];
const plural = (n, one, many = `${one}s`) => `${n} ${n === 1 ? one : many}`;
const shortDate = value => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'No date recorded';
const titleCase = value => String(value || 'Unknown').replace(/[_-]/g, ' ').replace(/\b\w/g, char => char.toUpperCase());
const status = value => `<span class="status status-${escape(String(value || 'unknown').toLowerCase())}">${escape(titleCase(value))}</span>`;
const button = (label, action, className = 'button secondary', extra = '') => `<button class="${className}" type="button" data-action="${escape(action)}" ${extra}>${escape(label)}</button>`;
const empty = (title, detail) => `<div class="empty"><strong>${escape(title)}</strong><p>${escape(detail)}</p></div>`;
const card = (title, body, className = '') => `<section class="card ${className}"><h2>${escape(title)}</h2>${body}</section>`;
const selected = () => state.data?.selected || null;
const business = () => selected() || list(state.data?.businesses).find(item => item.id === selected()?.id) || null;
const activeBusinessId = () => selected()?.id || '';
const isDemo = () => /demo|demonstration|sample/i.test(`${business()?.name || ''} ${business()?.status || ''}`);
const notice = (message, error = false) => { document.querySelector('#notice').innerHTML = message ? `<div class="notice ${error ? 'error' : ''}">${escape(message)}</div>` : ''; };

function metric(label, value, detail = '') { return `<div class="metric"><span>${escape(label)}</span><strong>${escape(value)}</strong>${detail ? `<small>${escape(detail)}</small>` : ''}</div>`; }
function evidenceIds(ids) { const values = list(ids); return values.length ? `<details class="evidence"><summary>Evidence IDs (${values.length})</summary><ul>${values.map(id => `<li><code>${escape(typeof id === 'string' ? id : id?.id || '')}</code></li>`).join('')}</ul></details>` : '<span class="muted">No evidence IDs attached</span>'; }
function goals(tasks) { return list(tasks).filter(task => !/complete|cancel/i.test(task.status || '')).slice(0, 6); }

function businessView() {
  const item = business();
  if (!item) return startupView();
  const sourceRows = list(item.sources);
  const claims = list(item.claims);
  const tasks = list(item.tasks);
  const artifacts = list(item.artifacts);
  const bottlenecks = list(item.bottlenecks).slice().sort((left, right) => Number(left.priority ?? 99) - Number(right.priority ?? 99));
  const accounting = item.accounting || {};
  return `
    ${isDemo() ? '<div class="demo-label">Demonstration workspace · separate from your operating business</div>' : ''}
    <section class="hero"><div><p class="eyebrow">CURRENT BUSINESS</p><h2>${escape(item.name || 'Untitled business')}</h2><p class="goal">${escape(item.goal || 'No business goal has been set.')}</p></div><div class="hero-status">${status(item.status)}<span class="mode ${item.mode === 'live' ? 'live' : 'offline'}">${escape(item.mode === 'live' ? (item.modelDisabledUntilGrant ? 'Prepared · model disabled' : 'Authorized live mode') : 'Offline preparation')}</span></div></section>
    <div class="metrics">
      ${metric('Open work', plural(goals(tasks).length, 'task'))}
      ${metric('Materials', plural(artifacts.length, 'artifact'))}
      ${metric('Provider requests', accounting.providerRequests ?? 0)}
      ${metric('Owner interventions', accounting.ownerInterventions ?? 0)}
    </div>
    ${card('What must be resolved', `${bottlenecks.length ? `<ol class="bottleneck-list">${bottlenecks.map(bottleneck => `<li><div><strong>${escape(bottleneck.description || 'Unspecified issue')}</strong>${bottleneck.uncertainty ? `<p>${escape(bottleneck.uncertainty)}</p>` : ''}${list(bottleneck.sourceIds).length ? evidenceIds(bottleneck.sourceIds) : ''}</div><span class="priority">Priority ${escape(bottleneck.priority ?? 'unranked')}</span></li>`).join('')}</ol>` : empty('No bottleneck is ranked yet', 'Run bounded work to compare the unresolved issues.')}<div class="next-action"><strong>Next action</strong><span>${escape(item.nextAction || 'No next action recorded.')}</span></div>`) }
    <div class="layout two">
      ${card('Business goal', `<form id="goal-form"><label for="business-goal">What should this business achieve next?</label><textarea id="business-goal" name="goal" required>${escape(item.goal || '')}</textarea><p class="help">Saving this goal starts a persisted work request. MIDAS uses the exact text as the task objective.</p><button class="button primary" type="submit">Create next work</button></form>`, 'goal-card')}
      ${card('Next actions', goals(tasks).length ? `<div class="action-list">${goals(tasks).map(task => `<article><div><strong>${escape(task.title || task.id || 'Untitled task')}</strong><p>${escape(task.reason || 'No reason recorded.')}</p></div>${status(task.status)} ${button('Run', 'run', 'button compact', `data-task-id="${escape(task.id || '')}"`)}</article>`).join('')}</div>` : empty('No next action yet', 'Write a business goal to create the first persisted work request.'))}
    </div>
    ${card('Add owner-provided evidence', `<form id="evidence-form"><label for="evidence-title">Evidence title</label><input id="evidence-title" name="title" required placeholder="e.g. Controlled test contact permission"><label for="evidence-text">What was actually provided?</label><textarea id="evidence-text" name="text" required placeholder="Record the source and limits without inferring demand, consent, or revenue."></textarea><p class="help">Owner-provided evidence is preserved as reported. It may include a permitted controlled test contact without treating public publication as permission.</p><button class="button secondary" type="submit">Save owner-provided evidence</button></form>`) }
    <div class="layout two">
      ${card('Allowed sources', sourceRows.length ? `<div class="source-list">${sourceRows.map(source => `<article><div><strong>${escape(source.title || source.id || 'Untitled source')}</strong><p>${escape(source.url || 'Retained source observation')}</p><small>${escape(shortDate(source.observedAt))}</small><details class="source-detail"><summary>Read retained source text</summary><p class="source-id">Source record <code>${escape(source.id || 'unidentified')}</code></p><textarea readonly rows="12" aria-label="Retained source plaintext">${escape(source.text || 'No plaintext was retained for this source.')}</textarea><p class="help">This retained plaintext is a source record. Its ID alone is not usable evidence.</p></details></div>${status(source.status)}</article>`).join('')}</div>` : empty('No retained source observation', list(item.allowedUrls).length ? 'Permitted seed URLs are available, but none has been read and retained yet.' : 'No permitted source has been added to this business.'))}
      ${card('Current claims', claims.length ? `<div class="claim-list">${claims.map(claim => `<article><p>${escape(claim.text || 'No claim text recorded.')}</p><div>${status(claim.kind)} ${evidenceIds(claim.sourceIds)}</div></article>`).join('')}</div>` : empty('No claims yet', 'Claims appear only after work records supported findings.'))}
    </div>`;
}

function startupView() {
  return `<section class="startup"><p class="eyebrow">NEW OWNER WORKSPACE</p><h2>Start with a business worth operating.</h2><p>No activity has been preloaded. Give MIDAS a concrete goal and choose whether to prepare offline or request a live operation.</p><form id="create-business-form"><label for="business-name">Business name</label><input id="business-name" name="name" required placeholder="e.g. Harbor customer research"><label for="create-goal">Business goal</label><textarea id="create-goal" name="goal" required placeholder="e.g. Validate whether independent clinics will pay for a faster intake follow-up service."></textarea><label for="allowed-url">Allowed source URL</label><input id="allowed-url" name="allowedUrl" type="url" placeholder="https://example.com"><div class="mode-choice"><label><input type="radio" name="mode" value="offline" checked> Offline preparation</label><label><input type="radio" name="mode" value="live"> Live operation</label></div><p class="help">Live mode only prepares work that is later subject to an exact approval. It does not send, spend, or publish automatically.</p><button class="button primary" type="submit">Create business</button></form><div class="demo-action"><strong>Want to inspect the product safely?</strong><p>A demonstration workspace is separately labeled and does not become your operating business.</p>${button('Create offline demonstration workspace', 'create-demo', 'button secondary')}</div></section>`;
}

function workView() {
  const item = business(); if (!item) return startupView();
  const tasks = list(item.tasks);
  const modelDisabled = item.modelDisabledUntilGrant || item.model?.disabledUntilGrant || item.model?.status === 'disabled_until_grant';
  return `<div class="view-intro"><p>${escape(item.goal || 'No business goal set.')}</p>${modelDisabled ? '<span class="disabled-model">Model disabled until grant</span>' : ''}</div>
    ${card('Create work from a goal', `<form id="run-form"><label for="run-goal">The next result to pursue</label><textarea id="run-goal" name="goal" required placeholder="State a specific, testable business objective."></textarea><p class="help">A new goal creates a linked assignment workspace. It does not overwrite this business, invent activity, or authorize external effects.</p><button class="button primary" type="submit">Create and run work</button></form>`) }
    ${card('Persisted work', tasks.length ? `<div class="table-scroll"><table><thead><tr><th>Work</th><th>Why now</th><th>Worker</th><th>Status</th><th>Business control</th></tr></thead><tbody>${tasks.map(task => `<tr><td><strong>${escape(task.title || task.id || 'Untitled task')}</strong>${evidenceIds([task.id].filter(Boolean))}</td><td>${escape(task.reason || 'No rationale recorded.')}</td><td>${evidenceIds([task.workerId].filter(Boolean))}</td><td>${status(task.status)}</td><td>${taskControl(task)}</td></tr>`).join('')}</tbody></table></div>` : empty('No work has been created', 'The business goal can create the first persisted task.'))}`;
}
function taskControl(task) { const current = String(task.status || '').toLowerCase(); if (/running|active|queued|waiting/.test(current)) return `${button('Pause business', 'pause', 'button compact', `data-task-id="${escape(task.id || '')}"`)} ${button('Cancel business', 'cancel', 'button compact danger', `data-task-id="${escape(task.id || '')}"`)}`; if (/paused/.test(current)) return `${button('Resume business', 'resume', 'button compact', `data-task-id="${escape(task.id || '')}"`)} ${button('Cancel business', 'cancel', 'button compact danger', `data-task-id="${escape(task.id || '')}"`)}`; return button('Run', 'run', 'button compact', `data-task-id="${escape(task.id || '')}"`); }

function teamView() {
  const item = business(); if (!item) return startupView(); const team = item.team || {}; const workers = list(team.workers);
  return `${card('Team configuration', `<p class="lead-copy">${escape(team.configuration || 'No team configuration recorded.')}</p><p class="help">${escape(team.reason || 'No staffing rationale recorded.')}</p>`)}
    ${card('Assigned workers', workers.length ? `<div class="workers">${workers.map(worker => `<article class="worker"><div><p class="eyebrow">${escape(worker.qualification || 'Unqualified')}</p><h3>${escape(worker.title || worker.id || 'Worker')}</h3>${evidenceIds([worker.id].filter(Boolean))}</div><div><details><summary>Procedure and competencies</summary><strong>Procedure</strong><p>${escape(worker.procedure || 'No procedure recorded.')}</p><strong>Competencies</strong><p>${list(worker.competencies).map(escape).join(' · ') || 'None recorded'}</p></details>${evidenceIds(worker.evidence)}</div></article>`).join('')}</div>` : empty('No workers assigned', 'MIDAS has not formed a team for the current business.'))}`;
}

function pipelineView() {
  const item = business(); if (!item) return startupView(); const artifacts = list(item.artifacts), canRevise = item.phase === 'approval';
  return `${card('Business materials', artifacts.length ? `<div class="artifact-list">${artifacts.map(artifact => `<article><div class="artifact-heading"><div><p class="eyebrow">VERSION ${escape(artifact.version || 'unversioned')} · ${escape(authorship(artifact.authorship || artifact.provenance))}</p><h3>${escape(artifact.title || artifact.id || 'Untitled artifact')}</h3>${evidenceIds([artifact.id].filter(Boolean))}</div>${status(artifact.reviewStatus)}</div><dl><dt>Offer</dt><dd>${escape(artifact.offer || 'Not recorded')}</dd><dt>Buyer</dt><dd>${escape(artifact.buyer || 'Not recorded')}</dd><dt>Scope</dt><dd>${list(artifact.scope).map(escape).join('; ') || 'Not recorded'}</dd><dt>Next test</dt><dd>${escape(artifact.nextTest || 'Not recorded')}</dd></dl><details><summary>Prepared outreach (${list(artifact.outreach).length})</summary><ul>${list(artifact.outreach).map(message => `<li><strong>${escape(message.subject || 'No subject')}</strong><br>${escape(message.body || '')}</li>`).join('') || '<li>No outreach draft</li>'}</ul></details>${canRevise && artifact.id === artifacts.at(-1)?.id ? `<button class="button secondary" data-action="open-revise" data-artifact-id="${escape(artifact.id || '')}">Revise material</button>` : '<p class="help">Historical version retained for comparison.</p>'}</article>`).join('')}</div>` : empty('No material in the pipeline', 'Work will place reviewable business materials here.'))}
    <dialog id="revise-dialog"><form id="revise-form" method="dialog"><input type="hidden" name="artifactId"><h2>Revise material</h2><label for="revise-title">Title</label><input id="revise-title" name="title" required><label for="revise-offer">Offer</label><textarea id="revise-offer" name="offer" required></textarea><label for="revise-buyer">Buyer</label><input id="revise-buyer" name="buyer" required><label for="revise-scope">Scope (one item per line)</label><textarea id="revise-scope" name="scope"></textarea><label for="revise-next-test">Next test</label><textarea id="revise-next-test" name="nextTest" required></textarea><label for="revise-subject">Outreach subject</label><input id="revise-subject" name="subject"><label for="revise-body">Outreach body</label><textarea id="revise-body" name="body"></textarea><div class="dialog-actions"><button class="button secondary" value="cancel">Cancel</button><button class="button primary" type="submit" value="default">Save revision</button></div></form></dialog>`;
}

function authorship(value) { return ({ developer: 'Developer-authored', 'developer-authored': 'Developer-authored', offline_mock: 'Offline mock', 'offline-mock': 'Offline mock', 'actual-model': 'Actual model output', actual_model: 'Actual model output' })[String(value || '').toLowerCase()] || 'Authorship not recorded'; }

function resultsView() {
  const item = business(); if (!item) return startupView(); const accounting = item.accounting || {}; const learning = item.learning || {}; const sources = list(learning.sources).filter(source => String(source.url || '').startsWith('https://')); const events = list(item.events ?? item.observations);
  const cents = value => value === null || value === undefined ? 'Not settled' : new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' }).format(Number(value) / 100);
  const simulated = item.mode === 'offline'; const analysis = learning.report?.analysis;
  const procedureCount = value => typeof value === 'object' && value !== null ? `${value.completed ?? 0} completed · ${value.failed ?? 0} failed · ${value.mechanicalPasses ?? 0} mechanical passes` : (value === undefined || value === null ? 'Not reported' : String(value));
  const study = analysis ? (typeof analysis === 'string' ? `<p>${escape(analysis)}</p>` : `<dl><dt>Cases</dt><dd>${escape(analysis.caseCount ?? 'Not reported')}</dd><dt>Completed pairs</dt><dd>${escape(analysis.completedPairs ?? 'Not reported')}</dd><dt>Baseline</dt><dd>${escape(procedureCount(analysis.baseline))}</dd><dt>Challenger</dt><dd>${escape(procedureCount(analysis.challenger))}</dd><dt>Decision</dt><dd>${escape(analysis.decision ?? 'No decision recorded')}</dd><dt>Semantic result</dt><dd>${escape(analysis.semanticResult ?? 'Not reported')}</dd><dt>Reason</dt><dd>${escape(analysis.reason ?? 'No reason recorded')}</dd></dl>`) : '';
  return `<div class="metrics four">${metric('Model calls', `${accounting.callsUsed ?? 0} / ${accounting.callLimit ?? 0}`)}${metric(simulated ? 'Simulated provisional cost' : 'Provisional cost', cents(accounting.provisionalMinor))}${metric(simulated ? 'Simulated retained value' : 'Retained value', cents(accounting.retainedMinor))}${metric('Settled value', cents(accounting.settledMinor))}</div>
    ${card('Observed economics', `<div class="accounting"><div><span>Provider requests</span><strong>${escape(accounting.providerRequests ?? 0)}</strong></div><div><span>Owner interventions</span><strong>${escape(accounting.ownerInterventions ?? 0)}</strong></div><div><span>Human time</span><strong>${accounting.humanSeconds === null || accounting.humanSeconds === undefined ? 'Unknown' : escape(`${accounting.humanSeconds}s`)}</strong></div></div><p class="help">${simulated ? 'These are simulated offline accounting amounts, not business costs or results.' : 'Amounts are accounting records. Provisional amounts are not verified business results.'}</p>`) }
    ${study ? card('Paired procedure study', `${study}<p class="help">This comparison does not establish an independently verified worker advantage.</p>`) : ''}
    ${card('Observed results', events.length ? `<div class="results-list">${events.map(event => `<article><div><strong>${escape(event.title || ({mail_provider_accepted:'Provider acknowledgement',mail_recipient_suppressed:'Further contact stopped',mail_inbound_recorded:'Reply received',mail_reconciliation_unresolved:'Send outcome remains uncertain',mail_authority_failed:'Account access rejected'})[event.kind] || (event.id?.startsWith('note-') ? 'Owner-reported observation' : 'Observed reply'))}</strong><p>${escape(event.summary || event.outcome || event.text || ({mail_provider_accepted:'The provider recorded the message. Delivery and demand are not established.',mail_recipient_suppressed:'The recipient has been suppressed; no follow-up is permitted.',mail_inbound_recorded:'The matched reply is retained below as untrusted source evidence.',mail_reconciliation_unresolved:'The original effect is held for reconciliation and will not be resent.',mail_authority_failed:'Account access was rejected. This action will not be retried.'})[event.kind] || 'Inspect the linked evidence for this event.')}</p><small>${escape(shortDate(event.observedAt || event.receivedAt || event.createdAt || event.at))} · Revenue: ${event.revenueMinor === null || event.revenueMinor === undefined ? 'Unknown' : escape(cents(event.revenueMinor))}</small></div>${list(event.evidenceIds || event.sourceIds).length ? evidenceIds(event.evidenceIds || event.sourceIds) : ''}</article>`).join('')}</div>` : empty('No observed result', 'No positive or negative outcome has been recorded. Revenue remains unknown.'))}
    ${card('Record an outside observation', `<form id="note-form"><label for="outside-note">What did you observe?</label><textarea id="outside-note" name="text" required placeholder="Record the observation and uncertainty. Do not infer a sale or revenue from interest."></textarea><p class="help">This is an owner-reported, unverified observation. It does not establish revenue, demand, or a customer outcome.</p><button class="button secondary" type="submit">Save outside observation</button></form>`) }
    ${item.mode === 'offline' ? card('Offline reply simulation', `<p class="help">Record a negative mock reply to exercise the evidence and learning path. This does not contact anyone.</p>${button('Simulate negative reply', 'simulate-reply', 'button secondary')}`) : ''}
    ${card('Procedure candidate / comparison required', sources.length ? `<div class="learning-list">${sources.map(source => `<article><div><strong>${escape(source.title || 'Learning source')}</strong><p>${escape(source.summary || source.reason || 'No learning summary recorded.')}</p>${evidenceIds([source.id].filter(Boolean))}</div>${button('Add to learning', 'learning', 'button compact', `data-source-id="${escape(source.id || '')}"`)}</article>`).join('')}</div>` : empty('No procedure candidate', 'A candidate appears only after MIDAS records a reviewed source or result.'))}
    ${learning.candidate ? card('Candidate comparison', `${evidenceIds([learning.candidate])}${learning.comparison ? `<p class="help">${escape(learning.comparison)}</p>` : '<p class="help">Comparison required before this candidate becomes a procedure.</p>'}`) : ''}`;
}

function approvalsView() {
  const item = business(); if (!item) return startupView(); const batches = list(item.approvals); const outbox = list(item.outbox);
  return `<div class="approval-banner"><span class="mode ${item.mode === 'live' ? 'live' : 'offline'}">${escape(item.mode === 'live' ? (item.modelDisabledUntilGrant ? 'Prepared · model disabled' : 'Authorized live mode') : 'Offline preparation')}</span><p>${item.mode === 'live' ? 'No message is sent from this screen. An exact approved batch remains subject to the execution controls.' : 'Offline preparation cannot send external messages.'}</p></div>
    ${card('Exact approval requests', batches.length ? `<div class="approval-list">${batches.map(batch => `<article><div class="approval-head"><div><p class="eyebrow">EXACT BATCH</p><h3>${escape(batch.reason || 'No reason recorded')}</h3><code>${escape(batch.batchHash || '')}</code></div>${status(batch.status || 'pending')}</div><dl><dt>From</dt><dd>${escape(batch.sender || 'Not specified')}</dd><dt>To</dt><dd>${escape(list(batch.recipients).join(', ') || 'Not specified')}</dd><dt>Expiry</dt><dd>${escape(shortDate(batch.expiresAt))}</dd></dl><div class="message-list">${list(batch.messages).map(message => `<article><p><strong>To:</strong> ${escape(message.to || 'Not specified')}</p><p><strong>Subject:</strong> ${escape(message.subject || 'No subject')}</p><pre>${escape(message.body || '')}</pre></article>`).join('') || '<p class="muted">No messages in this batch.</p>'}</div>${button('Approve exact batch', 'approve', 'button primary', `data-batch-hash="${escape(batch.batchHash || '')}"`)} ${/approved/i.test(String(batch.status || '')) ? button('Dispatch approved batch', 'dispatch', 'button secondary', `data-batch-hash="${escape(batch.batchHash || '')}"`) : ''}</article>`).join('')}</div>` : empty('No approval request waiting', 'MIDAS has not proposed an external batch for this business.'))}
    ${card('Outbox record', `${outbox.length ? `<div class="table-scroll"><table><thead><tr><th>To</th><th>Subject</th><th>Status</th><th>Reply</th></tr></thead><tbody>${outbox.map(message => `<tr><td>${escape(message.to || 'Not specified')}${evidenceIds([message.id].filter(Boolean))}</td><td>${escape(message.subject || 'No subject')}</td><td>${status(message.status)}</td><td>${escape(message.reply || 'No reply recorded')}<div class="reply-control">${button('Prepare follow-up', 'followup', 'button compact', `data-message-id="${escape(message.id || '')}"`)}</div></td></tr>`).join('')}</tbody></table></div>` : empty('Outbox is empty', 'No message has been sent or recorded.')}<div class="outbox-controls">${button('Check replies', 'poll', 'button secondary')}</div>`)}`;
}

function render() {
  const [heading, description] = views[state.view];
  document.querySelector('#page-title').textContent = heading;
  document.querySelector('#navigation').querySelectorAll('button').forEach(button => button.classList.toggle('active', button.dataset.view === state.view));
  const businesses = list(state.data?.businesses);
  document.querySelector('#business-picker').innerHTML = businesses.length ? `<label class="picker-label" for="business-select">Business</label><select id="business-select">${businesses.map(item => `<option value="${escape(item.id)}" ${item.id === activeBusinessId() ? 'selected' : ''}>${escape(item.name || item.id)}</option>`).join('')}</select>${button('Create offline demonstration workspace', 'create-demo', 'button compact secondary')}` : '<span class="new-workspace">New workspace</span>';
  document.querySelector('#workspace').innerHTML = `<p class="view-description">${escape(description)}</p>${({ business: businessView, work: workView, team: teamView, pipeline: pipelineView, results: resultsView, approvals: approvalsView })[state.view]()}`;
  bind();
}

function bind() {
  document.querySelectorAll('[data-view]').forEach(button => button.onclick = () => { state.view = button.dataset.view; notice(''); render(); window.scrollTo({ top: 0, behavior: 'smooth' }); });
  document.querySelector('#business-select')?.addEventListener('change', event => load(event.target.value));
  document.querySelector('#create-business-form')?.addEventListener('submit', event => { event.preventDefault(); const form = new FormData(event.currentTarget); request('create', { name: form.get('name'), goal: form.get('goal'), allowedUrls: form.get('allowedUrl') ? [form.get('allowedUrl')] : [], mode: form.get('mode') }); });
  document.querySelector('#goal-form')?.addEventListener('submit', event => { event.preventDefault(); const goal = new FormData(event.currentTarget).get('goal'); request('run', { goal }); });
  document.querySelector('#evidence-form')?.addEventListener('submit', event => { event.preventDefault(); const form = new FormData(event.currentTarget); request('evidence', { title: form.get('title'), text: form.get('text') }); });
  document.querySelector('#run-form')?.addEventListener('submit', event => { event.preventDefault(); const goal = new FormData(event.currentTarget).get('goal'); request('run', { goal }); });
  document.querySelector('#note-form')?.addEventListener('submit', event => { event.preventDefault(); const text = new FormData(event.currentTarget).get('text'); request('note', { text }); });
  document.querySelectorAll('[data-action]').forEach(control => control.addEventListener('click', () => action(control)));
  const dialog = document.querySelector('#revise-dialog');
  document.querySelector('#revise-form')?.addEventListener('submit', event => { event.preventDefault(); const form = new FormData(event.currentTarget); const original = list(selected()?.artifacts).find(item => item.id === form.get('artifactId')) || {}; const existingOutreach = list(original.outreach); const outreach = existingOutreach.length ? [{ ...existingOutreach[0], subject: form.get('subject'), body: form.get('body') }, ...existingOutreach.slice(1)] : []; const replacement = { title: form.get('title'), offer: form.get('offer'), buyer: form.get('buyer'), scope: String(form.get('scope') || '').split(/\r?\n/).map(value => value.trim()).filter(Boolean), assumptions: list(original.assumptions), sourceIds: list(original.sourceIds), nextTest: form.get('nextTest'), outreach }; dialog.close(); request('revise', { artifactId: original.id, replacement }); });
}

function action(control) {
  const actionName = control.dataset.action;
  if (actionName === 'open-revise') { const artifact = list(selected()?.artifacts).find(item => item.id === control.dataset.artifactId) || {}; const dialog = document.querySelector('#revise-dialog'); dialog.querySelector('[name=artifactId]').value = artifact.id || ''; dialog.querySelector('[name=title]').value = artifact.title || ''; dialog.querySelector('[name=offer]').value = artifact.offer || ''; dialog.querySelector('[name=buyer]').value = artifact.buyer || ''; dialog.querySelector('[name=scope]').value = list(artifact.scope).join('\n'); dialog.querySelector('[name=nextTest]').value = artifact.nextTest || ''; dialog.querySelector('[name=subject]').value = list(artifact.outreach)[0]?.subject || ''; dialog.querySelector('[name=body]').value = list(artifact.outreach)[0]?.body || ''; dialog.showModal(); return; }
  if (actionName === 'create-demo') return request('create', { name: 'Demonstration workspace', goal: 'Inspect a safe offline demonstration of the MIDAS operating workspace.', allowedUrls: [], mode: 'offline', demonstration: true });
  if (['run', 'pause', 'resume', 'cancel'].includes(actionName)) return request(actionName, { taskId: control.dataset.taskId, goal: control.dataset.goal });
  if (actionName === 'approve') return request('approve', { batchHash: control.dataset.batchHash });
  if (actionName === 'dispatch') return request('dispatch', { batchHash: control.dataset.batchHash });
  if (actionName === 'learning') return request('learning', { sourceId: control.dataset.sourceId });
  if (actionName === 'followup') return request('followup', { messageId: control.dataset.messageId });
  if (actionName === 'simulate-reply') return request('simulate-reply', {});
  if (actionName === 'poll') return request('poll', {});
}

async function load(id = '') {
  const requestedId = id || new URLSearchParams(window.location.search).get('id') || '';
  window.clearTimeout(state.pollTimer); const suffix = requestedId ? `?id=${encodeURIComponent(requestedId)}` : '';
  try { const response = await fetch(`${api}${suffix}`, { cache: 'no-store' }); if (!response.ok) throw new Error('Unable to load this workspace.'); state.data = await response.json(); if (activeBusinessId() && window.location.search !== `?id=${encodeURIComponent(activeBusinessId())}`) history.replaceState(null, '', `?id=${encodeURIComponent(activeBusinessId())}`); render(); schedulePoll(); }
  catch (error) { document.querySelector('#workspace').innerHTML = empty('Workspace unavailable', error.message) + button('Try again', 'poll', 'button primary'); bind(); }
}
function schedulePoll() { window.clearTimeout(state.pollTimer); const running = list(selected()?.tasks).some(task => /running|active|queued/.test(String(task.status || '').toLowerCase())); if (running) state.pollTimer = window.setTimeout(() => poll(true), 4000); }
async function poll(quiet = false) { if (state.busy) return; state.busy = true; try { await load(activeBusinessId()); if (!quiet) notice('Replies and work status refreshed.'); } catch (error) { if (!quiet) notice(error.message || 'Could not refresh status.', true); } finally { state.busy = false; } }
async function request(actionName, payload, quiet = false) {
  if (state.busy) return; state.busy = true;
  try { const response = await fetch(api, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': state.data?.csrf || '' }, body: JSON.stringify({ action: actionName, businessId: activeBusinessId(), ...payload }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(apiError(result)); if (result.selected || result.businesses) state.data = { ...state.data, ...result }; await load(result.businessId || activeBusinessId()); if (!quiet) notice(successMessage(actionName)); }
  catch (error) { if (!quiet) notice(error.message || 'That action could not be completed.', true); }
  finally { state.busy = false; }
}
function apiError(result) { const code = result?.error || result?.code; return ({ CSRF_INVALID: 'Refresh the workspace and try again.', BUSINESS_NOT_FOUND: 'This business is no longer available.', BATCH_EXPIRED: 'This approval has expired. Review the current batch.', BATCH_MISMATCH: 'The approval request changed. Review it again.', MODEL_DISABLED_UNTIL_GRANT: 'Model disabled until grant', INVALID_URL: 'Use a valid https URL.', INVALID_ACTION: 'That action is unavailable.' })[code] || result?.message || 'That action could not be completed.'; }
function successMessage(actionName) { return ({ create: 'Business created and saved.', run: 'Persisted work request created.', pause: 'Work paused.', resume: 'Work resumed.', cancel: 'Work cancelled.', approve: 'Exact batch approval recorded. No message was sent.', dispatch: 'Approved batch dispatched.', revise: 'Revision saved.', learning: 'Learning source saved.', evidence: 'Owner-provided evidence saved.', note: 'Outside observation saved as unverified.', poll: 'Replies and work status refreshed.', followup: 'Follow-up prepared for review.', 'simulate-reply': 'Negative mock reply recorded.' })[actionName] || 'Workspace updated.'; }
load();
