/** Explicit, opt-in runner. The ordinary owner server never loads this factory.
 * Preparation reads no credentials; execution reuses the existing signed ledger. */
import {existsSync,mkdirSync,writeFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {canonical,hash,rawHash,requireThat} from '../contracts.ts';
import {buildResponsesBody} from '../model-port.ts';
import {PortfolioEngine} from '../portfolio/engine.ts';
import {loadLivePortfolio,portfolioRoute,taskDefinitionHash,writePortfolioProposal} from '../portfolio/live.ts';
import type {PortfolioEnvelope} from '../portfolio/live.ts';
import {pilotImplementationHash,validatePilotBinding} from './binding.ts';
import {PilotExecution} from './execution.ts';
import {workerScope} from '../portfolio/worker.ts';
import {taskBusinessContext} from '../portfolio/task-context.ts';

export async function preparePilotAuthorization(execution:PilotExecution,input:{root:string;directory:string;id:string;projectId:string;credentialFile:string|null;expiresAt:string;countUncertaintyMinor:number;tasks:Array<{taskId:string;workCalls:number}>;mode?:'live'|'mock';billingPublicKey?:string|null}){
 requireThat(input.id.startsWith('portfolio-pilot-032-')&&input.tasks.length>0&&input.tasks.length<=4&&new Set(input.tasks.map(t=>t.taskId)).size===input.tasks.length,'PILOT_AUTHORIZATION_TASK_SCOPE');
 requireThat(!existsSync(join(input.directory,'portfolio.authorization.request.json'))&&!existsSync(join(input.root,'portfolio.authorization.json')),'PILOT_NEW_UNSIGNED_PACKET_REQUIRED');
 const selected=input.tasks.map(a=>{const t=execution.assertContextCurrent(a.taskId,true);requireThat(t.attempts===0&&!t.lease&&t.inputs&&t.status==='queued'&&(t.inputs as any).pilotRelease==='032'&&['service.brief','software.build','quality.review'].includes(t.capability)&&Number.isSafeInteger(a.workCalls)&&a.workCalls>=((t.inputs as any).pilotWorkflow==='business-site'?3:2)&&a.workCalls<=t.resource.modelCalls,'PILOT_UNSTARTED_FINITE_TASK_REQUIRED');return {task:t,workCalls:a.workCalls};});
 for(const {task} of selected)execution.store.transaction(()=>{const current=execution.portfolio.getTask(task.id);execution.store.put('portfolio-task',task.id,{...current,inputs:{...(current.inputs as any),modelCallMaxMinor:205}},current._version);});
 const tasks=selected.map(({task,workCalls})=>({id:task.id,definitionHash:taskDefinitionHash(execution.portfolio.getTask(task.id)),workCalls}));
 const previewEngine=new PortfolioEngine({portfolio:execution.portfolio,tools:execution.tools,evidence:execution.evidence,prepareTask:execution.engine.prepareTask,accounting:()=>({taskAllocations:tasks})});
 const route=portfolioRoute(input.id,input.projectId,true,true),requests=[];
 for(const task of tasks){const result=await previewEngine.previewRequest(task.id),body=buildResponsesBody(route,result.request,result.schema),bytes=canonical(body);requireThat(Buffer.byteLength(bytes)<=65536,'PILOT_INITIAL_REQUEST_BYTES_LIMIT');requests.push({taskId:task.id,request:result.request,schema:result.schema,body,bytes,bodyHash:rawHash(bytes),schemaHash:hash(result.schema)});}
 const pilotBinding={kind:'first-owner-pilot-032-v1' as const,implementationHash:pilotImplementationHash(),taskProcedures:requests.map(r=>({taskId:r.taskId,procedureHash:hash(r.request.role.procedure)}))};validatePilotBinding(pilotBinding,tasks,execution.store);
 const ids=[...new Set(selected.map(t=>t.task.ventureId))],ventures=ids.map(id=>{const items=selected.filter(t=>t.task.ventureId===id),v=taskBusinessContext(items[0].task,execution.portfolio.getVenture(id));requireThat(items.every(x=>taskBusinessContext(x.task,v).goal===v.goal),'PILOT_VENTURE_CONTEXT_MIXED');return {id,goal:v.goal,capabilities:[...new Set(items.map(x=>x.task.capability))],tools:[...new Set(items.flatMap(x=>x.task.allowedTools))],sourceHosts:[],workCalls:items.reduce((n,x)=>n+x.workCalls,0),searchCalls:0};});
 const proposal=writePortfolioProposal(input.directory,{root:resolve(input.root),id:input.id,projectId:input.projectId,credentialFile:input.credentialFile,billingPublicKey:input.billingPublicKey,expiresAt:input.expiresAt,mode:input.mode??'live',background:true,countUncertaintyMinor:input.countUncertaintyMinor,recoveryAdmissions:0,tasks,initialRequests:requests.map(r=>({taskId:r.taskId,bodyHash:r.bodyHash,schemaHash:r.schemaHash})),pilotBinding,ventures});
 mkdirSync(join(input.directory,'requests'),{recursive:true});for(const r of requests)writeFileSync(join(input.directory,'requests',hash(r.taskId).slice(0,16)+'.json'),JSON.stringify(r,null,2)+'\n',{flag:'wx'});
 const summary={kind:'pilot-live-preparation-v1',proposalHash:hash(proposal),approved:false,providerRequests:0,maximumExposureMinor:proposal.maximumExposureMinor,ordinaryAdmissions:proposal.inferenceAdmissions,countAdmissions:proposal.countAdmissions,route:proposal.portfolio.route,counts:'Unpriced uncertainty reserve; not asserted free. No search calls.',pricingStatus:'Retained official pricing basis from 2026-09-12; current official pricing and project access must be reconfirmed before owner approval. Preparation is not live compatibility evidence.',capacity:'Astra Max retained. 32768 total output tokens include reasoning and final source; 32768 complete-payload input ceiling. Conservative reservation is ceil(32768*1250/1e6 + 32768*5000/1e6) = 205 USD cents per admission. A larger allowance does not guarantee completion.',exclusions:['No diagnosis/understanding calls are included','No new owner correction task is implicitly admitted','No external effects, sending, hosting, search, retries, replacement inference or fallback','No historical grant or exposure transfers'],recovery:'Bounded same-ID background retrieval only under the included policy; unknown creation cannot be resubmitted.',nextAction:'Owner supplies confirmed project/credential-file location, current pricing/access confirmation, exact tasks/data, expiry and numerical approval; existing protected signer signs both inner and outer payloads.'};
 writeFileSync(join(input.directory,'pilot-execution-summary.json'),JSON.stringify(summary,null,2)+'\n',{flag:'wx'});return {proposal,summary,requests};
}

export function loadAuthorizedPilot(execution:PilotExecution,root:string,options:{envelope?:PortfolioEnvelope;trustedPublicKey?:string;execution?:{kind:'mock';transport:typeof fetch}|{kind:'live';transport?:typeof fetch;credential?:()=>string}}={}){
 const live=loadLivePortfolio(root,execution.store,options);requireThat(live.authorization.pilotBinding,'PILOT_SIGNED_APPLICATION_BINDING_REQUIRED');validatePilotBinding(live.authorization.pilotBinding,live.authorization.tasks,execution.store);
 const engine=new PortfolioEngine({portfolio:execution.portfolio,tools:execution.tools,evidence:execution.evidence,prepareTask:execution.engine.prepareTask,model:{...live.worker,run:call=>{const task=live.authorization.tasks?.find(t=>workerScope(call.ventureId,t.id).runId===call.request.scope.runId);requireThat(task,'PILOT_REQUEST_TASK_REQUIRED');execution.assertContextCurrent(task.id,true);return live.worker.run(call);}},accounting:live.totals});
 const run=async(taskId:string)=>{requireThat(live.authorization.tasks?.some(t=>t.id===taskId),'PILOT_TASK_NOT_GRANTED');await engine.recover();let task=execution.portfolio.getTask(taskId);if(task.status==='needs_reconciliation'){await engine.resumeResponse(taskId);task=execution.portfolio.getTask(taskId);}if(task.status==='completed')return task;execution.assertContextCurrent(taskId,true);return engine.runTask(taskId,(task.inputs as any).assignedWorkerId??'pilot-generalist');};
 return {engine,authorization:live.authorization,totals:live.totals,reconcileBilling:live.reconcileBilling,run,async runAll(){const results=[];for(const task of live.authorization.tasks??[]){const result=await run(task.id);results.push(result);if((result as any)?.status!=='completed')break;}return results;}};
}
