import {hash,requireThat} from '../contracts.ts';
import {StateStore} from '../state.ts';
import {Portfolio} from '../portfolio/core.ts';
import {ProcedureRegistry} from '../portfolio/learning.ts';
import {PilotKnowledge,pilotKnowledgeScope} from './knowledge.ts';
import {COMMERCIAL_PROCEDURE} from './intelligence-contract.ts';

export const commercialReviewDimensions=['consequential coverage and omissions','priority and alternatives','specificity and usable insight','artifact quality and execution','critical errors','owner correction effort','latency and total cost'];
/** Owner/assisted observations support diagnosis; they are not a model judge or an automatic skill promotion. */
export class CommercialReview{
 readonly store:StateStore;readonly knowledge:PilotKnowledge;readonly registry:ProcedureRegistry;
 constructor(store:StateStore){this.store=store;this.knowledge=new PilotKnowledge(store);this.registry=new ProcedureRegistry(store);}
 list(id:string){this.knowledge.company(id);return this.store.db.prepare("SELECT body FROM entities WHERE kind='pilot-commercial-review' ORDER BY rowid").all().map(r=>JSON.parse(String(r.body))).filter(r=>r.businessId===id);}
 record(id:string,input:{analysisAttemptId:string;sourceId:string;quote:string;omission:string;decisionImpact:string;severity:'consequential'|'minor'|'uncertain';assisted:boolean}){
  const c=this.knowledge.company(id),analysis=this.store.get('pilot-intelligence',id),s=this.knowledge.selectedSources(id).find(s=>s.id===input.sourceId);
  requireThat(analysis?.attemptId===input.analysisAttemptId,'COMMERCIAL_REVIEW_ANALYSIS_CHANGED');
  requireThat(s&&typeof input.quote==='string'&&input.quote.length>=5&&input.quote.length<=4000&&s.text.includes(input.quote),'COMMERCIAL_REVIEW_SOURCE_REQUIRED');
  requireThat(['omission','decisionImpact'].every(k=>typeof (input as any)[k]==='string'&&(input as any)[k].trim().length>=5&&(input as any)[k].length<=4000)&&['consequential','minor','uncertain'].includes(input.severity)&&typeof input.assisted==='boolean','COMMERCIAL_REVIEW_FIELDS');
  const key='coverage-'+hash({id,input}).slice(0,28),prior=this.store.get('pilot-commercial-review',key);if(prior)return prior;
  const p=new Portfolio(this.store);if(!this.store.get('portfolio-venture',id))p.createVenture({id,name:c.name,goal:c.goal,mode:c.mode==='fixture'?'fixture':'local'});
  const observation=p.recordObservation(id,{id:key,kind:'commercial-omission',summary:input.omission,source:input.sourceId,provenance:c.mode==='fixture'?'explicit fixture/assisted review; no measured AI omission':'owner-reported commercial omission; reviewer assistance recorded',metadata:{...input,sourceHash:s.sha256,analysisHash:hash(analysis),independentHumanSeconds:null,causalWeakness:'unestablished; source access, ambiguity and reviewer interpretation are alternatives'},reassess:false}).observation;
  const scope={capability:'business.intelligence',population:'source-grounded-commercial-analysis-v1'},baseline=this.registry.baseline({id:'commercial-analysis-baseline-v1',scope,procedure:COMMERCIAL_PROCEDURE,strongBaselineReference:'Excellent generalist commercial procedure with identical permitted sources, selected pixel evidence, retrieval and resource caps. Supplied Claude report prompt/model/connectors are unavailable; no equivalent comparison claimed.'});
  let candidate:any=null;
  if(input.severity==='consequential')candidate=this.registry.propose({id:'coverage-candidate-'+hash(key).slice(0,20),baselineId:baseline.id,scope,procedure:COMMERCIAL_PROCEDURE+'\nCandidate under evaluation: before selecting priorities, make an evidence-coverage table linking each owner objective and consequential observed customer obstacle to a finding, an explicit contrary explanation or a decision-relevant evidence request. Distinguish not investigated from investigated and not supported. Check whether an available source exposes an overlooked asset or a simpler alternative. Do not fill every dimension or increase report length merely to satisfy a checklist.',mechanism:'A coverage trace may expose a consequential source-backed omission before prioritization.',observationId:observation.id,alternativeExplanation:'The reviewer may be interpreting ambiguous sources, using information unavailable to the worker, or preferring a different commercial strategy. Investigate these before attributing a reasoning weakness.',regressionRisk:'Additional coverage work could displace deep investigation, overproduce weak opportunities or increase cost without improving decisions.',rights:'reusable'});
  const value={id:key,businessId:id,...input,sourceHash:s.sha256,analysisHash:hash(analysis),observationId:observation.id,candidateId:candidate?.id??null,candidateProcedure:candidate?.procedure??null,candidateProcedureHash:candidate?hash(candidate.procedure):null,baselineId:baseline.id,baselineProcedureHash:hash(baseline.procedure),diagnosis:'Reported omission; cause and commercial consequence require review.',status:candidate?'candidate_prepared':'observation_recorded',decision:'retain_baseline',independentHumanSeconds:null,qualification:'experimental_unqualified',provenance:c.mode==='fixture'?'Developer-visible fixture observation':'Owner review; independent expertise and timing unverified',comparison:{status:'not_executed',dimensions:commercialReviewDimensions,gate:'A consequential omission cannot be averaged away by unrelated strengths.',fairness:'Same model/settings, rights-cleared source corpus, relevant retrieval/visual tools and aggregate resources; strong generalist baseline. Separate development from fresh evaluator cases; related businesses are not independent observations.',baselineReportLimitation:'Original Claude prompt, exact model, connector/retrieval history, usage and correction effort are unavailable.',minimumUsefulTest:'Compare the proposed retrieval/coverage procedure against the baseline on a different business with a source-backed consequential opportunity and a regression case; freeze the evidence/rubric first.',actualModelCalls:0},nextAction:candidate?'Review the alternative causes, then prepare a fair transfer comparison only if it could change worker selection. No candidate is adopted.':'Retain the observation without buying a procedure comparison.',at:new Date().toISOString()};
  return this.store.transaction(()=>{this.store.record(pilotKnowledgeScope(id),key,'CommercialCoverageReview',value);return this.store.put('pilot-commercial-review',key,value,null);});
 }
}
