/** Local continuity snapshots. V2 carries the owner-facing functional-project
 * runtime as ordinary private data; V3 additionally binds adaptive workspaces and
 * command evidence. Explicit V4 adds bounded acquisition binaries and uncertain
 * command claims. No format carries authorization or starts restored work. */
import { constants, copyFileSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { hash, rawHash, requireThat } from '../contracts.ts';
import { projectPath } from '../portfolio/project-contracts.ts';
import { StateStore } from '../state.ts';
import {assertServicesStopped} from '../adaptive/wsl-service.ts';

const runtimeRoot='functional-project-runtime', maxSidecars=128, maxSidecarBytes=1_572_864, maxSidecarTotal=20*1024*1024;
type Sidecar={path:string;sha256:string;bytes:number};
type V1={version:'pilot-backup-v1';file:'pilot.sqlite';sha256:string;createdAt:string;contains:string;privacy:string};
type V2={version:'pilot-backup-v2';file:'pilot.sqlite';sha256:string;database:{path:'pilot.sqlite';sha256:string;bytes:number};sidecars:Sidecar[];createdAt:string;quiescent:true;consistency:string;contains:string;privacy:string};
type V3=Omit<V2,'version'> & {version:'pilot-backup-v3'};
type V4=Omit<V2,'version'> & {version:'pilot-backup-v4'};
type Options={sourceRoot?:string;quiescent?:boolean;format?:'v4'};
const limits=(extended=false)=>extended?{files:4096,bytes:16*1024*1024,total:256*1024*1024,directories:8192}:{files:maxSidecars,bytes:maxSidecarBytes,total:maxSidecarTotal,directories:1024};
const fileLimit=(path:string,extended=false)=>extended&&path.startsWith('adaptive/workspaces/')?limits(true).bytes:maxSidecarBytes;
function processAlive(pid:number){try{process.kill(pid,0);return true;}catch(error){return (error as NodeJS.ErrnoException).code!=='ESRCH';}}
function assertStopped(store:StateStore,root:string){
 const lease=join(root,'owner-service.json');if(existsSync(lease)){noLinks(lease,'PILOT_CONTINUITY_LINK_DENIED');const value=JSON.parse(readFileSync(lease,'utf8'));requireThat(Number.isSafeInteger(value.pid)&&value.pid>0&&!processAlive(value.pid),'BACKUP_OWNER_SERVICE_STILL_RUNNING');}
 for(const row of store.db.prepare('SELECT body FROM entities WHERE kind=?').all('portfolio-task')){const task=JSON.parse(String(row.body));if(!task.lease)continue;const owner=String(task.lease.ownerId??''),pid=Number(/^(?:worker-)?(\d+)(?:-|$)/.exec(owner)?.[1]);requireThat(pid>0?!processAlive(pid):Date.parse(task.lease.expiresAt)<=Date.now(),'BACKUP_WORKER_STILL_RUNNING');}
}

function noLinks(path:string,code:string){const absolute=resolve(path);for(let current=absolute;;current=dirname(current)){if(existsSync(current))requireThat(!lstatSync(current).isSymbolicLink(),code);if(dirname(current)===current)break;}return absolute;}
function absoluteRoot(path:string,code:string){requireThat(typeof path==='string'&&isAbsolute(path),code);const root=noLinks(path,'PILOT_CONTINUITY_LINK_DENIED');requireThat(existsSync(root)&&lstatSync(root).isDirectory(),code);return root;}
function boundedFile(path:string,code:string,max=maxSidecarBytes){noLinks(path,'PILOT_CONTINUITY_LINK_DENIED');const stat=statSync(path);requireThat(stat.isFile()&&stat.size>=0&&stat.size<=max,code);const bytes=readFileSync(path);return {sha256:rawHash(bytes),bytes:bytes.length};}
function sidecarPath(path:string){requireThat(typeof path==='string'&&path.length<=300&&!path.includes('\\')&&!path.startsWith('/')&&!path.split('/').some(part=>part===''||part==='.'||part==='..'),'PILOT_SIDECAR_PATH_DENIED');const parts=path.split('/');requireThat(parts[0]===runtimeRoot&&parts[1]==='projects'&&/^[a-z][a-z0-9-]{0,63}$/.test(parts[2]??''),'PILOT_SIDECAR_PATH_DENIED');if(parts[3]==='runtime')requireThat(parts.length===5&&['metadata.json','state.json'].includes(parts[4]),'PILOT_SIDECAR_PATH_DENIED');else {requireThat(parts[3]==='source'&&parts.length>=5,'PILOT_SIDECAR_PATH_DENIED');projectPath(parts.slice(4).join('/'));}return path;}
function adaptivePath(path:string,extended=false){
 requireThat(typeof path==='string'&&path.length<=500&&!path.includes('\\')&&!path.split('/').some(p=>!p||p==='.'||p==='..'),'PILOT_ADAPTIVE_PATH_DENIED');
 const parts=path.split('/');requireThat(parts[0]==='adaptive'&&['workspaces','execution-evidence'].includes(parts[1])&&/^[a-f0-9]{64}$/.test(parts[2]??'')&&parts.length>=4,'PILOT_ADAPTIVE_PATH_DENIED');
 requireThat(!parts.slice(3).some(p=>/^\.env(?:\.|$)|^(?:credentials?|grants?|auth|owner\.key|openai\.key)$|\.(?:key|pem|p12|pfx)$/i.test(p)),'PILOT_ADAPTIVE_AUTH_FILE_DENIED');
 if(parts[1]==='execution-evidence')requireThat(parts.length===4&&(/^(?:command-[a-f0-9]{64}|edit-[a-f0-9-]{36})\.json$/.test(parts[3])||extended&&/^(?:command-active|command-result-[a-f0-9]{64})\.json$/.test(parts[3])),'PILOT_ADAPTIVE_PATH_DENIED');
 return path;
}
function versionedPath(path:string,adaptive=false,extended=false){return adaptive&&path.startsWith('adaptive/')?adaptivePath(path,extended):sidecarPath(path);}
function collectAdaptive(sourceRoot:string,extended=false):Sidecar[]{
 const root=join(sourceRoot,'adaptive');if(!existsSync(root))return [];noLinks(root,'PILOT_SIDECAR_LINK_DENIED');const output:Sidecar[]=[];let directories=0;
 const limit=limits(extended);const walk=(directory:string,parts:string[])=>{requireThat(++directories<=limit.directories,'PILOT_SIDECAR_LIMIT');for(const entry of readdirSync(directory,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){const path=[...parts,entry.name],full=join(directory,entry.name),stat=lstatSync(full);requireThat(!stat.isSymbolicLink(),'PILOT_SIDECAR_LINK_DENIED');
  if(parts.length===1&&extended&&entry.name==='service-evidence'){requireThat(stat.isDirectory(),'PILOT_ADAPTIVE_PATH_DENIED');continue;}
  if(parts.length===1)requireThat(['workspaces','execution-evidence'].includes(entry.name),'PILOT_ADAPTIVE_PATH_DENIED');
  if(parts.length===2)requireThat(/^[a-f0-9]{64}$/.test(entry.name),'PILOT_ADAPTIVE_PATH_DENIED');
  if(stat.isDirectory()){requireThat(path.length<32,'PILOT_SIDECAR_LIMIT');if(path.length>=4)adaptivePath(path.join('/'),extended);walk(full,path);continue;}
  requireThat(stat.isFile(),'PILOT_ADAPTIVE_PATH_DENIED');const name=adaptivePath(path.join('/'),extended);output.push({path:name,...boundedFile(full,'PILOT_SIDECAR_FILE_INVALID',fileLimit(name,extended))});requireThat(output.length<=limit.files&&output.reduce((n,f)=>n+f.bytes,0)<=limit.total,'PILOT_SIDECAR_LIMIT');
 }};walk(root,['adaptive']);return output;
}
function collectAll(sourceRoot:string,adaptive:boolean,extended=false){const rows=[...collectSidecars(sourceRoot),...(adaptive?collectAdaptive(sourceRoot,extended):[])].sort((a,b)=>a.path.localeCompare(b.path)),limit=limits(extended);requireThat(rows.length<=limit.files&&rows.reduce((sum,item)=>sum+item.bytes,0)<=limit.total,'PILOT_SIDECAR_LIMIT');return rows;}
function sameSidecars(left:Sidecar[],right:Sidecar[]){return hash(left)===hash(right);}
function collectSidecars(sourceRoot:string):Sidecar[]{
 const root=join(sourceRoot,runtimeRoot);if(!existsSync(root))return [];noLinks(root,'PILOT_SIDECAR_LINK_DENIED');const output:Sidecar[]=[];
 const walk=(directory:string,relativePath:string)=>{for(const item of readdirSync(directory,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){const full=join(directory,item.name),next=relativePath?relativePath+'/'+item.name:item.name,stat=lstatSync(full);requireThat(!stat.isSymbolicLink(),'PILOT_SIDECAR_LINK_DENIED');if(stat.isDirectory()){if(relativePath==='')requireThat(item.name==='projects','PILOT_SIDECAR_PATH_DENIED');else if(relativePath==='projects')requireThat(/^[a-z][a-z0-9-]{0,63}$/.test(item.name),'PILOT_SIDECAR_PATH_DENIED');else if(/^projects\/[a-z][a-z0-9-]{0,63}$/.test(relativePath))requireThat(['source','runtime'].includes(item.name),'PILOT_SIDECAR_PATH_DENIED');else if(/\/runtime$/.test(relativePath))requireThat(false,'PILOT_SIDECAR_PATH_DENIED');walk(full,next);continue;}requireThat(stat.isFile(),'PILOT_SIDECAR_PATH_DENIED');const path=sidecarPath(runtimeRoot+'/'+next),info=boundedFile(full,'PILOT_SIDECAR_FILE_INVALID');output.push({path,...info});requireThat(output.length<=maxSidecars&&output.reduce((sum,x)=>sum+x.bytes,0)<=maxSidecarTotal,'PILOT_SIDECAR_LIMIT');}};
 walk(root,'');return output.sort((a,b)=>a.path.localeCompare(b.path));
}
function sidecarSource(root:string,path:string,adaptive=false,extended=false){versionedPath(path,adaptive,extended);const target=resolve(root,path),rel=relative(root,target);requireThat(!rel.startsWith('..')&&!isAbsolute(rel),'PILOT_SIDECAR_PATH_DENIED');return target;}
function snapshotHash(database:V2['database'],sidecars:Sidecar[],adaptive=false,extended=false){return hash({... (extended?{version:'pilot-backup-v4'}:adaptive?{version:'pilot-backup-v3'}:{}),database,sidecars});}
function writeNew(path:string,bytes:Buffer|string){mkdirSync(dirname(path),{recursive:true});writeFileSync(path,bytes,{flag:'wx'});}
function verifyV2(source:string,manifest:any,expectedHash:string){
 const extended=manifest?.version==='pilot-backup-v4',adaptive=extended||manifest?.version==='pilot-backup-v3',limit=limits(extended);
 requireThat(['pilot-backup-v2','pilot-backup-v3','pilot-backup-v4'].includes(manifest?.version)&&manifest.file==='pilot.sqlite'&&manifest.quiescent===true&&typeof manifest.consistency==='string'&&manifest.database?.path==='pilot.sqlite'&&Array.isArray(manifest.sidecars),'RESTORE_MANIFEST_MISMATCH');requireThat(/^[a-f0-9]{64}$/.test(expectedHash)&&manifest.sha256===expectedHash,'RESTORE_MANIFEST_MISMATCH');
 requireThat(Number.isSafeInteger(manifest.database.bytes)&&manifest.database.bytes>=0&&/^[a-f0-9]{64}$/.test(manifest.database.sha256),'RESTORE_MANIFEST_MISMATCH');const db=join(source,'pilot.sqlite'),dbInfo=boundedFile(db,'RESTORE_CONTENT_MISMATCH',536_870_912);requireThat(dbInfo.sha256===manifest.database.sha256&&dbInfo.bytes===manifest.database.bytes,'RESTORE_CONTENT_MISMATCH');
 requireThat(new Set(manifest.sidecars.map((x:any)=>x?.path)).size===manifest.sidecars.length&&manifest.sidecars.length<=limit.files,'RESTORE_SIDECAR_MANIFEST_INVALID');let total=0;for(const item of manifest.sidecars as Sidecar[]){versionedPath(item.path,adaptive,extended);const max=fileLimit(item.path,extended);requireThat(Number.isSafeInteger(item.bytes)&&item.bytes>=0&&item.bytes<=max&&/^[a-f0-9]{64}$/.test(item.sha256),'RESTORE_SIDECAR_MANIFEST_INVALID');total+=item.bytes;requireThat(total<=limit.total,'RESTORE_SIDECAR_MANIFEST_INVALID');const info=boundedFile(sidecarSource(source,item.path,adaptive,extended),'RESTORE_SIDECAR_HASH_MISMATCH',max);requireThat(info.sha256===item.sha256&&info.bytes===item.bytes,'RESTORE_SIDECAR_HASH_MISMATCH');}
 requireThat(snapshotHash(manifest.database,manifest.sidecars,adaptive,extended)===expectedHash,'RESTORE_MANIFEST_MISMATCH');return manifest as V2|V3|V4;
}

export function backupPilot(store: StateStore, directory: string, options:Options={}) {
 const target = resolve(directory); requireThat(!existsSync(target), 'BACKUP_TARGET_EXISTS');requireThat(options.format===undefined||options.format==='v4','BACKUP_FORMAT_INVALID');requireThat(!options.format||options.sourceRoot,'BACKUP_SOURCE_ROOT_REQUIRED');
 if(!options.sourceRoot){mkdirSync(target,{recursive:true});const file=join(target,'pilot.sqlite');store.db.prepare('VACUUM INTO ?').run(file);const manifest:V1={version:'pilot-backup-v1',file:'pilot.sqlite',sha256:rawHash(readFileSync(file)),createdAt:new Date().toISOString(),contains:'company data, immutable evidence, tool observations and local preview state; no credentials',privacy:'private owner data; keep off Git and public storage'};writeFileSync(join(target,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;}
 requireThat(options.quiescent===true,'BACKUP_QUIESCENCE_REQUIRED');noLinks(dirname(target),'PILOT_CONTINUITY_LINK_DENIED');const sourceRoot=absoluteRoot(options.sourceRoot,'BACKUP_SOURCE_ROOT_REQUIRED'),main=store.db.prepare('PRAGMA database_list').all().find((row:any)=>row.name==='main');requireThat(main&&resolve(String(main.file))===join(sourceRoot,'pilot.sqlite'),'BACKUP_SOURCE_DATABASE_MISMATCH');
 assertStopped(store,sourceRoot);const extended=options.format==='v4',adaptive=extended||existsSync(join(sourceRoot,'adaptive'));if(extended)assertServicesStopped(join(sourceRoot,'adaptive'));const before=collectAll(sourceRoot,adaptive,extended);mkdirSync(target,{recursive:true});const file=join(target,'pilot.sqlite');store.db.prepare('VACUUM INTO ?').run(file);const database={path:'pilot.sqlite' as const,...boundedFile(file,'BACKUP_DATABASE_INVALID',536_870_912)};
 for(const item of before){const max=fileLimit(item.path,extended),source=sidecarSource(sourceRoot,item.path,adaptive,extended),info=boundedFile(source,'PILOT_SIDECAR_CHANGED',max);requireThat(info.sha256===item.sha256&&info.bytes===item.bytes,'PILOT_SIDECAR_CHANGED');writeNew(sidecarSource(target,item.path,adaptive,extended),readFileSync(source));const copied=boundedFile(sidecarSource(target,item.path,adaptive,extended),'PILOT_SIDECAR_CHANGED',max);requireThat(copied.sha256===item.sha256&&copied.bytes===item.bytes,'PILOT_SIDECAR_CHANGED');}
 const after=collectAll(sourceRoot,adaptive,extended);assertStopped(store,sourceRoot);if(extended)assertServicesStopped(join(sourceRoot,'adaptive'));requireThat(sameSidecars(before,after),'PILOT_SIDECAR_CHANGED');const sidecars=before,manifest:V2|V3|V4={version:extended?'pilot-backup-v4':adaptive?'pilot-backup-v3':'pilot-backup-v2',file:'pilot.sqlite',database,sidecars,sha256:snapshotHash(database,sidecars,adaptive,extended),createdAt:new Date().toISOString(),quiescent:true,consistency:'Caller declared the owner runtime stopped; known owner and worker processes were checked, and bounded sidecar hashes matched before and after copying. SQLite and sidecars are separate snapshots, not one atomic multi-file snapshot.',contains:extended?'company data, functional-project source and owner records, bounded adaptive binaries and command evidence including stopped uncertain claims; no credential, authorization or live service control files':'company data, immutable evidence, functional-project source and owner records; V3 includes bounded adaptive workspaces and execution receipts; no credential or authorization files',privacy:'private owner data; keep off Git and public storage'};writeFileSync(join(target,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');return manifest;
}
export function restorePilot(directory: string, targetRoot: string, expectedHash: string) {
 const source = resolve(directory), target = resolve(targetRoot);requireThat(!existsSync(target),'RESTORE_TARGET_EXISTS');requireThat(/^[a-f0-9]{64}$/.test(expectedHash),'RESTORE_HASH_REQUIRED');noLinks(source,'PILOT_CONTINUITY_LINK_DENIED');noLinks(dirname(target),'PILOT_CONTINUITY_LINK_DENIED');const manifest=JSON.parse(readFileSync(join(source,'manifest.json'),'utf8'));
 if(manifest.version==='pilot-backup-v1'){requireThat(manifest.file==='pilot.sqlite'&&manifest.sha256===expectedHash,'RESTORE_MANIFEST_MISMATCH');const file=join(source,'pilot.sqlite'),info=boundedFile(file,'RESTORE_CONTENT_MISMATCH',536_870_912);requireThat(info.sha256===expectedHash,'RESTORE_CONTENT_MISMATCH');mkdirSync(target,{recursive:true});copyFileSync(file,join(target,'pilot.sqlite'),constants.COPYFILE_EXCL);const db=new StateStore(join(target,'pilot.sqlite'));try{requireThat(db.db.prepare('PRAGMA integrity_check').get()?.integrity_check==='ok','RESTORE_DATABASE_INVALID');}finally{db.close();}return {restored:true,target,sha256:expectedHash,automaticExecution:false};}
 const v2=verifyV2(source,manifest,expectedHash),extended=v2.version==='pilot-backup-v4',adaptive=extended||v2.version==='pilot-backup-v3';mkdirSync(target,{recursive:true});copyFileSync(join(source,'pilot.sqlite'),join(target,'pilot.sqlite'),constants.COPYFILE_EXCL);for(const item of v2.sidecars)writeNew(sidecarSource(target,item.path,adaptive,extended),readFileSync(sidecarSource(source,item.path,adaptive,extended)));if(adaptive){const copiedDb=boundedFile(join(target,'pilot.sqlite'),'RESTORE_CONTENT_MISMATCH',536_870_912);requireThat(copiedDb.sha256===v2.database.sha256&&copiedDb.bytes===v2.database.bytes,'RESTORE_CONTENT_MISMATCH');}const db=new StateStore(join(target,'pilot.sqlite'));try{requireThat(db.db.prepare('PRAGMA integrity_check').get()?.integrity_check==='ok','RESTORE_DATABASE_INVALID');}finally{db.close();}for(const item of v2.sidecars){const info=boundedFile(sidecarSource(target,item.path,adaptive,extended),'RESTORE_SIDECAR_READBACK_FAILED',fileLimit(item.path,extended));requireThat(info.sha256===item.sha256&&info.bytes===item.bytes,'RESTORE_SIDECAR_READBACK_FAILED');}return {restored:true,target,sha256:expectedHash,sidecars:v2.sidecars.length,automaticExecution:false,consistency:v2.consistency};
}
