import {campaignText,campaignPrice} from '../portfolio/campaign-profile.ts';
const e=(x:unknown)=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
/** Disclosed generic test content; no source-based diagnosis or real inference is claimed. */
export function fixtureCampaign(context:any,base:any){const job=context.workspace.inputs.job??{},sources=context.sources;const claim=(value:string)=>({value,status:'hypothesis',references:[]});
 const foundation={audience:claim(job.audience??'An owner-qualified buyer described by the supplied company evidence'),offer:claim(job.offer??job.outcome??'A bounded owner-reviewed test of the proposed service'),price:{currency:'USD',minorUnits:null,status:'unknown',references:[]},positioning:'Test a specific, clearly scoped offer against the buyer’s existing process. A simpler conversation or existing provider may already be sufficient; superiority and demand are unknown.',scope:['Included: a local reviewed offer and practical demonstration of the proposed workflow.','Excluded: sending, paid promotion, bookings, account access and any guarantee of business results.'],primaryAction:'Owner reviews current company policies and asks a consenting operator to compare this proposal with their existing process under separately approved contact authority.'};
 const assets=[
 {id:'initial-offer',kind:'offer',title:'Initial offer for owner review',body:'For {{audience}}: {{offer}}. Proposed price: {{price}}. Start with a short scope conversation around one actual job. Bring the current alternative and define what a useful result would look like before committing. The initial deliverable is a reviewed plan with clear exclusions; availability and fulfillment need owner confirmation.'},
 {id:'creative-direction',kind:'creative-brief',title:'Creative direction and proof requirements',body:'Audience: {{audience}}. Core offer: {{offer}}. Price statement: {{price}}. Show the actual before-and-after workflow without claiming measured savings. Use a real product or deliverable screenshot after owner approval. Lead with a recognizable operational moment; avoid urgency, testimonials and unsupported comparisons. The creative succeeds if a qualified viewer can explain the offer and identify the next step.'},
 {id:'demonstration-script',kind:'script',title:'Short demonstration script',body:'Opening: “If you are {{audience}}, here is the specific job this proposal addresses.” Demonstrate {{offer}} using clearly labeled example data. Ask the viewer how they handle the same job today, then show the actual produced artifact. Explain that {{price}} is unresolved until scope and delivery effort are understood. Close by asking which part would make them keep their existing process. Do not imply a purchase or consent from polite interest.'},
 {id:'first-conversation',kind:'lifecycle-message',title:'Unsent first-conversation message',body:'Hello — we are exploring a bounded offer for {{audience}}: {{offer}}. We would value a short comparison with your current process, including what would make switching inconvenient. {{price}}. There is no purchase expectation. Would reviewing one concrete example be useful? This is an unsent draft: choose an owner-controlled or consenting recipient and approve the exact wording before contact.'},
 {id:'after-demonstration',kind:'lifecycle-message',title:'Unsent follow-up after a real demonstration',body:'Thank you for reviewing the proposal for {{audience}}. We discussed {{offer}}; {{price}} remains the current price status. Please correct our understanding of the job and the alternative you already use. If there is a worthwhile next test, we can define one observable outcome and the effort required together. Send only after a real conversation; do not invent a prior meeting or a positive reaction.'},
 {id:'measurement-plan',kind:'measurement-plan',title:'Behavioral evidence and decision plan',body:'Population: {{audience}}. Test {{offer}} with {{price}} explicitly unresolved. Record the existing process, actual task completion, consequential errors, requested corrections, elapsed owner interaction and willingness to try the next step. Baseline rates and financial benefit are unknown. Continue only if a qualified operator demonstrates a material unmet need and chooses a concrete follow-up; revise for fixable friction, stop if the current alternative is sufficient. One conversation is exploratory evidence, not a conversion estimate.'},
 {id:'delivery-operations',kind:'operations-plan',title:'Delivery responsibilities and operating limits',body:'Serve {{audience}} through the bounded scope of {{offer}}; disclose {{price}}. The owner confirms rights, policies, account access, destination and external authority. The worker prepares the actual artifact and checks its current version. The owner reviews usefulness and any correction. Record source versions, accepted output, delivery/support effort and unresolved obligations. Acquisition, fulfillment, correction and owner labor are unknown costs until observed. No draft publication or task completion is recorded as revenue.'}
 ].map(a=>({...a,status:'draft_unsent'}));return {...base,recommendation:{...base.recommendation,title:'Review the coordinated commercial proposal against the existing alternative',basis:foundation.positioning,steps:[{action:foundation.primaryAction,owner:'business owner',successMeasure:'A separately authorized observation establishes whether the proposed job matters enough to justify a further bounded test.'}]},campaign:{version:1,foundation,assets}};}
export function fixtureMarketingSections(inputs:any){const c=inputs.campaign,f=c.foundation,asset=(kind:string)=>campaignText(c.assets.find((a:any)=>a.kind===kind).body,f);return `<section id="hero" data-campaign-hash="${e(inputs.campaignArtifactHash)}"><p class="eyebrow">LOCAL COMMERCIAL PROTOTYPE · TEST CONTENT</p><h1>${e(inputs.companyName)}</h1><p data-campaign-audience>${e(f.audience.value)}</p><h2 data-campaign-offer>${e(f.offer.value)}</h2><p data-owner-introduction>Explore this proposed offer with clear scope, evidence limits and a local next step. No customer result is implied.</p><nav class="actions"><a href="#offer">Explore the offer</a><a href="#next-step">Prepare the next step</a></nav></section><section id="problem" class="card"><h2>The job and the current alternative</h2><p>${e(f.positioning)}</p></section><section id="offer" class="card"><h2>What this proposal includes</h2><p>${e(asset('offer'))}</p><p data-campaign-price>${e(campaignPrice(f))}</p><ul>${f.scope.map((x:string)=>'<li>'+e(x)+'</li>').join('')}</ul></section><section id="process" class="card"><h2>How the bounded process works</h2><p>${e(asset('operations-plan'))}</p></section><section id="proof" class="card"><h2>Evidence and what remains unknown</h2><p>${e(asset('measurement-plan'))}</p></section><section id="faq" class="card"><h2>Before deciding on a next step</h2><details><summary>Is this a booking or purchase?</summary><p>No. This local prototype only prepares information for an owner-reviewed next step. No information is sent and no money changes hands.</p></details><details><summary>What has been validated?</summary><p>Mechanical checks can verify this page and its current campaign facts. Demand, independent semantic usefulness, savings and commercial outcomes remain unmeasured.</p></details></section>`;}
