import {mockResult} from '../portfolio/worker.ts';
import type {ModelPort} from '../contracts.ts';
import {requireThat} from '../contracts.ts';
/** Deliberately transparent fixture decisions for controller/UI integration.
 * Neither these choices nor their quality are model-generated. */
export const fixtureOutcomePlanner:ModelPort={kind:'fixture',run(request){
 const c=request.context as any,source=c.sources[0];requireThat(source&&c.mandate,'OUTCOME_FIXTURE_CONTEXT');
 const allowed=c.mandate.allowedFamilies,primary=allowed.includes('response-packet')?'response-packet':allowed.includes('campaign-packet')?'campaign-packet':null,project=allowed.includes('functional-project'),budget=c.mandate.maxCalls-c.mandate.repairReserve-1-(c.mandate.preparationReserve??0);
 const tasks:any[]=[];
 if(primary&&budget>=5)tasks.push({id:'business-deliverable',family:primary,title:'Source-grounded operating brief',outcome:c.mandate.objective,details:'Explicit fixture task: preserve source evidence, limitations and an owner-review next step. No commercial inference is claimed.',dependsOn:[],sourceIds:c.sources.map((s:any)=>s.id).slice(0,12),competencies:['evidence-grounded-work','commercial-writing'],reasonForWorker:'One strong generalist has the necessary source and writing tools; qualification remains experimental.',calls:5});
 if(project&&budget-tasks.reduce((n,t)=>n+t.calls,0)>=8)tasks.push({id:'working-application',family:'functional-project',title:'Local work and review desk',outcome:'Keep the work records and their review state consistent with '+c.business.name+' operating brief.',details:'Explicit fixture task: implement a real multi-file frontend and bounded backend; create, reopen, edit, review and export test records. Inherit the actual checked operating brief. No booking, messaging or real transaction.',dependsOn:tasks.map(t=>t.id),sourceIds:c.sources.map((s:any)=>s.id).slice(0,12),competencies:['artifact-correction','local-browser-implementation'],reasonForWorker:'A separate implementation job needs source, browser and data-model tools; this does not claim a second AI is superior or necessary for every outcome.',calls:8});
 return mockResult({decision:tasks.length?'prepare':'blocked',rationale:'Development-authored fixture plan demonstrates supported work and honest limits. It is not an autonomous priority judgment.',strongestAlternative:'Do no additional work until a separately authorized model evaluates the current business evidence.',blockingConditions:tasks.length?[]:['The explicit fixture needs a supported document or application family and sufficient finishing capacity.'],evidenceRefs:[{sourceId:source.id,quote:source.text}],tasks,successEvidence:['Current artifacts pass trusted checks, local publication and authenticated readback.','Owner correction produces a new authoritative revision and invalidates old dependent evidence.'],limitsOfInference:'Offline integration mechanics only. No actual-model competence, commercial outcome, optimal team or independent semantic review.'});
}};
