import {mockResult} from '../portfolio/worker.ts';
import type {ModelPort} from '../contracts.ts';

/** Developer-visible test cases. They are never used by a live adapter or as hidden labels in worker context. */
export const commercialCases = {
 service: {
  name:'Signal Bench — synthetic analytics service',website:'https://signal-bench.example/',
  goal:'Help an operations manager decide whether a bounded reporting cleanup is useful before buying a recurring service.',
  notes:'Developer-authored B2B service fixture. No real customers, revenues, interviews or claimed business result.',
  pages:[
   {path:'/',title:'Reporting cleanup service',text:'Signal Bench offers a fixed-scope reporting cleanup for small operations teams. The website lists dashboards, automation and training together. A visitor is asked to request a general consultation. No turnaround promise or recurring price is published. The pilot can produce a local reporting-readiness packet; it cannot access business systems or execute data changes.',links:['/scope','/process','/terms']},
   {path:'/scope',title:'Current service scope',text:'The initial service is a reporting-readiness review: map one recurring report, document its source fields and identify one decision it should support. The buyer must provide an anonymized sample and permission for its use. Integration and ongoing dashboard management are separate work, quoted only after access and scope review. This scope supersedes the previous all-in-one setup description.',links:['/terms']},
   {path:'/process',title:'Service process',text:'The proposed buyer is an operations manager responsible for a recurring report. The current alternative may be an analyst, a spreadsheet or doing nothing. The service has no observed acquisition, retention or correction-time measurements. A useful first test compares the readiness packet against the buyer’s current reporting process. No testimonial or quantified saving is available.',links:[]},
   {path:'/terms',title:'Current operating rules',text:'Never promise dashboard integration, a completion date or a price before owner scope review. Do not request credentials in an inquiry. Samples must be anonymized. All public communication needs exact owner approval. Draft a readiness checklist and a local explanatory page; neither represents customer demand.',links:[]}
  ],
  focus:{title:'Make the first engagement concrete',noticed:'The homepage mixes dashboards, automation and training but asks only for a general consultation.',mechanism:'A buyer cannot easily tell whether the first step solves a bounded reporting problem or commits them to an open-ended integration. This could create uncertainty; its actual conversion effect is unknown.',intervention:'Prepare a reporting-readiness offer and a local page that explains its boundaries and the anonymized sample needed.',alternative:'Keep the current website and use one clearly scoped owner conversation, or retain the spreadsheet/analyst already doing the job.',priority:'The intervention resolves a visible scope contradiction using current service evidence and requires no system access.',reversal:'If qualified operators already understand the scope or their obstacle is unavailable data access, prioritize that prerequisite rather than messaging.',audience:'Operations managers responsible for one recurring report',offer:'A reporting-readiness packet for one existing report, subject to owner scope review'},
  secondary:{title:'Measure the current reporting burden',intervention:'Prepare an observation worksheet for report frequency, correction effort and decision usefulness before estimating economic savings.'}
 },
 retail: {
  name:'Moss & Kettle — synthetic tea retailer',website:'https://moss-kettle.example/',
  goal:'Help first-time tea buyers choose a suitable sampler without unsupported taste, stock or delivery promises.',
  notes:'Developer-visible transfer fixture authored after the generic contracts. Not a protected holdout. No actual orders, revenue or customer outcomes.',
  pages:[
   {path:'/',title:'Loose-leaf tea collection',text:'Moss & Kettle sells loose-leaf tea and a discovery sampler. The homepage groups products by origin but provides no comparison by caffeine level or preparation equipment. A discovery sampler is listed as an introductory option. Current stock, delivered price and conversion data are unavailable to this public-only test.',links:['/sampler','/brewing','/shipping']},
   {path:'/sampler',title:'Discovery sampler',text:'The sampler contains three labeled tea varieties with brewing instructions. It is intended as a comparison aid, not a health treatment. Caffeine varies and is not laboratory measured. Do not invent ingredient weights, certifications, customer reviews or a caffeine-free guarantee. Sampler price and stock must be confirmed before a purchase recommendation.',links:['/brewing']},
   {path:'/brewing',title:'Brewing guide',text:'The buyer needs to know what equipment is required before choosing tea. The current guide assumes access to a loose-leaf infuser but says a reusable strainer is an alternative. A local discovery guide may ask about equipment and desired caffeine avoidance, then recommend questions for the owner rather than inventing a product specification.',links:[]},
   {path:'/shipping',title:'Delivery and returns',text:'Dispatch timing depends on confirmed stock and destination. The current policy requires a human check before giving delivery estimates. An archived seasonal banner promised next-day dispatch; it is superseded. Returns and allergies must be discussed using current owner policy. No shipping, payment or customer communication is connected in this local test.',links:[]}
  ],
  focus:{title:'Reduce uncertainty before a first sampler purchase',noticed:'Products are grouped by origin, while the buyer-facing guide assumes an infuser and public stock/price information is incomplete.',mechanism:'A new buyer may not know whether the product fits their equipment and caffeine constraints. Clear prerequisite information could help a useful decision; a sales effect has not been observed.',intervention:'Prepare a sampler discovery packet and a local page that explains equipment, known product facts and the questions needing owner confirmation.',alternative:'Use the existing brewing guide and one owner conversation, or buy a familiar supermarket tea instead of adding another page.',priority:'Equipment and unsupported dispatch promises are directly visible issues; a bounded guide can clarify them without inventing fulfillment information.',reversal:'If buyers already understand equipment and the main obstacle is stock or delivered price, fix that information before promoting the sampler.',audience:'First-time loose-leaf tea buyers comparing a sampler with their current tea',offer:'A sampler discovery guide with equipment and owner-confirmation questions'},
  secondary:{title:'Confirm fulfillment before making an offer',intervention:'Prepare a current stock, delivered-price and delivery-policy checklist for owner completion; make no purchase or health promise.'}
 }
} as const;

export function fixtureCommercialOutput(which:keyof typeof commercialCases,sources:any[]){
 const c=commercialCases[which],p=c.pages,ref=(index:number)=>{const s=sources.find(s=>s.text.includes(p[index].text));if(!s)throw Error('FIXTURE_REQUIRED_PAGE_MISSING');return {sourceId:s.id,quote:p[index].text};};
 const f=c.focus;
 return {kind:'commercial-understanding-v1',executiveSummary:f.title+'. '+f.intervention+' This is an offline mechanics demonstration, not an actual-model recommendation or customer validation.',
  report:`Prepared synthetic analysis for ${c.name}\n\nWhat is visible\n${p.map(x=>x.text).join('\n\n')}\n\nWhy this could matter\n${f.mechanism}\n\nThe strongest practical alternative\n${f.alternative}\n\nProposed bounded work\n${f.intervention}\n\nWhat could change the decision\n${f.reversal}\n\nEconomics and distribution\nNo channel conversion, willingness to pay, retention, contribution margin or owner labor is measured. Reach a consenting qualified buyer only after separate owner authority. Compare the deliverable against the existing process; a pleasant response is not demand.\n\nExecution boundaries\nUse one strong generalist with current company evidence. The commercial packet establishes one shared audience, offer and uncertainty record; a website depends on that checked artifact. A second worker is not justified by these fixtures. No messages, purchases, deployments or business actions occur.`,
  claims:p.map((x,i)=>({id:'claim-'+i,kind:'source_assertion',dimension:i===0?'positioning':i===1?'offer':i===2?'customer-journey':'policy',statement:x.text,evidenceRefs:[ref(i)]})),
  findings:[{id:'visible-uncertainty',title:f.title,noticed:f.noticed,mechanism:f.mechanism,evidenceRefs:[ref(0),ref(1)],uncertainty:'The source content is synthetic; causal priority, buyer behavior and economic impact are unmeasured.'}],
  contradictions:[],unknowns:[{question:'Does a qualified buyer regard this uncertainty as consequential compared with their current alternative?',decisionUse:'Determines whether to continue the intervention or keep the simpler process.'},{question:'What is the actual acquisition, delivery and owner correction effort?',decisionUse:'Required before estimating contribution margin or labor savings.'}],
  opportunities:[{id:'clarify-first-step',title:f.title,noticed:f.noticed,mechanism:f.mechanism,intervention:f.intervention,alternative:f.alternative,priorityBasis:f.priority,changeConditions:[f.reversal],evidenceRefs:[ref(0),ref(1),ref(3)],dependsOn:[],deliverables:[{family:'campaign-packet',title:'Coordinated offer and validation packet',outcome:f.offer,details:'Keep one shared audience and offer across an offer, creative brief, demonstration script, two unsent lifecycle messages, measurement plan and operating plan. '+f.audience,dependency:'Uses current public evidence; owner approval is required for future contact.'},{family:'marketing-page',title:'Local page for the reviewed offer',outcome:'Explain the checked commercial offer and a safe next step in a usable browser preview.',details:'Implement the actual current campaign foundation, preserve unknown prices and public-source limitations, inspect desktop and phone behavior.',dependency:'Requires the checked authoritative campaign artifact.'}]},
  {id:'observe-before-scale',title:c.secondary.title,noticed:'The source explicitly lacks commercial measurements.',mechanism:'Unmeasured effort and buyer response make a revenue projection unreliable.',intervention:c.secondary.intervention,alternative:'Assume a conversion rate or margin; this would add unsupported precision.',priorityBasis:'Avoid investing in scale without evidence of a useful job and feasible delivery.',changeConditions:['A reliable owner export or a recorded observation supplies the missing measurement.'],evidenceRefs:[ref(2)],dependsOn:[],deliverables:[{family:'unsupported',title:'Owner-authorized buyer observation',outcome:'Obtain one real behavioral observation under separate contact and data authority.',details:c.secondary.intervention,dependency:'Requires a consenting participant and explicit external-action authorization.'}]}],selectedOpportunityId:'clarify-first-step',selectionReason:f.priority,
  economics:{observed:'No commercial economics are measured in this synthetic fixture.',assumptions:['Any proposed price, conversion or labor estimate would be a hypothesis requiring validation.'],missing:['Acquisition cost','Delivery and correction effort','Actual accepted outcomes','Current price and fulfillment limits']}};
}
export const commercialFixturePort=(which:keyof typeof commercialCases,sources:any[]):ModelPort=>({kind:'fixture',async run(){return mockResult(fixtureCommercialOutput(which,sources));}});
