/** Exact opt-in commercial outcome authority. Reuses OperatingModels and
 * PortfolioEngine; no second ledger, hidden inference or external action port. */
import {existsSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {hostname} from 'node:os';
import {isAbsolute,join,resolve} from 'node:path';
import {hash,canonical,rawHash,requireThat,scopeKey} from '../contracts.ts';
import type {ModelPort,ModelRequest,Scope} from '../contracts.ts';
import {signed,verified} from '../experiment/config.ts';
import {assertCountableRequest} from '../experiment/token-count.ts';
import {OperatingModels,implementationHash as operatingImplementationHash} from '../operations/model.ts';
import type {OperatingGrant} from '../operations/model.ts';
import {buildResponsesBody} from '../model-port.ts';
import {portfolioRoute,portfolioImplementationHash,taskDefinitionHash} from '../portfolio/live.ts';
import {PortfolioEngine} from '../portfolio/engine.ts';
import {workerSchema,workerScope,validateWorker,FINALIZING_WORKER_PROCEDURE} from '../portfolio/worker.ts';
import type {WorkerCall,WorkerModel} from '../portfolio/worker.ts';
import {pilotImplementationHash} from './binding.ts';
import {PilotLearning} from './learning.ts';
import {ProcedureRegistry} from '../portfolio/learning.ts';
import {PilotIntelligence} from './intelligence.ts';
import {PilotDiscovery,discoverySchema,discoveryProcedure,DISCOVERY_VERSION} from './discovery.ts';
import type {DiscoveryFailureObservation} from './discovery.ts';
import {intelligenceSchema,COMMERCIAL_PROCEDURE,validateIntelligence} from './intelligence-contract.ts';

const AUTH='pilot.intelligence.authorization.json',PROPOSAL='pilot.intelligence.authorization.request.json';
export const intelligenceStageCaps={investigation:6,analysis:1,campaign:6,page:8,correction:4} as const;
type Stage=keyof typeof intelligenceStageCaps;
type Services={intelligence:PilotIntelligence;discovery:PilotDiscovery};
type Binding={kind:'business-intelligence-outcome-033-v1';id:string;businessId:string;implementationHash:string;companyHash:string;initialSources:Array<{id:string;sha256:string}>;discovery:{id:string;version:string;seeds:string[];limits:any;includeImages:boolean};stageCaps:Record<Stage,number>;procedures:{investigation:string;analysis:string;campaign:string;page:string;correction:string};schemas:{investigation:string;analysis:string;worker:string};initialRequest:{request:ModelRequest;requestHash:string;bodyHash:string};selectedOpportunityLimit:1;externalEffects:false};
export type IntelligenceGrant=OperatingGrant&{intelligence:Binding};
const accountScope=(id:string):Scope=>({tenantId:'mason',businessId:'business-intelligence-model-account',runId:id,dataPolicyVersion:'selected-business-outcome-033-v1',mode:'fixture'});
const companyFacts=(c:any)=>({id:c.id,name:c.name,goal:c.goal,website:c.website,notes:c.notes,mode:c.mode});
const rows=(services:Services,kind:string)=>services.intelligence.store.db.prepare('SELECT body FROM entities WHERE kind=? ORDER BY key').all(kind).map(r=>JSON.parse(String(r.body)));
const implementation=()=>hash({pilot:pilotImplementationHash(),portfolio:portfolioImplementationHash(),operating:operatingImplementationHash()});
function caps(includeCorrection:boolean){return {...intelligenceStageCaps,correction:includeCorrection?4:0};}
function limits(businessId:string,stageCaps:Record<Stage,number>,reserve:number){const total=Object.values(stageCaps).reduce((a,b)=>a+b,0);return {totalMinor:total*205+reserve,concurrency:1,astraCountRequests:total,overheadReserve:{minor:reserve,reason:'Explicit unpriced count and bounded same-ID retrieval uncertainty; not a provider fee quote.'},stages:{smoke:{minor:0,attempts:0},development:{minor:total*205,attempts:total},validation:{minor:0,attempts:0},evaluation:{minor:0,attempts:0}},allocations:[{metadataKey:'businessId',value:businessId,attempts:total,minor:total*205},...Object.entries(stageCaps).map(([stage,n])=>({metadataKey:'stage',value:stage,attempts:n,minor:n*205}))]};}
function bodyHash(g:IntelligenceGrant,request:ModelRequest,schema:any){const body=buildResponsesBody(g.route,{...request,scope:g.accountScope},schema);assertCountableRequest(body,196608);return {body,bytes:canonical(body),hash:rawHash(canonical(body))};}
function validate(services:Services,root:string,g:IntelligenceGrant,approved:boolean){const b=g?.intelligence,store=services.intelligence.store;
 requireThat(b?.kind==='business-intelligence-outcome-033-v1'&&/^intelligence-033-[A-Za-z0-9_-]+$/.test(b.id),'INTELLIGENCE_SIGNED_BINDING_REQUIRED');
 requireThat(['live','mock'].includes(g.mode)&&/^proj_[A-Za-z0-9_-]+$/.test(g.projectId),'INTELLIGENCE_MODE_OR_PROJECT');
 requireThat(g.root===resolve(root)&&g.host===hostname()&&g.kind==='operations-model-grant-v1'&&g.implementationHash===operatingImplementationHash()&&b.implementationHash===implementation(),'INTELLIGENCE_CODE_OR_LOCATION_CHANGED');
 requireThat(hash(g.accountScope)===hash(accountScope(b.id))&&g.retries===0&&g.providerConcurrency===1&&g.externalAuthority===false&&!g.recovery&&!g.stageContracts&&!g.learningGate&&g.countDeadlineMs===10000&&g.countRequestByteCeiling===196608,'INTELLIGENCE_AUTHORITY_SCOPE');
 requireThat(typeof b.discovery.includeImages==='boolean','INTELLIGENCE_IMAGE_SCOPE');
 requireThat(b.discovery.limits.maxDecisions===b.stageCaps.investigation,'INTELLIGENCE_DISCOVERY_VISIBLE_CAP_MISMATCH');
 requireThat(hash(b.stageCaps)===hash(caps(b.stageCaps.correction===4))&&b.selectedOpportunityLimit===1&&!b.externalEffects,'INTELLIGENCE_STAGE_CAPS');
 const reserve=g.limits.overheadReserve?.minor;requireThat(Number.isSafeInteger(reserve)&&reserve!>0&&hash(g.limits)===hash(limits(b.businessId,b.stageCaps,reserve!)),'INTELLIGENCE_AGGREGATE_LIMITS');
 requireThat(hash(g.route)===hash(portfolioRoute(b.id,g.projectId,true,true))&&g.businesses.length===1&&g.businesses[0].id===b.businessId&&g.businesses[0].maxCalls===Object.values(b.stageCaps).reduce((a,n)=>a+n,0)&&g.businesses[0].sourceHosts.length===0,'INTELLIGENCE_ROUTE_SCOPE');
 requireThat(g.credentialFile===null||typeof g.credentialFile==='string'&&isAbsolute(g.credentialFile),'INTELLIGENCE_CREDENTIAL_LOCATION');
 requireThat(hash(b.schemas)===hash({investigation:hash(discoverySchema),analysis:hash(intelligenceSchema),worker:hash(workerSchema)})&&b.procedures.investigation===hash(discoveryProcedure)&&b.procedures.analysis===hash(COMMERCIAL_PROCEDURE)&&b.procedures.correction===hash(FINALIZING_WORKER_PROCEDURE),'INTELLIGENCE_CONTRACT_CHANGED');
 const selectedHash=(workflow:string,capability:string)=>{const scope={capability,population:'pilot-company-'+b.businessId+'-'+workflow};return hash(new ProcedureRegistry(store).selected(scope,'pilot-baseline-'+hash(scope).slice(0,20)).procedure.procedure);};requireThat(b.procedures.campaign===selectedHash('campaign-packet','service.brief')&&b.procedures.page===selectedHash('marketing-page','software.build'),'INTELLIGENCE_WORKER_PROCEDURE_CHANGED');
 requireThat(b.initialRequest.requestHash===hash(b.initialRequest.request)&&b.initialRequest.bodyHash===bodyHash(g,b.initialRequest.request,discoverySchema).hash,'INTELLIGENCE_INITIAL_REQUEST_CHANGED');
 requireThat(approved?g.approvedBy.trim().length>0&&g.approvalReference.trim().length>0:g.approvedBy===''&&g.approvalReference==='','INTELLIGENCE_APPROVAL_REQUIRED');
 requireThat(Number.isFinite(Date.parse(g.expiresAt)),'INTELLIGENCE_EXPIRY_REQUIRED');return b;
}
/** The original owner data remains fixed. Only this bound discovery session may
 * add public material; unrelated uploads or excluded inputs cannot enter calls. */
function currentContext(services:Services,g:IntelligenceGrant){const b=g.intelligence,k=services.intelligence.knowledge,c=k.company(b.businessId),session=services.intelligence.store.get('pilot-discovery',b.businessId);
 requireThat(hash(companyFacts(c))===b.companyHash&&hash(c.goal)===g.businesses[0].goalHash,'INTELLIGENCE_OWNER_CONTEXT_CHANGED');
 requireThat(session?.id===b.discovery.id&&session.version===b.discovery.version&&hash(session.seeds)===hash(b.discovery.seeds)&&hash(session.limits)===hash(b.discovery.limits),'INTELLIGENCE_DISCOVERY_SCOPE_CHANGED');
 const selected=k.selectedSources(b.businessId),publicRows=services.discovery.sources(b.businessId);
 requireThat(b.initialSources.every(s=>selected.some(p=>p.id===s.id&&p.sha256===s.sha256)),'INTELLIGENCE_INITIAL_EVIDENCE_CHANGED');
 for(const s of selected){requireThat(b.initialSources.some(p=>p.id===s.id&&p.sha256===s.sha256)||publicRows.some((r:any)=>r.sessionId===b.discovery.id&&r.companyId===b.businessId&&r.status==='retrieved'&&r.knowledgeSourceId===s.id&&s.origin?.recordId===r.id&&s.origin?.contentHash===r.result?.source?.contentHash),'INTELLIGENCE_UNGRANTED_SOURCE');requireThat(!s.validUntil||Date.parse(s.validUntil)>=Date.now(),'INTELLIGENCE_STALE_SOURCE');}
 requireThat(g.mode!=='mock'||c.mode==='fixture','INTELLIGENCE_MOCK_FIXTURE_REQUIRED');return c;
}
export function prepareIntelligenceAuthorization(services:Services,input:{root:string;directory:string;id:string;businessId:string;projectId:string;credentialFile:string|null;expiresAt:string;countUncertaintyMinor:number;includeCorrection?:boolean;includeImages?:boolean;mode?:'mock'|'live';billingPublicKey?:string|null}){
 requireThat(!existsSync(join(input.root,AUTH))&&!existsSync(join(input.directory,PROPOSAL)),'INTELLIGENCE_NEW_UNSIGNED_PACKET_REQUIRED');requireThat(/^proj_[A-Za-z0-9_-]+$/.test(input.projectId)&&Date.parse(input.expiresAt)>Date.now(),'INTELLIGENCE_PROJECT_OR_EXPIRY');
 const k=services.intelligence.knowledge,c=k.company(input.businessId),s=services.intelligence.store.get('pilot-discovery',input.businessId);requireThat(s&&!s.pending&&s.used.decisions===0&&s.state!=='ready_for_analysis','INTELLIGENCE_UNSTARTED_DISCOVERY_REQUIRED');
 const selected=k.selectedSources(input.businessId);requireThat(selected.length>0&&selected.length<=24,'INTELLIGENCE_INITIAL_SOURCE_LIMIT');const stageCaps=caps(input.includeCorrection===true),learning=new PilotLearning(k.store),first=services.discovery.request(input.businessId,undefined,{includeImages:input.includeImages===true}),route=portfolioRoute(input.id,input.projectId,true,true);
 const binding:Binding={kind:'business-intelligence-outcome-033-v1',id:input.id,businessId:input.businessId,implementationHash:implementation(),companyHash:hash(companyFacts(c)),initialSources:selected.map(p=>({id:p.id,sha256:p.sha256})),discovery:{id:s.id,version:s.version,seeds:s.seeds,limits:s.limits,includeImages:input.includeImages===true},stageCaps,procedures:{investigation:hash(discoveryProcedure),analysis:hash(COMMERCIAL_PROCEDURE),campaign:learning.assignment(c.id,'campaign-packet').procedureHash,page:learning.assignment(c.id,'marketing-page').procedureHash,correction:hash(FINALIZING_WORKER_PROCEDURE)},schemas:{investigation:hash(discoverySchema),analysis:hash(intelligenceSchema),worker:hash(workerSchema)},initialRequest:{request:first.request,requestHash:hash(first.request),bodyHash:''},selectedOpportunityLimit:1,externalEffects:false};
 const grant:IntelligenceGrant={kind:'operations-model-grant-v1',mode:input.mode??'live',root:resolve(input.root),host:hostname(),implementationHash:operatingImplementationHash(),projectId:input.projectId,credentialFile:input.credentialFile,expiresAt:input.expiresAt,approvedBy:'',approvalReference:'',billingPublicKey:input.billingPublicKey??null,accountScope:accountScope(input.id),route,limits:limits(c.id,stageCaps,input.countUncertaintyMinor),businesses:[{id:c.id,goalHash:hash(c.goal),sourceHosts:[],maxCalls:Object.values(stageCaps).reduce((a,n)=>a+n,0)}],retries:0,providerConcurrency:1,countDeadlineMs:10000,countRequestByteCeiling:196608,externalAuthority:false,intelligence:binding};
 binding.initialRequest.bodyHash=bodyHash(grant,first.request,discoverySchema).hash;validate(services,input.root,grant,false);currentContext(services,grant);
 const summary={proposalHash:hash(grant),approved:false,providerRequests:0,maximumExposureMinor:grant.limits.totalMinor,stageCaps,currency:'USD',route,firstUsefulRequest:first.request.requestId,privacy:'Approved company data and this discovery session’s retained public evidence are transmitted. store:true background execution requires acceptance of provider retention at least 30 days.',pricing:'Official September 13 pricing basis: 205 USD cents per 32768-input/32768-total-output Astra Max admission. Reconfirm project access and pricing freshness before owner approval; no probe or spending occurs during preparation.',dynamicWork:'One owner-selected opportunity from this grant’s validated analysis may produce campaign and page work. Each generated task and exact request is durably bound before admission. Optional correction requires the exact existing artifact and owner instruction.',continuation:'The discovery session must be configured with maxDecisions:6 before preparation, including its finish decision. Same-ID response retrieval only. No replacement inference, fallback, stage transfer, hidden judge or new opportunity execution.',exclusions:['No sending, customer contact, accounts, purchases, deployment or real transactions','No protected evaluation or specialist certification','No prior mission grants or exposure transfer'],capacity:'The ceilings allow useful reads, source authorship, browser checks and targeted repair. They do not guarantee response completion or economic value.'};
 mkdirSync(input.directory,{recursive:true});writeFileSync(join(input.directory,PROPOSAL),JSON.stringify(grant,null,2)+'\n',{flag:'wx'});writeFileSync(join(input.directory,'intelligence-exact-initial-request.json'),JSON.stringify({...first,...bodyHash(grant,first.request,discoverySchema)},null,2)+'\n',{flag:'wx'});writeFileSync(join(input.directory,'intelligence-execution-summary.json'),JSON.stringify(summary,null,2)+'\n',{flag:'wx'});return {proposal:grant,proposalHash:hash(grant),summary};
}
export function signIntelligenceProposal(services:Services,root:string,input:{proposal:IntelligenceGrant;expectedHash:string;principal:string;approvalReference:string;publicKey:string;privateKey:string}){requireThat(hash(input.proposal)===input.expectedHash&&!existsSync(join(root,AUTH)),'INTELLIGENCE_EXACT_APPROVAL_HASH');validate(services,root,input.proposal,false);currentContext(services,input.proposal);requireThat(Date.parse(input.proposal.expiresAt)>Date.now(),'INTELLIGENCE_GRANT_EXPIRED');const g={...structuredClone(input.proposal),approvedBy:input.principal,approvalReference:input.approvalReference};validate(services,root,g,true);const envelope=signed(g,input.privateKey);verified(envelope,input.publicKey);mkdirSync(join(root,'auth'),{recursive:true});const anchor=join(root,'auth','portfolio-owner.pub');if(existsSync(anchor))requireThat(readFileSync(anchor,'utf8')===input.publicKey,'INTELLIGENCE_TRUST_ANCHOR_CHANGED');else writeFileSync(anchor,input.publicKey,{flag:'wx'});writeFileSync(join(root,AUTH),JSON.stringify(envelope,null,2)+'\n',{flag:'wx'});services.intelligence.store.record(g.accountScope,'owner-exact-approval','IntelligenceOutcomeApproval',{proposalHash:input.expectedHash,grantHash:hash(g),principal:input.principal,approvalReference:input.approvalReference});return {envelope,proposalHash:input.expectedHash,credentialRead:false,providerRequests:0};}

export function loadAuthorizedIntelligence(services:Services,root:string,options:{envelope?:any;trustedPublicKey?:string;execution?:{kind:'mock';transport:typeof fetch}|{kind:'live';transport?:typeof fetch;credential?:()=>string}}={}){
 const envelope=options.envelope??JSON.parse(readFileSync(join(root,AUTH),'utf8')),publicKey=options.trustedPublicKey??readFileSync(join(root,'auth','portfolio-owner.pub'),'utf8'),g=verified(envelope,publicKey) as IntelligenceGrant,b=validate(services,root,g,true),store=services.intelligence.store,x=services.intelligence.execution;
 // Lazy protected-file access occurs only after verified live admission. Explicit
 // mock transport never reaches fetch or this credential function.
 const credential=options.execution?.kind==='live'&&options.execution.credential?options.execution.credential:()=>{requireThat(typeof g.credentialFile==='string'&&isAbsolute(g.credentialFile),'INTELLIGENCE_PROTECTED_CREDENTIAL_REQUIRED');return readFileSync(g.credentialFile,'utf8').trim();};
 const execution=options.execution?.kind==='mock'?options.execution:{kind:'live' as const,credential,transport:options.execution?.transport??fetch};
 const models=new OperatingModels({store,root,envelope,trustedPublicKey:publicKey,execution}),principal={id:g.approvedBy,tenantId:'mason',businessId:b.businessId,permissions:['read','operate'] as any},bindingKey=b.id+'/';
 const failureObservation=(attemptId:string):DiscoveryFailureObservation=>{const row=models.ledger.get(attemptId),job=store.get('response-job',models.ledger.key(attemptId)),terminal=job?.terminal?.status??row?.observation?.status;return {status:!row?'not_admitted':terminal==='incomplete'?'terminal_incomplete':['failed','cancelled'].includes(terminal)||terminal==='completed'&&row.errorCode?'terminal_failed':'unknown',observationId:'model-attempt/'+attemptId,code:!row?'NO_PROVIDER_ADMISSION':typeof row.errorCode==='string'&&/^[A-Z_0-9]{1,80}$/.test(row.errorCode)?row.errorCode:null};};
 const bindings=()=>rows(services,'pilot-outcome-task-binding').filter(r=>r.grantHash===hash(g));
 const exposedResult=(result:any)=>g.mode==='live'?result:{...result,route:{...result.route,kind:'fixture' as const,provider:'offline-responses-mock'}};
 const checkNew=()=>{validate(services,root,g,true);currentContext(services,g);requireThat(Date.parse(g.expiresAt)>Date.now(),'INTELLIGENCE_GRANT_EXPIRED');};
 const invoke=async(stage:Stage,request:ModelRequest,schema:any,accept:(out:any)=>void,recover=false)=>{
  validate(services,root,g,true);const prior=models.ledger.get(request.requestId);
  if(recover)requireThat(prior,'INTELLIGENCE_RECOVERY_NOT_ADMITTED');else {requireThat(!prior,'INTELLIGENCE_USE_SAME_RESPONSE_RECOVERY');checkNew();}
  return exposedResult(await models.invoke(principal,{businessId:b.businessId,goalHash:g.businesses[0].goalHash,sourceHosts:[],attemptId:request.requestId,stage,request,schema,validate:accept}));
 };
 const investigation=async(request:ModelRequest,recover:boolean)=>{
  const intent=store.get('pilot-discovery-record',request.requestId);
  requireThat(intent?.companyId===b.businessId&&intent.sessionId===b.discovery.id&&intent.kind==='decision'&&intent.requestHash===hash(request)&&hash(intent.request)===hash(request)&&hash(intent.schema)===b.schemas.investigation,'INTELLIGENCE_DISCOVERY_INTENT_REQUIRED');
  requireThat(hash(request.role.procedure)===b.procedures.investigation&&request.role.model===g.route.model&&(!request.images?.length||b.discovery.includeImages),'INTELLIGENCE_DISCOVERY_PROCEDURE_OR_IMAGES');
  if(request.requestId===b.initialRequest.request.requestId)requireThat(bodyHash(g,request,discoverySchema).hash===b.initialRequest.bodyHash,'INTELLIGENCE_FIRST_REQUEST_CHANGED');
  else requireThat(models.ledger.rows().some(r=>r.id===b.initialRequest.request.requestId&&r.metadata.stage==='investigation'),'INTELLIGENCE_INITIAL_REQUEST_REQUIRED');
  return invoke('investigation',request,discoverySchema,out=>{services.discovery.validateAction(b.businessId,out,request.context);},recover);
 };
 const analysis=async(request:ModelRequest,recover:boolean)=>{
  const intent=store.get('pilot-commercial-attempt',b.businessId+'/'+request.requestId);
  requireThat(intent?.businessId===b.businessId&&intent.requestHash===hash(request)&&hash(intent.request)===hash(request)&&hash(request.role.procedure)===b.procedures.analysis&&request.role.model===g.route.model,'INTELLIGENCE_ANALYSIS_INTENT_REQUIRED');
  if(!recover){requireThat(store.get('pilot-discovery',b.businessId)?.state==='ready_for_analysis','INTELLIGENCE_DISCOVERY_FINISH_REQUIRED');const decisions=rows(services,'pilot-discovery-record').filter(r=>r.companyId===b.businessId&&r.sessionId===b.discovery.id&&r.kind==='decision');requireThat(decisions.length>0&&decisions.every(r=>r.status==='applied'&&models.ledger.get(r.id)?.metadata.stage==='investigation'&&hash(store.get('operating-response',scopeKey(g.accountScope)+'/'+r.id)?.result?exposedResult(store.get('operating-response',scopeKey(g.accountScope)+'/'+r.id).result):null)===hash(r.result)),'INTELLIGENCE_THIS_GRANT_DISCOVERY_REQUIRED');}
  return invoke('analysis',request,intelligenceSchema,out=>{validateIntelligence(out,intent.sources);},recover);
 };
 const investigationPort:ModelPort & {recoverSameResponse:(request:ModelRequest)=>Promise<any>}={kind:g.mode==='mock'?'fixture':'live',run:request=>investigation(request,false),recoverSameResponse:request=>investigation(request,true)};
 const analysisPort:ModelPort & {recoverSameResponse:(request:ModelRequest)=>Promise<any>}={kind:g.mode==='mock'?'fixture':'live',run:request=>analysis(request,false),recoverSameResponse:request=>analysis(request,true)};
 const selectedWork=(taskId:string)=>{
  const task=x.portfolio.getTask(taskId),input=task.inputs as any;requireThat(task.ventureId===b.businessId&&input.pilotRelease==='032','INTELLIGENCE_TASK_BUSINESS');
  const works=rows(services,'pilot-commercial-work').filter(w=>w.businessId===b.businessId),work=works.find(w=>w.campaignTaskId===taskId||w.pageTaskId===taskId||w.campaignTaskId===input.correctionOf||w.pageTaskId===input.correctionOf);
  requireThat(work,'INTELLIGENCE_OWNER_SELECTED_WORK_REQUIRED');
  const decision=store.get('pilot-opportunity-decision',b.businessId+'/'+work.analysisAttemptId+'/'+work.opportunityId),attempt=store.get('pilot-commercial-attempt',b.businessId+'/'+work.analysisAttemptId),admitted=models.ledger.get(work.analysisAttemptId),saved=store.get('operating-response',scopeKey(g.accountScope)+'/'+work.analysisAttemptId);
  requireThat(decision?.action==='selected'&&attempt?.status==='completed'&&saved&&admitted?.metadata.stage==='analysis'&&hash(exposedResult(saved.result))===hash(attempt.result),'INTELLIGENCE_THIS_GRANT_ANALYSIS_REQUIRED');
  const selected=store.get('pilot-outcome-selection',b.id);requireThat(!selected||selected.opportunityId===work.opportunityId&&selected.analysisAttemptId===work.analysisAttemptId,'INTELLIGENCE_SINGLE_OPPORTUNITY_LIMIT');
  let stage:Stage;if(input.correctionOf){requireThat(b.stageCaps.correction===4&&task.capability==='quality.review'&&typeof input.ownerCorrection==='string'&&input.ownerCorrection.trim().length>=5&&/^[a-f0-9]{64}$/.test(input.correctionArtifactHash),'INTELLIGENCE_EXACT_CORRECTION_REQUIRED');const parent=x.artifact(b.businessId,input.correctionOf);requireThat(parent?.hash===input.correctionArtifactHash&&task.inputArtifacts.some(a=>a.sha256===parent.hash),'INTELLIGENCE_CORRECTION_ARTIFACT_CHANGED');stage='correction';}
  else {stage=input.pilotWorkflow==='campaign-packet'?'campaign':'page';requireThat(stage==='campaign'?task.capability==='service.brief'&&taskId===work.campaignTaskId:input.pilotWorkflow==='marketing-page'&&task.capability==='software.build'&&taskId===work.pageTaskId,'INTELLIGENCE_TASK_CAPABILITY');}
  requireThat(task.allowedTools.every(t=>['workspace.list','workspace.read','workspace.replace','workspace.patch','workspace.candidate_read','check.run','artifact.publish_local','research.read'].includes(t))&&task.effectAuthority?.kind==='local'&&!input.replannedFrom,'INTELLIGENCE_TASK_TOOL_SCOPE');
  if(!selected)store.transaction(()=>store.put('pilot-outcome-selection',b.id,{grantHash:hash(g),businessId:b.businessId,opportunityId:work.opportunityId,analysisAttemptId:work.analysisAttemptId},null));return {task,stage,work};
 };
 let engine:PortfolioEngine;
 const registerTask=async(taskId:string)=>{
  const existing=store.get('pilot-outcome-task-binding',bindingKey+taskId);if(existing){requireThat(existing.grantHash===hash(g)&&existing.definitionHash===taskDefinitionHash(x.portfolio.getTask(taskId)),'INTELLIGENCE_TASK_DEFINITION_CHANGED');if(existing.initialBodyHash)return existing;requireThat(x.portfolio.getTask(taskId).attempts===0,'INTELLIGENCE_PARTIAL_BINDING_ALREADY_USED');const preview=await engine.previewRequest(taskId),procedureHash=hash(preview.request.role.procedure);requireThat(procedureHash===b.procedures[existing.stage as 'campaign'|'page'|'correction'],'INTELLIGENCE_SELECTED_PROCEDURE_CHANGED');const value={...existing,initialBodyHash:bodyHash(g,preview.request,preview.schema).hash,procedureHash,initialRequest:preview.request};store.transaction(()=>store.put('pilot-outcome-task-binding',bindingKey+taskId,value,existing._version));return value;}
  checkNew();const {task,stage,work}=selectedWork(taskId);requireThat(task.resource.modelCalls===b.stageCaps[stage],'INTELLIGENCE_TASK_STAGE_CAP_MISMATCH');x.assertContextCurrent(taskId,true);requireThat(task.attempts===0&&!task.lease&&task.status==='queued','INTELLIGENCE_UNSTARTED_SELECTED_TASK');
  const used=models.ledger.rows().filter(r=>r.metadata.stage===stage).length,capacity=b.stageCaps[stage]-used;requireThat(capacity>=(stage==='page'?3:2),'INTELLIGENCE_STAGE_FINISHING_CAPACITY');
  store.transaction(()=>{const current=x.portfolio.getTask(taskId);store.put('portfolio-task',taskId,{...current,inputs:{...current.inputs as any,modelCallMaxMinor:205}},current._version);});
  // Freeze the concrete generated assignment before its first paid request.
  const provisional={id:taskId,workCalls:Math.min(capacity,task.resource.modelCalls),stage,grantHash:hash(g),definitionHash:taskDefinitionHash(x.portfolio.getTask(taskId)),inputArtifactsHash:hash(task.inputArtifacts),opportunityId:work.opportunityId,analysisAttemptId:work.analysisAttemptId,initialBodyHash:null as string|null,procedureHash:null as string|null};
  store.transaction(()=>store.put('pilot-outcome-task-binding',bindingKey+taskId,provisional,null));
  const prepared=await engine.previewRequest(taskId),procedureHash=hash(prepared.request.role.procedure);requireThat(procedureHash===b.procedures[stage as 'campaign'|'page'|'correction']&&hash(prepared.schema)===b.schemas.worker,'INTELLIGENCE_SELECTED_PROCEDURE_CHANGED');
  const old=store.get('pilot-outcome-task-binding',bindingKey+taskId),value={...old,initialBodyHash:bodyHash(g,prepared.request,prepared.schema).hash,procedureHash,initialRequest:prepared.request};store.transaction(()=>store.put('pilot-outcome-task-binding',bindingKey+taskId,value,old._version));return value;
 };
 const workerInvoke=async(call:WorkerCall,recover:boolean)=>{
  const binding=bindings().find(t=>workerScope(b.businessId,t.id).runId===call.request.scope.runId);requireThat(binding&&binding.initialBodyHash,'INTELLIGENCE_FROZEN_TASK_REQUIRED');
  const t=x.portfolio.getTask(binding.id);requireThat(call.ventureId===b.businessId&&hash(call.goal)===g.businesses[0].goalHash&&!call.recoveryOf&&!call.stageContract&&call.sourceHosts.length===0&&hash(call.schema)===b.schemas.worker&&hash(call.request.role.procedure)===binding.procedureHash,'INTELLIGENCE_WORKER_CALL_SCOPE');
  const persisted=rows(services,'portfolio-model-request').find(r=>r.call?.attemptId===call.attemptId);requireThat(persisted&&hash(persisted.call.request)===hash(call.request)&&hash(persisted.call.schema)===hash(call.schema),'INTELLIGENCE_WORKER_INTENT_REQUIRED');
  if(!recover){requireThat(binding.definitionHash===taskDefinitionHash(t)&&binding.inputArtifactsHash===hash(t.inputArtifacts),'INTELLIGENCE_TASK_DEFINITION_CHANGED');x.assertContextCurrent(t.id,true);selectedWork(t.id);if(call.attemptId===binding.initialRequest.requestId)requireThat(bodyHash(g,call.request,call.schema).hash===binding.initialBodyHash,'INTELLIGENCE_WORKER_INITIAL_BYTES_CHANGED');}
  const result=await invoke(binding.stage,call.request,call.schema,validateWorker,recover);return g.mode==='live'?result:{...result,route:{...result.route,kind:'fixture' as const,provider:'offline-responses-mock'}};
 };
 const worker:WorkerModel={kind:g.mode==='mock'?'offline_mock':'actual_model',run:call=>workerInvoke(call,false),recover:call=>models.ledger.get(call.attemptId)?workerInvoke(call,true):Promise.resolve(null)};
 const totals=()=>({...models.totals(),stageUsage:Object.fromEntries(Object.keys(b.stageCaps).map(stage=>[stage,{used:models.ledger.rows().filter(r=>r.metadata.stage===stage).length,limit:b.stageCaps[stage as Stage]}])),taskAllocations:bindings().map(t=>({id:t.id,workCalls:t.workCalls,definitionHash:t.definitionHash}))});
 engine=new PortfolioEngine({portfolio:x.portfolio,tools:x.tools,evidence:x.evidence,prepareTask:x.engine.prepareTask,model:worker,accounting:totals});
 return {models,authorization:g,investigationPort,analysisPort,engine,totals,
  async runInvestigation(){await services.discovery.recover(b.businessId);for(;;){const session=store.get('pilot-discovery',b.businessId);const unknown=rows(services,'pilot-discovery-record').filter(r=>r.companyId===b.businessId&&r.sessionId===b.discovery.id&&r.kind==='decision'&&r.status==='unknown').at(-1);if(session.state==='ready_for_analysis'||session.state==='paused'||session.state==='blocked'&&!unknown)return services.discovery.view(b.businessId);if(!unknown){checkNew();requireThat(models.ledger.rows().filter(r=>r.metadata.stage==='investigation').length<b.stageCaps.investigation,'INTELLIGENCE_INVESTIGATION_CAP_EXHAUSTED');}const attemptId=unknown?.id??services.discovery.request(b.businessId,undefined,{includeImages:b.discovery.includeImages}).request.requestId;await services.discovery.next(b.businessId,{port:investigationPort,attemptId,recoverSameResponse:investigationPort.recoverSameResponse,includeImages:b.discovery.includeImages,trustedFailureObservation:failureObservation});}},
  async runAnalysis(){const completed=models.ledger.rows().find(r=>r.metadata.stage==='analysis'&&store.get('pilot-commercial-attempt',b.businessId+'/'+r.id)?.status==='completed');if(completed)return services.intelligence.view(b.businessId);const old=rows(services,'pilot-commercial-attempt').filter(r=>r.businessId===b.businessId&&r.status!=='completed').at(-1);return old?services.intelligence.resume(b.businessId,analysisPort):services.intelligence.analyze(b.businessId,analysisPort,services.discovery.context(b.businessId));},
  async runTask(taskId:string){await engine.recover();let t=x.portfolio.getTask(taskId);if(t.status==='needs_reconciliation'){requireThat(store.get('pilot-outcome-task-binding',bindingKey+taskId),'INTELLIGENCE_RECOVERY_TASK_REQUIRED');await engine.resumeResponse(taskId);t=x.portfolio.getTask(taskId);}if(t.status==='completed'){requireThat(store.get('pilot-outcome-task-binding',bindingKey+taskId),'INTELLIGENCE_TASK_NOT_GRANTED');return t;}await registerTask(taskId);checkNew();x.assertContextCurrent(taskId,true);return engine.runTask(taskId,(t.inputs as any).assignedWorkerId??'pilot-generalist');}
 };
}

/** Signature/account reads remain useful after code, owner data or expiry changes.
 * Unavailable billing is not zero; this helper never opens an API credential. */
export function readIntelligenceAccounting(store:import('../state.ts').StateStore,root:string){
 const empty={status:'no_intelligence_grant',mode:null as string|null,currency:'USD',callsUsed:0,callLimit:0,countDispatches:0,inferenceDispatches:0,retrievalDispatches:0,countRequests:0,retrievals:0,providerRequests:0,provisionalMinor:0,unknownCostAttempts:0,settledMinor:null as number|null,retainedMinor:0,remainingMinor:0,countBufferMinor:0,accountIdentity:null as string|null,stageUsage:{} as Record<string,{used:number;limit:number}>};
 const unavailable=(reason:string)=>({...empty,status:'unavailable',reason,callsUsed:null,callLimit:null,countDispatches:null,inferenceDispatches:null,retrievalDispatches:null,countRequests:null,retrievals:null,providerRequests:null,provisionalMinor:null,unknownCostAttempts:null,retainedMinor:null,remainingMinor:null,countBufferMinor:null});
 if(!existsSync(join(root,AUTH))){const orphan=store.db.prepare("SELECT body FROM entities WHERE kind IN ('model-attempt','experiment-account')").all().some(r=>{const v=JSON.parse(String(r.body));return v.scope?.dataPolicyVersion==='selected-business-outcome-033-v1'||v.limits?.allocations?.some((a:any)=>a.metadataKey==='stage'&&a.value==='investigation');});return orphan?unavailable('Outcome accounting exists without its signed authorization; restore the matching grant.'):empty;}
 try{const g=verified(JSON.parse(readFileSync(join(root,AUTH),'utf8')),readFileSync(join(root,'auth','portfolio-owner.pub'),'utf8')) as IntelligenceGrant;
  requireThat(g.intelligence?.kind==='business-intelligence-outcome-033-v1'&&g.root===resolve(root)&&hash(g.accountScope)===hash(accountScope(g.intelligence.id)),'INTELLIGENCE_ACCOUNTING_SCOPE');const prefix=scopeKey(g.accountScope)+'/',account=store.get('experiment-account',scopeKey(g.accountScope));requireThat(!account||account.authorizationHash===hash(g)&&hash(account.limits)===hash(g.limits),'INTELLIGENCE_ACCOUNTING_BINDING');
  const attempts=store.db.prepare("SELECT body FROM entities WHERE kind='model-attempt' AND substr(key,1,?)=?").all(prefix.length,prefix).map(r=>JSON.parse(String(r.body))),reserved=attempts.reduce((sum,r)=>sum+r.reservation,0),invoices=attempts.filter(r=>r.invoice),settled=invoices.reduce((sum,r)=>sum+r.invoice.minorUnits,0),buffer=g.limits.overheadReserve?.minor??0,known=attempts.filter(r=>r.cost?.status==='provisional'),counts=attempts.filter(r=>r.countDispatchIntent).length,inferences=attempts.filter(r=>r.inferenceDispatchIntent).length,retrievals=attempts.reduce((sum,r)=>sum+(store.get('response-job',prefix+r.id)?.retrievals??0),0);
  return {...empty,status:'signed_ledger',mode:g.mode,callsUsed:attempts.length,callLimit:g.businesses[0].maxCalls,countDispatches:counts,inferenceDispatches:inferences,retrievalDispatches:retrievals,countRequests:g.mode==='live'?counts:0,retrievals:g.mode==='live'?retrievals:0,providerRequests:g.mode==='live'?counts+inferences+retrievals:0,provisionalMinor:attempts.length&&!known.length?null:known.reduce((sum,r)=>sum+r.cost.money.minorUnits,0),unknownCostAttempts:attempts.filter(r=>!r.invoice&&r.cost?.status!=='provisional').length,settledMinor:invoices.length?settled:null,retainedMinor:reserved+buffer,remainingMinor:g.limits.totalMinor-reserved-settled-buffer,countBufferMinor:buffer,accountIdentity:hash({root:resolve(root),scope:g.accountScope,grantHash:hash(g)}),stageUsage:Object.fromEntries(Object.entries(g.intelligence.stageCaps).map(([stage,limit])=>[stage,{used:attempts.filter(r=>r.metadata.stage===stage).length,limit}]))};
 }catch(error){return unavailable((error as Error).message);}
}

/** Owner status reads only public signing metadata and persisted state. No key,
 * transport, admission, procedure creation or account mutation is performed. */
export function readIntelligenceAuthority(services:Services,root:string){
 const none={approved:false,current:false,liveEnabled:false,mode:null as string|null,businessId:null as string|null,expiresAt:null as string|null,reason:'No signed outcome authorization is installed.',sameIdRecoveryAvailable:false,credentialRead:false,providerRequests:0};
 if(!existsSync(join(root,AUTH)))return none;
 let g:IntelligenceGrant|null=null;
 try{g=verified(JSON.parse(readFileSync(join(root,AUTH),'utf8')),readFileSync(join(root,'auth','portfolio-owner.pub'),'utf8')) as IntelligenceGrant;const b=validate(services,root,g,true),accounting=readIntelligenceAccounting(services.intelligence.store,root);requireThat(accounting.status==='signed_ledger','INTELLIGENCE_ACCOUNTING_UNAVAILABLE');
  const sameIdRecoveryAvailable=rows(services,'response-job').some(j=>j.grantHash===hash(g)&&j.responseId&&!j.terminal),base={...none,approved:true,mode:g.mode,businessId:b.businessId,expiresAt:g.expiresAt,sameIdRecoveryAvailable,remainingMinor:accounting.remainingMinor,callsUsed:accounting.callsUsed,callLimit:accounting.callLimit,stageUsage:accounting.stageUsage};
  requireThat(Date.parse(g.expiresAt)>Date.now()&&!services.intelligence.store.get('operating-revocation',hash(g)),'INTELLIGENCE_EXPIRED_OR_REVOKED');
  try{currentContext(services,g);}catch(error){return {...base,reason:(error as Error).message};}
  const hasCapacity=(accounting.callsUsed??g.businesses[0].maxCalls)<g.businesses[0].maxCalls&&(accounting.remainingMinor??0)>=205,credentialConfigured=typeof g.credentialFile==='string'&&isAbsolute(g.credentialFile)&&existsSync(g.credentialFile);return {...base,current:true,liveEnabled:g.mode==='live'&&credentialConfigured&&(hasCapacity||sameIdRecoveryAvailable),reason:g.mode==='mock'?'Test-only mock authorization; no live transport is enabled.':!credentialConfigured?'The exact approved protected credential file is unavailable; no key was read.':!hasCapacity&&!sameIdRecoveryAvailable?'No inference capacity or pending same-ID recovery remains under this grant.':'Signed bounded outcome authority is current; each stage still enforces its own remaining calls and owner-selection requirements.'};
 }catch(error){return {...none,...(g?{approved:true,mode:g.mode,businessId:g.intelligence?.businessId??null,expiresAt:g.expiresAt}:{}),reason:(error as Error).message};}
}
