/** Owner-pilot evidence memory. Local storage and proposal validation only; never opens a provider connection. */
import { randomUUID } from 'node:crypto';
import { StateStore } from '../state.ts';
import { hash, identifier, requireThat, scopeKey } from '../contracts.ts';
import type { ModelPort, Scope } from '../contracts.ts';
import { buildEvidenceRequest, evidenceAudit, fixtureEvidencePort, prospectiveEvidenceRequest, runEvidenceProposal, validateEvidenceBundle, validateUnderstanding } from '../workbench/evidence.ts';
import type { EvidenceBundle, UnderstandingProposal } from '../workbench/evidence.ts';
import type { ResponsesRoute } from '../model-port.ts';

export type PilotMode = 'owner' | 'fixture';
export type PilotCompany = { id: string; name: string; website: string; goal: string; notes: string; mode: PilotMode; version: number; createdAt: string; updatedAt: string; _version: number };
export type SourceInput = { title: string; text: string; kind: 'notes' | 'text' | 'markdown' | 'csv' | 'json' | 'website'; rights: string; observedAt: string; validUntil?: string | null; permission?: 'worker' | 'excluded' };
export type PilotSource = SourceInput & { id: string; businessId: string; version: number; permission: 'worker' | 'excluded'; originalPermission?: 'worker' | 'excluded'; selected?: boolean; validUntil: string | null; sha256: string; bytes: number; createdAt: string; provenance: string; parsed: { format: string; rows?: number; columns?: number } };
export type CorrectionInput = { taskId: string; artifactHash: string; instruction: string; assisted: boolean; reviewSessionId?: string; id?: string };
export type OutcomeInput = { taskId: string; artifactHash: string; kind: 'accepted' | 'needs-change' | 'not-useful'; notes: string; assisted: boolean; id?: string };
const dimensions = ['offer', 'customers', 'positioning', 'goals', 'processes', 'constraints', 'pricing', 'policy', 'tools', 'permissions', 'outcomes'];
const now = () => new Date().toISOString();
const uid = (prefix: string) => prefix + '-' + randomUUID().replaceAll('-', '').slice(0, 20);
const text = (x: unknown, max = 12000) => requireThat(typeof x === 'string' && x.trim().length > 0 && x.length <= max, 'PILOT_TEXT_REQUIRED');
const timestamp = (x: string) => requireThat(typeof x === 'string' && /^\d{4}-\d{2}-\d{2}T.+(?:Z|[+-]\d{2}:\d{2})$/.test(x) && Number.isFinite(Date.parse(x)), 'PILOT_TIMESTAMP_REQUIRED');
export const pilotKnowledgeScope = (businessId: string): Scope => ({ tenantId: 'mason', businessId, runId: 'owner-pilot-032', dataPolicyVersion: 'owner-permitted-evidence-v1', mode: 'fixture' });
/** Scope.mode is the existing local-store namespace, not a claim that owner records are synthetic. */
function website(value: string) { requireThat(typeof value === 'string' && value.length <= 2048, 'PILOT_WEBSITE_INVALID'); if (!value) return ''; let parsed: URL; try { parsed = new URL(value); } catch { throw new Error('PILOT_WEBSITE_INVALID'); } requireThat(['http:', 'https:'].includes(parsed.protocol) && !parsed.username && !parsed.password, 'PILOT_WEBSITE_INVALID'); return parsed.toString(); }
function validateJson(value: unknown, depth = 0): void { requireThat(depth <= 20, 'PILOT_JSON_DEPTH'); if (typeof value === 'number') requireThat(Number.isFinite(value), 'PILOT_JSON_NUMBER'); if (value && typeof value === 'object') { requireThat(Object.keys(value).length <= 10000, 'PILOT_JSON_BOUNDS'); Object.values(value).forEach(v => validateJson(v, depth + 1)); } }
/** CSV is data, never spreadsheet execution. Count rows while respecting escaped quoted cells. */
export function inspectCsv(input: string) {
    let quoted = false, fieldStart = true, afterQuote = false, columns = 1, expected: number | null = null, rows = 0;
    const row = () => { if (expected === null) expected = columns; requireThat(columns === expected, 'PILOT_CSV_COLUMN_MISMATCH'); rows++; columns = 1; fieldStart = true; afterQuote = false; };
    for (let i = 0; i < input.length; i++) { const c = input[i]; if (quoted) { if (c === '"') { if (input[i + 1] === '"') i++; else { quoted = false; afterQuote = true; } } continue; } if (c === '"') { requireThat(fieldStart && !afterQuote, 'PILOT_CSV_QUOTES'); quoted = true; fieldStart = false; } else if (c === ',') { columns++; fieldStart = true; afterQuote = false; } else if (c === '\n' || c === '\r') { if (c === '\r' && input[i + 1] === '\n') i++; row(); } else { requireThat(!afterQuote, 'PILOT_CSV_AFTER_QUOTE'); fieldStart = false; } }
    requireThat(!quoted, 'PILOT_CSV_UNCLOSED_QUOTE'); if (!/[\r\n]$/.test(input)) row(); requireThat(rows >= 1, 'PILOT_CSV_EMPTY'); return { format: 'csv', rows: Math.max(0, rows - 1), columns: expected ?? columns };
}

export const pilotDemo = {
    name: 'Harbor Workshop — test company', website: '', goal: 'Help furniture-restoration inquiries reach an informed next step without unsupported prices or booking promises.',
    notes: 'This is a development fixture, not Mason’s stepmom’s business. Harbor Workshop restores household furniture. No customer data or measured demand is represented.',
    sources: [
        { title: 'Test company service and intake policy', kind: 'text' as const, text: 'Harbor Workshop is a synthetic furniture-restoration service. Customers may request a review of worn household furniture. An initial inquiry must include the item type, visible damage, dimensions, and the customer’s preferred way to be contacted. Photographs help a later human inspection, but this local prototype does not accept uploads. A human must inspect the item before confirming feasibility, price, or a booking. Never guarantee a price, completion date, or availability. Prepare an inquiry summary for the owner; do not send a message or create a booking. The owner reviews inquiry drafts before they are used.', rights: 'Synthetic development data authored for this pilot; no customer or third-party content.' },
        { title: 'Test owner workflow observation', kind: 'notes' as const, text: 'The synthetic owner reports that initial restoration inquiries often omit item dimensions and visible damage. The owner repeatedly requests these facts before considering an inspection. The frequency and economic cost have not been measured. The current website only describes restoration and does not help a visitor assemble an inquiry. It is unknown whether a guided local inquiry form improves useful inquiries or creates extra effort.', rights: 'Synthetic development data authored for this pilot; no customer or third-party content.' }
    ]
};

export class PilotKnowledge {
    readonly store: StateStore;
    constructor(store: StateStore) { this.store = store; }
    private rows(kind: string) { return this.store.db.prepare('SELECT body,version FROM entities WHERE kind=? ORDER BY rowid').all(kind).map(r => ({ ...JSON.parse(String(r.body)), _version: Number(r.version) })); }
    company(id: string): PilotCompany { identifier(id); const result = this.store.get('pilot-company', id); requireThat(result, 'PILOT_COMPANY_NOT_FOUND'); return result; }
    listCompanies(): PilotCompany[] { return this.rows('pilot-company'); }
    private originalSources(id: string): PilotSource[] { this.company(id); return this.rows('pilot-source').filter(s => s.businessId === id); }
    /** Effective worker permission reflects the owner's current selection. Original bytes,
     * rights and permission remain in immutable source records and originalPermission. */
    sources(id: string): PilotSource[] { const selection = this.store.get('pilot-evidence-selection', id); return this.originalSources(id).map(source => { const selected = source.permission === 'worker' && (!selection || selection.sourceIds.includes(source.id)); return { ...source, originalPermission: source.permission, selected, permission: selected ? 'worker' : 'excluded' }; }); }
    selectedSources(id: string): PilotSource[] { return this.sources(id).filter(s => s.selected); }
    selectEvidence(id: string, sourceIds: string[]) {
        this.company(id); requireThat(Array.isArray(sourceIds) && sourceIds.length <= 32 && sourceIds.every(x => typeof x === 'string'), 'PILOT_EVIDENCE_SELECTION_INVALID'); requireThat(new Set(sourceIds).size === sourceIds.length, 'PILOT_EVIDENCE_SELECTION_DUPLICATE');
        const originals = this.originalSources(id); for (const sourceId of sourceIds) { const source = originals.find(s => s.id === sourceId); requireThat(source, 'PILOT_EVIDENCE_SELECTION_SCOPE'); requireThat(source.permission === 'worker', 'PILOT_EXCLUDED_SOURCE_PERMISSION'); }
        const selectedIds = [...sourceIds].sort();
        return this.store.transaction(() => { const prior = this.store.get('pilot-evidence-selection', id); if (prior && hash(prior.sourceIds) === hash(selectedIds)) return prior;
            const value = { businessId: id, sourceIds: selectedIds, revision: (prior?.revision ?? 0) + 1, createdAt: now(), provenance: 'owner-selected worker evidence; original source bytes and permissions remain preserved', sourceBindings: selectedIds.map(sourceId => { const source = originals.find(s => s.id === sourceId)!; return { id: source.id, sha256: source.sha256, version: source.version }; }) };
            this.store.record(pilotKnowledgeScope(id), 'evidence-selection-v' + value.revision, 'PilotEvidenceSelection', value); const saved = this.store.put('pilot-evidence-selection', id, value, prior?._version ?? null); this.revise(this.company(id), {}, 'Owner changed the bounded evidence selected for future work'); return saved;
        });
    }
    corrections(id: string) { this.company(id); return this.rows('pilot-correction').filter(s => s.businessId === id); }
    outcomes(id: string) { this.company(id); return this.rows('pilot-outcome').filter(s => s.businessId === id); }
    private revise(c: PilotCompany, changes: any, reason: string) { const value = { ...c, ...changes, version: c.version + 1, updatedAt: now() }; this.store.record(pilotKnowledgeScope(c.id), 'company-v' + value.version, 'PilotCompanyRevision', { company: value, reason }); return this.store.put('pilot-company', c.id, value, c._version); }
    createCompany(input: { name: string; website?: string; goal: string; notes?: string; mode?: PilotMode; id?: string }): PilotCompany {
        text(input.name, 160); text(input.goal, 4000); requireThat(typeof (input.notes ?? '') === 'string' && (input.notes ?? '').length <= 12000, 'PILOT_NOTES_BOUNDS'); requireThat(!input.mode || ['owner', 'fixture'].includes(input.mode), 'PILOT_MODE');
        const id = input.id ?? uid('company'); identifier(id); const createdAt = now(); const value = { id, name: input.name.trim(), website: website(input.website ?? ''), goal: input.goal.trim(), notes: input.notes ?? '', mode: input.mode ?? 'owner', version: 1, createdAt, updatedAt: createdAt };
        const company = this.store.transaction(() => { requireThat(!this.store.get('pilot-company', id), 'PILOT_COMPANY_EXISTS'); this.store.record(pilotKnowledgeScope(id), 'company-v1', 'PilotCompanyRevision', { company: value, reason: 'Owner onboarding; company facts remain owner reported and incomplete' }); return this.store.put('pilot-company', id, value, null); });
        this.addSource(id, { title: 'Owner onboarding statement', text: ['Company: ' + value.name, 'Goal: ' + value.goal, value.notes].filter(Boolean).join('\n'), kind: 'notes', rights: 'Owner supplied for this business workspace; no independent verification', observedAt: createdAt }); return this.company(company.id);
    }
    updateCompany(id: string, patch: Partial<Pick<PilotCompany, 'name' | 'website' | 'goal' | 'notes'>>, expectedVersion?: number) {
        const c = this.company(id); if (expectedVersion !== undefined) requireThat(c.version === expectedVersion, 'PILOT_COMPANY_STALE'); requireThat(Object.keys(patch).every(k => ['name', 'website', 'goal', 'notes'].includes(k)), 'PILOT_COMPANY_FIELD');
        if (patch.name !== undefined) text(patch.name, 160); if (patch.goal !== undefined) text(patch.goal, 4000); if (patch.notes !== undefined) requireThat(typeof patch.notes === 'string' && patch.notes.length <= 12000, 'PILOT_NOTES_BOUNDS'); if (patch.website !== undefined) patch = { ...patch, website: website(patch.website) };
        this.store.transaction(() => this.revise(c, patch, 'Owner edited company context; previous interpretations need source-freshness review'));
        this.addSource(id, { title: 'Owner context correction v' + (c.version + 1), kind: 'notes', text: JSON.stringify(patch), rights: 'Owner correction; reported interpretation, not independent validation', observedAt: now() }); return this.company(id);
    }
    addSource(id: string, input: SourceInput): PilotSource {
        this.company(id); text(input.title, 240); text(input.text, 200000); text(input.rights, 1000); timestamp(input.observedAt); requireThat(Buffer.byteLength(input.text, 'utf8') <= 200000, 'PILOT_SOURCE_BYTE_LIMIT'); requireThat(['notes', 'text', 'markdown', 'csv', 'json', 'website'].includes(input.kind), 'PILOT_SOURCE_KIND');
        const validUntil = input.validUntil ?? null; if (validUntil !== null) timestamp(validUntil); const permission = input.permission ?? 'worker'; requireThat(['worker', 'excluded'].includes(permission), 'PILOT_SOURCE_PERMISSION');
        let parsed: PilotSource['parsed'] = { format: input.kind }; if (input.kind === 'json') { let value; try { value = JSON.parse(input.text); } catch { throw new Error('PILOT_JSON_INVALID'); } requireThat(value !== null && typeof value === 'object', 'PILOT_JSON_STRUCTURE'); validateJson(value); parsed = { format: 'json', ...(Array.isArray(value) ? { rows: value.length } : {}) }; } if (input.kind === 'csv') parsed = inspectCsv(input.text);
        const source: PilotSource = { ...input, id: uid('source'), businessId: id, version: 1, permission, validUntil, sha256: hash(input.text), bytes: Buffer.byteLength(input.text, 'utf8'), createdAt: now(), provenance: this.company(id).mode === 'fixture' ? 'development-authored synthetic fixture' : 'owner-supplied content; publisher and accuracy not independently verified', parsed };
        return this.store.transaction(() => { const c = this.company(id); this.store.record(pilotKnowledgeScope(id), source.id, 'PilotEvidenceSource', source); const saved = this.store.put('pilot-source', source.id, source, null); this.revise(c, {}, 'Evidence added: ' + source.title); return saved; });
    }
    bundle(id: string): EvidenceBundle {
        const c = this.company(id), sources = this.selectedSources(id); const bundle: EvidenceBundle = { version: 'pilot-evidence-v' + c.version, asOf: c.updatedAt, purpose: c.goal, currency: 'USD', valueBasis: 'unmeasured owner effort and accepted useful work per pilot assignment', dimensions, allowedTools: ['owner.evidence_request', 'workspace.read', 'workspace.patch', 'check.run', 'artifact.publish_local'], allowedEffects: [], sources: sources.map(s => ({ id: s.id, version: 'source-v' + s.version, text: s.text, observedAt: s.observedAt, validUntil: s.validUntil, permission: s.permission, rights: s.rights })) }; validateEvidenceBundle(bundle); return bundle;
    }
    prepareDiagnosis(id: string) { const c = this.company(id), bundle = this.bundle(id), attemptId = 'understanding-' + c.version + '-' + hash(bundle.sources).slice(0, 12); const request = buildEvidenceRequest(pilotKnowledgeScope(id), bundle, attemptId); return { businessId: id, companyVersion: c.version, bundle, request, requestHash: hash(request), state: 'prepared_only', providerCalls: 0, requiredAuthority: 'A new exact model route, data scope, token/count limits and aggregate budget grant; historical R5 is not usable for pilot inference.' }; }
    prepareLiveDiagnosis(id: string, route: ResponsesRoute) { const prepared = this.prepareDiagnosis(id); return { businessId: id, companyVersion: prepared.companyVersion, ...prospectiveEvidenceRequest(pilotKnowledgeScope(id), prepared.bundle, prepared.request.requestId, route), transportCalled: false }; }
    async diagnose(id: string, options: { port?: ModelPort; attemptId?: string } = {}) {
        const c = this.company(id); requireThat(!options.port || options.port.kind === 'fixture', 'PILOT_LIVE_AUTHORIZATION_REQUIRED'); requireThat(!options.port || c.mode === 'fixture', 'PILOT_FIXTURE_BUSINESS_REQUIRED');
        if (c.mode === 'owner') { let prepared: any; try { prepared = this.prepareDiagnosis(id); } catch (error) { prepared = { state: 'evidence_needs_bounded_selection', reason: (error as Error).message, providerCalls: 0 }; } const inventory = { businessId: id, companyVersion: c.version, status: prepared.state === 'prepared_only' ? 'needs_model_authorization' : 'needs_evidence_selection', provenance: 'deterministic source inventory; no model diagnosis executed', claims: [], hypotheses: [], contradictions: [], unknowns: this.inventoryUnknowns(id), nextAction: prepared.state === 'prepared_only' ? 'Review the company evidence and authorize a bounded model diagnosis when ready.' : 'Supply a decision-relevant excerpt or smaller source bundle; complete sources remain preserved.', prepared, createdAt: now() }; this.persistUnderstanding(id, inventory); return this.snapshot(id).understanding; }
        const bundle = this.bundle(id); const attemptId = options.attemptId ?? 'diagnosis-v' + c.version; const port = options.port ?? fixtureEvidencePort(this.fixtureProposal(id, bundle));
        const proposal = await runEvidenceProposal(this.store, { id: 'pilot-fixture-controller', tenantId: 'mason', businessId: id, permissions: ['read', 'operate'] }, pilotKnowledgeScope(id), bundle, port, attemptId);
        const output = proposal.output as UnderstandingProposal; const record = { businessId: id, companyVersion: c.version, status: 'proposal_ready', ...output, hypotheses: output.hypotheses.map((h, index) => ({ ...h, rank: index + 1, rankBasis: index === 0 ? 'Directly linked to the stated owner goal and a supported local workflow; economic benefit remains unmeasured.' : 'Alternative supported workflow; compare owner correction and usefulness before expansion.', workflow: index === 0 ? 'response-packet' : 'business-site' })), provenance: 'offline fixture through ModelPort; development-authored proposal, not measured AI competence', nextAction: 'Review the inquiry-response work proposal; use the local website workflow as a second test when useful.', proposalRef: proposal.attemptId, sourceAudit: evidenceAudit(bundle), createdAt: now() }; this.persistUnderstanding(id, record); return this.snapshot(id).understanding;
    }
    /** Called by the signed diagnosis factory only after OperatingModels has retained
     * the response. This records a proposal, never owner acceptance or causal truth. */
    acceptAuthorizedDiagnosis(id: string, binding: { companyHash: string; bundleHash: string; accountScope: Scope; grantHash: string; attemptId: string; requestHash: string }) {
        const company = this.company(id), bundle = this.bundle(id), key = scopeKey(binding.accountScope) + '/' + binding.attemptId;
        requireThat(hash(company) === binding.companyHash && hash(bundle) === binding.bundleHash, 'PILOT_DIAGNOSIS_CONTEXT_CHANGED');
        const account = this.store.get('experiment-account', scopeKey(binding.accountScope)), attempt = this.store.get('model-attempt', key), saved = this.store.get('operating-response', key);
        requireThat(account?.authorizationHash === binding.grantHash && attempt?.metadata?.businessId === id && attempt.metadata.stage === 'pilot-diagnosis' && attempt.requestHash === binding.requestHash && saved?.requestHash === binding.requestHash && !attempt.errorCode && attempt.finishedAt, 'PILOT_DIAGNOSIS_VALIDATED_RECORD_REQUIRED');
        requireThat(['offline_mock', 'actual-model'].includes(saved.provenance) && saved.provenance === attempt.metadata.source, 'PILOT_DIAGNOSIS_PROVENANCE_REQUIRED');
        const output = saved.result.output; validateUnderstanding(bundle, output);
        const resultKey = binding.grantHash + '/' + binding.attemptId, prior = this.store.get('pilot-authorized-understanding', resultKey);
        if (prior) { requireThat(prior.businessId === id && prior.outputHash === hash(output), 'PILOT_DIAGNOSIS_RESULT_CHANGED'); return prior; }
        const workflowFor = (hId: string) => { const tasks = output.tasks.filter(t => t.hypothesisId === hId); if (!tasks.length) return null;
            const competencies = new Set(tasks.flatMap(t => t.competencies));
            if (['frontend_implementation', 'input_validation', 'browser_verification'].every(c => competencies.has(c))) return 'business-site';
            if (['evidence_synthesis', 'customer_response', 'policy_review'].every(c => competencies.has(c))) return 'response-packet'; return null; };
        const value = { businessId: id, companyVersion: company.version, status: 'proposal_ready', ...output,
            hypotheses: output.hypotheses.map((h, index) => ({ ...h, rank: h.id === output.selectedHypothesisId ? 1 : index + 2, rankBasis: h.id === output.selectedHypothesisId ? output.selectionReason : 'Model-proposed alternative; comparative priority is not established.', workflow: workflowFor(h.id) })),
            provenance: saved.provenance === 'actual-model' ? 'actual-model sourced proposal through signed OperatingModels; accuracy and causal benefit not independently established' : 'offline mock through signed diagnosis binding; no measured AI competence',
            proposalRef: binding.attemptId, grantHash: binding.grantHash, requestHash: binding.requestHash, outputHash: hash(output), sourceAudit: evidenceAudit(bundle),
            recordedRoute: saved.result.route, recordedUsage: saved.result.usage, recordedMetadata: saved.result.metadata ?? null,
            acceptedByOwner: false, sourceAccuracy: 'unverified', causalConfidence: 'unvalidated hypothesis',
            nextAction: output.selectedHypothesisId ? 'Review the proposed bottleneck and supported task fit. Selecting an outcome and authorizing work remain separate owner decisions.' : 'Review the stated blocking information and permitted evidence requests before choosing work.', createdAt: now() };
        this.store.transaction(() => { this.store.record(pilotKnowledgeScope(id), 'authorized-diagnosis-' + hash(resultKey).slice(0, 24), 'PilotAuthorizedDiagnosisProposal', value); this.store.put('pilot-authorized-understanding', resultKey, value, null);
            const old = this.store.get('pilot-understanding', id), revision = (old?._version ?? 0) + 1; this.store.record(pilotKnowledgeScope(id), 'understanding-v' + revision, 'PilotUnderstandingProposal', value); this.store.put('pilot-understanding', id, value, old?._version ?? null); });
        return this.store.get('pilot-authorized-understanding', resultKey);
    }
    private persistUnderstanding(id: string, value: any) { this.store.transaction(() => { const old = this.store.get('pilot-understanding', id); const revision = (old?._version ?? 0) + 1; this.store.record(pilotKnowledgeScope(id), 'understanding-v' + revision, 'PilotUnderstandingProposal', value); this.store.put('pilot-understanding', id, value, old?._version ?? null); }); }
    private inventoryUnknowns(id: string) { const c = this.company(id); return [{ question: 'Which customer problem and operating bottleneck most affects this goal?', consequence: 'Needed to rank useful work; documents alone do not establish causation.', claimIds: [] }, { question: 'Which prices, policies, approvals and tools apply to the first task?', consequence: 'Missing authority or policy blocks external effects and unsupported promises.', claimIds: [] }, { question: 'How will the owner judge usefulness and measure correction effort?', consequence: 'Required to learn from the deliverable without equating completion with business benefit.', claimIds: [] }, ...(c.website ? [{ question: 'Has permitted website content been supplied?', consequence: 'The saved URL is a pointer only; MIDAS has not fetched it.', claimIds: [] }] : [])]; }
    snapshot(id: string) {
        const business = this.company(id), sources = this.sources(id), current = this.store.get('pilot-understanding', id), outcomes = this.outcomes(id), corrections = this.corrections(id), latestOutcome = outcomes.at(-1), latestCorrection = corrections.at(-1);
        const base = current ?? { status: 'needs_evidence', claims: [], hypotheses: [], contradictions: [], unknowns: this.inventoryUnknowns(id), nextAction: 'Add company notes or documents, then inspect the evidence inventory.', provenance: 'No diagnosis has run.' };
        const newerCorrection = latestCorrection && (!latestOutcome || latestCorrection.createdAt > latestOutcome.createdAt);
        const nextAction = newerCorrection ? 'Verify the corrected deliverable against the owner request before further use.' : latestOutcome?.kind === 'accepted' ? 'Use the accepted local deliverable in an owner-controlled test; record a real observation before claiming business benefit.' : latestOutcome?.kind === 'not-useful' ? 'Revisit the selected bottleneck: the owner found the artifact not useful. Do not repeat the same assignment without a changed reason.' : latestOutcome?.kind === 'needs-change' ? 'Correct the authoritative artifact using the recorded owner feedback, then recheck and review it.' : base.nextAction;
        return { business, sources, evidenceSelection: this.store.get('pilot-evidence-selection', id) ?? { businessId: id, sourceIds: sources.filter(s => s.selected).map(s => s.id), revision: 0, provenance: 'Default includes permitted owner uploads; explicit selection may narrow future worker access.' }, understanding: { ...base, completeness: 'partial', currentCompanyVersion: business.version, evidenceChangedSinceProposal: current ? current.companyVersion !== business.version : false, nextAction, adaptationProvenance: latestOutcome || latestCorrection ? 'Rule-based response to owner-reported evidence; causal improvement unestablished.' : null }, outcomes, corrections, history: this.store.records({ id: 'owner-workbench', tenantId: 'mason', businessId: id, permissions: ['read'] }, pilotKnowledgeScope(id)).map(r => ({ id: r.id, kind: r.kind, at: r.createdAt, sha256: r.sha256 })) };
    }
    correction(id: string, input: CorrectionInput) { this.company(id); text(input.taskId, 500); requireThat(/^[a-f0-9]{64}$/.test(input.artifactHash), 'PILOT_ARTIFACT_HASH'); text(input.instruction, 4000); requireThat(typeof input.assisted === 'boolean', 'PILOT_ASSISTANCE_REQUIRED'); const key = input.id ?? uid('correction'); identifier(key); const value = { ...input, id: key, businessId: id, createdAt: now(), provenance: this.company(id).mode === 'fixture' ? 'owner correction of synthetic fixture output' : 'owner-reported correction; not independent semantic validation', independentHumanSeconds: null, status: 'recorded; authoritative artifact correction must be checked by execution controller' }; return this.store.transaction(() => { const old = this.store.get('pilot-correction', key); if (old) { requireThat(old.businessId === id && old.taskId === input.taskId && old.artifactHash === input.artifactHash && old.instruction === input.instruction && old.assisted === input.assisted, 'PILOT_CORRECTION_ID_CONFLICT'); return old; } this.store.record(pilotKnowledgeScope(id), key, 'PilotOwnerCorrection', value); const saved = this.store.put('pilot-correction', key, value, null); this.revise(this.company(id), {}, 'Owner correction changes the evidence for the next assignment'); return saved; }); }
    outcome(id: string, input: OutcomeInput) { this.company(id); text(input.taskId, 500); requireThat(/^[a-f0-9]{64}$/.test(input.artifactHash), 'PILOT_ARTIFACT_HASH'); requireThat(['accepted', 'needs-change', 'not-useful'].includes(input.kind), 'PILOT_OUTCOME_KIND'); text(input.notes, 4000); requireThat(typeof input.assisted === 'boolean', 'PILOT_ASSISTANCE_REQUIRED'); const key = input.id ?? uid('outcome'); identifier(key); const value = { ...input, id: key, businessId: id, createdAt: now(), provenance: 'owner-reported artifact outcome; not measured demand or revenue', measuredRevenueMinor: null, independentHumanSeconds: null }; return this.store.transaction(() => { const old = this.store.get('pilot-outcome', key); if (old) { requireThat(old.businessId === id && old.taskId === input.taskId && old.artifactHash === input.artifactHash && old.kind === input.kind && old.notes === input.notes && old.assisted === input.assisted, 'PILOT_OUTCOME_ID_CONFLICT'); return old; } this.store.record(pilotKnowledgeScope(id), key, 'PilotOwnerOutcome', value); const saved = this.store.put('pilot-outcome', key, value, null); this.revise(this.company(id), {}, 'Recorded outcome revises the recommended next action'); return saved; }); }
    createDemo() { const c = this.createCompany({ ...pilotDemo, mode: 'fixture' }); for (const s of pilotDemo.sources) this.addSource(c.id, { ...s, observedAt: now() }); return this.company(c.id); }
    private fixtureProposal(id: string, bundle: EvidenceBundle): UnderstandingProposal {
        const sources = this.sources(id), policy = sources.find(s => s.title === pilotDemo.sources[0].title), observation = sources.find(s => s.title === pilotDemo.sources[1].title); requireThat(policy && observation, 'PILOT_FIXTURE_DATA_REQUIRED');
        const claims: UnderstandingProposal['claims'] = [{ id: 'intake-gap', kind: 'observation', dimension: 'processes', statement: 'The test owner reports missing dimensions and damage details in inquiries; this is not a measured frequency.', references: [{ sourceId: observation.id, quote: 'The synthetic owner reports that initial restoration inquiries often omit item dimensions and visible damage.' }] }, { id: 'inspection-policy', kind: 'observation', dimension: 'policy', statement: 'A human inspection is required before feasibility, price, or booking commitments.', references: [{ sourceId: policy.id, quote: 'A human must inspect the item before confirming feasibility, price, or a booking.' }] }, { id: 'site-gap', kind: 'observation', dimension: 'tools', statement: 'The test record describes a website without guided inquiry preparation.', references: [{ sourceId: observation.id, quote: 'The current website only describes restoration and does not help a visitor assemble an inquiry.' }] }];
        return { kind: 'business-understanding-proposal', completeness: 'partial', claims, contradictions: [], unknowns: [{ question: 'Would structured inquiry guidance save owner correction effort?', consequence: 'The fixture cannot establish actual efficiency or willingness to use it.', claimIds: ['intake-gap'] }], evidenceRequests: [{ id: 'request-owner-timing', tool: 'owner.evidence_request', query: 'Observe one consenting operator preparing and reviewing an inquiry with the existing process.', decisionUse: 'Compare missing information and measured owner effort before changing operations.', claimIds: ['intake-gap'] }], hypotheses: [{ id: 'response-opportunity', diagnosis: 'A reusable inquiry-response packet may reduce repeated requests for essential facts.', claimIds: ['intake-gap', 'inspection-policy'], alternativeExplanation: 'Inquiries may be rare or a short owner conversation may be sufficient.', uncertainty: 'Test hypothesis only; no effect frequency or economic benefit measured.', estimatedBenefit: null, estimatedCost: null, valueBasis: bundle.valueBasis }, { id: 'site-opportunity', diagnosis: 'A guided local inquiry website may help visitors assemble the facts needed for inspection.', claimIds: ['site-gap', 'inspection-policy'], alternativeExplanation: 'A plain checklist may provide the same benefit with less maintenance.', uncertainty: 'No customer usability or acquisition evidence exists.', estimatedBenefit: null, estimatedCost: null, valueBasis: bundle.valueBasis }], selectedHypothesisId: 'response-opportunity', selectionReason: 'Start with the smaller reversible deliverable tied to the reported missing facts; retain the website as a separately inspectable implementation test.', tasks: [{ id: 'prepare-inquiry-response', hypothesisId: 'response-opportunity', description: 'Prepare a source-grounded inquiry response, missing-information checklist and owner review notes.', dependsOn: [], competencies: ['evidence_synthesis', 'customer_response', 'policy_review'], tools: ['workspace.read', 'workspace.patch', 'check.run', 'artifact.publish_local'], effect: null, acceptance: ['Requests item type, dimensions and damage information', 'No unsupported price, completion-date or booking promise', 'Owner can inspect and correct the authoritative local deliverable'] }] };
    }
}

