/** A correction-to-comparison bridge. Fixture comparisons exercise governance, never qualify a worker. */
import { StateStore } from '../state.ts';
import { hash, requireThat } from '../contracts.ts';
import { Portfolio } from '../portfolio/core.ts';
import { ProcedureRegistry } from '../portfolio/learning.ts';
import { FINALIZING_WORKER_PROCEDURE } from '../portfolio/worker.ts';
import { PilotKnowledge, pilotKnowledgeScope } from './knowledge.ts';

export type PilotWorkflow = 'response-packet' | 'business-site';
const workflowDetails = (workflow: PilotWorkflow) => {
    requireThat(workflow === 'response-packet' || workflow === 'business-site', 'PILOT_WORKFLOW_UNSUPPORTED');
    return workflow === 'response-packet' ? { capability: 'service.brief', job: 'Source-grounded inquiry response and owner review packet', tools: ['workspace.read', 'workspace.patch', 'check.run', 'artifact.publish_local'], competencies: ['evidence_synthesis', 'customer_response', 'policy_review'] } : { capability: 'software.build', job: 'Contained business information and local inquiry workflow', tools: ['workspace.read', 'workspace.patch', 'check.run', 'artifact.publish_local'], competencies: ['frontend_implementation', 'input_validation', 'browser_verification'] };
};

export class PilotLearning {
    readonly store: StateStore;
    readonly knowledge: PilotKnowledge;
    readonly registry: ProcedureRegistry;
    constructor(store: StateStore) { this.store = store; this.knowledge = new PilotKnowledge(store); this.registry = new ProcedureRegistry(store); }
    private rows(kind: string) { return this.store.db.prepare('SELECT body,version FROM entities WHERE kind=? ORDER BY rowid').all(kind).map(r => ({ ...JSON.parse(String(r.body)), _version: Number(r.version) })); }
    assignment(businessId: string, workflow: PilotWorkflow) {
        const c = this.knowledge.company(businessId), spec = workflowDetails(workflow), scope = { capability: spec.capability, population: 'pilot-company-' + businessId + '-' + workflow }, id = 'pilot-baseline-' + hash(scope).slice(0, 20);
        const procedure = `${FINALIZING_WORKER_PROCEDURE}\nOwner-pilot job: ${spec.job}. Read all authorized company facts and policies. Distinguish sourced observations, assumptions and unknowns. Prefer the smallest useful deliverable; never invent customer demand, prices, authority or results. Resolve contradictory policy by flagging it for owner review. Check the exact current artifact, preserve rejected versions, and use complete-task finalization for checks, local publication and readback. Local publication is a preview only. Customer contact, deployments, payments and bookings are unavailable. Give the owner a clear primary action and useful input errors. A review may retain an adequate artifact unchanged. When an owner correction exists, inspect the current source and observation, make a targeted correction, and recheck the resulting version before proposing acceptance.`;
        const baseline = this.registry.baseline({ id, scope, procedure, strongBaselineReference: 'Existing excellent general-purpose finalizing worker procedure plus complete job, evidence, review, authority and quality instructions; same source/tool/resource access as any future candidate.' });
        const selected = this.registry.selected(scope, baseline.id);
        return { id: 'pilot-worker-' + hash(scope).slice(0, 20), name: workflow === 'response-packet' ? 'Business deliverable worker' : 'Local implementation worker', job: spec.job, capability: spec.capability, competencies: spec.competencies, tools: spec.tools, procedureVersion: selected.procedure.id, procedureHash: hash(selected.procedure.procedure), baselineProcedureId: baseline.id, procedureScope: scope, qualification: 'experimental_unqualified', evidence: c.mode === 'fixture' ? 'Offline execution mechanics can be inspected. No measured AI competence or advantage.' : 'No live results from this company yet. Declared job fit remains experimental.', selectionReason: selected.reason + '. One worker has the required declared tools; owner supplies policy judgment and acceptance. An extra role has no demonstrated benefit here.', limitations: ['Company-specific quality unmeasured', 'No independent human correction-time baseline', 'External actions and live model execution need separate exact authority'], requiredHuman: ['Supply current business policy and rights', 'Review local deliverable and consequential ambiguity', 'Authorize any later external effect separately'], selectedProcedure: selected.procedure, adoption: selected.adoption };
    }
    workers(businessId: string) { return (['response-packet', 'business-site'] as PilotWorkflow[]).map(w => this.assignment(businessId, w)); }
    list(businessId: string) { this.knowledge.company(businessId); return this.rows('pilot-learning').filter(x => x.businessId === businessId); }
    /** A persisted correction is evidence of an owner-requested change, not proof of a reasoning weakness. */
    propose(businessId: string, taskId: string, workflow: PilotWorkflow = 'response-packet') {
        const c = this.knowledge.company(businessId), correction = this.knowledge.corrections(businessId).filter(x => x.taskId === taskId).at(-1); requireThat(correction, 'PILOT_CORRECTION_EVIDENCE_REQUIRED');
        const assignment = this.assignment(businessId, workflow), key = 'learning-' + hash({ businessId, taskId, correction: correction.id }).slice(0, 24), existing = this.store.get('pilot-learning', key); if (existing) return existing;
        const portfolio = new Portfolio(this.store); if (!this.store.get('portfolio-venture', businessId)) portfolio.createVenture({ id: businessId, name: c.name, goal: c.goal, mode: c.mode === 'fixture' ? 'fixture' : 'local' });
        const observation = portfolio.recordObservation(businessId, { id: 'correction-' + hash(correction.id).slice(0, 24), kind: 'owner-correction', summary: 'The owner requested a material artifact correction; its cause remains a hypothesis until reviewed.', source: correction.id, provenance: correction.provenance, metadata: { correctionId: correction.id, artifactHash: correction.artifactHash, assisted: correction.assisted, independentHumanSeconds: null }, reassess: false }).observation;
        const candidateId = 'candidate-' + hash({ correction: correction.id, workflow }).slice(0, 24), procedure = assignment.selectedProcedure.procedure + '\nCandidate mechanism under evaluation: before finalizing an owner-corrected artifact, create a compact trace table from each correction requirement to the exact changed content and renewed check result. Reconcile that table against the source, owner-visible preview and local publication identity. If a correction changes a policy assumption, flag the shared specification and apply it consistently instead of treating the previous version as model inferiority.';
        const candidate = this.registry.propose({ id: candidateId, baselineId: assignment.baselineProcedureId, scope: assignment.procedureScope, procedure, mechanism: 'A correction trace table may prevent a requested change being lost between source, preview, checks and owner review.', observationId: observation.id, alternativeExplanation: 'The original output may have followed ambiguous or incomplete company context; owner preference can also change without a worker failure.', regressionRisk: 'Extra checklist work may increase latency and owner burden without improving accepted outcomes.', rights: 'reusable' });
        const value = { id: key, businessId, taskId, workflow, correctionId: correction.id, observationId: observation.id, sourceArtifactHash: correction.artifactHash, diagnosis: { symptom: 'Owner requested a correction to the preserved artifact', cause: 'Possible loss of a consequential requirement across artifact and review; not established', classification: 'owner correction; shared specification and preference-change alternatives remain open', provenance: 'development-assistant hypothesis grounded in a recorded correction' }, candidateId: candidate.id, baselineId: assignment.baselineProcedureId, candidateProcedureHash: hash(candidate.procedure), baselineProcedureHash: hash(assignment.selectedProcedure.procedure), status: 'candidate_prepared', decision: 'retain_baseline', comparison: null, qualification: 'experimental; no measured worker improvement', nextAction: c.mode === 'fixture' ? 'Exercise the comparison mechanics using separate disclosed synthetic evaluation observations.' : 'Freeze authorized development cases and a distinct evaluator-controlled comparison set before any actual-model measurement.', createdAt: new Date().toISOString() };
        return this.store.transaction(() => { this.store.record(pilotKnowledgeScope(businessId), key, 'PilotProcedureImprovementProposal', value); return this.store.put('pilot-learning', key, value, null); });
    }
    runFixtureComparison(businessId: string, taskId: string, workflow: PilotWorkflow = 'response-packet') {
        const c = this.knowledge.company(businessId); requireThat(c.mode === 'fixture', 'PILOT_FIXTURE_COMPARISON_ONLY'); const proposal = this.propose(businessId, taskId, workflow); if (proposal.comparison) return proposal;
        const baseline = this.store.get('portfolio-procedure', proposal.baselineId), candidate = this.store.get('portfolio-procedure', proposal.candidateId), scope = baseline.scope;
        // These are disclosed, development-authored observations. The deterministic check is shared;
        // it does not pretend that either worker generated these texts or establish semantic quality.
        const cases = [
            { id: 'evaluation-correction-trace', partition: 'evaluation_fixture', fresh: true, regression: false, requirements: ['human inspection', 'no booking'], baseline: 'Request human inspection; no booking has been made.', candidate: 'Request human inspection; no booking has been made. The correction is linked to the renewed policy check.' },
            { id: 'evaluation-unknown-price', partition: 'evaluation_fixture', fresh: true, regression: true, requirements: ['price unknown', 'owner review'], baseline: 'Price unknown pending owner review.', candidate: 'Price unknown pending owner review. The source and preview have matching wording.' }
        ];
        const check = (value: string, requirements: string[]) => requirements.every(r => value.includes(r));
        const observations = cases.map(item => ({ ...item, baselinePassed: check(item.baseline, item.requirements), candidatePassed: check(item.candidate, item.requirements), checkProvenance: 'deterministic exact requirement presence in development-authored fixture text; not semantic model scoring' }));
        const shared = { model: 'offline-scripted-fixture', toolsHash: hash(workflowDetails(workflow).tools), evidenceHash: hash(cases.map(x => ({ id: x.id, requirements: x.requirements }))), resourcesHash: hash({ callsPerCondition: 0, tokenCeiling: null, realProviderExposureMinor: 0, ownerTiming: 'unknown' }) };
        const evaluation = this.registry.evaluate(candidate.id, { id: 'pilot-fixture-comparison-v1', scope, provenance: 'fixture', baseline: { ...shared, instructionsHash: hash(baseline.procedure) }, candidate: { ...shared, instructionsHash: hash(candidate.procedure) }, strongBaselineReference: baseline.strongBaselineReference, resultEvidence: 'pilot-learning/' + proposal.id + '/comparison; exact fixture observations retained separately from the development correction', semanticReview: null, cases: observations.map(o => ({ id: o.id, fresh: o.fresh, regression: o.regression, baselinePassed: o.baselinePassed, candidatePassed: o.candidatePassed, criticalError: false, baselineCorrectionSeconds: null, candidateCorrectionSeconds: null })) });
        const selected = this.registry.selected(scope, baseline.id); requireThat(selected.procedure.id === baseline.id, 'PILOT_FIXTURES_CANNOT_SELECT_CANDIDATE');
        const comparison = { id: evaluation.id, observations, evaluationAnalysis: evaluation.analysis, developmentEvidence: { correctionId: proposal.correctionId, excludedFromEvaluation: true }, evaluationPopulation: 'Two separate developer-visible synthetic text fixtures; not a confidential holdout', fixtureDecision: 'retain_baseline', actualModelCalls: 0, actualProviderCostMinor: 0, independentHumanSeconds: null, strongerBaselinePreserved: true, futureSelection: selected.procedure.id, limitations: ['No model executed either procedure', 'Lexical fixture checks do not establish semantic usefulness', 'No worker improvement or production qualification established', 'Protected evaluation requires a real custodian boundary'] };
        return this.store.transaction(() => { const old = this.store.get('pilot-learning', proposal.id); const value = { ...old, status: 'fixture_comparison_complete', decision: 'retain_baseline', comparison, nextAction: 'Keep the strong baseline for future work. Collect a consequential real correction and authorize a fair bounded comparison only if it could change assignment.' }; this.store.record(pilotKnowledgeScope(businessId), proposal.id + '-comparison-v1', 'PilotFixtureComparison', comparison); return this.store.put('pilot-learning', proposal.id, value, old._version); });
    }
    run(businessId: string, taskId: string, workflow: PilotWorkflow = 'response-packet') { return this.knowledge.company(businessId).mode === 'fixture' ? this.runFixtureComparison(businessId, taskId, workflow) : this.propose(businessId, taskId, workflow); }
}
