import {hash,requireThat} from '../contracts.ts';
import type {ModelRequest} from '../contracts.ts';
import {pilotKnowledgeScope} from './knowledge.ts';
import {schemaCheck} from './intelligence-contract.ts';

export const outcomeFamilies=['response-packet','campaign-packet','business-site','marketing-page','functional-project'] as const;
export type OutcomeFamily=typeof outcomeFamilies[number];
const str=(max=2000)=>({type:'string',minLength:1,maxLength:max});
const obj=(properties:any)=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const array=(items:any,minItems=0,maxItems=12)=>({type:'array',items,minItems,maxItems});
export const outcomePlanSchema=obj({decision:{type:'string',enum:['prepare','reject','blocked']},rationale:str(4000),strongestAlternative:str(3000),blockingConditions:array(str()),
 evidenceRefs:array(obj({sourceId:str(160),quote:str(2000)}),1),
 tasks:array(obj({id:{...str(48),pattern:'^[a-z][a-z0-9-]{0,47}$'},family:{type:'string',enum:[...outcomeFamilies]},title:str(160),outcome:str(),details:str(4000),dependsOn:array(str(48),0,5),sourceIds:array(str(160),1,12),competencies:array(str(100),1,8),reasonForWorker:str(1500),calls:{type:'integer',minimum:3,maximum:16}}),0,6),
 successEvidence:array(str(),1,8),limitsOfInference:str(3000)});
export const OUTCOME_PLANNER_PROCEDURE=`Turn the owner's permitted outcome into the smallest executable dependency graph. You are an experimental work allocator, not a qualified CEO or a source of action authority. Challenge the outcome and propose reject or blocked when appropriate. Use current company evidence and the existing commercial proposal critically. Choose supported jobs for the actual work, never add a campaign or a second worker merely because that template exists. Different workers need different necessary jobs and explicit handoff dependencies. A response-packet can be any sourced business memo, offer or customer workflow. A campaign-packet coordinates offer, creative and lifecycle assets. A business-site provides a bounded inquiry interface. A marketing-page requires a preceding campaign-packet. A functional-project authors multiple frontend files and a declarative data/backend schema interpreted by trusted local code; it cannot execute arbitrary server modules, shell commands, external calls, or install dependencies. All work produces local reviewable artifacts only. Cite exact source quotations; source facts are not causal certainty. Preserve unknown economics and owner effort. Prefer a strong generalist until independent comparison evidence justifies specialization. Output ordered tasks with only earlier task IDs as dependencies. Allocate calls for source editing, actual checks, substantive review and deterministic completion: software needs at least one edit, check and completion; a multi-file project ordinarily needs at least seven calls including four files, check and finishing headroom. No extra calls for deterministic publication. Leave the mandate's repair reserve unused in primary work. Do not invent access, spending, demand or measured qualification. No required downstream work may be hidden in a completion note.`;

export function outcomePlannerProcedure(adaptive?:{allowCommands:boolean;allowServices?:boolean;acquisition?:unknown}){
 if(!adaptive)return OUTCOME_PLANNER_PROCEDURE;
 const procedure=OUTCOME_PLANNER_PROCEDURE.replace('it cannot execute arbitrary server modules, shell commands, external calls, or install dependencies.','the published application cannot execute arbitrary server modules or external calls. A separate task-scoped adaptive workbench is available under the exact mandate below. It can read, edit and test multi-file methods; isolated commands, private temporary services and public acquisition are available only when explicitly enabled. Acquired code and worker-authored tests remain unqualified candidates, not accepted business results. Stop services before delivery. Account for every tool step and capability-retention step in the same task call allocation.');
 return procedure+'\nExact optional workbench permissions: '+JSON.stringify({isolatedCommands:adaptive.allowCommands,privateServices:adaptive.allowServices===true,publicAcquisition:adaptive.acquisition??null})+'. These permissions do not grant provider spending or external business effects. Choose whether the added tools have a consequential purpose.';
}

export function validateOutcomePlan(value:any,context:any){
 schemaCheck(outcomePlanSchema,value);const sourceMap=new Map<string,any>(context.sources.map((s:any)=>[s.id,s]));
 for(const r of value.evidenceRefs)requireThat(sourceMap.get(r.sourceId)?.text.includes(r.quote),'OUTCOME_EVIDENCE_REFERENCE');
 const seen=new Map<string,any>();let calls=1+(context.mandate.preparationReserve??0);
 for(const t of value.tasks){requireThat(/^[a-z][a-z0-9-]{0,47}$/.test(t.id)&&!seen.has(t.id),'OUTCOME_TASK_ID');requireThat(context.mandate.allowedFamilies.includes(t.family),'OUTCOME_JOB_NOT_ALLOWED');requireThat(t.dependsOn.every((id:string)=>seen.has(id))&&new Set(t.dependsOn).size===t.dependsOn.length,'OUTCOME_DEPENDENCY_ORDER');requireThat(t.sourceIds.every((id:string)=>sourceMap.has(id))&&new Set(t.sourceIds).size===t.sourceIds.length,'OUTCOME_TASK_SOURCE');requireThat(Number.isSafeInteger(t.calls)&&t.calls>=3&&t.calls<=16,'OUTCOME_TASK_CALLS');if(t.family==='functional-project')requireThat(t.calls>=7,'OUTCOME_PROJECT_FINISH_CAPACITY');if(t.family==='marketing-page')requireThat(t.dependsOn.some((id:string)=>seen.get(id).family==='campaign-packet'),'OUTCOME_MARKETING_FOUNDATION');calls+=t.calls;seen.set(t.id,t);}
 requireThat(value.decision==='prepare'?value.tasks.length>0:value.tasks.length===0,'OUTCOME_DECISION_TASKS');requireThat(value.decision!=='blocked'||value.blockingConditions.length>0,'OUTCOME_BLOCK_REASON');
 requireThat(calls<=context.mandate.maxCalls-context.mandate.repairReserve,'OUTCOME_PRIMARY_CAPACITY');
 return {allocatedPrimaryCalls:calls,remainingRepairCalls:context.mandate.repairReserve,referenceChecks:'passed',semanticQuality:'unverified',planHash:hash(value)};
}
export function outcomePlanRequest(id:string,context:any):ModelRequest{return {scope:pilotKnowledgeScope(context.business.id),requestId:id,task:'decide',role:{id:'outcome-planner',version:context.mandate?.adaptive?'outcome-plan-adaptive-v1':'outcome-plan-v1',procedure:outcomePlannerProcedure(context.mandate?.adaptive),competencies:['evidence-synthesis','work-planning','resource-allocation'],tools:[],predecessor:null,model:'gpt-6-astra',qualification:'experimental_unqualified'},context,limits:{maxCost:{currency:'USD',minorUnits:205},maxAttempts:1,maxHumanMinutes:0},tools:[]};}
