/**
 * One signed, finite business journey.  This intentionally does not compose
 * the older intelligence and outcome loaders: each of those owns a ledger.
 * A journey owns one OperatingModels instance from discovery through the
 * outcome graph, so unused calls in one phase cannot silently become a second
 * account or a fresh response identity.
 */
import {existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync} from 'node:fs';
import {hostname} from 'node:os';
import {dirname, isAbsolute, join, relative, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {canonical, hash, rawHash, requireThat, scopeKey} from '../contracts.ts';
import type {ModelPort, ModelRequest, Principal, Scope} from '../contracts.ts';
import {signed, verified} from '../experiment/config.ts';
import {assertCountableRequest} from '../experiment/token-count.ts';
import {buildResponsesBody} from '../model-port.ts';
import {OperatingModels, implementationHash as operatingImplementationHash} from '../operations/model.ts';
import type {OperatingGrant} from '../operations/model.ts';
import {portfolioRoute, taskDefinitionHash} from '../portfolio/live.ts';
import {PortfolioEngine} from '../portfolio/engine.ts';
import {readOperatingLedgerAccounting} from '../portfolio/accounting-view.ts';
import {FINALIZING_WORKER_PROCEDURE, workerSchema, workerScope, validateWorker} from '../portfolio/worker.ts';
import type {WorkerCall, WorkerModel} from '../portfolio/worker.ts';
import {PilotDiscovery, DISCOVERY_VERSION, discoveryProcedure, discoverySchema} from './discovery.ts';
import {PilotIntelligence} from './intelligence.ts';
import {COMMERCIAL_PROCEDURE, intelligenceSchema, validateIntelligence} from './intelligence-contract.ts';
import {PilotOutcomes} from './outcomes.ts';
import {PilotLearning} from './learning.ts';
import {OUTCOME_PLANNER_PROCEDURE, outcomePlanSchema, validateOutcomePlan} from './outcome-contract.ts';

const AUTH='pilot.outcome.journey.authorization.json';
const PROPOSAL='pilot.outcome.journey.authorization.request.json';
const POLICY='one-ledger-business-journey-034-v1';
const STAGES=['discovery','analysis','planner','primary','repair'] as const;
type Stage=typeof STAGES[number];
type Services={outcomes:PilotOutcomes;intelligence:PilotIntelligence;discovery:PilotDiscovery};
type Profile={family:string;capability:string;procedureHash:string;schemaHash:string;allowedTools:string[];minimumCalls:number};
type Binding={kind:typeof POLICY;id:string;businessId:string;outcomeId:string;mandateHash:string;companyHash:string;implementationFiles:Array<{path:string;sha256:string}>;initialSources:Array<{id:string;sha256:string;permission:string}>;ownerObservationBaseline:{correctionHashes:string[];outcomeHashes:string[]};discovery:{id:string;version:string;seeds:string[];limits:any;publicReaderPolicy:'signed-session-only'};preparationReserve:7;plannerReserve:1;repairReserve:number;maximumCalls:number;primaryMaximum:number;profiles:Profile[];procedures:{discovery:string;analysis:string;planner:string;worker:string;correction:string};schemas:{discovery:string;analysis:string;planner:string;worker:string};initialRequest:{request:ModelRequest;requestHash:string;bodyHash:string};effectiveContextHash:string|null;effectiveSources:Array<{id:string;sha256:string;permission:string}>|null;externalEffects:false};
export type OutcomeJourneyGrant=OperatingGrant&{journey:Binding};

const accountScope=(id:string):Scope=>({tenantId:'mason',businessId:'outcome-journey-model-account',runId:id,dataPolicyVersion:POLICY,mode:'fixture'});
const LOCAL_TOOLS=['workspace.list','workspace.read','workspace.replace','workspace.patch','workspace.candidate_read','check.run','artifact.publish_local','research.read'];
const profileFor=(s:Services,businessId:string,family:string):Profile=>{const assignment=new PilotLearning(s.outcomes.store).assignment(businessId,family as any);return {family,capability:assignment.capability,procedureHash:assignment.procedureHash,schemaHash:hash(workerSchema),allowedTools:[...LOCAL_TOOLS],minimumCalls:family==='functional-project'?7:3};};
const PACKAGE_ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
function implementationFiles(directory=join(PACKAGE_ROOT,'src'),base=PACKAGE_ROOT):Array<{path:string;sha256:string}>{requireThat(existsSync(directory)&&statSync(directory).isDirectory(),'JOURNEY_IMPLEMENTATION_MISSING');return readdirSync(directory,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?implementationFiles(join(directory,entry.name),base):entry.isFile()&&entry.name.endsWith('.ts')?[{path:relative(base,join(directory,entry.name)).replace(/\\/g,'/'),sha256:rawHash(readFileSync(join(directory,entry.name)))}]:[]).sort((a,b)=>a.path.localeCompare(b.path));}
const sourceRows=(s:Services)=>s.outcomes.store.db.prepare('SELECT body FROM entities WHERE kind=? ORDER BY rowid').all('pilot-discovery-record').map((r:any)=>JSON.parse(String(r.body)));
const sources=(s:Services,businessId:string)=>s.outcomes.knowledge.selectedSources(businessId).map((x:any)=>({id:x.id,sha256:x.sha256,permission:x.permission??'worker',origin:x.origin??null}));
const company=(s:Services,id:string)=>s.outcomes.knowledge.company(id);
const mandateShape=(o:any)=>({id:o.id,businessId:o.businessId,objective:o.objective,autonomy:o.autonomy,allowedFamilies:o.allowedFamilies,maxCalls:o.maxCalls,repairReserve:o.repairReserve,preparationReserve:o.preparationReserve,effects:o.effects});
function limits(businessId:string,max:number,repair:number,reserve:number){const primary=max-repair-8;requireThat(primary>=0,'JOURNEY_FINITE_CAPACITY');const stages={discovery:6,analysis:1,planner:1,primary,repair};return {totalMinor:max*205+reserve,concurrency:1,astraCountRequests:max,overheadReserve:{minor:reserve,reason:'Explicit unpriced count and same-ID retrieval uncertainty reserve.'},stages:{smoke:{minor:0,attempts:0},development:{minor:max*205,attempts:max},validation:{minor:0,attempts:0},evaluation:{minor:0,attempts:0}},allocations:[{metadataKey:'businessId',value:businessId,attempts:max,minor:max*205},...Object.entries(stages).map(([value,attempts])=>({metadataKey:'stage',value,attempts,minor:attempts*205}))]};}
function bodyHash(g:OutcomeJourneyGrant,request:ModelRequest,schema:any){const body=buildResponsesBody(g.route,{...request,scope:g.accountScope},schema);assertCountableRequest(body,196608);return rawHash(canonical(body));}
function validate(services:Services,root:string,g:OutcomeJourneyGrant,approved:boolean){const b=g?.journey;requireThat(b?.kind===POLICY&&/^journey-034-[A-Za-z0-9_-]+$/.test(b.id),'JOURNEY_SIGNED_BINDING_REQUIRED');requireThat(g.kind==='operations-model-grant-v1'&&g.root===resolve(root)&&g.host===hostname()&&g.implementationHash===operatingImplementationHash(),'JOURNEY_GRANT_LOCATION_OR_CODE');requireThat(['mock','live'].includes(g.mode)&&/^proj_[A-Za-z0-9_-]+$/.test(g.projectId)&&(!g.credentialFile||isAbsolute(g.credentialFile)),'JOURNEY_PROJECT_OR_CREDENTIAL');requireThat(hash(g.accountScope)===hash(accountScope(b.id))&&g.retries===0&&g.providerConcurrency===1&&g.countDeadlineMs===10000&&g.countRequestByteCeiling===196608&&g.externalAuthority===false&&!g.recovery&&!g.stageContracts&&!g.learningGate,'JOURNEY_GRANT_SCOPE');
 requireThat(b.preparationReserve===7&&b.plannerReserve===1&&b.maximumCalls===g.businesses[0]?.maxCalls&&b.primaryMaximum===b.maximumCalls-b.repairReserve-8&&b.primaryMaximum>=0&&b.externalEffects===false,'JOURNEY_CAPACITY_BINDING');requireThat(hash(b.implementationFiles)===hash(implementationFiles()),'JOURNEY_AUTHORIZED_CODE_CHANGED');const reserve=g.limits.overheadReserve?.minor;requireThat(Number.isSafeInteger(reserve)&&reserve!>0&&hash(g.limits)===hash(limits(b.businessId,b.maximumCalls,b.repairReserve,reserve!)),'JOURNEY_ONE_LEDGER_LIMITS');requireThat(hash(g.route)===hash(portfolioRoute(b.id,g.projectId,true,true))&&g.businesses.length===1&&g.businesses[0].id===b.businessId&&g.businesses[0].sourceHosts.length===0,'JOURNEY_ROUTE_SCOPE');
 requireThat(b.discovery.version===DISCOVERY_VERSION&&b.discovery.limits.maxDecisions===6&&b.discovery.publicReaderPolicy==='signed-session-only'&&hash(b.procedures)===hash({discovery:hash(discoveryProcedure),analysis:hash(COMMERCIAL_PROCEDURE),planner:hash(OUTCOME_PLANNER_PROCEDURE),worker:hash(workerSchema),correction:hash(FINALIZING_WORKER_PROCEDURE)})&&hash(b.schemas)===hash({discovery:hash(discoverySchema),analysis:hash(intelligenceSchema),planner:hash(outcomePlanSchema),worker:hash(workerSchema)}),'JOURNEY_CONTRACT_CHANGED');const o=services.outcomes.get(b.outcomeId);requireThat(b.profiles.length===o.allowedFamilies.length&&new Set(b.profiles.map(p=>p.family)).size===b.profiles.length&&b.profiles.every(p=>hash(p)===hash(profileFor(services,b.businessId,p.family))),'JOURNEY_WORKER_PROFILE_CHANGED');requireThat(b.initialRequest.requestHash===hash(b.initialRequest.request)&&b.initialRequest.bodyHash===bodyHash(g,b.initialRequest.request,discoverySchema),'JOURNEY_INITIAL_REQUEST_CHANGED');requireThat(approved?g.approvedBy.trim().length>0&&g.approvalReference.trim().length>0:g.approvedBy===''&&g.approvalReference==='','JOURNEY_APPROVAL_REQUIRED');requireThat(Number.isFinite(Date.parse(g.expiresAt)),'JOURNEY_EXPIRY_REQUIRED');return b;}
function currentBeforeFreeze(s:Services,g:OutcomeJourneyGrant){
 const b=g.journey,o=s.outcomes.get(b.outcomeId),c=company(s,b.businessId),d=s.outcomes.store.get('pilot-discovery',b.businessId);
 requireThat(['awaiting_plan','planning','ready','running','completed','rejected','paused','blocked','cancelled'].includes(o.state),'JOURNEY_OUTCOME_STATE');
 requireThat(hash(mandateShape(o))===b.mandateHash&&o.businessId===b.businessId&&o.preparationReserve===7,'JOURNEY_MANDATE_CHANGED');
 requireThat(hash({id:c.id,name:c.name,goal:c.goal,website:c.website,notes:c.notes,mode:c.mode})===b.companyHash&&d?.id===b.discovery.id&&d.companyId===b.businessId&&d.version===b.discovery.version&&hash(d.seeds)===hash(b.discovery.seeds)&&hash(d.limits)===hash(b.discovery.limits),'JOURNEY_DISCOVERY_SCOPE_CHANGED');
 const corrections=s.outcomes.knowledge.corrections(b.businessId),observed=s.outcomes.knowledge.outcomes(b.businessId),prefix=corrections.slice(0,b.ownerObservationBaseline.correctionHashes.length),added=corrections.slice(b.ownerObservationBaseline.correctionHashes.length);
 requireThat(hash(prefix.map((x:any)=>hash(x)))===hash(b.ownerObservationBaseline.correctionHashes)&&hash(observed.map((x:any)=>hash(x)))===hash(b.ownerObservationBaseline.outcomeHashes),'JOURNEY_OWNER_OBSERVATION_CHANGED');
 requireThat(added.length===(o.corrections??[]).length&&added.every((x:any,i:number)=>x.id===o.corrections[i].correctionKey&&x.taskId===o.corrections[i].taskId&&x.artifactHash===o.corrections[i].artifactHash&&x.instruction===o.corrections[i].instruction),'JOURNEY_UNBOUND_OWNER_CORRECTION');
 const selected=sources(s,b.businessId);for(const initial of b.initialSources)requireThat(selected.some(x=>x.id===initial.id&&x.sha256===initial.sha256&&x.permission===initial.permission),'JOURNEY_INITIAL_EVIDENCE_CHANGED');
 for(const x of selected){const dynamic=sourceRows(s).some((r:any)=>r.companyId===b.businessId&&r.sessionId===b.discovery.id&&r.status==='retrieved'&&r.knowledgeSourceId===x.id&&r.result?.source?.contentHash===x.origin?.contentHash&&x.origin?.recordId===r.id);requireThat(b.initialSources.some(y=>y.id===x.id&&y.sha256===x.sha256&&y.permission===x.permission)||dynamic,'JOURNEY_UNGRANTED_EVIDENCE');}
 return {o,c,d,selected};
}
function current(s:Services,g:OutcomeJourneyGrant){const pre=currentBeforeFreeze(s,g),b=g.journey,stored=s.outcomes.store.get('pilot-outcome-journey-freeze',b.id),frozen=stored??(b.effectiveContextHash?{grantHash:hash(g),contextHash:b.effectiveContextHash,sources:b.effectiveSources}:null);if(frozen)requireThat(frozen.grantHash===hash(g)&&Array.isArray(frozen.sources)&&hash(pre.selected)===hash(frozen.sources),'JOURNEY_EFFECTIVE_CONTEXT_CHANGED');return pre;}

/** Preparation mutates only the owner's mandate to reserve the seven named
 * pre-planner admissions. It cannot sign, read credentials, or call a model. */
export function prepareOutcomeJourneyAuthorization(services:Services,input:{root:string;directory?:string;id:string;outcomeId:string;projectId:string;credentialFile:string|null;expiresAt:string;countUncertaintyMinor:number;mode?:'mock'|'live';billingPublicKey?:string|null}){
 requireThat(!existsSync(join(input.root,AUTH))&&/^journey-034-[A-Za-z0-9_-]+$/.test(input.id)&&/^proj_[A-Za-z0-9_-]+$/.test(input.projectId)&&Date.parse(input.expiresAt)>Date.now()&&Number.isSafeInteger(input.countUncertaintyMinor)&&input.countUncertaintyMinor>0,'JOURNEY_PREPARATION_INPUT');const o=services.outcomes.get(input.outcomeId),d=services.outcomes.store.get('pilot-discovery',o.businessId);requireThat(o.state==='awaiting_plan'&&o.autonomy==='prepare_supported_work'&&!services.outcomes.store.get('pilot-outcome-plan-attempt',o.id),'JOURNEY_UNSTARTED_MANDATE_REQUIRED');requireThat(d&&!d.pending&&d.used.decisions===0&&d.state!=='ready_for_analysis'&&d.limits.maxDecisions===6,'JOURNEY_UNSTARTED_DISCOVERY_REQUIRED');
 requireThat(o.maxCalls-o.repairReserve-8>=Math.min(...o.allowedFamilies.map((family:string)=>profileFor(services,o.businessId,family).minimumCalls)),'JOURNEY_FINISHING_CAPACITY_REQUIRED');
 if(o.preparationReserve!==7)services.outcomes.store.transaction(()=>{const old=services.outcomes.get(o.id);requireThat(old.state==='awaiting_plan'&&old.preparationReserve===0,'JOURNEY_PREPARATION_RESERVE_CHANGED');services.outcomes.store.put('pilot-outcome-mandate',o.id,{...old,preparationReserve:7,updatedAt:new Date().toISOString()},old._version);});const fresh=services.outcomes.get(o.id),initial=services.discovery.request(fresh.businessId).request,c=company(services,fresh.businessId),b:Binding={kind:POLICY,id:input.id,businessId:fresh.businessId,outcomeId:fresh.id,mandateHash:hash(mandateShape(fresh)),companyHash:hash({id:c.id,name:c.name,goal:c.goal,website:c.website,notes:c.notes,mode:c.mode}),implementationFiles:implementationFiles(),initialSources:sources(services,fresh.businessId),ownerObservationBaseline:{correctionHashes:services.outcomes.knowledge.corrections(fresh.businessId).map((x:any)=>hash(x)),outcomeHashes:services.outcomes.knowledge.outcomes(fresh.businessId).map((x:any)=>hash(x))},discovery:{id:d.id,version:d.version,seeds:d.seeds,limits:d.limits,publicReaderPolicy:'signed-session-only'},preparationReserve:7,plannerReserve:1,repairReserve:fresh.repairReserve,maximumCalls:fresh.maxCalls,primaryMaximum:fresh.maxCalls-fresh.repairReserve-8,profiles:fresh.allowedFamilies.map((family:string)=>profileFor(services,fresh.businessId,family)),procedures:{discovery:hash(discoveryProcedure),analysis:hash(COMMERCIAL_PROCEDURE),planner:hash(OUTCOME_PLANNER_PROCEDURE),worker:hash(workerSchema),correction:hash(FINALIZING_WORKER_PROCEDURE)},schemas:{discovery:hash(discoverySchema),analysis:hash(intelligenceSchema),planner:hash(outcomePlanSchema),worker:hash(workerSchema)},initialRequest:{request:initial,requestHash:hash(initial),bodyHash:''},effectiveContextHash:null,effectiveSources:null,externalEffects:false};
 const g:OutcomeJourneyGrant={kind:'operations-model-grant-v1',mode:input.mode??'live',root:resolve(input.root),host:hostname(),implementationHash:operatingImplementationHash(),projectId:input.projectId,credentialFile:input.credentialFile,billingPublicKey:input.billingPublicKey??null,expiresAt:input.expiresAt,approvedBy:'',approvalReference:'',accountScope:accountScope(input.id),route:portfolioRoute(input.id,input.projectId,true,true),limits:limits(fresh.businessId,fresh.maxCalls,fresh.repairReserve,input.countUncertaintyMinor),businesses:[{id:fresh.businessId,goalHash:hash(c.goal),sourceHosts:[],maxCalls:fresh.maxCalls}],retries:0,providerConcurrency:1,countDeadlineMs:10000,countRequestByteCeiling:196608,externalAuthority:false,journey:b};b.initialRequest.bodyHash=bodyHash(g,initial,discoverySchema);validate(services,input.root,g,false);currentBeforeFreeze(services,g);const summary={approved:false,providerRequests:0,credentialRead:false,maximumAdmissions:fresh.maxCalls,preparationReserve:7,plannerReserve:1,primaryMaximum:b.primaryMaximum,repairReserve:fresh.repairReserve,stages:{discovery:6,analysis:1,planner:1,primary:b.primaryMaximum,repair:fresh.repairReserve},authority:'One signed grant and one OperatingModels ledger cover only this fixed journey.'};if(input.directory){requireThat(!existsSync(join(input.directory,PROPOSAL)),'JOURNEY_NEW_UNSIGNED_PACKET_REQUIRED');mkdirSync(input.directory,{recursive:true});writeFileSync(join(input.directory,PROPOSAL),JSON.stringify(g,null,2)+'\n',{flag:'wx'});writeFileSync(join(input.directory,'journey-exact-initial-request.json'),JSON.stringify({...initial,bodyHash:b.initialRequest.bodyHash},null,2)+'\n',{flag:'wx'});writeFileSync(join(input.directory,'journey-execution-requirements.json'),JSON.stringify(summary,null,2)+'\n',{flag:'wx'});}return {proposal:g,proposalHash:hash(g),summary};
}
export function signOutcomeJourneyProposal(services:Services,root:string,input:{proposal:OutcomeJourneyGrant;expectedHash:string;principal:string;approvalReference:string;publicKey:string;privateKey:string}){requireThat(hash(input.proposal)===input.expectedHash&&!existsSync(join(root,AUTH))&&input.principal.trim().length>0&&input.approvalReference.trim().length>0,'JOURNEY_EXACT_APPROVAL_HASH');validate(services,root,input.proposal,false);currentBeforeFreeze(services,input.proposal);requireThat(Date.parse(input.proposal.expiresAt)>Date.now(),'JOURNEY_GRANT_EXPIRED');const grant={...structuredClone(input.proposal),approvedBy:input.principal,approvalReference:input.approvalReference};validate(services,root,grant,true);const envelope=signed(grant,input.privateKey);verified(envelope,input.publicKey);mkdirSync(join(root,'auth'),{recursive:true});const key=join(root,'auth','portfolio-owner.pub');if(existsSync(key))requireThat(readFileSync(key,'utf8')===input.publicKey,'JOURNEY_TRUST_ANCHOR_CHANGED');else writeFileSync(key,input.publicKey,{flag:'wx'});writeFileSync(join(root,AUTH),JSON.stringify(envelope,null,2)+'\n',{flag:'wx'});services.outcomes.store.record(grant.accountScope,'owner-exact-approval','OutcomeJourneyAuthorizationApproval',{proposalHash:input.expectedHash,grantHash:hash(grant),principal:input.principal,approvalReference:input.approvalReference});return {envelope,proposalHash:input.expectedHash,credentialRead:false,providerRequests:0};}

/** Read-only authority/accounting view for UI and CLI status.  It verifies the
 * envelope but neither creates a ledger nor opens the protected credential. */
export function inspectOutcomeJourney(services:Services,root:string){
 const zero={currency:'USD' as const,readOnly:true as const,executionAuthority:false as const,scope:'This signed journey only.',status:'unfunded' as const,reason:'No signed journey grant has created an accounting ledger.',callsUsed:0,callLimit:0,inferenceDispatches:0,countRequests:0,provisionalMinor:0,estimatedAttempts:0,unknownCostAttempts:0,settledMinor:null,settlementCount:0,retainedMinor:0,countBufferMinor:0,remainingMinor:null};
 const none={approved:false,current:false,liveEnabled:false,businessId:null as string|null,outcomeId:null as string|null,reason:'No signed journey authorization is installed.',credentialRead:false,accounting:zero};if(!existsSync(join(root,AUTH)))return none;
 try{const publicKey=readFileSync(join(root,'auth','portfolio-owner.pub'),'utf8'),g=verified(JSON.parse(readFileSync(join(root,AUTH),'utf8')),publicKey) as OutcomeJourneyGrant,prefix=scopeKey(g.accountScope)+'/',persisted=Boolean(services.outcomes.store.get('experiment-account',scopeKey(g.accountScope))||services.outcomes.store.db.prepare("SELECT 1 FROM entities WHERE kind='model-attempt' AND substr(key,1,?)=? LIMIT 1").get(prefix.length,prefix));
  const accounting=(()=>{try{return readOperatingLedgerAccounting(services.outcomes.store,g);}catch{return persisted?({currency:'USD',readOnly:true,executionAuthority:false,scope:'This signed journey only.',status:'unavailable',reason:'A persisted journey ledger could not be verified or read. Amounts are unavailable, not zero.',callsUsed:null,callLimit:null,inferenceDispatches:null,countRequests:null,provisionalMinor:null,estimatedAttempts:null,unknownCostAttempts:null,settledMinor:null,settlementCount:null,retainedMinor:null,countBufferMinor:null,remainingMinor:null} as any):zero;}})();
  let reason='Signed journey authority is current.',isCurrent=true,b:any;try{b=validate(services,root,g,true);requireThat(Date.parse(g.expiresAt)>Date.now()&&!services.outcomes.store.get('operating-revocation',hash(g)),'JOURNEY_GRANT_EXPIRED_OR_REVOKED');current(services,g);}catch(error){isCurrent=false;reason=(error as Error).message;b=g.journey;}
  const liveEnabled=isCurrent&&g.mode==='live'&&typeof g.credentialFile==='string'&&isAbsolute(g.credentialFile)&&existsSync(g.credentialFile)&&(accounting.callsUsed??0)<g.businesses[0].maxCalls;return {approved:true,current:isCurrent,liveEnabled,businessId:b.businessId,outcomeId:b.outcomeId,grantHash:hash(g),reason,credentialRead:false,accounting};
 }catch(error){return {...none,reason:(error as Error).message};}
}

function taskFor(s:Services,id:string){return s.outcomes.execution.portfolio.getTask(id);}
function outcomeNode(s:Services,g:OutcomeJourneyGrant,id:string){const o=s.outcomes.get(g.journey.outcomeId),node=o.graph.find((x:any)=>x.taskId===id),task=node&&taskFor(s,id);requireThat(node&&task,'JOURNEY_TASK_NOT_IN_GRAPH');return {o,node,task};}
export function loadAuthorizedOutcomeJourney(services:Services,root:string,options:{testing?:{envelope:any;trustedPublicKey:string;transport:typeof fetch}}={}){
 const envelope=options.testing?.envelope??JSON.parse(readFileSync(join(root,AUTH),'utf8')),publicKey=options.testing?.trustedPublicKey??readFileSync(join(root,'auth','portfolio-owner.pub'),'utf8'),g=verified(envelope,publicKey) as OutcomeJourneyGrant,b=validate(services,root,g,true),store=services.outcomes.store;requireThat(!options.testing||g.mode==='mock','JOURNEY_TEST_ENVELOPE_MOCK_ONLY');const credential=()=>{requireThat(typeof g.credentialFile==='string'&&isAbsolute(g.credentialFile),'JOURNEY_PROTECTED_CREDENTIAL_REQUIRED');return readFileSync(g.credentialFile,'utf8').trim();};const models=new OperatingModels({store,root,envelope,trustedPublicKey:publicKey,execution:options.testing?{kind:'mock',transport:options.testing.transport}:{kind:'live',credential,transport:fetch}}),principal:Principal={id:g.approvedBy,tenantId:'mason',businessId:b.businessId,permissions:['read','operate']},grantHash=hash(g),prefix=b.id+'/';
 const check=()=>{validate(services,root,g,true);requireThat(Date.parse(g.expiresAt)>Date.now()&&!store.get('operating-revocation',grantHash),'JOURNEY_GRANT_EXPIRED_OR_REVOKED');return current(services,g);};const recordPreparationAdmissions=()=>{const actual=models.ledger.rows().filter(x=>x.metadata.stage==='discovery'||x.metadata.stage==='analysis').length,old=services.outcomes.get(b.outcomeId);requireThat(actual<=b.preparationReserve&&old.preparationReserve===b.preparationReserve,'JOURNEY_PREPARATION_ADMISSION_SCOPE');if(old.preparationAdmissions!==actual)store.transaction(()=>{const latest=services.outcomes.get(b.outcomeId);store.put('pilot-outcome-mandate',b.outcomeId,{...latest,preparationAdmissions:actual,updatedAt:new Date().toISOString()},latest._version);});};const invoke=async(stage:Stage,request:ModelRequest,schema:any,accept:(x:any)=>void,recover=false)=>{const prior=models.ledger.get(request.requestId);if(recover)requireThat(prior,'JOURNEY_RECOVERY_NOT_ADMITTED');else{requireThat(!prior,'JOURNEY_USE_SAME_RESPONSE_RECOVERY');check();}let result:any;try{result=await models.invoke(principal,{businessId:b.businessId,goalHash:g.businesses[0].goalHash,sourceHosts:[],attemptId:request.requestId,stage,request,schema,validate:accept});}finally{if(stage==='discovery'||stage==='analysis')recordPreparationAdmissions();}/* OperatingModels has durably preserved a returned response before this point. Re-check here, rather than before retrieval, so a known identity remains recoverable after authority changes but can never be applied to changed scope. */check();return g.mode==='mock'?{...result,route:{...result.route,kind:'fixture' as const,provider:'offline-responses-mock'}}:result;};
 const discoveryPort:ModelPort & {recoverSameResponse:(r:ModelRequest)=>Promise<any>}={kind:g.mode==='mock'?'fixture':'live',run:r=>invoke('discovery',r,discoverySchema,x=>services.discovery.validateAction(b.businessId,x,r.context)),recoverSameResponse:r=>invoke('discovery',r,discoverySchema,x=>services.discovery.validateAction(b.businessId,x,r.context),true)};
 const analysisPort:ModelPort & {recoverSameResponse:(r:ModelRequest)=>Promise<any>}={kind:g.mode==='mock'?'fixture':'live',run:r=>invoke('analysis',r,intelligenceSchema,x=>validateIntelligence(x,(store.get('pilot-commercial-attempt',b.businessId+'/'+r.requestId)?.sources??[]))),recoverSameResponse:r=>invoke('analysis',r,intelligenceSchema,x=>validateIntelligence(x,(store.get('pilot-commercial-attempt',b.businessId+'/'+r.requestId)?.sources??[])),true)};
 const failure=(id:string)=>{const row=models.ledger.get(id);return {status:!row?'not_admitted':row.errorCode?'terminal_failed':'unknown',observationId:'model-attempt/'+id,code:row?.errorCode??null} as any;};
 const runDiscovery=async()=>{await services.discovery.recover(b.businessId);for(;;){const session=store.get('pilot-discovery',b.businessId),unknown=sourceRows(services).filter((x:any)=>x.sessionId===b.discovery.id&&x.kind==='decision'&&x.status==='unknown').at(-1);if(session.state==='ready_for_analysis'||session.state==='paused'||session.state==='blocked'&&!unknown)return services.discovery.view(b.businessId);if(!unknown)requireThat(models.ledger.rows().filter(x=>x.metadata.stage==='discovery').length<6,'JOURNEY_DISCOVERY_CAP');const id=unknown?.id??services.discovery.request(b.businessId).request.requestId;await services.discovery.next(b.businessId,{port:discoveryPort,attemptId:id,recoverSameResponse:discoveryPort.recoverSameResponse,trustedFailureObservation:failure});}};
 const runAnalysis=async()=>{const old=store.db.prepare("SELECT body FROM entities WHERE kind='pilot-commercial-attempt' ORDER BY rowid").all().map((x:any)=>JSON.parse(String(x.body))).filter((x:any)=>x.businessId===b.businessId).at(-1);if(old?.status==='completed')return services.intelligence.view(b.businessId);requireThat(store.get('pilot-discovery',b.businessId)?.state==='ready_for_analysis','JOURNEY_DISCOVERY_FINISH_REQUIRED');return old?services.intelligence.resume(b.businessId,analysisPort):services.intelligence.analyze(b.businessId,analysisPort,services.discovery.context(b.businessId));};
 const freeze=()=>{const p=services.outcomes.prepare(b.outcomeId),now=sources(services,b.businessId),old=store.get('pilot-outcome-journey-freeze',b.id);if(!old)store.transaction(()=>store.put('pilot-outcome-journey-freeze',b.id,{grantHash,contextHash:p.contextHash,sources:now,at:new Date().toISOString()},null));else requireThat(old.grantHash===grantHash&&old.contextHash===p.contextHash&&hash(old.sources)===hash(now),'JOURNEY_EFFECTIVE_CONTEXT_CHANGED');return p;};
 const plan=async()=>{check();let attempt=store.get('pilot-outcome-plan-attempt',b.outcomeId),p:any;if(attempt?.result)return services.outcomes.acceptPlan(b.outcomeId,attempt,attempt.result);if(!attempt){p=freeze();const o=services.outcomes.get(b.outcomeId);requireThat(o.state==='awaiting_plan'&&o.plannerAdmissions===0,'JOURNEY_PLANNER_STATE');attempt={id:o.id,request:p.request,requestHash:hash(p.request),context:p.context,contextHash:p.contextHash,grantHash,state:'pending',createdAt:new Date().toISOString()};store.transaction(()=>{store.put('pilot-outcome-plan-attempt',o.id,attempt,null);const old=services.outcomes.get(o.id);store.put('pilot-outcome-mandate',o.id,{...old,plannerAdmissions:1,state:'planning',updatedAt:new Date().toISOString()},old._version);});}else{p=freeze();requireThat(attempt.id===b.outcomeId&&attempt.grantHash===grantHash&&attempt.requestHash===hash(attempt.request)&&attempt.contextHash===p.contextHash&&hash(attempt.request)===hash(p.request),'JOURNEY_PLANNER_ATTEMPT_CHANGED');}const recover=Boolean(models.ledger.get(attempt.request.requestId));try{const r=await invoke('planner',attempt.request,outcomePlanSchema,x=>validateOutcomePlan(x,attempt.context),recover),saved=store.get('pilot-outcome-plan-attempt',b.outcomeId);store.transaction(()=>store.put('pilot-outcome-plan-attempt',b.outcomeId,{...saved,result:r,state:'response_preserved'},saved._version));const accepted=services.outcomes.acceptPlan(b.outcomeId,store.get('pilot-outcome-plan-attempt',b.outcomeId),r);requireThat(accepted.plan?.decision!=='reject'||accepted.state==='rejected','JOURNEY_PLANNER_REJECTION_STATE');return accepted;}catch(error){const saved=store.get('pilot-outcome-plan-attempt',b.outcomeId),row=models.ledger.get(attempt.request.requestId),job=row?store.get('response-job',models.ledger.key(attempt.request.requestId)):null,status=job?.terminal?.status==='incomplete'?'terminal_incomplete':['failed','cancelled'].includes(job?.terminal?.status)?'terminal_failed':row?'unknown':'not_admitted';if(saved)store.transaction(()=>store.put('pilot-outcome-plan-attempt',b.outcomeId,{...saved,state:status,error:String((error as Error).message)},saved._version));throw error;}};
 let engine:PortfolioEngine;const bindings=()=>store.db.prepare("SELECT body FROM entities WHERE kind='pilot-outcome-journey-task' ORDER BY rowid").all().map((x:any)=>JSON.parse(String(x.body))).filter((x:any)=>x.grantHash===grantHash);
 const bind=async(taskId:string)=>{check();let {o,node,task}=outcomeNode(services,g,taskId),inputs=task.inputs as any,profile=b.profiles.find(p=>p.family===node.family),correction=node.generation>0&&Boolean(inputs?.correctionOf);requireThat(profile&&task.ventureId===b.businessId&&task.status==='queued'&&task.attempts===0&&!task.lease&&node.calls>=profile.minimumCalls&&task.resource.modelCalls===node.calls&&task.capability===(correction?'quality.review':profile.capability)&&task.effectAuthority?.kind==='local'&&task.allowedTools.every((x:string)=>profile!.allowedTools.includes(x))&&inputs?.outcomeId===b.outcomeId&&inputs?.outcomeNodeId===node.id&&inputs?.outcomeGeneration===node.generation&&inputs?.outcomePlanHash===o.planHash,'JOURNEY_UNSTARTED_TASK');requireThat(node.sourceIds.every((id:string)=>sources(services,b.businessId).some((x:any)=>x.id===id)),'JOURNEY_TASK_SOURCE_CHANGED');const existing=store.get('pilot-outcome-journey-task',prefix+taskId);if(existing){requireThat(existing.definitionHash===taskDefinitionHash(task)&&existing.inputHash===hash(task.inputArtifacts),'JOURNEY_TASK_CHANGED');return existing;}const expected=correction?hash(FINALIZING_WORKER_PROCEDURE):profile.procedureHash;store.transaction(()=>store.put('portfolio-task',taskId,{...task,inputs:{...inputs,modelCallMaxMinor:205}},task._version));task=taskFor(services,taskId);const preview=await engine.previewRequest(taskId);requireThat(hash(preview.request.role.procedure)===expected&&hash(preview.schema)===profile.schemaHash,'JOURNEY_WORKER_CONTRACT_CHANGED');const stage:Stage=node.generation>0?'repair':'primary',value={id:taskId,grantHash,stage,definitionHash:taskDefinitionHash(task),inputHash:hash(task.inputArtifacts),procedureHash:expected,schemaHash:profile.schemaHash,initialRequest:preview.request};store.transaction(()=>store.put('pilot-outcome-journey-task',prefix+taskId,value,null));return value;};
 const workerInvoke=async(call:WorkerCall,recover:boolean)=>{const task=store.db.prepare("SELECT body FROM entities WHERE kind='portfolio-task' ORDER BY rowid").all().map((x:any)=>JSON.parse(String(x.body))).find((x:any)=>scopeKey(workerScope(x.ventureId,x.id))===scopeKey(call.request.scope)),binding=task&&store.get('pilot-outcome-journey-task',prefix+task.id);requireThat(task&&binding&&binding.definitionHash===taskDefinitionHash(task)&&binding.inputHash===hash(task.inputArtifacts)&&binding.procedureHash===hash(call.request.role.procedure)&&binding.schemaHash===hash(call.schema),'JOURNEY_WORKER_INTENT_CHANGED');const persisted=store.db.prepare("SELECT body FROM entities WHERE kind='portfolio-model-request' ORDER BY rowid").all().map((x:any)=>JSON.parse(String(x.body))).find((x:any)=>x.call?.attemptId===call.attemptId);requireThat(persisted&&hash(persisted.call.request)===hash(call.request),'JOURNEY_WORKER_INTENT_REQUIRED');const result=await invoke(binding.stage,call.request,call.schema,validateWorker,recover);services.outcomes.execution.assertContextCurrent(task.id,true);check();return result;};
 const worker:WorkerModel={kind:g.mode==='mock'?'offline_mock':'actual_model',run:c=>workerInvoke(c,false),recover:c=>models.ledger.get(c.attemptId)?workerInvoke(c,true):Promise.resolve(null)};const totals=()=>({...models.totals(),stageUsage:Object.fromEntries(STAGES.map(stage=>[stage,{used:models.ledger.rows().filter(x=>x.metadata.stage===stage).length,limit:g.limits.allocations!.find(x=>x.metadataKey==='stage'&&x.value===stage)!.attempts}])),authorization:grantHash});engine=new PortfolioEngine({portfolio:services.outcomes.execution.portfolio,tools:services.outcomes.execution.tools,evidence:services.outcomes.execution.evidence,prepareTask:services.outcomes.execution.engine.prepareTask,model:worker,accounting:totals,validateTask:task=>{check();services.outcomes.execution.assertContextCurrent(task.id,true);}});
 const runTask=async(id:string)=>{await engine.recover();let t=taskFor(services,id);if(t.status==='needs_reconciliation')await engine.resumeResponse(id);t=taskFor(services,id);if(t.status==='completed')return t;await bind(id);return engine.runTask(id,(t.inputs as any).assignedWorkerId??'pilot-generalist');};const run=async()=>{await runDiscovery();await runAnalysis();let outcome=services.outcomes.get(b.outcomeId);if(!outcome.plan)await plan();outcome=services.outcomes.get(b.outcomeId);if(outcome.plan?.decision==='reject')return outcome;requireThat(outcome.plan?.decision==='prepare','JOURNEY_PLAN_REQUIRED');for(let pass=0;pass<8;pass++){services.outcomes.materialize(b.outcomeId);let advanced=false;for(const n of services.outcomes.get(b.outcomeId).graph)if(n.taskId&&['queued','needs_reconciliation'].includes(taskFor(services,n.taskId).status)){await runTask(n.taskId);advanced=true;}if(!advanced)break;}return services.outcomes.refresh(b.outcomeId);};
 return {authorization:g,runDiscovery,runAnalysis,plan,run,resume:run,runTask,totals,status:()=>({outcome:services.outcomes.view(b.outcomeId),discovery:services.discovery.view(b.businessId),intelligence:services.intelligence.view(b.businessId),totals:totals()}),control:(action:'pause'|'resume'|'cancel')=>services.outcomes.control(b.outcomeId,action),correct:(input:{nodeId:string;artifactHash:string;instruction:string;repairCalls:number;assisted:boolean})=>{check();return services.outcomes.correct(b.outcomeId,input);}};
}

/** Compatibility name for the product service; callers receive the same
 * bounded runner and never a raw OperatingModels handle. */
export const loadOutcomeJourney=loadAuthorizedOutcomeJourney;
