import {randomUUID} from 'node:crypto';
import {hash,requireThat} from '../contracts.ts';
import type {ModelPort} from '../contracts.ts';
import type {WorkerModel} from '../portfolio/worker.ts';
import {StateStore} from '../state.ts';
import {PilotKnowledge,pilotKnowledgeScope} from './knowledge.ts';
import {PilotExecution} from './execution.ts';
import {PilotIntelligence} from './intelligence.ts';
import {WorkerDevelopmentService} from './worker-development-service.ts';
import {PilotLearning} from './learning.ts';
import {outcomeFamilies,outcomePlanRequest,validateOutcomePlan} from './outcome-contract.ts';
import type {OutcomeFamily} from './outcome-contract.ts';
import {boundObservationContext} from './observation-loop.ts';
import {validateAdaptiveOptions,adaptiveContract,ADAPTIVE_TOOL} from '../adaptive/worker-contract.ts';
import type {AdaptiveOptions} from '../adaptive/worker-contract.ts';

/** A finite owner mandate over the existing controller, not a second scheduler.
 * The mandate is local workflow authority only. A signed provider grant remains separate. */
export class PilotOutcomes{
 readonly knowledge:PilotKnowledge;readonly intelligence:PilotIntelligence;readonly store:StateStore;readonly execution:PilotExecution;
 constructor(store:StateStore,execution:PilotExecution){this.store=store;this.execution=execution;this.knowledge=new PilotKnowledge(store);this.intelligence=new PilotIntelligence(store,execution);}
 private rows(kind:string){return this.store.db.prepare('SELECT body,version FROM entities WHERE kind=? ORDER BY rowid').all(kind).map(r=>({...JSON.parse(String(r.body)),_version:Number(r.version)}));}
 get(id:string){const r=this.store.get('pilot-outcome-mandate',id);requireThat(r,'OUTCOME_NOT_FOUND');return r;}
 list(businessId:string){this.knowledge.company(businessId);return this.rows('pilot-outcome-mandate').filter(o=>o.businessId===businessId).map(o=>this.view(o.id));}
 private write(id:string,patch:any){const p=this.get(id);return this.store.put('pilot-outcome-mandate',id,{...p,...patch,updatedAt:new Date().toISOString()},p._version);}
 private save(id:string,patch:any){return this.store.transaction(()=>this.write(id,patch));}
 create(businessId:string,input:{id?:string;observationIds?:string[];objective:string;autonomy:'propose_only'|'prepare_supported_work';allowedFamilies?:OutcomeFamily[];maxCalls:number;repairReserve:number;adaptive?:AdaptiveOptions}){
  if(input.adaptive)validateAdaptiveOptions(input.adaptive);
  if(input.adaptive?.acquisition)requireThat(this.knowledge.company(businessId).mode==='fixture'||this.knowledge.selectedSources(businessId).every(s=>s.origin?.kind==='public-retrieval'),'ACQUISITION_PRIVATE_CONTEXT_DENIED');
  this.knowledge.company(businessId);requireThat(typeof input.objective==='string'&&input.objective.trim().length>=8&&input.objective.length<=4000,'OUTCOME_OBJECTIVE');requireThat(['propose_only','prepare_supported_work'].includes(input.autonomy),'OUTCOME_AUTONOMY');
  requireThat(Number.isSafeInteger(input.maxCalls)&&input.maxCalls>=4&&input.maxCalls<=64&&Number.isSafeInteger(input.repairReserve)&&input.repairReserve>=0&&input.repairReserve<input.maxCalls-3,'OUTCOME_FINITE_CAPACITY');
  const allowedFamilies=input.allowedFamilies??[...outcomeFamilies];requireThat(allowedFamilies.length>0&&new Set(allowedFamilies).size===allowedFamilies.length&&allowedFamilies.every(f=>outcomeFamilies.includes(f)),'OUTCOME_FAMILY_SCOPE');
  const observationIds=input.observationIds??[],observations=boundObservationContext(this.store,businessId,observationIds),creationHash=hash({businessId,...input,allowedFamilies,observationIds});
  const id=input.id??'outcome-'+randomUUID().slice(0,18);requireThat(/^[A-Za-z0-9][A-Za-z0-9_-]{0,119}$/.test(id),'OUTCOME_ID');
  const prior=this.store.get('pilot-outcome-mandate',id);if(prior){requireThat(prior.creationHash===creationHash,'OUTCOME_CREATE_ID_CONFLICT');return prior;}
  const v={id,businessId,...input,allowedFamilies,observationIds,observationContextHash:hash(observations),creationHash,effects:'local_preparation_only',state:'awaiting_plan',taskIds:[],graph:[],plannerAdmissions:0,preparationAdmissions:0,preparationReserve:0,repairAllocated:0,plan:null,contextHash:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),provenance:'Owner outcome mandate; no provider or external-action permission'};
  return this.store.transaction(()=>{this.store.record(pilotKnowledgeScope(businessId),id,'OutcomeMandate',v);return this.store.put('pilot-outcome-mandate',id,v,null);});
 }
 prepare(id:string){const o=this.get(id),observations=boundObservationContext(this.store,o.businessId,o.observationIds??[]);requireThat(!o.observationContextHash||hash(observations)===o.observationContextHash,'OUTCOME_OBSERVATION_CONTEXT_CHANGED');const b=this.knowledge.company(o.businessId),sources=this.intelligence.sources(b.id);requireThat(sources.length>0,'OUTCOME_EVIDENCE_REQUIRED');const analysis=this.intelligence.view(b.id),context={business:{id:b.id,name:b.name,goal:b.goal,notes:b.notes,website:b.website},mandate:{objective:o.objective,autonomy:o.autonomy,allowedFamilies:o.allowedFamilies,maxCalls:o.maxCalls,repairReserve:o.repairReserve,preparationReserve:o.preparationReserve??0,effects:o.effects,...(o.adaptive?{adaptive:o.adaptive}:{})},sources,businessMode:this.store.get('pilot-business-intake',b.id)?.operatingMode??'operate',observedResults:observations,commercialUnderstanding:analysis.current?{executiveSummary:analysis.executiveSummary,opportunities:analysis.opportunities,provenance:analysis.provenance}:null,ownerObservations:{corrections:this.knowledge.corrections(b.id).slice(-4),outcomes:this.knowledge.outcomes(b.id).slice(-4)},acceptance:'All required behavior is in this schema/procedure/context. Every source reference must quote supplied text exactly. No hidden desired business or team. A valid rejection saves dependent work. Existing analysis remains a proposal, not authority.'};const contextHash=this.intelligence.contextHash(b.id),request=outcomePlanRequest(id+'-plan',context);return {request,context,contextHash};}
 async propose(id:string,port:ModelPort){
  const p=this.prepare(id),o=this.get(id),prior=this.store.get('pilot-outcome-plan-attempt',id);
  // Live callers must use the separate signed factory; UI and ordinary ports cannot create authority.
  requireThat(port.kind==='fixture','OUTCOME_SIGNED_RUNNER_REQUIRED');
  if(prior?.result)return this.acceptPlan(id,prior,prior.result);
  requireThat(!prior&&o.state==='awaiting_plan','OUTCOME_PLAN_UNCERTAIN_NO_RESUBMIT');
  this.store.transaction(()=>{this.store.put('pilot-outcome-plan-attempt',id,{id,request:p.request,requestHash:hash(p.request),context:p.context,contextHash:p.contextHash,state:'pending',createdAt:new Date().toISOString()},null);this.write(id,{plannerAdmissions:1,state:'planning'});});
  try{const result=await port.run(p.request);const a=this.store.get('pilot-outcome-plan-attempt',id);this.store.transaction(()=>this.store.put('pilot-outcome-plan-attempt',id,{...a,result,state:'response_preserved'},a._version));return this.acceptPlan(id,a,result);}catch(e){const a=this.store.get('pilot-outcome-plan-attempt',id);this.store.transaction(()=>this.store.put('pilot-outcome-plan-attempt',id,{...a,state:a.result?'invalid_preserved':'unknown',error:String((e as Error).message)},a._version));this.save(id,{state:'blocked',reason:String((e as Error).message)});throw e;}
 }
 acceptPlan(id:string,attempt:any,result:any){const o=this.get(id);requireThat(!['cancelled','paused'].includes(o.state),'OUTCOME_CONTROL_BLOCKS_PLAN');const observed=boundObservationContext(this.store,o.businessId,o.observationIds??[]);requireThat(!o.observationContextHash||hash(observed)===o.observationContextHash,'OUTCOME_OBSERVATION_CONTEXT_CHANGED');requireThat(attempt.id===id&&hash(attempt.request)===attempt.requestHash&&attempt.contextHash===this.intelligence.contextHash(o.businessId),'OUTCOME_CONTEXT_CHANGED');const audit=validateOutcomePlan(result.output,attempt.context);if(o.plan)return o;const plan=result.output,state=plan.decision==='prepare'?(o.autonomy==='prepare_supported_work'?'ready':'waiting_owner_selection'):plan.decision==='reject'?'rejected':'blocked';return this.store.transaction(()=>{const a=this.store.get('pilot-outcome-plan-attempt',id);requireThat(a?.result&&hash(a.result)===hash(result),'OUTCOME_PRESERVED_RESULT_REQUIRED');this.store.put('pilot-outcome-plan-attempt',id,{...a,state:'completed'},a._version);return this.write(id,{plan,planHash:hash(plan),audit,contextHash:attempt.contextHash,state,reason:plan.rationale,graph:plan.tasks.map((t:any)=>({...t,taskId:null,generation:0,status:'waiting_dependencies'})),planProvenance:result.route.kind==='fixture'?'offline fixture; planner decisions were development-authored':'actual-model proposal; quality and optimal assignment unproven'});});}
 allowPreparation(id:string){const o=this.get(id);requireThat(o.state==='waiting_owner_selection','OUTCOME_NOT_WAITING');return this.save(id,{autonomy:'prepare_supported_work',state:'ready',ownerSelectedAt:new Date().toISOString()});}
 assignment(businessId:string,node:any){
  const base=new PilotLearning(this.store).assignment(businessId,node.family), sources=this.knowledge.selectedSources(businessId).filter(s=>node.sourceIds.includes(s.id)), jobId=node.family+'-'+hash(sources.map(s=>({id:s.id,sha256:s.sha256}))).slice(0,12), development=new WorkerDevelopmentService(this.store);
  try{development.development.getDefinition(businessId,jobId);}catch{development.define(businessId,jobId,{responsibilities:[base.job],model:'gpt-6-astra',tools:[...base.tools],sourceIds:sources.map(s=>s.id),capability:base.capability,baselineProcedure:base.selectedProcedure.procedure,outputContract:{id:node.family,version:'034-v1',description:base.job},knownLimits:[...base.limitations,'No fixture observation establishes superior job competence.']});}
  const selected=development.assignment(businessId,jobId,node.family);requireThat(selected.sourceCurrent,'OUTCOME_WORKER_CONTEXT_REVOKED');return {...selected,jobId,reasonForWorker:node.reasonForWorker,requestedCompetencies:node.competencies,competenceEvidence:'Declared tool/procedure fit; no measured specialist advantage.'};
 }
 materialize(id:string){let o=this.get(id);const observationContext=boundObservationContext(this.store,o.businessId,o.observationIds??[]);requireThat(!o.observationContextHash||hash(observationContext)===o.observationContextHash,'OUTCOME_OBSERVATION_CONTEXT_CHANGED');requireThat(['ready','running','blocked','completed'].includes(o.state)&&o.plan?.decision==='prepare','OUTCOME_NOT_EXECUTABLE');requireThat(o.contextHash===this.intelligence.contextHash(o.businessId),'OUTCOME_CONTEXT_CHANGED');
  for(const node of o.graph){if(node.taskId)continue;const parents=node.dependsOn.map((key:string)=>o.graph.find((n:any)=>n.id===key));if(parents.some((p:any)=>!p?.taskId||!this.execution.artifact(o.businessId,p.taskId)?.current||this.execution.portfolio.getTask(p.taskId).status!=='completed'))continue;
   const sourceLimits=['response-packet','business-site'].includes(node.family)?{maxSources:12,maxSourceCharacters:20000,maxBytes:8000}:{maxSources:24,maxSourceCharacters:24000,maxBytes:160000};
   const sources=this.intelligence.executionSources(o.businessId,node.sourceIds,sourceLimits),baseAssignment=this.assignment(o.businessId,node),compiled=o.adaptive?adaptiveContract(o.adaptive):null;
   const assignment=compiled?{...baseAssignment,id:'pilot-generalist',name:'Business generalist · adaptive workbench · experimental',procedureVersion:'adaptive-project-v1/'+o.adaptive!.prompt,procedureHash:hash(compiled.procedure),selectedProcedure:{id:'adaptive-project-v1/'+o.adaptive!.prompt,procedure:compiled.procedure},adoption:null,tools:[...new Set([...baseAssignment.tools,ADAPTIVE_TOOL])],qualification:'experimental; no measured specialist advantage',selectionReason:'The explicitly selected adaptive generalist has the declared isolated tools. Prior specialized-procedure adoption does not apply to this separately compiled procedure.'}:baseAssignment,campaign=parents.find((p:any)=>p.family==='campaign-packet');
   const task=this.execution.plan({taskId:id+'-'+node.id+'-v'+node.generation,business:this.knowledge.company(o.businessId),sources,selectedEvidence:true,workflow:node.family,...(o.adaptive?{adaptive:{...o.adaptive,modelCalls:node.calls,localToolRuns:Math.min(128,Math.max(32,node.calls*4))}}:{procedureBinding:assignment}),job:{title:node.title,outcome:node.outcome,details:node.details},requiredSourceIds:node.sourceIds,...(node.family==='marketing-page'?{campaignTaskId:campaign.taskId}:{})});
   this.store.transaction(()=>{const t=this.execution.portfolio.getTask(task.id),bindings=parents.flatMap((p:any)=>this.execution.portfolio.getTask(p.taskId).outputArtifacts);this.store.put('portfolio-task',t.id,{...t,dependsOn:parents.map((p:any)=>p.taskId),inputArtifacts:bindings,resource:{...t.resource,modelCalls:node.calls,localToolRuns:Math.max(t.resource.localToolRuns,node.calls+8)},inputs:{...t.inputs as any,outcomeId:id,outcomeNodeId:node.id,outcomeGeneration:node.generation,outcomePlanHash:o.planHash,...(observationContext.length?{outcomeObservations:observationContext}:{})}},t._version);o=this.write(id,{taskIds:[...new Set([...o.taskIds,t.id])],graph:o.graph.map((n:any)=>n.id===node.id?{...n,taskId:t.id,status:'planned',assignment}:n),state:'ready'});});
  }return this.view(id);
 }
 async runOffline(id:string){const o=this.get(id);requireThat(this.knowledge.company(o.businessId).mode==='fixture','OUTCOME_REAL_EXECUTION_REQUIRES_GRANT');requireThat(!['paused','cancelled','rejected','waiting_owner_selection'].includes(o.state),'OUTCOME_NOT_EXECUTABLE');this.save(id,{state:'running'});
  for(let pass=0;pass<o.graph.length+1;pass++){this.materialize(id);const current=this.get(id);let advanced=false;for(const node of current.graph){if(!node.taskId)continue;const t=this.execution.portfolio.getTask(node.taskId);if(t.status!=='queued')continue;this.save(id,{state:'running'});await this.execution.run(o.businessId,t.id);advanced=true;}if(!advanced)break;}return this.refresh(id);
 }
 refresh(id:string){const o=this.get(id),contextCurrent=!o.contextHash||o.contextHash===this.intelligence.contextHash(o.businessId),graph=o.graph.map((n:any)=>{const t=n.taskId?this.execution.portfolio.getTask(n.taskId):null;return {...n,status:t?.status??n.status,current:n.taskId?Boolean(this.execution.artifact(o.businessId,n.taskId)?.current):false};}),complete=contextCurrent&&graph.length>0&&graph.every((n:any)=>n.status==='completed'&&n.current),blocked=!contextCurrent||graph.some((n:any)=>['blocked','stale','needs_reconciliation','failed'].includes(n.status));const state=['paused','cancelled','rejected','waiting_owner_selection','awaiting_plan'].includes(o.state)?o.state:complete?'completed':blocked?'blocked':'ready';this.save(id,{graph,state,...(complete?{completedAt:o.completedAt??new Date().toISOString()}:{}),reason:!contextCurrent?'Business evidence or owner context changed; retained artifacts are historical and require a new governed plan or correction.':complete?'All declared current artifacts checked, locally published and read back. Commercial impact and independent semantic quality remain unmeasured.':blocked?'A task or dependency needs correction/reconciliation; completed results remain available.':o.reason});return this.view(id);}
 control(id:string,action:'pause'|'resume'|'cancel'){requireThat(['pause','resume','cancel'].includes(action),'OUTCOME_CONTROL');const o=this.get(id);requireThat(o.state!=='cancelled','OUTCOME_CANCELLED');for(const taskId of o.taskIds){const t=this.execution.portfolio.getTask(taskId);if(['completed','cancelled'].includes(t.status))continue;this.execution.portfolio.controlTask(taskId,action);}return this.save(id,{state:action==='pause'?'paused':action==='cancel'?'cancelled':'ready'});}
 correct(id:string,input:{nodeId:string;artifactHash:string;instruction:string;repairCalls:number;assisted:boolean}){
  requireThat(typeof input.assisted==='boolean','OUTCOME_CORRECTION_ASSISTANCE_REQUIRED');const o=this.get(id),correctionKey='outcome-correction-'+hash({id,nodeId:input.nodeId,artifactHash:input.artifactHash,instruction:input.instruction}).slice(0,30);if(o.corrections?.some((c:any)=>c.correctionKey===correctionKey))return o;const node=o.graph.find((n:any)=>n.id===input.nodeId);requireThat(node?.taskId&&Number.isSafeInteger(input.repairCalls)&&input.repairCalls>=3,'OUTCOME_CORRECTION_SCOPE');const affected=new Set<string>();for(const n of o.graph){if(n.id!==node.id&&n.dependsOn.some((d:string)=>d===node.id||affected.has(d)))affected.add(n.id);}const descendants=o.graph.filter((n:any)=>affected.has(n.id)),required=input.repairCalls+descendants.reduce((n:number,x:any)=>n+x.calls,0);requireThat(o.repairAllocated+required<=o.repairReserve,'OUTCOME_REPAIR_RESERVE_INSUFFICIENT');requireThat(!o.taskIds.some((taskId:string)=>this.execution.portfolio.getTask(taskId).lease),'OUTCOME_RUNNING_FINISH_BEFORE_CORRECTION');
  const correction=this.execution.correct({businessId:o.businessId,taskId:node.taskId,artifactHash:input.artifactHash,instruction:input.instruction,stableTaskId:correctionKey}),t=this.execution.portfolio.getTask(correction.id);this.store.transaction(()=>this.store.put('portfolio-task',t.id,{...t,resource:{...t.resource,modelCalls:input.repairCalls},inputs:{...t.inputs as any,outcomeId:id,outcomeNodeId:node.id,outcomeGeneration:node.generation+1}},t._version));for(const n of descendants)if(n.taskId)this.execution.portfolio.invalidateTask(n.taskId,'Upstream owner correction requires a fresh dependent revision under the existing outcome reserve');const observation=this.knowledge.correction(o.businessId,{id:correctionKey,taskId:t.id,artifactHash:input.artifactHash,instruction:input.instruction,assisted:input.assisted});if(!this.store.get('pilot-correction-link',correctionKey))this.store.transaction(()=>this.store.put('pilot-correction-link',correctionKey,{businessId:o.businessId,taskId:node.taskId,newTaskId:t.id,artifactHash:input.artifactHash,instruction:input.instruction,observationId:observation.id,timing:null,assisted:input.assisted,at:new Date().toISOString()},null));return this.save(id,{contextHash:this.intelligence.contextHash(o.businessId),state:'ready',repairAllocated:o.repairAllocated+required,taskIds:[...o.taskIds,t.id],graph:o.graph.map((n:any)=>n.id===node.id?{...n,taskId:t.id,generation:n.generation+1,calls:input.repairCalls,status:'planned'}:affected.has(n.id)?{...n,priorTaskId:n.taskId,taskId:null,generation:n.generation+1,status:'waiting_corrected_dependency'}:n),corrections:[...(o.corrections??[]),{...input,correctionKey,taskId:t.id,dependentIds:[...affected],reservedCalls:required,at:new Date().toISOString()}]});
 }
 view(id:string){const o=this.get(id);let observationCurrent=true;try{const context=boundObservationContext(this.store,o.businessId,o.observationIds??[]);observationCurrent=!o.observationContextHash||hash(context)===o.observationContextHash;}catch{observationCurrent=false;}const contextCurrent=observationCurrent&&(!o.contextHash||o.contextHash===this.intelligence.contextHash(o.businessId)),steps=this.rows('portfolio-step').filter(s=>o.taskIds.includes(s.taskId)&&s.kind==='model'),calls=(o.preparationAdmissions??0)+o.plannerAdmissions+steps.length,unknown=steps.filter(s=>s.status==='uncertain'||s.status==='reserved');return {...o,contextCurrent,state:!contextCurrent&&o.state==='completed'?'stale':o.state,calls:{admitted:calls,remaining:Math.max(0,o.maxCalls-calls),maximum:o.maxCalls,repairReserved:o.repairReserve,repairAllocated:o.repairAllocated,unknown:unknown.map(s=>s.id)},artifacts:o.graph.flatMap((n:any)=>n.taskId?[{nodeId:n.id,...this.execution.artifact(o.businessId,n.taskId),businessContextCurrent:contextCurrent}]:[]),providerExposure:'Read the separate signed accounting ledger; outcome call counts are not billing.',nextAction:o.state==='awaiting_plan'?'Obtain exact model authority or use the explicitly labeled offline demonstration':o.state==='completed'?'Review usefulness, record an observed outcome and revise priorities':o.state==='paused'?'Resume the preserved outcome':o.reason??o.state};}
}
