/** Finite coordinator over existing signed runners; no model, signing or credential port. */
import {existsSync,readFileSync,readdirSync,realpathSync,writeFileSync,lstatSync} from 'node:fs';
import {dirname,isAbsolute,join,relative,resolve,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import {hash,rawHash,requireThat,scopeKey} from '../contracts.ts';
import {StateStore} from '../state.ts';
import {verified} from '../experiment/config.ts';
import {PilotService} from '../pilot/service.ts';
import {loadAuthorizedPilot} from '../pilot/authorized.ts';
import {loadAuthorizedOutcomeJourney} from '../pilot/outcome-journey-authorized.ts';
import {loadAuthorizedOutcome} from '../pilot/outcome-authorized.ts';
import {taskDefinitionHash} from '../portfolio/live.ts';
import {backupPilot,restorePilot} from '../pilot/continuity.ts';

const KIND='adaptive-release-trial', SLOT='adaptive-release-stage', LOCK='adaptive-release-lock';
const arms=['strong-direct','preserved-midas-procedure','adaptive-midas'] as const;
export type TrialArm=typeof arms[number];
export type TrialStage={id:string;chunk:string;arm:TrialArm;phase:'development'|'flagship'|'transfer'|'nonreuse'|'ablation';runner:'pilot'|'outcome-journey'|'outcome';root:string;caseId:string;workerFactsHash:string;bindingHash:string;configurationHash:string;configurationReference:string;migrationDisclosure:string;maximumCalls:number;maximumMinor:number;lineageHash:string|null};
export type ReleaseTrialManifest={kind:'adaptive-release-trial-v1';id:string;mode:'live'|'fixture';implementationHash:string;caseManifestHash:string;caseProviderReference:string;rubricHash:string;assessorReference:string;custody:'externally-supplied-not-protected';orderPolicy:'predeclared-fixed';order:string[];maximumCalls:number;maximumMinor:number;concurrency:1;stages:TrialStage[];comparison:{kind:'common-controls'|'disclosed-product-comparison';allowedDifferences:string[]}};
export type TrialSnapshot={binding:any;configurationHash:string;workerFactsHash:string;conditions:Record<string,string>;ablation?:{factsHash:string;candidateIds:string[];backupHash:string};maximumCalls:number;maximumMinor:number;fresh:boolean;resumable:boolean;unknownEffect:boolean;completed:boolean;attemptIds:string[];metrics:any};
export type TrialAdapter={snapshot():TrialSnapshot;run():Promise<unknown>;resume():Promise<unknown>;close():void};
export type FixtureTrialFactory={kind:'fixture-only';open(stage:TrialStage):TrialAdapter};
const digest=(v:any)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
const positive=(v:any)=>Number.isSafeInteger(v)&&v>0;
const text=(v:any)=>typeof v==='string'&&v.trim().length>0;
function exact(value:any,keys:string[],code:string){requireThat(value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join(',')===[...keys].sort().join(','),code);}
const stageKeys=['id','chunk','arm','phase','runner','root','caseId','workerFactsHash','bindingHash','configurationHash','configurationReference','migrationDisclosure','maximumCalls','maximumMinor','lineageHash'];
const deferred=(s:TrialStage)=>[s.workerFactsHash,s.bindingHash,s.configurationHash,s.lineageHash].every(v=>v==='deferred');
export function trialImplementationHash(){const src=resolve(dirname(fileURLToPath(import.meta.url)),'..');const walk=(dir:string):any[]=>readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name)).flatMap(e=>e.isDirectory()?walk(join(dir,e.name)):/\.(ts|js|mjs|py|html|css)$/.test(e.name)?[{path:relative(src,join(dir,e.name)).split(sep).join('/'),content:readFileSync(join(dir,e.name),'utf8').replace(/\r\n/g,'\n')}]:[]);return hash([...walk(src),{path:'tools/adaptive-trial.mjs',content:readFileSync(resolve(src,'../../../tools/adaptive-trial.mjs'),'utf8').replace(/\r\n/g,'\n')}]);}
function distinctRoots(values:string[]){for(let i=0;i<values.length;i++)for(let j=i+1;j<values.length;j++){const r=relative(values[i],values[j]),back=relative(values[j],values[i]);requireThat(r!==''&&(r==='..'||r.startsWith('..'+sep)||isAbsolute(r))&&(back==='..'||back.startsWith('..'+sep)||isAbsolute(back)),'TRIAL_ROOTS_MUST_BE_DISJOINT');}}
function noLinks(path:string){for(let p=resolve(path);;p=dirname(p)){if(existsSync(p))requireThat(!lstatSync(p).isSymbolicLink(),'TRIAL_LINK_DENIED');if(p===dirname(p))break;}}
export function validateReleaseTrialManifest(m:ReleaseTrialManifest){
 exact(m,['kind','id','mode','implementationHash','caseManifestHash','caseProviderReference','rubricHash','assessorReference','custody','orderPolicy','order','maximumCalls','maximumMinor','concurrency','stages','comparison'],'TRIAL_MANIFEST_FIELDS');
 const comparison=(m as any).comparison;exact(comparison,['kind','allowedDifferences'],'TRIAL_COMPARISON_POLICY');requireThat(['common-controls','disclosed-product-comparison'].includes(comparison.kind)&&Array.isArray(comparison.allowedDifferences)&&new Set(comparison.allowedDifferences).size===comparison.allowedDifferences.length&&comparison.allowedDifferences.every((k:string)=>['workerFacts','model','evidence','tools','resources'].includes(k))&&(comparison.kind!=='common-controls'||comparison.allowedDifferences.length===0),'TRIAL_COMPARISON_POLICY');
 requireThat(m.kind==='adaptive-release-trial-v1'&&/^[a-z][a-z0-9-]{0,79}$/.test(m.id)&&['live','fixture'].includes(m.mode),'TRIAL_MANIFEST_REQUIRED');
 requireThat(digest(m.implementationHash)&&digest(m.caseManifestHash)&&digest(m.rubricHash)&&text(m.caseProviderReference)&&text(m.assessorReference)&&m.custody==='externally-supplied-not-protected','TRIAL_EXTERNAL_BINDINGS_REQUIRED');
 requireThat(m.orderPolicy==='predeclared-fixed'&&m.concurrency===1&&positive(m.maximumCalls)&&positive(m.maximumMinor),'TRIAL_LIMITS_REQUIRED');
 requireThat(Array.isArray(m.stages)&&m.stages.length>=3&&m.stages.length<=24&&new Set(m.stages.map(s=>s.id)).size===m.stages.length,'TRIAL_FINITE_STAGES_REQUIRED');
 for(const s of m.stages){exact(s,stageKeys,'TRIAL_STAGE_FIELDS');requireThat(/^[a-z][a-z0-9-]{0,79}$/.test(s.id)&&arms.includes(s.arm)&&['development','flagship','transfer','nonreuse','ablation'].includes(s.phase)&&['pilot','outcome-journey','outcome'].includes(s.runner)&&/^[a-z][a-z0-9-]{0,79}$/.test(s.chunk)&&isAbsolute(s.root)&&s.root===resolve(s.root),'TRIAL_STAGE_SCOPE');requireThat(text(s.caseId)&&([s.workerFactsHash,s.bindingHash,s.configurationHash].every(digest)&&(s.lineageHash===null||digest(s.lineageHash))||deferred(s))&&text(s.configurationReference)&&text(s.migrationDisclosure)&&positive(s.maximumCalls)&&positive(s.maximumMinor),'TRIAL_STAGE_BINDINGS_REQUIRED');}
 requireThat(Array.isArray(m.order)&&m.order.length===m.stages.length&&new Set(m.order).size===m.order.length&&m.order.every(id=>m.stages.some(s=>s.id===id)),'TRIAL_ORDER_REQUIRED');
 const chunks:string[]=[];for(const id of m.order){const chunk=m.stages.find(s=>s.id===id)!.chunk;if(chunks.at(-1)!==chunk){requireThat(!chunks.includes(chunk),'TRIAL_CHUNK_ORDER_REQUIRED');chunks.push(chunk);}}
 requireThat(m.stages.reduce((n,s)=>n+s.maximumCalls,0)<=m.maximumCalls&&m.stages.reduce((n,s)=>n+s.maximumMinor,0)<=m.maximumMinor,'TRIAL_AGGREGATE_EXCEEDED');
 const flagship=m.stages.filter(s=>s.phase==='flagship');requireThat(flagship.length===3&&arms.every(a=>flagship.some(s=>s.arm===a)),'TRIAL_THREE_LEGITIMATE_ARMS_REQUIRED');
 requireThat(flagship.every(deferred)||flagship.every(s=>!deferred(s)),'TRIAL_PARTIAL_FLAGSHIP_BINDING_DENIED');
 requireThat(new Set(flagship.map(s=>s.chunk)).size===1&&m.stages.filter(s=>s.chunk===flagship[0].chunk).length===3,'TRIAL_FLAGSHIP_SINGLE_CHUNK_REQUIRED');
 if(!flagship.every(deferred))requireThat(new Set(flagship.map(s=>s.configurationHash)).size===3,'TRIAL_BASELINE_COPIES_DENIED');
 requireThat(new Set(flagship.map(s=>s.caseId)).size===1&&new Set(flagship.map(s=>s.maximumCalls)).size===1&&new Set(flagship.map(s=>s.maximumMinor)).size===1,'TRIAL_FLAGSHIP_MATCHED_CEILINGS_REQUIRED');
 distinctRoots(m.stages.map(s=>resolve(s.root)));
 return {manifestHash:hash(m),calls:m.stages.reduce((n,s)=>n+s.maximumCalls,0),minor:m.stages.reduce((n,s)=>n+s.maximumMinor,0)};
}
function rows(store:StateStore,kind:string){return store.db.prepare('SELECT body FROM entities WHERE kind=? ORDER BY rowid').all(kind).map(r=>JSON.parse(String(r.body)));}
function workerFacts(task:any){const {authoritativeArtifactId,...inputs}=task.inputs??{};return {objective:task.objective,inputs,inputArtifacts:task.inputArtifacts??[]};}
function comparisonFacts(task:any){const facts=structuredClone(workerFacts(task));if(facts.inputs.adaptiveExecution){delete facts.inputs.adaptiveExecution.prompt;delete facts.inputs.pilotPlanIntentHash;}return facts;}
function quietHistory(store:StateStore){const operations=rows(store,'adaptive-tool-operation'),stops=rows(store,'adaptive-service-stop');requireThat(operations.every(r=>r.status==='completed'),'TRIAL_LINEAGE_UNKNOWN_OPERATION');requireThat(rows(store,'adaptive-task-execution-lease').every(r=>r.status==='released'),'TRIAL_LINEAGE_ACTIVE_EXECUTION_LEASE');requireThat(rows(store,'response-job').every(j=>!j.createDispatched||Boolean(j.terminal)),'TRIAL_LINEAGE_UNKNOWN_RESPONSE');for(const op of operations.filter(r=>r.action==='serviceStart')){const stop=stops.find(s=>s.businessId===op.binding.businessId&&s.taskId===op.binding.taskId&&s.serviceId===op.id);requireThat(op.serviceNotStarted===true||stop?.state?.quiescent===true&&stop?.state?.stopConfirmed===true,'TRIAL_LINEAGE_SERVICE_NOT_STOPPED');}}
/** Copies completed lineage with the existing V4 verifier. No old authority files or execution. */
export function prepareTrialLineage(input:{sourceRoot:string;targetRoot:string;backupRoot:string;businessId:string;arm:TrialArm}){
 requireThat([input.sourceRoot,input.targetRoot,input.backupRoot].every(isAbsolute)&&arms.includes(input.arm),'TRIAL_LINEAGE_SCOPE');distinctRoots([input.sourceRoot,input.targetRoot,input.backupRoot]);requireThat(!existsSync(input.targetRoot)&&!existsSync(input.backupRoot),'TRIAL_LINEAGE_NEW_ROOT_REQUIRED');
 noLinks(join(input.sourceRoot,'pilot.sqlite'));requireThat(lstatSync(join(input.sourceRoot,'pilot.sqlite')).nlink===1,'TRIAL_DATABASE_ALIAS_DENIED');noLinks(join(input.sourceRoot,'trial-stage-origin.json'));const origin=JSON.parse(readFileSync(join(input.sourceRoot,'trial-stage-origin.json'),'utf8'));requireThat(origin.arm===input.arm&&origin.status==='completed'&&digest(origin.manifestHash)&&digest(origin.receiptHash),'TRIAL_LINEAGE_SAME_ARM_REQUIRED');
 const source=new StateStore(join(input.sourceRoot,'pilot.sqlite'));let backup:any;let historicalTasks:any[];let candidateBindings:any[];let historicalAttempts:any[];
 try{const tasks=rows(source,'portfolio-task');requireThat(tasks.length>0&&tasks.every(t=>t.ventureId===input.businessId&&t.status==='completed'&&!t.lease),'TRIAL_LINEAGE_COMPLETED_BUSINESS_REQUIRED');quietHistory(source);requireThat(rows(source,'model-attempt').every(r=>Boolean(r.finishedAt)),'TRIAL_LINEAGE_PENDING_MODEL');historicalTasks=tasks.map(t=>({id:t.id,businessId:t.ventureId,definitionHash:taskDefinitionHash(t),recordHash:hash(t)}));historicalAttempts=source.db.prepare("SELECT key,body FROM entities WHERE kind='model-attempt'").all().map(r=>({key:String(r.key),recordHash:hash(JSON.parse(String(r.body)))}));candidateBindings=rows(source,'adaptive-skill-candidate').filter(c=>c.businessId===input.businessId).map(c=>({id:c.id,recordHash:hash(c),packageHash:c.packageHash??null}));backup=backupPilot(source,input.backupRoot,{sourceRoot:input.sourceRoot,quiescent:true,format:'v4'});requireThat(!backup.sidecars.some((s:any)=>s.path.endsWith('/command-active.json')),'TRIAL_LINEAGE_ACTIVE_COMMAND');}finally{source.close();}
 const restored=restorePilot(input.backupRoot,input.targetRoot,backup.sha256);requireThat(!existsSync(join(input.targetRoot,'portfolio.authorization.json'))&&!existsSync(join(input.targetRoot,'pilot.outcome.journey.authorization.json'))&&!existsSync(join(input.targetRoot,'auth')),'TRIAL_LINEAGE_AUTHORITY_COPIED');
 const payload={kind:'adaptive-trial-lineage-v1',sourceRoot:resolve(input.sourceRoot),targetRoot:resolve(input.targetRoot),businessId:input.businessId,arm:input.arm,origin,backupHash:backup.sha256,databaseHash:backup.database.sha256,historicalTasks:historicalTasks!,historicalAttempts:historicalAttempts!,candidateBindings:candidateBindings!,candidateIds:candidateBindings!.map(c=>c.id),sidecars:backup.sidecars,automaticExecution:false,authorizationCopied:false,createdAt:new Date().toISOString()};const lineageHash=hash(payload);writeFileSync(join(input.targetRoot,'trial-lineage.json'),JSON.stringify({payload,lineageHash},null,2)+'\n',{flag:'wx'});return {lineageHash,payload,restored,providerRequests:0};
}
function lineageFor(stage:TrialStage,allTasks:any[],selected:any[],store:StateStore){
 if(stage.lineageHash===null||stage.lineageHash===undefined){requireThat(allTasks.length===selected.length,'TRIAL_EXACT_TASK_SET_REQUIRED');return null;}
 requireThat(digest(stage.lineageHash),'TRIAL_LINEAGE_BINDING_REQUIRED');const receipt=JSON.parse(readFileSync(join(stage.root,'trial-lineage.json'),'utf8')),p=receipt.payload;requireThat(hash(p)===stage.lineageHash&&receipt.lineageHash===stage.lineageHash&&p.kind==='adaptive-trial-lineage-v1'&&p.targetRoot===stage.root&&p.arm===stage.arm&&p.origin.arm===stage.arm&&p.authorizationCopied===false&&p.automaticExecution===false&&digest(p.backupHash),'TRIAL_LINEAGE_BINDING_REQUIRED');requireThat(selected.every(t=>t.ventureId===p.businessId)&&Array.isArray(p.historicalTasks),'TRIAL_LINEAGE_BUSINESS_MISMATCH');
 const history=allTasks.filter(t=>!selected.some(s=>s.id===t.id));requireThat(history.length===p.historicalTasks.length&&history.every(t=>{const old=p.historicalTasks.find((h:any)=>h.id===t.id);return old&&t.status==='completed'&&!t.lease&&t.ventureId===p.businessId&&taskDefinitionHash(t)===old.definitionHash&&hash(t)===old.recordHash;}),'TRIAL_LINEAGE_TASK_CHANGED');
 requireThat(Array.isArray(p.candidateBindings)&&p.candidateBindings.every((c:any)=>{const row=rows(store,'adaptive-skill-candidate').find(r=>r.id===c.id);return row&&hash(row)===c.recordHash;}),'TRIAL_LINEAGE_CANDIDATE_CHANGED');for(const file of p.sidecars??[]){const path=resolve(stage.root,file.path),rel=relative(stage.root,path);requireThat(!isAbsolute(rel)&&rel!== '..'&&!rel.startsWith('..'+sep),'TRIAL_LINEAGE_FILE_CHANGED');noLinks(path);requireThat(rawHash(readFileSync(path))===file.sha256,'TRIAL_LINEAGE_FILE_CHANGED');}return {lineageHash:stage.lineageHash,backupHash:p.backupHash,origin:p.origin,historicalTaskHashes:p.historicalTasks,candidateBindings:p.candidateBindings,historicalAttempts:p.historicalAttempts??[]};
}
function makeProductionAdapter(stage:TrialStage,testing?:{transport:typeof fetch}):TrialAdapter{
 requireThat(existsSync(join(stage.root,'pilot.sqlite')),'TRIAL_PREPARED_ROOT_REQUIRED');
 noLinks(join(stage.root,'pilot.sqlite'));requireThat(lstatSync(join(stage.root,'pilot.sqlite')).nlink===1,'TRIAL_DATABASE_ALIAS_DENIED');
 const service=new PilotService(stage.root,{publicReader:{kind:'public'}});
 try{
 const isPilot=stage.runner==='pilot',services={outcomes:service.operatingOutcomes,intelligence:service.intelligence,discovery:service.discovery};
 const pub=readFileSync(join(stage.root,'auth','portfolio-owner.pub'),'utf8');
 const outcomeOnly=stage.runner==='outcome';
 const testOptions=testing&&!isPilot?{testing:{envelope:JSON.parse(readFileSync(join(stage.root,outcomeOnly?'pilot.outcome.authorization.json':'pilot.outcome.journey.authorization.json'),'utf8')),trustedPublicKey:pub,transport:testing.transport}}:{};
 const runner:any=isPilot?loadAuthorizedPilot(service.execution,stage.root,testing?{execution:{kind:'mock',transport:testing.transport}}:{}):outcomeOnly?loadAuthorizedOutcome(services,stage.root,testOptions):loadAuthorizedOutcomeJourney(services,stage.root,testOptions);
 const g=runner.authorization;
 const b=isPilot?null:(outcomeOnly?g.outcome:g.journey);
 const operating:any=isPilot?verified(JSON.parse(readFileSync(join(stage.root,'portfolio.authorization.json'),'utf8')).operatingEnvelope,pub):g;
 requireThat(g.mode===(testing?'mock':'live')&&operating.mode===g.mode&&operating.providerConcurrency===1&&operating.retries===0&&!operating.limits.carryIn?.length,'TRIAL_CURRENT_LIVE_AUTHORITY_REQUIRED');
 const snapshot=():TrialSnapshot=>{
  const tasks=isPilot?g.tasks.map((a:any)=>service.execution.portfolio.getTask(a.id)):[];
  const taskBindings=tasks.map((task:any)=>({id:task.id,businessId:task.ventureId,definitionHash:taskDefinitionHash(task),procedureHash:g.pilotBinding.taskProcedures.find((p:any)=>p.taskId===task.id)?.procedureHash,toolsHash:hash(task.allowedTools),evidenceHash:hash((task.inputs as any).sourceBindings),resourcesHash:hash(task.resource),workerFactsHash:hash(workerFacts(task))}));
  for(const t of taskBindings)requireThat(digest(t.procedureHash),'TRIAL_PREPARED_PROCEDURE_REQUIRED');
  const allTasks=rows(service.store,'portfolio-task');
  const activeTasks=isPilot?tasks:allTasks.filter(t=>t.inputs?.outcomeId===b.outcomeId);
  const lineage=lineageFor(stage,allTasks,activeTasks,service.store);
  requireThat(!lineage||testing||lineage.origin.provenance==='authorized_existing_runners','TRIAL_FIXTURE_LINEAGE_CANNOT_BECOME_LIVE_EVIDENCE');
  const route={model:operating.route.model,reasoningEffort:operating.route.reasoningEffort,serviceTier:operating.route.serviceTier,inputTokenCeiling:operating.route.inputTokenCeiling,maxOutputTokens:operating.route.maxOutputTokens};
  const configurationHash=hash({route,procedures:isPilot?taskBindings.map((t:any)=>t.procedureHash):b.profiles.map((p:any)=>p.procedureHash),tools:isPilot?taskBindings.map((t:any)=>t.toolsHash):b.profiles.map((p:any)=>hash(p.allowedTools)),resources:isPilot?taskBindings.map((t:any)=>t.resourcesHash):{calls:b.maximumCalls,profiles:b.profiles}});
  const binding={runner:stage.runner,authorityHash:hash(g),operatingHash:hash(operating),taskBindings,lineage,journey:isPilot?null:{outcomeId:b.outcomeId,businessId:b.businessId,bindingHash:hash(b)},route};
  const prefix=scopeKey(operating.accountScope)+'/';
  const otherAttempts=service.store.db.prepare("SELECT key,body FROM entities WHERE kind='model-attempt'").all().filter(r=>!String(r.key).startsWith(prefix));requireThat(lineage?otherAttempts.length===lineage.historicalAttempts.length&&otherAttempts.every(r=>lineage.historicalAttempts.some((a:any)=>a.key===r.key&&a.recordHash===hash(JSON.parse(String(r.body))))):otherAttempts.length===0,'TRIAL_UNBOUND_HISTORICAL_ATTEMPT');
  const attempts=service.store.db.prepare("SELECT key,body FROM entities WHERE kind='model-attempt' AND substr(key,1,?)=?").all(prefix.length,prefix).map(r=>({key:String(r.key),...JSON.parse(String(r.body))}));
  const commands=rows(service.store,'adaptive-tool-operation');
  const serviceStops=rows(service.store,'adaptive-service-stop');
  const unresolvedServices=commands.filter(c=>c.action==='serviceStart').filter(c=>{const stopped=serviceStops.find(s=>s.businessId===c.binding.businessId&&s.taskId===c.binding.taskId&&s.serviceId===c.id);const notStarted=c.status==='completed'&&c.serviceNotStarted===true;return !notStarted&&!(stopped?.state?.quiescent===true&&stopped?.state?.stopConfirmed===true);});
  const unknownEffect=attempts.some(a=>{const j=service.store.get('response-job',a.key);return j?.createDispatched&&!j.responseId&&!j.terminal;})||rows(service.store,'adaptive-task-execution-lease').some(r=>r.status!=='released')||commands.some(c=>['running','pending','uncertain'].includes(c.status))||unresolvedServices.length>0;
  const outcome=isPilot?null:service.operatingOutcomes.get(b.outcomeId);
  const completed=isPilot?tasks.every((t:any)=>t.status==='completed'):(outcome.state==='completed'||outcomeOnly&&outcome.state==='rejected');
  const fresh=attempts.length===0&&(isPilot?tasks.every((t:any)=>t.status==='queued'&&t.attempts===0&&!t.lease):outcome.state==='awaiting_plan'&&activeTasks.length===0);
  const terminalFailure=isPilot?tasks.some((t:any)=>['failed','cancelled'].includes(t.status)):['cancelled','rejected'].includes(outcome.state);
  const factsHash=isPilot?hash(taskBindings.map((t:any)=>t.workerFactsHash)):(outcomeOnly?b.planner.requestHash:b.initialRequest.requestHash);
  let ablation:TrialSnapshot['ablation'];if(stage.phase==='ablation'){const policy=tasks[0]?.inputs?.adaptiveExecution?.memoryPolicy;requireThat(isPilot&&tasks.length===1&&lineage&&policy?.kind==='retained-candidates-v1'&&policy.candidateIds.every((id:string)=>lineage.candidateBindings.some((c:any)=>c.id===id)),'TRIAL_ABLATION_MEMORY_BINDING_REQUIRED');const facts=structuredClone(workerFacts(tasks[0]));delete facts.inputs.adaptiveExecution.memoryPolicy;delete facts.inputs.pilotPlanIntentHash;ablation={factsHash:hash(facts),candidateIds:policy.candidateIds,backupHash:lineage.backupHash};}
  const conditions={workerFacts:isPilot?hash(tasks.map(comparisonFacts)):factsHash,model:hash(route),evidence:isPilot?hash(taskBindings.map((t:any)=>t.evidenceHash)):hash(b.initialSources??b.sourceBindings),tools:isPilot?hash(taskBindings.map((t:any)=>t.toolsHash)):hash(b.profiles.map((p:any)=>p.allowedTools)),resources:isPilot?hash(taskBindings.map((t:any)=>t.resourcesHash)):hash({calls:b.maximumCalls,repair:b.repairReserve})};
  return {binding,configurationHash,workerFactsHash:factsHash,conditions,...(ablation?{ablation}:{}),maximumCalls:operating.businesses.reduce((n:number,b:any)=>n+b.maxCalls,0),maximumMinor:operating.limits.totalMinor,fresh,resumable:attempts.length>0&&!unknownEffect&&!terminalFailure,unknownEffect,completed,attemptIds:attempts.map(a=>a.id),metrics:{accounting:runner.totals(),taskStates:isPilot?tasks.map((t:any)=>({id:t.id,status:t.status})):allTasks.map((t:any)=>({id:t.id,status:t.status})),artifactHashes:rows(service.store,'portfolio-artifact').map(a=>({id:a.id,sha256:a.sha256})),unresolvedServiceIds:unresolvedServices.map(s=>s.id),episodeStates:rows(service.store,'adaptive-capability-episode').map(e=>({id:e.id,state:e.state})),reuseOutcomes:rows(service.store,'adaptive-skill-reuse-outcome').map(r=>({candidateId:r.candidateId,passed:r.passed,evidenceRefs:r.evidenceRefs,provenance:r.provenance,qualification:'unqualified'})),independentSemanticAcceptance:null,customerOutcome:null}};
 };
 const runOutcome=async()=>{const old=service.operatingOutcomes.get(b.outcomeId);if(!old.plan)await runner.plan();const current=service.operatingOutcomes.get(b.outcomeId);return current.plan?.decision==='prepare'?runner.run():current;};
 return {snapshot,run:()=>isPilot?runner.runAll():outcomeOnly?runOutcome():runner.run(),resume:()=>isPilot?runner.runAll():outcomeOnly?runOutcome():runner.resume(),close:()=>service.store.close()};
 }catch(error){service.store.close();throw error;}
}
/** This observation exports hashes and finite limits only. It cannot supply a model or authorize work. */
export function inspectTrialStage(stage:TrialStage){const adapter=makeProductionAdapter(stage);try{return adapter.snapshot();}finally{adapter.close();}}
/** Test-only bridge: same adapter and existing signed factories, forced mock mode. */
export function createSignedMockTrialFactory(transport:typeof fetch):FixtureTrialFactory{return {kind:'fixture-only',open:stage=>makeProductionAdapter(stage,{transport})};}
function alive(pid:number|null){if(!pid)return false;try{process.kill(pid,0);return true;}catch(error){return (error as any).code==='EPERM';}}
export class ReleaseTrial{
 readonly root:string;readonly store:StateStore;readonly manifest:ReleaseTrialManifest;readonly manifestHash:string;readonly testing?:FixtureTrialFactory;
 constructor(root:string,manifest:ReleaseTrialManifest,options:{testing?:FixtureTrialFactory}={}){
  requireThat(isAbsolute(root),'TRIAL_ROOT_ABSOLUTE_REQUIRED');this.root=resolve(root);const checked=validateReleaseTrialManifest(manifest);
  requireThat(manifest.implementationHash===trialImplementationHash(),'TRIAL_CODE_CHANGED');
  requireThat(options.testing?options.testing.kind==='fixture-only'&&manifest.mode==='fixture':manifest.mode==='live','TRIAL_FIXTURE_CANNOT_AUTHORIZE_LIVE');
  distinctRoots([this.root,...manifest.stages.map(s=>s.root)]);
  noLinks(join(this.root,'trial.sqlite'));if(existsSync(join(this.root,'trial.sqlite')))requireThat(lstatSync(join(this.root,'trial.sqlite')).nlink===1,'TRIAL_DATABASE_ALIAS_DENIED');
  this.manifest=structuredClone(manifest);this.manifestHash=checked.manifestHash;this.testing=options.testing;this.store=new StateStore(join(this.root,'trial.sqlite'));
  try{this.store.transaction(()=>{const old=this.store.get(KIND,'manifest');requireThat(!old||old.manifestHash===this.manifestHash,'TRIAL_MANIFEST_CHANGED');if(!old)this.store.put(KIND,'manifest',{manifestHash:this.manifestHash,manifest:this.manifest,provenance:options.testing?'fixture':'authorized_existing_runners',createdAt:new Date().toISOString()},null);});}catch(e){this.store.close();throw e;}
 }
 close(){this.store.close();}
 private open(stage:TrialStage){return this.testing?this.testing.open(stage):makeProductionAdapter(stage);}
 private effectiveStage(stage:TrialStage):TrialStage{return deferred(stage)?this.store.get('adaptive-release-chunk',stage.chunk)?.stages.find((s:TrialStage)=>s.id===stage.id)??stage:stage;}
 /** Bind only a whole predeclared future chunk, against its newly signed factories. */
 bindChunk(stages:TrialStage[]){
  this.current();requireThat(Array.isArray(stages)&&stages.length>0,'TRIAL_CHUNK_REQUIRED');const chunk=stages[0].chunk,planned=this.manifest.stages.filter(s=>s.chunk===chunk);requireThat(planned.length===stages.length&&planned.every(deferred)&&new Set(stages.map(s=>s.id)).size===stages.length&&stages.every(s=>s.chunk===chunk),'TRIAL_EXACT_DEFERRED_CHUNK_REQUIRED');
  const fixed=(s:TrialStage)=>{const {workerFactsHash,bindingHash,configurationHash,lineageHash,configurationReference,migrationDisclosure,...rest}=s;return rest;};for(const s of stages){const plan=planned.find(p=>p.id===s.id);requireThat(plan&&hash(fixed(plan))===hash(fixed(s))&&!deferred(s),'TRIAL_CHUNK_SCOPE_CHANGED');}
  const first=Math.min(...planned.map(s=>this.manifest.order.indexOf(s.id)));requireThat(this.manifest.order.slice(0,first).every(id=>this.store.get(SLOT,id)?.status==='completed'),'TRIAL_PREDECLARED_ORDER_REQUIRED');
  validateReleaseTrialManifest({...this.manifest,stages:this.manifest.stages.map(s=>stages.find(x=>x.id===s.id)??s)});
  for(const s of stages){const adapter=this.open(s);try{const observed=adapter.snapshot();this.validateSnapshot(s,observed);requireThat(observed.fresh&&!observed.unknownEffect,'TRIAL_FRESH_ROOT_REQUIRED');}finally{adapter.close();}}
  const value={chunk,manifestHash:this.manifestHash,stages:structuredClone(stages),bindingHash:hash(stages),authorization:'Existing signed per-root grants only; this binding creates no authority.'};this.store.transaction(()=>{const old=this.store.get('adaptive-release-chunk',chunk);requireThat(!old||old.bindingHash===value.bindingHash,'TRIAL_CHUNK_IMMUTABLE');if(!old)this.store.put('adaptive-release-chunk',chunk,value,null);});return value;
 }
 private validateSnapshot(stage:TrialStage,s:TrialSnapshot){
  exact(s.conditions,['workerFacts','model','evidence','tools','resources'],'TRIAL_OBSERVED_CONTROLS_REQUIRED');requireThat(Object.values(s.conditions).every(digest),'TRIAL_OBSERVED_CONTROLS_REQUIRED');
  requireThat(hash(s.binding)===stage.bindingHash&&s.configurationHash===stage.configurationHash&&s.workerFactsHash===stage.workerFactsHash,'TRIAL_STAGE_BINDING_CHANGED');
  requireThat(s.maximumCalls===stage.maximumCalls&&s.maximumMinor===stage.maximumMinor,'TRIAL_SIGNED_LIMIT_MISMATCH');
 }
 private current(){requireThat(trialImplementationHash()===this.manifest.implementationHash,'TRIAL_CODE_CHANGED');requireThat(this.store.get(KIND,'manifest')?.manifestHash===this.manifestHash,'TRIAL_MANIFEST_CHANGED');}
 inspect(){this.current();return {manifestHash:this.manifestHash,provenance:this.testing?'fixture':'authorized_existing_runners',stages:this.manifest.order.map(id=>this.store.get(SLOT,id)??{id,status:'not_started'}),lease:this.store.get(LOCK,'global')??null,independentSemanticAcceptance:null,protectedCustody:false,providerDispatch:'Delegated only to the existing signed runners; actual attempts and accounting are in each stage receipt.'};}
 preflight(){
  this.current();const snapshots:any[]=[];const failures:any[]=[];const roots:string[]=[];const pendingBindings:string[]=[];const next=this.manifest.order.find(id=>this.store.get(SLOT,id)?.status!=='completed'),nextChunk=this.manifest.stages.find(s=>s.id===next)?.chunk;
  for(const planned of this.manifest.stages){const stage=this.effectiveStage(planned);if(deferred(stage)){pendingBindings.push(stage.id);if(stage.chunk===nextChunk)failures.push({id:stage.id,code:'TRIAL_CHUNK_BINDING_REQUIRED'});continue;}let adapter:TrialAdapter|undefined;try{const prior=this.store.get(SLOT,stage.id);if(!this.testing){requireThat(existsSync(stage.root),'TRIAL_PREPARED_ROOT_REQUIRED');roots.push(realpathSync(stage.root));}const s:TrialSnapshot=prior?.status==='completed'?prior.snapshot:(adapter=this.open(stage)).snapshot();requireThat(s,'TRIAL_PERSISTED_SNAPSHOT_REQUIRED');this.validateSnapshot(stage,s);requireThat(prior||s.fresh&&!s.unknownEffect,'TRIAL_FRESH_ROOT_REQUIRED');snapshots.push({id:stage.id,chunk:stage.chunk,authorityHash:s.binding.authorityHash,conditions:s.conditions,ablation:s.ablation??null,attemptIds:s.attemptIds,maximumCalls:s.maximumCalls,maximumMinor:s.maximumMinor});}catch(e){failures.push({id:stage.id,code:(e as any).code??(e as Error).message});}finally{adapter?.close();}}
  if(!this.testing)try{distinctRoots([realpathSync(this.root),...roots]);}catch(e){failures.push({id:null,code:(e as any).code??(e as Error).message});}
  const authorities=snapshots.map(s=>s.authorityHash);if(new Set(authorities).size!==authorities.length)failures.push({id:null,code:'TRIAL_AUTHORITY_REUSE_DENIED'});
  const flagship=snapshots.filter(s=>this.manifest.stages.find(t=>t.id===s.id)?.phase==='flagship');const observedDifferences=['workerFacts','model','evidence','tools','resources'].filter(k=>new Set(flagship.map(s=>s.conditions[k])).size>1);for(const key of observedDifferences)if(!this.manifest.comparison.allowedDifferences.includes(key))failures.push({id:null,code:'TRIAL_UNDECLARED_CONTROL_DIFFERENCE',field:key});
  const matchedAblation=(group:any[])=>group.length===2&&group.every(s=>s.ablation&&this.manifest.stages.find(t=>t.id===s.id)?.phase==='ablation')&&new Set(group.map(s=>s.ablation.factsHash)).size===1&&new Set(group.map(s=>s.ablation.backupHash)).size===1&&group.filter(s=>s.ablation.candidateIds.length===0).length===1&&group.filter(s=>s.ablation.candidateIds.length>0).length===1&&['model','evidence','tools','resources'].every(k=>new Set(group.map(s=>s.conditions[k])).size===1);
  for(const chunk of new Set(snapshots.map(s=>s.chunk))){const group=snapshots.filter(s=>s.chunk===chunk);if(group.length<2)continue;for(const key of ['workerFacts','model','evidence','tools','resources'])if(new Set(group.map(s=>s.conditions[key])).size>1&&!this.manifest.comparison.allowedDifferences.includes(key)&&!(key==='workerFacts'&&matchedAblation(group)))failures.push({id:chunk,code:'TRIAL_UNDECLARED_CONTROL_DIFFERENCE',field:key});}
  for(const chunk of new Set(this.manifest.stages.filter(s=>s.phase==='ablation').map(s=>s.chunk))){const group=snapshots.filter(s=>s.chunk===chunk);if(!group.length)continue;if(!matchedAblation(group))failures.push({id:chunk,code:'TRIAL_ABLATION_MATCHING_REQUIRED'});}
  return {ready:failures.length===0,manifestHash:this.manifestHash,nextChunk,pendingBindings,failures,snapshots,observedDifferences,comparisonInterpretation:observedDifferences.length?'declared_product_confounds_no_orchestration_attribution':'matched_observed_hashes_not_semantic_certification',provenance:this.testing?'fixture':'signed_configuration_not_semantic_verification'};
 }
 async run(stageId:string,mode:'run'|'resume'='run'){
  this.current();const planned=this.manifest.stages.find(s=>s.id===stageId);requireThat(planned,'TRIAL_STAGE_UNKNOWN');const stage=this.effectiveStage(planned!);const old=this.store.get(SLOT,stageId);if(old?.status==='completed')return old;
  const check=this.preflight();requireThat(check.ready,'TRIAL_PREFLIGHT_BLOCKED');
  const index=this.manifest.order.indexOf(stageId);requireThat(this.manifest.order.slice(0,index).every(id=>this.store.get(SLOT,id)?.status==='completed'),'TRIAL_PREDECLARED_ORDER_REQUIRED');
  requireThat(mode==='resume'?Boolean(old):!old,'TRIAL_USE_EXISTING_STAGE_RECOVERY');
  const adapter=this.open(stage!);let claimed=false;
  try{
   const before=adapter.snapshot();this.validateSnapshot(stage!,before);requireThat(!before.unknownEffect,'TRIAL_UNKNOWN_EFFECT_NO_REPLAY');requireThat(old?before.resumable:before.fresh,'TRIAL_SAME_ATTEMPT_RECOVERY_REQUIRED');
   this.store.transaction(()=>{const lease=this.store.get(LOCK,'global');requireThat(!lease?.active||lease.stageId===stageId&&!alive(lease.pid),'TRIAL_CONCURRENCY_OR_UNCERTAINTY');const current=this.store.get(SLOT,stageId);requireThat(old?current?.attemptId===old.attemptId:!current,'TRIAL_STAGE_CONCURRENT');const attemptId=old?.attemptId??'trial-'+hash({manifestHash:this.manifestHash,stageId}).slice(0,32);const value={id:stageId,manifestHash:this.manifestHash,attemptId,status:'running',startedAt:old?.startedAt??new Date().toISOString(),resumes:(old?.resumes??0)+(old?1:0),beforeAttemptIds:old?.beforeAttemptIds??before.attemptIds,provenance:this.testing?'fixture':'authorized_existing_runners',independentSemanticAcceptance:null};this.store.put(SLOT,stageId,value,current?._version??null);this.store.put(LOCK,'global',{active:true,stageId,attemptId,pid:process.pid,owner:randomUUID()},lease?._version??null);});claimed=true;
   await (old?adapter.resume():adapter.run());
   const after=adapter.snapshot();this.validateSnapshot(stage!,after);
   const status=after.completed&&!after.unknownEffect?'completed':'blocked';
   if(status==='completed'){const origin={arm:stage!.arm,stageId,manifestHash:this.manifestHash,status,receiptHash:hash({manifestHash:this.manifestHash,stageId,bindingHash:stage!.bindingHash,attemptIds:after.attemptIds}),provenance:this.testing?'fixture':'authorized_existing_runners'};const path=join(stage!.root,'trial-stage-origin.json');if(existsSync(path))requireThat(hash(JSON.parse(readFileSync(path,'utf8')))===hash(origin),'TRIAL_ROOT_ORIGIN_CHANGED');else writeFileSync(path,JSON.stringify(origin,null,2)+'\n',{flag:'wx'});}
   return this.store.transaction(()=>{const current=this.store.get(SLOT,stageId),lease=this.store.get(LOCK,'global');const value={...current,status,finishedAt:new Date().toISOString(),attemptIds:after.attemptIds,metrics:after.metrics,snapshot:after,unknownEffect:after.unknownEffect,independentSemanticAcceptance:null};this.store.put(SLOT,stageId,value,current._version);this.store.put(LOCK,'global',{...lease,active:status!=='completed',pid:null},lease._version);return value;});
  }catch(e){if(claimed)this.store.transaction(()=>{const current=this.store.get(SLOT,stageId),lease=this.store.get(LOCK,'global');this.store.put(SLOT,stageId,{...current,status:'uncertain',code:(e as any).code??(e as Error).message,independentSemanticAcceptance:null},current._version);this.store.put(LOCK,'global',{...lease,active:true,pid:null},lease._version);});throw e;}finally{adapter.close();}
 }
}
export function releaseTrialTemplate(){return {status:'template_requires_independent_job_bindings_and_current_signed_runners',notExecutable:true,providerRequests:0,manifest:{kind:'adaptive-release-trial-v1',id:'release-trial',mode:'live',implementationHash:trialImplementationHash(),caseManifestHash:null,caseProviderReference:null,rubricHash:null,assessorReference:null,custody:'externally-supplied-not-protected',orderPolicy:'predeclared-fixed',order:['direct','current','adaptive'],maximumCalls:60,maximumMinor:12600,concurrency:1,comparison:{kind:'disclosed-product-comparison',allowedDifferences:['workerFacts','tools']},stages:arms.map((arm,i)=>({id:['direct','current','adaptive'][i],chunk:'flagship',lineageHash:null,arm,phase:'flagship',runner:'pilot',root:null,caseId:null,workerFactsHash:null,bindingHash:null,configurationHash:null,configurationReference:null,migrationDisclosure:null,maximumCalls:20,maximumMinor:4200}))},instructions:'Prepare legitimate distinct configurations and independently supplied tasks first. Observe each current signed runner with inspect-stage; bind its actual snapshot. No template field is a grant, independent assessment or protected-case claim.'};}
