import {createServer} from 'node:http';
import {hash,requireThat} from '../contracts.ts';
import {renderPreview,previewCSP,launchCheckBrowser,validatePreviewRequest} from './preview.ts';
import type {PreviewBinding} from './preview.ts';
import type {SourceFile,Check} from './products.ts';
import {emptyBusinessSiteState} from './business-site-state.ts';
/** Fixed browser acceptance belongs to this replaceable job profile, never the worker source. */
export async function checkBusinessSite(options:PreviewBinding&{files:SourceFile[];inputs:any;launchBrowser?:()=>Promise<any>;stateHandler?:(body:any)=>any;saveScreenshot?:(name:string,data:Buffer)=>unknown}):Promise<Check[]>{
 const checks:Check[]=[],views:any[]=[],errors:string[]=[];let state=emptyBusinessSiteState(),version=0,browser:any,page:any,context:any,phase='startup',blocked=0;
 const binding={ventureId:options.ventureId,taskId:options.taskId,manifestHash:options.manifestHash};
 const handler=options.stateHandler??((body:any)=>{if(body.operation==='write'){requireThat(body.expectedVersion===version,'PREVIEW_STATE_STALE');state=structuredClone(body.state);version++;}return {state,version};});
 const read=()=>handler({...binding,operation:'read'});
 const record=(id:string,passed:boolean,summary:string,evidence?:unknown,required=true)=>checks.push({id,passed,required,summary,...(evidence?{evidence}:{})});
 record('software.handoff',Buffer.byteLength(JSON.stringify(options.files))<=24000,'Complete source fits the worker-visible 24000-byte serialized handoff.');
 const server=createServer(async(req,res)=>{try{if(req.method==='GET'&&req.url==='/'){res.writeHead(200,{'content-type':'text/html','content-security-policy':previewCSP}).end(renderPreview({...binding,files:options.files,executionProfile:'business-site-v1',stateEndpoint:'/state'}));return;}if(req.method==='POST'&&req.url==='/state'){let raw='';for await(const c of req){raw+=c;requireThat(raw.length<=300000,'REQUEST_TOO_LARGE');}const body=JSON.parse(raw);validatePreviewRequest(body,binding,'business-site-v1');res.writeHead(200,{'content-type':'application/json'}).end(JSON.stringify(handler(body)));return;}res.writeHead(404).end();}catch(e){res.writeHead(400,{'content-type':'application/json'}).end(JSON.stringify({error:(e as Error).message}));}});
 await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+(server.address() as any).port;
 const frame=()=>page.frameLocator('#product-frame');
 const snapshot=async(name:string)=>{try{const f=page.frames().find((f:any)=>f.parentFrame()===page.mainFrame());const dom=await f.evaluate(()=>({title:document.querySelector('h1')?.textContent??'',text:document.body.innerText.slice(0,1800),viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,controls:Array.from(document.querySelectorAll('input,textarea,button')).filter(el=>el.getBoundingClientRect().height>0).map((el:any)=>{const r=el.getBoundingClientRect();return {id:el.id,tag:el.tagName.toLowerCase(),text:(el.labels?.[0]?.textContent||el.textContent||el.getAttribute('aria-label')||'').trim(),box:{x:r.x,y:r.y,width:r.width,height:r.height}};})}));views.push({name,...dom,screenshot:options.saveScreenshot?.(name,await page.screenshot({type:'png'}))??null});}catch(e){views.push({name,error:(e as Error).message});}};
 async function open(){context=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'allow',acceptDownloads:false});await context.routeWebSocket('**/*',(ws:any)=>{blocked++;ws.close();});await context.route('**/*',async(route:any)=>{const r=route.request(),u=new URL(r.url());const allowed=page&&r.frame()===page.mainFrame()&&u.origin===origin&&(u.pathname==='/'&&r.method()==='GET'&&r.isNavigationRequest()||u.pathname==='/state'&&r.method()==='POST'&&!r.isNavigationRequest());if(allowed)await route.continue();else{blocked++;await route.abort();}});page=await context.newPage();page.setDefaultTimeout(3000);page.on('pageerror',(e:Error)=>errors.push(e.message));page.on('dialog',(d:any)=>void d.dismiss());context.on('page',(p:any)=>{if(p!==page)void p.close();});await page.goto(origin);await frame().locator('[data-ready="true"]').waitFor();}
 try{
  browser=await(options.launchBrowser??launchCheckBrowser)();await open();await snapshot('initial-desktop');
  record('software.sandbox',await page.locator('#product-frame').getAttribute('sandbox')==='allow-scripts allow-forms','Source executes in an opaque sandbox, without host or network access.');
  const sources=options.inputs?.evidence??[];let supported=sources.length>0&&(await frame().locator('h1').innerText()).includes(options.inputs.companyName);
  for(const source of sources){const el=frame().locator('[data-source-id]').filter({hasText:source.quote});supported&&=await el.count()>0&&await el.first().getAttribute('data-source-id')===source.sourceId;}
  record('site.source-binding',supported,'Company identity and every declared exact company excerpt appear in the actual rendered page.',{sourceIds:sources.map((s:any)=>s.sourceId)});
  record('site.empty',read().state.inquiries.length===0&&await frame().locator('#empty-state').isVisible()&&/local|not sent|does not send/i.test(await frame().locator('body').innerText()),'Initial state is empty with useful guidance and an explicit local-only boundary.');
  phase='invalid input';let invalid=true;const fieldValues=(options.inputs.intakeFields??[]).map((f:any)=>({fieldId:f.id,value:'Acceptance detail for '+f.label}));for(const detail of fieldValues)await frame().locator('[data-intake-field="'+detail.fieldId+'"]').fill(detail.value);for(const [name,need] of [['','Inspect a chair'],['Acceptance visitor','']]){await frame().locator('#name').fill(name);await frame().locator('#need').fill(need);const before=hash(read());await frame().locator('#save').click();await page.waitForTimeout(50);invalid&&=hash(read())===before&&(await frame().locator('#notice').innerText()).trim().length>=8;}await frame().locator('#name').fill('Acceptance visitor');await frame().locator('#need').fill('Inspection request');for(const detail of fieldValues){const el=frame().locator('[data-intake-field="'+detail.fieldId+'"]');await el.fill('');const before=hash(read());await frame().locator('#save').click();await page.waitForTimeout(30);invalid&&=hash(read())===before;await el.fill(detail.value);}record('site.invalid-input',invalid,'Missing name, requirement or any configured intake field gives feedback without persisting an incomplete inquiry.');
  phase='save/edit';await frame().locator('#name').fill('Acceptance visitor');await frame().locator('#need').fill('Chair inspection; dimensions and photos are available.');await frame().locator('#save').click();await frame().locator('#inquiries article').waitFor();const id=read().state.inquiries[0]?.id;await frame().locator('[data-open]').first().click();await frame().locator('#need').fill('Chair inspection; request a scope review, not an approved price.');await frame().locator('#save').click();await page.waitForTimeout(100);record('site.save-edit',read().state.inquiries.length===1&&read().state.inquiries[0].id===id&&read().state.inquiries[0].need==='Chair inspection; request a scope review, not an approved price.'&&hash(read().state.inquiries[0].details)===hash(fieldValues)&&await frame().locator('[data-detail-field]').count()===fieldValues.length&&await frame().locator('[data-need]').innerText()===read().state.inquiries[0].need,'Reopening updates the same persisted inquiry and rendered detail without duplication.');
  phase='owner review';await frame().locator('[data-review]').first().click();await page.waitForTimeout(100);record('site.review-state',read().state.inquiries[0].status==='reviewed'&&/reviewed/i.test(await frame().locator('[data-status]').first().innerText()),'An explicit local click marks review; it does not send or book.');
  const stable=structuredClone(read().state);phase='reload';await page.reload();await frame().locator('[data-ready="true"]').waitFor();record('site.persistence',hash(read().state)===hash(stable)&&await frame().locator('#inquiries article').count()===1&&await frame().locator('[data-need]').innerText()===stable.inquiries[0].need,'Content and review state survive page refresh and match trusted state readback.');
  phase='export';await frame().locator('#export').click();record('site.export',hash(JSON.parse(await frame().locator('#export-data').inputValue()))===hash(stable),'JSON export agrees exactly with authoritative local records.');
  phase='fresh session';await context.close();await open();record('site.fresh-session',hash(read().state)===hash(stable)&&await frame().locator('#inquiries article').count()===1,'A new browser context reads the same persisted inquiry.');
  phase='narrow';await page.setViewportSize({width:390,height:844});await snapshot('narrow');const narrow=views.at(-1);record('site.responsive',narrow.viewport===390&&narrow.scrollWidth<=392&&narrow.controls.length>=5&&narrow.controls.every((c:any)=>c.box.x>=-1&&c.box.x+c.box.width<=392&&c.text.length>0&&(c.tag!=='button'||c.box.height>=32)),'At 390px the rendered controls have labels, fit the page and use usable button heights. Geometry is not independent aesthetic review.');
  const before=hash(read());await page.evaluate(()=>window.postMessage({channel:'midas-preview',nonce:'forged',id:'rogue',operation:'write',state:{schemaVersion:1,inquiries:[]},expectedVersion:0},'*'));await page.waitForTimeout(40);record('software.bridge-isolation',hash(read())===before,'A forged parent message cannot change inquiry records.');
 }catch(e){record('site.journey',false,'Actual browser journey stopped at '+phase,{error:(e as Error).message.slice(0,1000)});await snapshot('failure');}
 finally{record('software.network',blocked===0&&errors.length===0,'No attempted network use or uncaught browser errors in the acceptance journey.',{blockedRequests:blocked,pageErrors:errors});record('software.browser-observation',true,'Actual DOM/geometry observations and retained screenshots; no model vision or independent human scoring.',{profile:'business-site-v1',manifestHash:options.manifestHash,views,independentHumanReview:false},false);await browser?.close();await new Promise<void>(r=>server.close(()=>r()));}
 return checks;
}
