import {hash} from '../contracts.ts';
import type {Check,SourceFile,BriefInputs} from './products.ts';
import {renderServiceBrief} from './products.ts';
export const campaignKinds=['offer','creative-brief','script','lifecycle-message','measurement-plan','operations-plan'] as const;
export const campaignChecks=['campaign.structure','campaign.source-support','campaign.shared-consistency','campaign.execution-boundary'];
export const campaignContract={id:'commercial-campaign-v1',source:'brief.json',extension:'Keep the normal service brief and add campaign. Every field below is worker-authored except controller-owned workspace metadata.',shape:{campaign:{version:1,foundation:{audience:{value:'Nonempty target segment, <=500 chars',status:'source | hypothesis | unknown',references:[{sourceId:'permitted ID',quote:'exact supporting excerpt'}]},offer:'same value/status/references shape; precise scope and offer',price:{currency:'USD',minorUnits:'null if unknown; otherwise safe integer cents 0..100000000',status:'source | hypothesis | unknown',references:'same reference shape'},positioning:'1..1200 characters: concrete proposed advantage and strongest alternative',scope:['1..12 included/excluded scope statements'],primaryAction:'1..500 characters, local owner-controlled validation only'},assets:[{id:'unique <=80 character identifier',kind:campaignKinds,title:'1..160 characters',body:'80..5000 characters of actual usable content, not a task to write it later; use {{audience}}, {{offer}} and {{price}} for shared values',status:'draft_unsent'}]}},rules:['At least one asset for each declared kind and two lifecycle-message assets, 7..12 assets total. Creative scripts and messages are actual unsent copy. Measurement plan includes observable measures, unknown baseline and a small decision rule; operations plan states owner responsibilities and unavailable execution.','Every asset body must reference {{audience}}, {{offer}}, and {{price}}. Shared value tokens are resolved from the single foundation when displayed/exported. Never copy a guessed price into individual assets. Unknown tokens or raw currency/percentage claims in body are rejected; write measurable thresholds in the measurement plan without inventing observed rates.','A source status requires at least one permitted exact reference. Hypothesis/unknown are not established facts; unknown price requires null, other prices require cents. Source quotation checks reference integrity, not commercial truth.','No contact, campaign launch, publication to the internet, spend, booking or purchase occurs. Assets remain draft_unsent. Existing required source coverage and handoff rules apply.']};
const txt=(v:any,min=1,max=10000)=>typeof v==='string'&&v.trim().length>=min&&v.length<=max;
const statuses=['source','hypothesis','unknown'];
export function checkCampaign(report:any,inputs:BriefInputs):Check[]{
 const c=report?.campaign,f=c?.foundation,a=c?.assets,sources=new Map(inputs.sources.map(s=>[s.id,s.text]));
 const claim=(v:any)=>v&&txt(v.value,1,500)&&statuses.includes(v.status)&&Array.isArray(v.references)&&v.references.length<=8;
 const price=f?.price;const structure=c?.version===1&&claim(f?.audience)&&claim(f?.offer)&&price&&price.currency==='USD'&&statuses.includes(price.status)&&Array.isArray(price.references)&&(price.status==='unknown'?price.minorUnits===null:Number.isSafeInteger(price.minorUnits)&&price.minorUnits>=0&&price.minorUnits<=100000000)&&txt(f?.positioning,1,1200)&&Array.isArray(f?.scope)&&f.scope.length>0&&f.scope.length<=12&&f.scope.every((s:any)=>txt(s,1,500))&&txt(f?.primaryAction,1,500)&&Array.isArray(a)&&a.length>=7&&a.length<=12&&new Set(a.map((x:any)=>x.id)).size===a.length&&a.every((x:any)=>txt(x.id,1,80)&&/^[a-z][a-z0-9-]*$/.test(x.id)&&campaignKinds.includes(x.kind)&&txt(x.title,1,160)&&txt(x.body,80,5000))&&campaignKinds.every(k=>a.some((x:any)=>x.kind===k))&&a.filter((x:any)=>x.kind==='lifecycle-message').length>=2;
 const supported=Boolean(structure&&[f.audience,f.offer,f.price].every(v=>(v.status!=='source'||v.references.length>0)&&v.references.every((r:any)=>txt(r.sourceId,1,200)&&txt(r.quote)&&sources.has(r.sourceId)&&sources.get(r.sourceId)!.includes(r.quote))));
 const consistent=Boolean(structure&&a.every((x:any)=>['audience','offer','price'].every(k=>x.body.includes('{{'+k+'}}'))&&!/\{\{(?!audience\}\}|offer\}\}|price\}\})/.test(x.body)&&!/(?:[$€£]\s*\d|\bUSD\s*\d|\b\d+(?:\.\d+)?\s*(?:USD|dollars?|%))/i.test(x.body)));
 return [{id:'campaign.structure',required:true,passed:Boolean(structure),summary:'Campaign has a canonical commercial foundation and authored offer, creative, script, lifecycle, measurement and operations assets.'},{id:'campaign.source-support',required:true,passed:supported,summary:'Claim statuses distinguish supplied source assertions, hypotheses and unknowns; exact references are permitted. Semantic truth remains unverified.'},{id:'campaign.shared-consistency',required:true,passed:consistent,summary:'Every asset resolves audience, offer and price from one canonical foundation; no unknown token or separate numeric currency/rate claim is allowed.',evidence:{foundationHash:structure?hash(f):null,scope:'Structured shared-value consistency, not a semantic promise detector.'}},{id:'campaign.execution-boundary',required:true,passed:Boolean(structure&&a.every((x:any)=>x.status==='draft_unsent')),summary:'All campaign content is explicitly draft and unsent; customer, spending and deployment effects are unavailable.'}];
}
export function campaignPrice(f:any){return f.price.minorUnits===null?'Price unknown — owner decision required':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(f.price.minorUnits/100)+' ('+f.price.status+')';}
export function campaignText(body:string,f:any){return body.replaceAll('{{audience}}',f.audience.value).replaceAll('{{offer}}',f.offer.value).replaceAll('{{price}}',campaignPrice(f));}
const e=(x:any)=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function campaignFiles(report:any,inputs:BriefInputs):SourceFile[]{const c=report.campaign,f=c.foundation;const html='<section id="commercial-assets"><h2>Coordinated commercial assets</h2><p>Drafts for owner review. These are prepared content, not executed campaigns or proven demand.</p><article><h3>Shared commercial foundation</h3><p><b>Audience:</b> '+e(f.audience.value)+' · '+e(f.audience.status)+'</p><p><b>Offer:</b> '+e(f.offer.value)+' · '+e(f.offer.status)+'</p><p><b>Price:</b> '+e(campaignPrice(f))+'</p><p>'+e(f.positioning)+'</p><ul>'+f.scope.map((x:string)=>'<li>'+e(x)+'</li>').join('')+'</ul><p><b>Next action:</b> '+e(f.primaryAction)+'</p></article>'+c.assets.map((a:any)=>'<article id="asset-'+e(a.id)+'"><small>'+e(a.kind)+' · draft, unsent</small><h3>'+e(a.title)+'</h3><p style="white-space:pre-wrap">'+e(campaignText(a.body,f))+'</p></article>').join('')+'</section>';return [{path:'report.html',content:renderServiceBrief(report,inputs).replace('</html>',html+'</html>')},...c.assets.map((a:any)=>({path:a.id+'.md',content:'# '+a.title+'\n\nDraft — unsent. Shared foundation '+hash(f)+'\n\n'+campaignText(a.body,f)+'\n'})),{path:'campaign-foundation.json',content:JSON.stringify(f,null,2)}];}
