/** Exact credit-failure continuation. No billing mutation, probe or implicit retry. */
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {hash,rawHash,requireThat,scopeKey} from '../contracts.ts';
import {verified} from '../experiment/config.ts';
import {validateStageContinuationR4,stageRetirementAllowsProgress,R4_SOURCE_ARTIFACT_ID,R4_ACCEPTED_BRIEF_HASH} from './continuation-r4.ts';
import {CREDIT_CONTINUATION_KIND,stageContractSet} from './stage-contracts.ts';
import type {PortfolioGrant} from './live.ts';
import {taskDefinitionHash} from './live.ts';
import type {HistoricalExposure} from './continuation.ts';
export const R5_PARENT_PROPOSAL='2d177f6a5bd89e656899eba56823f09066f880f98e526c756be994873e46af69';
export const R5_PARENT_ATTEMPT='p031-2c7a9771c07a9c24-0';
export const R5_PLAN='value-release-v4-credit-continuation-r5';
export const R5_TASKS=stageContractSet(CREDIT_CONTINUATION_KIND).map((c,i)=>({parentId:['quote-desk/decide-v4-r4','quote-desk/build-v4-r4','quote-desk/review-product-v4-r4','quote-desk/operate-v4-r4','quote-desk/adapt-v4-r4'][i],id:['quote-desk/decide-v4-r5','quote-desk/build-v4-r5','quote-desk/review-product-v4-r5','quote-desk/operate-v4-r5','quote-desk/adapt-v4-r5'][i],stageContract:c.id,workCalls:c.ordinaryAdmissions}));
export type CreditContinuationR5={kind:typeof CREDIT_CONTINUATION_KIND;parentRoot:string;parentGrantHash:string;parentOperatingHash:string;parentProposalHash:string;parentGrantFileHash:string;parentSnapshotHash:string;diagnosticHash:string;backupManifestHash:string;backupDatabaseHash:string;restoreHash:string;historical:HistoricalExposure;carryId:string;combinedCeilingMinor:number;combinedAdmissionLimit:number;originalCeilingMinor:number;originalAdmissionLimit:number;tasks:typeof R5_TASKS;sourceArtifactHash:string;historicalRetrievals:number;diagnosticRetrievals:1;maxNewRetrievals:3360;durability:Record<string,unknown>};
const rows=(db:DatabaseSync,kind:string)=>db.prepare('SELECT key,body FROM entities WHERE kind=? ORDER BY key').all(kind).map(r=>({key:String(r.key),body:JSON.parse(String(r.body))}));
const entity=(db:DatabaseSync,kind:string,key:string)=>rows(db,kind).find(r=>r.key===key)?.body??null;
export function inspectCreditParent(root:string,key:string){
 const bytes=readFileSync(join(root,'portfolio.authorization.json')),envelope=JSON.parse(bytes.toString('utf8')),grant=verified(envelope,key) as PortfolioGrant,inner=verified(envelope.operatingEnvelope,key);
 requireThat(grant.root===resolve(root)&&grant.continuation?.kind==='portfolio-v4-stage-continuation-r4'&&hash(inner)===grant.operatingGrantHash,'CREDIT_PARENT_AUTHORITY');validateStageContinuationR4(grant,key,true);
 const proposal=JSON.parse(readFileSync(join(root,'proposal',grant.id,'portfolio.authorization.request.json'),'utf8'));requireThat(hash(proposal)===R5_PARENT_PROPOSAL,'CREDIT_PARENT_PROPOSAL');
 const db=new DatabaseSync(join(root,'portfolio.sqlite'),{readOnly:true});try{
  const scope=scopeKey(grant.accountScope),attempts=rows(db,'model-attempt').filter(r=>r.key.startsWith(scope+'/')),jobs=rows(db,'response-job').filter(r=>r.key.startsWith(scope+'/')),account=entity(db,'experiment-account',scope),tasks=R5_TASKS.map(t=>entity(db,'portfolio-task',t.parentId));
  requireThat(attempts.length===1&&jobs.length===1&&attempts[0].body.id===R5_PARENT_ATTEMPT,'CREDIT_PARENT_ADMISSIONS');const a=attempts[0].body,j=jobs[0].body;
  requireThat(a.reservation===164&&a.errorCode==='MODEL_USAGE_MISSING'&&a.inferenceDispatchIntent&&a.countDispatchIntent&&!a.result&&!a.invoice&&a.cost.status==='unknown'&&j.terminal.status==='failed'&&j.terminal.usage===null&&j.terminal.output.length===0&&j.retrievals===2&&hash(j.terminal)===j.terminalHash&&j.terminalHash==='3760be8e2a4eb24e3d9fa55d9313b19d8a9e6ec0926f277a6b54e02aa8c0fa9d','CREDIT_PARENT_FAILURE');
  requireThat(account.authorizationHash===hash(inner)&&hash(account.limits)===hash(inner.limits)&&!account.settled&&!account.halted,'CREDIT_PARENT_ACCOUNT');
  requireThat(tasks.every((t,i)=>t&&!t.lease&&!t.outputArtifacts.length&&taskDefinitionHash(t)===grant.tasks![i].definitionHash&&(i===0?t.status==='needs_reconciliation'&&t.attempts===1&&!t.result:t.status==='queued'&&t.attempts===0)),'CREDIT_PARENT_TASK_STATE');
  const source=entity(db,'portfolio-artifact',R4_SOURCE_ARTIFACT_ID);requireThat(source.content.brief.sha256===R4_ACCEPTED_BRIEF_HASH&&source.content.brief.bytes===17908,'CREDIT_SOURCE');
  const dir=join(root,'diagnostics/response-r4-one-read'),diagnosticEnvelope=JSON.parse(readFileSync(join(dir,'authorization.json'),'utf8')),diagnosticGrant=verified(diagnosticEnvelope,key),diagnostic=JSON.parse(readFileSync(join(dir,'observation.json'),'utf8')),body=readFileSync(join(dir,'response-body.json')),raw=JSON.parse(body.toString('utf8'));
  requireThat(diagnosticGrant.approved&&diagnosticGrant.parentGrantHash===hash(grant)&&diagnosticGrant.maxGETs===1&&diagnosticGrant.maxPOSTs===0&&diagnosticGrant.maxCounts===0&&diagnosticGrant.deadlineMs===15000&&diagnosticGrant.projectId===grant.projectId&&diagnosticGrant.responseId===j.responseId&&diagnostic.authorizationHash===hash(diagnosticGrant)&&diagnostic.responseId===j.responseId&&diagnostic.getAdmissions===1&&diagnostic.counts===0&&diagnostic.inferences===0&&diagnostic.retries===0&&diagnostic.httpStatus===200&&diagnostic.bodyHash===rawHash(body)&&diagnostic.bodyHash==='5597a9cfb9515f02fa6a6bf10c11dbe4cfe42e013114e4b7dc6a327fc86d0d59'&&raw.id===j.responseId&&raw.status==='failed'&&raw.error.code==='credit_balance_exhausted'&&raw.usage===null,'CREDIT_DIAGNOSTIC');
  const historical={...grant.continuation.historical,admissions:12,counts:12,reservedMinor:1517};requireThat(hash(historical)===hash({admissions:12,counts:12,reservedMinor:1517,provisionalMinor:574,settledMinor:0,countBufferMinor:400}),'CREDIT_CARRY');
  const snapshot={attempts,jobs,account,tasks,source,bindings:rows(db,'portfolio-work-binding').filter(r=>r.key.startsWith(scope+'/')),requests:rows(db,'portfolio-model-request').filter(r=>r.key.startsWith('quote-desk/decide-v4-r4/')),steps:rows(db,'portfolio-step').filter(r=>r.body.taskId==='quote-desk/decide-v4-r4')};
  return {grant,inner,proposal,tasks,source,historical,snapshotHash:hash(snapshot),grantFileHash:rawHash(bytes),diagnosticHash:hash({diagnosticGrant,diagnostic}),historicalLedgerHash:hash({account,attempts:attempts.map(r=>({key:r.key,value:r.body}))}),retired:entity(db,'portfolio-revocation',hash(grant)),operatingRetired:entity(db,'operating-revocation',hash(inner))};
 }finally{db.close();}
}
export function creditCarry(c:CreditContinuationR5){return [{id:c.carryId,exposureMinor:c.historical.reservedMinor,evidenceHash:hash({parent:c.parentGrantHash,snapshot:c.parentSnapshotHash,diagnostic:c.diagnosticHash,historical:c.historical})}];}
export function validateCreditContinuation(g:PortfolioGrant,key:string,requireRetired:boolean){
 const c=g.continuation as CreditContinuationR5;requireThat(c?.kind===CREDIT_CONTINUATION_KIND&&resolve(c.parentRoot)!==g.root,'CREDIT_SCOPE');const p=inspectCreditParent(c.parentRoot,key);
 requireThat(c.parentSnapshotHash===p.snapshotHash&&c.diagnosticHash===p.diagnosticHash&&c.parentGrantHash===hash(p.grant)&&c.parentOperatingHash===hash(p.inner)&&c.parentGrantFileHash===p.grantFileHash&&c.parentProposalHash===R5_PARENT_PROPOSAL&&hash(c.historical)===hash(p.historical),'CREDIT_HISTORY_CHANGED');
 requireThat(c.combinedCeilingMinor===4582&&c.originalCeilingMinor===4582&&c.combinedAdmissionLimit===26&&c.originalAdmissionLimit===26&&c.historical.reservedMinor+c.historical.countBufferMinor===1917&&c.historicalRetrievals===2&&c.diagnosticRetrievals===1&&c.maxNewRetrievals===3360,'CREDIT_LIMITS');
 requireThat(hash(c.durability)===hash({...((p.grant.continuation as any).durability),retrieval:{...((p.grant.continuation as any).durability.retrieval),maxAcrossGrantedResponses:3360}}),'CREDIT_DURABILITY');
 requireThat(g.projectId===p.grant.projectId&&g.credentialFile===p.grant.credentialFile&&g.expiresAt===p.grant.expiresAt&&g.mode===p.grant.mode&&hash(g.route)===hash({...p.grant.route,authorizationId:g.id})&&g.countUncertaintyMinor===400&&g.recovery.maxAdmissions===0,'CREDIT_AUTHORITY');
 requireThat(hash(c.tasks)===hash(R5_TASKS)&&hash(g.stageContracts)===hash(stageContractSet(CREDIT_CONTINUATION_KIND))&&g.tasks?.length===5&&g.tasks.every((t,i)=>t.id===R5_TASKS[i].id&&t.workCalls===R5_TASKS[i].workCalls&&t.stageContract===R5_TASKS[i].stageContract)&&g.ventures.length===1&&g.ventures[0].workCalls===14&&g.ventures[0].searchCalls===0&&g.ventures[0].goalHash===p.grant.ventures[0].goalHash,'CREDIT_ALLOCATION');
 requireThat(g.initialRequests?.length===1&&g.initialRequests[0].taskId===R5_TASKS[0].id,'CREDIT_INITIAL_DECISION');
 const restore=JSON.parse(readFileSync(join(g.root,'restore.json'),'utf8'));requireThat(hash(restore)===c.restoreHash&&restore.backupManifestHash===c.backupManifestHash&&restore.originalDatabaseHash===c.backupDatabaseHash&&restore.historicalLedgerHash===p.historicalLedgerHash&&restore.sourceRoot===c.parentRoot&&restore.root===g.root&&!restore.credentialsCopied&&!restore.activeAuthorizationInstalled,'CREDIT_RESTORE');
 const progress=stageRetirementAllowsProgress(g,p.retired,p.operatingRetired,requireRetired),db=new DatabaseSync(join(g.root,'portfolio.sqlite'),{readOnly:true});try{
  requireThat(hash(entity(db,'portfolio-artifact',R4_SOURCE_ARTIFACT_ID))===c.sourceArtifactHash&&c.sourceArtifactHash===hash(p.source),'CREDIT_SOURCE_CHANGED');
  const tasks=R5_TASKS.map(t=>entity(db,'portfolio-task',t.id));requireThat(tasks.every((t,i)=>t&&taskDefinitionHash(t)===g.tasks![i].definitionHash&&t.inputs.continuationVersion===R5_PLAN&&t.inputs.stageContract===R5_TASKS[i].stageContract&&t.inputArtifacts.length===1&&t.inputArtifacts[0].sha256===p.source.sha256&&hash(t.dependsOn)===hash(p.tasks[i].dependsOn.filter((id:string)=>R5_TASKS.some(m=>m.parentId===id)).map((id:string)=>id.replace(/-r4$/,'-r5')))),'CREDIT_TASK_CHANGED');
  const freshIds=new Set(R5_TASKS.map(t=>t.id)),scope=scopeKey(g.accountScope),bindings=rows(db,'portfolio-work-binding').filter(r=>freshIds.has(r.body.taskId)||r.key.startsWith(scope+'/'));requireThat(bindings.every(r=>r.key.startsWith(scope+'/')&&r.body.grantHash===hash(g)&&freshIds.has(r.body.taskId)),'CREDIT_LINEAGE');
  if(!progress)requireThat(tasks.every(t=>t.status==='queued'&&t.attempts===0&&!t.lease&&!t.outputArtifacts.length)&&!bindings.length&&!rows(db,'local-workspace').some(r=>freshIds.has(r.body.taskId))&&!rows(db,'portfolio-step').some(r=>freshIds.has(r.body.taskId))&&!rows(db,'model-attempt').some(r=>r.key.startsWith(scope+'/')),'CREDIT_FRESH_REQUIRED');
 }finally{db.close();}return p;
}
