import { Portfolio } from './core.ts';
import { EvidenceLibrary } from './evidence.ts';
import { prepareOperatingRelease } from './release.ts';
import { TOOL_NAMES } from './worker.ts';
import { taskDefinitionHash } from './live.ts';

export const INTEGRATED_RELEASE='integrated-build-v3';
export const integratedAllocation=[['investigate-v3',8],['decide-v3',1],['build-v3',10],['review-product-v3',6],['operate-v3',6],['adapt-v3',1]] as const;
/** Frozen experiment assignments, not a claim that the controller discovered a team. */
export function prepareIntegratedRelease(p:Portfolio,e:EvidenceLibrary){
 prepareOperatingRelease(p,e);
 if(p.store.get('portfolio-plan','quote-desk/'+INTEGRATED_RELEASE))return {prepared:false,providerRequests:0};
 // Supersede only unadmitted preparation. Historical observations are immutable.
 for(const t of p.snapshot().tasks)if(['investigate-v2','review-v2','decide-v2'].some(id=>t.id.endsWith('/'+id))&&t.attempts===0&&['queued','paused'].includes(t.status))p.controlTask(t.id,'cancel');
 const local=TOOL_NAMES.filter(t=>!['research.search','research.fetch'].includes(t));
 const branch=['build-v3','review-product-v3','operate-v3','adapt-v3'].map(id=>'quote-desk/'+id);
 const spec=(id:string,capability:string,title:string,objective:string,dependsOn:string[],extra:any={})=>({id,title,objective,lane:capability.startsWith('portfolio.')?'research' as const:'build' as const,capability,dependsOn,acceptance:['Preserve source support, uncertainty and actual observations; no inferred demand, revenue or competence.','Deliver the current independently checked artifact, or a justified decision to stop.'],allowedTools:capability.startsWith('portfolio.')?[]:id==='investigate-v3'?[...TOOL_NAMES]:[...local],requiredCompetencies:[capability==='quality.review'?'source-review':'evidence-grounded-work'],requiredChecks:[capability.startsWith('portfolio.')?'proposal.reference_checks':'delivery.current'],inputs:{requiresGrant:true,feedbackPolicy:'defer_to_declared_decision',release:INTEGRATED_RELEASE,procedureScope:{capability,population:'owner-permitted-portfolio-jobs-v1'},baselineProcedureId:'baseline-'+capability.replace('.','-')+'-v2',...extra},resource:{modelCalls:integratedAllocation.find(a=>a[0]===id)![1]+2,localToolRuns:12},maxAttempts:1});
 p.addPlan('quote-desk',{id:INTEGRATED_RELEASE,rationale:'Research → explicit value gate → runtime source creation/testing/repair → actual product review → operating deliverable → outcome decision. Replaces unsigned report-heavy release. No spending authority.',evidenceIds:e.list('quote-desk').map(s=>s.id),tasks:[
  spec('investigate-v3','research.investigate','Investigate buyer need and challenge the quote-to-job premise','Find evidence for and against a lightweight quote-to-job tool for a reachable small service operator. Examine substitutes and at least one alternative where warranted. Use up to two hosted searches and permitted public fetches. Produce a concise sourced decision brief: buyer problem, distribution, founder effort, cost assumptions, next useful action, and reasons to reject. There are eight decision calls including writing, checking, publishing and completion; allocate discovery accordingly. The existing prototype is development-assistant work, not customer validation.',[]),
  spec('decide-v3','portfolio.plan','Decide whether a bounded product build is worth doing','Read the full actual investigation. Include exactly one alternative named quote-to-job. Its decision must be prototype only if this bounded local build can change a consequential product or fulfillment decision. Otherwise select reject, investigate, retain or needs_owner_commitment: the controller cancels the four downstream build/review/operate/adapt tasks without spending on them. Explain alternatives and next action in the persisted decision. You may create useful follow-up tasks, but this grant cannot execute newly created tasks. Do not call customer demand proven. The supported product scope is supplied by capabilityProfiles.', ['investigate-v3'],{prototypeGate:{alternativeName:'quote-to-job',cancelUnlessPrototype:branch}}),
  spec('build-v3','software.build','Build and test a real local quote-to-job product','Implement from the blank app.html using the supported file contract and the actual source-grounded decision. Create your own useful interface and implementation. Do not copy the development-assistant demonstration or imply commercial validation. Run check.run, inspect actual failures and replace source to repair them; rerun unchanged checks before local publication. Keep source small enough for full review. This profile supports quoting, job tracking, durable owner state and CSV; it cannot deploy, transact, send, install or implement a different backend.', ['decide-v3']),
  spec('review-product-v3','quality.review','Review and correct the actual runtime product','Read the copied actual app.html and upstream readback/check evidence. Review arithmetic, state/UX, failure handling and stated business use. Correct substantive problems in the authoritative source, rerun checks and publish. Retain an adequate implementation; do not invent an error. This is the strong baseline own-work review, not an independent human or specialist comparison. Explain actual changes and remaining limitations.', ['build-v3']),
  spec('operate-v3','service.brief','Deliver the reviewed product operating and validation packet','Use the full actual reviewed source, authenticated publication readback and check results in context.dependencies, plus permitted business sources. Produce a usable source-grounded brief: precise offer or rejection, product demo/use steps, what the checks establish and leave unknown, founder interview questions, draft unsent outreach, explicit economics assumptions including unknown labor, acceptance/stop criteria and the next owner action. Refer to exact artifact hashes. Do not claim a new customer or real business outcome. Keep operational checks separate from source assertions. Publish locally after checks.', ['review-product-v3']),
  spec('adapt-v3','portfolio.plan','Use the delivered work to revise the next business decision','Read the full operating packet and actual observations. Revise priority and propose the smallest next useful tasks or stop. Separate tool competence, artifact usefulness and missing buyer evidence. Any observed failure may motivate a procedure hypothesis, not automatic specialist superiority. Newly created tasks are persisted but outside this frozen execution grant; no further provider work is released.', ['operate-v3'])
 ]});return {prepared:true,providerRequests:0};
}
export function integratedTaskAllowances(p:Portfolio){return integratedAllocation.map(([id,workCalls])=>{const t=p.getTask('quote-desk/'+id);return {id:t.id,definitionHash:taskDefinitionHash(t),workCalls};});}

export const integratedOwnerPacket={
 summary:'Proposed: investigate the business need, decide whether to build, then have Astra write a local product from blank source, run and repair it, review the actual product, and deliver its operating/validation packet. The grant is unsigned; these jobs have not run on a real model.',
 authorship:'Development-assistant preparation of an executable experiment. Existing quote-to-job software is development-assistant-authored; mock repair used predefined code. Future v3 source must come from recorded actual-model responses.',
 implemented:['Live-shaped worker actions can replace scoped source, execute isolated browser checks, repair failures and publish checked local artifacts.','Actual software source, authenticated delivery, checks and revision evidence now reach downstream review and operating tasks.','A model rejection cancels product work. Model-generated next tasks are saved but outside the six-task grant.'],
 bottlenecks:[{title:'Commercial premise',reason:'A usable prototype is not evidence of buyer demand.',next:'Research alternatives and permit rejection before product admissions.'},{title:'Actual software worker capability',reason:'No real-model build has yet run through these tools.',next:'Fund an explicit blank-source build/test/repair task and review its real output.'},{title:'Scope of execution',reason:'Only the quote-to-job browser profile and sourced briefs are executable; no arbitrary backend or host engineering.',next:'Evaluate useful local fulfillment and record unsupported work without claiming it was executed.'}],
 nextDecision:'Review the fresh integrated-build-v3 request: maximum $51.82, 32 primary work calls, two held known-incomplete recoveries, two hosted searches and 36 counts. No automatic spending; no specialization, sending or deployment.',
 unsupportedClaims:['Autonomous arbitrary product development','Verified customer demand or revenue','Independent human semantic validation','Specialist superiority','Deployment or external business execution']
};
