import {ADAPTIVE_TOOL,adaptiveEnabled,adaptiveWorkerSchema,validateAdaptiveWorker} from '../adaptive/worker-contract.ts';
import {taskBusinessContext} from './task-context.ts';
import {validatePilotBinding} from '../pilot/binding.ts';
import type {PilotBinding} from '../pilot/binding.ts';
import {BACKGROUND_POLICY} from '../durable-responses.ts';
/** New portfolio authority boundary. No historical grant is amended or reused.
 * Creating a proposal never signs it, reads credentials, counts tokens or calls
 * a provider. Only this loader exposes CLI worker/search execution ports. */
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { hostname, homedir } from 'node:os';
import { createPublicKey } from 'node:crypto';
import { canonical, hash, rawHash, requireThat, identifier, safeInteger, scopeKey, FoundryError } from '../contracts.ts';
import type { Scope } from '../contracts.ts';
import { StateStore } from '../state.ts';
import { OperatingModels, implementationHash as operatingImplementationHash, recoveryInstruction } from '../operations/model.ts';
import type { OperatingGrant } from '../operations/model.ts';
import type { ResponsesRoute } from '../model-port.ts';
import { buildResponsesBody } from '../model-port.ts';
import { verified } from '../experiment/config.ts';
import { BudgetedWorker, WORKER_PROCEDURE, FINALIZING_WORKER_PROCEDURE, workerSchema, validateWorker, workerScope, workerPrincipal, ALL_TOOL_NAMES } from './worker.ts';
import type { WorkerModel, WorkerCall } from './worker.ts';
import { planningSchema, EXECUTIVE_PROCEDURE } from './planning.ts';
import { HostedSearch, searchPolicy } from './search.ts';
import {STAGE_CONTRACTS,stageContractSet,stageContractForTask,stageProcedure,stageProcedureForContract,stageSchema,stageTools,validateStageOutput} from './stage-contracts.ts';
import type {StageContractId} from './stage-contracts.ts';
import {continuationCarry,validateContinuation} from './continuation.ts';
import type {DraftContinuation} from './continuation.ts';

export const PORTFOLIO_AUTHORITY_VERSION='portfolio-execution-grant-v1';
export const portfolioRecoveryInstruction=recoveryInstruction;
export type PortfolioRoute=Omit<ResponsesRoute,'reasoningEffort'>&{reasoningEffort:'max'};
export type VentureEnvelope={id:string;goalHash:string;capabilities:string[];tools:string[];sourceHosts:string[];workCalls:number;searchCalls:number};
type SignedStageContract=(typeof STAGE_CONTRACTS)[StageContractId];
export type FrozenTaskAllowance={id:string;definitionHash:string;workCalls:number;stageContract?:StageContractId};
export type InitialRequestBinding={taskId:string;bodyHash:string;schemaHash:string};
export function taskDefinitionHash(t:any){const {authoritativeArtifactId,...inputs}=t.inputs??{};return hash({id:t.id,ventureId:t.ventureId,title:t.title,objective:t.objective,capability:t.capability,dependsOn:t.dependsOn,allowedTools:t.allowedTools,acceptance:t.acceptance,requiredChecks:t.requiredChecks,requiredCompetencies:t.requiredCompetencies,resource:t.resource,inputs,...(inputs.adaptiveExecution?{effectAuthority:t.effectAuthority}:{})});}
export type PortfolioGrant={kind:typeof PORTFOLIO_AUTHORITY_VERSION;approved:boolean;id:string;mode:'mock'|'live';root:string;host:string;account:string;implementationHash:string;operatingImplementationHash:string;operatingGrantHash:string;projectId:string;credentialFile:string|null;accountScope:Scope;expiresAt:string;approvedBy:string;approvalReference:string;route:PortfolioRoute;ventures:VentureEnvelope[];countUncertaintyMinor:number;countPolicy:'separate-unpriced-count-reserve-v1';providerConcurrency:1;automaticRetries:0;recovery:{kind:'known-incomplete-v1';maxAdmissions:0|1|2};externalAuthority:false;historicalAuthorizationTransfer:false;dataPolicy:'permitted-owner-inputs-and-public-sources-v1';searchPolicyHash:string;procedureHashes:string[];stageContracts?:SignedStageContract[];tasks?:FrozenTaskAllowance[];initialRequests?:InitialRequestBinding[];continuation?:DraftContinuation;pilotBinding?:PilotBinding};
export type PortfolioEnvelope={payload:PortfolioGrant;signature:string;operatingEnvelope:{payload:OperatingGrant;signature:string}};
/** A stable local profile binding, not authentication. Owner signatures and
 * provider project credentials authenticate authority; this forbids relocating
 * a signed workspace into another profile without a new grant. */
function accountName(){return 'profile-path:'+resolve(homedir());}
export function portfolioImplementationHash(){
 const here=dirname(fileURLToPath(import.meta.url)),pending=readdirSync(here).filter(n=>/\.(?:ts|js|css|html)$/.test(n)).map(n=>join(here,n)),sources=new Map<string,string>();
 // Bind the portfolio assets and the transitive local modules actually imported
 // by its runtime, including shared validation and config dependencies. Built-in
 // modules and installed browser/runtime binaries remain deployment bindings.
 while(pending.length){const file=pending.pop()!;if(sources.has(file))continue;const source=readFileSync(file,'utf8').replace(/\r\n/g,'\n');sources.set(file,source);for(const match of source.matchAll(/\b(?:from\s*|import\s*(?:\(\s*)?)['"](\.[^'"]+)['"]/g)){if(/\.(?:ts|js|css|html)$/.test(match[1]))pending.push(resolve(dirname(file),match[1]));}}
 const files=[...sources].map(([path,text])=>({path:relative(here,path).replace(/\\/g,'/'),text})).sort((a,b)=>a.path.localeCompare(b.path));return hash({files,operatingImplementationHash:operatingImplementationHash()});
}
export function portfolioRoute(id:string,projectId:string,background=false,stageContracted=false):PortfolioRoute{return {...(background?{background:structuredClone(BACKGROUND_POLICY)}:{}),authorizationId:id,projectId,model:'gpt-6-astra',reasoningEffort:'max',serviceTier:'default',maxOutputTokens:stageContracted?32768:16384,deadlineMs:background?60000:180000,inputTokenCeiling:32768,maxCallCost:{currency:'USD',minorUnits:stageContracted?205:123},pricing:{inputMinorPerMillion:1250,outputMinorPerMillion:5000,source:'https://developers.openai.com/api/docs/models/gpt-6-astra ; conservative cache-write input ceiling $12.50/M and output $50/M',effectiveAt:'2026-09-12T00:00:00.000Z'}};}
export function portfolioTaskRoute(route:PortfolioRoute,contract:SignedStageContract|null){return contract?{...route,inputTokenCeiling:contract.inputTokenCeiling,maxOutputTokens:contract.maxOutputTokens,maxCallCost:structuredClone(contract.maxCallCost)}:route;}
/** The old transport type predates max. Its implementation forwards this exact
 * field; the new boundary validates the current supported max value explicitly. */
function transportRoute(route:PortfolioRoute):ResponsesRoute{return route as unknown as ResponsesRoute;}
function validateBillingKey(key:string|null|undefined){if(key===null||key===undefined)return;requireThat(typeof key==='string'&&key.length<=8192&&key.includes('-----BEGIN PUBLIC KEY-----')&&!key.includes('PRIVATE KEY'),'PORTFOLIO_BILLING_PUBLIC_KEY_REQUIRED');requireThat(createPublicKey(key).asymmetricKeyType==='ed25519','PORTFOLIO_BILLING_KEY_UNSUPPORTED');}
function validateInitialRequests(bindings:InitialRequestBinding[]|undefined,tasks:FrozenTaskAllowance[]|undefined){
 if(bindings===undefined)return;
 requireThat(Array.isArray(bindings)&&bindings.length>0&&bindings.length<=100&&new Set(bindings.map(b=>b?.taskId)).size===bindings.length&&bindings.every(b=>b&&Object.keys(b).sort().join(',')==='bodyHash,schemaHash,taskId'&&typeof b.taskId==='string'&&tasks?.some(t=>t.id===b.taskId)&&/^[a-f0-9]{64}$/.test(b.bodyHash)&&/^[a-f0-9]{64}$/.test(b.schemaHash)),'PORTFOLIO_INITIAL_REQUEST_BINDINGS');
}
function continuationCapMatches(c:DraftContinuation,totalMinor:number,calls:number){return c.kind==='portfolio-v4-artifact-continuation-r2'||c.kind==='portfolio-v4-durable-continuation-r3'
 ?totalMinor===c.combinedCeilingMinor&&calls===c.combinedAdmissionLimit&&totalMinor<=c.originalCeilingMinor&&calls<=c.originalAdmissionLimit
 :c.kind==='portfolio-v4-stage-continuation-r4'?totalMinor===c.combinedCeilingMinor&&calls===c.combinedAdmissionLimit&&totalMinor<=c.originalCeilingMinor&&calls<=c.originalAdmissionLimit
 :totalMinor===c.combinedCeilingMinor&&calls===c.combinedAdmissionLimit;}
export function createPortfolioProposal(input:{background?:boolean;stageContracts?:StageContractId[];root:string;id:string;projectId:string;credentialFile:string|null;billingPublicKey?:string|null;expiresAt:string;mode?:'mock'|'live';countUncertaintyMinor:number;recoveryAdmissions?:0|1|2;tasks?:FrozenTaskAllowance[];initialRequests?:InitialRequestBinding[];continuation?:DraftContinuation;pilotBinding?:PilotBinding;ventures:Array<Omit<VentureEnvelope,'goalHash'|'sourceHosts'>&{goal:string;sourceHosts?:string[]}>}){
 identifier(input.id);requireThat(input.id.startsWith('portfolio-031-')||Boolean(input.pilotBinding)&&input.id.startsWith('portfolio-pilot-032-'),'PORTFOLIO_FRESH_AUTHORITY_REQUIRED');if(input.pilotBinding){validatePilotBinding(input.pilotBinding,input.tasks);requireThat(input.background===true&&!input.continuation&&!input.stageContracts?.length&&(input.recoveryAdmissions??0)===0&&input.ventures.every(v=>v.searchCalls===0),'PILOT_GRANT_SCOPE_REQUIRED');};requireThat(/^proj_[A-Za-z0-9_-]+$/.test(input.projectId),'PORTFOLIO_PROJECT_REQUIRED');safeInteger(input.countUncertaintyMinor,1);validateBillingKey(input.billingPublicKey);validateInitialRequests(input.initialRequests,input.tasks);
 const stageIds=input.stageContracts??[],expectedStageIds=Object.keys(STAGE_CONTRACTS) as StageContractId[];
 requireThat(!stageIds.length||hash(stageIds)===hash(expectedStageIds),'PORTFOLIO_STAGE_CONTRACT_SET');
 const stageContracts=stageIds.length?stageContractSet(input.continuation?.kind):[],root=resolve(input.root),route=portfolioRoute(input.id,input.projectId,input.background,Boolean(stageContracts.length)||Boolean(input.pilotBinding)),mode=input.mode??'live',ventures:VentureEnvelope[]=input.ventures.map(v=>{safeInteger(v.workCalls);safeInteger(v.searchCalls);return {id:v.id,goalHash:hash(v.goal),capabilities:[...v.capabilities],tools:[...v.tools],sourceHosts:[...(v.sourceHosts??[])],workCalls:v.workCalls,searchCalls:v.searchCalls};});
 const workCalls=ventures.reduce((n,v)=>n+v.workCalls,0),searchCalls=ventures.reduce((n,v)=>n+v.searchCalls,0),callMinor=route.maxCallCost.minorUnits,stageSpend=stageContracts.reduce((n,c)=>n+c.ordinaryAdmissions*c.maxCallCost.minorUnits,0),spend=(stageContracts.length?stageSpend:workCalls*callMinor+searchCalls*300),accountScope:Scope={tenantId:'mason',businessId:'portfolio-models',runId:input.id,dataPolicyVersion:'portfolio-live-v1',mode:'fixture'};
 requireThat([0,1,2].includes(input.recoveryAdmissions??0)&&workCalls>=(input.recoveryAdmissions??0),'PORTFOLIO_RECOVERY_POLICY');
 requireThat(!stageContracts.length||searchCalls===0&&(input.recoveryAdmissions??0)===0&&input.tasks?.length===stageContracts.length&&input.tasks.every(t=>t.stageContract&&stageContracts.find(c=>c.id===t.stageContract)?.ordinaryAdmissions===t.workCalls)&&input.tasks.reduce((n,t)=>n+t.workCalls,0)===workCalls,'PORTFOLIO_STAGE_TASK_ALLOCATIONS');
 const operating:OperatingGrant={kind:'operations-model-grant-v1',mode,root,host:hostname(),implementationHash:operatingImplementationHash(),projectId:input.projectId,credentialFile:input.credentialFile,billingPublicKey:input.billingPublicKey??null,expiresAt:input.expiresAt,approvedBy:'',approvalReference:'',accountScope,route:transportRoute(route),...(stageContracts.length?{stageContracts:structuredClone(stageContracts)}:{}),limits:{totalMinor:spend+input.countUncertaintyMinor,concurrency:1,astraCountRequests:workCalls+searchCalls,overheadReserve:{minor:input.countUncertaintyMinor,reason:'Token-count endpoint price is not established; independent uncertainty reserve, never treated as free.'},stages:{smoke:{minor:0,attempts:0},development:{minor:spend,attempts:workCalls+searchCalls},validation:{minor:0,attempts:0},evaluation:{minor:0,attempts:0}},allocations:[...ventures.map(v=>({metadataKey:'businessId',value:v.id,attempts:v.workCalls+v.searchCalls,minor:stageContracts.length?spend:v.workCalls*callMinor+v.searchCalls*300})),{metadataKey:'stage',value:'portfolio-work',attempts:workCalls,minor:stageContracts.length?spend:workCalls*callMinor},{metadataKey:'stage',value:'portfolio-search',attempts:searchCalls,minor:searchCalls*300},...stageContracts.map(c=>({metadataKey:'stageContract',value:c.id,attempts:c.ordinaryAdmissions,minor:c.ordinaryAdmissions*c.maxCallCost.minorUnits}))]},businesses:ventures.map(v=>({id:v.id,goalHash:v.goalHash,sourceHosts:v.sourceHosts,maxCalls:v.workCalls+v.searchCalls})),retries:0,providerConcurrency:1,countDeadlineMs:10000,externalAuthority:false};
 const r2=input.continuation?.kind==='portfolio-v4-artifact-continuation-r2'||Boolean(input.background);
 const portfolio:PortfolioGrant={kind:PORTFOLIO_AUTHORITY_VERSION,approved:false,id:input.id,mode,root,host:hostname(),account:accountName(),implementationHash:portfolioImplementationHash(),operatingImplementationHash:operatingImplementationHash(),operatingGrantHash:hash(operating),projectId:input.projectId,credentialFile:input.credentialFile,accountScope,expiresAt:input.expiresAt,approvedBy:'',approvalReference:'',route,ventures,countUncertaintyMinor:input.countUncertaintyMinor,countPolicy:'separate-unpriced-count-reserve-v1',providerConcurrency:1,automaticRetries:0,recovery:{kind:'known-incomplete-v1',maxAdmissions:input.recoveryAdmissions??0},externalAuthority:false,historicalAuthorizationTransfer:false,dataPolicy:'permitted-owner-inputs-and-public-sources-v1',searchPolicyHash:hash(searchPolicy),...(input.pilotBinding?{pilotBinding:structuredClone(input.pilotBinding)}:{}),procedureHashes:input.pilotBinding?[...new Set(input.pilotBinding.taskProcedures.map(p=>p.procedureHash))].sort():stageContracts.length?stageIds.map(id=>hash(stageProcedureForContract(id))):r2?[hash(FINALIZING_WORKER_PROCEDURE),hash(EXECUTIVE_PROCEDURE)]:[hash(WORKER_PROCEDURE),hash(EXECUTIVE_PROCEDURE)],...(stageContracts.length?{stageContracts:structuredClone(stageContracts)}:{}),...(input.tasks?{tasks:structuredClone(input.tasks)}:{}),...(input.initialRequests?{initialRequests:structuredClone(input.initialRequests)}:{})};
 if(input.continuation){portfolio.continuation=structuredClone(input.continuation);operating.countRequestByteCeiling=196608;operating.limits.carryIn=continuationCarry(input.continuation);operating.limits.totalMinor+=input.continuation.historical.reservedMinor;operating.limits.overheadReserve!.reason=input.background?'The SAME historical unpriced token-count and durable retrieval uncertainty reserve, carried once; no second count/read buffer is allocated.':'The SAME historical unpriced token-count uncertainty reserve, carried once; no second count buffer is allocated.';portfolio.operatingGrantHash=hash(operating);const calls=workCalls+searchCalls+input.continuation.historical.admissions;requireThat(continuationCapMatches(input.continuation,operating.limits.totalMinor,calls),'CONTINUATION_COMBINED_CAP');}
 return {portfolio,operating,approved:false,providerRequests:0,inferenceAdmissions:workCalls+searchCalls,countAdmissions:workCalls+searchCalls,maximumExposureMinor:operating.limits.totalMinor,...(input.continuation?{incrementalExposureMinor:spend,historicalRetainedMinor:input.continuation.historical.reservedMinor+input.countUncertaintyMinor}:{}),currency:'USD',instructions:'Review exact scope and limits. Both payloads require owner signatures; set matching approvedBy/approvalReference, approve the outer payload, and recompute its operatingGrantHash after finalizing the inner payload. No historical grants transfer. A linked continuation retires parent execution authority before new dispatch and preserves its evidence and exposure.'};
}
export function writePortfolioProposal(directory:string,input:Parameters<typeof createPortfolioProposal>[0]){const proposal=createPortfolioProposal(input);mkdirSync(directory,{recursive:true});writeFileSync(join(directory,'portfolio.authorization.request.json'),JSON.stringify(proposal,null,2)+'\n',{flag:'wx'});return proposal;}

export function loadLivePortfolio(root:string,store:StateStore,options:{envelope?:PortfolioEnvelope;trustedPublicKey?:string;purpose?:'execute'|'billing'|'sign';execution?:{kind:'mock';transport:typeof fetch}|{kind:'live';transport?:typeof fetch;credential?:()=>string}}={}){
 const envelope=options.envelope??JSON.parse(readFileSync(join(root,'portfolio.authorization.json'),'utf8')),publicKey=options.trustedPublicKey??readFileSync(join(root,'auth','portfolio-owner.pub'),'utf8');
 const g=structuredClone(verified(envelope,publicKey)) as PortfolioGrant,inner=structuredClone(verified(envelope.operatingEnvelope,publicKey)) as OperatingGrant;
 requireThat(g.kind===PORTFOLIO_AUTHORITY_VERSION&&g.approved===true&&(g.id.startsWith('portfolio-031-')||Boolean(g.pilotBinding)&&g.id.startsWith('portfolio-pilot-032-'))&&g.historicalAuthorizationTransfer===false,'PORTFOLIO_NEW_APPROVAL_REQUIRED');identifier(g.id);
 requireThat(g.root===resolve(root)&&g.host===hostname()&&g.account===accountName(),'PORTFOLIO_LOCATION_MISMATCH');
 requireThat(g.implementationHash===portfolioImplementationHash()&&g.operatingImplementationHash===operatingImplementationHash(),'PORTFOLIO_CODE_CHANGED');
 requireThat(g.operatingGrantHash===hash(inner)&&inner.implementationHash===g.operatingImplementationHash,'PORTFOLIO_INNER_BINDING');
 requireThat(g.approvedBy.length>0&&g.approvalReference.length>0&&inner.approvedBy===g.approvedBy&&inner.approvalReference===g.approvalReference&&Number.isFinite(Date.parse(g.expiresAt))&&(options.purpose==='billing'||Date.parse(g.expiresAt)>Date.now()),'PORTFOLIO_EXPIRED_OR_UNSIGNED');validateBillingKey(inner.billingPublicKey);
 requireThat(g.mode===inner.mode&&g.mode===(options.execution?.kind??'live')&&g.root===inner.root&&g.host===inner.host&&g.expiresAt===inner.expiresAt&&g.projectId===inner.projectId&&g.credentialFile===inner.credentialFile,'PORTFOLIO_INNER_SCOPE');
 requireThat(/^proj_[A-Za-z0-9_-]+$/.test(g.projectId)&&g.route.projectId===g.projectId,'PORTFOLIO_PROJECT_MISMATCH');
 if(g.pilotBinding){validatePilotBinding(g.pilotBinding,g.tasks,store);requireThat(Boolean(g.route.background)&&!g.continuation&&!g.stageContracts?.length&&g.recovery.maxAdmissions===0&&g.ventures.every(v=>v.searchCalls===0),'PILOT_GRANT_SCOPE_REQUIRED');}
 const expectedStageContracts=stageContractSet(g.continuation?.kind),stageContracted=Boolean(g.stageContracts?.length);
 requireThat(stageContracted===Boolean(inner.stageContracts?.length)&&(!stageContracted||hash(g.stageContracts)===hash(expectedStageContracts)&&hash(inner.stageContracts)===hash(expectedStageContracts)),'PORTFOLIO_STAGE_CONTRACT_SET');
 requireThat(hash(g.route)===hash(portfolioRoute(g.id,g.projectId,Boolean(g.route.background),stageContracted||Boolean(g.pilotBinding)))&&hash(inner.route)===hash(g.route),'PORTFOLIO_ROUTE_MISMATCH');
 requireThat(g.accountScope.tenantId==='mason'&&g.accountScope.businessId==='portfolio-models'&&g.accountScope.runId===g.id&&g.accountScope.dataPolicyVersion==='portfolio-live-v1'&&scopeKey(inner.accountScope)===scopeKey(g.accountScope),'PORTFOLIO_ACCOUNT_SCOPE');
 requireThat(g.automaticRetries===0&&g.providerConcurrency===1&&g.externalAuthority===false&&g.dataPolicy==='permitted-owner-inputs-and-public-sources-v1'&&g.countPolicy==='separate-unpriced-count-reserve-v1'&&g.searchPolicyHash===hash(searchPolicy),'PORTFOLIO_AUTHORITY_MISMATCH');
 requireThat(g.recovery?.kind==='known-incomplete-v1'&&[0,1,2].includes(g.recovery.maxAdmissions),'PORTFOLIO_RECOVERY_POLICY');
 const r2=g.continuation?.kind==='portfolio-v4-artifact-continuation-r2'||Boolean(g.route.background),procedureHashes=g.pilotBinding?[...new Set(g.pilotBinding.taskProcedures.map(p=>p.procedureHash))].sort():stageContracted?(Object.keys(STAGE_CONTRACTS) as StageContractId[]).map(id=>hash(stageProcedureForContract(id))):r2?[hash(FINALIZING_WORKER_PROCEDURE),hash(EXECUTIVE_PROCEDURE)]:[hash(WORKER_PROCEDURE),hash(EXECUTIVE_PROCEDURE)];
 requireThat(hash(g.procedureHashes)===hash(procedureHashes),'PORTFOLIO_PROCEDURE_MISMATCH');safeInteger(g.countUncertaintyMinor,1);
 requireThat(g.ventures.length>0&&new Set(g.ventures.map(v=>v.id)).size===g.ventures.length,'PORTFOLIO_VENTURE_SCOPE');
 for(const v of g.ventures){identifier(v.id);safeInteger(v.workCalls);safeInteger(v.searchCalls);requireThat(v.capabilities.length>0&&v.capabilities.every(c=>typeof c==='string'&&c.length>0)&&new Set(v.tools).size===v.tools.length&&v.tools.every(t=>(ALL_TOOL_NAMES as readonly string[]).includes(t)||(t===ADAPTIVE_TOOL&&Boolean(g.pilotBinding)&&Boolean(g.tasks?.some(f=>{const task=store.get('portfolio-task',f.id);return task?.ventureId===v.id&&f.definitionHash===taskDefinitionHash(task)&&adaptiveEnabled(task);}))))&&(!v.searchCalls||v.tools.includes('research.search')),'PORTFOLIO_TOOL_ENVELOPE');const b=inner.businesses.find(b=>b.id===v.id);requireThat(b&&b.goalHash===v.goalHash&&hash(b.sourceHosts)===hash(v.sourceHosts)&&b.maxCalls===v.workCalls+v.searchCalls,'PORTFOLIO_BUSINESS_BINDING');}
 const workCalls=g.ventures.reduce((n,v)=>n+v.workCalls,0),searchCalls=g.ventures.reduce((n,v)=>n+v.searchCalls,0),callMinor=g.route.maxCallCost.minorUnits,stageSpend=(g.stageContracts??[]).reduce((n,c)=>n+c.ordinaryAdmissions*c.maxCallCost.minorUnits,0),spend=stageContracted?stageSpend:workCalls*callMinor+searchCalls*300;
 requireThat(workCalls>=g.recovery.maxAdmissions,'PORTFOLIO_RECOVERY_POLICY');
 if(g.tasks){requireThat(g.tasks.length>0&&new Set(g.tasks.map(t=>t.id)).size===g.tasks.length&&g.tasks.every(t=>typeof t.id==='string'&&/^[a-f0-9]{64}$/.test(t.definitionHash)&&Number.isSafeInteger(t.workCalls)&&t.workCalls>0&&(!stageContracted||Boolean(t.stageContract)&&expectedStageContracts.find(c=>c.id===t.stageContract)?.ordinaryAdmissions===t.workCalls))&&g.tasks.reduce((n,t)=>n+t.workCalls,0)===workCalls-g.recovery.maxAdmissions,'PORTFOLIO_FROZEN_TASK_ALLOCATIONS');}
 requireThat(!stageContracted||g.recovery.maxAdmissions===0&&searchCalls===0&&g.tasks?.length===g.stageContracts!.length,'PORTFOLIO_STAGE_TASK_ALLOCATIONS');
 validateInitialRequests(g.initialRequests,g.tasks);
 const expectedAllocations=[...g.ventures.map(v=>({metadataKey:'businessId',value:v.id,attempts:v.workCalls+v.searchCalls,minor:stageContracted?spend:v.workCalls*callMinor+v.searchCalls*300})),{metadataKey:'stage',value:'portfolio-work',attempts:workCalls,minor:stageContracted?spend:workCalls*callMinor},{metadataKey:'stage',value:'portfolio-search',attempts:searchCalls,minor:searchCalls*300},...(g.stageContracts??[]).map(c=>({metadataKey:'stageContract',value:c.id,attempts:c.ordinaryAdmissions,minor:c.ordinaryAdmissions*c.maxCallCost.minorUnits}))];
 const carry=g.continuation?continuationCarry(g.continuation):[],historical=carry.reduce((n,c)=>n+c.exposureMinor,0);
 requireThat(g.continuation?inner.countRequestByteCeiling===196608:inner.countRequestByteCeiling===undefined,'PORTFOLIO_COUNT_BYTE_LIMIT');
 requireThat(inner.businesses.length===g.ventures.length&&inner.limits.totalMinor===spend+g.countUncertaintyMinor+historical&&inner.limits.overheadReserve?.minor===g.countUncertaintyMinor&&inner.limits.astraCountRequests===workCalls+searchCalls&&hash(inner.limits.allocations)===hash(expectedAllocations)&&inner.limits.stages.development.minor===spend&&inner.limits.stages.development.attempts===workCalls+searchCalls&&hash(inner.limits.carryIn??[])===hash(carry),'PORTFOLIO_AGGREGATE_MISMATCH');
 if(g.continuation){validateContinuation(g,publicKey,options.purpose!=='sign'&&options.purpose!=='billing');const calls=Number(inner.limits.astraCountRequests)+g.continuation.historical.counts;requireThat(continuationCapMatches(g.continuation,inner.limits.totalMinor,calls),'CONTINUATION_COMBINED_CAP');}
 requireThat(['smoke','validation','evaluation'].every(k=>inner.limits.stages[k as 'smoke'].attempts===0&&inner.limits.stages[k as 'smoke'].minor===0)&&!inner.recovery,'PORTFOLIO_FROZEN_GRANT_REUSE_DENIED');
 const credential=options.execution?.kind==='live'&&options.execution.credential?options.execution.credential:()=>{requireThat(typeof g.credentialFile==='string'&&g.credentialFile.length>0,'PORTFOLIO_CREDENTIAL_NOT_CONFIGURED');return readFileSync(g.credentialFile,'utf8').trim();};
 const execution=options.execution?.kind==='mock'?{kind:'mock' as const,transport:options.execution.transport}:{kind:'live' as const,credential,transport:options.execution?.transport??fetch};
 const models=new OperatingModels({store,root,envelope:envelope.operatingEnvelope,trustedPublicKey:publicKey,execution});const baseline=g.mode==='live'?new BudgetedWorker(models):null;
 const providerAvailable=(attemptId:string)=>{
  if(models.ledger.get(attemptId))return;const rows=models.ledger.rows();
  requireThat(!rows.some(r=>r.errorCode&&(['MODEL_ACCESS_REQUIRED','PORTFOLIO_CREDENTIAL_NOT_CONFIGURED','ENOENT','EACCES','EPERM'].includes(r.errorCode)||['http_error','invalid_response'].includes(r.observation?.tokenCount?.phase)||r.observation?.inferenceHTTP?.httpStatus>=400)),'PORTFOLIO_PROVIDER_UNAVAILABLE');
  requireThat(!rows.some(r=>!r.invoice&&r.errorCode&&((r.inferenceDispatchIntent&&r.cost?.status==='unknown')||r.observation?.tokenCount?.phase==='transport_error')),'PORTFOLIO_PROVIDER_UNCERTAIN');
 };
 const current=()=>{requireThat(options.purpose!=='billing','PORTFOLIO_BILLING_ONLY');requireThat(options.purpose!=='sign','PORTFOLIO_SIGN_ONLY');requireThat(Date.parse(g.expiresAt)>Date.now()&&!store.get('portfolio-revocation',hash(g))&&!store.get('operating-revocation',hash(inner)),'PORTFOLIO_AUTHORIZATION_INACTIVE');requireThat(g.implementationHash===portfolioImplementationHash(),'PORTFOLIO_CODE_CHANGED');if(g.continuation)validateContinuation(g,publicKey,true);if(g.pilotBinding)validatePilotBinding(g.pilotBinding,g.tasks,store);};
 const taskAllowed=(ventureId:string,taskId:string,search=false)=>{current();const policy=g.ventures.find(v=>v.id===ventureId),storedVenture=store.get('portfolio-venture',ventureId),task=store.get('portfolio-task',taskId),venture=task&&storedVenture?taskBusinessContext(task,storedVenture):storedVenture;requireThat(policy&&venture&&hash(venture.goal)===policy.goalHash,'PORTFOLIO_GOAL_CHANGED');requireThat(task&&task.ventureId===ventureId&&policy.capabilities.includes(task.capability)&&task.allowedTools.every((t:string)=>policy.tools.includes(t)),'PORTFOLIO_TASK_NOT_GRANTED');if(g.tasks){const frozen=g.tasks.find(t=>t.id===taskId),contract=stageContractForTask(task);requireThat(frozen&&frozen.definitionHash===taskDefinitionHash(task)&&(!stageContracted||frozen.stageContract===contract?.id),'PORTFOLIO_FROZEN_TASK_SCOPE');}if(search)requireThat(policy.searchCalls>0&&task.allowedTools.includes('research.search'),'PORTFOLIO_SEARCH_NOT_GRANTED');return {policy,task,venture};};
 const checkCall=(call:WorkerCall)=>{const tasks=store.db.prepare("SELECT body FROM entities WHERE kind='portfolio-task'").all().map(r=>JSON.parse(String(r.body)));const task=tasks.find(t=>t.ventureId===call.ventureId&&scopeKey(workerScope(t.ventureId,t.id))===scopeKey(call.request.scope));requireThat(task,'PORTFOLIO_REQUEST_TASK_MISSING');const {policy,venture}=taskAllowed(call.ventureId,task.id),contract=stageContractForTask(task);requireThat(policy.workCalls>0&&call.goal===venture.goal&&hash(call.sourceHosts)===hash(policy.sourceHosts),'PORTFOLIO_REQUEST_SCOPE');const expectedTools=stageTools(task),expectedProcedure=stageProcedure(task);requireThat(call.request.requestId===call.attemptId&&call.request.role.model===g.route.model&&g.procedureHashes.includes(hash(call.request.role.procedure))&&(!g.pilotBinding||g.pilotBinding.taskProcedures.some(p=>p.taskId===task.id&&p.procedureHash===hash(call.request.role.procedure)))&&(!contract||call.stageContract===contract.id&&call.request.role.version===contract.id&&(call.request.context as any)?.stageContract?.id===contract.id&&call.request.role.procedure===expectedProcedure)&&hash([...call.request.role.tools].sort())===hash([...expectedTools].sort())&&hash(call.request.tools)===hash(expectedTools.map((name:string)=>({name,version:'portfolio-tool-v1'}))),'PORTFOLIO_REQUEST_TOOLS');const planning=contract?['build-gate-v1','outcome-review-v1'].includes(contract.id):['portfolio.plan','portfolio.reassess'].includes(task.capability),expectedSchema=adaptiveEnabled(task)?adaptiveWorkerSchema(task):stageSchema(task)??(planning?planningSchema:workerSchema);requireThat(hash(call.schema)===hash(expectedSchema),'PORTFOLIO_SCHEMA_CHANGED');return {planning,task,policy,contract};};
 const grantHash=hash(g),accountKey=scopeKey(g.accountScope),bindingKey=(id:string)=>accountKey+'/'+id;
 const ownedRows=(kind:string)=>store.db.prepare('SELECT body FROM entities WHERE kind=?').all(kind).map(r=>JSON.parse(String(r.body))).filter(r=>r.grantHash===grantHash);
 const binding=(id:string)=>store.get('portfolio-work-binding',bindingKey(id));
 const recoveryLink=(id:string)=>store.get('portfolio-recovery-link',bindingKey(id));
 const incomplete=(id:string)=>{const row=models.ledger.get(id),bound=binding(id),o=row?.observation;return Boolean(g.recovery.maxAdmissions&&row?.finishedAt&&row.errorCode==='MODEL_RESPONSE_INCOMPLETE'&&row.metadata.stage==='portfolio-work'&&o?.status==='incomplete'&&o.model===g.route.model&&typeof o.providerRequestId==='string'&&/^[A-Za-z0-9_-]{1,200}$/.test(o.providerRequestId)&&Number.isSafeInteger(o.inputTokens)&&o.inputTokens>=0&&Number.isSafeInteger(o.outputTokens)&&o.outputTokens>=0&&row.cost?.status==='provisional'&&row.cost.money.currency==='USD'&&row.cost.money.minorUnits<=123&&bound?.grantHash===grantHash&&!bound.recoveryOf&&bound.bodyHash===row.requestHash);};
 const recoveryEvidence=(parentAttemptId:string)=>{identifier(parentAttemptId);const row=models.ledger.get(parentAttemptId),bound=binding(parentAttemptId),o=row?.observation;return {eligible:incomplete(parentAttemptId)&&!recoveryLink(parentAttemptId)&&ownedRows('portfolio-recovery-link').length<g.recovery.maxAdmissions&&Date.parse(g.expiresAt)>Date.now()&&!store.get('portfolio-revocation',grantHash)&&!store.get('operating-revocation',hash(inner)),parentAttemptId,parentRequestHash:row?.requestHash??null,requestHash:row?.requestHash??null,ventureId:bound?.ventureId??null,taskId:bound?.taskId??null,status:o?.status??null,providerId:typeof o?.providerRequestId==='string'&&/^[A-Za-z0-9_-]{1,200}$/.test(o.providerRequestId)?o.providerRequestId:null,errorCode:row?.errorCode??null,cost:row?.cost??null,inputTokens:o?.inputTokens??null,outputTokens:o?.outputTokens??null,recoveryClaim:recoveryLink(parentAttemptId)?.attemptId??null};};
 const bindCall=(call:WorkerCall,task:any,policy:VentureEnvelope)=>{
  const recoveryOf=call.recoveryOf??null,key=bindingKey(call.attemptId),contract=stageContractForTask(task),body=buildResponsesBody(transportRoute(portfolioTaskRoute(g.route,contract)),call.request,call.schema),bodyHash=rawHash(canonical(body));
  const actualBytes=Buffer.byteLength(canonical(body)),limitBytes=inner.countRequestByteCeiling??65536;
  if(actualBytes>limitBytes)throw Object.assign(new FoundryError('PORTFOLIO_REQUEST_BYTES_LIMIT'),{providerAdmission:false,requestHash:bodyHash,actualBytes,limitBytes});
  const value={attemptId:call.attemptId,ventureId:call.ventureId,taskId:task.id,goal:call.goal,sourceHosts:call.sourceHosts,request:call.request,schema:call.schema,bodyHash,grantHash,recoveryOf,...(contract?{stageContract:contract.id}:{})};
  store.transaction(()=>{
   const initial=g.initialRequests?.find(b=>b.taskId===task.id);
   // The first ordinary request is determined by durable grant bindings, not
   // an attempt-name suffix. Rejected stale attempts cannot consume this gate.
   if(initial&&!recoveryOf&&!ownedRows('portfolio-work-binding').some(r=>r.taskId===task.id&&!r.recoveryOf)){
    const actual={bodyHash,schemaHash:hash(call.schema)},expected={bodyHash:initial.bodyHash,schemaHash:initial.schemaHash};
    if(hash(actual)!==hash(expected))throw Object.assign(new FoundryError('PORTFOLIO_INITIAL_REQUEST_CHANGED','PORTFOLIO_INITIAL_REQUEST_CHANGED '+JSON.stringify({expected,actual})),{expected,actual});
   }
   const old=binding(call.attemptId);if(old){const {_version,...prior}=old;requireThat(old._version===1&&hash(prior)===hash(value),'PORTFOLIO_WORK_BINDING_CHANGED');}
   const exactIntent=store.get('portfolio-recovery-intent',call.attemptId);
   if(recoveryOf){
    identifier(recoveryOf);requireThat(recoveryOf!==call.attemptId&&incomplete(recoveryOf),'PORTFOLIO_RECOVERY_INELIGIBLE');
    const parent=binding(recoveryOf),proof=models.ledger.get(recoveryOf);
    requireThat(parent.ventureId===call.ventureId&&parent.taskId===task.id&&exactIntent?._version===1&&exactIntent.id===call.attemptId&&exactIntent.parentAttemptId===recoveryOf&&exactIntent.ventureId===call.ventureId&&exactIntent.taskId===task.id&&exactIntent.reason==='known-incomplete-v1'&&exactIntent.parentRequestHash===proof.requestHash&&Number.isFinite(Date.parse(exactIntent.createdAt)),'PORTFOLIO_RECOVERY_INTENT_REQUIRED');
    const expected={...parent.request,requestId:call.attemptId,context:{...parent.request.context,recoveryInstruction:portfolioRecoveryInstruction}};
    requireThat(hash(expected)===hash(call.request)&&hash(parent.schema)===hash(call.schema)&&parent.goal===call.goal&&hash(parent.sourceHosts)===hash(call.sourceHosts),'PORTFOLIO_RECOVERY_REQUEST_CHANGED');
    const link=recoveryLink(recoveryOf);requireThat(!link||link.attemptId===call.attemptId&&link.bodyHash===bodyHash&&link.intentHash===hash(exactIntent),'PORTFOLIO_RECOVERY_ALREADY_CLAIMED');
    if(!link){requireThat(ownedRows('portfolio-recovery-link').length<g.recovery.maxAdmissions,'PORTFOLIO_RECOVERY_CAP');const claim={grantHash,parentAttemptId:recoveryOf,attemptId:call.attemptId,ventureId:call.ventureId,taskId:task.id,parentRequestHash:proof.requestHash,bodyHash,intentHash:hash(exactIntent),correction:portfolioRecoveryInstruction};store.record(g.accountScope,'portfolio-recovery-'+hash(recoveryOf),'PortfolioRecoveryLink',claim);store.put('portfolio-recovery-link',bindingKey(recoveryOf),claim,null);}
   }else{
    requireThat(!exactIntent,'PORTFOLIO_RECOVERY_LINK_REQUIRED');
    if(!old){if(g.tasks){const cap=g.tasks.find(t=>t.id===task.id)!;requireThat(ownedRows('portfolio-work-binding').filter(r=>r.taskId===task.id&&!r.recoveryOf).length<cap.workCalls,'PORTFOLIO_FROZEN_TASK_CAP');}const pending=store.db.prepare("SELECT body FROM entities WHERE kind='portfolio-recovery-intent'").all().map(r=>JSON.parse(String(r.body))).filter(i=>i.taskId===task.id&&i.ventureId===call.ventureId).some(i=>{const recovered=models.ledger.get(i.id);return !recovered?.finishedAt||Boolean(recovered.errorCode);});requireThat(!pending,'PORTFOLIO_RECOVERY_PENDING');requireThat(ownedRows('portfolio-work-binding').filter(r=>!r.recoveryOf).length<workCalls-g.recovery.maxAdmissions,'PORTFOLIO_ORDINARY_WORK_CAP');}
   }
   if(!old){requireThat(ownedRows('portfolio-work-binding').filter(r=>r.ventureId===call.ventureId).length<policy.workCalls,'PORTFOLIO_VENTURE_WORK_CAP');store.record(g.accountScope,'portfolio-work-'+hash(call.attemptId),'PortfolioWorkBinding',value);store.put('portfolio-work-binding',key,value,null);}
  });
 };
 const worker:WorkerModel={kind:g.mode==='live'?'actual_model':'offline_mock',async run(call){
  const {planning,task,policy,contract}=checkCall(call);providerAvailable(call.attemptId);
  if(!models.ledger.get(call.attemptId))requireThat(models.ledger.rows().filter(r=>r.metadata.businessId===call.ventureId&&r.metadata.stage==='portfolio-work').length<policy.workCalls,'PORTFOLIO_VENTURE_WORK_CAP');
  bindCall(call,task,policy);
  const validate=(out:any)=>{if(adaptiveEnabled(task))validateAdaptiveWorker(task,out);else if(contract)validateStageOutput(task,out,call.request.context);else if(!planning)validateWorker(out);call.validate(out);};
  try{const result=baseline?await baseline.run({...call,validate}):await models.invoke(workerPrincipal(call.ventureId),{businessId:call.ventureId,goalHash:hash(call.goal),sourceHosts:call.sourceHosts,attemptId:call.attemptId,stage:'portfolio-work',stageContract:call.stageContract,request:call.request,schema:call.schema,validate});return g.mode==='live'?result:{...result,route:{...result.route,provider:'offline-responses-mock',kind:'fixture' as const}};
  }catch(error){if(['MODEL_USAGE_EXCEEDS_ADMISSION','MODEL_COST_EXCEEDS_ADMISSION'].includes((error as any).code))store.transaction(()=>{const account=store.get('experiment-account',scopeKey(g.accountScope));store.put('experiment-account',scopeKey(g.accountScope),{...account,halted:true},account._version);});throw error;}
 },async recover(call){checkCall(call);if(!models.ledger.get(call.attemptId))return null;return worker.run(call);}};
 const search=new HostedSearch(models,(ventureId,taskId,attemptId)=>{const {policy}=taskAllowed(ventureId,taskId,true);providerAvailable(attemptId);if(!models.ledger.get(attemptId))requireThat(models.ledger.rows().filter(r=>r.metadata.businessId===ventureId&&r.metadata.stage==='portfolio-search').length<policy.searchCalls,'PORTFOLIO_VENTURE_SEARCH_CAP');});
 const totals=()=>{const t=models.totals(),jobs=store.db.prepare("SELECT body FROM entities WHERE kind='response-job'").all().map(r=>JSON.parse(String(r.body))).filter(j=>j.grantHash===hash(inner));return {...t,...(g.route.background?{retrievalRequests:jobs.reduce((n,j)=>n+j.retrievals,0),retrievalLimit:workCalls*g.route.background.maxRetrievals,pendingResponses:jobs.filter(j=>!j.terminal).map(j=>({responseId:j.responseId,status:j.status??'unknown',retrievals:j.retrievals,completionDeadlineAt:j.completionDeadlineAt,resumeUntil:j.resumeUntil}))}:{}),...(g.continuation?{historical:g.continuation.historical,combinedCallsUsed:t.callsUsed+g.continuation.historical.admissions,combinedCallLimit:g.continuation.combinedAdmissionLimit,combinedProvisionalMinor:t.provisionalMinor+g.continuation.historical.provisionalMinor,historicalParent:g.continuation.parentRoot,countBufferReused:true}:{}),recoveryAdmissions:ownedRows('portfolio-recovery-link').length,recoveryLimit:g.recovery.maxAdmissions,ordinaryWorkLimit:workCalls-g.recovery.maxAdmissions,taskAllocations:g.tasks??[]};};
 const reconcileBilling=(envelope:unknown)=>{requireThat(g.implementationHash===portfolioImplementationHash(),'PORTFOLIO_CODE_CHANGED');requireThat(typeof inner.billingPublicKey==='string','PORTFOLIO_BILLING_AUTHORITY_REQUIRED');models.ledger.reconcile(envelope,inner.billingPublicKey,g.projectId);return {reconciled:true,accounting:totals(),countUncertaintyReleasedMinor:0,source:'Signed closed-attempt statement; factual accuracy depends on its underlying provider/project records.'};};
 return {worker,search,totals,recoveryEvidence,reconcileBilling,authorization:structuredClone(g),implementationHash:g.implementationHash};
}
