import { object,requireThat,hash } from '../contracts.ts';
import { validateClaims } from './evidence.ts';
import type { ClaimProposal,EvidenceSource } from './evidence.ts';
const str=(maxLength=1200)=>({type:'string',minLength:1,maxLength});
const array=(items:unknown,maxItems=20)=>({type:'array',items,maxItems});
const obj=(properties:Record<string,unknown>)=>({type:'object',additionalProperties:false,required:Object.keys(properties),properties});
export const planningSchema=obj({summary:str(1800),claims:array(obj({kind:{type:'string',enum:['source_assertion','observation','assumption','estimate','hypothesis','unknown']},text:str(),sourceId:{type:['string','null']},quote:{type:['string','null'],maxLength:1200}}),24),contradictions:array(str(),8),unknowns:array(str(),12),alternatives:array(obj({name:str(120),caseFor:str(),caseAgainst:str(),evidenceIds:array(str(80),20),decision:{type:'string',enum:['investigate','prototype','retain','reject','needs_owner_commitment']}}),6),priority:{type:'integer',minimum:0,maximum:100},rationale:str(1800),cancelTaskIds:array(str(160),20),tasks:array(obj({id:str(80),title:str(180),objective:str(1600),lane:{type:'string',enum:['research','build','commit']},capability:str(80),dependsOn:array(str(80),12),acceptance:array(str(500),10),requiredCompetencies:array(str(80),8),allowedTools:array(str(80),12),priority:{type:'integer',minimum:0,maximum:100}}),12)});
export const EXECUTIVE_PROCEDURE=`Turn the actual venture goal and permitted evidence into a useful, bounded work plan. Challenge the existing venture hypothesis. Compare substitutes, distribution, willingness to pay, fulfillment, founder attention and economics; assumptions are not demand. Research breadth, reversible prototype work and commercial commitment are distinct. Unknown dollars need not block inexpensive evidence gathering, but do not invent return estimates to rank work. Describe falsifying evidence and useful stopping rules. Create dependency-ordered tasks with observable acceptance, supplied capabilities/tools, and the smallest defensible assignment. Refer missing capabilities as blocked work with concrete acceptance; do not pretend role titles establish skill. Source assertions/observations require a preserved exact source quote; unverified inference is a hypothesis. Source quotes establish provenance only. Plan proposals cannot grant external authority or declare customer success. When current outcomes refute a premise, cancel or supersede only unstarted tasks and explain the changed allocation. Your output controls persisted work; include substantive alternatives where warranted. CancelTaskIds must refer to supplied unstarted tasks, never completed history. Priority must be an integer 0–100. Task IDs must be unique local identifiers matching [A-Za-z0-9][A-Za-z0-9_-]{0,79}; dependencies refer only to earlier tasks in this proposal. All required fields must be present.`;
export type PlanningProposal={summary:string;claims:ClaimProposal[];contradictions:string[];unknowns:string[];alternatives:Array<{name:string;caseFor:string;caseAgainst:string;evidenceIds:string[];decision:string}>;priority:number;rationale:string;cancelTaskIds:string[];tasks:Array<{id:string;title:string;objective:string;lane:'research'|'build'|'commit';capability:string;dependsOn:string[];acceptance:string[];requiredCompetencies:string[];allowedTools:string[];priority:number}>};
export function validatePlan(p:any,sources:EvidenceSource[],allowedTools:string[],capabilities:string[],existingTaskIds:string[]):asserts p is PlanningProposal{
 object(p,['summary','claims','contradictions','unknowns','alternatives','priority','rationale','cancelTaskIds','tasks']);
 for(const [k,max]of [['summary',1800],['rationale',1800]]as const)requireThat(typeof p[k]==='string'&&p[k].length>0&&p[k].length<=max,'PLAN_TEXT_BOUNDS');
 validateClaims(p.claims,sources);requireThat(Number.isInteger(p.priority)&&p.priority>=0&&p.priority<=100,'PLAN_PRIORITY');
 for(const [k,max]of [['contradictions',8],['unknowns',12]]as const)requireThat(Array.isArray(p[k])&&p[k].length<=max&&p[k].every((s:any)=>typeof s==='string'&&s.length>0&&s.length<=1200),'PLAN_LIST_BOUNDS');
 requireThat(Array.isArray(p.alternatives)&&p.alternatives.length<=6,'PLAN_ALTERNATIVES');for(const a of p.alternatives){object(a,['name','caseFor','caseAgainst','evidenceIds','decision']);for(const k of ['name','caseFor','caseAgainst'])requireThat(typeof a[k]==='string'&&a[k].length>0&&a[k].length<=(k==='name'?120:1200),'PLAN_ALTERNATIVE_TEXT');requireThat(['investigate','prototype','retain','reject','needs_owner_commitment'].includes(a.decision)&&Array.isArray(a.evidenceIds)&&a.evidenceIds.length<=20&&a.evidenceIds.every((id:string)=>sources.some(s=>s.id===id)),'PLAN_ALTERNATIVE_REFERENCE');}
 requireThat(Array.isArray(p.cancelTaskIds)&&p.cancelTaskIds.length<=20&&p.cancelTaskIds.every((id:string)=>existingTaskIds.includes(id)),'PLAN_CANCEL_SCOPE');
 requireThat(Array.isArray(p.tasks)&&p.tasks.length<=12,'PLAN_TASK_BOUNDS');const seen=new Set<string>();
 for(const t of p.tasks){object(t,['id','title','objective','lane','capability','dependsOn','acceptance','requiredCompetencies','allowedTools','priority']);requireThat(typeof t.id==='string'&&/^[A-Za-z0-9][A-Za-z0-9_-]{0,79}$/.test(t.id)&&!seen.has(t.id),'PLAN_TASK_ID');requireThat(Array.isArray(t.dependsOn)&&t.dependsOn.length<=12&&t.dependsOn.every((id:string)=>seen.has(id)),'PLAN_DEPENDENCIES');seen.add(t.id);
  for(const [k,max] of [['title',180],['objective',1600]]as const)requireThat(typeof t[k]==='string'&&t[k].length>0&&t[k].length<=max,'PLAN_TASK_TEXT');
  requireThat(['research','build','commit'].includes(t.lane)&&capabilities.includes(t.capability),'PLAN_CAPABILITY');
  for(const [k,max,len]of [['acceptance',10,500],['requiredCompetencies',8,80],['allowedTools',12,80]]as const)requireThat(Array.isArray(t[k])&&t[k].length<=max&&t[k].every((v:any)=>typeof v==='string'&&v.length>0&&v.length<=len),'PLAN_TASK_LIST');
  requireThat(t.acceptance.length>0&&t.allowedTools.every((v:string)=>allowedTools.includes(v)),'PLAN_TOOLS_OR_ACCEPTANCE');requireThat(Number.isInteger(t.priority)&&t.priority>=0&&t.priority<=100,'PLAN_TASK_PRIORITY');
 }
}
export const planDigest=(p:PlanningProposal,sources:EvidenceSource[])=>hash({p,sources:sources.map(s=>({id:s.id,sha256:s.sha256}))});
