import { hash,rawHash } from '../contracts.ts';
import { Portfolio } from './core.ts';
import { LocalWorkTools,localToolIds } from './tools.ts';
import { quoteTrackerFiles } from './products.ts';
import type { BriefInputs,SourceFile } from './products.ts';
import { EvidenceLibrary } from './evidence.ts';
import type { WorkerModel,WorkerDecision,WorkerCall } from './worker.ts';
import { mockResult } from './worker.ts';

export const founderContext='Mason owns MIDAS. The product objective is an adaptive business-building system: understand businesses, choose valuable work, assemble the smallest effective team, develop evidence-backed workers, execute within authority, verify economics, and adapt. Available assets explicitly supplied: existing MIDAS software, laptop, current AI development tools and willingness to learn. School, sleep and existing commitments constrain availability. No buyer network or industry expertise is confirmed. Founder effort, commercial budget and business results are not assumed. Current authority permits local engineering and public read-only research, not new paid runtime calls, accounts, external messages, registrations, purchases or deployment.';
const date='2026-09-12T16:00:00.000Z';
const publicSources=[
 {title:'Checkly browser checks — competitive capability',url:'https://www.checklyhq.com/docs/detect/synthetic-monitoring/browser-checks/overview/',text:'Checkly documents browser checks that exercise user journeys using Playwright, collect results and inspect performance. This establishes a capable existing substitute for generic automated website checking. Development-assistant inference: a new service would need a narrower buyer job, useful interpretation and delivery rather than claiming browser automation itself is unique. This page provides no evidence that a buyer would purchase Mason’s proposed service.'},
 {title:'Feedly Market Intelligence — research substitute',url:'https://feedly.com/market-intelligence',text:'Feedly describes finding, synthesizing and sharing industry intelligence, with configurable feeds, reports and source citations. Development-assistant inference: generic summaries are a weak product distinction. A decision-specific recurring brief should first show that a real owner changes a consequential decision because of it. No willingness to pay for a MIDAS service was observed.'},
 {title:'OpenAI Astra — existing frontier baseline',url:'https://developers.openai.com/api/docs/models/gpt-6-astra',text:'The official model documentation lists gpt-6-astra for complex reasoning, coding and research, with Responses structured outputs and tool support. It lists reasoning levels low, medium, high, xhigh and max. A MIDAS worker must be compared fairly against this strong practical baseline with excellent instructions and the same evidence/tools; local fixtures do not establish a specialist advantage.'}
];
export function briefFiles(inputs:BriefInputs,options:{unsupportedQuote?:boolean;purpose?:'portfolio'|'release'}={}):SourceFile[]{
 const portfolio=options.purpose!=='release';
 const report={title:inputs.title,client:inputs.client,asOf:inputs.asOf,observations:inputs.sources.map((s,i)=>({id:'finding-'+(i+1),statement:s.title,sourceId:s.id,quote:options.unsupportedQuote&&i===0?'Customers have already purchased this offer.':s.text})),recommendation:{title:portfolio?'Develop reusable fulfillment before making a commercial commitment':'Offer a bounded release-readiness handoff, conditional on buyer discovery',basis:portfolio?'Existing substitutes weaken a generic automation offer. The prepared product and service are reversible capability tests; market demand and economics remain unmeasured.':'Browser checks are mature technology. The proposed service must earn value through a scoped customer journey, reproducible findings, decision usefulness and reliable handoff. Public vendor documentation is competitive evidence, not a customer interview.',steps:[{action:'Inspect the working local product and complete deliverable, then record a specific defect or decision they help resolve.',owner:'Mason',successMeasure:'An observed owner task result or correction is recorded, with assistance and time limitations.'},{action:'Prepare a problem interview for one agency delivery owner: examine their last release handoff, existing checks, failure consequences and buying authority.',owner:'venture worker prepares; Mason owns any external conversation',successMeasure:'Exact questions and scoped outreach are reviewable; no interview is fabricated or sent.'},{action:'Continue only if evidence identifies an unmet consequential job that the existing tools and excellent frontier baseline do not already satisfy.',owner:'portfolio executive',successMeasure:'A persisted decision cites actual new evidence and either revises the offer or stops spending effort.'}]},unknowns:['No buyer access, willingness to pay or accepted delivery has been observed.','Founder correction time and domain expertise remain unmeasured.','A source-backed hypothesis does not establish causation, profit or model superiority.'],obligations:[{id:'owner-review',description:'Inspect the recommendation for usefulness; record whether assistance was used.',owner:'Mason',status:'open'},{id:'external-access',description:'Obtain exact external-action authorization and an appropriate consenting recipient before outreach or delivery.',owner:'Mason',status:'open'}],provenance:'Development-assistant-authored public-evidence packet. Offline runtime review/correction is explicitly recorded separately.'};
 return [{path:'brief.json',content:JSON.stringify(report,null,2)}];
}
export function preparePortfolio(portfolio:Portfolio,tools:LocalWorkTools,evidence:EvidenceLibrary){
 if(portfolio.snapshot().ventures.length)return {created:false,reason:'Preserved existing portfolio; no reset or duplicate preparation.'};
 portfolio.configure({name:'MIDAS · Founder portfolio',maxConcurrency:3,resources:{workerSlots:3,modelCalls:120,localToolRuns:240}});
 portfolio.registerWorker({id:'baseline-worker',name:'Strong single-worker baseline',competencies:['evidence-grounded-work','software-implementation','source-review'],capabilities:['software.build','service.brief','research.investigate','portfolio.plan','portfolio.reassess','commercial.prepare','quality.review'],maxConcurrency:3,procedureId:'portfolio-worker-v1'});
 const ventures=[
  {id:'quote-desk',name:'Quote desk',goal:'Test a low-friction quote-to-job workflow for a small service operator. Produce software that performs the job locally; do not assume a SaaS opportunity or customer demand.',stage:'prototype',priority:65,summary:'A working local product to investigate quoting, job handoff and persistence. Commercial differentiation remains unproven.',metadata:{model:'Local software prototype',customer:'Small service operator — segment hypothesis',whyNow:'Reusable software fulfillment and defect correction are concrete MIDAS gaps.',bottleneck:'No observed buyer need beyond existing quoting tools.',commitment:'build',nextAction:'Try a quote, convert it to a job, refresh and export.'}},
  {id:'release-readiness',name:'Release readiness',goal:'Investigate a scoped release-readiness service for small web agencies. Prepare a complete evidence-backed handoff and interview package; challenge whether established tools already solve the problem.',stage:'research',priority:70,summary:'A service hypothesis centered on an actionable release handoff, not a generic site audit.',metadata:{model:'Scoped service hypothesis',customer:'Small-agency delivery owner — unvalidated',whyNow:'A bounded service could test buyer value while exercising research, review and delivery.',bottleneck:'Willingness to pay and buyer access are unobserved.',commitment:'research',nextAction:'Inspect the source-linked service packet and its interview questions.'}},
  {id:'midas-intelligence',name:'MIDAS decision brief',goal:'Produce a useful recurring internal decision brief for MIDAS. Track substitutes and operating evidence, distinguish assumptions, and revise portfolio priorities only when evidence warrants it.',stage:'prototype',priority:60,summary:'An internal consumer for source review, recurring content and evidence-driven allocation. External demand is not claimed.',metadata:{model:'Internal briefing; optional future service',customer:'Mason as internal owner',whyNow:'The system needs a concrete way for new evidence to change what happens next.',bottleneck:'Decision usefulness and human correction burden remain unknown.',commitment:'build',nextAction:'Record one observed result; inspect the generated reassessment work.'}}
 ];
 for(const input of ventures){portfolio.createVenture({...input,mode:'local'});evidence.add(input.id,{title:'Founder-supplied operating context',text:founderContext,url:null,observedAt:date,publishedAt:null,rights:'owner_supplied',provenance:'owner_report'});for(const source of publicSources)evidence.add(input.id,{...source,observedAt:date,publishedAt:null,rights:'public_readonly',provenance:'development_assistant_research'});
  const kind=input.id==='quote-desk'?'software':'service',taskId=input.id+'/fulfill';
  const inputs:BriefInputs={title:input.id==='release-readiness'?'Release-readiness validation packet':'MIDAS portfolio decision brief',client:'Mason · MIDAS',asOf:'2026-09-12',sources:evidence.list(input.id).map(s=>({id:s.id,title:s.title,text:s.text,rights:s.rights+(s.url?' · '+s.url:'')})),requiredSourceIds:evidence.list(input.id).map(s=>s.id)};
  tools.seed(input.id,taskId,{kind,files:kind==='software'?quoteTrackerFiles({defect:true}):briefFiles(inputs,{unsupportedQuote:true,purpose:input.id==='release-readiness'?'release':'portfolio'}),inputs:kind==='software'?{product:'quote-to-job',currency:'USD'}:inputs,provenance:'Development-assistant-authored starting artifact with an explicitly seeded defect for offline runtime correction. Not a naturally occurring model error.'});
  portfolio.addPlan(input.id,{id:'initial-local-work',rationale:'Develop and verify reversible fulfillment. The initial inherited artifact has a disclosed injected defect; mock execution proves correction mechanics only.',evidenceIds:evidence.list(input.id).map(s=>s.id),tasks:[{id:'fulfill',title:kind==='software'?'Build and verify the quote-to-job product':'Review and deliver the sourced decision packet',objective:kind==='software'?'Implement a working local product: customer/line-item quotes with correct USD cents, quote-to-job transition, saved state after refresh and CSV export. Inspect failures, revise source, rerun checks and deliver locally.':'Produce a complete source-grounded recommendation with exact source references, accountable next actions, explicit unknowns and open delivery/review obligations. Inspect failures, correct the authoritative packet and deliver locally.',lane:'build',capability:kind==='software'?'software.build':'service.brief',dependsOn:[],acceptance:kind==='software'?['Correct quote arithmetic, job status, persistence and export.','Passed trusted browser checks and current local delivery readback.']:['Every claimed source quote exists in the permitted source bundle.','Current title, client and date match the supplied task.','Recommendation has owners, measurements, unknowns and open obligations.'],requiredCompetencies:[kind==='software'?'software-implementation':'source-review'],allowedTools:[...localToolIds],requiredChecks:['delivery.current'],resource:{modelCalls:8,localToolRuns:8},maxAttempts:3,inputs:{kind,sourceAuthorship:'development_assistant',executionProvenance:'offline_mock',requiredDeliverableContract:kind==='service'?{title:inputs.title,client:inputs.client,asOf:inputs.asOf}:null}},{id:'live-investigation',title:'Investigate the business hypothesis with Astra',objective:input.goal,lane:'research',capability:'portfolio.plan',dependsOn:['fulfill'],acceptance:['Sourced alternatives and a justified work plan or rejection.'],allowedTools:['research.search','research.fetch'],requiredChecks:['proposal.reference_checks'],inputs:{requiresGrant:true},resource:{modelCalls:2,localToolRuns:8}}]});
 }
 return {created:true,ventures:ventures.map(v=>v.id),mode:'prepared_with_disclosed_offline_correction_cases',externalExecution:false};
}
const action=(name:string,args:any={},reason='Inspect actual tool feedback and fulfill the task.'):WorkerDecision=>({action:'tool',reason,toolCall:{name:name as any,arguments:{path:null,content:null,expectedHash:null,query:null,url:null,...args}}});
/** Test double is intentionally separate from the production worker. It branches
 * on actual check feedback, not an expected outcome hidden in worker context.
 * Authorship and predetermined repair content remain openly disclosed. */
export function offlinePortfolioModel(tools:LocalWorkTools):WorkerModel{return {kind:'offline_mock',async run(call:WorkerCall){
 const c=call.request.context as any;
 if(call.schema.required.includes('alternatives'))return mockResult({summary:'The local artifact was checked; retain the commercial uncertainty and examine the owner’s actual task result before new commitments.',claims:[],contradictions:[],unknowns:['Customer demand, accepted delivery and independent owner correction time are not established by a local rehearsal.'],alternatives:[{name:'Continue bounded preparation',caseFor:'Existing artifacts support a concrete owner inspection.',caseAgainst:'More mock variations cannot prove buyer value.',evidenceIds:[],decision:'retain'}],priority:45,rationale:'The observed local delivery closes the implementation task but leaves commercial evidence unchanged. Lower this venture’s immediate build priority and preserve capacity for distinct unresolved work.',cancelTaskIds:[],tasks:[]});
 const taskId=(c as any).taskBinding??call.request.scope.runId;const matched=tools.store.db.prepare("SELECT body FROM entities WHERE kind='local-workspace'").all().map(r=>JSON.parse(String(r.body))).find(w=>w.ventureId===call.ventureId&&hash(w.taskId).slice(0,24)===call.request.scope.runId.replace('portfolio-',''));
 if(!matched)return mockResult({action:'blocked',reason:'This offline fixture has no authored task recipe. Actual model work requires its own grant.',toolCall:null});
 const w=tools.load(call.ventureId,matched.taskId),observations=c.observations??[],last=observations.at(-1),path=w.kind==='software'?'app.html':'brief.json';
 if(!last)return mockResult(action('workspace.read',{path}));
 if(last.tool==='workspace.read'||last.tool==='workspace.replace')return mockResult(action('check.run'));
 if(last.tool==='check.run'&&last.result.checks.some((check:any)=>!check.passed)){
  const corrected=w.kind==='software'?quoteTrackerFiles():briefFiles(w.inputs,{purpose:call.ventureId==='release-readiness'?'release':'portfolio'});
  return mockResult(action('workspace.replace',{path,content:corrected.find(f=>f.path===path)!.content,expectedHash:w.manifest.files.find(f=>f.path===path)!.sha256},'The persisted mandatory check found a real defect in the inherited artifact. Apply the disclosed fixture repair and rerun the unchanged check.'));
 }
 if(last.tool==='check.run')return mockResult(action('artifact.publish_local'));
 return mockResult({action:'complete',reason:'The revised local deliverable passed the trusted checks and was published to local delivery storage. This is mock-driven infrastructure evidence, not demonstrated model competence or customer value.',toolCall:null});
 }};}
