import { randomBytes } from 'node:crypto';
import { createServer } from 'node:http';
import { createRequire } from 'node:module';
import { existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { requireThat } from '../contracts.ts';
import type { SourceFile, Check } from './products.ts';

export type QuoteState={schemaVersion:1;quotes:Array<{id:string;customer:string;lines:Array<{description:string;quantity:number;unitMinor:number}>;status:'quoted'|'scheduled'|'in_progress'|'completed'}>};
export const emptyQuoteState=():QuoteState=>({schemaVersion:1,quotes:[]});
const exact=(v:any,keys:string[])=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));
export function validateQuoteState(value:any):asserts value is QuoteState{
 const text=(s:any,n:number)=>typeof s==='string'&&s.trim().length>0&&s.length<=n;
 requireThat(exact(value,['schemaVersion','quotes'])&&value.schemaVersion===1&&Array.isArray(value.quotes)&&value.quotes.length<=500,'PREVIEW_STATE_INVALID');
 const ids=new Set<string>();
 for(const q of value.quotes){requireThat(exact(q,['id','customer','lines','status'])&&text(q.id,100)&&!ids.has(q.id)&&text(q.customer,200)&&['quoted','scheduled','in_progress','completed'].includes(q.status)&&Array.isArray(q.lines)&&q.lines.length>0&&q.lines.length<=100,'PREVIEW_QUOTE_INVALID');ids.add(q.id);let total=0;
  for(const l of q.lines){requireThat(exact(l,['description','quantity','unitMinor'])&&text(l.description,300)&&Number.isSafeInteger(l.quantity)&&l.quantity>=1&&l.quantity<=10000&&Number.isSafeInteger(l.unitMinor)&&l.unitMinor>=0&&l.unitMinor<=100000000,'PREVIEW_LINE_INVALID');total+=l.quantity*l.unitMinor;}
  requireThat(Number.isSafeInteger(total)&&total<=1000000000000,'PREVIEW_TOTAL_INVALID');
 }
 requireThat(Buffer.byteLength(JSON.stringify(value))<=512000,'PREVIEW_STATE_TOO_LARGE');
}
export type PreviewBinding={ventureId:string;taskId:string;manifestHash:string};
export type PreviewStateRequest=PreviewBinding&{operation:'read'|'write';expectedVersion?:number;state?:QuoteState};
export function validatePreviewRequest(body:any,binding:PreviewBinding):asserts body is PreviewStateRequest{
 requireThat(body&&body.ventureId===binding.ventureId&&body.taskId===binding.taskId&&body.manifestHash===binding.manifestHash,'PREVIEW_BINDING_MISMATCH');
 requireThat(body.operation==='read'||body.operation==='write','PREVIEW_OPERATION_DENIED');
 requireThat(exact(body,body.operation==='read'?['ventureId','taskId','manifestHash','operation']:['ventureId','taskId','manifestHash','operation','expectedVersion','state']),'PREVIEW_REQUEST_INVALID');
 if(body.operation==='write'){requireThat(Number.isSafeInteger(body.expectedVersion)&&body.expectedVersion>=0,'PREVIEW_VERSION_INVALID');validateQuoteState(body.state);}
}
const json=(x:any)=>JSON.stringify(x).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
export const previewCSP="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; frame-src 'self'; base-uri 'none'; form-action 'none'; object-src 'none'";
/** The iframe has no host filesystem, same-origin access, parent DOM access, or
 * network APIs. Browser-level request interception additionally blocks navigation
 * during checks. CSP alone is not claimed to block every self-navigation. */
export function renderPreview(options:PreviewBinding&{files:SourceFile[];stateEndpoint:string;csrf?:string;csrfHeader?:string;title?:string}):string{
 requireThat(/^\/(?!\/)[^\s]*$/.test(options.stateEndpoint),'PREVIEW_ENDPOINT_INVALID');
 const source=options.files.find(f=>f.path==='app.html')?.content;requireThat(typeof source==='string'&&source.length<=262144,'PREVIEW_SOURCE_REQUIRED');
 const nonce=randomBytes(24).toString('hex');const binding={ventureId:options.ventureId,taskId:options.taskId,manifestHash:options.manifestHash};
 const bootstrap=`(()=>{const nonce=${json(nonce)},pending=new Map();let seq=0;addEventListener('message',e=>{if(e.source!==parent||e.data?.channel!=='midas-preview-result'||e.data.nonce!==nonce)return;const p=pending.get(e.data.id);if(!p)return;clearTimeout(p.timer);pending.delete(e.data.id);e.data.ok?p.resolve(e.data.result):p.reject(Error(e.data.error||'Preview operation failed'));});function call(operation,state,expectedVersion){return new Promise((resolve,reject)=>{const id=String(++seq),timer=setTimeout(()=>{pending.delete(id);reject(Error('Save timed out; reload to inspect saved state.'));},10000);pending.set(id,{resolve,reject,timer});parent.postMessage({channel:'midas-preview',nonce,id,operation,...(operation==='write'?{state,expectedVersion}:{})},'*');});}Object.defineProperty(window,'midas',{value:Object.freeze({getState:()=>call('read'),saveState:(state,expectedVersion)=>call('write',state,expectedVersion)}),writable:false,configurable:false});})();`;
 const child="<!doctype html><meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'; frame-src 'none'; worker-src 'none'; base-uri 'none'; form-action 'none'; object-src 'none'\"><script>"+bootstrap+'</script>'+source;
 return '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="'+previewCSP+'"><title>Product preview</title><style>body{margin:0;font:14px system-ui;background:#f2f4f0;color:#243c33}header{padding:12px 18px;border-bottom:1px solid #ccc;display:flex;justify-content:space-between;gap:20px}iframe{border:0;width:100%;height:calc(100vh - 49px);background:white}#bridge-status{color:#587065}</style><header><b>Local product preview</b><span id="bridge-status">Saved data belongs to this product.</span></header><iframe id="product-frame" title="Quote desk product" sandbox="allow-scripts" referrerpolicy="no-referrer"></iframe><script>'+`
(()=>{const frame=document.getElementById('product-frame'),nonce=${json(nonce)},binding=${json(binding)},endpoint=${json(options.stateEndpoint)},headers={'content-type':'application/json',${json(options.csrfHeader??'x-csrf-token')}:${json(options.csrf??'')}};let queue=Promise.resolve(),count=0,started=Date.now();const accepted=new Set();
addEventListener('message',event=>{const m=event.data;if(event.source!==frame.contentWindow||event.origin!=='null'||!m||m.channel!=='midas-preview'||m.nonce!==nonce||typeof m.id!=='string'||m.id.length>64||accepted.has(m.id)||!['read','write'].includes(m.operation))return;
 if(Date.now()-started>60000){count=0;started=Date.now();}if(++count>120)return;accepted.add(m.id);const body={...binding,operation:m.operation,...(m.operation==='write'?{state:m.state,expectedVersion:m.expectedVersion}:{})};if(JSON.stringify(body).length>600000)return;
 queue=queue.then(async()=>{try{const response=await fetch(endpoint,{method:'POST',headers,credentials:'same-origin',body:JSON.stringify(body),redirect:'error'});const result=await response.json();if(!response.ok||result.error)throw Error(result.error||'Persistence request failed');frame.contentWindow.postMessage({channel:'midas-preview-result',nonce,id:m.id,ok:true,result},'*');document.getElementById('bridge-status').textContent='Saved version '+result.version;}catch(error){frame.contentWindow.postMessage({channel:'midas-preview-result',nonce,id:m.id,ok:false,error:error.message},'*');document.getElementById('bridge-status').textContent=error.message;}});
});frame.srcdoc=${json(child)};})();`+'</script></html>';
}

export async function browserModule():Promise<any>{
 const req=createRequire(import.meta.url);try{return req('playwright');}catch{}
 const candidate=join(homedir(),'.cache','codex-runtimes','codex-primary-runtime','dependencies','node','node_modules','playwright');
 requireThat(existsSync(candidate),'PLAYWRIGHT_DEPENDENCY_UNAVAILABLE');return req(candidate);
}
export async function launchCheckBrowser(){const {chromium}=await browserModule();
 const installed=process.platform==='win32'?['C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe','C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'].find(p=>existsSync(p)):undefined;
 return chromium.launch({headless:true,...(installed?{executablePath:installed}:{}),args:['--disable-background-networking','--disable-component-update','--disable-sync','--no-first-run']});
}
/** Mandatory checks are trusted code, outside all worker source revisions. */
export async function checkQuoteApplication(options:PreviewBinding&{files:SourceFile[];launchBrowser?:()=>Promise<any>;stateHandler?:(body:any)=>any}):Promise<Check[]>{
 const checks:Check[]=[];let version=0,state=emptyQuoteState(),writes=0;const binding={ventureId:options.ventureId,taskId:options.taskId,manifestHash:options.manifestHash};
 const stateHandler=options.stateHandler??((body:any)=>{validatePreviewRequest(body,binding);if(body.operation==='write'){requireThat(body.expectedVersion===version,'PREVIEW_STATE_STALE');state=structuredClone(body.state!);version++;}return {version,state};});
 const server=createServer(async(req,res)=>{try{if(req.method==='GET'&&req.url==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8','content-security-policy':previewCSP});res.end(renderPreview({...binding,files:options.files,stateEndpoint:'/state'}));return;}if(req.method==='POST'&&req.url==='/state'){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>600000)throw Error('REQUEST_TOO_LARGE');}const body=JSON.parse(raw);validatePreviewRequest(body,binding);const result=stateHandler(body);if(body.operation==='write')writes++;res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(result));return;}res.writeHead(404).end();}catch(e){res.writeHead(400,{'content-type':'application/json'}).end(JSON.stringify({error:(e as Error).message}));}});
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address() as any,origin='http://127.0.0.1:'+address.port;let browser:any;
 const record=(id:string,passed:boolean,summary:string,evidence?:any)=>checks.push({id,passed,required:true,summary,...(evidence?{evidence}:{})});
 try{
  browser=await (options.launchBrowser??launchCheckBrowser)();const context=await browser.newContext({serviceWorkers:'block',acceptDownloads:false});let blockedRequests=0;
  await context.routeWebSocket('**/*',(ws:any)=>ws.close());
  await context.route('**/*',async(route:any)=>{const u=new URL(route.request().url());if(u.origin!==origin){blockedRequests++;await route.abort('blockedbyclient');}else await route.continue();});
  const page=await context.newPage();page.setDefaultTimeout(7000);await page.goto(origin);let frame=page.frameLocator('#product-frame');await frame.locator('#notice').filter({hasText:'Ready'}).waitFor();
  record('software.sandbox',await page.locator('#product-frame').getAttribute('sandbox')==='allow-scripts','Product executes in an opaque-origin frame; host code is never evaluated.',{networkInterception:true});
  await frame.locator('#customer').fill('Acceptance customer');await frame.locator('.description').nth(0).fill('Visit');await frame.locator('.quantity').nth(0).fill('2');await frame.locator('.unit').nth(0).fill('10.00');await frame.locator('#add-line').click();await frame.locator('.description').nth(1).fill('Materials');await frame.locator('.unit').nth(1).fill('5.50');await frame.locator('#save').click();await frame.locator('#quotes article').waitFor();
  const total=await frame.locator('[data-total]').textContent();record('software.line-totals',total==='$25.50','Two $10.00 units plus $5.50 must total $25.50.',{actual:total,expected:'$25.50'});
  await frame.locator('[data-convert]').click();await frame.locator('[data-job]').waitFor();await frame.locator('[data-job]').selectOption('completed');await frame.locator('[data-status]').filter({hasText:'completed'}).waitFor();record('software.job-transition',true,'A saved quote converts to a job and its status updates.');
  await page.reload();frame=page.frameLocator('#product-frame');await frame.locator('#notice').filter({hasText:'Ready'}).waitFor();const persisted=stateHandler({...binding,operation:'read'}),saved=persisted.state?.quotes?.[0];record('software.persistence',await frame.locator('[data-status]').textContent()==='completed'&&await frame.locator('#quotes h3').textContent()==='Acceptance customer'&&saved?.customer==='Acceptance customer'&&saved?.status==='completed'&&saved?.lines?.length===2&&saved.lines[0].quantity===2&&saved.lines[0].unitMinor===1000&&saved.lines[1].unitMinor===550,'Customer, line items and completed job survive full page reload and agree with trusted persistence readback.',{durableWrites:writes,persistedVersion:persisted.version});
  await frame.locator('#export').click();const csv=await frame.locator('#export-data').inputValue();record('software.export',csv.includes('"Acceptance customer","completed","25.50"'),'CSV export agrees with the saved customer, status and computed monetary total.',{csv});
  const before=stateHandler({...binding,operation:'read'});await page.evaluate(()=>window.postMessage({channel:'midas-preview',nonce:'forged',id:'rogue',operation:'write',state:{schemaVersion:1,quotes:[]},expectedVersion:0},'*'));await page.waitForTimeout(50);const after=stateHandler({...binding,operation:'read'});record('software.bridge-isolation',JSON.stringify(before)===JSON.stringify(after),'A parent-window message cannot impersonate the product frame.');
  record('software.network',blockedRequests===0,'The acceptance journey requires no external network.',{blockedExternalRequests:blockedRequests});await context.close();
 }catch(e){record('software.journey',false,'Browser execution did not establish the required customer journey.',{error:(e as Error).message.slice(0,2000)});}
 finally{await browser?.close();await new Promise<void>(resolve=>server.close(()=>resolve()));}
 return checks;
}

export type PreviewAction={kind:'click'|'type'|'key'|'refresh'|'export';x?:number;y?:number;text?:string;key?:string};
type Session={id:string;binding:PreviewBinding;browser:any;context:any;page:any;server:any;origin:string;lastUsed:number;busy:boolean;blockedRequests:number;timer?:ReturnType<typeof setTimeout>};
/** Owner browsers receive pixels and bounded controls only. Authored source is
 * executed exclusively in a fresh managed browser context with all external
 * requests, WebSockets, service workers and downloads denied. */
export class InteractivePreviewSessions{
 private sessions=new Map<string,Session>();private opening=0;private launchBrowser:()=>Promise<any>;
 constructor(options:{launchBrowser?:()=>Promise<any>}={}){this.launchBrowser=options.launchBrowser??launchCheckBrowser;}
 binding(id:string){const s=this.sessions.get(id);requireThat(s,'PREVIEW_SESSION_NOT_FOUND');return structuredClone(s.binding);}
 async open(options:PreviewBinding&{files:SourceFile[];stateHandler:(body:any)=>any}){
  for(const s of this.sessions.values())if(Date.now()-s.lastUsed>900000)await this.close(s.id);
  requireThat(this.sessions.size+this.opening<4,'PREVIEW_SESSION_CAP');this.opening++;const binding={ventureId:options.ventureId,taskId:options.taskId,manifestHash:options.manifestHash},secret=randomBytes(24).toString('hex');let expectedOrigin='';
  const server=createServer(async(req,res)=>{try{requireThat(req.headers.host===new URL(expectedOrigin).host,'PREVIEW_HOST_DENIED');if(req.method==='GET'&&req.url==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8','content-security-policy':previewCSP,'cache-control':'no-store'});res.end(renderPreview({...binding,files:options.files,stateEndpoint:'/state',csrf:secret}));return;}
   if(req.method==='POST'&&req.url==='/state'){requireThat(req.headers['x-csrf-token']===secret&&req.headers.origin===expectedOrigin,'PREVIEW_REQUEST_DENIED');let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>600000)throw Error('REQUEST_TOO_LARGE');}const body=JSON.parse(raw);validatePreviewRequest(body,binding);const result=options.stateHandler(body);res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'}).end(JSON.stringify(result));return;}res.writeHead(404).end();
  }catch(e){res.writeHead(400,{'content-type':'application/json'}).end(JSON.stringify({error:(e as Error).message}));}});
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));expectedOrigin='http://127.0.0.1:'+(server.address() as any).port;let browser:any;
  try{browser=await this.launchBrowser();const context=await browser.newContext({viewport:{width:1100,height:850},serviceWorkers:'block',acceptDownloads:false});const id=randomBytes(24).toString('hex');const session:Session={id,binding,browser,context,page:null,server,origin:expectedOrigin,lastUsed:Date.now(),busy:false,blockedRequests:0};
   await context.route('**/*',async(route:any)=>{const r=route.request(),u=new URL(r.url());const mainFrame=session.page&&r.frame()===session.page.mainFrame();const allowed=mainFrame&&u.origin===expectedOrigin&&((u.pathname==='/'&&r.method()==='GET'&&r.isNavigationRequest())||(u.pathname==='/state'&&r.method()==='POST'&&!r.isNavigationRequest()));if(!allowed){session.blockedRequests++;await route.abort('blockedbyclient');}else await route.continue();});
   await context.routeWebSocket('**/*',(ws:any)=>{session.blockedRequests++;ws.close();});
   context.on('page',(page:any)=>{if(session.page&&page!==session.page)void page.close();});const page=await context.newPage();session.page=page;page.setDefaultTimeout(5000);page.on('download',(download:any)=>void download.cancel());page.on('dialog',(dialog:any)=>void dialog.dismiss());page.on('console',(message:any)=>{if(message.type()==='error'&&/Content Security Policy/i.test(message.text())&&/refused|violat|blocked/i.test(message.text()))session.blockedRequests++;});await page.goto(expectedOrigin);await page.frameLocator('#product-frame').locator('body').waitFor();this.sessions.set(id,session);return await this.image(session);
  }catch(error){await browser?.close();await new Promise<void>(resolve=>server.close(()=>resolve()));throw error;}finally{this.opening--;}
 }
 private async image(s:Session,extra:any={}){s.lastUsed=Date.now();if(s.timer)clearTimeout(s.timer);s.timer=setTimeout(()=>void this.close(s.id),900000);s.timer.unref();const bytes=await s.page.screenshot({type:'png',animations:'disabled'});return {sessionId:s.id,binding:s.binding,width:1100,height:850,image:{mimeType:'image/png',data:bytes.toString('base64')},blockedRequests:s.blockedRequests,...extra};}
 async act(id:string,action:PreviewAction){const s=this.sessions.get(id);requireThat(s,'PREVIEW_SESSION_NOT_FOUND');requireThat(Date.now()-s.lastUsed<=900000,'PREVIEW_SESSION_EXPIRED');requireThat(!s.busy,'PREVIEW_SESSION_BUSY');requireThat(action&&['click','type','key','refresh','export'].includes(action.kind),'PREVIEW_ACTION_DENIED');s.busy=true;try{let extra:any={};
  if(action.kind==='click'){requireThat(Number.isFinite(action.x)&&Number.isFinite(action.y)&&action.x!>=0&&action.x!<1100&&action.y!>=0&&action.y!<850,'PREVIEW_COORDINATES_INVALID');await s.page.mouse.click(action.x,action.y);}
  else if(action.kind==='type'){requireThat(typeof action.text==='string'&&action.text.length>0&&action.text.length<=1000,'PREVIEW_TEXT_INVALID');await s.page.keyboard.insertText(action.text);}
  else if(action.kind==='key'){requireThat(['Tab','Shift+Tab','Enter','Backspace','Delete','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Control+A','Meta+A','Escape','PageDown','PageUp'].includes(action.key??''),'PREVIEW_KEY_DENIED');await s.page.keyboard.press(action.key);}
  else if(action.kind==='refresh')await s.page.reload();
  else{await s.page.frameLocator('#product-frame').locator('#export').click();const text=await s.page.frameLocator('#product-frame').locator('#export-data').inputValue();requireThat(text.length<=262144,'PREVIEW_EXPORT_TOO_LARGE');extra={exportCsv:text};}
  await s.page.waitForTimeout(100);return await this.image(s,extra);
 }finally{s.busy=false;}}
 async screenshot(id:string){const s=this.sessions.get(id);requireThat(s,'PREVIEW_SESSION_NOT_FOUND');return this.image(s);}
 async close(id:string){const s=this.sessions.get(id);if(!s)return;this.sessions.delete(id);if(s.timer)clearTimeout(s.timer);await s.browser.close();await new Promise<void>(resolve=>s.server.close(()=>resolve()));}
 async closeAll(){for(const id of [...this.sessions.keys()])await this.close(id);}
}
/** Trusted UI for a remote local-browser session. No worker HTML/JS appears here. */
export function renderRemotePreview(options:PreviewBinding&{openEndpoint:string;actionEndpoint:string;csrf?:string;csrfHeader?:string}):string{
 for(const endpoint of [options.openEndpoint,options.actionEndpoint])requireThat(/^\/(?!\/)[^\s]*$/.test(endpoint),'PREVIEW_ENDPOINT_INVALID');
 const settings={...options};return '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'unsafe-inline\'; style-src \'unsafe-inline\'; img-src data:; connect-src \'self\'; base-uri \'none\'; form-action \'none\'"><title>Interactive local product</title><style>body{font:15px system-ui;margin:0;background:#eff3ee;color:#153e31}header{padding:16px;display:flex;gap:12px;align-items:center;flex-wrap:wrap}button,input{font:inherit;padding:10px;border:1px solid #95b6a5;border-radius:6px}button{background:#18513f;color:white;cursor:pointer}input{min-width:250px}#product{display:block;width:100%;max-width:1100px;margin:auto;border:1px solid #b4c4b8;outline:0}p{margin:8px 16px}textarea{width:95%;height:150px;margin:16px}</style><header><b>Interactive product</b><button id="refresh">Refresh saved work</button><button id="export">Get CSV export</button><input id="text" placeholder="Text for the selected product field"><button id="type">Type into product</button><button id="tab">Tab</button><button id="enter">Enter</button><button id="down">Scroll down</button><button id="up">Scroll up</button></header><p id="status" role="status">Opening isolated local browser…</p><img id="product" tabindex="0" alt="Live product browser. Click a field, then enter text using the toolbar or keyboard. Control+A or Command+A selects the field value."><textarea id="csv" readonly hidden aria-label="Exported CSV"></textarea><script>'+`
(()=>{const config=${json(settings)},img=document.getElementById('product'),status=document.getElementById('status');let sessionId=null,busy=false;async function send(endpoint,body){if(busy)return;busy=true;status.textContent='Updating product…';try{const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',[config.csrfHeader||'x-csrf-token']:config.csrf||''},credentials:'same-origin',redirect:'error',body:JSON.stringify(body)}),value=await response.json();if(!response.ok||value.error)throw Error(value.error||'Preview operation failed');sessionId=value.sessionId;img.src='data:'+value.image.mimeType+';base64,'+value.image.data;if(value.exportCsv!==undefined){document.getElementById('csv').value=value.exportCsv;document.getElementById('csv').hidden=false;}status.textContent='Product ready · saved data persists across refresh';}catch(e){status.textContent=e.message;}finally{busy=false;}}const action=a=>sessionId?send(config.actionEndpoint,{sessionId,...a}):null;img.onclick=e=>{const r=img.getBoundingClientRect();img.focus();action({kind:'click',x:(e.clientX-r.left)*1100/r.width,y:(e.clientY-r.top)*850/r.height});};img.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();action({kind:'key',key:e.metaKey?'Meta+A':'Control+A'});}else if(e.key.length===1&&!e.ctrlKey&&!e.metaKey){e.preventDefault();action({kind:'type',text:e.key});}else if(['Tab','Enter','Backspace','Delete','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Escape','PageDown','PageUp'].includes(e.key)){e.preventDefault();action({kind:'key',key:e.shiftKey&&e.key==='Tab'?'Shift+Tab':e.key});}};document.getElementById('type').onclick=()=>action({kind:'type',text:document.getElementById('text').value});document.getElementById('refresh').onclick=()=>action({kind:'refresh'});document.getElementById('export').onclick=()=>action({kind:'export'});document.getElementById('tab').onclick=()=>action({kind:'key',key:'Tab'});document.getElementById('enter').onclick=()=>action({kind:'key',key:'Enter'});document.getElementById('down').onclick=()=>action({kind:'key',key:'PageDown'});document.getElementById('up').onclick=()=>action({kind:'key',key:'PageUp'});send(config.openEndpoint,{ventureId:config.ventureId,taskId:config.taskId,manifestHash:config.manifestHash});})();`+'</script></html>';
}
