import {requireThat} from '../contracts.ts';

/** Replaceable execution requirements. The controller does not diagnose a business
 * from this profile; it only makes the supported local product job explicit. */
export const quoteProductV2={
 id:'quote-to-job-v2',version:2,path:'app.html',sourceHandoffBytes:24000,
 purpose:'A local quote and job tracker for a small service operator. This is a prototype; no customer sending, payment, deployment or account features.',
 files:'Implement in app.html with inline CSS and JavaScript. Other ordinary source files are retained but not loaded as assets. No external fonts, libraries, network or host commands. Forms may run JavaScript submit handlers with preventDefault; actual form navigation/submission is forbidden by CSP and request interception. The frame remains opaque: no same-origin access, service workers or parent DOM.',
 bridge:'await window.midas.getState() -> {state,version}; await window.midas.saveState(state,expectedVersion) -> {state,version}. Handle rejection visibly; never report saved before success. State persists in MIDAS SQLite across refresh, a fresh preview session and host-process restart using the same data directory. Do not use localStorage as authoritative state. Quote IDs stable across edits.',
 state:{exactKeys:true,schemaVersion:1,maxQuotes:500,quote:{keys:['id','customer','lines','status'],id:'unique nonblank <=100 characters',customer:'nonblank <=200 characters',lines:'1..100 rows',status:['quoted','scheduled','in_progress','completed']},line:{keys:['description','quantity','unitMinor'],description:'nonblank <=300 characters',quantity:'integer 1..10000',unitMinor:'integer USD cents 0..100000000'},total:'sum(quantity*unitMinor), safe integer <=1000000000000 USD cents',maxStateUTF8Bytes:512000},
 money:'USD only. Accept finite decimal dollars with at most two decimal places; reject negatives, blank prices, NaN, infinity and extra precision instead of silently rounding. Parse cents using decimal digits. Quantity must be an integer in bounds. Sum every line in integer minor units; format USD totals consistently.',
 selectors:{ready:'set data-ready="true" on body or app root only after state loaded',purpose:'h1 explains the product; include a short use instruction',customer:'#customer with associated label',description:'.description on each line input',quantity:'.quantity on each line input',unit:'.unit on each dollar input',addLine:'#add-line button',save:'#save button creates a new quote or updates the reopened quote',newQuote:'#new-quote button clears editing and returns to blank new quote',notice:'#notice with role=status or role=alert, visible success/error feedback; wording is yours',empty:'#empty-state visible useful guidance when no records',quotes:'#quotes contains one article per saved record; h3 contains customer',open:'[data-open] button within each article reopens that record into the form',total:'[data-total] within each article displays its USD total',status:'[data-status] within each article gives quoted/scheduled/in_progress/completed (case/space normalization allowed)',convert:'[data-convert] visible/enabled only for a quoted record; converts to scheduled',job:'[data-job] select for jobs only, values scheduled,in_progress,completed; selecting updates saved status',export:'#export button produces #export-data textarea'},
 csv:'RFC-style CSV with header customer,status,total_usd (id and other extra columns permitted). total_usd is a two-decimal numeric dollar value. Quoted or unquoted fields and LF/CRLF accepted; escape embedded quotes/commas. Export all saved records; if a user field starts =,+,-,@ prefix an apostrophe to avoid spreadsheet formula execution. A CSV here is a local export, not an invoice or sent offer.',
 journey:['First-time purpose, primary action and useful empty state without mission documentation.','Invalid or blank customer/description/quantity/price: no state mutation, visible useful error.','Create multi-line quote, save, reopen and edit without duplicating; creating a second quote must preserve the first.','Convert quoted record to scheduled, progress to in_progress/completed; controls and saved status agree.','Reload and fresh browser context recover the same customer, line items, totals and statuses.','Desktop (1280px) and narrow (390px) layouts: visible labeled controls, no horizontal page overflow, usable buttons (minimum 32 CSS px high), readable text.','No example records on first load. Any optional examples must be clearly labeled and explicitly loaded; the acceptance journey starts empty.'],
 review:'check.run executes the fixed journey and returns manifest-bound checks, bounded rendered text, controls, errors and geometry. These are actual browser/DOM observations, not model vision. Screenshots are retained separately for developer/owner inspection. Inspect failures and repair source, rerun checks, then publish locally and complete. Semantic fitness/design judgments remain model/development-assisted, never independent human validation.',
 callEconomy:'Current source and exact hashes are included in context when they fit. Avoid redundant reads. Budget at least check.run, artifact.publish_local and complete after a write; retain two more decisions for repair/recheck where possible. One model action per response; checking does not consume another inference itself.'
};
export const quoteV2Checks=['software.sandbox','software.empty','software.invalid-input','software.line-totals','software.reopen','software.second-quote','software.job-transition','software.persistence','software.fresh-session','software.export','software.feedback','software.responsive','software.bridge-isolation','software.network','software.handoff'];
export const businessSiteV1={
 id:'business-site-v1',version:1,path:'app.html',sourceHandoffBytes:24000,
 purpose:'A company-information website and local inquiry preparation application. It prepares an inquiry for owner review; it cannot send, book, charge, deploy or imply a confirmed estimate.',
 files:'Implement app.html with inline CSS/JavaScript. No external assets, credentials, network, host commands or server features. Source executes only inside the managed opaque browser frame.',
 evidence:'Display workspace.inputs.companyName and every workspace.inputs.evidence entry as an exact text excerpt with its sourceId. These are permitted company assertions, not independent validation. Do not infer prices, turnaround or availability. Fixture company content and inquiry records must be labeled test data.',
 bridge:'await window.midas.getState() returns {state,version}; await window.midas.saveState(state,expectedVersion) persists atomically. Display save failure and never claim success before acknowledgement. State survives refresh, new preview sessions and host restart using the same data directory; no localStorage authority.',
 state:{exactKeys:['schemaVersion','inquiries'],schemaVersion:1,maxInquiries:100,inquiry:{exactKeys:['id','name','need','details','status'],details:'array of {fieldId,value}: exactly one nonblank <=1000-character value for each controller-bound workspace.inputs.intakeFields entry; never guess missing details',id:'unique nonblank <=100 characters',name:'nonblank <=120 characters',need:'nonblank <=2000 characters',status:['draft','reviewed']},maximumUTF8Bytes:256000},
 selectors:{ready:'[data-ready="true"] after loading state',purpose:'h1',evidence:'[data-source-id] exact sourceId attributes with visible exact excerpts',name:'#name associated label',need:'#need associated label',requiredInformation:'[data-intake-field] inputs with exact configured field id; associated label includes its human-readable label',save:'#save saves new or reopened inquiry',notice:'#notice visible role=status/alert',empty:'#empty-state useful initial instruction',list:'#inquiries article with h3=name, [data-need]=need, [data-status]=draft/reviewed',open:'[data-open] within article',review:'[data-review] marks reviewed only after local owner action, never sent',fresh:'#new-inquiry clears editing',export:'#export produces #export-data textarea with exact JSON state'},
 journey:['Start with no fabricated inquiries and visible local-only notice.','Blank name, need or any configured required-information field does not mutate state and gives useful feedback. Values are reported data, not validated facts or a booking approval.','Save a complete inquiry, reopen and update same identity, mark reviewed, refresh and reopen a new browser session; records and status agree.','Export all saved inquiry records as JSON.','Desktop and 390px phone widths remain labeled, usable, and without horizontal overflow.'],
 correction:'The task may include an owner correction. Preserve source quotations and company identity; implement an actionable change in the authoritative artifact. Changed source invalidates previous checks and publication.',
 review:'check.run returns actual rendered text, DOM controls, errors and geometry. This is browser evidence, not model vision. Inspect it before complete. Deterministic finalization then publishes locally and verifies readback; independent semantic approval and business outcomes remain unknown.'
};
export const businessSiteChecks=['site.source-binding','site.empty','site.invalid-input','site.save-edit','site.review-state','site.persistence','site.fresh-session','site.export','site.responsive','software.sandbox','software.bridge-isolation','software.network','software.handoff'];
export const marketingPageV1={...businessSiteV1,id:'marketing-page-v1',version:1,purpose:'A source-grounded, responsive local commercial page with a coordinated offer, buyer problem, scope/process, proof limits, FAQ and next-step preparation. This is not a deployed site or a payment/send integration.',
 campaign:'Use workspace.inputs.campaign.foundation and authored campaign assets from the exact authenticated upstream artifact. Display canonical audience, offer and price exactly in [data-campaign-audience], [data-campaign-offer], [data-campaign-price]. Price and claim statuses remain visible. Preserve unknowns; do not add unverified claims.',
 sections:'Visible semantic sections with ids hero, problem, offer, process, proof, faq, next-step. Each section has a heading and useful substantive text. Provide nav links to offer and next-step. At least two FAQ disclosures use details/summary. The primary CTA links to #next-step. In the opaque srcdoc frame, handle section links with preventDefault and target.scrollIntoView; ordinary hash navigation can attempt a forbidden frame navigation. Include campaign artifact hash in data-campaign-hash. A complete local next-step record uses the same supported persistence bridge as the site profile; nothing is sent.'};
export const marketingPageChecks=[...businessSiteChecks,'marketing.sections','marketing.campaign-binding','marketing.navigation','marketing.faq'];
/** Generic, multi-file local application. The worker authors declarative data
 * models/actions plus frontend files; trusted MIDAS code owns the server,
 * validation, persistence, export and loopback-only runtime. */
export const functionalProjectV1={
 id:'functional-project-v1',version:1,path:'project.json',sourceHandoffBytes:24000,
 purpose:'A configurable local application with a worker-authored frontend and a trusted, persisted backend. It remains local: no customer sending, deployment, credentials, packages, shell commands, arbitrary server JavaScript or external network access.',
 files:'The authoritative source requires project.json, public/index.html, public/app.js and public/style.css; add ordinary static files only when useful. .mjs, .cjs, .ts and native modules are denied. project.json is strict JSON with version:1, a title/description, 1–12 generic entities with typed fields, and optional typed status-transition actions. For the first declared entity, render one labeled editable control for every field with data-project-field="field-id", a data-project-save button that creates or updates the reopened record, data-project-error for visible validation feedback, data-project-record on each visible saved row, and a data-project-open control in each row. Render every configured action for that entity as data-project-action="action-id". Read exact current files before editing. workspace.replace can add a file only with expectedHash:null; workspace.patch makes up to 12 literal single-match edits. Every accepted source revision invalidates checks, local publication and the prior preview identity.',
 backend:'MIDAS starts a trusted Node HTTP service on 127.0.0.1 for the exact source revision. It serves the frontend under CSP default-src/connect-src self; validates configured entity fields; persists records under the project runtime root; exports JSON at /api/export; uses optimistic update versions; and requires idempotency keys for record creation and transitions. The service interprets project.json and never executes worker-authored backend Node code. The worker cannot select a shell command, install a dependency, read a host path, receive environment variables or request a remote URL.',
 endpoints:'GET /api/health and /api/schema expose the bound profile/manifest. GET/POST /api/entities/:entity reads/creates configured records; PATCH /api/entities/:entity/:id performs a version-bound update; POST /api/entities/:entity/:id/actions/:action runs a configured transition; GET /api/export returns persisted local state. The application frontend should use only these same-origin endpoints and show useful validation/save feedback.',
 checks:'check.run validates the strict manifest and runs a fixed trusted HTTP journey in a disposable project state: frontend serving/CSP, typed record validation, idempotent create, export, and restart readback. The managed browser then uses the required first-entity markers to verify visible invalid-input feedback, create/readback, reopen/edit without duplication, configured action controls, and 390px no-overflow usability. It retains bounded DOM/action evidence plus desktop/narrow screenshots. This establishes mechanics only; it does not establish semantic fitness, customer acceptance, or business outcomes.',
 handoff:'The full JSON-serialized project source is bounded at 24000 UTF-8 bytes for this profile. This is an explicit all-files handoff; a larger project is rejected rather than truncated. Use workspace.list and workspace.read to retrieve exact hashes/content, and retain substantial room for review/repair.',
 journey:['Start with an empty persisted application state and a legible purpose.','Validate configured required values/types before a create/update; show a useful local error rather than claiming success.','Create a record, reload/restart the trusted backend, read it back and export current JSON.','Use idempotency keys for create/transition retry safety; duplicate requests must not duplicate local effects.','Use desktop and narrow layouts with labeled, usable controls.','Never implement an external send, account action, deployment, dependency installer, arbitrary server process or an unbounded command.']
};
export const functionalProjectChecks=['project.schema','project.preview','project.browser','project.persistence','project.restart'];
export function productProfile(id:string){requireThat(['quote-to-job-v1',quoteProductV2.id,businessSiteV1.id,marketingPageV1.id,functionalProjectV1.id].includes(id),'EXECUTION_PROFILE_UNAVAILABLE');return id===functionalProjectV1.id?functionalProjectV1:id===marketingPageV1.id?marketingPageV1:id===businessSiteV1.id?businessSiteV1:id===quoteProductV2.id?quoteProductV2:null;}
