/** Developer-authored product starting points. The runtime stores and revises these
 * ordinary source files; it does not branch on business names or fixture labels. */
export type SourceFile = {path:string;content:string};
export type WorkKind = 'software'|'service';
export const developerProvenance = 'Developer-authored starting point; no actual-model authorship claimed';
export const quoteTrackerFiles = (options:{defect?:boolean}={}):SourceFile[] => [{path:'app.html',content:`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quote desk</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f5f4ee;color:#172c2b;font:16px system-ui,sans-serif}main{max-width:1000px;margin:auto;padding:32px}header{display:flex;justify-content:space-between;align-items:center;gap:20px}h1{font-size:38px;margin:0}h2{font-size:22px}.muted{color:#596c69}section,article{background:white;border:1px solid #d9e1da;border-radius:14px;padding:22px;margin:20px 0}label{display:block;font-size:14px;margin:12px 0}input,select,button,textarea{font:inherit;border:1px solid #a4b5ae;border-radius:7px;padding:10px}input{width:100%}button{background:#174e43;color:white;cursor:pointer}button.secondary{background:white;color:#174e43}.line{display:grid;grid-template-columns:2fr 1fr 1fr;gap:12px}.actions{display:flex;gap:10px;flex-wrap:wrap}.amount{font-size:25px;font-weight:700}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:9px;border-bottom:1px solid #ddd}textarea{width:100%;min-height:130px}#notice{min-height:25px;color:#814413}@media(max-width:600px){main{padding:16px}.line{grid-template-columns:1fr}header{align-items:start;flex-direction:column}h1{font-size:30px}}</style></head>
<body><main><header><div><p class="muted">CUSTOMER OPERATIONS</p><h1>Quote desk</h1><p class="muted">Prepare a quote. Turn accepted work into a job.</p></div><button id="export" class="secondary">Export CSV</button></header><p id="notice" role="status">Loading saved work…</p>
<section><h2>New quote</h2><label>Customer<input id="customer" maxlength="200" autocomplete="off" placeholder="Customer or company"></label><div id="lines"></div><div class="actions"><button id="add-line" class="secondary">Add line</button><button id="save">Save quote</button></div><p>Total <strong id="draft-total" class="amount">$0.00</strong></p></section><section><h2>Quotes and jobs</h2><div id="quotes"></div></section><section id="export-panel" hidden><h2>Export</h2><p class="muted">Copy this CSV into your spreadsheet.</p><textarea id="export-data" readonly aria-label="CSV export"></textarea></section></main>
<script>
const $=id=>document.getElementById(id),escapeHTML=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
let state={schemaVersion:1,quotes:[]},version=0,busy=false;
function total(lines){return lines.reduce((sum,line)=>sum+${options.defect?'line.unitMinor':'line.quantity*line.unitMinor'},0);}
function addLine(){const row=document.createElement('div');row.className='line';row.innerHTML='<label>Description<input class="description" maxlength="300" placeholder="Work or material"></label><label>Quantity<input class="quantity" type="number" min="1" max="10000" step="1" value="1"></label><label>Unit price (USD)<input class="unit" type="number" min="0" max="1000000" step="0.01" value="0.00"></label>';$('lines').append(row);row.addEventListener('input',updateTotal);}
function readLines(){return [...document.querySelectorAll('.line')].map(row=>({description:row.querySelector('.description').value.trim(),quantity:Number(row.querySelector('.quantity').value),unitMinor:Math.round(Number(row.querySelector('.unit').value)*100)}));}
function updateTotal(){$('draft-total').textContent=money(total(readLines()));}
function render(){$('quotes').innerHTML=state.quotes.length?state.quotes.map(q=>'<article data-quote="'+escapeHTML(q.id)+'"><h3>'+escapeHTML(q.customer)+'</h3><p class="amount" data-total>'+money(total(q.lines))+'</p><p data-status>'+escapeHTML(q.status)+'</p><table><thead><tr><th>Work</th><th>Quantity</th><th>Unit price</th></tr></thead><tbody>'+q.lines.map(l=>'<tr><td>'+escapeHTML(l.description)+'</td><td>'+l.quantity+'</td><td>'+money(l.unitMinor)+'</td></tr>').join('')+'</tbody></table><div class="actions">'+(q.status==='quoted'?'<button data-convert="'+escapeHTML(q.id)+'">Convert to job</button>':'<label>Job status<select data-job="'+escapeHTML(q.id)+'"><option '+(q.status==='scheduled'?'selected':'')+'>scheduled</option><option '+(q.status==='in_progress'?'selected':'')+'>in_progress</option><option '+(q.status==='completed'?'selected':'')+'>completed</option></select></label>')+'</div></article>').join(''):'<p class="muted">No work saved yet. Create your first quote above.</p>';document.querySelectorAll('[data-convert]').forEach(b=>b.onclick=()=>changeStatus(b.dataset.convert,'scheduled'));document.querySelectorAll('[data-job]').forEach(b=>b.onchange=()=>changeStatus(b.dataset.job,b.value));}
async function persist(next){if(busy)throw Error('A save is already running.');busy=true;try{const result=await window.midas.saveState(next,version);state=result.state;version=result.version;render();$('notice').textContent='Saved';}finally{busy=false;}}
async function changeStatus(id,status){try{await persist({...state,quotes:state.quotes.map(q=>q.id===id?{...q,status}:q)});}catch(e){$('notice').textContent=e.message;render();}}
$('add-line').onclick=addLine;$('save').onclick=async()=>{try{const customer=$('customer').value.trim(),lines=readLines();if(!customer||!lines.length||lines.some(l=>!l.description||!Number.isSafeInteger(l.quantity)||l.quantity<1||!Number.isSafeInteger(l.unitMinor)||l.unitMinor<0))throw Error('Enter a customer, description, positive whole quantity and valid price.');await persist({...state,quotes:[...state.quotes,{id:'Q-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),customer,lines,status:'quoted'}]});$('customer').value='';$('lines').replaceChildren();addLine();updateTotal();}catch(e){$('notice').textContent=e.message;}};
$('export').onclick=()=>{const cell=x=>'"'+String(x).replace(/"/g,'""')+'"';$('export-data').value=[['Quote','Customer','Status','Total USD'].map(cell).join(','),...state.quotes.map(q=>[q.id,q.customer,q.status,(total(q.lines)/100).toFixed(2)].map(cell).join(','))].join('\\n');$('export-panel').hidden=false;};
addLine();window.midas.getState().then(result=>{state=result.state;version=result.version;render();$('notice').textContent='Ready';}).catch(e=>$('notice').textContent=e.message);
</script></body></html>`},{path:'README.md',content:'# Quote desk\nA local quote and job tracker. Prices use integer USD cents. Data is persisted by the trusted MIDAS preview bridge. No outbound customer communication or payment operation is implemented.\n'}];

export type BriefInputs={title:string;client:string;asOf:string;sources:Array<{id:string;title:string;text:string;rights:string}>;requiredSourceIds:string[]};
export const defaultServiceInputs:BriefInputs={title:'Service operations diagnostic',client:'Example facilities operator',asOf:'2026-09-12',sources:[
 {id:'service-log',title:'Permitted service completion log',text:'The August log records 40 scheduled visits. Six visits started more than 30 minutes late. Four of those six lacked a confirmed access contact. The log records no customer satisfaction score.',rights:'Developer-authored synthetic operations data; local preparation only.'},
 {id:'complaint-log',title:'Permitted complaint register',text:'Three August complaints mention arrival uncertainty. Two complaints request an arrival window. The register does not measure cancellation or revenue effects.',rights:'Developer-authored synthetic operations data; local preparation only.'},
 {id:'dispatch-policy',title:'Current dispatch procedure',text:'A dispatcher assigns the next day’s visits by 16:00. Access contacts are optional in the current checklist. Changes to customer messages require owner approval.',rights:'Developer-authored synthetic operations data; local preparation only.'}
],requiredSourceIds:['service-log','complaint-log','dispatch-policy']};
export function serviceBriefFiles(inputs:BriefInputs=defaultServiceInputs,options:{defect?:boolean}={}):SourceFile[]{
 const observations=inputs.sources.map((s,i)=>({id:'finding-'+(i+1),statement:s.title,sourceId:s.id,quote:options.defect&&i===0?'Every visit was completed on time.':s.text}));
 return [{path:'brief.json',content:JSON.stringify({title:inputs.title,client:inputs.client,asOf:inputs.asOf,observations,recommendation:{title:'Test a confirmed-access and arrival-window checklist',basis:'The supplied logs describe recurring arrival uncertainty. They do not establish causation or financial value.',steps:[{action:'Require a confirmed access contact before dispatch; log missing contacts as an exception.',owner:'dispatch lead',successMeasure:'Every pilot visit records contact confirmation or an explicit exception.'},{action:'Prepare a proposed arrival-window message for owner review before any customer sending.',owner:'service manager',successMeasure:'Owner reviews exact proposed message and permitted recipients.'},{action:'Compare late arrivals and access-related delays over the next 20 visits with the recorded baseline.',owner:'operations analyst',successMeasure:'A source-linked pilot log records scheduled and actual arrival times; report sample limitations.'}]},unknowns:['Whether confirmed access causes fewer late visits.','Whether customers value arrival-window messages.','Labor cost, cancellation effects and economic benefit remain unmeasured.'],obligations:[{id:'owner-review',description:'Owner reviews recommendation, pilot scope and any proposed customer communication.',owner:'service manager',status:'open'},{id:'delivery-ack',description:'Client acknowledges receipt of the completed local diagnostic packet.',owner:'engagement owner',status:'open'}],provenance:developerProvenance},null,2)}];
}
export type Check={id:string;passed:boolean;required:boolean;summary:string;evidence?:unknown};
export function checkServiceBrief(files:SourceFile[],inputs:BriefInputs):{checks:Check[];report:any|null}{
 const checks:Check[]=[];let report:any=null;
 try{report=JSON.parse(files.find(f=>f.path==='brief.json')?.content??'');}catch{checks.push({id:'service.structure',passed:false,required:true,summary:'brief.json must contain a JSON object.'});return {checks,report};}
 const text=(x:any,max=10000)=>typeof x==='string'&&x.trim().length>0&&x.length<=max;
 const structure=report&&typeof report==='object'&&!Array.isArray(report)&&text(report.title)&&text(report.client)&&text(report.asOf)&&Array.isArray(report.observations)&&report.observations.length>0&&report.observations.length<=50&&Array.isArray(report.recommendation?.steps)&&report.recommendation.steps.length>0&&report.recommendation.steps.length<=20&&text(report.recommendation.title)&&text(report.recommendation.basis)&&report.recommendation.steps.every((s:any)=>text(s.action)&&text(s.owner)&&text(s.successMeasure))&&Array.isArray(report.unknowns)&&report.unknowns.length>0&&report.unknowns.every((x:any)=>text(x))&&Array.isArray(report.obligations)&&report.obligations.length>0&&report.obligations.length<=30&&report.obligations.every((o:any)=>text(o.id,100)&&text(o.description)&&text(o.owner)&&o.status==='open')&&new Set(report.obligations.map((o:any)=>o.id)).size===report.obligations.length;
 checks.push({id:'service.structure',passed:Boolean(structure),required:true,summary:structure?'Readable recommendation, action owners, measures, unknowns and open obligations are present.':'Complete the required recommendation, actions, unknowns and delivery obligations.'});
 const sources=new Map(inputs.sources.map(s=>[s.id,s]));const refs=Array.isArray(report?.observations)&&report.observations.every((o:any)=>text(o.id,100)&&text(o.statement)&&text(o.quote)&&sources.has(o.sourceId)&&sources.get(o.sourceId)!.text.includes(o.quote));
 checks.push({id:'service.sources',passed:Boolean(refs),required:true,summary:refs?'Every observation quotes a permitted source exactly. Semantic interpretation still requires review.':'An observation has an unavailable source or a quote absent from that source.',evidence:{sourceHashesRequired:true,scope:'Exact quotation support; not independent causal or commercial validation'}});
 const coverage=Array.isArray(report?.observations)&&inputs.requiredSourceIds.every(id=>report.observations.some((o:any)=>o.sourceId===id));
 checks.push({id:'service.coverage',passed:Boolean(coverage),required:true,summary:coverage?'All required source documents are represented.':'Address every source required by the task contract.',evidence:{requiredSourceIds:inputs.requiredSourceIds}});
 const bound=report?.title===inputs.title&&report?.client===inputs.client&&report?.asOf===inputs.asOf;
 checks.push({id:'service.input-binding',passed:bound,required:true,summary:bound?'Packet is bound to the current client, title and reporting date.':'Packet metadata differs from the authorized input contract.'});
 return {checks,report};
}
const escapeHTML=(x:any)=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderServiceBrief(report:any,inputs:BriefInputs):string{
 const e=escapeHTML;return '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; base-uri \'none\'; form-action \'none\'"><title>'+e(report.title)+'</title><style>html{overflow-x:hidden}body{font:17px/1.6 system-ui;color:#173932;background:#faf9f4;max-width:900px;margin:40px auto;padding:25px;overflow-wrap:anywhere}h1{font-size:40px;line-height:1.15}h2{margin-top:35px}article{background:white;border:1px solid #cddcd3;padding:20px;margin:15px 0;border-radius:10px}blockquote{border-left:3px solid #8cb7a6;padding-left:18px;color:#4c625a}small{color:#54665f}li{margin-bottom:12px}@media(max-width:600px){body{margin:0;padding:16px;font-size:16px}h1{font-size:30px}article{padding:16px}blockquote{margin-left:0;margin-right:0;padding-left:14px}ol,ul{padding-left:22px}}</style><p>OPERATIONS DIAGNOSTIC · '+e(report.asOf)+'</p><h1>'+e(report.title)+'</h1><p>Prepared for '+e(report.client)+'</p><h2>Source observations</h2>'+report.observations.map((o:any)=>'<article><h3>'+e(o.statement)+'</h3><blockquote>'+e(o.quote)+'</blockquote><small>Source: '+e(o.sourceId)+'</small></article>').join('')+'<h2>'+e(report.recommendation.title)+'</h2><p>'+e(report.recommendation.basis)+'</p><ol>'+report.recommendation.steps.map((s:any)=>'<li><b>'+e(s.action)+'</b><br>Owner: '+e(s.owner)+'<br>Measure: '+e(s.successMeasure)+'</li>').join('')+'</ol><h2>Unknowns and test limits</h2><ul>'+report.unknowns.map((x:any)=>'<li>'+e(x)+'</li>').join('')+'</ul><h2>Delivery and follow-up obligations</h2><ul>'+report.obligations.map((o:any)=>'<li>'+e(o.description)+' — '+e(o.owner)+' · '+e(o.status)+'</li>').join('')+'</ul><h2>Source register</h2>'+inputs.sources.map(s=>'<p><b>'+e(s.id)+' · '+e(s.title)+'</b><br>'+e(s.rights)+'</p>').join('')+'<p><small>Local deliverable. Source assertions are not independently verified facts. Customer delivery acceptance and business impact have not been observed.</small></p></html>';
}
