import {createServer} from 'node:http';
import {hash,requireThat} from '../contracts.ts';
import {renderPreview,previewCSP,launchCheckBrowser,emptyQuoteState,validatePreviewRequest} from './preview.ts';
import type {PreviewBinding} from './preview.ts';
import type {SourceFile,Check} from './products.ts';
import {quoteProductV2} from './product-profiles.ts';

export function parseCSV(text:string){const rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(x=>x.length))rows.push(row);row=[];field='';}else field+=c;}requireThat(!quoted,'CSV_UNCLOSED_QUOTE');if(field.length||row.length){row.push(field);rows.push(row);}return rows;}
const normalized=(x:string)=>x.trim().toLowerCase().replace(/\s+/g,'_');
const dollars=(x:string)=>Number(x.replace(/USD/gi,'').replace(/[$,\s]/g,''));
export async function checkProductV2(options:PreviewBinding&{files:SourceFile[];launchBrowser?:()=>Promise<any>;stateHandler?:(body:any)=>any;saveScreenshot?:(name:string,data:Buffer)=>unknown}):Promise<Check[]>{
 const checks:Check[]=[],views:any[]=[],errors:string[]=[];let state=emptyQuoteState(),version=0,writes=0,phase='startup';
 const binding={ventureId:options.ventureId,taskId:options.taskId,manifestHash:options.manifestHash};
 const handler=options.stateHandler??((body:any)=>{if(body.operation==='write'){requireThat(body.expectedVersion===version,'PREVIEW_STATE_STALE');state=structuredClone(body.state);version++;}return {state,version};});
 const read=()=>handler({...binding,operation:'read'});const record=(id:string,passed:boolean,summary:string,evidence?:unknown,required=true)=>checks.push({id,passed,required,summary,...(evidence?{evidence}:{})});
 record('software.handoff',Buffer.byteLength(JSON.stringify(options.files))<=quoteProductV2.sourceHandoffBytes,'All source fits the declared complete downstream handoff.',{bytes:Buffer.byteLength(JSON.stringify(options.files)),limit:quoteProductV2.sourceHandoffBytes});
 let origin='',browser:any,context:any,page:any,blocked=0;
 const server=createServer(async(req,res)=>{try{if(req.method==='GET'&&req.url==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8','content-security-policy':previewCSP});res.end(renderPreview({...binding,files:options.files,executionProfile:'quote-to-job-v2',stateEndpoint:'/state'}));return;}if(req.method==='POST'&&req.url==='/state'){let raw='';for await(const c of req){raw+=c;requireThat(raw.length<=600000,'REQUEST_TOO_LARGE');}const body=JSON.parse(raw);validatePreviewRequest(body,binding);const result=handler(body);if(body.operation==='write')writes++;res.writeHead(200,{'content-type':'application/json'}).end(JSON.stringify(result));return;}res.writeHead(404).end();}catch(e){res.writeHead(400,{'content-type':'application/json'}).end(JSON.stringify({error:(e as Error).message}));}});
 await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+(server.address() as any).port;
 const frame=()=>page.frameLocator('#product-frame');
 async function open(width=1280){context=await browser.newContext({viewport:{width,height:900},serviceWorkers:'allow',acceptDownloads:false});await context.routeWebSocket('**/*',(ws:any)=>{blocked++;ws.close();});await context.route('**/*',async(route:any)=>{const req=route.request(),u=new URL(req.url());const allowed=page&&req.frame()===page.mainFrame()&&u.origin===origin&&(u.pathname==='/'&&req.method()==='GET'&&req.isNavigationRequest()||u.pathname==='/state'&&req.method()==='POST'&&!req.isNavigationRequest());if(!allowed){blocked++;await route.abort('blockedbyclient');}else await route.continue();});page=await context.newPage();page.setDefaultTimeout(3000);page.on('pageerror',(e:Error)=>errors.push(e.message.slice(0,220)));page.on('dialog',(d:any)=>void d.dismiss());context.on('page',(p:any)=>{if(p!==page)void p.close();});await page.goto(origin);await frame().locator('[data-ready="true"]').waitFor();}
 async function snapshot(name:string){if(!page)return;try{const f=page.frames().find((f:any)=>f.parentFrame()===page.mainFrame());if(!f)return;const dom=await f.evaluate(()=>{const visible=(el:Element)=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none';};const controls=Array.from(document.querySelectorAll('button,input,select,textarea')).filter(visible).slice(0,18).map((el:any)=>{const r=el.getBoundingClientRect();return {tag:el.tagName.toLowerCase(),id:el.id||null,text:(el.getAttribute('aria-label')||el.labels?.[0]?.textContent||el.textContent||'').trim().slice(0,80),type:el.type??null,disabled:Boolean(el.disabled),box:{x:Math.round(r.x),y:Math.round(r.y),width:Math.round(r.width),height:Math.round(r.height)}};});return {title:document.querySelector('h1')?.textContent?.trim()??'',text:document.body.innerText.slice(0,1400),viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,controls};});const ref=options.saveScreenshot?.(name,await page.screenshot({type:'png',animations:'disabled'}));views.push({name,...dom,screenshot:ref??null});}catch(e){views.push({name,error:(e as Error).message.slice(0,200)});}}
 const fill=async(customer:string,description:string,quantity:string,unit:string)=>{await frame().locator('#customer').fill(customer);await frame().locator('.description').first().fill(description);await frame().locator('.quantity').first().fill(quantity);await frame().locator('.unit').first().fill(unit);};
 try{
  browser=await (options.launchBrowser??launchCheckBrowser)();await open();phase='empty state';await snapshot('empty-desktop');
  record('software.sandbox',await page.locator('#product-frame').getAttribute('sandbox')==='allow-scripts allow-forms','Actual source runs inside an opaque-origin browser frame.');
  record('software.empty',read().state.quotes.length===0&&(await frame().locator('h1').innerText()).trim().length>0&&await frame().locator('#empty-state').isVisible()&&(await frame().locator('#empty-state').innerText()).trim().length>=8,'First load has no fabricated customer records, a product heading and visible empty-state guidance.');
  phase='invalid input';let invalidOK=true;const initialNotice=await frame().locator('#notice').innerText(),invalidMessages:string[]=[];
  for(const [customer,description,quantity,unit]of [['','Visit','1','10.00'],['Acceptance customer','','1','10.00'],['Acceptance customer','Visit','0','10.00'],['Acceptance customer','Visit','1','-1.00'],['Acceptance customer','Visit','1','1.999'],['Acceptance customer','Visit','','10.00'],['Acceptance customer','Visit','1.5','10.00'],['Acceptance customer','Visit','1','']]){await fill(customer,description,quantity,unit);const before=hash(read());await frame().locator('#save').click();await page.waitForTimeout(80);const message=await frame().locator('#notice').innerText();invalidMessages.push(message.slice(0,250));invalidOK&&=hash(read())===before&&await frame().locator('#notice').isVisible()&&message.trim().length>=5;}
  record('software.invalid-input',invalidOK&&invalidMessages[0]!==initialNotice,'Missing customer/description, zero quantity, negative and over-precision prices must not save and must show useful feedback.');
  phase='create quote';await fill('Acceptance customer','Visit','2','10.00');await frame().locator('#add-line').click();await frame().locator('.description').nth(1).fill('Materials');await frame().locator('.quantity').nth(1).fill('1');await frame().locator('.unit').nth(1).fill('5.50');await frame().locator('#save').click();await frame().locator('#quotes article').first().waitFor();
  const first=read().state.quotes[0],id=first?.id;
  record('software.line-totals',read().state.quotes.length===1&&first?.customer==='Acceptance customer'&&first.lines.length===2&&first.lines[0].description==='Visit'&&first.lines[0].quantity===2&&first.lines[0].unitMinor===1000&&first.lines[1].description==='Materials'&&first.lines[1].unitMinor===550&&dollars(await frame().locator('[data-total]').first().innerText())===25.5,'Rendered and persisted quote agree on both work descriptions and integer-cent arithmetic.');
  record('software.feedback',(await frame().locator('#notice').innerText())!==invalidMessages.at(-1)&&await frame().locator('#notice').isVisible()&&(await frame().locator('#notice').innerText()).trim().length>=5,'Saving produces visible feedback; usefulness also requires assisted/owner review.');
  phase='reopen';await frame().locator('[data-open]').first().click();const reopened=(await frame().locator('.description').first().inputValue())==='Visit';await frame().locator('.description').first().fill('Revised visit');await frame().locator('#save').click();await page.waitForTimeout(100);record('software.reopen',reopened&&read().state.quotes.length===1&&read().state.quotes[0].id===id&&read().state.quotes[0].lines[0].description==='Revised visit','Reopen/edit saves the same quote identity without duplication.');
  phase='second quote';await frame().locator('#new-quote').click();await fill('=Example, "Local"','Separate work','1','0.10');await frame().locator('#save').click();await page.waitForTimeout(100);const all=read().state.quotes;record('software.second-quote',all.length===2&&new Set(all.map((q:any)=>q.id)).size===2&&all.find((q:any)=>q.id===id)?.lines[0].description==='Revised visit'&&all.some((q:any)=>q.customer==='=Example, "Local"'&&q.lines[0].unitMinor===10),'A second independent quote preserves the prior customer, work and identity.');
  phase='job transitions';const article=()=>frame().locator('#quotes article').filter({has:frame().locator('h3').filter({hasText:'Acceptance customer'})});await article().locator('[data-convert]').click();await article().locator('[data-job]').waitFor();let transitions=read().state.quotes.find((q:any)=>q.id===id)?.status==='scheduled';for(const status of ['in_progress','completed']){await article().locator('[data-job]').selectOption(status);await page.waitForTimeout(90);transitions&&=read().state.quotes.find((q:any)=>q.id===id)?.status===status&&normalized(await article().locator('[data-status]').innerText())===status;}transitions&&=!(await article().locator('[data-convert]').count())||!await article().locator('[data-convert]').isVisible()||await article().locator('[data-convert]').isDisabled();record('software.job-transition',transitions,'Quote converts once; all job states agree with persisted values and available controls.');
  const stable=structuredClone(read().state);phase='refresh persistence';await page.reload();await frame().locator('[data-ready="true"]').waitFor();record('software.persistence',hash(read().state)===hash(stable)&&await frame().locator('#quotes article').count()===2&&normalized(await article().locator('[data-status]').innerText())==='completed','Full state and rendered jobs survive reload.',{durableWrites:writes,readbackState:stable});
  phase='CSV export';await frame().locator('#export').click();const csv=parseCSV(await frame().locator('#export-data').inputValue()),head=csv[0]?.map(normalized)??[],ci=head.indexOf('customer'),si=head.indexOf('status'),ti=head.indexOf('total_usd');const exported=ci>=0&&si>=0&&ti>=0&&csv.length===3&&stable.quotes.every((q:any)=>csv.slice(1).some(row=>row[ci]===(/^[=+\-@]/.test(q.customer)?"'"+q.customer:q.customer)&&normalized(row[si])===q.status&&row[ti]===(q.lines.reduce((n:number,l:any)=>n+l.quantity*l.unitMinor,0)/100).toFixed(2)));record('software.export',exported,'Parsed CSV contains every saved customer, status and two-decimal total regardless of legal quoting/newline style.',{columns:head,rowCount:csv.length-1});
  await snapshot('completed-desktop');phase='fresh session';await context.close();await open();record('software.fresh-session',hash(read().state)===hash(stable)&&await frame().locator('#quotes article').count()===2,'A fresh isolated browser context loads the complete saved records from trusted persistence.');
  phase='narrow layout';await page.setViewportSize({width:390,height:844});await snapshot('completed-narrow');const narrow=views.at(-1);const mandatory=['#customer','.description','.quantity','.unit','#add-line','#save','#new-quote','#export','[data-open]','[data-job]'];const controlsPresent=(await Promise.all(mandatory.map(selector=>frame().locator(selector).first().isVisible()))).every(Boolean);const allGeometry=await page.frames().find((f:any)=>f.parentFrame()===page.mainFrame()).evaluate(()=>Array.from(document.querySelectorAll('button,input,select,textarea')).every((el:any)=>{const r=el.getBoundingClientRect(),style=getComputedStyle(el);if(!r.width||!r.height||style.display==='none'||style.visibility==='hidden')return true;return r.x>=-1&&r.right<=innerWidth+2&&(el.tagName!=='BUTTON'||r.height>=32)&&Boolean((el.getAttribute('aria-label')||el.labels?.[0]?.textContent||el.textContent||'').trim());}));const responsive=allGeometry&&controlsPresent&&narrow.controls.length>0&&narrow.viewport===390&&narrow.scrollWidth<=392&&narrow.controls?.every((c:any)=>c.box.width>0&&c.box.x>=-1&&c.box.x+c.box.width<=392&&(c.tag!=='button'||c.box.height>=32)&&c.text.length>0);let narrowInteraction=false;if(controlsPresent){await frame().locator('[data-open]').first().click();const reopened=await frame().locator('.description').first().inputValue();await frame().locator('#save').click();await page.waitForTimeout(100);narrowInteraction=reopened==='Revised visit'&&hash(read().state)===hash(stable);await frame().locator('#export').click();narrowInteraction&&=await frame().locator('#export-data').isVisible();}record('software.responsive',Boolean(responsive&&narrowInteraction),'At 390px, visible controls fit without horizontal page overflow, have labels and usable button height; narrow reopen/save/export works. DOM/geometry checks do not establish aesthetic quality.');
  const before=hash(read());await page.evaluate(()=>window.postMessage({channel:'midas-preview',nonce:'forged',id:'rogue',operation:'write',state:{schemaVersion:1,quotes:[]},expectedVersion:0},'*'));await page.waitForTimeout(40);record('software.bridge-isolation',hash(read())===before,'Forged parent messages cannot mutate product state.');
 }catch(e){record('software.journey',false,'The actual journey stopped at '+phase+'.',{phase,error:(e as Error).message.slice(0,700)});await snapshot('failure-'+phase.replace(/\s+/g,'-'));}
 finally{record('software.network',blocked===0&&errors.length===0,'No external request or uncaught browser error occurred in this journey.',{blockedRequests:blocked,pageErrors:errors.slice(0,8)});record('software.browser-observation',true,'Actual rendered text, control labels and geometry; screenshots are retained but not transmitted as model vision.',{profile:quoteProductV2.id,manifestHash:options.manifestHash,views,independentHumanReview:false},false);await browser?.close();await new Promise<void>(r=>server.close(()=>r()));}
 return checks;
}
