import { createServer, type Server } from 'node:http';
import { extname } from 'node:path';
import { randomUUID } from 'node:crypto';
import { hash, requireThat } from '../contracts.ts';
import { parseProjectManifest, projectPath, type ProjectEntity, type ProjectField, type ProjectManifest } from './project-contracts.ts';
import { ProjectWorkspace, type ProjectState } from './project-workspace.ts';

type Reply = { status: number; body: unknown };
const csp = "default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-src 'none'; worker-src 'none'; manifest-src 'none'; frame-ancestors 'none'";
const contentType: Record<string, string> = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml' };
function json(res: any, status: number, body: unknown) { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', 'content-security-policy': csp }); res.end(JSON.stringify(body)); }
async function body(req: any) { let text = ''; for await (const chunk of req) { text += chunk; requireThat(Buffer.byteLength(text) <= 256_000, 'PROJECT_REQUEST_BYTES'); } try { return JSON.parse(text || '{}'); } catch { throw Error('PROJECT_REQUEST_JSON'); } }
function errorCode(error: unknown) { return error instanceof Error ? error.message : 'PROJECT_REQUEST_FAILED'; }
function validField(field: ProjectField, value: unknown) { if (field.type === 'string') { if (typeof value !== 'string') return false; if (field.required && value.trim().length === 0) return false; if (field.maxLength !== undefined && value.length > field.maxLength) return false; if (field.values && !field.values.includes(value)) return false; return true; } if (field.type === 'integer') return typeof value === 'number' && Number.isSafeInteger(value) && (field.min === undefined || value >= field.min) && (field.max === undefined || value <= field.max); return typeof value === 'boolean'; }
function validateRecord(entity: ProjectEntity, candidate: any, partial: boolean) { requireThat(candidate && typeof candidate === 'object' && !Array.isArray(candidate), 'PROJECT_RECORD_INVALID'); requireThat(Object.keys(candidate).every(key => Object.hasOwn(entity.fields, key)), 'PROJECT_RECORD_UNKNOWN_FIELD'); for (const [key, field] of Object.entries(entity.fields)) { if (partial && !Object.hasOwn(candidate, key)) continue; if (!Object.hasOwn(candidate, key)) { requireThat(!field.required, 'PROJECT_RECORD_FIELD_REQUIRED'); continue; } requireThat(validField(field, candidate[key]), 'PROJECT_RECORD_FIELD_INVALID'); } }
function entity(manifest: ProjectManifest, id: string) { const found = manifest.entities.find(item => item.id === id); requireThat(found, 'PROJECT_ENTITY_NOT_FOUND'); return found; }
function stateFor(workspace: ProjectWorkspace, manifest: ProjectManifest) { const state = workspace.state(); for (const item of manifest.entities) state.entities[item.id] ??= []; return state; }

/** The trusted backend interprets a constrained data/action manifest. It never
 * imports or executes worker server modules, and it owns HTTP, persistence,
 * source binding, export, validation, and idempotency. */
export class TrustedProjectServer {
  readonly workspace: ProjectWorkspace; readonly manifestHash: string; readonly manifest: ProjectManifest; private server: Server | null = null; private origin: string | null = null;
  constructor(workspace: ProjectWorkspace) { this.workspace = workspace; const revision = workspace.revision(); this.manifestHash = revision.manifestHash; const source = workspace.read('project.json'); this.manifest = parseProjectManifest(source.content); }
  url() { requireThat(this.origin, 'PROJECT_SERVER_NOT_STARTED'); return this.origin; }
  private stale() { return this.workspace.revision().manifestHash !== this.manifestHash; }
  async start() { requireThat(!this.server, 'PROJECT_SERVER_STARTED'); this.server = createServer((req, res) => void this.handle(req, res)); await new Promise<void>((resolve, reject) => { this.server!.once('error', reject); this.server!.listen(0, '127.0.0.1', () => resolve()); }); this.origin = 'http://127.0.0.1:' + (this.server.address() as any).port; return { url: this.origin, manifestHash: this.manifestHash }; }
  async close() { const server = this.server; this.server = null; this.origin = null; if (server) await new Promise<void>(resolve => server.close(() => resolve())); }
  private async handle(req: any, res: any) { try { requireThat(req.headers.host === new URL(this.url()).host, 'PROJECT_HOST_DENIED'); if (this.stale()) return json(res, 409, { error: 'PROJECT_PREVIEW_STALE', manifestHash: this.manifestHash }); const url = new URL(req.url, this.url());
      if (req.method === 'GET' && url.pathname === '/api/health') return json(res, 200, { ok: true, profile: 'project-workspace-v1', manifestHash: this.manifestHash, title: this.manifest.title });
      if (req.method === 'GET' && url.pathname === '/api/schema') return json(res, 200, { manifest: this.manifest, manifestHash: this.manifestHash });
      if (req.method === 'GET' && url.pathname === '/api/export') return json(res, 200, { manifestHash: this.manifestHash, state: stateFor(this.workspace, this.manifest) });
      const segments = url.pathname.split('/').filter(Boolean); if (segments[0] === 'api' && segments[1] === 'entities' && segments.length >= 3) return await this.entities(req, res, segments.slice(2));
      if (req.method === 'GET') return this.static(res, url.pathname); json(res, 404, { error: 'PROJECT_ROUTE_NOT_FOUND' });
    } catch (error) { json(res, 400, { error: errorCode(error) }); } }
  private static(res: any, pathname: string) { const relativePath = pathname === '/' ? 'public/index.html' : 'public/' + decodeURIComponent(pathname.replace(/^\/+/, '')); projectPath(relativePath); const file = this.workspace.read(relativePath); res.writeHead(200, { 'content-type': contentType[extname(relativePath)] ?? 'application/octet-stream', 'cache-control': 'no-store', 'content-security-policy': csp, 'x-midas-project-manifest': this.manifestHash, 'x-content-type-options': 'nosniff' }); res.end(file.content); }
  private async entities(req: any, res: any, parts: string[]) { const entityId = parts[0] ?? ''; const definition = entity(this.manifest, entityId); const state = stateFor(this.workspace, this.manifest); const records = state.entities[entityId];
    if (req.method === 'GET' && parts.length === 1) return json(res, 200, { entity: entityId, records, version: state.version, manifestHash: this.manifestHash });
    if (req.method === 'POST' && parts.length === 1) { const request = await body(req); const key = req.headers['idempotency-key']; requireThat(typeof key === 'string' && /^[A-Za-z0-9_.-]{8,128}$/.test(key), 'PROJECT_IDEMPOTENCY_REQUIRED'); const requestHash=hash({operation:'create',entity:entityId,record:request.record}); if (state.operations[key]) { const prior=state.operations[key]; requireThat(prior.requestHash===requestHash&&prior.operation==='create'&&prior.entity===entityId,'PROJECT_IDEMPOTENCY_CONFLICT'); return json(res, prior.status, prior.body); } requireThat(records.length < 5_000 && Object.keys(state.operations).length < 10_000, 'PROJECT_STATE_LIMIT'); validateRecord(definition, request.record, false); const record = { id: randomUUID(), ...structuredClone(request.record), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; records.push(record); const response: Reply = { status: 201, body: { record, version: state.version + 1, duplicate: false } }; state.operations[key] = {...response,requestHash,operation:'create',entity:entityId,recordId:record.id}; const saved = this.workspace.saveState(state, state.version); return json(res, 201, { ...response.body as any, version: saved.version }); }
    requireThat(parts.length >= 2, 'PROJECT_ROUTE_NOT_FOUND'); const record = records.find(item => item.id === parts[1]); if (!record || typeof record.id !== 'string') throw Error('PROJECT_RECORD_NOT_FOUND'); const recordId = record.id;
    if (req.method === 'PATCH' && parts.length === 2) { const request = await body(req); requireThat(Number.isSafeInteger(request.expectedVersion) && request.expectedVersion === state.version, 'PROJECT_STATE_STALE'); validateRecord(definition, request.record, true); Object.assign(record, structuredClone(request.record), { updatedAt: new Date().toISOString() }); const saved = this.workspace.saveState(state, state.version); return json(res, 200, { record, version: saved.version }); }
    if (req.method === 'POST' && parts.length === 4 && parts[2] === 'actions') { const action = (this.manifest.actions ?? []).find(item => item.id === parts[3] && item.entity === entityId); requireThat(action, 'PROJECT_ACTION_NOT_FOUND'); const key = req.headers['idempotency-key']; requireThat(typeof key === 'string' && /^[A-Za-z0-9_.-]{8,128}$/.test(key), 'PROJECT_IDEMPOTENCY_REQUIRED'); const requestHash=hash({operation:'action',entity:entityId,recordId,action:action.id}); if (state.operations[key]) { const prior=state.operations[key]; requireThat(prior.requestHash===requestHash&&prior.operation==='action'&&prior.entity===entityId&&prior.recordId===recordId,'PROJECT_IDEMPOTENCY_CONFLICT'); return json(res, prior.status, prior.body); } requireThat(Object.keys(state.operations).length < 10_000, 'PROJECT_STATE_LIMIT'); if (action.from) requireThat(action.from.includes(String(record.status)), 'PROJECT_ACTION_STATE_DENIED'); Object.assign(record, structuredClone(action.set), { updatedAt: new Date().toISOString() }); const response: Reply = { status: 200, body: { record, version: state.version + 1, action: action.id, duplicate: false } }; state.operations[key] = {...response,requestHash,operation:'action',entity:entityId,recordId}; const saved = this.workspace.saveState(state, state.version); return json(res, 200, { ...response.body as any, version: saved.version }); }
    throw Error('PROJECT_ROUTE_NOT_FOUND');
  }
}
