import { hash,requireThat } from '../contracts.ts';
import { Portfolio } from './core.ts';
import { ProcedureRegistry } from './learning.ts';
import { WORKER_PROCEDURE,TOOL_NAMES } from './worker.ts';
import { EXECUTIVE_PROCEDURE } from './planning.ts';
import { EvidenceLibrary } from './evidence.ts';

/** Additive release preparation. Old proposals and observed work stay intact. */
export function prepareOperatingRelease(p:Portfolio,e:EvidenceLibrary){
 const registry=new ProcedureRegistry(p.store),prepared=[];
 for(const capability of ['research.investigate','quality.review','portfolio.plan','software.build','service.brief','portfolio.reassess'])registry.baseline({id:'baseline-'+capability.replace('.','-')+'-v2',scope:{capability,population:'owner-permitted-portfolio-jobs-v1'},procedure:capability.startsWith('portfolio.')?EXECUTIVE_PROCEDURE:WORKER_PROCEDURE,strongBaselineReference:'Excellent evidence, task contract, tools, correction opportunity and bounded resources; no measured specialist advantage.'});
 for(const v of p.snapshot().ventures){
  const id=v.id+'/operating-release-v2';if(p.store.get('portfolio-plan',id))continue;
  for(const previous of ['investigate-v1','review-v1','decide-v1']){const task=p.store.get('portfolio-task',v.id+'/'+previous);if(task&&task.attempts===0&&['queued','paused'].includes(task.status))p.controlTask(task.id,'cancel');}
  const old=p.store.get('portfolio-task',v.id+'/live-investigation');if(old&&old.attempts===0&&['queued','paused'].includes(old.status))p.controlTask(old.id,'cancel');
  const binding=(capability:string)=>({requiresGrant:true,feedbackPolicy:'defer_to_declared_decision',procedureScope:{capability,population:'owner-permitted-portfolio-jobs-v1'},baselineProcedureId:'baseline-'+capability.replace('.','-')+'-v2'});
  const investigate={id:'investigate-v2',title:'Investigate the opportunity and produce a decision brief',objective:v.goal+' Challenge the inherited proposal, including replacing or rejecting it. Use public search to find relevant evidence beyond the prepared corpus, fetch decision-relevant sources, assess buyer pain, substitutes, reachability, delivery and owner workload. Write a complete useful sourced brief with a concrete next action. Do not infer commercial validation.',lane:'research' as const,capability:'research.investigate',dependsOn:[],acceptance:['A useful sourced recommendation or rejection, alternatives, unknowns and accountable next actions.','Current independent source/structure checks and local delivery readback.'],allowedTools:[...TOOL_NAMES],requiredCompetencies:['evidence-grounded-work'],requiredChecks:['delivery.current'],inputs:binding('research.investigate'),resource:{modelCalls:8,localToolRuns:10},maxAttempts:1};
  const review={id:'review-v2',title:'Review the actual investigation and correct the recommendation',objective:'Read the actual upstream report and its permitted sources. Challenge its reasoning, useful alternatives, distribution, speculative economics and owner burden. Correct the authoritative recommendation and action steps when justified; retain it when adequate. Check the resulting packet and deliver it locally. No needless refusal wording or invented weakness.',lane:'build' as const,capability:'quality.review',dependsOn:['investigate-v2'],acceptance:['Substantive review of the actual artifact and any justified changes preserved.','Source references, metadata and open obligations remain accurate; independent checks pass.'],allowedTools:TOOL_NAMES.filter(t=>!['research.search','research.fetch'].includes(t)),requiredCompetencies:['source-review'],requiredChecks:['delivery.current'],inputs:binding('quality.review'),resource:{modelCalls:6,localToolRuns:8},maxAttempts:1};
  const plan={id:'decide-v2',title:'Decide the next useful work from the reviewed result',objective:'Use the actual reviewed recommendation and evidence to retain, replace or reject the business hypothesis, then propose only work that can change a consequential decision. A sufficient baseline needs no invented specialist. Separate research, reversible development and owner commercial commitment. Additional proposed tasks remain subject to capability and signed aggregate limits.',lane:'research' as const,capability:'portfolio.plan',dependsOn:v.id==='midas-intelligence'?[]:['review-v2'],acceptance:['A source-bound work plan or justified stop with alternatives and observable next actions.'],allowedTools:[] as string[],requiredChecks:['proposal.reference_checks'],inputs:binding('portfolio.plan'),resource:{modelCalls:1,localToolRuns:0},maxAttempts:1};
  prepared.push(p.addPlan(v.id,{id:'operating-release-v2',rationale:'Replace the unexecuted planning-only proposal with investigate → actual artifact review → decision and bounded work. This prepares a new unsigned scope, not spending authority.',evidenceIds:e.list(v.id).map(s=>s.id),tasks:v.id==='midas-intelligence'?[plan]:[investigate,review,plan]}));
 }
 return {prepared,authority:'unsigned_preparation_only',providerRequests:0};
}

export const operatingPacket={summary:'MIDAS now has a connected local portfolio workspace: evidence, executable assignments, source editing, independent checks, local delivery, observations and reprioritization. Actual-model business execution for these jobs remains unsigned.',authorship:'Development-assistant synthesis of implementation and retained evidence; not an autonomous MIDAS market finding.',implemented:['Working quote-to-job product with persistence and export.','Complete source-grounded decision/service packets and exact revision history.','Runtime actions follow tool feedback; planning can create executable work, and observations can change priority.'],bottlenecks:[{title:'Commercial evidence',reason:'No identified buyer has accepted the offer or demonstrated willingness to pay.',next:'A sourced investigation should test alternatives and prepare one concrete validation action.'},{title:'Actual worker competence',reason:'These local workers were deterministic mocks. Prior Astra support observations do not qualify these software and research jobs.',next:'Run an end-to-end strong baseline with the exact tools and evaluate the actual deliverable.'},{title:'Owner access and independent outcome evidence',reason:'No connected customer account, independent correction timing, reconciled new provider bill or deployed unattended host.',next:'Keep channel connection optional; capture actual owner/use outcomes without inventing labor or revenue.'}],nextDecision:'Approve the separately versioned bounded Astra operating grant, with optional controlled Gmail test selected separately. No specialization calls release without a consequential observed weakness and a fair comparison.',unsupportedClaims:['Autonomous business success','Specialist superiority','Optimal team assignment','Customer demand or revenue','Unattended remote operation']};
