/** Trusted preparation of dynamically planned jobs. No expected diagnosis or
 * finished deliverable is supplied. This describes the actual bounded tools. */
import { requireThat } from '../contracts.ts';
import { Portfolio } from './core.ts';
import type { Task } from './contracts.ts';
import { EvidenceLibrary } from './evidence.ts';
import { LocalWorkTools } from './tools.ts';

export const REPORT_HANDOFF_RULE='Keep the complete brief.json at or below 18000 UTF-8 bytes when a downstream planning task must read it in full. Use concise exact supporting excerpts. Larger reports require an explicit revised handoff rather than silent truncation.';

export const SERVICE_FILE_CONTRACT={path:'brief.json',description:'Write a complete JSON document. These are operational requirements visible before work, not hidden evaluator answers.',shape:{title:'exact workspace.inputs.title',client:'exact workspace.inputs.client',asOf:'exact workspace.inputs.asOf',observations:[{id:'unique descriptive identifier, <=100 characters',statement:'source-supported observation, not invented causal certainty',sourceId:'permitted workspace.inputs.sources ID',quote:'nonempty exact substring of that permitted source text; see context.sources or research.read for full text'}],recommendation:{title:'actual recommendation, rejection or next evidence-gathering decision',basis:'explain alternatives, evidence, economics and uncertainty',steps:[{action:'concrete next action',owner:'required responsibility; availability may be unknown',successMeasure:'observable condition'}]},unknowns:['material unanswered question'],obligations:[{id:'unique identifier <=100 characters',description:'unresolved review, evidence, or delivery obligation',owner:'responsible role',status:'open'}]},bounds:{observations:[1,50],steps:[1,20],obligations:[1,30],textCharacters:[1,10000]},rules:[REPORT_HANDOFF_RULE,'Represent every requiredSourceIds entry in observations; do not treat all sources as equally reliable.','Use current permitted sources; exact quotation proves reference support only.','Owner/customer acceptance and independent correction time remain unknown until evidence is recorded.','No messages or external commitments are executed by local publication.']};
export const SOFTWARE_FILE_CONTRACT={path:'app.html',profile:'quote-to-job-v1',description:'Implement customer + description/quantity/unit USD price input, line totals, save quote, convert to job, scheduled/in_progress/completed status, persisted state and CSV export. Source runs only inside the isolated browser.',bridge:'window.midas.getState() returns {state,version}; window.midas.saveState(state,expectedVersion) returns updated {state,version}. Use optimistic concurrency.',state:{schemaVersion:1,quotes:[{id:'unique nonempty string',customer:'nonempty customer name',lines:[{description:'nonempty string',quantity:'integer 1..10000',unitMinor:'safe integer USD cents >=0'}],status:'quoted | scheduled | in_progress | completed'}]},selectors:{customer:'#customer',description:'.description',quantity:'.quantity',unit:'.unit',save:'#save',convert:'[data-convert]',job:'[data-job]',total:'[data-total]',export:'#export',csv:'#export-data'},limits:'For a downstream artifact review or operating handoff, keep JSON.stringify(files) within 24000 UTF-8 bytes; larger source requires a revised handoff, never silent truncation. Use only ordinary source files; no external network, host commands or filesystem access. This tool profile does not claim arbitrary SaaS execution.'};
export function createTaskPreparer(portfolio:Portfolio,tools:LocalWorkTools,evidence:EvidenceLibrary){return (task:Task)=>{
 const venture=portfolio.getVenture(task.ventureId),sources=evidence.list(task.ventureId);
 requireThat(sources.length>0,'PERMITTED_JOB_EVIDENCE_REQUIRED');
 if(task.capability==='software.build'){
  tools.seed(task.ventureId,task.id,{kind:'software',files:[{path:'app.html',content:'<!doctype html><html lang="en"><title>Unimplemented product</title><body><h1>Product implementation pending</h1></body></html>'}],inputs:{profile:'quote-to-job-v1'},provenance:'Controller-created blank workspace; subsequent source authorship is recorded per actual runtime attempt.'});return;
 }
 requireThat(['service.brief','research.investigate','quality.review','commercial.prepare'].includes(task.capability),'EXECUTABLE_CAPABILITY_UNAVAILABLE');
 if(task.capability==='quality.review'||(task.inputs as any)?.authoritativeArtifactId){
  const target=(task.inputs as any)?.authoritativeArtifactId,bindings=task.inputArtifacts.filter(b=>{const a=portfolio.store.get('portfolio-artifact',b.artifactId);return a?.content?.manifest&&(!target||b.artifactId===target||b.artifactId===task.ventureId+'/'+target);});
  requireThat(bindings.length===1,'ONE_AUTHORITATIVE_REVIEW_ARTIFACT_REQUIRED');const a=portfolio.store.get('portfolio-artifact',bindings[0].artifactId);requireThat(a&&a.ventureId===task.ventureId&&a.sha256===bindings[0].sha256,'AUTHORITATIVE_REVIEW_INPUT_STALE');
  const original=tools.load(task.ventureId,a.taskId);requireThat(original.manifest.sha256===a.content?.manifest?.sha256&&original.published?.manifestHash===original.manifest.sha256,'AUTHORITATIVE_REVIEW_SOURCE_CHANGED');tools.download(task.ventureId,a.taskId);tools.seed(task.ventureId,task.id,{kind:original.kind,files:original.files,inputs:original.inputs,provenance:'Runtime review of preserved upstream artifact '+a.sha256+'; original source authorship retained.'});
  portfolio.store.transaction(()=>{const current=portfolio.getTask(task.id);portfolio.store.put('portfolio-task',task.id,{...current,inputs:{...(current.inputs as any??{}),authoritativeArtifactId:a.id}},(current as any)._version);});return;
 }
 tools.seed(task.ventureId,task.id,{kind:'service',files:[{path:'brief.json',content:'{}'}],inputs:{title:task.title,client:venture.name,asOf:new Date().toISOString().slice(0,10),sources:sources.map(s=>({id:s.id,title:s.title,text:s.text,rights:s.rights})),requiredSourceIds:sources.filter(s=>s.rights==='owner_supplied').map(s=>s.id)},provenance:'Blank controller workspace; content must be produced by the runtime. No predetermined conclusion.'});
};}
