import {campaignChecks,checkCampaign,campaignFiles} from './campaign-profile.ts';
import { randomUUID } from 'node:crypto';
import { join } from 'node:path';
import { StateStore } from '../state.ts';
import { hash, rawHash, requireThat, scopeKey } from '../contracts.ts';
import type { Scope, Ref } from '../contracts.ts';
import { checkServiceBrief, renderServiceBrief } from './products.ts';
import type { SourceFile, WorkKind, BriefInputs, Check } from './products.ts';
import { checkQuoteApplication, emptyQuoteState, validatePreviewRequest, launchCheckBrowser } from './preview.ts';
import type { PreviewStateRequest } from './preview.ts';
import {checkOperatingPacket,renderOperatingPacket} from './operating-profile.ts';
import {checkProductV2} from './product-check-v2.ts';
import {productProfile,quoteV2Checks,businessSiteChecks,marketingPageChecks,functionalProjectChecks} from './product-profiles.ts';
import {checkBusinessSite} from './business-site-check.ts';
import {emptyBusinessSiteState} from './business-site-state.ts';
import {sourceHandoff} from './source-handoff.ts';
import {applySourcePatch,validateSourcePatch} from './source-repair.ts';
import {ProjectWorkspace} from './project-workspace.ts';
import {TrustedProjectServer} from './project-server.ts';
import {runProjectCommand} from './project-check.ts';
import {validateProjectSource} from './project-contracts.ts';
import {ManagedProjectPreviewSessions} from './project-preview.ts';
import type {ProjectPreviewAction} from './project-preview.ts';

export type Manifest={revision:number;sha256:string;files:Array<{path:string;sha256:string;bytes:number}>;ref:Ref};
export type Workspace={ventureId:string;taskId:string;kind:WorkKind;files:SourceFile[];inputs:any;provenance:string;manifest:Manifest;checks:Check[];checkedManifest:string|null;published:any|null;_version?:number};
export type ToolCall={ventureId:string;taskId:string;tool:string;args:any;invocationId?:string;operationId?:string};
export type ToolObservation={ok:boolean;tool:string;observationId:string;manifest:Manifest|null;checks:Check[];changes:any[];output:any;error?:string};
const requiredChecks={software:['software.sandbox','software.line-totals','software.job-transition','software.persistence','software.export','software.bridge-isolation','software.network'],service:['service.structure','service.sources','service.coverage','service.input-binding']};
export const mandatoryCheckIds=(kind:WorkKind,profile?:string)=>kind==='service'&&profile==='commercial-campaign-v1'?[...requiredChecks.service,...campaignChecks]:kind==='software'&&profile==='functional-project-v1'?[...functionalProjectChecks]:kind==='software'&&profile==='marketing-page-v1'?[...marketingPageChecks]:kind==='software'&&profile==='business-site-v1'?[...businessSiteChecks]:kind==='software'&&profile==='quote-to-job-v2'?[...quoteV2Checks]:[...requiredChecks[kind]];
export const localToolIds=['workspace.list','workspace.read','workspace.replace','workspace.patch','workspace.candidate_read','check.run','artifact.publish_local'] as const;
const pathCheck=(path:any)=>requireThat(typeof path==='string'&&path.length<=150&&/^[A-Za-z0-9][A-Za-z0-9_.-]*(?:\/[A-Za-z0-9][A-Za-z0-9_.-]*)*$/.test(path)&&!path.split('/').some(p=>p==='.'||p==='..'||p.startsWith('.')),'WORKSPACE_PATH_DENIED');
function validateFiles(files:SourceFile[]){requireThat(Array.isArray(files)&&files.length>0&&files.length<=32,'WORKSPACE_FILES_INVALID');let bytes=0;const seen=new Set();for(const f of files){pathCheck(f.path);requireThat(!seen.has(f.path)&&typeof f.content==='string'&&Buffer.byteLength(f.content)<=262144,'WORKSPACE_FILE_INVALID');seen.add(f.path);bytes+=Buffer.byteLength(f.content);}requireThat(bytes<=1048576,'WORKSPACE_SIZE_LIMIT');}
/** Workspace source is stored as immutable SQLite artifacts, never written to a
 * host executable path. Only trusted browser/document tools interpret it. */
export class LocalWorkTools{
 readonly store:StateStore;readonly root:string;readonly scopeFor:(ventureId:string)=>Scope;readonly launchBrowser?:()=>Promise<any>;readonly projectPreviews:ManagedProjectPreviewSessions;
 constructor(options:{store:StateStore;root:string;scopeFor:(ventureId:string)=>Scope;taskFor?:(ventureId:string,taskId:string)=>any;browserLauncher?:()=>Promise<any>}){this.store=options.store;this.root=options.root;this.scopeFor=options.scopeFor;this.launchBrowser=options.browserLauncher;this.projectPreviews=new ManagedProjectPreviewSessions({launchBrowser:options.browserLauncher});}
 private key(ventureId:string,taskId:string){requireThat(typeof taskId==='string'&&taskId.length>0&&taskId.length<=250&&!/[\x00-\x1f]/.test(taskId),'TASK_ID_INVALID');return scopeKey(this.scopeFor(ventureId))+'/'+encodeURIComponent(taskId);}
 private manifest(s:Scope,taskId:string,kind:WorkKind,files:SourceFile[],inputs:any,revision:number,parent?:Ref):Manifest{
  validateFiles(files);const entries=[...files].sort((a,b)=>a.path.localeCompare(b.path)).map(f=>({path:f.path,sha256:rawHash(f.content),bytes:Buffer.byteLength(f.content)}));const digest=hash({kind,files:entries,inputs});
  const id='source-'+hash(taskId).slice(0,16)+'-'+revision;const ref=this.store.record(s,id,'LocalSourceRevision',{taskId,kind,revision,sha256:digest,files,inputs},parent?[parent]:[]);return {revision,sha256:digest,files:entries,ref};
 }
 seed(ventureId:string,taskId:string,input:{kind:WorkKind;files:SourceFile[];inputs?:any;provenance:string}):Manifest{
  requireThat(['software','service'].includes(input.kind)&&typeof input.provenance==='string'&&input.provenance.length>0,'WORKSPACE_SEED_INVALID');const key=this.key(ventureId,taskId),existing=this.store.get('local-workspace',key);if(existing){requireThat(existing.kind===input.kind,'WORKSPACE_KIND_PINNED');return existing.manifest;}
  const inputs=structuredClone(input.inputs??{}),files=structuredClone(input.files);if(input.kind==='software'){productProfile(inputs.profile??'quote-to-job-v1');if(inputs.profile==='functional-project-v1')validateProjectSource(files);}if(input.kind==='service'){requireThat(Array.isArray(inputs.sources)&&Array.isArray(inputs.requiredSourceIds)&&inputs.sources.length>0,'SERVICE_INPUTS_REQUIRED');for(const s of inputs.sources)requireThat(typeof s.id==='string'&&typeof s.text==='string'&&s.text.length<=50000&&typeof s.rights==='string'&&typeof s.title==='string','SERVICE_SOURCE_INVALID');requireThat(new Set(inputs.sources.map((s:any)=>s.id)).size===inputs.sources.length&&inputs.requiredSourceIds.every((id:string)=>inputs.sources.some((s:any)=>s.id===id)),'SERVICE_SOURCE_SCOPE');}
  return this.store.transaction(()=>{const manifest=this.manifest(this.scopeFor(ventureId),taskId,input.kind,files,inputs,1);this.store.put('local-workspace',key,{ventureId,taskId,kind:input.kind,files,inputs,provenance:input.provenance,manifest,checks:[],checkedManifest:null,published:null},null);return manifest;});
 }
 load(ventureId:string,taskId:string):Workspace{const w=this.store.get('local-workspace',this.key(ventureId,taskId));requireThat(w&&w.ventureId===ventureId&&w.taskId===taskId,'WORKSPACE_NOT_FOUND');return w;}
 /** Persistent owner-preview runtime. It mirrors the exact immutable source
  * revision but is not the disposable project state used by check.run. */
 projectRuntime(ventureId:string,taskId:string){
  const w=this.load(ventureId,taskId);requireThat(w.kind==='software'&&w.inputs.profile==='functional-project-v1','FUNCTIONAL_PROJECT_PROFILE_REQUIRED');
  const project=new ProjectWorkspace(join(this.root,'functional-project-runtime'),'project-'+hash({workspace:this.key(ventureId,taskId)}).slice(0,32));let existing:any=null;
  try{existing=project.revision();}catch{project.seed(w.files);return project;}
  const current=new Map<string,{path:string;sha256:string;bytes:number}>(existing.files.map((file:any)=>[file.path,file]));requireThat(existing.files.every((file:any)=>w.files.some(source=>source.path===file.path)),'PROJECT_MIRROR_SOURCE_REMOVAL_DENIED');
  for(const file of w.files){const prior=current.get(file.path);if(!prior||prior.sha256!==rawHash(file.content))project.replace({path:file.path,content:file.content,expectedHash:prior?.sha256??null});}
  return project;
 }
 async openProjectPreview(ventureId:string,taskId:string){const source=this.load(ventureId,taskId);requireThat(source.published?.manifestHash===source.manifest.sha256,'LOCAL_PUBLICATION_REQUIRED');const workspace=this.projectRuntime(ventureId,taskId),server=new TrustedProjectServer(workspace),opened=await server.start();return {...opened,server,workspace,localManifestHash:source.manifest.sha256};}
 async openManagedProjectPreview(ventureId:string,taskId:string,viewportWidth=1100){return this.projectPreviews.open(()=>this.openProjectPreview(ventureId,taskId),viewportWidth);}
 async actManagedProjectPreview(sessionId:string,action:ProjectPreviewAction){return this.projectPreviews.act(sessionId,action);}
 async closeManagedProjectPreview(sessionId:string){return this.projectPreviews.close(sessionId);}
 repairCandidate(ventureId:string,taskId:string,id?:string){
  const key=this.key(ventureId,taskId),head=this.store.get('workspace-repair-head',key),w=this.load(ventureId,taskId);
  if(!id&&(!head?.active||head.baseManifestHash!==w.manifest.sha256))return null;
  const candidateId=id??head?.candidateId;requireThat(typeof candidateId==='string'&&/^candidate-[a-f0-9]{32}$/.test(candidateId),'CANDIDATE_ID_INVALID');
  const record=this.store.get('workspace-rejected-candidate',key+'/'+candidateId);requireThat(record&&record.taskId===taskId&&record.ventureId===ventureId&&rawHash(record.content)===record.sha256,'CANDIDATE_NOT_FOUND_OR_CHANGED');
  return {...record,active:Boolean(head?.active&&head.candidateId===candidateId&&head.baseManifestHash===w.manifest.sha256)};
 }
 /** Controller-only evidence refresh. Workers cannot edit permissions/checks. */
 updateInputs(ventureId:string,taskId:string,inputs:BriefInputs,reason:string):Manifest{
  const w=this.load(ventureId,taskId),key=this.key(ventureId,taskId);requireThat(w.kind==='service'&&reason.trim().length>0,'TRUSTED_INPUT_UPDATE_INVALID');
  requireThat(inputs.title===w.inputs.title&&inputs.client===w.inputs.client&&inputs.asOf===w.inputs.asOf,'TRUSTED_INPUT_METADATA_PINNED');
  requireThat(Array.isArray(inputs.sources)&&inputs.sources.length>0&&inputs.sources.every(s=>s&&typeof s.id==='string'&&s.id.trim().length>0&&s.id.length<=200&&typeof s.text==='string'&&s.text.length<=50000&&typeof s.rights==='string'&&typeof s.title==='string')&&new Set(inputs.sources.map(s=>s.id)).size===inputs.sources.length,'SERVICE_SOURCE_INVALID');
  requireThat(Array.isArray(inputs.requiredSourceIds)&&w.inputs.requiredSourceIds.every((id:string)=>inputs.requiredSourceIds.includes(id))&&inputs.requiredSourceIds.every(id=>inputs.sources.some(s=>s.id===id)),'REQUIRED_SOURCE_REMOVAL_DENIED');
  requireThat(w.inputs.sources.every((source:{id:string})=>inputs.sources.some(s=>s.id===source.id)),'SOURCE_REMOVAL_DENIED');
  if(hash(inputs)===hash(w.inputs))return w.manifest;
  return this.store.transaction(()=>{const latest=this.load(ventureId,taskId);requireThat(latest._version===w._version,'WORKSPACE_CONCURRENT');const manifest=this.manifest(this.scopeFor(ventureId),taskId,w.kind,w.files,inputs,w.manifest.revision+1,w.manifest.ref);this.store.put('local-workspace',key,{...w,inputs:structuredClone(inputs),manifest,checks:[],checkedManifest:null,published:null},w._version!);this.store.event(this.scopeFor(ventureId),'portfolio.input_contract_updated',{taskId,reason,previousManifest:w.manifest.sha256,manifest:manifest.sha256,sourceIds:inputs.sources.map(s=>s.id)});return manifest;});
 }
 toolContract(){return [{id:'workspace.list',description:'Inspect the current file paths, hashes and check results.'},{id:'workspace.read',description:'Read one authoritative source file. Arguments: {path}.'},{id:'workspace.replace',description:'Replace or create one source file. Arguments: {path,content,expectedHash}; expectedHash is null only for a new file. Rejected complete candidates remain separate repair targets; the authoritative source is unchanged.'},{id:'workspace.patch',description:'Apply at most 12 literal single-match edits atomically. Arguments: {path,expectedHash,candidateId,serialization,edits:[{find,replace}]}. candidateId=null edits the authoritative file; otherwise use the active repair candidate ID and its hash. Each find must occur exactly once in sequence. serialization=preserve retains bytes outside edits; compact-json explicitly parses/re-serializes JSON without whitespace (zero edits allowed). Both the model-edited proposal and serialization are preserved. No automatic content removal. New bytes must satisfy the unchanged handoff and checks.'},{id:'workspace.candidate_read',description:'Read the complete retained rejected candidate in explicit chunks: path=candidate ID, query=decimal UTF-16 character offset, starting 0. At most 8000 characters per chunk; nextOffset marks remaining content. No provider fetch. Unused legacy arguments null.'},{id:'check.run',description:'Run mandatory trusted checks on the current source manifest. No host commands. Arguments: {}.'},{id:'artifact.publish_local',description:'Publish a verified current revision to local delivery storage. Arguments: {}. Customer acceptance remains an open obligation.'}];}
 recoverOperation(operationId:string,ventureId:string,taskId:string):ToolObservation|null{return this.store.get('local-tool-call',this.key(ventureId,taskId)+'/'+operationId)?.result??null;}
 async execute(call:ToolCall):Promise<ToolObservation>{
  requireThat(!call.operationId||!call.invocationId||call.operationId===call.invocationId,'TOOL_OPERATION_ID_CONFLICT');const key=this.key(call.ventureId,call.taskId),s=this.scopeFor(call.ventureId),id=call.operationId??call.invocationId??randomUUID(),attemptKey=key+'/'+id;
  const digest=hash({ventureId:call.ventureId,taskId:call.taskId,tool:call.tool,args:call.args??{}}),prior=this.store.get('local-tool-call',attemptKey);
  if(prior){requireThat(prior.requestHash===digest,'TOOL_INVOCATION_CONFLICT');requireThat(prior.result,'TOOL_RESULT_UNCERTAIN');return prior.result;}
  this.store.transaction(()=>this.store.put('local-tool-call',attemptKey,{id,requestHash:digest,status:'running',tool:call.tool,startedAt:new Date().toISOString()},null));
  const saveResult=(result:ToolObservation)=>{const row=this.store.get('local-tool-call',attemptKey);if(row.result)return row.result;this.store.put('local-tool-call',attemptKey,{...row,status:'completed',result,finishedAt:new Date().toISOString()},row._version);this.store.record(s,'tool-'+hash(attemptKey).slice(0,32),'LocalToolObservation',result);this.store.event(s,'portfolio.tool_observed',{taskId:call.taskId,tool:call.tool,ok:result.ok,observationId:id,manifestHash:result.manifest?.sha256??null});return result;};
  const finish=(result:ToolObservation)=>this.store.transaction(()=>saveResult(result));
  try{requireThat((localToolIds as readonly string[]).includes(call.tool),'TOOL_NOT_ALLOWED');let w=this.load(call.ventureId,call.taskId);let args=structuredClone(call.args??{});let output:any=null,changes:any[]=[];
   if(call.tool==='workspace.list')output={files:w.manifest.files,kind:w.kind,inputs:w.inputs};
   else if(call.tool==='workspace.read'){pathCheck(args.path);const file=w.files.find(f=>f.path===args.path);requireThat(file,'WORKSPACE_FILE_NOT_FOUND');output={...file,sha256:rawHash(file.content)};}
   else if(call.tool==='workspace.candidate_read'){
    requireThat(typeof args.query==='string'&&/^\d+$/.test(args.query),'CANDIDATE_OFFSET_INVALID');const c=this.repairCandidate(call.ventureId,call.taskId,args.path)!,offset=Number(args.query);
    requireThat(Number.isSafeInteger(offset)&&offset>=0&&offset<=c.content.length&&!(offset>0&&/[\uD800-\uDBFF]/.test(c.content[offset-1])&&/[\uDC00-\uDFFF]/.test(c.content[offset]??'')),'CANDIDATE_OFFSET_INVALID');
    let end=Math.min(c.content.length,offset+8000);if(end<c.content.length&&/[\uD800-\uDBFF]/.test(c.content[end-1]))end--;
    output={candidateId:c.candidateId,path:c.path,sha256:c.sha256,active:c.active,content:c.content.slice(offset,end),offset,nextOffset:end<c.content.length?end:null,totalCharacters:c.content.length,totalBytes:Buffer.byteLength(c.content),complete:offset===0&&end===c.content.length,authority:'Rejected proposal only; not accepted source'};
   }
   else if(call.tool==='workspace.replace'||call.tool==='workspace.patch'){
    let derivation:any=null;
    if(call.tool==='workspace.patch'){
     validateSourcePatch(args);const p=args,candidate=p.candidateId?this.repairCandidate(call.ventureId,call.taskId,p.candidateId):null;
     requireThat(!candidate||candidate.active&&candidate.path===p.path,'PATCH_CANDIDATE_STALE');const base=candidate?.content??w.files.find(f=>f.path===p.path)?.content;requireThat(typeof base==='string','PATCH_FILE_REQUIRED');
     const patched=applySourcePatch(base,p);derivation=patched.derivation;
     this.store.record(s,'edit-'+hash(attemptKey).slice(0,32),'ModelSourceEdit',derivation);
     args={path:p.path,content:patched.content,expectedHash:w.manifest.files.find(f=>f.path===p.path)?.sha256??null};
    }
    pathCheck(args.path);requireThat(typeof args.content==='string','WORKSPACE_CONTENT_REQUIRED');const old=w.files.find(f=>f.path===args.path),before=old?rawHash(old.content):null;requireThat(args.expectedHash===before,'WORKSPACE_STALE_FILE');const files=old?w.files.map(f=>f.path===args.path?{path:f.path,content:args.content}:f):[...w.files,{path:args.path,content:args.content}];validateFiles(files);if(w.kind==='software'&&w.inputs.profile==='functional-project-v1')validateProjectSource(files);
    const task=this.store.get('portfolio-task',call.taskId),handoff=sourceHandoff({...w,files},w.inputs.profile==='functional-project-v1'||task?.ventureId===call.ventureId&&Boolean(task.inputs?.sourceBindings));
    if(!handoff.accepted){
     const candidateId='candidate-'+hash(attemptKey).slice(0,32),candidate={candidateId,ventureId:call.ventureId,taskId:call.taskId,path:args.path,content:args.content,sha256:rawHash(args.content),baseSourceHash:before,baseManifestHash:w.manifest.sha256,feedback:handoff,derivation,createdAt:new Date().toISOString(),provenance:'Rejected model-proposed source; not authoritative'};
     this.store.transaction(()=>{this.store.record(s,candidateId,'RejectedSourceCandidate',candidate);this.store.put('workspace-rejected-candidate',key+'/'+candidateId,candidate,null);const head=this.store.get('workspace-repair-head',key);this.store.put('workspace-repair-head',key,{candidateId,baseManifestHash:w.manifest.sha256,active:true},head?._version??null);});
     return finish({ok:false,tool:call.tool,observationId:id,manifest:w.manifest,checks:w.checks,changes:[],error:'WORKSPACE_HANDOFF_TOO_LARGE',output:{effect:'none',path:args.path,currentSourceHash:before,...handoff,candidate:{id:candidateId,sha256:candidate.sha256,bytes:Buffer.byteLength(candidate.content)},sourcePreserved:true,nextAction:'Use workspace.patch on this separate candidate, citing its ID/hash, for targeted shortening with substantial headroom. Preserve evidence. The accepted source remains unchanged; this failure adds no model capacity.'}});
    }
    const saved=this.store.transaction(()=>{const latest=this.load(call.ventureId,call.taskId);requireThat(latest._version===w._version,'WORKSPACE_CONCURRENT');const manifest=this.manifest(s,w.taskId,w.kind,files,w.inputs,w.manifest.revision+1,w.manifest.ref);const next=this.store.put('local-workspace',key,{...w,files,manifest,checks:[],checkedManifest:null,published:null},w._version!);const head=this.store.get('workspace-repair-head',key);if(head?.active)this.store.put('workspace-repair-head',key,{...head,active:false,resolvedBy:manifest.sha256},head._version);saveResult({ok:true,tool:call.tool,observationId:id,manifest:next.manifest,checks:[],changes:[{path:args.path,beforeHash:before,afterHash:rawHash(args.content)}],output:{revision:next.manifest.revision,invalidated:['checks','local-publication']}});return next;});w=saved;if(w.kind==='software'&&w.inputs.profile==='functional-project-v1')this.projectRuntime(w.ventureId,w.taskId);changes=[{path:args.path,beforeHash:before,afterHash:rawHash(args.content)}];output={revision:w.manifest.revision,invalidated:['checks','local-publication']};
   }else if(call.tool==='check.run'){
    const checkHash=w.manifest.sha256;
    const checks=w.kind==='software'&&w.inputs.profile==='functional-project-v1'?(await runProjectCommand(this.projectRuntime(w.ventureId,w.taskId),'project.http',{launchBrowser:this.launchBrowser??launchCheckBrowser,saveScreenshot:(name,bytes)=>{this.store.artifact(s,'browser-'+hash({id,name}).slice(0,24),{kind:'browser_screenshot',taskId:w.taskId,manifestHash:checkHash,name,mimeType:'image/png',base64:bytes.toString('base64'),provenance:'trusted_browser_capture_not_model_vision'});}})).checks.map(check=>({...check,required:true})):w.kind==='software'?await (['business-site-v1','marketing-page-v1'].includes(w.inputs.profile)?checkBusinessSite:w.inputs.profile==='quote-to-job-v2'?checkProductV2:checkQuoteApplication)({ventureId:w.ventureId,taskId:w.taskId,manifestHash:checkHash,files:w.files,inputs:w.inputs,launchBrowser:this.launchBrowser,saveScreenshot:(name:string,bytes:Buffer)=>this.store.artifact(s,'browser-'+hash({id,name}).slice(0,24),{kind:'browser_screenshot',taskId:w.taskId,manifestHash:checkHash,name,mimeType:'image/png',base64:bytes.toString('base64'),provenance:'trusted_browser_capture_not_model_vision'}),stateHandler:body=>this.previewState(w.ventureId,w.taskId,body,'check-'+id)}):checkServiceBrief(w.files,w.inputs as BriefInputs).checks;
    if(w.kind==='service'&&w.inputs.enforceHandoff)checks.push({id:'service.handoff',required:true,passed:Buffer.byteLength(w.files.find(f=>f.path==='brief.json')?.content??'')<=(w.inputs.operatingProfile==='operating-packet-v1'?9000:18000),summary:'Complete report fits its declared raw UTF-8 handoff: operating packet 9000 bytes, other briefs 18000 bytes.'});
    if(w.kind==='service'&&w.inputs.profile==='commercial-campaign-v1'){let report:any=null;try{report=JSON.parse(w.files.find(f=>f.path==='brief.json')?.content??'null');}catch{}checks.push(...checkCampaign(report,w.inputs));}
    if(w.kind==='service'&&w.inputs.operatingProfile==='operating-packet-v1'){let report:any=null;try{report=JSON.parse(w.files.find(f=>f.path==='brief.json')?.content??'null');}catch{}checks.push(...checkOperatingPacket(report,w.inputs.reviewedArtifactHash));}
    w=this.store.transaction(()=>{const latest=this.load(call.ventureId,call.taskId);requireThat(latest.manifest.sha256===checkHash,'CHECK_SOURCE_CHANGED');return this.store.put('local-workspace',key,{...latest,checks,checkedManifest:checkHash},latest._version!);});output={passed:mandatoryCheckIds(w.kind,w.inputs.profile).every(id=>checks.some(c=>c.id===id&&c.passed))&&!checks.some(c=>c.required&&!c.passed),checkProfile:w.kind==='software'?w.inputs.profile??'quote-to-job-v1':'source-brief-core-v1',claim:'Executed local checks; actual-model competence and customer outcomes not established'};
   }else if(call.tool==='artifact.publish_local'){
    requireThat(w.checkedManifest===w.manifest.sha256&&mandatoryCheckIds(w.kind,w.inputs.profile).every(id=>w.checks.some(c=>c.id===id&&c.passed))&&!w.checks.some(c=>c.required&&!c.passed),'CURRENT_CHECKS_REQUIRED');
    if(w.published)output=w.published;
    else{const report=w.kind==='service'?checkServiceBrief(w.files,w.inputs as BriefInputs).report:null;const files=w.kind==='service'?[...(w.inputs.profile==='commercial-campaign-v1'?campaignFiles(report,w.inputs):[{path:'report.html',content:w.inputs.operatingProfile==='operating-packet-v1'?renderOperatingPacket(report,w.inputs.reviewedProductLinks):renderServiceBrief(report,w.inputs as BriefInputs)}]),...w.files,{path:'sources.json',content:JSON.stringify(w.inputs,null,2)}]:w.files;const payload={taskId:w.taskId,manifest:w.manifest,files,checks:w.checks,provenance:w.provenance,obligations:report?.obligations??[],delivery:{mode:'local',customerAcknowledged:false}};
     output=this.store.transaction(()=>{const latest=this.load(call.ventureId,call.taskId);requireThat(latest._version===w._version,'WORKSPACE_CONCURRENT');const ref=this.store.artifact(s,'local-delivery-'+hash({key,hash:w.manifest.sha256}).slice(0,32),payload);const publication={ref,manifestHash:w.manifest.sha256,payloadHash:hash(payload),publishedAt:new Date().toISOString(),fileNames:files.map(f=>f.path),obligations:payload.obligations,deliveryMode:'local',customerAcknowledged:false};this.store.put('local-workspace',key,{...w,published:publication},w._version!);saveResult({ok:true,tool:call.tool,observationId:id,manifest:w.manifest,checks:w.checks,changes:[],output:publication});return publication;});w=this.load(call.ventureId,call.taskId);
    }
   }
   return finish({ok:call.tool==='check.run'?Boolean(output.passed):true,tool:call.tool,observationId:id,manifest:w.manifest,checks:w.checks,changes,output});
  }catch(error){let w:Workspace|null=null;try{w=this.load(call.ventureId,call.taskId);}catch{}return finish({ok:false,tool:call.tool,observationId:id,manifest:w?.manifest??null,checks:w?.checks??[],changes:[],output:null,error:((error as any).code??(error as Error).message).slice(0,2000)});}
 }
 previewState(ventureId:string,taskId:string,body:any,namespace='owner'){
  const w=this.load(ventureId,taskId);requireThat(w.kind==='software','PREVIEW_SOFTWARE_REQUIRED');validatePreviewRequest(body,{ventureId,taskId,manifestHash:w.manifest.sha256},w.inputs.profile);if(['business-site-v1','marketing-page-v1'].includes(w.inputs.profile)&&body.operation==='write')for(const row of (body as any).state.inquiries)requireThat(Array.isArray(w.inputs.intakeFields)&&row.details.length===w.inputs.intakeFields.length&&w.inputs.intakeFields.every((f:any)=>row.details.some((d:any)=>d.fieldId===f.id&&d.value.trim().length>0)),'PREVIEW_REQUIRED_INFORMATION_MISSING');const key=this.key(ventureId,taskId)+'/'+namespace;
  return this.store.transaction(()=>{const prior=this.store.get('local-preview-state',key);let state=prior?.state??(['business-site-v1','marketing-page-v1'].includes(w.inputs.profile)?emptyBusinessSiteState():emptyQuoteState()),version=prior?.version??0;if(body.operation==='write'){requireThat(body.expectedVersion===version,'PREVIEW_STATE_STALE');state=structuredClone(body.state);version++;this.store.put('local-preview-state',key,{ventureId,taskId,version,state,manifestHash:w.manifest.sha256},prior?prior._version:null);}return {version,state};});
 }
 download(ventureId:string,taskId:string,path?:string){const w=this.load(ventureId,taskId);requireThat(w.published&&w.published.manifestHash===w.manifest.sha256,'LOCAL_PUBLICATION_REQUIRED');const s=this.scopeFor(ventureId),payload=this.store.readArtifact({id:'local-delivery-reader',tenantId:s.tenantId,businessId:s.businessId,permissions:['read']},s,w.published.ref.id);requireThat(hash(payload)===w.published.payloadHash,'LOCAL_DELIVERY_READBACK_MISMATCH');if(path){const file=payload.files.find((f:SourceFile)=>f.path===path);requireThat(file,'DELIVERY_FILE_NOT_FOUND');const mimeType=path.endsWith('.html')?'text/html; charset=utf-8':path.endsWith('.json')?'application/json; charset=utf-8':path.endsWith('.js')?'text/javascript; charset=utf-8':path.endsWith('.css')?'text/css; charset=utf-8':'text/plain; charset=utf-8';return {fileName:path,mimeType,content:file.content};}return {fileName:'artifact-bundle.json',mimeType:'application/json; charset=utf-8',content:JSON.stringify(payload,null,2)};}
}
