let csrf='',selected=null,tab='journey',data=null;
const $=id=>document.getElementById(id),e=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const list=xs=>'<ul>'+(xs??[]).map(x=>`<li>${e(typeof x==='string'?x:JSON.stringify(x))}</li>`).join('')+'</ul>';
const detail=(label,x)=>`<details><summary>${e(label)}</summary><pre>${e(JSON.stringify(x,null,2))}</pre></details>`;
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'content-type':'application/json','x-csrf-token':csrf}:{},body:body?JSON.stringify(body):undefined});const out=await r.json();if(!r.ok)throw Error(out.error||'Request failed');return out;}
async function action(name,extra={}){try{$('notice').innerHTML='<p>Working on persisted state…</p>';await api('action',{businessId:selected,action:name,...extra});await refresh();$('notice').innerHTML='<div class="success">Saved. The view below reflects persisted state.</div>';}catch(err){$('notice').innerHTML=`<div class="error">${e(err.message)}. No automatic replacement call or action was made.</div>`;}}
async function refresh(){const root=await api('state');csrf=root.csrf;$('businesses').innerHTML=root.businesses.map(b=>`<button data-business="${e(b.id)}" class="${selected===b.id?'active':''}">${e(b.name)}<br><small>${e(b.assignment)}</small></button>`).join('');document.querySelectorAll('[data-business]').forEach(b=>b.onclick=()=>{selected=b.dataset.business;refresh();});if(selected)data=await api('state?id='+encodeURIComponent(selected));render(root.packet);}
function artifact(a){if(!a)return '<p>No artifact exists yet.</p>';if(a.register)return `<h3>${e(a.title||'Supplier release / hold recommendation')}</h3><table><tr><th>Invoice</th><th>Recommendation</th><th>Amount (cents)</th><th>Reason / next step</th></tr>${a.register.map(r=>`<tr><td>${e(r.invoiceId)}</td><td>${e(r.decision||r.action||r.recommendation||r.status)}</td><td>${e(r.amountMinor)}</td><td>${e(r.rationale||r.reason)}${r.nextEvidenceRequest?'<p>'+e(r.nextEvidenceRequest)+'</p>':''}</td></tr>`).join('')}</table><p>${e(a.memo)}</p>${detail('Totals and source trail',a)}`;return `<h3>${e(a.title)}</h3>${list(a.steps)}${(a.answers??[]).map(x=>`<p><b>${e(x.topic)}</b><br>${e(x.text)}</p>`).join('')}`;}
function render(packet){$('welcome').hidden=!!selected||tab==='packet';if(tab==='packet'){$('content').innerHTML=`<div class="card"><p class="eyebrow">DEVELOPMENT-ASSISTANT AUTHORED · EVIDENCE-LINKED</p><h1>MIDAS operating packet</h1><p>Capabilities, observations, product bottlenecks and the next owner decision.</p>${Object.entries(packet).map(([k,v])=>`<h2>${e(k.replaceAll('_',' '))}</h2>${Array.isArray(v)?v.map(x=>`<div class="fact">${typeof x==='string'?e(x):Object.entries(x).map(([a,b])=>`<p><b>${e(a)}:</b> ${e(typeof b==='string'?b:JSON.stringify(b))}</p>`).join('')}</div>`).join(''):`<p>${e(typeof v==='string'?v:JSON.stringify(v))}</p>`}`).join('')}</div>`;return;}if(!data||!selected){$('content').innerHTML='';return;}const b=data.business,current=data.current,proposal=data.proposal,plan=data.plan,run=data.run;
if(tab==='competence'){$('content').innerHTML=`<div class="card"><h1>Workers & controlled improvement</h1><p>Assignment is rule-based. Evidence does not imply qualification outside its population.</p>${(current?.brief.workers??[]).map(w=>`<div class="fact"><h3>${e(w.id)} <span class="pill">${e(w.qualification)}</span></h3>${list(w.competencies)}${detail('Evidence and supported population',w.evidence)}</div>`).join('')}${detail('Selected assignment and missing requirements',plan?.team)}<h2>Failure → procedure proposal → comparison</h2><p>The offline mechanics use a disclosed injected failure and preserve the strong baseline. No specialist improvement is measured.</p><button id="improve">Exercise offline comparison mechanics</button>${detail('Persisted comparison evidence',data.improvement)}</div>`;$('improve').onclick=()=>action('improvement');return;}
$('content').innerHTML=`<p class="eyebrow">${e(b.assignment)} · PERSISTENT WORKSPACE ${e(b.id)}</p><h1>${e(current?.brief.goal||b.name)}</h1><div class="steps">${['Evidence','Understanding','Bottleneck','Plan & worker','Execution','Exact approval','Verified outcome','Adaptation'].map(x=>`<span>${x}</span>`).join('')}</div>
<div class="card"><h2>1. Business brief & permitted evidence</h2><label>Goal<input id="goal" value="${e(b.goal)}"></label><p class="muted">Edit the brief or evidence before analysis. Re-analysis creates a fresh bounded mock attempt; old observations remain intact. There is no live route in this workbench. Edited source bundles can be analyzed, but execution is supported only for the unchanged versioned assignment corpus; unsupported edits block execution.</p>${b.bundle.sources.map((s,i)=>`<details><summary>${e(s.id)} · ${e(s.permission)}</summary><label>Source text<textarea data-source="${i}">${e(s.text)}</textarea></label><p>${e(s.observedAt)} · ${e(s.rights)}</p></details>`).join('')}<div class="actions"><button id="save">Save brief/evidence revision</button><button class="primary" id="analyze">Analyze evidence (explicit mock)</button></div></div>
<div class="card"><h2>2. Proposed business understanding</h2><p class="warning">Partial understanding. Model outputs are proposals with source references; they are not established causal truth. This offline run uses deterministic output fixtures.</p>${proposal?`${(proposal.claims??[]).map(c=>`<div class="fact"><span class="pill">${e(c.kind)}</span> ${e(c.statement||c.text)}${detail('Source references',c.refs||c.sources||c)}</div>`).join('')}${detail('Contradictions, unknowns and evidence requests',proposal)}<button class="primary" id="accept">Accept as provisional business interpretation</button>`:'<p>Analyze the permitted evidence bundle to create a proposal.</p>'}</div>
<div class="card"><h2>3. Bottleneck → work plan → worker assignment</h2>${current?`<p>Business revision ${current._version}. ${e(data.assessment?.method)}</p>${(data.assessment?.candidates??[]).map(c=>`<div class="fact"><b>${e(c.id)}</b> — ${e(c.state)}<p>${e(c.diagnosis)}</p>${c.missing?.length?'<p>Missing evidence: '+e(c.missing.join(', '))+'</p>':''}</div>`).join('')}<button id="plan">Create pinned work plan</button>${plan?`<h3>${e(plan.id)} — ${e(plan.status)}</h3>${detail('Tasks, selected workers, why and remaining uncertainty',{tasks:plan.opportunity?.tasks,team:plan.team,roleVersions:plan.roleVersions})}`:''}`:'<p>Accept the proposal before planning.</p>'}</div>
<div class="card"><h2>4. Execute & review</h2><p>Four bounded mock stages: investigate, decide/draft, review/correct, inspect. No provider or token-count requests. Invoice drafts contain a disclosed injected recommendation defect to exercise correction; it is not an observed AI error.</p>${run?`<p><b>${e(run.phase||run.checkpoint||run.state)}</b> · ${e(run.reason||'')}</p>`:''}<button class="primary" id="run" ${plan?'':'disabled'}>Run / resume supported assignment</button>${data.initialArtifact?`<details><summary>Original draft (preserved)</summary>${artifact(data.initialArtifact)}</details>`:''}${data.review?detail('Substantive review corrections',data.review):''}</div>
<div class="card"><h2>5. Exact owner approval</h2>${data.approval?`<p class="warning">One unchanged internal fixture publication only, capped at 25 simulated USD cents. No payment, customer contact or account change.</p><div class="artifact">${artifact(data.approval.artifact)}</div><p>Proposal SHA-256:<br><code>${e(data.approval.proposalHash)}</code></p><label><input id="confirm" type="checkbox" style="display:inline;width:auto"> I approve this exact synthetic fixture action. Artifact review is AI-assisted; independent human validation and timing are not asserted.</label><button class="primary" id="approve">Approve exact artifact & continue</button>`:'<p>No exact approval is pending. Missing evidence or unsupported work cannot be approved into validity.</p>'}</div>
<div class="card"><h2>6. Deliverable, verification & updated understanding</h2>${data.finalArtifact?`<div class="artifact">${artifact(data.finalArtifact)}</div>`:'<p>No verified deliverable yet.</p>'}${data.plan?.outcome?`<p class="success">Operational result: ${e(data.plan.outcome.operational)} · ${e(data.plan.outcome.effectCount)} fixture effect(s). Provenance: ${e(data.plan.outcome.provenance)}.</p>`:''}${detail('Receipt, independent checks and accounting',data.outcome)}${detail('Persistent business feedback and next evidence need',data.feedback)}<p>Operational completion does not establish realized economic benefit. Mock success does not qualify a worker.</p></div>`;
$('save').onclick=()=>action('save',{goal:$('goal').value,sources:[...document.querySelectorAll('[data-source]')].map(x=>({index:Number(x.dataset.source),text:x.value})),expected:b.revision});$('analyze').onclick=()=>action('analyze');if($('accept'))$('accept').onclick=()=>action('accept',{proposalHash:data.proposalHash});if($('plan'))$('plan').onclick=()=>action('plan');$('run').onclick=()=>action('run');if($('approve'))$('approve').onclick=()=>{if(!$('confirm').checked){$('notice').innerHTML='<div class="warning">Read the exact artifact and check the approval box first.</div>';return;}action('approve',{proposalHash:data.approval.proposalHash});};}
$('create').onclick=async()=>{try{const x=await api('create',{assignment:$('assignment').value});selected=x.id;tab='journey';await refresh();}catch(x){$('notice').textContent=x.message;}};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;refresh();});refresh().catch(x=>$('notice').textContent=x.message);
