/** Exercises existing admission + paired analysis with explicitly injected output fixtures, never competence evidence. */
import {ModelLedger} from '../experiment/ledger.ts';
import {analyze} from '../experiment/analysis.ts';
import {canonical,hash,rawHash} from '../contracts.ts';
import type {Scope,ModelPort,ModelRequest} from '../contracts.ts';
import type {StateStore} from '../state.ts';
export async function compareFixtureProcedures(store:StateStore,scope:Scope,baseline:string,challenger:string){const ledger=new ModelLedger(store,{...scope,runId:'comparison-model-account'},hash({baseline,challenger}),{totalMinor:0,concurrency:1,stages:{smoke:{minor:0,attempts:0},development:{minor:0,attempts:2},validation:{minor:0,attempts:0},evaluation:{minor:0,attempts:0}}});const rows=[];
    for(const condition of ['baseline','challenger'] as const){const request:ModelRequest={scope:ledger.scope,requestId:'compare-'+condition,task:'operate',role:{id:'reference-worker',version:'v1',procedure:condition==='baseline'?baseline:challenger,competencies:['source_retention'],tools:[],model:'offline-procedure-fixture',predecessor:null,qualification:'experimental_unqualified'},context:{source:{id:'source-1',text:'Authorized source to retain through the handoff'},instruction:'Return references needed to trace this source. Both conditions receive identical facts.'},tools:[],limits:{maxCost:{currency:'USD',minorUnits:0},maxAttempts:1,maxHumanMinutes:0}};let result=ledger.get(request.requestId)?.result;
        if(!result){const budget=ledger.port('development',{condition,provenance:'explicit_mock_with_injected_baseline_output_fault'});const bytes=canonical(request);await budget.prepare!(request,request.limits.maxCost,rawHash(bytes),bytes);await budget.reserve(request,request.limits.maxCost,rawHash(bytes));const port:ModelPort={kind:'fixture',run:()=>({output:{references:condition==='baseline'?[]:['source-1'],provenance:'Scripted mock output; missing baseline reference is injected, not measured model behavior'},route:{kind:'fixture',provider:'mock',model:request.role.model},usage:{inputTokens:null,outputTokens:null,cost:{status:'known',money:{currency:'USD',minorUnits:0},basis:'no provider request'}}})};result=await port.run(request);ledger.finish(request.requestId,result,null);}
        rows.push({id:request.requestId,caseId:'reference-handoff',cluster:'injected-fixture',family:'mechanics',repeat:0,condition,accepted:result.output.references.includes('source-1'),critical:false,costMinor:null,latencyMs:null,correctionSeconds:null,failed:false});}
    const spec={caseCount:1,clusters:1,repeats:1,minimumQuality:1,minimumQualityLowerBound:.8,practicalGain:.1,maxCriticalUpperBound:.05,maxP95LatencyMs:180000,maxMeanCorrectionSeconds:600,maxCostPerAcceptedMinor:52,seed:29};const analysis=analyze(rows,spec);const record={observations:rows,analysis,mechanicsOnly:true,qualification:'none',providerRequests:0,interpretation:'Existing ModelLedger and paired analysis executed on two scripted output fixtures. No statistical interval or apparent gain estimates model competence. The strong baseline prompt is unchanged; its output fault is explicitly injected.'};store.transaction(()=>store.record(scope,'executed-comparison-mechanics','OfflineComparisonMechanics',record));return record;}
