import {mkdirSync,existsSync,readFileSync,writeFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {StateStore} from '../state.ts';
import {RunController} from '../runtime.ts';
import {Authority} from '../authority.ts';
import {FixtureService} from '../lab/fixture-service.ts';
import {ModelLedger} from '../experiment/ledger.ts';
import {canonical,hash,rawHash,requireThat,scopeKey} from '../contracts.ts';
import type {Scope,Role,ModelPort,ModelRequest} from '../contracts.ts';
import {implementationHash} from '../workflow/config.ts';
import {invoiceBundle,invoiceWorkerBundle,lookupInvoiceEvidence,materializePacket,checkPacket,validateInvoiceOutput,invoiceStageSchema} from './invoice.ts';
import type {InvoiceBundle,InvoiceRecommendation,InvoiceStage} from './invoice.ts';
import {invoiceMockOutput} from './invoice-fixtures.ts';
import {supportBrief} from '../business/support-adapter.ts';
import type {Brief} from '../business/core.ts';
export const invoiceProcedure='Act as an excellent reconciliation worker. Read the full current policy, source invoices, purchase-order amounts, receipts, credits and cash limit. Obtain missing permitted evidence. Identify duplicate economic obligations, partial receipts, superseded evidence, mismatches and missing records. Apply the explicit priority rule. Recommend release or hold only, with source references and concrete next steps. Review the actual draft by recomputing each line from source records; return a complete replacement recommendation. Keep totals, memo and proposed action consistent. Never approve a payment or claim approval. After approved fixture publication inspect actual receipt, readback and obligations. No customer or financial action is authorized.';
export function invoiceBrief(batchId:string):Brief{const b=supportBrief();b.version='invoice-business-v1';b.goal='Prepare an auditable supplier-invoice release / hold recommendation under the supplied cash constraint.';b.prioritizationBasis='USD cents per synthetic batch; planning value assumption, not measured savings';b.claims[0].statement='A supplier invoice batch requires current receiving evidence and reconciliation before recommending releases.';b.claims[0].source=batchId+' source corpus';b.opportunities[0]={...b.opportunities[0],id:'reconcile-invoices',diagnosis:'Reconcile evidence before an owner decides which obligations can be recommended for release.',valueBasis:b.prioritizationBasis,adapter:'supplier-invoice-v1',tasks:b.opportunities[0].tasks.map(t=>({...t,tools:t.tools.map(x=>x==='lab.evidence'?'invoice.lookup':x),competencies:[t.id==='inspect'?'outcome_verification':'invoice_reconciliation'],description:t.id==='investigate'?'Obtain permitted missing receiving records':t.id==='decide'?'Draft an evidence-linked release/hold register':t.id==='review'?'Recompute and replace the recommendation before exact approval':'Inspect authenticated fixture delivery'})),acceptance:['Current source-supported eligibility and priority','No duplicate or over-budget release','Register, totals, memo and approval payload agree','One exact-approved fixture effect and authenticated readback']};b.constraints.allowedTools=['invoice.lookup','lab.readback'];b.workers=[{...b.workers[0],tools:['invoice.lookup','lab.readback'],id:'invoice-owner',procedure:invoiceProcedure,version:'invoice-owner-v1',competencies:['invoice_reconciliation','outcome_verification'],evidence:[],qualification:'experimental'}];return b;}
function shapeDecision(rec:InvoiceRecommendation){return {kind:'decision',chosenOptionId:'prepare-packet',status:'proposed',alternatives:[],rationale:rec.summary,assumptions:['Synthetic recommendation; no payment or realized benefit'],reversalConditions:['Missing or contradictory source evidence','Cash or policy changes'],experiment:{scope:'Internal fixture only'},draft:{recommendation:rec}};}
function invoiceScope(id:string):Scope{return {tenantId:'workbench',businessId:id,runId:'invoice-workflow',dataPolicyVersion:'invoice-policy-v1',mode:'fixture'};}
export function invoiceLocation(root:string,plan:any){return resolve(root,'invoice-executions',hash(plan.ref).slice(0,24));}
function openInvoice(root:string){const binding=JSON.parse(readFileSync(join(root,'binding.json'),'utf8'));requireThat(binding.mode==='mock'&&binding.implementationHash===implementationHash(),'INVOICE_RUNTIME_PIN_MISMATCH');return {binding,store:new StateStore(join(root,'workflow.sqlite')),s:invoiceScope(binding.id)};}
export async function runInvoice(root:string,plan:any,batchId:string,options:{seedDraftDefect?:boolean;fault?:string;port?:ModelPort}={}){
    requireThat(plan.team?.workers.length===1&&plan.team.workers[0].id==='invoice-owner'&&plan.team.workers[0].procedure===invoiceProcedure,'INVOICE_ASSIGNMENT_UNSUPPORTED');
    mkdirSync(root,{recursive:true});const bundle=invoiceBundle(batchId),binding={version:'invoice-runtime-v1',mode:'mock',id:hash(plan.ref).slice(0,24),planHash:hash(plan.ref),batchId,implementationHash:implementationHash(),seedDraftDefect:options.seedDraftDefect??false};
    if(!existsSync(join(root,'binding.json')))writeFileSync(join(root,'binding.json'),JSON.stringify(binding),{flag:'wx'});
    const opened=openInvoice(root);requireThat(opened.binding.planHash===binding.planHash&&opened.binding.batchId===batchId,'INVOICE_PLAN_MISMATCH');const {store,s}=opened;const principal={id:'invoice-runtime',tenantId:s.tenantId,businessId:s.businessId,permissions:['read','operate']};const service=new FixtureService(join(root,'fixture.sqlite'),options.fault??'none');
    const ledger=new ModelLedger(store,{...s,runId:'model-account'},hash(opened.binding),{totalMinor:208,concurrency:1,stages:{smoke:{minor:208,attempts:4},development:{minor:0,attempts:0},validation:{minor:0,attempts:0},evaluation:{minor:0,attempts:0}}});
    const hydrated=(run:any):InvoiceBundle=>run.evidence[0]?.bundle??bundle;
    const role:Role={id:'invoice-owner',version:'invoice-owner-v1',procedure:invoiceProcedure,competencies:['artifact_delivery','invoice_reconciliation','outcome_verification'],tools:['invoice.lookup','lab.publish','lab.readback'],predecessor:null,model:'offline-invoice-fixture',qualification:'experimental_unqualified'};
    const env:any={id:'supplier-invoice-v1',version:bundle.version,snapshot:()=>({bundle:invoiceWorkerBundle(bundle),business:{goal:plan.brief.goal,claims:plan.assessment.claims,planHash:hash(plan.ref)},options:[{id:'prepare-packet'}]}),getEvidence:(q:any)=>({status:'provided',authorized:true,bundle:lookupInvoiceEvidence(bundle,q.branches.filter((x:any)=>x.action==='retrieve').map((x:any)=>x.answer))}),validateDecision:(_s:any,_e:any,d:any)=>({ok:d.kind==='decision'&&d.chosenOptionId==='prepare-packet'&&d.status==='proposed',reason:'Internal recommendation only; final line correctness checked before effect'}),actionFor:(o:any)=>{const b=hydrated(store.get('run',scopeKey(s)));const packet=materializePacket(b,o.recommendation);requireThat(checkPacket(b,packet).ok,'INVOICE_REVIEW_NOT_ACCEPTABLE');return {toolId:'lab.publish',payload:{artifact:packet,simulatedLedger:{simulated:true,obligations:{currency:'USD',minorUnits:25}}},estimatedCost:{currency:'USD',minorUnits:25},effectClass:'reversible_write'};},verify:(x:any)=>{const checked=checkPacket(hydrated(store.get('run',scopeKey(s))),x.artifact);const inspected=store.get('model',scopeKey(s)+'/verify')?.result?.output;if(inspected?.status!=='pass')checked.failures.push('Inspection did not establish pass: '+(inspected?.status??'missing'));return {operationalResult:checked.ok&&inspected?.status==='pass'?'pass':'fail',economicResult:'unmeasured',measurements:{totalReleaseMinor:x.artifact.totalReleaseMinor,remainingCashMinor:x.artifact.remainingCashMinor},failures:checked.failures,simulated:true};}};
    const ext:any={id:hash({binding:opened.binding,role}),maxModelCost:{currency:'USD',minorUnits:52},skipLearning:true,roles:()=>({analyst:role,operator:role,verifier:role}),recover:(id:string)=>ledger.get(id)?.result??null,reviewedDecision:(_run:any,out:any)=>shapeDecision(out.recommendation),context:({run,task,observed}:any)=>({business:run.snapshot.business,bundle:invoiceWorkerBundle(hydrated(run)),...(task==='operate'?{recommendation:run.decision.draft.recommendation}:{}),...(task==='verify'?{receipt:observed,approvedArtifact:run.proposal.payload.artifact,obligations:observed.ledger.obligations}:{})}),model:async({request,run,task}:any)=>{
        const stage=({investigate:'investigate',decide:'draft',operate:'review',verify:'inspect'} as const)[task as ModelRequest['task']];const b=hydrated(run);const rawRequest={...request,scope:{...s,runId:'model-account'},context:{...request.context,outputSchema:invoiceStageSchema(stage)}};const bytes=canonical(rawRequest),digest=rawHash(bytes);const prior=ledger.get(request.requestId);if(prior){requireThat(prior.result&&!prior.errorCode&&prior.requestHash===digest,'INVOICE_NO_RETRY');return prior.result;}
        const budget=ledger.port('smoke',{workflow:s.runId,component:'invoice',provenance:'offline_mock'});await budget.prepare!(rawRequest,{currency:'USD',minorUnits:52},digest,bytes);await budget.reserve(rawRequest,{currency:'USD',minorUnits:52},digest);
        try{let out:any;if(options.port){requireThat(options.port.kind==='fixture','INVOICE_LIVE_NOT_AUTHORIZED');const received=await options.port.run(rawRequest);store.transaction(()=>store.record(s,request.requestId+'-raw-response','InvoiceModelObservation',{stage,result:received,provenance:'offline_mock'}));requireThat(received.route.kind==='fixture'&&received.route.model===role.model,'INVOICE_ROUTE_MISMATCH');out=received.output;}else{out=invoiceMockOutput(stage,b,request.context);if(stage==='draft'&&opened.binding.seedDraftDefect){out.rows.find((r:any)=>r.decision==='release').amountMinor=0;out.rows=out.rows.map((r:any)=>r.amountMinor===0?{...r,decision:'hold',rationale:'INJECTED MOCK DRAFT DEFECT: unnecessary hold',nextEvidenceRequest:'Review source eligibility'}:r);}if(stage==='inspect')out={status:'pass',findings:['OFFLINE MOCK: compare supplied receipt/readback; no semantic competence claim'],evidenceRefs:[request.context.receipt.externalReceiptId,request.context.receipt.payloadHash]};}
            validateInvoiceOutput(stage,out,b);if(stage==='inspect')requireThat(out.status!=='pass'||(out.evidenceRefs.includes(request.context.receipt.externalReceiptId)&&out.evidenceRefs.every((id:string)=>[request.context.receipt.externalReceiptId,request.context.receipt.payloadHash].includes(id))&&hash(request.context.receipt.artifact)===hash(request.context.approvedArtifact)&&request.context.obligations.minorUnits===0),'INVOICE_INSPECTION_UNSUPPORTED');
            const output=stage==='investigate'?{kind:'information_request',variable:'receiving_records',decision:out.rationale,plausibleRange:{minimum:0,maximum:8,unit:'records'},branches:out.requests.length?out.requests.map((id:string)=>({answer:id,action:'retrieve'})):[{answer:'no missing records',action:'continue'}],source:'invoice.lookup',maxCost:{currency:'USD',minorUnits:0},deadline:new Date(Date.parse(run.createdAt)+86400000).toISOString()}:stage==='draft'?shapeDecision(out):stage==='review'?{recommendation:out.recommendation,review:{issues:[],changes:out.changes,verdict:'ready'}}:out;
            const result={output,usage:{inputTokens:null,outputTokens:null,cost:{status:'known',money:{currency:'USD',minorUnits:0},basis:'Offline mock; zero provider requests'}},route:{provider:'fixture',model:role.model,kind:'fixture'}};ledger.finish(request.requestId,result,null);return result;
        }catch(e){if(!ledger.get(request.requestId)?.finishedAt)ledger.finish(request.requestId,null,(e as any).code??(e as Error).message);throw e;}
    }};
    const runtime=new RunController(store,ext);try{runtime.create(principal,env,{runId:s.runId,cap:{currency:'USD',minorUnits:25},policyVersion:s.dataPolicyVersion});const auth=new Authority(store);if(!existsSync(join(root,'fixture-approver'))){const token=auth.enroll('owner',s.tenantId,s.businessId,['read','approve']);writeFileSync(join(root,'fixture-approver'),token,{flag:'wx'});}try{await runtime.advance(principal,s,env,{kind:'fixture',run(){throw Error('UNMETERED_INVOICE_PATH');}},service);}catch(error){const run=store.get('run',scopeKey(s));if(run&&run.phase!=='reconciling')runtime.update(s,run._version,{phase:'failed',outcome:{operationalResult:'fail',economicResult:'unmeasured',failures:[(error as any).code??(error as Error).message],simulated:true}},'workbench.invoice_failure',{code:(error as any).code??'INVOICE_MODEL_OR_CONTRACT_FAILURE'});else throw error;}return invoiceView(root);}finally{service.close();store.close();}}
export function approveInvoice(root:string,digest:string){const {store,s}=openInvoice(root);try{const run=store.get('run',scopeKey(s));requireThat(run?.phase==='waiting_approval'&&hash(run.proposal)===digest,'STALE_APPROVAL');const auth=new Authority(store);const p=auth.authenticate('owner',readFileSync(join(root,'fixture-approver'),'utf8'));auth.approve(s,p,run.proposal,{reviewMinutes:0});store.transaction(()=>store.event(s,'workbench.exact_owner_approval',{proposalHash:digest,reviewProvenance:'AI-assisted artifact review',independentHumanValidation:false,humanSeconds:null}));return {approved:true};}finally{store.close();}}
export function invoiceView(root:string){const {store,s,binding}=openInvoice(root);try{const run=store.get('run',scopeKey(s));if(!run)return {phase:'not_started'};const attempts=store.db.prepare("SELECT body FROM entities WHERE kind='model-attempt'").all().map(r=>JSON.parse(String(r.body)));const records=store.records({id:'viewer',tenantId:s.tenantId,businessId:s.businessId,permissions:['read']},s);const initial=records.find(r=>r.kind==='DecisionRecord')?.value;let observation:any=null;if(run.proposal){const f=new FixtureService(join(root,'fixture.sqlite'));try{observation=f.observe(run.proposal);if(observation.status==='confirmed')requireThat(f.identity()===run.serviceIdentity&&f.verifyObservation(run.proposal,observation),'INVOICE_RECEIPT_INVALID');}finally{f.close();}}
        const full=run.evidence[0]?.bundle??invoiceBundle(binding.batchId);return {phase:run.phase,decision:run.decision,initialDecision:initial,initialArtifact:initial?.draft?materializePacket(full,initial.draft.recommendation):null,review:store.get('model',scopeKey(s)+'/operate')?.result?.output?.review??null,approval:run.phase==='waiting_approval'?{proposalHash:hash(run.proposal),artifact:run.proposal.payload.artifact}:null,finalArtifact:observation?.status==='confirmed'?observation.artifact:null,outcome:run.outcome,observation,evidence:run.evidence,checks:observation?.artifact?checkPacket(full,observation.artifact):null,attempts:attempts.map(a=>({id:a.id,status:a.status,error:a.errorCode,reservation:a.reservation})),callsUsed:attempts.length,providerRequests:0,provenance:'offline_mock',pending:attempts.filter(a=>!a.finishedAt).map(a=>a.id),binding};
    }finally{store.close();}}
