import {hash,canonical} from '../contracts.ts';

export type InvoiceStage='investigate'|'draft'|'review'|'inspect';
export interface Invoice {id:string; sourceId:string; supplier:string; obligation:string; poMinor:number; invoiceMinor:number; priority:number; due:string; creditMinor:number; creditSource:string|null; receiptSource:string;}
export interface InvoiceEvidence {id:string; kind:'receipt'; invoiceId:string; receivedMinor:number|null; status:'current'|'superseded'|'unavailable'; supersedes:string|null;}
export interface InvoiceBundle {id:string; version:string; provenance:string; currency:'USD'; cashMinor:number; policy:{id:string; version:string; rules:string[]; supersedes:string}; policyHistory:{id:string; status:'superseded'; rule:string}[]; invoices:Invoice[]; evidence:InvoiceEvidence[]; permittedLookups:string[]; lookupRecords:InvoiceEvidence[];}
export interface InvoiceRow {invoiceId:string; decision:'release'|'hold'; amountMinor:number; sourceRefs:string[]; rationale:string; nextEvidenceRequest:string|null; owner:string;}
export interface InvoiceRecommendation {rows:InvoiceRow[]; summary:string;}
export interface InvoicePacket {kind:'supplier-release-recommendation'; version:string; batchId:string; currency:'USD'; register:InvoiceRow[]; totalReleaseMinor:number; remainingCashMinor:number; exceptions:{invoiceId:string; request:string|null; owner:string;reason:string}[]; memo:string; authority:string; contentHash:string;}
const rules=[
 'This synthetic task recommends internal release or hold only. It cannot pay, contact suppliers, change accounts or assert approval. Publication requires exact human approval of the final packet.',
 'Use USD integer cents. PO and invoice amounts must match exactly; no tolerance. Hold a mismatch. A receipt with unavailable status or null amount is not evidence of delivery.',
 'Only current receiving records count. Superseded records never count. The current policy supersedes every entry in policyHistory; historical policy cannot override current rules. Request permitted missing records before deciding; if unavailable, hold and name the evidence request and finance owner.',
 'Partial receipts permit proportional release up to receivedMinor. Subtract the explicitly allocated credit once from min(invoiceMinor, receivedMinor), floored at zero. Each credit is unique to its named invoice.',
 'Duplicate economic obligations share supplier plus obligation. Only the lexicographically smallest invoice ID may be released; hold other copies even if receipt evidence exists.',
 'Eligible means matching PO, current receipt, positive amount, and not a duplicate. Allocate whole eligible amounts by ascending priority, then due date, then invoice ID. If an amount exceeds remaining cash, hold it and continue to the next eligible invoice. No partial cash allocation.',
 'Every row must cite its invoice source and current receipt when used, plus policy and any credit source used. Explain holds and supply a specific next step and finance-owner responsibility. A missing receipt or mismatch is an exception, not invented evidence.',
 'The owner memo, register, totals, exceptions and approval payload must describe the same authoritative recommendation. Review returns a complete replacement recommendation; prior approvals cannot authorize changed content.'
];
export function invoiceBatches():InvoiceBundle[]{return [1,2,3].map(n=>{
 const id=`AP-00${n}`,amounts=[12000,16000,9000,9000,14000,11000,8000,6000], invoices:Invoice[]=amounts.map((amount,i)=>({id:`I-${i+1}`,sourceId:`${id}-invoice-${i+1}`,supplier:i===3?'Supplier-3':`Supplier-${i+1}`,obligation:i===3?'PO-3':`PO-${i+1}`,poMinor:i===6?8500:amount,invoiceMinor:amount,priority:i+1,due:`2026-09-${String(15+i).padStart(2,'0')}`,creditMinor:i===5?2000:0,creditSource:i===5?`${id}-credit-6`:null,receiptSource:`${id}-receipt-${i+1}`}));
 const receipts:InvoiceEvidence[]=invoices.map((v,i)=>({id:v.receiptSource,kind:'receipt',invoiceId:v.id,receivedMinor:i===1?8000:i===7?null:v.invoiceMinor,status:i===7?'unavailable':'current',supersedes:i===5?`${id}-receipt-6-old`:null}));
 receipts.push({id:`${id}-receipt-6-old`,kind:'receipt',invoiceId:'I-6',receivedMinor:3000,status:'superseded',supersedes:null});
 if(n===2){invoices[0].priority=6;invoices[5].priority=1;receipts[4].status='unavailable';receipts[4].receivedMinor=null;}
 if(n===3){invoices[1].creditMinor=1000;invoices[1].creditSource=`${id}-credit-2`;receipts[1].receivedMinor=16000;}
 const lookupRecords=receipts.filter(r=>r.invoiceId==='I-5');
 return {id,version:'synthetic-payables-v1',provenance:'Invented distributor records; developer-visible exploratory cases; related case family, not protected customer data.',currency:'USD',cashMinor:n===1?35000:n===2?25000:30000,policy:{id:`${id}-policy`,version:'payables-policy-v1',rules:[...rules],supersedes:`${id}-policy-retired`},policyHistory:[{id:`${id}-policy-retired`,status:'superseded',rule:'Historical rule: hold every partial receipt until complete delivery. Superseded by current proportional-release rule.'}],invoices,evidence:receipts.filter(r=>r.invoiceId!=='I-5'),permittedLookups:lookupRecords.map(r=>r.id),lookupRecords};
 });}
export function invoiceBundle(id='AP-001'):InvoiceBundle{const b=invoiceBatches().find(b=>b.id===id);if(!b)throw Error('INVOICE_BATCH_UNKNOWN');return b;}
/** Worker context excludes inaccessible lookup bytes, evaluator expectations and labels. */
export function invoiceWorkerBundle(b:InvoiceBundle){const {lookupRecords,...visible}=b;return structuredClone(visible);}
export function lookupInvoiceEvidence(b:InvoiceBundle,ids:string[]):InvoiceBundle{if(ids.length>8||new Set(ids).size!==ids.length||ids.some(id=>!b.permittedLookups.includes(id)))throw Error('INVOICE_LOOKUP_DENIED');const next=structuredClone(b);for(const id of ids){const r=b.lookupRecords.find(r=>r.id===id);if(!r)throw Error('INVOICE_LOOKUP_UNAVAILABLE');if(!next.evidence.some(e=>e.id===id))next.evidence.push(r);}return next;}
const str={type:'string',minLength:1,maxLength:4000},nullable={anyOf:[str,{type:'null'}]},arr=(items:unknown)=>({type:'array',items,maxItems:32});
const obj=(properties:Record<string,unknown>)=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const rowSchema=obj({invoiceId:str,decision:{type:'string',enum:['release','hold']},amountMinor:{type:'integer',minimum:0,maximum:Number.MAX_SAFE_INTEGER},sourceRefs:arr(str),rationale:str,nextEvidenceRequest:nullable,owner:str});
const recommendationSchema=obj({rows:{type:'array',items:rowSchema,minItems:8,maxItems:8},summary:str});
export function invoiceStageSchema(stage:InvoiceStage):any{switch(stage){case'investigate':return obj({requests:arr(str),unknowns:arr(str),rationale:str});case'draft':return recommendationSchema;case'review':return obj({recommendation:recommendationSchema,changes:arr(str)});case'inspect':return obj({status:{type:'string',enum:['pass','fail','unknown']},findings:arr(str),evidenceRefs:arr(str)});default:throw Error('INVOICE_STAGE_UNSUPPORTED');}}
function structural(s:any,v:any){if(s.anyOf){if(!s.anyOf.some((x:any)=>{try{structural(x,v);return true;}catch{return false;}}))throw Error('INVOICE_OUTPUT_INVALID');return;}if(s.type==='null'){if(v!==null)throw Error('INVOICE_OUTPUT_INVALID');return;}if(s.type==='object'){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==s.required.length||s.required.some((k:string)=>!Object.hasOwn(v,k)))throw Error('INVOICE_OUTPUT_INVALID');for(const k of s.required)structural(s.properties[k],v[k]);}else if(s.type==='array'){if(!Array.isArray(v)||v.length>(s.maxItems??Infinity)||v.length<(s.minItems??0))throw Error('INVOICE_OUTPUT_INVALID');v.forEach(x=>structural(s.items,x));}else if(s.type==='string'){if(typeof v!=='string'||v.length<(s.minLength??0)||v.length>(s.maxLength??Infinity)||s.enum&&!s.enum.includes(v))throw Error('INVOICE_OUTPUT_INVALID');}else if(!Number.isSafeInteger(v)||v<s.minimum||v>s.maximum)throw Error('INVOICE_OUTPUT_INVALID');}
export function validateInvoiceOutput(stage:InvoiceStage,value:unknown,b:InvoiceBundle):any{structural(invoiceStageSchema(stage),value);const v=value as any;if(stage==='investigate'){if(v.requests.some((id:string)=>!b.permittedLookups.includes(id)))throw Error('INVOICE_LOOKUP_DENIED');}if(stage==='draft'||stage==='review'){const r=stage==='review'?v.recommendation:v;const sources=new Set([b.policy.id,...b.invoices.flatMap(i=>[i.sourceId,...(i.creditSource?[i.creditSource]:[])]),...b.evidence.map(e=>e.id)]);if(new Set(r.rows.map((r:InvoiceRow)=>r.invoiceId)).size!==8||r.rows.some((r:InvoiceRow)=>!b.invoices.some(i=>i.id===r.invoiceId)||r.sourceRefs.some(id=>!sources.has(id))||r.decision==='hold'&&r.amountMinor!==0))throw Error('INVOICE_REFERENCE_OR_ROW_INVALID');}return value;}
export function materializePacket(b:InvoiceBundle,r:InvoiceRecommendation):InvoicePacket{validateInvoiceOutput('draft',r,b);const total=r.rows.reduce((sum,row)=>sum+row.amountMinor,0);if(!Number.isSafeInteger(total)||total>b.cashMinor)throw Error('INVOICE_CASH_LIMIT');const register=structuredClone(r.rows).sort((a,b)=>a.invoiceId.localeCompare(b.invoiceId)),remaining=b.cashMinor-total;
 const body={kind:'supplier-release-recommendation' as const,version:'invoice-packet-v1',batchId:b.id,currency:b.currency,register,totalReleaseMinor:total,remainingCashMinor:remaining,exceptions:register.filter(r=>r.decision==='hold').map(r=>({invoiceId:r.invoiceId,request:r.nextEvidenceRequest,owner:r.owner,reason:r.rationale})),memo:`Internal recommendation only. Recommend USD ${total} cents across ${register.filter(r=>r.decision==='release').length} invoices; retain USD ${remaining} cents. ${register.map(r=>`${r.invoiceId}: ${r.decision} ${r.amountMinor} cents. ${r.rationale}`).join(' ')}`,authority:'Exact human approval permits fixture publication only; no payment, supplier contact or account change.'};return {...body,contentHash:hash(body)};}
/** Independent arithmetic/policy checks against public records. Does not author or repair recommendations. */
export function checkPacket(b:InvoiceBundle,p:InvoicePacket){const failures:string[]=[];let rem=b.cashMinor;const expected=new Map<string,number>();for(const i of [...b.invoices].sort((a,b)=>a.priority-b.priority||a.due.localeCompare(b.due)||a.id.localeCompare(b.id))){const receipt=b.evidence.find(e=>e.id===i.receiptSource&&e.invoiceId===i.id&&e.status==='current');const duplicate=b.invoices.some(other=>other.supplier===i.supplier&&other.obligation===i.obligation&&other.id<i.id);const eligible=!duplicate&&i.poMinor===i.invoiceMinor&&receipt?.receivedMinor!==null&&receipt!==undefined;const amount=eligible?Math.max(0,Math.min(i.invoiceMinor,receipt!.receivedMinor!)-i.creditMinor):0;const release=amount>0&&amount<=rem?amount:0;expected.set(i.id,release);rem-=release;}
 try{const normalized=materializePacket(b,{rows:p.register,summary:'Revalidate preserved recommendation'});if(canonical(normalized)!==canonical(p))failures.push('Packet fields/hash differ from authoritative register');}catch(e){failures.push(String(e));}
 for(const i of b.invoices){const row=p.register.find(r=>r.invoiceId===i.id);if(!row){failures.push(`${i.id}: missing row`);continue;}const amount=expected.get(i.id)!;if(row.amountMinor!==amount||row.decision!==(amount?'release':'hold'))failures.push(`${i.id}: recommendation contradicts receipt, duplicate, matching, credit or cash-priority policy`);if(!row.sourceRefs.includes(i.sourceId)||!row.sourceRefs.includes(b.policy.id))failures.push(`${i.id}: missing invoice/policy references`);if(amount&&(!row.sourceRefs.includes(i.receiptSource)||i.creditSource&&!row.sourceRefs.includes(i.creditSource)))failures.push(`${i.id}: missing release evidence`);if(!amount&&(!row.nextEvidenceRequest||row.owner!=='finance-owner'))failures.push(`${i.id}: hold requires next step and finance-owner`);}
 return {ok:failures.length===0,failures,semanticReview:'not established by arithmetic checks',humanCorrectionTime:null};}
