import {randomUUID} from 'node:crypto';
import {mkdirSync,readFileSync,existsSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {StateStore} from '../state.ts';
import {BusinessLoop} from '../business/core.ts';
import type {Brief} from '../business/core.ts';
import {supportBrief,execute,approval,approvePlan} from '../business/support-adapter.ts';
import {open as openWorkflow,workflowScope} from '../workflow/runner.ts';
import {report as workflowReport} from '../workflow/report.ts';
import {hash,identifier,requireThat,scopeKey} from '../contracts.ts';
import type {Scope} from '../contracts.ts';
import {runEvidenceProposal,fixtureEvidencePort} from './evidence.ts';
import type {EvidenceBundle} from './evidence.ts';
import {understandingMock} from './fixtures.ts';
import {invoiceBrief,invoiceLocation,runInvoice,invoiceView,approveInvoice} from './invoice-runtime.ts';
import {invoiceBundle,invoiceWorkerBundle} from './invoice.ts';
import {compareFixtureProcedures} from './comparison.ts';
import {environmentFor} from '../workflow/task.ts';
export class Workbench {
    root:string;store:StateStore;active=new Set<string>();
    constructor(root:string){this.root=resolve(root);mkdirSync(this.root,{recursive:true});this.store=new StateStore(join(this.root,'workbench.sqlite'));}
    close(){this.store.close();}
    scope(id:string):Scope{identifier(id);return {tenantId:'workbench',businessId:id,runId:'business-memory',dataPolicyVersion:'workbench-v1',mode:'fixture'};}
    loop(id:string){const s=this.scope(id);return new BusinessLoop(this.store,s,{id:'local-owner-session',tenantId:s.tenantId,businessId:s.businessId,permissions:['read','operate']});}
    get(id:string){identifier(id);const b=this.store.get('workbench-business',id);requireThat(b,'BUSINESS_NOT_FOUND');return b;}
    save(b:any,patch:any){return this.store.transaction(()=>this.store.put('workbench-business',b.id,{...b,...patch},b._version));}
    create(assignment:string){requireThat(['support','invoice-1','invoice-2','invoice-3'].includes(assignment),'ASSIGNMENT_UNSUPPORTED');const id='B-'+randomUUID().slice(0,8),brief=assignment==='support'?supportBrief():invoiceBrief('AP-00'+assignment.at(-1));const raw=assignment==='support'?environmentFor('W-001').snapshot():invoiceWorkerBundle(invoiceBundle('AP-00'+assignment.at(-1)));const bundle:EvidenceBundle={version:'workbench-evidence-v1',asOf:new Date().toISOString(),purpose:brief.goal,currency:'USD',valueBasis:brief.prioritizationBasis,dimensions:brief.dimensions,allowedTools:[...new Set(brief.opportunities[0].tasks.flatMap(t=>t.tools))],allowedEffects:['lab.publish'],sources:[{id:'authorized-assignment',version:'v1',text:JSON.stringify(raw,null,2),observedAt:'2026-09-11T00:00:00Z',validUntil:null,permission:'worker',rights:'Invented synthetic records; authorized internal fixture only; no customer data or action'}]};
        this.store.transaction(()=>{this.store.put('workbench-business',id,{id,name:assignment==='support'?'Support operations':'Supplier reconciliation',assignment,goal:brief.goal,revision:1,bundle,executionSourceHash:hash(bundle.sources),brief,proposal:null,currentPlan:null,analysisCount:0,history:[],authorship:'Development-assistant authored synthetic source fixtures'},null);this.store.record(this.scope(id),'sources-1','PermittedEvidenceBundle',bundle);});return {id};}
    list(){return this.store.db.prepare("SELECT body FROM entities WHERE kind='workbench-business'").all().map(r=>{const b=JSON.parse(String(r.body));return {id:b.id,name:b.name,assignment:b.assignment};});}
    view(id:string){const b=this.get(id),loop=this.loop(id),plan=b.currentPlan?loop.getPlan(b.currentPlan):null;let view:any={};if(plan?.execution){if(b.assignment==='support'){const r=workflowReport(plan.execution.root),o=r.observations.find((x:any)=>x.runId===plan.execution.runId);const {store}=openWorkflow(plan.execution.root);try{const s=workflowScope(plan.execution.runId),run=store.get('run',scopeKey(s));view={run:o,initialArtifact:run.decision?.draft?.artifact??null,review:o?.prepublicationReview,approval:run.phase==='waiting_approval'?approval(loop,plan.id):null,finalArtifact:o?.artifact,outcome:o};}finally{store.close();}}else{const r=invoiceView(plan.execution.root);view={run:r,initialArtifact:r.initialArtifact,review:r.review,approval:r.approval,finalArtifact:r.finalArtifact,outcome:{checks:r.checks,observation:r.observation,outcome:r.outcome,attempts:r.attempts,providerRequests:0}};}}
        return {business:b,current:loop.current(),proposal:b.proposal?.output??null,proposalAudit:b.proposal?.audit??null,proposalHash:b.proposal?.outputHash??null,assessment:loop.current()?loop.assess():null,plan,feedback:this.store.get('business-feedback',id?('workbench/'+id):''),improvement:b.improvement??null,...view};}
    async act(id:string,action:string,input:any={}){requireThat(!this.active.size,'WORKBENCH_BUSY');this.active.add(id);try{let b=this.get(id);const loop=this.loop(id);
        if(action==='save'){requireThat(b.revision===input.expected,'STALE_BRIEF');const old=b.currentPlan?loop.getPlan(b.currentPlan):null;requireThat(!old?.execution||old.outcome,'FINISH_OR_RESOLVE_EXISTING_EXECUTION');requireThat(typeof input.goal==='string'&&input.goal.length>0&&input.goal.length<=4000,'GOAL_REQUIRED');const bundle=structuredClone(b.bundle);requireThat(Array.isArray(input.sources)&&input.sources.length===bundle.sources.length,'SOURCE_SET_MISMATCH');input.sources.forEach((s:any,i:number)=>{requireThat(s.index===i&&typeof s.text==='string'&&s.text.length>0&&s.text.length<24000,'INVALID_SOURCE');bundle.sources[i].text=s.text;});bundle.purpose=input.goal;this.store.transaction(()=>this.store.record(this.scope(id),'sources-'+(b.revision+1),'PermittedEvidenceBundle',bundle));this.save(b,{goal:input.goal,bundle,revision:b.revision+1,proposal:null,currentPlan:null});}
        else if(action==='analyze'){const attempt='understanding-'+(b.analysisCount+1);const proposal=await runEvidenceProposal(this.store,loop.principal,this.scope(id),b.bundle,fixtureEvidencePort(understandingMock(b.bundle,b.brief)),attempt);this.save(b,{proposal,analysisCount:b.analysisCount+1});}
        else if(action==='accept'){if(b.acceptedProposalHash===input.proposalHash)return this.view(id);requireThat(b.proposal&&b.proposal.outputHash===input.proposalHash,'STALE_UNDERSTANDING_PROPOSAL');const old=b.currentPlan?loop.getPlan(b.currentPlan):null;requireThat(!old?.execution||old.outcome,'FINISH_OR_RESOLVE_EXISTING_EXECUTION');const out=b.proposal.output,brief:Brief=structuredClone(b.brief);brief.goal=b.goal;brief.version='accepted-'+b.analysisCount;const ids=new Map<string,string>();for(const c of out.claims){const cid='analysis-'+b.analysisCount+'-'+c.id;ids.set(c.id,cid);const src=b.bundle.sources.find((s:any)=>s.id===c.references[0].sourceId);brief.claims.push({id:cid,kind:c.kind==='observation'?'fact':c.kind==='estimate'?'assumption':c.kind,statement:c.kind==='observation'?'Source records (not independently established): '+c.statement:c.statement,source:JSON.stringify(c.references),observedAt:src.observedAt,validUntil:src.validUntil,supersedes:[],dimension:c.dimension});}const selected=out.hypotheses.find((h:any)=>h.id===out.selectedHypothesisId);if(selected){const o=brief.opportunities[0];o.diagnosis=selected.diagnosis;o.claimIds=selected.claimIds.map((x:string)=>ids.get(x)!);o.benefit=selected.estimatedBenefit;o.cost=selected.estimatedCost;o.tasks=out.tasks.map(({hypothesisId,acceptance,...t}:any)=>t);}else brief.opportunities=[];loop.revise(brief,loop.current()?._version??null,'Owner accepted a provisional, source-traceable interpretation; not independent truth or causal validation');this.store.transaction(()=>this.store.record(this.scope(id),'accepted-'+b.analysisCount,'OwnerAcceptedInterpretation',{outputHash:input.proposalHash,provenance:'owner acceptance of offline model fixture proposal',independentValidation:false}));this.save(b,{currentPlan:null,acceptedProposalHash:input.proposalHash});}
        else if(action==='plan'){requireThat(loop.current()&&b.acceptedProposalHash===b.proposal?.outputHash,'ACCEPT_CURRENT_INTERPRETATION_FIRST');const planId='plan-'+(b.history.length+1);loop.plan(planId);this.save(b,{currentPlan:planId,history:[...b.history,planId]});}
        else if(action==='run'||action==='approve'){requireThat(hash(b.bundle.sources)===b.executionSourceHash,'EDITED_EVIDENCE_NOT_SUPPORTED_BY_ASSIGNMENT_ADAPTER');requireThat(b.currentPlan,'PLAN_REQUIRED');const p=loop.getPlan(b.currentPlan);if(b.assignment==='support'){if(action==='approve')approvePlan(loop,p.id,input.proposalHash);await execute(loop,p.id,join(this.root,id));}else{const execution={root:invoiceLocation(this.root,p),runId:'invoice-workflow',adapter:'supplier-invoice-v1'};loop.bind(p.id,execution);if(action==='approve')approveInvoice(execution.root,input.proposalHash);const r=await runInvoice(execution.root,p,'AP-00'+b.assignment.at(-1),{seedDraftDefect:true});if(r.phase==='reconciling')await runInvoice(execution.root,p,'AP-00'+b.assignment.at(-1));const final=invoiceView(execution.root);loop.progress(p.id,{state:final.phase==='completed'?'completed':final.phase==='failed'?'blocked':'waiting',checkpoint:final.phase,reason:final.outcome?.failures?.join('; ')??null,nextAction:final.phase==='waiting_approval'?'approve':final.phase==='failed'?'inspect failure; no automatic retry':'report',callsUsed:final.callsUsed,callsRemaining:4-(final.callsUsed??0),pendingEffect:final.phase==='reconciling',pendingModelAttempts:final.pending});if(['completed','failed'].includes(final.phase)&&!loop.getPlan(p.id).outcome)loop.observe({id:'outcome-'+p.id,planId:p.id,executionRef:hash(execution),provenance:'mock',operational:final.phase==='completed'&&final.checks?.ok?'pass':'failed',effectCount:final.observation?.effectCount??0,acquiredEvidence:[{id:'receiving-records',statement:'Permitted missing receiving records retrieved; unavailable entries retained as holds.',source:'invoice.lookup',observedAt:new Date().toISOString(),qualification:'Synthetic fixture only'}],obligations:final.observation?.ledger?.obligations??{currency:'USD',minorUnits:0},costs:[{status:'known',money:{currency:'USD',minorUnits:final.observation?.effectCount===1?25:0},basis:'simulated internal publication'}],independentHumanSeconds:null,semanticAcceptance:'unknown',failures:(final.outcome?.failures??[]).map((symptom:string)=>({symptom,evidence:'invoice workflow persisted result',category:'verification_or_model_failure',hypothesis:null})),digest:hash(final.observation??final.outcome),adapter:'supplier-invoice-v1'});}}
        else if(action==='improvement'){requireThat(loop.current(),'BUSINESS_REQUIRED');const result=await exerciseImprovement(this.root);this.save(b,{improvement:result});}
        else throw Error('ACTION_UNSUPPORTED');return this.view(id);
    }finally{this.active.delete(id);}}
}
async function exerciseImprovement(root:string){const file=join(root,'improvement.sqlite'),store=new StateStore(file);const s:Scope={tenantId:'workbench',businessId:'offline-improvement',runId:'memory',dataPolicyVersion:'v1',mode:'fixture'};const loop=new BusinessLoop(store,s,{id:'test-controller',tenantId:s.tenantId,businessId:s.businessId,permissions:['read','operate']});try{if(!loop.current())loop.revise(supportBrief(),null,'Disclosed synthetic failure for comparison mechanics, not an observed live weakness');if(!loop.getPlan('mock-failure')){loop.plan('mock-failure');const ex={root:'offline-comparison-only',runId:'mock',adapter:'synthetic-support-workflow-v1'};loop.bind('mock-failure',ex);loop.observe({id:'fixture-failure',planId:'mock-failure',executionRef:hash(ex),provenance:'mock',operational:'failed',effectCount:0,acquiredEvidence:[],obligations:{currency:'USD',minorUnits:0},costs:[],independentHumanSeconds:null,semanticAcceptance:'unknown',failures:[{symptom:'Injected fixture handoff omits a required source reference',evidence:'disclosed-fixture-event-1',category:'handoff_loss',hypothesis:null}],digest:hash('fixture'),adapter:ex.adapter});}const baseline=loop.getPlan('mock-failure').team.workers[0].procedure;const candidate=loop.proposeProcedure('source-check','mock-failure','workflow-owner',0,baseline+' Before handoff, explicitly check each retained source reference against the source bundle.','May prevent handoff source loss','Extra tokens or redundant checks');const frozen=loop.freezeComparison('source-check',{model:'offline-fixture',settings:{mode:'mock'},tools:['lab.evidence'],contextVersion:'v1',authorityVersion:'v1',maxCalls:4,maxExposure:{currency:'USD',minorUnits:0},developmentIds:['injected-development'],validationIds:['open-validation'],rubricVersion:'reference-retention-v1',successRule:'No missing required source references and no authority violation; fixture result cannot promote a worker'});const comparison=await compareFixtureProcedures(store,s,baseline,candidate.procedure);return {candidate,frozen,comparison,decision:'mechanics_exercised_only',independentHumanSeconds:null,promotion:false};}finally{store.close();}}
