import {createServer} from 'node:http';
import {randomBytes} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {parseArgs} from 'node:util';
import {Workbench} from './service.ts';
import {VentureWorkspace} from '../venture/workspace.ts';
export function startWorkbench(root:string,port=43129){const app=new Workbench(root),venture=new VentureWorkspace(app.store),session=randomBytes(32).toString('hex'),csrf=randomBytes(32).toString('hex'),base=dirname(fileURLToPath(import.meta.url));const server=createServer(async(req,res)=>{const origin='http://127.0.0.1:'+((server.address() as any)?.port);res.setHeader('cache-control','no-store');res.setHeader('x-content-type-options','nosniff');res.setHeader('x-frame-options','DENY');res.setHeader('content-security-policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; connect-src 'self'");
    try{if(req.headers.host!==new URL(origin).host){res.writeHead(403).end();return;}const url=new URL(req.url??'/',origin);if(req.method==='GET'&&['/','/lab','/app.js','/style.css','/venture.js','/venture.css'].includes(url.pathname)){if(url.pathname==='/'||url.pathname==='/lab')res.setHeader('set-cookie',`midas_session=${session}; HttpOnly; SameSite=Strict; Path=/`);const isVenture=['/','/venture.js','/venture.css'].includes(url.pathname);const name=url.pathname==='/'||url.pathname==='/lab'?'index.html':url.pathname==='/venture.js'?'app.js':url.pathname==='/venture.css'?'style.css':url.pathname.slice(1);res.setHeader('content-type',name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.js')?'text/javascript; charset=utf-8':'text/css; charset=utf-8');res.end(readFileSync(join(isVenture?join(base,'../venture'):base,name)));return;}
        if(!req.headers.cookie?.split(';').some(c=>c.trim()==='midas_session='+session)){res.writeHead(401,{'content-type':'application/json'}).end(JSON.stringify({error:'LOCAL_SESSION_REQUIRED'}));return;}
        const assets:Record<string,string>={'/venture-sample':'sample-site.html','/venture-report':'SAMPLE-REPORT.md','/venture-economics':'economics.csv','/venture-package':'VALIDATION-PACKAGE.md','/venture-buyer-evidence':'BUYER-EVIDENCE.md'};if(req.method==='GET'&&assets[url.pathname]){const file=assets[url.pathname];res.setHeader('content-type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.csv')?'text/csv; charset=utf-8':'text/plain; charset=utf-8');res.end(readFileSync(resolve(base,'../../../../docs/foundry/029/venture',file)));return;}res.setHeader('content-type','application/json');if(req.method==='GET'&&url.pathname==='/api/venture'){res.end(JSON.stringify({csrf,...venture.view()}));return;}if(req.method==='GET'&&url.pathname==='/api/state'){const id=url.searchParams.get('id');res.end(JSON.stringify(id?app.view(id):{csrf,businesses:app.list(),packet:JSON.parse(readFileSync(join(base,'operating-packet.json'),'utf8'))}));return;}
        if(req.method!=='POST'||req.headers.origin!==origin||req.headers['x-csrf-token']!==csrf||!String(req.headers['content-type']).startsWith('application/json')){res.writeHead(403).end(JSON.stringify({error:'ORIGIN_OR_CSRF_DENIED'}));return;}
        let bytes=0;const chunks=[];for await(const chunk of req){bytes+=chunk.length;if(bytes>262144){res.writeHead(413).end(JSON.stringify({error:'BODY_TOO_LARGE'}));return;}chunks.push(chunk);}const body=JSON.parse(Buffer.concat(chunks).toString('utf8'));const result=url.pathname==='/api/venture-action'?venture.act(body.action,body):url.pathname==='/api/create'?app.create(body.assignment):url.pathname==='/api/action'?await app.act(body.businessId,body.action,body):null;if(!result){res.writeHead(404).end(JSON.stringify({error:'NOT_FOUND'}));return;}res.end(JSON.stringify(result));
    }catch(e){res.writeHead(409,{'content-type':'application/json'}).end(JSON.stringify({error:(e as any).code??(e as Error).message}));}});server.listen(port,'127.0.0.1');server.on('close',()=>app.close());return {server,app};}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const {values}=parseArgs({options:{root:{type:'string'},port:{type:'string'}}});const {server}=startWorkbench(values.root??'var/integrated-workbench-029',Number(values.port??43129));server.on('listening',()=>console.log('MIDAS offline workbench: http://127.0.0.1:'+((server.address() as any).port)));}
